### ISSUE TITLE
Дизайн профиля Нарушителей

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#114]
Открыто обсуждение улучшений по "Профилю Нарушителя" 
- Здесь дизайн
- Цвет
- Размер шрифта
- Отступы
- Границы
- Заголовки

Функционал не здесь, отдельно
Спасибо

**Comment by inquisitor6789** [comment]
комментарии админов выровнять по одному краю. Сейчас простые (серые) комментарии выравниваются по левому краю. Все остальные - по правому.

как вариант сделать в виде чата (как в мессенджерах) - свои комменты выравнивать по правому краю, все остальные по левому

**Comment by mj4444ru** [comment]
вроде так и сделано? разве нет?

**Comment by tebaly** [comment]
Нет, не так)
