### ISSUE TITLE
глюк или баг?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#115]
http://freedomsex.net/history/message/98110563/

как видно, решение по данной жалобе было принято 5 дней назад и было решено наказать.
Сегодня я увидел эту жалобу в списке заблокированных сообщений. Причем никакой информации о переносе жалобы в заблокированные нет.
И сбились отсечки времени в разделе "Вердикт"

**Comment by mj4444ru** [comment]
это багоглюк...

и сделал это я
http://freedomsex.net/history/message/98965545/

разработчики, разбирайтесь как у вас жалобы так хитро связаны...

**Comment by tebaly** [comment]
Связаны по _содержанию_
* текст подвергается канонизированию

**Comment by tebaly** [comment]
Проблема должна была уйти с обновлением.
