### ISSUE TITLE
Бездумное голосование

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#117]
http://freedomsex.net/argue/profile/11151035/

http://freedomsex.net/argue/votes/11151035/7/0/
http://freedomsex.net/history/message/98110563/
http://freedomsex.net/history/message/98698274/
http://freedomsex.net/history/message/98665125/
http://freedomsex.net/history/message/98109460/

и вот эти люди не вводят капчу (траст списывает их)

дайте инструмент борьбы с такими...

я предлагаю сделать:
1) если ранг ниже 0, траст не списывает капчи... админы будут сбрасывать ранг в минус для таких...
2) голоса в голосовании от таких личностей не учитывать...

**Comment by tebaly** [comment]
Конечно сбрасывайте рейтинг. 

>  если ранг ниже 0, траст не списывает капчи...

#57 - Особое наказание и модерирование сообщений - Ваша собственная ветка, которая была закрыта решением

> Реализовано 
`$this->moder->getCredit() > 0 and $this->moder->getRank() >= 0`
Возможны комбинации от значений рейтинга и кредитов.

Пожалуйста, "Называете" тикеты в соответствии содержанию. Если выделять темы чётко по их содержанию, будет на много проще находить и закрывать ДУБЛИ предложений/проблем. Потому как вы уже выдвигали подобное обсуждение, и оно было решено

--- 
Сейчас в тикете сразу три идеи
* Бездумное голосование - обсуждение идей
* Идея 1 - если ранг ниже 0, траст не списывает капчи...
* Идея 2 - голоса в голосовании от таких личностей не учитывать...

Смотрите, если сделать три Ветки вместо одной, то:
* Идея 1 - закрывается как дубль
* Идея 2 - обсуждается отдельно (можно скоро закрыть)
* Бездумное голосование - продолжается поиск Идей (пока не будет решена проблема)

Поверьте, так на много удобнее решать и обсуждать проблемы. Например в прошлый раз потерялось одно из ваших предложений #119 из #57

---
Давайте продолжим здесь в ключе "Бездумное голосование - обсуждение идей". 

Остальное 
#118
#119

Спасибо большое за новые идеи #120
