### ISSUE TITLE
Допускаеть ли использование эротических фото из интернета?

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#122]
9.7  Допускается использование эротических фото из интернета без лица в ограниченном количестве. При строгом отношении к Пользователю допускается блокировка при наличии 3-х жалоб. При лояльном отношении к пользователю - более 10 жалоб.

Собственно философия
- Использовать чужие фото запрещено
- Если за _количество_ принимать уникальные фото, то
- Фейк или мошенник может использовать этот пункт, отправляя единственное фото долгое время
- Если факт отправки, то чаcты случаи, когда банить НУЖНО уже при первой жалобе

Пункт в данной формулировке = генератор конфликтов

**Comment by inquisitor6789** [comment]
замечание справедливо, но в соглашении сказано
`Вполне разумна ситуация, когда девушка отправляет обычную фотографию свою, настоящую, а в качестве интимной выбирает подходящее фото в интернете, которое имеет все сходства с "реальностью". Она просто не готова к таким действиям. Если блокировать только за это, можно перебанить массу реальных девушек на сайте. Ну накажите, ну опубликуйте замечание. Блокировка тут неуместна.`

таким образом, конфликт заложен изначально

**Comment by tebaly** [comment]
Ну так сабж

> Допускаеть ли использование эротических фото из интернета?

Закрепляем безусловное использование фейковых фото?

**Comment by Fenslau** [comment]
Смысл блокировки в том, чтобы исключить явных фэйков, которые не преследуют цель знакомства. Как отличить троллей от тех, кто просто стесняется выкладывать свои фото почему то?
Хз. У меня был знакомый пацан. Он короче хотел познакомиться с девушкой. По-видимому во что бы то ни стало. И на сайте знакомств выкладывал не свои фото (он был толстый). Я у него поинтересовался как-то: а в чем смысл? все равно же встречаться и все раскроется. Его ответ меня поразил: "А иначе мне вообще никто не напишет". То есть чувак готов, не думая, пройти хотя бы первую фазу знакомства, а потом мол уже хер с ним, как нибудь. Естественно, он так ни с кем и не познакомился. До встреч доходило, но девушки тупо недоумевали, когда видели несоответствие. И уходили. Так что вариант сравнительно безобидного фэйка теоретически возможен.

**Comment by tebaly** [comment]
> так что ж, перебанить пол сайта?

Закрепляем безусловное использование фейковых фото? - здесь нет ни слова про блокировку :) 

Закрепляем разрешение безусловного использования фейковых фото?

**Comment by tebaly** [comment]
> вариант сравнительно безобидного фэйка теоретически возможен.

На большинстве серьезных сайтов - только реальные фото. Мы тоже так хотели

**Comment by Fenslau** [comment]
В принципе, замечания есть и вроде бы они не зря. и они работают.  Фэйковые фото туда постоянно попадают. Может быть пусть будут? Опять сложно формализовать и различить - зачем пользователи выкладывают фэйк. При чем, такие есть и среди девушек и среди парней. 
Здесь невозможно без эвристики, без оценки человеком этих фото. Некоторые из них явно фэйковые и должны быть как-то наказаны (хотя бы замечанием). Другие.... ну вроде бы и понятно, что не с целью троллинга выложено. И как тут однозначно рассудить? 
+бывает такое, что читаешь замечание, в котором заявлено а фэйке и мол проверено, но ни через яндекс, ни через гугл фото не бьется. Уже сейчас понятно, что этих двух сервисов для поиска фоток не хватает. Как еще искать? Какие варианты?

**Comment by mj4444ru** [comment]
На многих сайтах запрещены чужие фото, но за это никто ни где не блокирует...

Есть ситуации когда девушка скидывает не свою фоту и даже говорит об этом, но на неё поступает жалоба...

По этому моё предложение следующее... Фейковые фото загружать нельзя, но мы за это не наказываем (хотя имеем право)... Но в случае жалобы, мы просто одобряем её и все будут видеть что пользователь отправляет не настоящие фото... А в идеале в случае если пользовательское замечание не проходит цензуру, то добавляем системное замечание типа "Этот пользователь отправляет не свои фото"...

**Comment by Fenslau** [comment]
Тогда давайте в шаблонах комментах изменим ! на нейтральное. По этому поводу. А то я недавно и так лоханулся с особыми, сам того не желая. До сих пор голову пеплом посыпаю.

**Comment by mj4444ru** [comment]
причём тут коммент? не ставьте коммент и всё...
коммент определяет как поступать... не ставьте лишний раз...

**Comment by NeverovI** [comment]
Наказывать за такое не стоит, а вот замечание пусть будет. Каждый сам выберет.

**Comment by tebaly** [comment]
Нет уж. Фейкам бой)) Не хочешь, не загружай. Нечего отправить - не отправляй. Загрузил фейк-фото - наказан или даже в бан. Есть маленькие поблажки для "безличных" фото, в правилах описаны детали.

Какой цели вы добьетесь "всеобщим одобрением" фейковых фото? :confused:

**Comment by NeverovI** [comment]
@tebaly если человек выдает чужие фото за свои или говорит о том, что на фото изображен он, а на самом деле нет, то определенно таких надо наказывать. Это и обман и присвоение авторских прав. Тут даже "отрезание лица" не может идти в рассмотрение. Я говорил о использовании сцен порнофильмов, ведь в правилах не говорится о цели использования, только об ограничении.

**Comment by NeverovI** [comment]
> 9.7 Допускается использование эротических фото из интернета без лица в ограниченном количестве. При строгом отношении к Пользователю допускается блокировка при наличии 3-х жалоб.

Допускается с какой целью? Выдача чужого фото за свое? Это надо пресекать, если доказано, что фото чужое. Если фото уже светилось в интернете, это еще не значит, что оно не принадлежит тому кто его показывает.
Использование в целях дополнительной стимуляции при виртуальном сексе? А почему бы нет?

**Comment by mj4444ru** [comment]
@tebaly, мы люди, а не роботы...  правила - не программа... можно всех виртуалов назвать фейками... надо бороться с троллями и теми кто портит лицо сайта... остальных ТОЛЬКО наказывать...  как всегда настаиваю что за фото нельзя блокировать...

**Comment by tebaly** [comment]
@mj4444ru - где про сцены из фильмов. интересно же :heart_eyes:

**Comment by tebaly** [comment]
https://github.com/freedomsex/docs/tree/master/deal

@NeverovI - неоднозначные и спорные ситуации

> (3) Интимные фото девушки скачены из интернета - блокировать?

> Интимные фото девушки скачены из интернета. Не стоит полагать, что все девушки готовы делать интим фото и отправлять их всем желающим. Вполне разумна ситуация, когда девушка отправляет обычную фотографию свою, настоящую, а в качестве интимной выбирает подходящее фото в интернете, которое имеет все сходства с "реальностью". Она просто не готова к таким действиям. Если блокировать только за это, можно перебанить массу реальных девушек на сайте. Ну накажите, ну опубликуйте замечание. Блокировка тут неуместна.

> У настоящего фейка все фотографии будут фейкофые. Ведь нет резона отправлять обычное фото, принадлежащее другому человеку, скачивать и отправлять обычные фотки из вконтактика. Вот если девушка отправляет обычные фотки, не интимные, и они фейковые, тогда да, с большой вероятностью анкета фейк. Фейки часто скачивают сразу интернет подборку фоток и выдают их за свои.
