### ISSUE TITLE
Нужна помощь в написании Новостей разработки

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#123]
Каждое обновление или новая функция сопровождается заметкой в Новостях разработки. Так получается, что новость об обновлении выходит через месяц после обновления. У многих возникают вопросы по поводу использования нового функционала, так как описание некоторое время отсутствует. Так происходит потому что
- не меньше месяца новые функции проходят обкатку/тестирование
- еще дольше идет сбор статистики по использованию конкретного инструмента 
- после получения данных может быть принято решение об изменении или удалении инструмента

Поэтому _новость_ появляется с лагом по времени. Вы можете помочь в создании и написании _новости_, в её редактировании по мере вносимых в инструмент изменений.

Ветка: https://github.com/tebaly/freedomsex/tree/news

Спасибо

**Comment by inquisitor6789** [comment]
готов помочь при условии оперативного информирования о появлении новой фичи

**Comment by tebaly** [comment]
При закрытии ветки по проблеме, если решением было обновление или внедрение инструмента

**Comment by inquisitor6789** [comment]
если это не было опубликовано в issue?
например как в планируемом http://freedomsex.net/admin/bannam/
могу и не заметить как это запустится

**Comment by tebaly** [comment]
Будет. Как же тестить и обсуждать?
