### ISSUE TITLE
Предлагаю следующий алгоритм по арбитражу

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#127]
Сейчас, на сколько я понял, в арбитраж скидывается всем. И любой может принять решение.
Предлагаю сделать так: Если скидываешь арбитраж на свое же решение (ошибся, хочешь исправиться), то возможно самостоятельное принятие решения. В остальных случаях этот арбитраж показывается только модерам или админам, у которых ранг выше и они решают.  Сейчас это реализовано, но частично. Те, у которых ранг существенно ниже, не могут скидывать в арбитраж решения тех, у кого ранг высокий и решать по ним сами. Но, если тот, у кого ранг высок скинул в арбитраж решение пользователя с более низким рангом, то тот же самый пользователь может самостоятельно принять решение по арбитражу.
Возможно там тоже заложен какой то разрыв по рангу, но так ли это?

**Comment by mj4444ru** [comment]
я уже предлагал пересмотреть эту систему, но не захотели
#2, #23,

**Comment by tebaly** [comment]
@mj4444ru - по вашим предложениям была реализована защита от "сброса в арбитраж" кем попало

В системе должны быть "способы" определить _достойнного_ Администратора. Вы хором предлагаете автоматизировать все процессы по максимуму. При этом возможность определять _адекватность_ Администратора снизится.
* автоматика может определять, кому "дать" Администратора
* мы с вами видим, что _точность_ этого не достаточна

Планировались инструменты, при которых 
* для действий в СБ необходимо участие _человека_
* то есть - _машина_ будет не в состоянии принять верное решение
* по этим действия определять _машинные действия_, и блокировать подобную активность

Таким образом
* у машины может быть строгий аглгоритм на принятие решения
* неадекватный администратор может иметь ошибочное суждение

Если машине, или _неадекватному_ человеку повторно предложить ту же задачу
* машина вынесет то же решение, так как имеет строгий алгоритм, а ИИ еще не придумали
* человек совершит ту же ошибку, так как имеет ошибочное суждение

Только в отличии от машины
* человек в состоянии прочитать комментарий
* машина тоже может, но понять не в силах
* если человек _меняет_ своё решение в верную сторону, значит он на верном пути
* машина не может поменять решения, это будет признаком на "машинальность"
* если человек _не меняет_ своего решения, до него нужно "донести", что он не прав

Таким образом
* появляется возможность вычислять и блокировать попытки внедрения "автоматики" и ботов на уровне СБ
* появляется возможность "сбрасывать" неадекватных Администраторов
* имеются предпосылки к _обучению_ будущих Администраторов

Я уделяю последним трем пунктам серьезнейшее значение, особенно третьему. Вы же предлагаете всё похерить((

**Comment by mj4444ru** [comment]
я предлагал много разных ограничений, но сейчас я обратил внимание на

> Но, если тот, у кого ранг высок скинул в арбитраж решение пользователя с более низким рангом, то тот же самый пользователь может самостоятельно принять решение по арбитражу.

Я предлагал что дважды подрят нельзя вынести одинаковое решение по одной жалобе

**Comment by tebaly** [comment]
> то тот же самый пользователь может самостоятельно принять решение по арбитражу

И? Ну ведь 100500 раз эту тему поднимали

Вариант №1 - ситуация _сложная_ или не однозначная
* администратору производящему сброс крайне рекомендуется указать комментарий-причину сброса
* в арбитраже ВИДЕН комментарий, и его можно прочитать
* модератор, прочитал комментарий, проигнорировал его, и вновь вынес ошибочное решение
* вы вправе СБРОСИТЬ рейтинг модератору

Вариант №2 - ситуация _очевидная_
* администратору производящему сброс НЕ обязатель указать комментарий-причину сброса
* модератор, обязан знать правила принятия решения, если вновь вынес ошибочное решение 
* вы вправе СБРОСИТЬ рейтинг модератору

**Comment by tebaly** [comment]
Назовите мне адекватную причину спора?

**Comment by tebaly** [comment]
> появляется возможность вычислять и блокировать попытки внедрения "автоматики" и ботов на уровне СБ
появляется возможность "сбрасывать" неадекватных Администраторов
имеются предпосылки к обучению будущих Администраторов

**Comment by tebaly** [comment]
появляется возможность "сбрасывать" неадекватных Администраторов **раньше**, чем они наделают серьезных дел

**Comment by mj4444ru** [comment]
сброс рейтинга зло... не надо до этого доводить...

**Comment by tebaly** [comment]
Я вас перестал понимать. Вы предлагаете ему закрыть возможность принять решение, он на чём учиться будет?

> сброс рейтинга зло... не надо до этого доводить...

он сам себя доводит. Никто не говорит вам в минус сбрасывать. Скиньте сотню другую
* он потеряет возможность выносить решения на несколько часов или пару дней
* а как ещё учить то?

**Comment by mj4444ru** [comment]
очень просто, не надо давать доступ к решению по этой же жалобе... когда получит возможность видеть решения, сам всё поймет... это я по себе знаю...
а тупо сброс он может и не поймет что вообще случилось...

сброс я считаю можно применять только в одном случае, когда зафиксировано намеренное вредительство... за ошибки и споры не стоит сбрасывать (в сотый раз наверно уже говорю)...

**Comment by tebaly** [comment]
> а тупо сброс он может и не поймет что вообще случилось...

Система нотификаций всё победит

**Comment by Fenslau** [comment]
Реализовано: Если модер с более низким рангом сбрасывает в арбитраж решение, принятое тем, у кого ранг выше, то это передается на арбитраж, но не всем, а тому, у кого соответствующий ранг.
Тогда почему если тот, у кого ранг выше сбрасывает в арбитраж решение того, у кого ранг ниже, то тот же самый ниже по рангу может вновь принять свое же прежнее решение? Если тут заложен некоторый разрыв по рангу, то это в принципе норм, но нужно обсудить разрывы. Если же вообще ничего не заложено, то нужно заложить. 
Пример: Модер принял решение. Какой-то админ начинающий или помощник сбросил его в арбитраж, но по каким-то причинам не захотел сразу сам принимать решение (допустим даже по принципиальным, хочет отдать всё на суд выше, или же примет его но позже, или сам не уверен, какое решение принять, но то что принято явно неверно) - предложение - запретить тем, у кого ранг ниже сбросившего принимать решение (обсуждаем), ну по крайней мере тому, кто уже принимал это же решение ранее.

**Comment by tebaly** [comment]
>  Если модер с более низким рангом сбрасывает в арбитраж решение, принятое тем, у кого ранг выше

Не сбросит.

**Comment by Fenslau** [comment]
Это я как раз пояснил то, что уже реализовано. И это правильно. Но ниже я привел аргумент. Пример, который относится к той же ситуации, но противоречит ей же. Было несколько ситуаций спорных. Если нужно, приведу ссылку:
http://sexoo.ru/history/message/99598968/
Мне пришло авто в арбитраж (сложно) - что делать. Да, сообщение спорное, но в нем я не увидел оскорбления. Я не поленился, зашел в истории, посмотрел, что ранее аналогичное (вплоть до буквы почти) сообщение было разрешено Сергеем. Отправил в разрешить. 
Тем не менее по вердикту или еще как то, оно оказалось в наказанных. Ладно. Я отправляю это решение на арбитраж с комментом (почему я так поступил: я планировал его просто скинуть в арбитраж и надеяться, что тот же сергей примет решение. Я знаю, что он уже такие сообщения встречал. К тому же, у него больше ранг. ) Тем не менее мы видим, что благодаря моему комменту сообщение разрешил другой модер. 
Что видим позже. Его опять скидывают в арбитраж и сам же он (скинувший) утверждает наказать. С комментами. 
Сколько можно гонять туда-сюда одно и то же сообщение? Я могу конечно снова скинуть его в арбитраж, написать длинный коммент на тему того, что такое оскорбление, а что такое личное мнение и т.п. Но!
Зачем? 
Любой его перекритикует. Я хочу его сбросить в арбитраж сразу далеко наверх. И готов сам не принимать решения по арбитражу. 
Это один пример. Ссылку на другой я уже не припомню, но там вообще все было еще проще. Модер наказал, я скинул с комментом, но без своего решения, тот же самый модер подобрал и снова наказал. Да емнрт.... 
+ Я за последовательность действий. три недели назад разрешили - давайте дальше такое разрешать, что изменилось? 
+ Админ сбрасывает - пусть решает тоже админ.

**Comment by mj4444ru** [comment]
Вот скажите мне, зачем вообще эта двухшаговая вещь нужна? можно же просто взять и поменять решение... Что за изврат такой? Сбрасываешь, бежишь в арбитраж что бы его решить... Почему сразу не переместить? 

Но я считаю это вполне правильно...  К тому же надо запретить принимать решение сбросившему в арбитраж + надо запретить принимать решение тем у кого рейтинг ниже того кто сбросил, за исключением резидентов... Резиденты должны договариваться между собой... В случае если речь идёт о блокировек, конфликт резидентов можно решить только голосованием... Пусть это будет хоть здесь например в виде отдельного топика и сообщений "я согласен с наказанием"... Если 3 админа согласны наказать, то человека наказываем... Опять же, резидент это человек который достаточно важен для системы... Надо обеспечить все условия для мирного уригулирования, а не создания враждебный среды между верхушкой администраторов...

**Comment by tebaly** [comment]
> Сбрасываешь, бежишь в арбитраж что бы его решить...

В таком варианте да, полный идиотизм. В том, который задумывался - администратор, после подтверждения сброса возвращается в списки мониторинга решений. Кроме прочего, администраторам не рекомендуется "принимать решения"(участвовать в арбитраже) по жалобам, в принятии решения по которым они уже участвовали. Можно, но рекомендуется по возможности такого избегать. 

Система арбитража была "переработана". Как таковых "проблем" должно было стать меньше.
* исключена возможность "спора", технически, но по факту осталась
* трактовка "спор крайне не желателен" теперь активирована на уровне автоматики
* таким образом, самих споров со временем должно стать много меньше

Внедрена система "запретить принимать решение сбросившему" - неявно, но она работает.

Предлагаю закрыть этот тикет. Некоторое время взаимодействовать с системой администрирования в новых условиях. По ходу получения новых "данных/ощущений" открывать новые тикеты, если необходимо. Предлагаю вернуться к вопросу спустя некоторое время.

PS Система арбитража была сильно изменена, поэтому обсуждение "в том же ключе" затруднительно.
