### ISSUE TITLE
Предложение навязывать меньше капчи за многочисленные утвержденные жалобы от одного пользователя.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#128]
http://sexoo.ru/userinfo/profile/7463374
Иначе получается немного некорректно. За 4 наказания за жалобы от одного пользователя у человека 60 капч. 251 день анкете как бы. Но когда мы принимаем решения, мы же не можем знать, от одного они были или от нескольких. Да, этот пользователь хам. Но вес жалоб от разных пользователей должен быть больше, чем от одного и того же, если они поступили на несколько почти подряд идущих сообщений.

**Comment by tebaly** [comment]
Всё норм - оскорбления засчитаны по правилам

**Comment by tebaly** [comment]
Опишите пожалуйста ваше видение ситуации. Сколько нужно было начислить?

**Comment by Fenslau** [comment]
Может и правильно... Я сначала думал, что 60 капч одновременно - это уже практически блокировка. Ан нет, он их преодолел.

**Comment by tebaly** [comment]
@Fenslau - перекосы возможны, если заметите что-то похожее, пожалуйста сообщите.
