### ISSUE TITLE
вкладка Голосование для раздела жалоб

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#129]
Пусть сообщения на голосовании будут в разделе Голосование правее бездны с доступом у администраторов
вижу нарушение в голосовалке за которое надо заблокировать, но не могу ничего сделать пока не проголосует народ...

**Comment by tebaly** [comment]
Как назовем?

**Comment by tebaly** [comment]
№2 - не много ли разделов станет во вкладке "Решения" ?

**Comment by mj4444ru** [comment]
Так и назовите, "голосование"...
ну я другого логически правильного места не вижу, может другие что скажут...

**Comment by inquisitor6789** [comment]
на мой взгляд, "голосование" наиболее подходящее название для этого раздела. Только логически его надо не справа размещать, а слева. Хотя это спорный момент

**Comment by mj4444ru** [comment]
сортировка по уровню доступа логичнее

**Comment by tebaly** [comment]
>  не справа размещать, а слева

доступ к ней ограничен - только Админам, а слева специалисты..

**Comment by Fenslau** [comment]
Я согласен, что порой хочется понять, кто же пишет эти сообщения и уже что-то предпринять, но нет возможности. В рамках оперативной борьбы с проститутками и провокаторами, предлагаю раздел назвать "Все жалобы" и оформить его в тех же самых светло-серых тонах, что и бездну. И пихатьтуда весь лог жалоб, но после того, как жалоба попала в какой-либо список, исключать ее оттудова.

**Comment by tebaly** [comment]
* Вкладку "Комментарии" переносим из "Разработчикам" в "Администрирование"
* Кнопку GitHub переносим в футтер или убираем

В разделе "Разработчикам"
* добавляем новую вкладку "Голосование" с вкладками "Открытые", "Бездна" 

"Открытые" - жалобы, по которым еще не принято решение.

**Comment by Fenslau** [comment]
Вкладка комментарии в разделе Админов - вроде бы хорошо. Мы ее немного потестировали, постепенно о ней узнали другие - можно вводить. Вроде бы ничего плохого от ее ведения не случилось.  Хотя думаю, что не все еще знают о ней.. 
Открытые и бездна - тоже хорошо. А, вот. У меня есть сомнение.
В этих открытых по-моему, должны быть только сами жалобы. Без истории решений по ним. То есть сам текст и профиль подозреваемого. Чтобы никто не знал, кто и как проголослвал до него. А то начнутся копирования, подхалимажи, желание вылезть на авторитете другого и т.п.

**Comment by tebaly** [comment]
Давайте оставим для "закрытого раздела" - для системщиков. Как минимум сделать доступ туда резидентам. Но это планы. На уровне админки "открывать" голосование я пока не хочу.
