### ISSUE TITLE
Отображение пола человека в анкете

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#13]
Необходимо отображение пола человека в анкете.
Так же можно добавить поле "знакомлюсь как" с вариантами ответа "м/ж/мм/жж/мж/жм" (естественной основной пол сохранить как сейчас).

**Comment by tebaly** [comment]
Ок. Принято

**Comment by tebaly** [comment]
> с вариантами ответа "м/ж/мм/жж/мж/жм" 

нет, вынужден отказаться от этой идеи - что-то подобное можно указывать в желаниях

> Необходимо отображение пола человека в анкете. 

@mj4444ru - пожалуйста, уточните суть проблемы. Я не совсем понимаю актуальность этого изменения.

**Comment by mj4444ru** [comment]
<img id="human_photo_min" src="/img/icon/contact.jpg">
Сделайте для девочек девочку, для мальчиков мальчика...

**Comment by tebaly** [comment]
@mj4444ru  - натуралам на белом фоне, для трансгендеров что? А трависти, и так далее.. Пусть уж лучше будет это бесполое "оно") - это про картинку. А про пол в анкете, чуть позже. Суть проблемы та же. Предложение открыто, и обсуждается. Спасибо.

**Comment by tebaly** [comment]
Смотреть профили в сторону "Написать/Познакомиться" можно только из поиска, прежде указав кого именно найти М/Ж. В том случае, когда не указано - не суть важно. Поэтому ценность акцента на пол переоценена. Если по имени сложно определить, в анкете есть строка "Я девушка..."

Проект может показаться не "современным", но он однонаправленно заточен на поиск _парнем девушки_, а не наоборот. Поэтому парни пишут, а девушки ожидают сообщения от парней.

**Comment by tebaly** [comment]
#436
