### ISSUE TITLE
фотки в виде недоступных ссылок 

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#130]
http://freedomsex.net/userinfo/profile/?id=11547324
может исправите?

**Comment by tebaly** [comment]
Так то это те же "серые жалобы", и причина "бага" таже

**Comment by tebaly** [comment]
В качестве краткосрочного фикса 
* разрешим все жалобы на фото, без лимитов
* если лимит вводить придется, вернемся к теме

Как решение?

**Comment by mj4444ru** [comment]
норм...
а зачем лимит по фоткам? они ни кого не напрягают, ни где не вылазят...

**Comment by tebaly** [comment]
технический момент

**Comment by tebaly** [comment]
ссылки на фото в сером - это структурная "особенность". Исправлено будет после переработки самого механизма жалоб на фото. Так как изначально такого механизма не было, он существует по сей день как жесточайший костыль приделанный к системе жалоб на сообщения. Сам интерфейс обмена фото выглядит не лучше :persevere:
