### ISSUE TITLE
Не отображается имя если история удалена по сроку давности

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#132]
Если зайти в анкету в публичной части и переименовать её, то через некоторое время когда все сообщения удаляться по сроку давности, имя новое превращается в настоящее... но стоит написать этому пользователю, как переименованное имя возвращается...
вроде раньше этого бага небыло...

**Comment by Fenslau** [comment]
у меня после удаления сообщений по сроку давности, переименование сохранилось.

**Comment by mj4444ru** [comment]
оно сохраняется, но его не видно пока не напишешь...

**Comment by Fenslau** [comment]
http://hdd.tomsk.ru/desk/zonrcntc#
Когда то переписывался с ней. У нее было имя Алёна. И тогда и сейчас в поиске оно так Аленой и отображается. Но по ходу общения выяснилось, что ее зовут Ирина, поэтому я переименовал. Переписка уже удалилась автоматически, а переименование так и осталось.

**Comment by mj4444ru** [comment]
У меня так же было... видимо баг не всегда прявляется...

**Comment by tebaly** [comment]
от количества сообщений не зависит. @mj4444ru это создает проблему сейчас?

**Comment by mj4444ru** [comment]
понятия не имею...  я не знакомлюсь сейчас...  нескем :)

**Comment by tebaly** [comment]
грусть
