### ISSUE TITLE
Особое с особой жесткокостью

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#137]
http://sexoo.ru/userinfo/profile/?id=12534008

Вот объясните с какой целью тут особое?

**Comment by tebaly** [comment]
Объясниет, почему вы считаете иначе?

**Comment by mj4444ru** [comment]
http://sexoo.ru/блог/особое-наказание/

Александр: Что-то я всё равно не понял, почему нельзя давать больше 50 каптч?..
Отправка даже одного сообщения станет практически невозможной. И учитывая, что регистрация на сайте автоматическая, пользователь бросит эту анкету и просто заведёт новую в два клика. Он выйдет из видимого контроля и снова начнёт вредоносную дятельность

**Comment by tebaly** [comment]
Почему тогда вопрос ко мне?)

**Comment by mj4444ru** [comment]
Вопрос не к вам...
Предлагаю обсудить правила дачи особого наказания...
Интересно мнение других администраторов на эту тему...

**Comment by tebaly** [comment]
#86
> После реализации механизма ускорения блокировки установим верхний лимит по капчам

**Comment by mj4444ru** [comment]
спс

**Comment by mj4444ru** [comment]
но всё таки хотелось бы обратится к админам...
не делайте так!!!

**Comment by mj4444ru** [comment]
http://freedomsex.net/userinfo/profile/12466202/
Вот хочется иногда админам особое дать... да штук 100 сразу...

**Comment by inquisitor6789** [comment]
http://freedomsex.net/userinfo/profile/12568165
это автоматика выдает

**Comment by mj4444ru** [comment]
В логе особых видно кто выдаёт...

**Comment by Fenslau** [comment]
http://freedomsex.net/userinfo/profile/12466202/
Вот с этим полностью согласен. Нельзя так. 
Предлагаю повнимательнее относиться к профилям и комментам и проверять их. 
Заодно покаюсь. Сам не так давно выдал целую кучу особых одному стручку, еще и комент написал. Ошибка. Но там ладно, всеравно капчефакер был. Но к анкетам девушек, которые реагируют грубостью на грубость, предлагаю относиться лояльнее в плане особых хотя бы. Бох с ними с наказаниями по регламенту - пусть будут, пока не решим по-другому. Попала в топ, отработала капчи тем более, давайте проверять и перепроверять. Хотя кому я пишу, если бы в этом обсуждении принимали участие все...А так то и так все ясно...

**Comment by tebaly** [comment]
> В логе особых видно кто выдаёт...

24 часа, потом не видно уже
