### ISSUE TITLE
Ошибка в истории жалобы

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#138]
http://sexoo.ru/history/message/99436562/

первый раз я выне решение наказать без блокировки, потом скинул в арбитраж и переголосовал с блокировкой...
а в истории оба раза я за блокировку проголосовал, причём сверху всё правильно показывает.

**Comment by tebaly** [comment]
Этот баг присутствует с самого начала :(

**Comment by tebaly** [comment]
Пересыпал немного историю. Спасибо

**Comment by tebaly** [comment]
Исправлено в новой "версии" админки.
