### ISSUE TITLE
Расширение WOT не пускает на сайт sexoo.ru

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#144]
https://www.mywot.com/ru/scorecard/sexoo.ru?utm_source=addon&utm_content=rw-viewsc

Давайте поднатужимся и всеми админами и модераторами проголосуем за то что сайт хороший...

Разработчики могут попросить администраторов, модераторов, кому не безразлично, помочь в голосовании...

**Comment by tebaly** [comment]
Если у вас получится, напишите им в поддержку. 

> The site does not contain prohibited information. No pornography. No gambling.
sexoo.ru(oesex.ru, qbsex.ru) it is the mirror of freedomsex.net - one Data Base, one server 212.83.133.201

Они просят установить их говноприложение - мне нельзя ставить это на рабочий комп.

**Comment by mj4444ru** [comment]
я не о вас... они не вмешиваются в голосовалку, там всё на основе тупо большенства голосов...
расширение WOT по умолчанию присутствует в ряде браузеров (например yandex браузер)...

**Comment by tebaly** [comment]
> Тем не менее, если вы подозреваете, что с репутацией вашего сайта происходит что-то странное, пожалуйста, **сообщите нам об этом**, и мы исследуем эту проблему.

https://www.mywot.com/ru/faq/site-owners-support/reputation

**Comment by mj4444ru** [comment]
да, надо быть владельцем для этого... я почитал что это значит и врятли это как то особо поможет...
