### ISSUE TITLE
Результат поиска Онлайн

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#15]
Выдавать только пользователей онлайн в результатах поиска при установленной галочке

**Comment by tebaly** [comment]
Галочка бутафорская. Все кто онлайн всегда наверху. Ее не было изначально, и все спрашивали, как искать тех кто онлайн. Прилепили галочку, вопросов почти не стало. Спрашивают только тогда, когда онлайн никого нет. Нужно что-то придумать конечно.

**Comment by mj4444ru** [comment]
Сделайте чтобы работала галочка. Знаете ли визуально высматривать у кого есть значок онлайн, а где он заканчивается тоже напрягает.

**Comment by tebaly** [comment]
Так они ВСЕ вверху - у нас поиск сортируется автоматически каждые 10-15 минут. Поэтому данная опция теряет смысл. Вообще замечание верное, согласен. По схеме "минимум" кликов, необходимо предоставлять "результаты" сразу, без промежуточных ссылок. Предложенное вами решение данную схему нарушает.

**Comment by mj4444ru** [comment]
Тогда хотя бы разделите онлайн юзеров от оффлайн...

**Comment by mj4444ru** [comment]
Так вы тут принципиально против... Не смотря на постоянные жалобы на эту тему... Я думал тема закрыта )))

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/22656320/11e485b0-eca4-11e6-9bff-d0439f05aa4b.png)

**Comment by tebaly** [comment]
аттач #412
