### ISSUE TITLE
Как определить что человек на сайте

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#155]
Давайте вместе придумаем ответ на этот частый вопрос и лишний раз попинаем разработчиков, что бы дату посещения вынесли из анкеты и поместили ниже или правее имени...

**Comment by tebaly** [comment]
А что нас пинать.. Сделаем

**Comment by Fenslau** [comment]
Ох уж эти "вопросы"... ))
Некоторые не в состоянии нажать на анкету (хотя бы одну) и прочитать, как давно была девушка. Они лучше напишут сразу Юлии.
Хоть и есть опыт общения с такими пользователями, иногда не знаешь что отвечать:
Как написать сообщение? - действительно, как же? Ведь только что написал)

**Comment by mj4444ru** [comment]
@Fenslau Сообщение Юле можно написать разными способами (если не ошибаюсь), не только через саму Юлю.

**Comment by Fenslau** [comment]
Через отзывы? Так их найти вроде сложнее, чем открыть анкету. В основном такие вопросы задают те, кто пару часов как создал анкету. Юля им пишет, они не читают и тупят и задают вопросы, типа "Как зайти на сайт". Такое ощущение, что нужно еще пару плашек для таких добавить. 
Это "войти" всех смущает. Но отказываться от этого мне кажется не стоит. Может быть заменить эту надпись на другой текст? Например, "Вы вошли как: Евлампий 59 лет" А когда наводишь на нее, то предлагать что-то еще...

**Comment by inquisitor6789** [comment]
ну да, надпись войти и меня поначалу привела в смущение. Однако я превозмог себя и не стал задавать глупых вопросов :-)
надо с ней что-то сделать

**Comment by Fenslau** [comment]
Всё дело в том, что если взять даже "нормальное распределение", то iq большинства (берем за 100) будет меньше, чем iq разработчиков или админов (которых меньше). А есть ведь еще и те, у которых меньше ровно на столько же. Их немного, но нам кажется, что много, потому что они пишут. Это не столь большой процент от всех, кто приходит, но они есть. Это и есть нормальное распределение. Мы порой не можем понять, где, как, и почему пользователь натыкается на непреодолимую преграду. С одной стороны, сколько бы не улучшал интерфейс, сколько бы ни делал его юзер-френдли, как говорится, найдется энное количество пользователей, которые не разберутся и в этом.
Я не знаю, лично для меня было все понятно с первого дня (в плане интерфейса и юзабилити), единственно, один раз чот подзапутался, не мог вспомнить, где задавать свои предпочтения по возрасту и т.п. поиску. Помнил, что где-то они были, но потом довольно быстро нашел это в "сообщениях" Кого вы ищете?

**Comment by mj4444ru** [comment]
Люди, а вы поспрашивайте у окружающих сколько будет 1/2 + 1/2 и вам сразу будет понятен iq нашей страны... и так в общем то везде наверно...

На счёт кнопки Войти я давно писал. Переименовали бы на кнопку "Сменить пользователя"...

**Comment by Fenslau** [comment]
Вот эта вот кнопка "войти".... Почему-то мне кажется, что менять ее название не стоит. Интуитивно я чувствую, что этого делать не надо.... Объяснить довольно сложно. Что-то в этом есть. Чтобы пользователь не был склонен туда сюда входить-выходить зачем-то. Пусть меняет свою анкету. Предлагаю так: Пусть все отображается как сейчас. Но когда наводим курсор на "Войти", то там отображается подсказка: "<--Вы уже вошли как .Иван 28 лет Москва". и ссылочка на анкету (изменить). Как то вот так это красиво нужно продумать ИМХО.

**Comment by mj4444ru** [comment]
да блин тут как посмотреть...
но думаю тем кто меняют анкеты, им хоть войти, хоть сменить не имеет значение...

**Comment by Fenslau** [comment]
)) да согласен, всеравно будут вопросы вида "я навожу курсор на "войти", а почему (или как) нужно менять анкету?"
Тут бесполезно. Это всегда будет. Я и раньше и сейчас задумывался, нужно ли вообще реагировать на "тупые" вопросы, а самое главное - где грань между тупыми и очень тупыми... Не определил. Наверно придется это все на "естественный отбор" оставить... Но "как определить, что человек на сайте" - пусть будет. Похоже, что это не самый тупой вопрос.

**Comment by mj4444ru** [comment]
а ещё просьбы, найдите мне девушку на вечер для секса...

**Comment by mj4444ru** [comment]
Дубликат #55

**Comment by tebaly** [comment]
не важгно) я закрвываю пачками.

**Comment by tebaly** [comment]
>  попинаем разработчиков, что бы дату посещения вынесли из анкеты и поместили ниже или правее имени...

#434 - в анкете _правее_ города в самой первой строке
