### ISSUE TITLE
Информация в профиле

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#159]
http://sexoo.ru/userinfo/profile/?id=11691536
http://sexoo.ru/userinfo/profile/?id=12391363
Чот недопонл, как так Жалоб сегодня 0, всего 0, долг 0 капчи.
Или это не сразу обновляется?

**Comment by Fenslau** [comment]
Прибавилось с тех пор ) но только не в статистике количеств) 
Так и не исправили?

**Comment by tebaly** [comment]
Нет) Проблема же открыта еще.

**Comment by tebaly** [comment]
Эммм. Даже не знаю. Количество жалоб - "счетчик" - обнуляется при "хорошем поведении" автоматически. Возможно это тот случай
