### ISSUE TITLE
значёк Онлайн в анкете

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#16]
Очень часто спрашивают как определить пользователь онлайн или нет.
Значок онлайн необходимо сделать в не сворачиваемой части анкеты, желательно зелёным, а в противном случае значок оффлайн красным.

**Comment by tebaly** [comment]
Ок. Интерфейс будет полностью переписан, все ваши замечания по части юзабилити и дизайна будут учтены.

**Comment by Fenslau** [comment]
Можно градацию небольшую по цветам, в зависимости от срока давности

**Comment by tebaly** [comment]
изменено. позже вероятно сделаем его ярче
