### ISSUE TITLE
Ввести пограничный маркер "двусмысленное содержание" для жалоб

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#168]
- разрешено-вирт
- разрешено-наказать
- наказать-блокировать
- наказать-вирт
- вирт-блокировать
- и т.д.

**Comment by Fenslau** [comment]
А что же на основании его потом предполагается делать? Боюсь, что таких будет очень много, что несколько всё усложнит и запутает.

**Comment by tebaly** [comment]
Вручную оценивать...

**Comment by Fenslau** [comment]
И все будут кидать в эти непонятки всё подряд. Я конечно против этих бинарных оценок. Но иногда это полехно. Грань надо просто чувствовать и установить на уровне регламента. Сейчас обратная связь с модерами работает на основании ошибок. А так они просто будут делать эти непонятные оценки - ни туда ни сюда, и все испортится.

**Comment by tebaly** [comment]
> А так они просто будут делать эти непонятные оценки - ни туда ни сюда, и все испортится.

За последние полгода было _достаточно_ инцидентов, в которых _сложные_ ситуации намеренно эксплуатировались для создания конфликтов, и в иных целях. С этим нужно что-то делать

**Comment by Fenslau** [comment]
Есть кнопка "пропустить" для тех, кто не уверен. Кстати, она во всех случаях есть?
Сложные ситуации будут. Сейчас уже комменты реализованы - уже проще. Не смотря на то, что порой эти же комменты становятся площадкой для выяснения отношений между администраторами ) Но мне кажется, что этого не избежать)

**Comment by Fenslau** [comment]
Я как раз кстати недавно думал об этом. И пришел к выводу, что такое нельзя внедрять. 
Потому что на всех этих разногласиях и взаимных ошибках происходит обучение новичков, да и истина порой рождается. 
Не будем внедрять "ни рыбу не мясо", это повредит. Нужно просто выбрать что-то одно и все. Дальше жизнь сама все расставит на свои места. Новички (думающие) будут пропускать то, в чем они не уверены и потом смотреть, что решилось, сравнивать со своим мнением (а это и правильно). А старики будут принимать решения так или иначе - через споры, мнения. 
Петля гистерезиса опять же. пограничные случаи так и останутся пограничными. Но те из них, что склоняются в сторону + - со временем будут обретать положительную окраску, если у вас там эвристика задумана.

**Comment by Fenslau** [comment]
Кстати, хотите или нет, но регламент устарел. Местами. Примеры уже неактуальны. А мне говорили, что ориентируются на это. Там в частности упоминаются примеры, за которые стоило бы наказать, но. РЕАЛИИ показали, что это нормально. По крайней мере мат допустим, если это не оскорбление. А в регламенте грубые матерные выражения без личных обращений тем не менее рекомендуется наказывать. Это непорядок. Надо исправить. 
Если нужно, я могу заморочиться и все их выложить.
