### ISSUE TITLE
Сделать отдельную панель помощи с преферансом и мадмуазелями

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#177]
Полностью изолированную от административного интерфейса панель Помощи со своим собственным рейтингом, званиями и достижениями. 

---

Обсуждение

**Comment by Fenslau** [comment]
Мое ИМХО: на данный момент будет почти никому не нужно. А вот если сперва на определенное количество повысить онлайн и заинтересованность пользователей проектом, то многих будет не оторвать от этой фишки.

**Comment by inquisitor6789** [comment]
И что это будет такое? Своя отдельная песочница?

**Comment by tebaly** [comment]
Типа. Как мы уже поняли, нередки случаи, когда администратор использует статус администратора, чтобы гадить в "Помощи".

**Comment by Fenslau** [comment]
Так мы же вроде бы это теперь контролируем с помощью логов ответов. А так начнутся новые злоупотребления. Если только не продумать, как это сделать (на первых этапах модерировать ответы?) Идея с рейтингами, званиями и достижениями - очень хорошая! Это всегда стимулирует юзеров. Но и у админов нельзя полностью эту фишку забирать, бывает так, что ответить могут только они... 
Вообще идея с точки зрения повышения лояльности некоторых пользователей - очень хорошая. Додумать ее надо.

**Comment by tebaly** [comment]
> Но и у админов нельзя полностью эту фишку забирать

и 

> Додумать ее надо.

Надо)
