### ISSUE TITLE
Верхнее меню

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#18]
Некоторые люди не видят верхнее меню, часто спрашивают "как искать", "как поменять имя", "как изменить анкетные данные"...

Гид по сайту пишет слишком много, скорее всего большинство этого просто не читает из за количества текста. Многие готовы переварить максимум первые 2-3 строчки текста. Как вариант можно как то подсказки разбить на более мелкие кусочки.

**Comment by tebaly** [comment]
Не видят в смысле не замечают?
Подобные вопросы были и будут всегда. Не реже спрашивают как создать емаил - это не повод  отвечать на подобные вопросы, если вы об этом.

**Comment by mj4444ru** [comment]
Да вот недавно писали в ТП типа ваш дизайн бомжи делали. Всё таки как то надо заняться дизайном чтобы было понятно где меню, где реклама, а где информационные сообщения на которые стоит обратить внимание.

**Comment by tebaly** [comment]
Точно такое же меню у Вк и Фэйсбука и твиттеки и т.д. - синяя строка вверху экрана с элементами навигации. Надеюсь хоть в этих компаниях дизайнеры не бомжи, своих то мы бережем :)

**Comment by mj4444ru** [comment]
В контакте в новом дизайне в верху экрана больше нет навигации.
Я бы не один из этих дизайнов не сравнил с вашим.
А можно увидеть хотя бы макет вашего нового дизайна? если конечно вы не планировали оставить в новой системе прежний дизайн.

**Comment by tebaly** [comment]
Оставим как было)) фейсбук и твиттер вы намеренно проигнорировали?)

**Comment by mj4444ru** [comment]
Дизайн фейсбука у меня кроме негатива ничего больше не вызывал, да и кроме знакомых блогеров там никто не сидит (кстати я интересовался, у других он тоже восторга не вызывает).
Твитером никогда не пользовался, по этому не могу ничего про него говорить.

Не отрицаю, в текущем дизайне есть много хороших вещей, в том числе для удобства, но он очень непонятен в плане восприятия и понятности.
Вот даже кнопка пожаловаться с телефона со второго раза нажимается, а до этого ещё как то допереть надо.

**Comment by tebaly** [comment]
Но в верхнем меню нет кнопки пожаловаться :)
--
По части навигации есть три элемента:
- Поиск
- Сообщения
- Настройки (Анкета)

Ради только этого выводить целый сайдбар? Просто опишите/нарисуйте ваше видение навигации/меню. Так нам будет проще понять суть проблемы. Для себя мы копировали это меню(элементы) у озвученных сайтов..

**Comment by tebaly** [comment]
лучше не станет
