### ISSUE TITLE
Рейтинг модератора сделать публичным

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#181]
Информацию о конкретном значении Рейтинга сделать публично доступной. Надо ли?

**Comment by Fenslau** [comment]
Идея интересна. Это точно. Я это говорю не просто так, а сразу же вспомнил про тот самый проект, с которым я уже здесь всем проел плешь. Там была возможность отображать не то что бы конкретный рейтинг, а "уровень" - все равно что звание здесь. Но только по желанию пользователя. Кто-то хотел этого и отображал, кто-то наоборот, скрывал. 
Здесь я боюсь высказать однозначно положительное мнение, мол "отображаем по тому же принципу", потому что кроме плюсов (повышение лояльности пользователей-модеров), я чувствую некоторые минуса. Вот какие конкретно - предлагаю за меня сказать более опытным администраторам.

**Comment by inquisitor6789** [comment]
может вместо рейтинга отображать ачивки?
на счет минусов я вижу только злоупотребление этим статусом. Это есть и сейчас, но проверить это могут только админы. Если же сделать ачивки публичными, то заявления типа "я модер я тебя сейчас забаню" будут звучать смешно для уровня, скажем, мастер1.
Конечно же отображение ачивок надо сделать с пояснениями что они означают (вроде есть статья на гите).
Под ачивками я понимаю не только статусы страж, инквизитор, гуру и т.п., но и звания - доброволец, мастер и конечно же администратор :-)
Опционально можно показывать резидента

**Comment by Fenslau** [comment]
Ачивки и звания нужны тем пользователям, которые давно здесь. Или недавно, но планируют развивать свою анкету, не бросать ее. Это здорово повысит "лояльность". Пользователь захочет вновь заходить на сайт и делать что-то полезное. Наверно нужно придумать ачивки и для девушек. отдельные. Конечно сразу все это им всем не объяснишь, особенно в одном сообщении-баннере, Не хватает онлайна немного. При более высоком онлайне эта идея проявила бы себя по-полной. Юзеры и юзерши по сарафанному радио поняли бы, что означают эти все ачивки и продолжали бы сидеть только ради них.И увеличения их.

**Comment by inquisitor6789** [comment]
предлагаешь сделать их в розовых тонах с бабочками? :-D
на счет оповещения можно наверно организовать оповещение от Юли всем пользователям. И конечно же сделать ссылку на статью (типа "что это") рядом с ачивками.
С моей т.з. не обязательно иметь высокий онлайн. Все таки сайт создавался для быстрых знакомств. Если юзеру интересно модерство, то он останется на долгий срок. Иначе никакими плюшками кроме реальных денег его тут не оставишь.

**Comment by Fenslau** [comment]
Сайт создан для быстрых знакомств. Вот это вот и хорошо и плохо одновременно.... Почему?
На таких сайтах всегда был и будет дефицит девушек. И огромный же дефицит адекватных парней. С помощью плюшек (представим, что они уже внедрены), мы повышаем онлайн тех именно пользователей, которые адекватны. Они сегодня зашли на сайт (с определенной целью), у них не получилось, но в общем то это неплохие пользователи. Мы их удерживаем какими то способами, а завтра они служат основной идее сайта.

**Comment by inquisitor6789** [comment]
да я не ставлю под сомнение, что всякие плюшки могут повысить онлайн. Весь вопрос в реализации

**Comment by Fenslau** [comment]
Такие темы нужно после одобрения разработчиками помещать в какой-то особый раздел, где те, кто предлагал одобренные плюшки - помогал бы их реализовывать, хоть кодом хоть подсказками/мнениями. Я так думаю.

**Comment by tebaly** [comment]
> (представим, что они уже внедрены), мы повышаем онлайн тех именно пользователей, которые адекватны

Мы с вами будем править интернетом после этого :)

**Comment by tebaly** [comment]
> Все таки сайт создавался для быстрых знакомств. 

В идеале 1-3 дня. Если имелось в виду "оставить на сайте" адекватов подольше (15-45 дней) - то это несколько противоречит идее. Мы не имеем ни малейшего желания удерживать Пользователей после того, как они с кем-то _познакомятся_. Смысла нахождения на сайте для них уже просто не будет(в иных случаях, например _отношения_, это даже не рекомендуется). Такие пользователи вернутся на сайт, как только им нужно будет _познакомиться_ снова, ведь в предыдущий раз у них всё получилось.

**Comment by tebaly** [comment]
> Юзеры и юзерши по сарафанному радио поняли бы, что означают эти все ачивки и продолжали бы сидеть только ради них.И увеличения их.

Пробуем внедрять. Рейтинг сам по себе является _сильной_ ачивкой. Отсюда и тема. Стоит ли?

**Comment by inquisitor6789** [comment]
> Стоит ли?

да, однозначно. Только над видом подачи стоит подумать

**Comment by Fenslau** [comment]
_Мы не имеем ни малейшего желания удерживать Пользователей после того, как они с кем-то познакомятся._
А почему? может быть пользователь хочет познакомиться сегодня с одной а завтра с другой? Может быть это вообще вирт-знакомство, которых может быть очень много.

**Comment by tebaly** [comment]
Так это уже частное от общего :)

**Comment by tebaly** [comment]
Обсудили
