### ISSUE TITLE
Цели сайта и истинное положение дел.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#190]
Всем привет.
С точки зрения разработчиков - цель сайта - чтобы пользователи находили секс-знакомства и через 1-3 дня уходили. Это по некоторым причинам нереально. Мало девушек, мало адекватов. Возможно, некоторые так и делают, но вот что я успел понять за свой недолгий онлайн и общение здесь:
+девушки, которые ищут на 1-2 раза продолжают сидеть здесь. Ищут еще. 
+у некоторых не получается найти, но они все сидят и сидят. Хотя им и скучновато.
+некоторые ищут дрочки в скайпе и находят ее (да, да, такое бывает).
+некоторые просто общаются, используя этот сайт на постоянной основе, хотя это и странно.
Нужно весь этот онлайн поддержать и задержать. Они ничего плохого не делают.

**Comment by tebaly** [comment]
При более широком взгляде, не существует такого понятия, как _секс-знакомства_. 
* любое знакомство парня и девушки приводит к сексу, либо имеет такую цель 
* выражение "не бывает дружбы между мужчиной и женщиной" основано именно на этом
* примите во внимание также существование "секса по дружбе" 

> Нужно весь этот онлайн поддержать и задержать. Они ничего плохого не делают.

= некоторые ищут дрочки в скайпе и находят ее
* мы их сюда не зовем, всячески намекаем им, что здесь не лучшее место для этого, и задерживать тут их, уж простите, не имеем никакого желания.

= некоторые просто общаются, используя этот сайт на постоянной основе, хотя это и странно
* я понимаю, что меня сложно понять, но, некоторые фундаментальные причины не позволяют сесть попой проекта сразу на два стула. Проект _можно_ использовать сугубо для общения. Мы стараемся всё наладить конечно, но 
* на сегодняшний день, длительное нахождение и общение на сайте не приводящее к реальному знакомству, способствует накоплению жалоб, замечаний и общего негатива вокруг анкеты.
* написано - _быстрые знакомства_ - и когда пользователь обнаруживает "я просто общаюсь тут" - это приведет и к жалобе и к замечанию. Я думаю у нас не получится повлиять на это. 
* мы не планируем хоть как либо влиять на _личные воздействия_ Пользователей в будущем. Поэтому жалобы и замечания будут поступать и дальше.

**Comment by Fenslau** [comment]
А вы не хотите расширить цели проекта? Без какой-либо широкой огласки. Ведь некоторым анкетам годы... Что-то же они здесь ищут. Некоторые из них вполне нормальные пользователи и это не админы, их мы не учитываем. 
+ не бывает дружбы между мужчиной и женщиной. - Это я всегда говорил, очень легко проверить представим: - не будет дружбы между двумя геями, если каждый из них свободен. Им не за чем "дружить", они будут трахаться! Общность интересов при правильной ориентации - это приводит к сексу. Но не все, даже те, кто на этот сайт приходит, сразу готовы к такому, особенно девушки. Они хотят осмотреться. А некоторым достаточно просто самой возможности, флирта даже какого-то. На грани. Ну напишут на нее замечание "не дает". Да, ужасно конечно )) Но она создает реальный онлайн. Этому не дала, а другому возьмет и даст! Правильный подход и всего делов.
Как таких "теплющихся" задержать здесь?

**Comment by Fenslau** [comment]
> на сегодняшний день, длительное нахождение и общение на сайте не приводящее к реальному знакомству, способствует накоплению жалоб, замечаний и общего негатива вокруг анкеты.
> написано - быстрые знакомства - и когда пользователь обнаруживает "я просто общаюсь тут" - это приведет и к жалобе и к замечанию. Я думаю у нас не получится повлиять на это.
Рассмотрим реальный пример:
Девочка 16-22 двух лет. Она не хочет встречаться или даже виртить с кем-то, у нее нет опыта, но есть желание его получить. Она этот опыт начинает получать через общение - и что она видит - явный негатив от "пользователей" - парней, которым видите ли не сразу отсосали/дали. При этом, учитывая ее желания в анкете, становится понятно, что все зависит от подхода к ней. Нормальный подход = нормальное развитие знакомства. 
Или же наоборот, женщина в возрасте просто хочет немного, как говорится, развеяться. И тем и другим нужно внимание для начала, но правильное. То, которого они ожидают. Эти девочки представляют собой "хороший онлайн". Но они уйдут, если подумают, что на этом сайте лишь одни стручки, которые шлют фото члена. 
Нужно их как-то завлечь. Во всю эту круговерть.  Потому что настоящих оторв, которые пришли сюда ради списка наиболее популярных желаний среди пользователей - единицы, но они приходят, это я вижу. но быстро сливаются. Хотя у них есть потенциал.

**Comment by inquisitor6789** [comment]
Кроме того, если будут сидеть тут только 2-3 дня, то возникает вопрос - как монетизировать таких пользователей кроме как показом банеров?

**Comment by tebaly** [comment]
> И тем и другим нужно внимание для начала, но правильное. 

Дежурная цитата: - "Общение на сайте никого и не к чему не обязывает. Сайт не меняет реальности, здесь те же люди, с теми же желаниями и ожиданиями."

Именно, внимание и аккуратность при начале общения важны, но это игнорируется массой.

**Comment by tebaly** [comment]
* потому что настоящих оторв, которые пришли сюда ради списка наиболее популярных желаний среди пользователей
* Кроме того, если будут сидеть тут только 2-3 дня, то возникает вопрос

Мать моя женщина, хорошо что вы не знаете планов на ближайшее будущее..
* реализация концепции _гиперчата_ - суперскоростного общения

И если это будет получаться
* оборот сообщений вырастет в несколько раз
* поток кратно жалоб увеличится*

* мы запланировали алгоритмы, которые позволят уменьшить или не допустить линейного увеличения потока жалоб.

**Comment by tebaly** [comment]
> как монетизировать таких пользователей кроме как показом банеров?

мы нацелены на уход от этого вида монетизации

**Comment by Fenslau** [comment]
Да, здесь те же самые люди, что и в жизни - это как раз ответ на вопрос большинства вопрошающих к юлии "что же я делаю не так" - да блять - в реале ты свой хуй всем подряд не показываешь - вот что ты делаешь не так ))) А если бы показал, то понял бы, что ты делаешь не так)))
Перефразирую:
Здесь так же как в жизни. Все хотят секса. Кто-то в большей степени, кто-то в меньшей. 
Но у парней замылился подход. Они считают что этот сайт для секса в такой степени, что стоит только показать и сразу же на них должны запрыгнуть. Этого не будет нигде, даже вспомнив всем известный анекдот про женскую колонию и парня с кучей освобождений )))
Здесь и так уже довольно таки все просто. Да, здесь есть контингент соответствующий (он кстати уже есть из девушек). И есть все инструменты, чтобы найти девушку для секса,.  Но им все мало. Им нужно чтобы это происходило автоматически, а это вот уже не так и не правильно и нигде и никогда не будет )

**Comment by Fenslau** [comment]
Поэтому сюда будут и будут заходить дрочеры (в плохом смысле слова). Это да. И девушки будут. 
Что нужно: Чтобы девушки остались, а спамеры, которые считают, что им дадут по одному сообщению, поуходили. тогда все будет хорошо.
Мне тут трудно судить, потому что я не особо часто общаюсь не в формате анкеты, а если отказывают, то ну и ладно.  Считаю что такое допустимо. И к тому же, большинство девочек реально устало от дрочеров, от которых и толоку то нет. Но тем не менее ни разу я не наблюдал оскорбления в свой адрес.

**Comment by tebaly** [comment]
> Но им все мало. Им нужно чтобы это происходило автоматически

Это цель проекта, она достижима. Главное верить :)

> И к тому же, большинство девочек реально устало от дрочеров, от которых и толоку то нет. 

Отправлять письки всем подряд запрещено)

---

Вы всё верно говорите.
