### ISSUE TITLE
Движение жалоб по голосовке

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#199]
Иногда почему-то с момента подачи жалобы и принятия кем-то первоначального решения и до появления её хоть в каком-нибудь из списков (или на следующем этапе голосовки), проходит очень много времени.
Пример:
http://sexoo.ru/history/message/103557550/
http://sexoo.ru/history/message/103697308/
http://sexoo.ru/history/message/103684059/
http://sexoo.ru/history/message/103693631/
Видимо это из-за "авто, сложно"... 
Где-то уже кто-то предлагал сделать возможность то ли какой-то лог просматривать по всем жалобам (например для оперативных блокировок анкет), то ли как-то еще: https://github.com/freedomsex/freedomsex/issues/129

**Comment by tebaly** [comment]
Да. Всё верно. При расхождении "общего" мнения в голосовании, процесс принятия решения может затянуться.
* для оперативных блокировок анкет

Да. Обсуждение замерло на определении логического "места" такого раздела администрирования. Если вы согласны с тем, что обе темы похожи, давайте продолжим в той ветке. 

#129

Спасибо.
