### ISSUE TITLE
Содержание замечаний.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#200]
Иногда замечание верно только наполовину. Или в нем используется слово, которое нежелательно к публикации. При этом сама суть верна. Чтобы не было этих мучительных дилемм - публиковать/не публиковать, может сделать возможность отправки автоматической рекомендации (например от лица Юлии) пользователю, чтобы он скорректировал текст? Можно даже просто со стандартным текстом, где были бы разъяснены основные ошибки вкратце и что нужно переделать.

**Comment by tebaly** [comment]
Да. Идея очень хорошая. Здесь нужно серьезно подумать. Возможно нужен какой-то новый механизм. Возможно нет.

Давать ли возможность опубликовать замечание администраторам?
* есть некоторый неявный "сдерживающий" механизм, позволяющий уменьшить вероятность "засорения" потока замечаний
* он выражен в том, что нужно для начала начать общаться, дождаться ответа, пожаловаться, и только потом появляется возможность* отправить замечание

Получив доступ к админке, злоумышленник сможет отправлять и публиковать замечания "вольного" содержания, либо "сложные" в подтверждении замечания, для создания конфликтных ситуаций, либо с иным умыслом(возможно). Сейчас есть хотя бы вера в то, что собеседнику некоторые моменты более очевидны.

**Comment by tebaly** [comment]
Давайте подумаем, как может выглядеть реализация.

**Comment by tebaly** [comment]
Мой вариант
* открываем возможность публиковать замечания администраторам
* содержание замечания на общих правилах
* без введения новых элементов типа "от администратора" или "замечание администратора" 
* пользователь не видит разницы между "обычным" замечанием и замечанием "администратора"

Возможно нужно ввести метку типа "от администратора", но только на уровне интерфейса администратора.

**Comment by Fenslau** [comment]
Я - за то, чтобы не переделывать оригинальный текст замечаний. Все-же пусть они будут от пользователя. А админы их будут или принимать или не принимать. Я предлагаю в интерфейс принятия решений по замечанию добавить ссылку "переписать" (название можно и другое) - смысл ее будет в том, что при ее нажатии, пользователю, который написал замечание, оправляется от Юлии следующий текст (корректируем): "Здравствуйте, вы хотели написать замечание на пользователя ххх. Но текст самого замечания не соответствует правилам сайта или же содержит излишнюю информацию, или же вы не подкрепили замечание достаточным количеством фактов. Рекомендуем вам переписать текст замечания и отправить его заново. _Здесь_  можно посмотреть типичные ошибки при составлении замечаний. _Здесь_ - это будет ссылка, по которой вкратце будут объяснены все основные ошибки:
Мат в замечании
Диагнозы в замечании
Надумывание (пример: фото фэйк, наверно это мужик, не отправляет фото взамен, не знает чего хочет, и т.п.)
Так же по этой ссылке будет текст правил оформления замечаний. 
Раньше я иногда сам общался с теми, кто решил что-то такое о ком то опубликовать и разъяснял им правила, но это утомительно. Да и пользователи порой ведут себя некорректно, начинают прогонять по голосовке мои сообщения или еще что-то неадекватное делать.

**Comment by Fenslau** [comment]
Дополнение:
К сожалению НЕ ВСЕ!!! админы, почему-то, участвуют в гитхабе, поэтому придется для них сделать баннерок - или как там лучше это описать - подсказку, которая всплывает, при наведении курсора на ссылку "переписать", мол, сделана она для тех пользователей, чье замечание верно, но некорректно написано.

**Comment by inquisitor6789** [comment]
Не удобно с мобилы писать тут что-то. Я знаю админов которые только читают.
Тем паче, что участие тут сугубо добровольное.
А может просто они не знают

**Comment by inquisitor6789** [comment]
По теме - вариант с "переписать" как мне кажется не сработает. 
Возможно при отклонении замечания имеет смысл слать от имени юли сообщение что-то типа "ваше замечание отклонено в связи....". Где .... - набор типичных ошибок в составлении замечания.

**Comment by Fenslau** [comment]
дык я это и имел виду. только слать это пользователю не по "отклонено" (а то по всем отклоненкам заколебут переписыванием), а добавить ссылку "переписать" - для тех случаев, когда и правда переписать стоит.

**Comment by inquisitor6789** [comment]
Ок. Можно и так

**Comment by tebaly** [comment]
> пользователю, который написал замечание, оправляется от Юлии следующий текст (корректируем): "Здравствуйте, вы хотели написать замечание на пользователя ххх. Но текст самого замечания

Хотим таки реализовать систему "Уведомлений" (ранее такого вида обратной связи делать не планировалось). Таким образом, при отклонении замечания - отправлять пользователю уведомления 
* замечание отклонено

Но этого всего делать не обязательно. Дело в том, что Пользователь подает "сигнал" администратору, что с этой анкетой что-то не ладно. Сами замечания _анонимны_. Поэтому можно не делать "уведомлений", а заиметь возможность 
* добавить замечание администратором

Сам администратор сможет либо исправить полученный текст, либо написать полностью новый. Исходный текст Пользователя останется отклоненным.

**Comment by Fenslau** [comment]
Вот сейчас недопонял. Исходные текст пользователя будет отображен вместе с текстом, который откорректировал админ? Это неплохо. И решает ту проблему, которая была. Но опять же, что делать с теми текстами пользователя, которые через чур экспрессивны и не годятся для публикации?

**Comment by tebaly** [comment]
> Вот сейчас недопонял. 

Не, всё не так) Всё будет как есть сейчас, просто у вас будет возможность написать замечание "от себя" а для облегчения процесса:
* будет возможно скопировать отклоненный текст, и затем отредактировать его
* такое "отредактированное" замечание будет опубликовано, а исходное останется в списке отклоненных.

> вроде бы противоречит идее?

В целом да, но сейчас уже нет.. Доверие к коллективу администраторов, по сравнению с тем, которое было год-два назад, значительно возросло. Команда администраторов показывает высокую сплоченность и справедливость в принятии решений. 

> При этом будет понятно, что это не пользовательский текст. 

Вероятно будет именно так.

**Comment by tebaly** [comment]
Более не актуально. Мы уходим от публикации/модерации замечаний. В сторону публикации фиксированных текстов. Отправлять можно будет по прежнему что угодно.


![image](https://cloud.githubusercontent.com/assets/9466814/22229028/38bb4264-e1e6-11e6-82b9-ea4a93de2d95.png)
