### ISSUE TITLE
Глючок с фотками

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#201]
Короче, как говорится, скорее баг, нежели фича:
Допустим общался кто-то с кем-то. Было выслано фото. А потом удалено пользователем, который его высылал, удалено просто из переписки, но не из галереи своей. Но. Если зайти в анкету то справа от имени будет маааленькая иконка этого фото. и если на нее нажать, то фото откроется в полном размере.

**Comment by tebaly** [comment]
Да. Всё верно. Это недочет системы обмена фотографиями
* если отправить фото, а затем удалить _загруженную_ фотографию, то так не выйдет
* при удалении фото из переписки, удаляется только сообщение с фотографией

Это уже устоявшееся поведение скрипта, многие к этому привыкли, и замечены попытки _эксплуатировать_ данный баг. Надо будет поправить это поведение, но это не получится сделать быстро. 

Спасибо

**Comment by tebaly** [comment]
Переведеное из багов в фичи. 
* при удалении фото из переписки, удаляется только сообщение с фотографией
* для удаления того, что отправилось - нужно удалять само фото

Появилась галерея присланных фото #430
