### ISSUE TITLE
Давайте разберемся, как правильнее поступать при скидывании в арбитраж

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#202]
Я не раз уже говорил, что некоторым образом я поддерживаю идею арбитраж -> сами решение не принимаем. Я не уверен, что я прав в этом. Иногда скидываю и сам же принимаю решение. Иногда скидываю и какое то время жду. 
В этом случае бывают повторные ошибки модеров. При чем даже с комментариями в арбитраже, повторные.
Вот примеры:
http://sexoo.ru/history/message/104492058/
вот свежий:
http://sexoo.ru/history/message/105347572/
Что полезнее для системы? Стоит ли гонять сообщение туда-сюда, если всем очевидно, куда его нужно пихать?

**Comment by tebaly** [comment]
Если дословно - _очевидные_ жалобы
* стоит сбросить в арбитраж БЕЗ комментария 
* это должно помогать в определении компетентности модераторов/администраторов
* если модератор допускает ошибки в очевидных решениях, его нельзя допускать к администрированию
* пожалуйста, сбросьте рейтинг модератору, допускающему подобные ошибки администрирования, если подобные ошибки для него закономерность, а не случайность.
* принимая решение в очевидных случаях самостоятельно, вы снижаете _устойчивость_ системы, в том плане, что становится сложнее оценивать действия других администраторов/модераторов

Бывают сложные и неоднозначные случаи
* их рекомендуется сопровождать комментариями
* стоит игнорировать допускаемые ошибки модераторами в них
* вы можете расценивать конфликт и постоянный сброс таких решений, как саботаж системы(провокация, флуд)
