### ISSUE TITLE
Проблемы с доступностью сайта

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#203]
Плановое обслуживание серверов и внеплановые задачи 26 июля. С 1:30 и до 14:41 сайт периодически был не доступен либо были недоступны отдельные сервисы и/или страницы сайта. Приносим свои извинения за доставленные неудобства.

Пожалуйста, сообщите нам, если вы по прежнему наблюдаете проблему в работе того или иного сервиса или некорректное отображение страницы. Нормальная работа сайта будет восстановлена.

**Comment by Fenslau** [comment]
лаги) вот так вот общаешься с девачкой и - бац. отсосиновик.

**Comment by tebaly** [comment]
Сегодня сайт заметно лихорадило. Вроде бы всё наладилось. Сообщите пожалуйста при обнаружении проблем. Спасибо.

**Comment by Fenslau** [comment]
Внедряете что-то? Мелких замечаний куча. Стоит ли по каждому создавать темку?

**Comment by Fenslau** [comment]
502 Bad Gateway
Частенько. Но это можно обойти.

**Comment by Fenslau** [comment]
при чем тупизм такой - нажимал на профиль из списка топа нарушителей - 502. Стоит просто цифры скопипастить - попадаешь куда надо. Видимо кэш.

**Comment by Fenslau** [comment]
HTTP ERROR 500 при отправке сообщений.

**Comment by tebaly** [comment]
Бывает.. Сегодня сделали большие правки, вылезла гора косяков, ожидалось. Стиль выкладки кода будем менять конечно. С этого момента(~01:00) основную массу косяков поправили. В течении суток подшлифуем остальное.

Спасибо.

**Comment by Fenslau** [comment]
Так и не отправляются мессаги. HTTP ERROR 500
Хотя остальные же как то пишутся...

**Comment by tebaly** [comment]
Досадно(( Поправили, спасибо

**Comment by Fenslau** [comment]
HTTP ERROR 500 при отправке сообщений. Снова.

**Comment by Fenslau** [comment]
стоит рамка в поле отправки сообщений "мне интересны только парни", к примеру, хотя всё в формате анкеты. Это в том случае, если девушка ищет только парней.

**Comment by tebaly** [comment]
> стоит рамка в поле отправки сообщений "мне интересны только парни"

Исправлено
