### ISSUE TITLE
Будет убран функционал "Сейчас на сайте"

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#209]
- Обсуждается -
---
У достаточно популярного приложения тиндер 
- нет идентификации "онлайн"
- нет статуса времени "был на сайте"
- нет индикатора - дата регистрации

--- 
Возможно разработчики лентяи, возможно гении
* в первом случае всё будет реализовано скоро
* во втором, они просто отбросили лишнее

Например
- если ты хочешь познакомиться - ты пишешь всем, и тебе не должно быть важно, кто онлайн
- это важно, когда ты хочешь пообщаться - тогда тебе важен быстрый ответ
- многие пишут только тем, кто онлайн, несмотря на то, что оффлайн скоро вернется и ответит

При этом
- "дата регистрации" и  "был на сайте"  часто источник "лишней" (для начала знакомства) информацией

**Comment by Fenslau** [comment]
О_о имхо это архиважно, знать, онлайн или нет и когда кто заходил. Это што ш такое, сейчас то юлию задалбывают, где ж онлайн, что ж не пишут. А если этой инфы не будет, то вообще начнется бурление недовольств. Мне кажется, обычно пишут либо тем кто онлайн, либо тем кто был недавно. При этом от тех, кто онлайн ждут ответа (по крайней мере надеятся хоть что он будет).

**Comment by tebaly** [comment]
Вопрос крайне дискуссионный. 
* сейчас то юлию задалбывают, где ж онлайн, что ж не пишут
* то вообще начнется бурление недовольств

Панель ответов и всю систему тикетов предварительно адаптировать к наплыву "недовольств".
*  Мне кажется, обычно пишут либо тем кто онлайн, либо тем кто был недавно. 

Так оно и понятно - но у нас "Знакомства" и лишь часть из тривиального "Общение", так как одно без другого не возможно. Вот именно для "Познакомиться", информация "кто онлайн, либо тем кто был недавно" не обязательна, если учитывать, что результаты поиска строятся именно исходя из правила "кто онлайн, либо тем кто был недавно"(так сейчас и так останется, но без индикации)

**Comment by tebaly** [comment]
Если только не сделать какой-то дополнительный функционал такого рода, работающий по такому же принципу.
* вместо лайка - отправить сообщение
* но можно и "лайк" прикрутить 
* если ответили на лайк, можно отправить сообщение(обсуждается)

**Comment by tebaly** [comment]
Мы выбрали третий вариант
* упростить отправку шаблонных сообщений (ускорить)
* это некоторого рода "трансмутация" сущностей _лайк+сообщение_
* является первым этапом "высказать симпатию" 
* внешне не отличается от обычного общения

**Comment by tebaly** [comment]
Техническая сторона - оптимизация ресурсов (здесь вопрос конечно философский)
* нам нужно собирать актуальную информацию о "присутствии" пользователя из каждого обращения каждого пользователя пользователя к сайту
* это _относительно_ большой объем информации
* нам нужно постоянно обновлять эту информацию в базе (каждый запрос)
* это затрудняет кэширование в базе
* что заставляет базу _тупить_

Нет, ну мы можем конечно оптимизировать процесс(сейчас вполне терпимо), но нужно рассмотреть все варианты, рас уж прецеденты есть.. :grin:

**Comment by tebaly** [comment]
@Fenslau вы считаете, стоит отложить данную "оптимизацию" в долгий ящик?

**Comment by Fenslau** [comment]
Пожалуйста, не спешите!!!!
"дата регистрации" и "был на сайте" часто источник "лишней" (для начала знакомства) информацией

Это очень важная информация. И нельзя к сожалению убирать маркер "онлайн". Потому что пользователю важно знать, заходит ли сюда хоть вообще кто-то, или он пишет в очередную мертвую пустоту.
Давайте на примере: Один мой давний друг давно искал подобный сайт. И куда он только ни попадал. Но НИГДЕ ему абсолютно ничего не удавалось, только лишь проститутки либо все уже неактивно и закрыто давно. И только здесь этот самый приятель смог найти с кем познакомиться. Так давайте же этим дорожить! 

Нужно онлайн поднимать всеми методами. и рассказывать пользователям, что он есть. 
Я предлагаю следующее!
Дело вот в чем. Не все заходят на этот сайт скажем так, каждый день. Некоторые тем не менее заходят нерегулярно, но им были бы интересны предложения, которые поступили уже 8 дней назад. Может ввести какой то новый функционал? Типа предложение встречи перманентное, или что-то такое? Возможно, только если допустим девушка оффлайн пару дней, а юзер ею заинтересовался. 
 Я понимаю, что вы стараетесь сократить ресурсы, но это новый функционал... Хотя, с другой стороны, недели возможно и хватило бы. .. Короче! Это точно не то, что нужно резать!

**Comment by Fenslau** [comment]
Все таки намутили так, что теперь непонятно, кто онлайн, а кого уж и 2 недели как след простыл )

**Comment by tebaly** [comment]
"Онлайн" остался. 
"Был на сайте" - оценка КПД, скоро вернем(день/два).

**Comment by DrAllcome** [comment]
Отсутствие "был на сайте" аж заставило зарегистрироваться тут :) Верните пожалуйста, очень неудобно.

**Comment by tebaly** [comment]
По результатам обсуждения инициатива снимается :stuck_out_tongue_winking_eye:
* _онлайн_ вернулся
* _был на сайте_ - сегодня восстановим
