### ISSUE TITLE
Редактирование желаний

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#21]
Часто спрашивают как удалит желания.
1) В анкете пункт Добавить необходимо поменять на Изменить (возможно только в случае когда есть хоть одно желание).
2) При заходе в свою анкету рядом с желаниями добавить (продублировать) кнопку Добавить/Изменить

**Comment by tebaly** [comment]
Согласен, не явно реализовано. Открою секрет - так сделано намеренно на время тестирования "желаний", чтобы в большем количестве анкет было указано максимальное количество желаний. Удалить легко - одним кликом по желанию в списке. Интерфейс будет переделан для более прозрачного взаимодействия. Также будет введен поиск анкет по желаниям.

**Comment by tebaly** [comment]
исправлено
