### ISSUE TITLE
Изменить принцип "поднятия в топ" списка анкет в поиске

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#211]
Сейчас триггером выступает любая активность Пользователя на сайте, начиная от факта "открыл сайт". Планируется _ужесточить_ требование до 
* отправил сообщение

Таким образом, Пользователи переставшие отправлять сообщения будут постепенно _тонуть_ в списке анкет результатов поиска по сайту. Вне зависимости от факта и времени _присутствия_.

**Comment by tebaly** [comment]
Техническая сторона - оптимизация ресурсов
* частое обновление индексов в базе затрудняет кэширование
* приводит в _подтормаживанию_ базы и всего сайта в целом

**Comment by Fenslau** [comment]
Вот тут полностью поддерживаю. Если это освободит ресурсы сервера, то тем более! +++

**Comment by tebaly** [comment]
Принцип изменен. Единогласно
