### ISSUE TITLE
Дать еще один шанс Пользователям

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#212]
Сейчас если общение у Пользователей не _сложилось_, может получиться, что они больше никогда друг другу не напишут
- пользователь заблокировал собеседника

Предлагается
- дать возможность пообщаться Пользователям "как в первый раз" 
- спустя определенное время, например 3 месяца

Основная масса пользователей спустя такое время в принципе может уже и не встретиться, поэтому изменение функционала на них скажется в меньшей степени, при этом
- анкеты спамеров, троллей и фейков к тому моменту вероятно будут заблокированы "насовсем"

Поэтому у данного контингента повторно пообщаться с Пользователями не получится.

**Comment by tebaly** [comment]
Техническая сторона - оптимизация ресурсов
* сейчас мы должны хранить статус "мертвых пар" Пользователей
* таких записей в базе уже достаточно много, пользы от них не много

Если удалить уже "не актуальные" пары, единственный косяк
* пользователь сможет написать собеседнику, с которым ранее уже общался
* определить это будет уже невозможно

**Comment by Fenslau** [comment]
Согласен полностью, такую инфу хранить долго нет смысла, особенно, если это жрет ресурсы.
Спамеры. Давайте тупо установим флажок, если капчи более тыщи, то не применять это правило )

**Comment by mj4444ru** [comment]
за 3 месяца они забудут всё... так что ничего страшного наверно...

**Comment by tebaly** [comment]
Запущено
