### ISSUE TITLE
Не хватает действующих админов в хабе

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#213]
Понимаю, что насильно мил не будешь. Но если честно, судя по активности в системе даже, я вижу Может быть не знают как? Такое маловероятно, но возможно. Некоторые пишут комменты, но сюда не заходят. Нужно сделать так, чтобы админы принимали участие в обсуждении "проблем".

**Comment by tebaly** [comment]
Не хотят) Чуть позже можно попробовать интегрировать гитхаб прямо в панель администратора.

**Comment by Premaswarupa** [comment]
Так грустно здесь у вас) и с мотивацией печалька) читаем молча)

**Comment by Fenslau** [comment]
Ну да, шомпанское пока не подают.

**Comment by Premaswarupa** [comment]
Шампанское и не надо)) а вот живое общение,оч бы хотелось увидеть))

**Comment by Fenslau** [comment]
Тоже этого хочу.

**Comment by inquisitor6789** [comment]
хм... гит не самое лучшее место для болталки

**Comment by Fenslau** [comment]
Болталка болталке рознь.
Почему не хотят. Вот в чем вопрос. Ведь есть всегда что заметить, приметить, предложить, обсудить. Может быть просто им некогда или неинтересно? А тогда какие их цели вообще, такой вот вопрос.

**Comment by Premaswarupa** [comment]
https://github.com/inquisitor6789

**Comment by Premaswarupa** [comment]
inquisitor6789 commented 16 hours ago
хм... гит не самое лучшее место для болталки
Так речь не о том чтобы обсудить мой розовый маникюр :-P просто вы с таким официозом и серьезностью,что тихо дохну от зависти))  А можно по сути,но в неформальной обстановке?))

**Comment by tebaly** [comment]
Ой, да пожалуйста :satisfied: 

Просто это не только публичное место, но и _официальное_ место общения разработчиков и резидентов проекта. Как грицца "Положено по статусу")

Но, например, когда вы сообщаете об ошибке работы сайта, сквозь толщу сарказма и метафор нужно понять, в чём собственно суть обнаруженной проблемы, чтобы иметь возможность как можно скорее её исправить. От сего "сухость" в багрепортах приветствуется. Тем более ошибки на сайте не могут радовать((

Обсуждение чего бы то ни было можно вести в любой тональности.

**Comment by Premaswarupa** [comment]
Встала в угол,предварительно ревернув) 
И тихо побормочу ,из угла,оправдываясь)- ни грамма сарказма!!!все время забываю,что в сети слова "звучат" по другому(

**Comment by tebaly** [comment]
Так я в общем, по истории принятых багрепортов за всё время :blush:

**Comment by tebaly** [comment]
Наверное стоит завести "неофициальный" профиль на Гите, и дать волю "неформальности" 
:joy: :joy: :joy:

**Comment by Premaswarupa** [comment]
Пасиб,выдохнула с облегчением) буду учиться политесу "пограничной зоны) Если что,где угол,уже знаю))

**Comment by tebaly** [comment]
Как вы думаете, как привлечь в Git больше администраторов?

**Comment by Fenslau** [comment]
А они сами должны этого хотеть. Насильно их не привлечешь. Но давайте подметим вот что. 
+Цели администрирования? (сделать сайт лучше, тогда почему не здесь)
+Знают ли они хотя бы о таком инструменте как хаб?
Если знают, то почему не участвуют? 
Если не знают, то почему?
Допустим знают, но не хотят писать:
+ хотя бы читают
++ думают, что и так всё разрешится, без них
++ возможно скептики и не верят в то, что что-то изменится
+ не читают и не собираются этого делать.

**Comment by Premaswarupa** [comment]
На Хаб выходят те,кто любопытнее) и проверяет все на предмет рабочих маркеров и кнопок))

**Comment by Fenslau** [comment]
Когда я пришел, тут было 2 активных админа + тебалай. потом один из админов "ушел". Осталось совсем чут чуть, но даже этой "командой" - вон сколько багрепортов наделали. 
А если будут участвовать больше?

**Comment by tebaly** [comment]
Пользователи не до конца понимают "куда" писать
* много сообщений приходит также на почту, так как до Гита им _не_ добраться в силу _разных_ обстоятельств
* другие пишут _юльке_, так как почта - это достаточно _далеко_
* а еще часть Пользователей вообще _не пишут_ о багах - это _тяжело_..

Тикет открыт, что-нибудь придумаем

**Comment by inquisitor6789** [comment]
с моей т.з. пользоваться гитом (не только админам но и модерам, и простым юзерам) мешает то, что тут надо регистрироваться. Вроде Без регистрации на гите не напишешь issue.
А так же, что ссылка на него закопана очень глубоко (в панели админки и вроде где-то в глубине блога).

**Comment by tebaly** [comment]
Накинул ссылок в админке.

**Comment by tebaly** [comment]
Проверил на "беззащитных" Пользователях. Маленький эксперимент - "пропало удаление фоток". На сайте есть много постоянных Пользователей, которые в курсе, что "пропажа" этой функции =равно= баг/ошибка. При обнаружении бага/ошибки "заинтересованный" Пользователь должен дойти до самих разработчиков с целью выяснить причины. 

Имеются ссылки на то, что разработчики на ГитХабе, и что, если обнаружена неполадка, о ней можно/нужно сообщить на ГитХабе. Итоги:
* зарегистрированы сотни обращений по внутреннему каналу отзывы/вопросы
* поступило несколько десятков емайл/писем на "саппорт"
* **ни одного сообщения на ГитХабе**

Полагаю, нет возможностей косвенно влиять на "количество админов в хабе" - только прямое указание на важность/необходимость такой активности вплоть до "обязаловки". Эксперимент окончен, прошу прощения за доставленные неудобства.
