### ISSUE TITLE
Проблема с меню в админке.

### ISSUE THREAD

**Issue by Premaswarupa** [freedomsex/freedomsex#214]
Конпки "интерфейс модератора" и "администрирование сообщества" не работают (

**Comment by Premaswarupa** [comment]
Да, и на Хаб можно пробраться ток огородами...( через кнопку"хаба" в меню поиска,остальные(лично у меня), не работают.

**Comment by inquisitor6789** [comment]
сейчас в админке в 99% выскакивает ошибка 502
в то же самое время модерилка работает почти как часы

**Comment by tebaly** [comment]
hot-fix
* дубликаты жалоб в списках 

Их отсутствие раньше создавало проблемы, когда по идентичным жалобам принимались разные решения (bug)
