### ISSUE TITLE
отрицательный долг капчи

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#215]
Это баг или фишка?

**Comment by tebaly** [comment]
Дайте хоть посмотреть :)

**Comment by Premaswarupa** [comment]
http://freedomsex.net/userinfo/profile/?id=13945072
Пжалста:) отрицаловка,если ток не накосячит и кто-нить не влепит капчи) тогда по правилам математики работает)))

**Comment by Premaswarupa** [comment]
http://freedomsex.net/userinfo/profile/?id=13945072

**Comment by Premaswarupa** [comment]
![image](https://cloud.githubusercontent.com/assets/20158856/17501167/4954c6c2-5e06-11e6-95fe-fc4ecda45acb.png)

**Comment by tebaly** [comment]
Исправлено. Повториться не должно
