### ISSUE TITLE
нельзя изменить раздел "Другие контакты, соцсети" в своей анкете

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#216]
сабж
фрейм появляется, но на нем нельзя ничего поменять. Все пункты, а так же кнопка сохранить не активны.
Это было специально сделано?

**Comment by tebaly** [comment]
Нет. Баги полезли...

**Comment by tebaly** [comment]
Код не полностью покрыт тестами, поэтому не всегда получается всё протестировать. Спасибо.
