### ISSUE TITLE
Система распознает дубли анкет или одинаковые тексты?

### ISSUE THREAD

**Issue by Premaswarupa** [freedomsex/freedomsex#217]
![image](https://cloud.githubusercontent.com/assets/20158856/17501291/a1f5e5b2-5e07-11e6-9d77-160e675360bb.png)

**Comment by Premaswarupa** [comment]
Следствие распознавания дубликатов жалоб?)

**Comment by tebaly** [comment]
Раньше они все "схлопывались" в одну строчку - "давай по скайпу". Сейчас после "хот-фикс" это поведение отключилось, и мы с вами видим, то, что видим..

> Следствие распознавания дубликатов жалоб?)

Нет. Следствие того, что распознавание было отключено

Это поведение будет исправлено скоро.
