### ISSUE TITLE
Дублирующиеся уведомления

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#22]
Часто бывает больше 10 одинаковых уведомлений в правой части страницы (например "Оксана, 45 Уфа - Сейчас на сайте"...
Необходимо исключить дубликаты...

**Comment by tebaly** [comment]
Да, это косяк. В данный момент работаем над подготовкой к обновлению всего этого функционала. Очень объемная задача. Проблема с дубликатами будет решена. Ориентировочно несколько недель осталось.

**Comment by tebaly** [comment]
раздел выпилен. в каком виде добавить ХЗ
#430
