### ISSUE TITLE
множественные уведомления

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#220]
при появлении уведомления (например регистрация нового пользователя) оно дублируется множество раз
![image](https://cloud.githubusercontent.com/assets/19651618/17508433/952a9ad8-5e1d-11e6-9fdb-d4770af00f78.png)

**Comment by tebaly** [comment]
Спасибо. Будет исправлено. Пожалуйста, сообщайте по возможности обо всех обнаруженных неисправностях. Пришлось править очень много кода за раз, что и привело к такому количеству багов.

**Comment by tebaly** [comment]
исправлено. уведомления запустили, по регистрациям чуть позже
