### ISSUE TITLE
вопрос про поиск

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#221]
В связи с отменой указания давности посещения сайта возникает вопрос - в поиске как анкеты отсортированы?
Раньше была сортировка именно по давности посещения

**Comment by tebaly** [comment]
#211 - по времени последнего написанного сообщения

Пока ничего не отменено. Всё работает как и работало
* отключили индикацию(был на сайте), но не функционал
* индикация "онлайн" осталась.

Вероятно вернем индикацию на место в течении пары дней
