### ISSUE TITLE
алгоритм арбитража и разница в рейтингах.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#222]
http://sexoo.ru/history/message/107614336/
чот непонял, с каких пор кандидаты вот так вот решения админов спокойно арбитражат?
@6498145 наказал, а потом @12177176 вытащил в разрешенные.

**Comment by tebaly** [comment]
Всё переделал. Старые ссылки по сообщениям/жалобам теперь не актуальны.
