### ISSUE TITLE
блокированные анкеты

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#223]
http://sexoo.ru/userinfo/profile/12867465
Вроде оснований нет. 
Не знаю, может это фишка. тогда ладно.
А вдруг баг?

**Comment by tebaly** [comment]
Ложное срабатывание. Пожалуйста, если обнаружите подобное еще раз, сообщайте.
* сработал фильтр на "отпечаток" ранее заблокированного сообщения.
* в сообщении пользователя при этом ничего такого не было

Сбойный "отпечаток" удален, пользователь восстановлен. Прискорбно.
