### ISSUE TITLE
Отсутствие группировки по статусу "онлайн" и нерабочий чекбокс

### ISSUE THREAD

**Issue by autumnrustle** [freedomsex/freedomsex#224]
1. При поиске онлайн анкеты разбиваются, а не группируются - http://i.imgur.com/KTKahAj.png
2. Не работает чекбокс "только онлайн".
3. Предложение - опция поиска исходя из пожеланий поиска остальных людей. Например, люди из такго-то города такого-то возраста, которым интересен ты со своим возрастом.

**Comment by tebaly** [comment]
> Не работает чекбокс "только онлайн".

Он никогда не работал :sweat: Эта опция изначально бутафорская, так как поиск всегда сортировался по "онлайн", теперь нет - #211 - поэтому разброс

**Comment by tebaly** [comment]
> Предложение - опция поиска исходя из пожеланий поиска остальных людей. Например, люди из такго-то города такого-то возраста, которым интересен ты со своим возрастом.

Идея хорошая, однако она затрагивает проблему кэширования результатов такого поиска. С каждой новой опцией количество данный в кэше возрастает многократно, но это не главное
* поиск должен быть простым для всех
* интерфейс сайта должен быть простым

На сегодняшний день поиск осуществляется только по критериям
* половая принадлежность
* возраст собеседника
* город
 
Очень хотим запустить поиск по желаниям

Под большим вопросом 
* поиск геев/лесби
* поиск пар

Такие _"суб поиски"_ планируется возложить на поиск по желаниям - он действительно сделает возможности шире, без особого усложнения
