### ISSUE TITLE
наказание за спам -3 капчи??? (это минус а не тире)

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#225]
![image](https://cloud.githubusercontent.com/assets/19651618/17553435/5f6c43dc-5f0e-11e6-9a60-cb5deba98d6b.png)

**Comment by tebaly** [comment]
Проблема в БД по "минус" капчам была _исправлена_. Вероятно эти баги взаимосвязаны
* обнаружено ещё 27 записей с отрицательным значением
* записи удалены, перепроверим несколько раз в ближайшие пару дней для достоверности

Спасибо
