### ISSUE TITLE
нововведения не нравятся пользователям

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#226]
http://freedomsex.net/admin/sethelp/?id=151979&ln=0
Добрый день! Проведенные работы на сайте не пошли на пользу. Появилось много проблем. Первейшая - не работает оповещение о поступлении новых сообщений от пользователей. Далее - в поиске анкеты онлайн не группируются в начале списка найденных, как это было раньше, а разбросаны по всем страницам. Также при первом входе на заглавную страницу не видна своя анкета в списке. И вообще список обновляется очень медленно, значительно реже чем было изначально. Хотелось бы чтобы работа сайта было приведена к изначальному высокому уровню. О других замеченных проблемах буду сообщать.

**Comment by Fenslau** [comment]
Юля,здравствуйте!Пожалуйста,подскажите почему не определяется время и дата когда человек был на сайте? В сообщениях на синей полоске в верху не видно количество их и сайт не мигает когда они есть.Версия,которая была раньше,была удобной и всех устраивала,а теперь приходится искать другие сайты потому что здесь прошли изменения.Можно как нибудь устранить эту проблему?Спасибо!

**Comment by inquisitor6789** [comment]
похоже надо откатывать изменения....

**Comment by Fenslau** [comment]
Я то так понял, что не вместе с изменениями много глюков привнеслось. Не понятно, хотели ли разработчики именно такого эффекта. Врядли.

**Comment by inquisitor6789** [comment]
с нотификацией явно глюк какой-то
скорей всего как и с https://github.com/freedomsex/freedomsex/issues/216

**Comment by Fenslau** [comment]
Теблай создал несколько тем, в которых предполагались незначительные изменения, которых бы никто не заметил. Но это позволило бы высвободить ресурсы. Вот их и нужно видимо реализовать, ну может быть обновление по последнему сообщению еще оставить (только все равно сначала онлайн показывать вверху). А остальное пожалуй лучше откатить. Особенно время посещения.... И нотификацию)
Юзер негодует! )

**Comment by tebaly** [comment]
Это не нововведения, а баги в коде. Мы их обязательно поправим. До этого сайт еле работал и в итоге провисел в даунтайме почти двое суток. Изменения были крайне необходимы.
* кэширование результатов поиска действует на всех проектах знакомств
* в некоторых проектах анкеты в списке вообще не поднимаются, либо за деньги

Нотификацию поправим, индикацию вернем в течении суток. Спасибо.

**Comment by tebaly** [comment]
Раз или два в год такое бывает :persevere:

**Comment by Fenslau** [comment]
Добрый день! Я не пользуюсь месеенджерами вайбер и вацап, но на сайте я больше года и знаю, как он работал всё это время, до проведения отладочных работ. Не заню какие плюсы должны появиться после них, но масса минусов уже налицо. Вот ещё один момент: когда заходишь в профиль пользователя не отображается онлайн ли он в данный момент или как давно был онлайн, час или сутки назад. На прошлой неделе эта функция великолепно работала.

**Comment by Fenslau** [comment]
Раньше то постоянно спрашивали, как найти онлайн, теперь вообще...
Не нужно думать, что здесь большинство действуют в режиме "послал сообщение - завтра прочитаю" - нет. Почти все хотят онлайна! И ответов в случае заинтересованности. 
Это создает хорошую обратную связь и очень важно пользователям! Тех, кто хочет заходить через несколько дней, все равно не потеряем. А вот если онлайна не будет, то все, это будет конец.

Обращаюсь к разработчикам: 
+Планируется ли восстановление "как было"? 
+Прогнозируемый был результат, я же говорил, что все будут в шоке. зачем внедрять заведомо очень спорный функционал?

**Comment by tebaly** [comment]
> не работает оповещение о поступлении новых сообщений от пользователей. 

* исправлено

> в поиске анкеты онлайн не группируются в начале списка найденных, как это было раньше, а разбросаны по всем страницам. 

* изменился принцип "поднятия", адаптируемся

> Также при первом входе на заглавную страницу не видна своя анкета в списке. И вообще список обновляется очень медленно, значительно реже чем было изначально. 

* это кэширование, до 15 минут на результаты поиска. Уменьшим сегодня до 5

> Хотелось бы чтобы работа сайта было приведена к изначальному высокому уровню. 

* как показала практика, без кэширования сайт уже не в состоянии работать - проект набрал критическую массу пользователей, пришло время оптимизации ресурсов.

**Comment by inquisitor6789** [comment]
может стоит написать пару слов про сортировку в поиске? большими красными буквами
А то вопросами уже затрахали, а будет еще больше
