### ISSUE TITLE
При блокировке анкеты скидывать ранг в 0 

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#227]
А то может получиться вот как:
http://sexoo.ru/argue/profile/9905367/
http://sexoo.ru/userinfo/profile/9905367
Чувак до сих пор заходит. И возможно влияет на что-то. 
даже поди может посмотреть за что его блокировали (я уже не помню, позволяет ли его ранг это), но даже если не позволяет, всеравно нельзя допустить, чтобы привилегии оставались после блокировки..

**Comment by tebaly** [comment]
Сущности "Пользователь сайта" и "Модератор/Администратор проекта" не взаимосвязаны. Далее по плану админ интерфейс архитектурно будет полностью отделен от самого сайта (сейчас есть некоторые архитектурные связи).
* морально - можно(допускается) применять "административные" воздействия за нарушение правил пользования сайтом
* технически - это не регламентировано и не описано, так как "административные" воздействия применять необходимо при ошибках администрирования, а ограничение общения - только при нарушении правил пользования сайтом.
* так задумывалось
