### ISSUE TITLE
http://freedomsex.net/userinfo/profile/13748836

### ISSUE THREAD

**Issue by Premaswarupa** [freedomsex/freedomsex#228]
http://freedomsex.net/userinfo/profile/13748836 
Понятно,что ошибка. Какие действия предпринимать с такими анкетами?
![image](https://cloud.githubusercontent.com/assets/20158856/17592827/0b1fdcc0-600e-11e6-8ce6-a2b251235791.png)

**Comment by inquisitor6789** [comment]
а что с ним не так? отрицательный долг капчи?

**Comment by Premaswarupa** [comment]
Да.

**Comment by inquisitor6789** [comment]
https://github.com/freedomsex/freedomsex/issues/215

**Comment by Premaswarupa** [comment]
Видела,что ссылка на одну и туже анкету. Вопрос в том,как с ними поступать? В последние дни,аналогичных случаев ,встречается все больше.

**Comment by Premaswarupa** [comment]
http://freedomsex.net/userinfo/profile/13924354 
Таких анкет все больше,и минуса большие. Что делать с такими анкетами?

**Comment by tebaly** [comment]
hot-fix 

Вероятно проблема была в структуре БД 
* исправлено
* код не затрагивался
* функционал поставлен на ривизию
