### ISSUE TITLE
может стоит написать пару слов про сортировку в поиске

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#229]
может стоит написать пару слов про сортировку в поиске? большими красными буквами
А то вопросами уже затрахали, а будет еще больше

**Comment by Fenslau** [comment]
Да уж, будьте любезны.
А еще все очень переживают, что не видно, когда предмет их ̶о̶н̶а̶н̶и̶з̶  ....фантазий был на сайте.

**Comment by Fenslau** [comment]
Да уж, будьте любезны.
А еще все очень переживают, что не видно, когда предмет их ̶ ....фантазий был на сайте.

**Comment by Fenslau** [comment]
Блин... Я вот тут подумал... А не создаст ли такой способ сортировки нехорошую положительную обратную связь..? Что-то прям беспокойство. Может ну её? Общаешься с девушкой просто, а ее все задалбывают....

**Comment by tebaly** [comment]
>  Общаешься с девушкой просто, а ее все задалбывают....

Оно и раньше так было

**Comment by Fenslau** [comment]
логично. так может лучше ООС сделать??
Вообще, давайте разберемся: зачем нужно поднимать анкеты?
....
....
Мне кажется, в основном затем чтобы на них обращали больше внимания.
Так может по ООС сделать так, чтобы в первую очередь шли анкеты, которые онлайн (или были буквально недавно - хватит лага отображения онлайн статуса), но КОТОРЫМ почему-то не пишут (пишут меньше). Потом бы шли анкеты, которые онлайн, но им пишут много (к концу списка самые задолбанные). Потом бы шли анкеты, которые были недавно и далее по возрастанию срока посещения сайта. 
Я понимаю, что это все может показать ерундой на палке, но если б я делал, сделал бы именно так.

**Comment by tebaly** [comment]
> ерундой на палке 

:blush:

Таки у нас цель:
* создать условия для максимально быстрого _знакомства_ и общения

Так вот, вы предлагаете "уменьшить вероятность" знакомства парня с девушкой. Понятно что девушка "больше не хочет", но по вашему предложению, мы с вами у парня не спрашиваем его личного мнения. А все парни здесь по умолчанию хотят познакомиться.

Вопрос по количеству "входящих сообщений" лежит в другой плоскости. А именно части "общение". А сортировка в поиске к общению имеет малое отношение, оно больше к "познакомиться". Поэтому нам с вами в этой ситуации стоит думать о том, как дать девушкам возможность _отвечать_ на максимум входящих сообщений, либо дать возможность _игнорировать_ входящие БЕЗ приоритета этому действию.

Последнее реализовано функцией "Фавориты" - это не просто _избранное_, а именно возможность _игнорировать_ входящие. Да, при этом нужно кликать вкладку "Фавориты", чтобы открыть любимый контакт. 

Это и есть _приоритет всех входящих_ перед возможностью их игнорирования.

**Comment by tebaly** [comment]
Возможности "не задалбываться" у девушек сейчас есть
* мысленно игнорируем все входящие, а они будут входить, так как это основная цель проекта
* добавляем избранные контакты в _фавориты_
* общаемся по принципу white-list, только с теми, кто в фаворитах

PROFIT!

**Comment by Fenslau** [comment]
Не, не, почему это уменьшить вероятность я предлагал? наоборот же, если наверху будут те, которым пишут меньше, то они теоретически больше желают знакомства, чем те, которым и так много пишут. То есть сейчас тем, кому не пишут оказываются на третьих, четвертых страницах и так там могут и застрять, а те кто активно общается - наоборот на самом видном месте... 
Про фавориты я не знал... А что, работает?

**Comment by tebaly** [comment]
Тогда вижу как минимум два решения
* сделать кнопку типа "Нужно больше сообщений" - а по ее нажатии открывать справку с описанием того принципа, что поднятие только по написанному сообщению
* сделать нотификацию того же плана: "Вам нужно больше новых знакомств и сообщений, поднимите анкету в поиске бесплатно. Подробнее.."

**Comment by drvalera** [comment]
Поднимать прям в прямом смысле не обязательно, надо чтобы те кто онлайн были опять сверху, а не искать по всем страницам кто в сети.

**Comment by fenixnoir** [comment]
На мой взгляд поднятие по посещаемости вполне логично. Зашел, счетчик обрушился, и ты в самом верху, и медленно сползаешь вниз до следующего входа.
У меня вопрос по другой сортировке, которая на сайте не реализована.

Я парень, о чем в анкете/базе есть отметка. Я ищу девушку через поиск, но мне почему-то выводятся так же девушки ищущие девушек. А ведь многие, кхм, пишут этим девушкам и портят им настроение... Почему бы из выдачи не убрать несоответствующие результаты? Давайте сделаем так, чтобы гомосексуалисты не страдали от неадекватных гетеросексуалов, или наоборот.

**Comment by tebaly** [comment]
#13 #412 - добавлено информационное окно с текстом

> Онлайн анкеты всегда наверху. Все самые активные пользователи на главной странице. Просто пишите тем, с кем ещё не общались. Отдельный поиск онлайн анкет отсутствует, да он и не нужен.

Смотреть можно на дев-ственном сервере сегодня/завтра

Онлайн поиска скорее всего не будет никогда ~не говори никогда~, так как сервис не расположен к онлайн общениям, а нацелен на знакомство в оффлайне. Нужно чувствовать разницу.

**Comment by tebaly** [comment]
#13
