### ISSUE TITLE
Отсутствие индикации "ОНЛАЙН" являестя ошибкой, а не улучшением

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#231]
При проведении работы в связи с оптимизацией ресурсов, был нарушен механизм индикации в анкете статуса "онлайн". Его отсутствие не является улучшением, а следствие архитектурной неисправности. Статус будет отображаться как раньше после устранения неисправности.

**Comment by Fenslau** [comment]
Ну хорошо, а то Юзер уже весь извелся. Не может он не знать степень свежести анкеты.
Кстати, хорошо что вернули город при раскрытии анкеты, а то какое то время не было почему то. Лишь бы опять не потерялось)

**Comment by tebaly** [comment]
Статус онлайн восстановлен. Корректность тестируется.
