### ISSUE TITLE
Убрать положительную обратную связь при неправильном вводе капчи.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#232]
Уже об этом я писал, но тогда не понимал, что толком происходит.
А происходит вот что:
Пользователь (часто новый) попадает на капчу (иногда в первом-втором сообщении).
Вводит то ли неправильно, то ли вообще не вводит, тупо жмет ок.
Ему назначается еще больше. и так до бесконечности. При этом бывает такое, что пользователь что-то все же вводит. Я подозреваю, что или по какой-то причине он видит не то, что нужно вводить (не всегда, но мне кажется, что такое тоже бывает). Я предлагаю ПОС убрать и при реально ошибочном вводе капчи (а не тогда, когда ее уже много и действует троллинг), новую не назначать в арифметической прогрессии. 
+ разобраться, почему иногда пользователи вводят цифры, но они не соответствуют запросу. Таких случаев много, это наш онлайн, там и девушки попадаются. Может баг закрался в отображении картинки с капчей?

**Comment by tebaly** [comment]
Ранее мы с вами обнаружили баг в капчах - минус-капчи
* неисправность была устранена

Если эти два бага никак не взаимосвязаны, давайте найдем Пользователей с проблемой и изучим ее более детально.

**Comment by Fenslau** [comment]
Да я сам не пойму, баг это или не баг...
http://sexoo.ru/userinfo/profile/5863647
видно же, что пользователь что-то вводит, но постоянно с ошибкой. Ну ладно, вы скажете мол, пёс его знает, пользователь старый, может он там чего заслужил, ну вот еще пример:
http://sexoo.ru/userinfo/profile/14232275
этот постоянно вводит одни и те же комбинации на одни и те же запросы, но они не совпадают! Почему, штош такое, ну не может быть, чтобы это было специально им так подстроено. 
И за каждую ошибку, получается долг капчи нарастает. за несколько ошибок, получается, можно себя загнать в ту область, где уже даже правильно введенная капча посчитается за ошибку?

**Comment by tebaly** [comment]
Я пробовал повторить такое поведение, у меня не получалось. Давайте вместе попробуем симулировать такой результат.

**Comment by tebaly** [comment]
Test №1 - 14435880 - собеседник №1
- полная регистрация (имя+возраст+город)
- отправка сообщения "не по интересам"
- ввод неправильной капчи около 5 раз
- отправка без ввода капчи
- отправка с правильной капчей

Отработано штатно

Test №2 - 14435880  - собеседник №2
- отправка сообщения "не по интересам"
- ввод неправильной капчи около 5 раз (появились записи в логе)
- отправка "Привет" собеседнику №1 - требуется капча
- отправка с НЕ правильной капчей - ошибка зарегистрирована
- отправка без ввода капчи - ошибка зарегистрирована
- отправка с правильной капчей №1
-- не принято - ошибка не регистрируется
- отправка с правильной капчей №2 - отправлено собеседнику №1

Отработано штатно

**Comment by tebaly** [comment]
Test №3 - 14435880 - собеседник №3
- отправка сообщения "не по интересам"
- ввод неправильной капчи около 5 раз - записи в логе НЕ появились
- ввод неправильной капчи около 5 раз - записи в логе НЕ появились
- отправка с правильной капчей №1 - не принято - ошибка не регистрируется
- отправка с правильной капчей №2 - не принято - ошибка не регистрируется
- отправка с правильной капчей №3 - отправлено

Отработано штатно (поведение странное...)

**Comment by tebaly** [comment]
Test №4 - 14435880 - собеседник №4
- отправка сообщения "не по интересам"
- отправка с правильной капчей №1 - не принято - ошибка не регистрируется
- отправка с правильной капчей №2 - не принято - ошибка не регистрируется
- отправка с правильной капчей №3 - не принято - ошибка не регистрируется
- отправка с правильной капчей №4 - не принято - ошибка не регистрируется
- отправка с правильной капчей №5 - не принято - ошибка не регистрируется
- отправка с правильной капчей №6 - отправлено
- ПОСТУПИЛА ЖАЛОБА (или две)
- отправка с правильной капчей №1 - не принято - ошибка не регистрируется
- отправка с правильной капчей №2 - не принято - ошибка не регистрируется
- отправка с правильной капчей №3 - не принято - ошибка не регистрируется
- отправка с правильной капчей №4 - не принято - ошибка не регистрируется
- отправка с правильной капчей №5 - отправлено
- ПОСТУПИЛА ЖАЛОБА

Сообщения отправить можно, но уже крайне сложно

Отработано штатно

**Comment by tebaly** [comment]
Test №5 - 14435880 - собеседник №5

РУЧНАЯ ПРАВКА ДАННЫХ В БАЗЕ 
для пользователя 14435880

- отправка сообщения "не по интересам" (парень-парень)
- отправилось

**Comment by tebaly** [comment]
Test №5 - 14435880 - собеседник №5

- отправка сообщения "не по интересам" (парень-девушка)
- отправилось (O_o)

Проверяем...

**Comment by tebaly** [comment]
А не, норм.  Все работало штатно, отправлял тем же

**Comment by Fenslau** [comment]
Хорошо, я тоже приму участие в этом тесте. Я чувствую, что где то зарыта собака. юзерам отображается не то, что от них ждут. Но как же это узнать? Найти онлайн юзера с такой проблемой и долгом в 70+ капчи оперативно - очень проблематично. И при этом еще нужно запросить у вас разрешение на снятие капчи с него (чтобы поговорить и понять, как такое произошло). Остается тестировать самостоятельно...

**Comment by Fenslau** [comment]
так... а если сделать немного по-другому? я насобираю таких пользователей (собственно невелика задача, все они в утопленниках в топе), может получится понять, что их объединяет?
Может быть они все через телефон сидят и в этом какая то проблема или еще чего..?

**Comment by Fenslau** [comment]
Странно, что раньше этот вопрос никем не поднимался, ощущение есть какой-то проблемки, какой-то где-то тут порылся бачок, мож даже не там, куда я смотрю.. Основываюсь на том, что такое происходит систематически с разными абсолютно пользователями.

**Comment by tebaly** [comment]
Попробуйте оба варианта.

Я кстати "нащупал" возможную истину 
* если отправлять сообщение с неправильной капчей и НЕ дожидаться ответа сервера
* затем нажать "обновить", и отправить данные повторно - засчитается ошибка
* так как капча на сервере уже обновилась

Такое возможно например, когда сервер долго "отвечал" либо дошло до таймаута с чьей либо стороны
* страница ответа сервера не загрузилась
* пользователь нажимает "обновить" - стандартное поведение
* пользователю засчитывается ОШИБКА капчи

Вариант
* отключить обновление капчи при повторе 

Это несколько ослабит защиту.
* давайте попробуем, а если "почувствуем" увеличение количества роботов, вернем как было.

**Comment by tebaly** [comment]
Изменено поведение генератора кода
* при обновлении кода, сам код не меняется

Пользователям с запредельным значением капчи установлена капча - 5

**Comment by Fenslau** [comment]
Я редко в этом списке видел спамеров. В основном там единичные случаи. такие, как я описал в первых сообщениях и потом уточнил. 
Я попробую как-то связь установить с теми, кто такому подвергся. И буду послеживать за такими.

**Comment by tebaly** [comment]
Сейчас изменено поведение системы - подождите пожалуйста "новых" потерпевших, после вернемся к изучению проблемы. Мне кажется это больше не повторится.
* кроме случаев намеренных ошибок

**Comment by tebaly** [comment]
По теме отбращения ПОС убрать нельзя. Я отключил оба фактора защиты - вот пример
http://freedomsex.net/userinfo/profile/14470072

Сейчас включу кубики(троллинг) понаблюдать

**Comment by tebaly** [comment]
* кубики включил
* ошибки(ПОС) временно отключены
