### ISSUE TITLE
косяк с нормализацией сообщения

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#233]
есть 2 сообщения
"$$$ хочешь?" http://freedomsex.net/history/message/108375752/
и
"хочешь?" http://freedomsex.net/history/message/108331383/

по первому сообщению видно, что это предложение оплаты. В то же самое время второе сообщение вполне легально. Если заблокировать первое сообщение, то второе тоже блокируется. И наоборот - разрешишь второе, разрешишь и первое

**Comment by tebaly** [comment]
Найдено 100 конфликтных записей. Поведение исправлено
