### ISSUE TITLE
Непонятный автоматический сброс рейтинга у модераторов/администраторов

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#236]
У нас давно заложен механизм предотвращения злоупотреблений "Администратором"
* есть список наказанных/заблокированных сообщений
* если администратор/модератор отправит что-то из списка - ата-та
* автоматически списывается ТРЕТЬ рейтинга за каждое такое сообщение

Например, даже если дословно отправить "копию" в благих целях.

Кто сталкивался? Одного знаем))

**Comment by inquisitor6789** [comment]
ага, знаем.
чаще всего это происходит если из "наказано" переводить в "блокировано".

**Comment by tebaly** [comment]
Это не то.. там такого поведения быть не должно

**Comment by inquisitor6789** [comment]
хм... тогда со мной такого не было

**Comment by inquisitor6789** [comment]
или все таки было. Еще вчера рейтинг составлял 5024, а сейчас 1800 http://freedomsex.net/argue/profile/5040613/
чисто теоретически я могу связать это с проблемой https://github.com/freedomsex/freedomsex/issues/233 но хотелось бы какого-то подтверждения или опровержения

**Comment by drvalera** [comment]
а где вообще смотрится рейтинг?

**Comment by Fenslau** [comment]
видимо что-то не до конца исправлено... Раньше то не было такого, а я в общем то по себе даже могу сказать, что ничего не изменилось в текстах моих сообщений за последние 2-3 дня.

**Comment by tebaly** [comment]
Будем искать :copyright:

**Comment by Fenslau** [comment]
четвертый раз уже. Не то что бы неприятно, но странно. ладно, нет смысла восстанавливать рейтинги, пока не будет понятно, что же такое случилось, что все стали так слетать. Я ничего такого не говорил. Все в пределах нормы.

**Comment by Fenslau** [comment]
мож уже восстановим всем рейтинги и приостановим сброс, а просто тупо изучим, почему так происходит? ) Ладно, у Сереги слетает до 1800, он хоть при этом еще админить может, у меня слетает сразу до <1000

**Comment by tebaly** [comment]
Да. Отключим. Только чуть позже

**Comment by Fenslau** [comment]
жескачь. Я уже даже сомневаться стал, што ж такое в этом списке то, что я ж постоянно попадаю на эту фигню... ) Поди опять за ссылку наказали )

**Comment by tebaly** [comment]
Это пока всё "глюки системы", исправим обязательно. Рейтинг восстанавливаем всем при обнаружении такой ситуации.

**Comment by Premaswarupa** [comment]
Круто)) вот это разжалование)) из админов в специалисты высший класс o_O

**Comment by Premaswarupa** [comment]
И дальше падает((( уже ток спец 1 класса(((

**Comment by Fenslau** [comment]
Оу, я уж думал да минет тебя сия чаша, ан нет. Запрещенными фразами выражаемся стало быть )

**Comment by Premaswarupa** [comment]
Где??? И какими,позвольте полюбопытствовать???

**Comment by Fenslau** [comment]
Они держатся в секрете)))) я тут намедни кучу из блоков вытащил, но так как рейтинг слетел, сам не мог их арбитражить. Чего там только не было...от совсем безобидного до простых оскорблений (видимо в начале правила были жесче). Прошелся по всей истории и такая же куча еще там осталась. Дальнейшая судьба этих сообщений мне неизвестна, застряли где то....

**Comment by Premaswarupa** [comment]
Хм....ну эт самое криминальное из моего злоупотребления)) если причина в этом))
![image](https://cloud.githubusercontent.com/assets/20158856/17835492/16bd7e4c-6799-11e6-9d29-7d6ca68317b0.png)

**Comment by Fenslau** [comment]
Да я и сам ничего криминального не делал) а поди ж ты) я даже сейчас посмотреть не могу, остался ли кто там в админах вообще)) так непривычно ))

**Comment by Fenslau** [comment]
Может быть нам нельзя сам факт админства обсуждать и говорить ключевые слова?) я даже тоже в догадках, Саша-тебалай пока тоже помалкивает ))

**Comment by Premaswarupa** [comment]
Здесь нет обсуждения админства)) а к такому ответу можно прийти даже не будучи админом)))

**Comment by Fenslau** [comment]
Фотку отправил - все ппц. Теперь я в этом уверен на 146%.
Мля, вот так и думал!

**Comment by tebaly** [comment]
Я работал. Только сейчас заглянуть получилось. 
@Premaswarupa - пришлите пожалуйста на почту ID - поправим.

Сейчас попробую усилить логирование, чтобы отловить причину сбросов, явно ведь глюк какой-то

**Comment by Premaswarupa** [comment]
Уже)) Реверанс и дробь ресницами))) за "спасение")

**Comment by tebaly** [comment]
`У нас давно заложен механизм предотвращения злоупотреблений`

Там с того момента отсутствует логирования производимого сброса. Попробую добавить и отследить поведение, если причина именно в этом месте.

**Comment by Fenslau** [comment]
за фотки точно сбрасывает. только не понятно, почему это только недавно стало актуально.

**Comment by Premaswarupa** [comment]
Хм...я тоже вчера отправляла фото,после них и слетела. Но отправляла,отнюдь не первым сообщением,а в диалоге.

**Comment by Fenslau** [comment]
Вот и я так же.

**Comment by tebaly** [comment]
Прямо сейчас обновил код логирования и начислил вам по 5000 и по 10000 кредитов. Пожалуйста, давайте поотправляем и фото и сообщения с целью локализовать бажыну

**Comment by Fenslau** [comment]
отправил @Premaswarupa фотку из инета, у меня стало  1666 )

**Comment by Premaswarupa** [comment]
Аналогично, отправила без пометки на интим фото.

**Comment by Fenslau** [comment]
А мне пришло как интимное кстати )

**Comment by Premaswarupa** [comment]
Эт потому, что затрахалась с паркетом в бокс))))))))
Извините))

**Comment by tebaly** [comment]
Отловил ))))

`администратор употребил непотребство - списано 3334` 

Всем спасибо.
Сейчас разберусь

**Comment by Premaswarupa** [comment]
Саша,посвятите нас,бога ради,непотребство в чем выражалось?))) если эт не протеворечит правилам,конечно)))

**Comment by tebaly** [comment]
Это очень странно...

**Comment by Premaswarupa** [comment]
Что странно?))

**Comment by tebaly** [comment]
Это дремлющий баг которому тысячи лет. Он спал и никак себя не проявлял, внешне казался безобидным. Но когда случилось это #235 под общий шумок, в базе у неведомой строки поменялось значение с `разрешено` на `наказано`. И понеслась.. А неведомая, потому что пустая :joy:

Ничего не предвещало беды, так как всегда было `разрешено` и в строке ничего не было. Да и как она там появилась тоже загадка. Короче
* удалил косяк
* будьте бдительны
* может что ещё найдем

:smile:

**Comment by tebaly** [comment]
Спасибо. Баг был достаточно сложно определим и действовал на всех пользователей.

**Comment by Premaswarupa** [comment]
Приятственно)

**Comment by tebaly** [comment]
Если данное "поведение" будет по прежнему наблюдаться, пожалуйста, сообщите мне. Данный баг "покосил" массу модераторов. Если вам известно, что у кого-то ещё сильно срезало рейтинг, дайте знать, или скажите модераторам, чтобы обратились в саппорт. Спасибо.
