### ISSUE TITLE
на всякий случай сообщаю о заблокированной анкете

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#237]
http://sexoo.ru/userinfo/profile/14470009
как бе, вдруг опять баги? Я вроде смотрел смотрел, за что - не понял

**Comment by tebaly** [comment]
"я ищу спонсора" - пусть ищет в другом месте :stuck_out_tongue:

**Comment by Fenslau** [comment]
http://sexoo.ru/userinfo/profile/?id=14485562
тоже чот не сразу доходит, что не так.
