### ISSUE TITLE
звуковое оповещение

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#238]
будет ли звуковое оповещение при поступлении нового сообщения?
http://freedomsex.net/admin/sethelp/?id=152152&ln=152153

**Comment by tebaly** [comment]
да, как вернем "уведомления"

**Comment by inquisitor6789** [comment]
так вроде они работали на прошлой неделе. По крайней мере у меня :-)

**Comment by tebaly** [comment]
Всплывающие - звук с ними только работал

**Comment by tebaly** [comment]
уведомления запустили
