### ISSUE TITLE
Пользовательская функция заблокировать - работает ли?

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#239]
Сегодня мне пользователь (девушка) пожаловалась на то, что когда она пыталась заблокировать доставшего её мужика, сообщения не приходили до того момента, пока она не выходила и потом заново не заходила на сайт. Разлогинивалась она или нет, я не уточнял, но думаю, что нет.  Хотя все возможно.
То есть по ее словам выходит так:
1. пишет ей мужик. 
2. он ей не понравился, она решает его заигнорить, нажимает заблокировать у него в анкете.
3. больше сообщений от него нет
4. она уходит куда-то по делам, сайт закрывает.
5. потом (возможно с другого устройства, а может быть и нет) она снова заходит на сайт и вот тут то все его сообщения снова мигают как непрочитанные.

Я попытался такое воспроизвести с тестовой анкетой, но не получилось. Я не видел сообщений от тестера, в независимости от того разлогиниваюсь я или же нет, захожу, ваыхожу и т.п. нет их и все.
Но ей я верю, так как это было сказано в таком контексте, что не было смысла обманывать. На всякий случай решил создать темку, вдруг кто чо знает. Мож поспрошаю еще у нее, когда это было, мож давно уже да исправили.
Надо заметить. Не в первый раз я о таком слышу. Но раньше не придавал этому значения, думал юзеры тупят. но похоже что-то где-то все же есть...

**Comment by inquisitor6789** [comment]
да, подтверждаю, что время от времени такие жалобы попадаются. 
Чисто теоретически можно предположить, что вторая сторона создает новую анкету. И продолжает писать уже с нового акка. Но как-то не особо верится.

**Comment by Fenslau** [comment]
Я спрашивал про вторые акки, она говорит нет, мол, тот же самый. Вторые - то это понятно. А тут мол от того же и все тут. Хер конечно знает.

**Comment by tebaly** [comment]
Проверьте пожалуйста. Попробуйте создать левую анкету, начать переписываться и заблокировать.

Я вижу еще одну причину
* пользователь отправил сообщение уже заблокированному собеседнику
* это автоматически "разблокирует" его

**Comment by tebaly** [comment]
Пожалуйста, если у вас получилось подтвердить, что "функция" не работает, дайте знать.
