### ISSUE TITLE
жалуются, что картинки не видят

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#240]
http://freedomsex.net/admin/sethelp/?id=152160&ln=0
собственно сабж. В личной переписке отправил ей картинку - говорит, что не видит. Так же говорит, что проблема возникла послед обновления сайта. 
С моей стороны все нормально, все картинки вижу.
Может где-то очередной косяк вкрался?

**Comment by tebaly** [comment]
Я тоже их вижу. Я видел обращение и отправил "объектив" - и вы его тоже видели наверное. Сервер картинок не обновлялся. Я думаю проблема у конкретного пользователя, а не на сайте. Вероятно антивирус или блокировщик рекламы

**Comment by DrAllcome** [comment]
массовые жалобы пошли, на проблемы с фото.

**Comment by tebaly** [comment]
А вот сегодня да) #245
