### ISSUE TITLE
Как усилить обратную связь с пользователями ресурса

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#241]
Что ж. Довелось мне повстречаться с реальной юзершей этого проекта (не то что бы в первый раз, тут дело скорее в том, что встречались чисто ради поболтать). Мне было интересно узнать, что она думает о сайте, и вообще сабж )
Так вот, может быть кому-то будет интересно, какие мысли прозвучали в нашем диалоге:
1. девушкам шлют члены разнокалиберные. В основном им это не нужно, особенно первым сообщением, некоторых это отпугивает от сайта. Это и так понятно, но может быть уже добьем бан фото по хэшу, или что там предлагалось такое в связи с этим?
2. Пишут из других городов. - Тоже и так понятно. Сам много раз наблюдал в админке, когда написали из другого города, но потом что-то там заладилось и понислась - вирт, скайп, вся херня) бывает такое, но редко. Ограничить они не могут, но хотят (порой сильно). Эта девушка хотела не так уж сильно, поэтому отнеслась с пониманием, но все равно говорит, мол, "мне они всеравно все неинтересны, ну хочут - пусть пишут".
3. Самое блин главное. О чем я уже тему создавал, давайте вернемся к ней. Дать 5-10 минут девушке, которая только что создала анкету на то, чтобы осмотреться, заполнить данные о себе, еще что-то в конце концов, подразобраться немного. Мы теряем онлайн женский только из-за того, что девочек сразу заваливают стручками и прочее. НИКТО сразу не готов к сексу через секунду. Но предложения поступают и сразу масса фоток хуёв. Давайте думать над этим. Они потенциально то готовы и это наш онлайн (возможный), но уходят только из за такого вот похабского обращения.
4.жалуются на город/вирт/возраст. Может быть продумать алгоритм? Как сейчас? списывают пару капчи за то что на это наплевал и потом все? Я этого не знаю. Опять же можно подумать. Если ты пресет эйдж, вирт или еще что-то, то можно и похуже наказывать, но зато если тебе отвечают - потом уже не наказывать - это было бы супер
5. многие юзеры уверены что сайт работает так: Зашел, увидел девочку, написал предложение - она обязана ответить и сразу же бежать ебаться. Ну тут уж ничего не поделаешь, это уж пусть сами они тама разбираются )

**Comment by Fenslau** [comment]
кстати. сайт сам она оценила очень высоко. несколько раз говорила что основное достоинство - это что регистрации нет и что все само удаляется со временем. так что плюсы есть безусловно. Она говорит, мол, на других сайтах не так, поэтому здесь супер

**Comment by tebaly** [comment]
> можно предусмотреть запрет

Я понимаю, что меня не понять. Но запретительный путь - не наш путь. В части "общение и знакомства" мы крайне неохотно что-либо запрещаем, и по возможности разрешаем то, что было ранее запрещено.

**Comment by tebaly** [comment]
> запрет посылки каких-либо фото в течении какого-то промежутка времени после регистрации.

Идея очень хорошая. Только не запрет, а _ограничение_. Схему ограничения можно придумать
* предупреждение "пользователь ещё зелен", и, например текстовая капча гугла - как при "другой город"

**Comment by tebaly** [comment]
А если посмотреть иначе?
* все входящие фото в начале переписки "скрываются" клубничкой - так задумывалось
* если это по прежнему работает :grin: писек не видно, если не нажимать "показать"
* пользователь **предупрежден**, что под бананом возможно интим фото

Тогда в чём собственно проблема?

**Comment by drvalera** [comment]
Так тогда надо ставить галку в бокс, что фото интим, многие наверняка забывают про это

**Comment by tebaly** [comment]
> Так тогда надо ставить галку в бокс, что фото интим, многие наверняка забывают про это

Проверьте пожалуйста. Оно и без галки "по умолчанию" работает.
* все фотографии в начале переписки считаются "интимными" и прячутся за банан/клубничку
* если вы не нажимали "показывать всегда"

**Comment by Premaswarupa** [comment]
Скажу от лица барышень сайта)))Больше всего,достают даже не фотографиями членов(не любо-не смотри),а достают малолетки-возрастные ограничения никого не останавливают,лезут оч настырно и нудно,требуя объяснений,оскорбляя.
Очень актуален момент для лесби-эти просто воют от "желающих направить на путь истинный", )))
Было бы здорово,если бы существовал инструмет ограничения ,сильно рьяных и настырных. Это давало бы чувство комфортности и защищённости) и уменьшило агрессию.

**Comment by Fenslau** [comment]
теблай считает так: если есть вероятность, что тетку 50 лет трахнет подросток лет 18, хотя до этого они не договаривались, то это будет здорово, видите ли ) так что ограничений не ждите )

**Comment by tebaly** [comment]
> Было бы здорово,если бы существовал инструмет ограничения ,сильно рьяных и настырных. Это давало бы чувство комфортности и защищённости) и уменьшило агрессию.

Оно собственно и задумывалось
* написать красным - смотри возраст/город/пол
* просить капчу за игнорирование

Видимо инструмент нужно либо усилить, либо заменить. Но это уже отдельная тема беседы

> теблай

Саша, просто Саша :sweat_smile:

**Comment by Premaswarupa** [comment]
"...Если тетку 50 лет трахнет подросток лет 18, хотя до этого они не договаривались, то это будет здорово...
Здорово(!),если это устроит ,и "тетку", и "подростка"-в каждой избушке,свои погремушки))))
А вот когда меня с души мутит от малолетних мальчиков)))) мне хочется защищенности от настырного мальчишки пытающегося укусить за вежливое "Благодарю,нет")))) и мне кажется,имею право выбирать)))КажНый раз судорожно ищу кнопку "отправить в аут"))))))

**Comment by Premaswarupa** [comment]
Вот задумалась)) а чем кнопка"отправить в аут" противоречит политике сайта НЕ ЗАПРЕЩАТЬ??? Эт же решение пользователя)

**Comment by Fenslau** [comment]
Ну чтооо ты ) Сегодня ты ищешь такую кнопку, а завтра ты уже подумаешь, а мож и правда дать этому юнцу? 
Та с кем я болтал, так и сделала кстати. По итогам вышло так: эффект 50% один из этих молокососов ее не устроил, а с другим есть уже долгосрочная связь. 
То есть практика подтверждает, что порой настойчивость порождает результат.... Поразительно, конечно....
Хотя я сам лично против вседозволенности и я бы ограничил. Дал бы возможность девочкам решить, с кем они хотят а с кем не хотят (общаться). Ну поставила она "только девушки" - ну так пусть только они и пишут. Максимум бы я делал бы уведомление (и то ненавязчиво, раз в день, там), мол вам написало хх парней за сегодня, хотите посмотреть? Ну это на случай если ей скучно станет. А щас получается мужикам все можно, и даже усилий для этого не требуется (мало капчи за пресет секс/вирт/эйдж)

**Comment by tebaly** [comment]
> мол вам написало хх парней за сегодня, хотите посмотреть? 

Вот эту идею нужно проработать. Когда я об этом думал, у меня было две тупиковые ветки
* если пользователь только что зарегистрировался - у него нет контактов
* затем контакты появляются, и пользователь ВИДИТ и знает где их найти
* затем контактов становится очень много

Интерфейс должен быть простым 
* если сразу спрятать все входящие, то пользователь не вдуплит, где собственно контакты, сколько бы ему не намекать, что - вот же они, кликни "тут"
* хотя...
* а если не скрывать, то всесвято ленивый пользователь никогда НЕ спрячет лишние контакты, сколько ему не пиши и не намекай - вот тут кликни, и лишнне "уйдет"

**Comment by tebaly** [comment]
Цель - придумать, чтобы "оно само всё делало"

**Comment by tebaly** [comment]
Как вариант
* теперь у вас больше 10 активных контактов - остальные вот "тут"

**Comment by Fenslau** [comment]
@Premaswarupa
Классная аватарка.

2tebaly: 
вы уже делали так ни раз, я уверен, но - лишним не будет: зайдите на сайт с женской анкетой. 
Не, вам бесполезно. Попросите девушку/близкую подругу/знакомую сделать так - сразу проблема будет ясна. 
"мы не планируем ограничивать" - да не ограничивайте, не запрещайте. 5 минут тишины для нового пользователя у вас не отнимет прав таких. Давайте попробуем внедрить.

**Comment by fenixnoir** [comment]
1. "Мертвое время" штука полезная.
2. Пустынных нарушителей наказывать капчей бессмысленно. Лучше ввести кратковременный бан за жалобу от собеседника. Обидел, 5 минут отдыхай, не читал анкету, 10 минут отдыха, домогался собеседника иной ориентации, 30 минут отдохни. В большинстве случаев это реально может остудить.
3. Ввести возможность отказа от приема фото, и параллельно запретить начинать знакомство с отправки фото.
4. Не афишировать направленность сайта на знакомства именно для секса, тем более, что на сайте есть и несовершеннолетние. К сожалению львиная доля "юнцов" почему-то уверена, что девушка ищущая секс по умолчанию шлюха/проститутка, которая хочет все и сразу. Хотя на самом деле девушки ищущие секс именно его ищут в последнюю очередь (о чем я в поддержке одному пользователю и объяснял).

Итого:
Знакомства для секса, это конечно хорошо, но знакомства для приятного времяпрепровождения, имхо, звучит лучше и предпочтительнее. Новые анкеты не должны быть видны до того, как пользователь отправит первое сообщение (своеобразная активация анкеты, при отправке проверяется значение активации в базе и выставляется в положительное, если уже не стоит). Нужно осаждать ярых эксгибиционистов запретом на фото со стороны собеседника. Особо настырных не нервировать капчей, а давать время охладить свой пыл, с уведомлением о сроке и причине блокировки.
Чего нельзя:
Запрещать контакт, если возрастные или территориальные предпочтения не сходятся. Ограничивать время на заполнение анкеты (всем нужно по разному).

**Comment by tebaly** [comment]
> а давать время охладить свой пыл, с уведомлением о сроке и причине блокировки.

так новая анкета - два клика..

> Новые анкеты не должны быть видны до того, как пользователь отправит первое сообщение

Парням не пишут - парни пишут девушкам. То есть, не отображать анкету парней, смысла нет. А не отображать анкету девушки - так ей никто не напишет.. Парадокс?)

**Comment by mj4444ru** [comment]
На тему фоток, повторюсь...
1) надо не за клубничкой скрывать, а вообще скрывать, отображая только кнопку "показать фото, возможно интимное", пользователь 
2) сделать как на сайтах знакомств, запретить отправлять фото пока девушка не ответила хоть 1 раз...

**Comment by NeverovI** [comment]
Если что-то и следует сделать, то написать сообщение "если вам не нравится собеседник -  нажмите заблокировать".  Несмотря на то, что блокировка удобно расположена, девушки считают какой-то уж наивысшей мерой ей воспользоваться. Они готовы тратить нервы, возмущаться, что их анкету не читают, что админы не способны допилить сервис, хотя это делают кодеры, но на блокировку у них какое-то табу. Член прикрытый бананом вещь не однозначная. Ну а вдруг там не член, а какая-нибудь шутка.  Так  что блоковка посыла фото до первого ответа разумна.

**Comment by tebaly** [comment]
> Очень актуален момент для лесби-эти просто воют от "желающих направить на путь истинный"

Мне кажется, проект пойдет по пути "онли гетеро". В лучшем случае появится "клон" для "онли гомо". Окончательного решения ещё нет, но планы были такими. Изначально подразумевался секс между парнем и девушкой. Есть масса технических сложностей(фейки девушка/парень) которые продавливают в сторону именно "онли гетеро". А иначе, оснований банить фейков просто не будет.

По остальному - решение в предстоящей обнове.

**Comment by tebaly** [comment]
В целом идея реализована #406. На счет запрета фоток пока работаем. 
* отправить его вероятно можно будет всегда, но вот увидеть станет сложнее, если вы ещё толком не общались. А для активных контактов никаких сложностей не добавится
