### ISSUE TITLE
убрать чек-бокс "только онлайн" из поиска

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#242]
Если этот флаг не работает, то может его убрать со страницы? Тем более при новом принципе сортировки.

**Comment by Fenslau** [comment]
или же уже сделать его рабочим на радость юзеру?

**Comment by drvalera** [comment]
было бы очень полезным

**Comment by tebaly** [comment]
```
<нострадамус=вкл>
  планируем заточить сервис на "знакомство через общение", а не поиск
<нострадамус=выкл>
```

**Comment by Fenslau** [comment]
Ну практика показывает, что общение необходимо пользователям. Опять же все эти вирты, обмены фотками, дроч. Поэтому они переживают, когда не могут определить, онлайн или нет. Им кажется, что даже если у кого-то анкета просто открыта и висит сутками, вероятность ответа будет больше, чем если сообщение отправить кому-то оффлайн.

**Comment by inquisitor6789** [comment]
> планируем заточить сервис на "знакомство через общение", а не поиск

а как найти с кем общаться то? будете спамить всем подрят типа "Эхой, новый юзер хочет подрочить!!! Кто согласен?"
Так чтоли?

**Comment by tebaly** [comment]
Да :relaxed:

Это же так весело

**Comment by Fenslau** [comment]
> "Эхой, новый юзер хочет подрочить!!! Кто согласен?"
Так чтоли?

В принципе, так сейчас примерно и происходит, ггг

**Comment by tebaly** [comment]
attach #412
