### ISSUE TITLE
Право на ошибку у Пользователей

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#243]
Сейчас
* если пользователь загрузил фото
* отправил его кому-то
* затем через несколько минут удалил загруженное фото

То фотография выходит из области контроля администраторов сообщества, и остается только под контролем системного администратора ещё некоторое время(для предупреждения противозаконных действий)

Есть возможность
* отображать "удаленные фото" в профиле нарушителя

У администраторов появится возможность "видеть" дополнительную информацию по совершенным действиям пользователя. Возможно для организации подобного доступа придется выделить уровень "Системный администратор" в администрировании

Такое действие делает общение чуть менее приватным(содержание удаленных фото может быть некоторое время доступно системному администратору), но повышает безопасность того самого общения и нахождения на сайте.

**Comment by Fenslau** [comment]
Время от времени попадаются такие пользователи, которые удаляют фото довольно быстро. Их немного, но они есть. Непонятно, знают ли они об этой особенности работы системы, или же удаляют фото по каким-то другим причинам...

**Comment by tebaly** [comment]
Ошибся человек, понял что ошибся, и удалил))

**Comment by Fenslau** [comment]
Аа... Ну это да. Но некоторые удаляют специально через несколько минут после отправки. Видимо из соображений конспирации. 
Но попадались такие пользователи (девушки кстати, парням то вообще пох), которые удаляли фото регулярно. То есть иногда при жалобе в профиле их уже не видно, иногда даже и пожаловаться не успевали, одно замечание висело только (уж не знаю, что там она такого присылала). А моэет быть это вообще были фэйки, кто знает.

**Comment by sexifixy** [comment]
> А моэет быть это вообще были фэйки, кто знает.

Таки да. От этого и вопрос. Сложно принять правильное решение. Хочется знать мнение участников.

**Comment by Premaswarupa** [comment]
Мне кажется,что и удаляют резко во избежание жалоб. И большинство таких случаев ,как показывает практика,пользуют "рецидивисты"(создающие анкеты одну за другой),обычные пользователи редко почищают фото)

**Comment by Fenslau** [comment]
если будете разрешать, поставьте время даже для тех кому разрешите смотреть около нескольких дней, не больше.

**Comment by sexifixy** [comment]
> большинство таких случаев ,как показывает практика,пользуют "рецидивисты"

солидарен на 146%

**Comment by Premaswarupa** [comment]
А в плане на сколько оставлять ,мне кажется и суток достаточно) даже если будет 2-3 человека со спец статусом и таким уровнем доступа,то за это время,при наличии жалоб,сложно будет пропустить. На явных "рецидивистов" пачками замечания строчат)))
А для обычного пользователя) не злоупотребим нарушением прав на конфиденциальность)

**Comment by tebaly** [comment]
Грамотно) Внесу поправку
* конфиденциальность ни чуть не задевается, в общем ее смысле. Нам поступает жалоба с содержанием фотографии. И то, что ее сейчас можно удалить, это даже некорректное поведение системы)) Мы же имеем право хранить ее(жалобу) сколько потребуется :simple_smile:

Подытожу
* единогласно
