### ISSUE TITLE
инфа в истории жалобы

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#244]
не бох весть конечно какой бачок, а может я чего-то просто недопонимаю, но:
Есть у нас допустим исходное сообщение:
http://sexoo.ru/history/message/109046611/
заходим и видим, что все понятно, кто скинул в арбитраж, с каким комментом, то се.
Но есть куча таких же точно, но по ним этой инфы увы не выловить.
http://sexoo.ru/history/message/86878734/
А нельзя ли эту всю историю на все идентичные сообщения распространять?

**Comment by sexifixy** [comment]
Привет ;) Можно. Сейчас вертим сервак фоток, потом ротатор прокинем и начнем исправлять всю эту вакханалию)

**Comment by tebaly** [comment]
Реализовано
