### ISSUE TITLE
жалуются, что не видно фоток

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#245]
Заметил, что сейчас они становятся не видны в диалогах, если прошло какое-то время. Причем, как те, что я отправлял, так и те, что были отправлены мне. Свои я точно не удалял. Вместо них теперь вот так:
http://hdd.tomsk.ru/desk/kerbyrgq#
Если нажать на "показать", ничего не происходит. Два дня назад все отображалось норм.
upd: впрочем сейчас даже у меня все фотки отображаются так, свежие, не свежие, неважно! Вчера вроде такого еще не было..) Юзер негодует и волнуется, как всегда )

**Comment by tebaly** [comment]
Их реально не видно. Я сервер фоток поломал в 3 ночи. 
Починил

**Comment by tebaly** [comment]
Новое поведение
* ссылка на фото будет "работать" определенное время 
* определять время будем постепенно, возможно уменьшим до 1-5 минут

Раньше
* ссылка "работала" для получателя до времени удаления записи о фото (неделя-две)
* при условии сохранения некоторых параметров 

Передать ссылку кому либо уже давно невозможно. Новое поведение сложно обосновать, но оно уменьшит время доступности фотографии к загрузке. Хотелось уменьшить это время до нескольких секунд(время для первоначальной загрузки фотографии) после чего фото уже становится недоступно.

**Comment by Fenslau** [comment]
Секунд то точно невозможно. Юзер не успеет нажать и опять будет думать, что что-то не работает.. Мож хоть пояснять что-то текстом тогда? там типа срок истек, то се. 5 минут, не меньше ) Ну и тогда оффлайн обмен фотками идет лесом, получается.

**Comment by tebaly** [comment]
Так еще не реализовано :blush: планы. Может и отказаться придется, так как КПД реализации мал - оно не нужно в целом, передать ссылку на фото почти не реально, фото не откроется у получателя. Но скачать и отправить фото всегда можно..

**Comment by inquisitor6789** [comment]
а вот тут встает вопрос модерации... Будут ли фото доступны в профиле? Если нет, то как тогда проверять их фейковость?

**Comment by DrAllcome** [comment]
Можно прикрутить функционал как на badoo.com. При отсылке фото, указывается, сколько она будет висеть в чате. Там вроде 1м.-3м.-5м.-всегда.

И да, как модерировать?

**Comment by tebaly** [comment]
Нет. Модерации фотографий нет, и никогда не будет. Речь сугубо о жалобах на содержание фотографий. 

> Можно прикрутить функционал как на badoo.com. 

Надо посмотреть

**Comment by DrAllcome** [comment]
Да я неправильно выразился. Конечно же речь о жалобах на фото.

**Comment by tebaly** [comment]
Технически это затрагивает только "ссылку" - она выдается каждый раз новая.
* раньше она была одного и того же содержания долгое время
* теперь время взяли под контроль
* сгенерированная ссылка будет действовать ограниченное время

В профиле да в в целом на сайт это никак не сказывается.
