### ISSUE TITLE
модер с отрицательным рейтингом может голосовать?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#247]
Есть модер http://freedomsex.net/argue/profile/9152070/ с рейтингом -10
есть жалоба http://freedomsex.net/history/message/109404237/ по которой он проголосовал.
это нормально? или ему был понижен рейтинг после голосования?

**Comment by Fenslau** [comment]
это же первый модер (то есть сам пожаловавшийся), разве не?

**Comment by inquisitor6789** [comment]
да, это его жалоба. Как простой пользователь он может жаловаться сколько угодно, но действовать как модератор не должен (из-за рейтинга). Кроме того, если мне не изменяет память, то некоторое время назад вроде был внедрен функционал закрывающий возможность голосовать и выносить решение по свои жалобам. Или я что-то путаю?
тем не менее вопрос остается открытым - может модер с отрицательным рейтингом голосовать?

**Comment by Fenslau** [comment]
Как я понял, он и не голосовал фактически, нижний же модер - всегда начальный. Хотя да, вопрос открытый. 
http://sexoo.ru/history/message/109544344/
второй снизу -300 почти. Врядли он слетел так за одну ошибку...

**Comment by tebaly** [comment]
По секрету:
* голосовать может, но голос не учитывается

В этом есть Глубинный смысл.

**Comment by tebaly** [comment]
Да. Подавший жалобу в низу
* изначально хотелось скрывать такого рода информацию, чтобы пожаловавшийся оставался инкогнито, но пока не получается..

**Comment by inquisitor6789** [comment]
> изначально хотелось скрывать такого рода информацию, чтобы пожаловавшийся оставался инкогнито, но пока не получается..

позвольте, а нахрена это делать если жалобщик виден в профиле того, на кого пожаловались?

**Comment by tebaly** [comment]
> а нахрена

Так поэтому и не получается - если скрывать, то всё. А на практике оно как оказалось очень нужно.
