### ISSUE TITLE
А точно сообщения нормально ходят?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#248]
http://freedomsex.net/admin/sethelp/?id=152464&ln=0
Судя по всему к юле попали все сообщения от пользователя, которые были адресованы другим. И я не уверен что от одного пользователя.

**Comment by tebaly** [comment]
Спасибо. Я посмотрел другие контакты `юли` подобного больше не встретил. Сейчас всё возможно...

**Comment by tebaly** [comment]
Если подтвердится предположение, дайте знать пожалуйста
