### ISSUE TITLE
У нас новый сервер для базы данных :)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#249]
Тестируем полет. Должен быть раз в шесть быстрее старого, посмотрим. 
* перенос проходил не совсем гладко :unamused:

Благодарю за терпение.

**Comment by tebaly** [comment]
Рапартую: по части тормозов сайт вроде вытянули. Если вы заметите просадку по части скорости загрузки сайта до ощутимо не комфортного уровня, пожалуйста, сообщите.

**Comment by inquisitor6789** [comment]
Жалуются на то что фото не показывает http://freedomsex.net/admin/sethelp/?id=152535&ln=152534

**Comment by tebaly** [comment]
@inquisitor6789 ну работают же фотки. Отправил-Принял, работает) 
я направил ей запрос, чтобы уточнить проблему
