### ISSUE TITLE
во всех анкетах время последнего захода "давно", если не онлайн.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#250]
сабж.

**Comment by tebaly** [comment]
fix

**Comment by Fenslau** [comment]
Конечно ерунда на палке, но на всякий случай сообщу, что если открывать анкету через поиск обычный, то фикс, да. А если извратиться и сначала открыть профиль нарушителя, а потом в нем нажать на имя - то все еще "давно" ))) Ну это так уже, мелочи тонкости... ) Вдруг какой баг рядом порылся, скучно будет - посмотрите )

**Comment by tebaly** [comment]
> А если извратиться и 

У меня не получилось. Поможете?)
