### ISSUE TITLE
Лог всех жалоб от пользователя

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#251]
Предлагаю внедрить ссылочку в профиль допустим, с помощью которой будет понятно, на кого пользователь жаловался за все свое время. И чтобы все эти жалобы его были отображены в этом подразделе. Ничего я в этом криминального не вижу с точки зрения конфиденциальности, а вот польза может быть.

**Comment by tebaly** [comment]
Да, конечно. У нас было два равнозначных пути развития
* всё и для всех анонимно
* анонимно только для Пользователей

Теперь идем по второму, будем агрегировать всю необходимую информацию в профиле. Можно пока сделать как со "статусами", по отдельной ссылке открыть список. А можно перенести в раздел "разработчикам" по типу "истории" для жалобы. Назвать например "как-нибудь"...

**Comment by Fenslau** [comment]
перенести в тестовый раздел (как было с ответами юлии) - да там и оставить ) Я стал сомневаться, что админы кроме Сергея, Юлии и еще парочки, которых я даже не знаю - эффективны. Может быть это им и не нужно.

**Comment by inquisitor6789** [comment]
Со сменой компа я ту ссылку потерял. Может имеет смысл её куда-нибудь в раздел "разработки" поместить?

**Comment by tebaly** [comment]
Ok

**Comment by Premaswarupa** [comment]
Идея интересная,на мой взгляд, дает массу дополнительной информации,я бы точно регулярно ныряла по такой ссылке) смущает ток одна мысь,что пока буду изучать историю для принятия решения,придет новоиспеченный админ)))) и раскидает все по разным углам))

**Comment by inquisitor6789** [comment]
не, обычно такие перцы достаточно быстро выявляются и караются

**Comment by tebaly** [comment]
> **на кого** пользователь жаловался за все свое время

А собственно для каких целей :hushed:
