### ISSUE TITLE
Добавить автоопределение мата и грубых слов

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#254]
Как бы вы хотели реализовать подобное? Встречали ли вы подобное на других ресурсах, как это сделано там?

Предложение:
- при начале знакомства активировать "фильтр" матерных слов и грубости
- выдавать предупреждение Пользователю о содержании грубости в сообщении

**Comment by Premaswarupa** [comment]
А не будет ли это работать как "обрезание" в принудительном порядке?) эт  мысль вслух о фильтре)

**Comment by tebaly** [comment]
Намеренно упустил детали реализации)) 
* работать будет только по принципу уведомления
* типа, привет друг, у тебя тут маты в сообщениях, не хорошо как-то

Так как подобные фильтры в запретительной форме легко обходить

**Comment by inquisitor6789** [comment]
не, ну че за вопросы? на многих форумах реализован антимат. стащить оттуда код не получится?
или тут вопрос больше про наполняемость словаря?

**Comment by fenixnoir** [comment]
Принудиловку нельзя, ибо мат, как это не прискорбно лично для меня, для многих стал важным элементом сексуального общения и игр. А в виде предупреждения... И что получается? Придется несколько раз подтверждать отправку? Спасибо. Меня жутко бесила капча 2 октября, приходилось до 20 раз подтверждать отправку. Шутка ли? Мое Солнце дала мне телефон через 10 сообщений, но для этого мне пришлось тыкать клаву и мышь в течении 3 часов. Я уже готов был все послать и уйти на привычную Мамбу. Пусть лучше мат остается на модерах.
В конце концов, проект влюбляет в себя именно простотой и бескорыстием. Да и тем, кто нашел свое счастье но полюбил проект есть удовольствие быть его модератором.

**Comment by NeverovI** [comment]
Мату быть. Не надо трогать мат. По хорошему и модерам запретить его трогать. Т.е. если предложение оскорбляющего характера, то наказывать, если нет - пропускать, а ни как не опираться на наличие мата.

**Comment by tebaly** [comment]
Спасибо. В этом ключе и будем пытаться разрулить.

**Comment by tebaly** [comment]
Нашел вот эту регулярку: http://ermouth.livejournal.com/618514.html - но дает много ложных срабатываний типа - корабля, сабля. Давайте делать фильтр вместе :relaxed:

**Comment by tebaly** [comment]
Добавлено. Должно работать. Из-за постояннох обнов в полную силу будет реализовано постепенно. Проверить можно на форме сообщения в анкете

**Comment by tebaly** [comment]
![default](https://cloud.githubusercontent.com/assets/9466814/26678850/32c3b60c-46db-11e7-9c90-8baf056e4b9f.png)
