### ISSUE TITLE
пополнение рядов резидентов

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#255]
Всем привет!
Смотрел я надысь список админов и поразился что Женя (aka Fenslau, он же http://freedomsex.net/argue/profile/11877811) до сих пор не в списке резидентуры.
Может уже пора причислить его к сонму святых?

Кто за? Кто против? Воздержавшиеся?

**Comment by Premaswarupa** [comment]
За!!!)))

**Comment by tebaly** [comment]
Это не так) :grimacing:

По случайности для него было включено "скрытое" резидентство
* доступны все возможности и привилегии резидента
* в списке резидентов не отображается 

Если есть желающие, обращайтесь))

**Comment by Fenslau** [comment]
Спасибо. .. 
Серьезно, я был рад когда заметил. 
Заранее извиняюсь, что все совпало это кое с чем.
У меня наметились некоторые трудности в жизни, а именно в поиске работы или что-то вроде того, долго рассказывать короче. В общем, не обессудьте, если я буду какое то время неактивен.
