### ISSUE TITLE
заблокирован или нет

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#257]
есть анкета http://freedomsex.net/userinfo/profile/3938401 по которой было вынесено решение о блокировке. Но нет маркера о том, что анкета заблокирована. И в списке она отмечена как не заблокированная.
Косяк или фича?

**Comment by tebaly** [comment]
Я думаю это временная шибка за период "обновления" сайта. Подобных это ошибок больше быть не должно. Спасибо за понимание. Прошу прощения за доставленные неудобства. Сообщите пожалуйста о вновь выявленняеых ошибках.

Часто, вместо того, чтобы исправить баг локально, мы тянем системную область - это требует и большего времени и большего объема работ(что иногда порождает новые баги). В связи с этим, мелкие баги могут закрываться так же долго как и системные. В таких случаях мелкий баг также тяжело закрыть, как и системный. 

Спасибо.
