### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#258]
Есть переписка с Юлей http://freedomsex.net/admin/sethelp/?id=152625&ln=0
Отбрасывая эмоции обнаружилась проблема - пользователь не может оставить жалобу если в переписке не остается ни одного сообщения.
Вроде какое-то время назад подобное уже обсуждалось. Будут ли сняты ограничения? Например если сообщений в переписке нет, но была жалоба на сообщение все таки позволять оставлять замечание к анкете.

**Comment by tebaly** [comment]
Да. Добавим, спасибо. Не дошли видимо еще просто.

**Comment by tebaly** [comment]
> пользователь не может оставить жалобу если в переписке не остается ни одного сообщения.
если просто нажать "удалить" сообщение - оно удаляется и всё, в переписке пусто..
* чтобы так не происходило, "удалить и наказать"

**Comment by tebaly** [comment]
Там в коде это сообщение никак иначе не выдается - жесткое **и**(если есть жалоба от меня, принять). Вопрос лишь в части "от меня" можно заменить на "есть жалобы"... но здесь ещё подумать нужно. Например - рандомно кликаем по всем анкетам пытаясь отправить жалобу "с отсутствием переписки" - лазейка для спама..

```
 if( !$count_reply && !$count_mybun ) {        // Не обнаружено сообщений собеседника адресованных вам.
  echo '{"error":"message","text":"Замечание не может быть опубликовано, так как собеседник с вами не общался. Ни сообщений вам ни жалоб от вас не обнаружено.","hash":"'.time().'"}';
 }

**Comment by tebaly** [comment]
Я удалю проверку `$count_reply` но это особо дело не поправит - если не было жалобы на сообщение, замечание не отправится всё равно.

> но была жалоба на сообщение все таки позволять оставлять замечание к анкете

С той оговоркой, что жалоба была отправлена этим пользователем.

**Comment by tebaly** [comment]
Тестирую обновление модуля замечаний. На пару дней отключен показ списка замечаний в анкетах. Будет изменен принцип замечаний. Не всем понравится, но по другому нельзя - время такое...

**Comment by tebaly** [comment]
Выкатил модуль отправки замечания везде _кроме главного зеркала_. Завтра к полудню и туда закину.

**Comment by tebaly** [comment]
#318
