### ISSUE TITLE
уменьшим кол-во фейков

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#259]
в рамках эксперимента решил я зайти на сайт не под своим логином.... И был немного удивлен следующим - если не заполнять свои анкетные данные, то при  поиске тебе автоматом присваивается женский пол. Я полагаю, что именно этим объясняется большое кол-во фейков на сайте (если честно, то у меня уже мышка устала их банить).
Может стоит поменять алгоритм присвоения пола по умолчанию?
Есть несколько вариантов:
1. присваивать по умолчанию мужской пол
2. в принудительном порядке заставлять пользователя указывать данные о своей половой принадлежности

первый вариант прост в реализации (поменять одну цифру)
второй вариант более правильный с т.з. жизни - ты сначала должен себя идентифицировать. Но идет в разрез с идеей автоматической регистрации

**Comment by Fenslau** [comment]
> 1. присваивать по умолчанию мужской пол

заодно будет возможность у пользователя остальные данные заполнить, так как кроме Юлии никто не напишет в первое время..
А я думал, что пол присваивается рандомно...

**Comment by inquisitor6789** [comment]
в поиске выставляется "я девушка ищу парня". наверно отсюда ноги растут

**Comment by tebaly** [comment]
Те фейки о которых вы говорите, они реально "ничего не подозревающие мужчины, которым сайт назначил женский пол"? Или это "анкеты парней, у которых указано что они девушки. Которые пишут и отвечают от лица девушки"?

Как вы верно заметили, это "убьет" идею автоматической регистрации. Но действительно ли её смертью удастся решить проблему фейков?

**Comment by inquisitor6789** [comment]
Второй вариант убьет. Первый - нет.
Что же касается намеренностм действий, то очень много случаев когда анкете 20 минут, а уже сыплются жалобы.
Полагаю, что они в свою анкету не лезут, а сразу пользуются поиском. Плюс мое предложение позволит накинуть им капчу автоматом за то, что пишут не тем (по признаку пола)

**Comment by tebaly** [comment]
> 1. присваивать по умолчанию мужской пол

Девушкам свойственно осторожничать/стесняться и, пардон, тупить. Я в последнем не о умственных способностях, а о том, что в вопросах "интерфейса", что где нажать и где поменять - они не то что бы найти не могут, а часто попросту вообще даже не ищут. 
* парни заинтересованы заполнить анкету правильно и найти как это сделать
* девушки - нет, и не делают этого в большинстве.

**Comment by inquisitor6789** [comment]
откуда такая уверенность? Вы проводили опрос? Или это просто догадка основанная на собственном поведении?
не, я согласен, что есть определенная доля пидорчуков типа этого http://freedomsex.net/userinfo/profile/14555738/ которые намеренно выдают себя за бабу. 
Но есть так же и те, кто сначала начал переписку, а только потом сменил данные в анкете. Типа этого http://freedomsex.net/userinfo/profile/15308286 (кстати удивлен почему его не забанили).
Как раз для того, чтобы анкет второго типа стало меньше и нацелено мое предложение.

**Comment by tebaly** [comment]
> Но есть так же и те, кто сначала начал переписку

> доля пидорчуков

> http://freedomsex.net/userinfo/profile/15308286

`Подставлю свою попу под твой член`

Этот тоже пидорчук :cry:

---
Статистика нужна в другом
* какое количество анкет фейков - фейки
* а какое - не фейки - анкеты девушек в которых по случайности "оказался" парень

Да, у меня тет точных данных, есть ощущение из наблюдений (95% фейк=фейк)
* более 80% фейков - реально фейки изначально
* 15% профи фейки, когда понять, что фейк удается далеко не сразу
* что-то около 5% _случайно_ зарегавшие анкету девушки и долго не могут это исправить

Какой расклад по вашим наблюдениям?

**Comment by tebaly** [comment]
Идея проектка в истоках была:
* вы делаете бумажку со ссылкой на сайт
* клеите ее на видном месте
* девушка заходит на сайт по ссылке

Степень "аккуратности" у такой девушки будет наивысшая - она просто не нажмет ни кнопки "регистрация", ни кнопки "заполнить анкету". 

Вы же рассуждаете со стороны посетительниц, которые нашли сайт через интернет
* мотивация у этой группы совершенно иная

**Comment by inquisitor6789** [comment]
> Этот тоже пидорчук :cry:

так я и не спорю. Но он хотя бы честный пидор :-)

> а какое - не фейки - анкеты девушек в которых по случайности "оказался" парень

количество таких анкет исчезающе малО. На моей памяти было порядка 10 (десяти).

> более 80% фейков - реально фейки изначально

а изначально фейки они по причине, что им изначально присваивается "неправильный" пол. Если это поправить, то они будут писать от лица парня. Это как минимум справедливо по отношению к другим пользователям. Ну и награда в виде капчи им будет обеспечена (или нет?).

> вы делаете бумажку со ссылкой на сайт

может это и работало несколько лет назад, но сейчас это выглядит как минимум забавно. Можно попробовать поспрашивать народ кто и как нашел этот сайт. Почему-то у меня почти 100% уверенность, что 99.9% нашли его через инет.

**Comment by tebaly** [comment]
> Почему-то у меня почти 100% уверенность, что 99.9% нашли его через инет.

Так а их почти поровну
* Переходы из поисковых систем - 46,7 %
* Прямые заходы - 31,3 %

И находят во многом по домену сайта и названию
* секс знакомства - 58K
* freedomsex - 38K

Но не об этом сейчас. А вы меня запутали

> количество таких анкет исчезающе малО. На моей памяти было порядка 10 (десяти). 

Я имел ввиду анкету, в которой по случайности указано "девушка", в то время как Пользователь - парень, который не может долго это исправить. Моё мнение:
* адекватный пацан, обнаружив такое, относительно быстро найдет как это исправить. 
* и 146% - не станет писать пацанам от лица девушки

> то они будут писать от лица парня

`Разруха не в клозетах - разруха в головах` - вы никак не заставите пидорчуков осознавать, что они не пидорчуки. Я думаю, они просто будут исправлять пол на женский.

Ваше предложение понятно, но оно прольёт очень много крови, при том, что основной проблемы не решит. Это подействует только на малую часть "случайных фейков", а пидорчуки как были, так и останутся.

**Comment by inquisitor6789** [comment]
> Переходы из поисковых систем - 46,7 %
Прямые заходы - 31,3 %

из этого я могу сделать только один вывод - 31.3% наши постоянные посетители. Запомнили они адрес или закладку сделали роли не играет.

Не хотите делать не надо. Я особо не настаиваю. Но можно было бы это с самого начала сказать.

**Comment by tebaly** [comment]
В спорах рождается истина ;)

* ставить по умолчанию мужской пол - нет
* обязать указывать пол в ручную - нет

Напротив:
* можно просто продумать алгоритм простановки пола в анкете
* например "навязчиво" спрашивать
* либо уведомлять, что Пользователь теперь "такого" пола
* и если хочет поменять, то делается это "вот так"

Благодарю вас за ваши идеи. Всё о чем говорилось будет реализовано. До тех пор тикет нужно держать открытым :yum:

**Comment by inquisitor6789** [comment]
Блин, ну что тут думать?!! Выводить вопрос и пока не ответит не давать ничего делать на сайте. Или у вас есть в заначке телепатия?

**Comment by Fenslau** [comment]
А чем плох муж. Пол по умолчанию? Мол девки не разберутся? А есть такая вероятность что медик поступает так: заходит, такой.... Так... Надо бы кому нибудь написать.... Хм. Так у меня уже имя Алена и пол женский!? Бинго!!! Им пишут сами. Поэтому то они сразу признаются.

**Comment by inquisitor6789** [comment]
не совсем так. Насколько я понял, то пока не выполнишь поиск тебе никакой пол не присваивается. Поищи женщин (по крайней мере в москве) и увидишь там несколько записей имя - "Девушка" ищет парня от 17 до 23. Это все значения по умолчанию. И вот после этого им и начинают писать.

**Comment by tebaly** [comment]
Да, так и есть. При первичном поиске, Пользователь заполняет первичную форму "авто-регистрации". Данная форма по умолчанию гласит:
* Я девушка, ищу парня в возрасте приблизительно 20 лет

Вы меня натолкнули на мысль о том, чтобы просто просить Пользователей "выбрать" вариант с полом в форма первичного поиска. Это элементарно и не сильно навязчиво. От этого будем и отталкиваться. Спасибо.

**Comment by tebaly** [comment]
А лучше сделать первичную форму интерактивной. В которой на первом этапе нужно указать пол.

**Comment by inquisitor6789** [comment]
> А лучше сделать первичную форму интерактивной. В которой на первом этапе нужно указать пол.

`Блин, ну что тут думать?!! Выводить вопрос и пока не ответит не давать ничего делать на сайте. Или у вас есть в заначке телепатия?`

**Comment by Fenslau** [comment]
Вообще, судя по количеству этих педиков-фэйков (в последнее время, мне кажется, особенно), у них не должно быть особых проблем чтобы перезнакомиться друг с другом (если конечно это не один и тот же всё)...

**Comment by Fenslau** [comment]
Сейчас зашел с новой анкеты. Представил что я педик ))))
Ну сразу страница Вы: Парень/Девушка
Выбираю парень.
Кого ищете - чуть ниже - выбираю парня.
Вот результаты поиска. Мне пришлось пролистнуть пару страниц, чтобы по характерному бледному цвету понять, что моя цель находится здесь. Но это я искал по всем городам...
Но неважно. ... 
Может быть сделать так, что когда парень ищет парня или девушка ищет девушку, их цели отображались первыми в списке? Это сложно?

**Comment by inquisitor6789** [comment]
> Выбираю парень.

а ты не выбирай. Сразу жми на найти. И результат тебя немного удивит :-)

**Comment by tebaly** [comment]
Обновлено 
* при первичном поиске Пользователь обязан указать пол.

Пожалуйста, если вами будет обнаружена не корректная работа сайта, сообщите мне, я всё исправлю :)
