### ISSUE TITLE
Сервис отправки почты не работал

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#260]
Сервис отправки почты частично не работал, письма подтверждения емайл не отправлялись.

**Comment by inquisitor6789** [comment]
http://freedomsex.net/admin/sethelp/?id=152784&ln=0
а не отвалился ли сервис опять?

**Comment by tebaly** [comment]
Вероятно, он шалит. Проверить легко:
* в настройках Анкеты "Ваши логин и пароль скрыты" кликнуть _выслать на эл. почту_
* появится уведомление "Письмо отправлено, проверьте почтовый ящик."

Письмо придет в течении 10 сек - значит работает.

На данный момент всё в норме
