### ISSUE TITLE
в арбитраж из бездны

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#261]
Всем привет!
В последнее время участились не мотивированные сбросы в арбитраж из бездны фраз типа "да", "привет" и других популярных. В связи с этим забивается список принятых решений.
Хотелось бы видеть одно из следующих
1. группировка одинаковых фраз в списке принятых решений
2. запрет всем кроме резидентов скидывать в арбитраж из бездны

**Comment by tebaly** [comment]
второе проще и вкуснее)

**Comment by tebaly** [comment]
Реализовано.

У нас на сегодня не разработано ограничений для "централизованной" системы Администрирования, поэтому все кроме резидентов теперь увидят вместо обычного для бездны
`Раздел проектируется или на техническом обслуживании`

Давайте оценим технически такой шаг
* мне казалось, бездна нужна в очень редких случаях

Имея практические наблюдения, давайте обсудим дальнейшую перспективу развития данного раздела. Давайте с чистого листа попробуем дать характеристики того
* зачем оно
* для кого
* степень актуальности/необходимости

Благодарю.

**Comment by inquisitor6789** [comment]
> мне казалось, бездна нужна в очень редких случаях

так и есть. Однако, она бывает очень полезна. Например когда пользователь жалуется на каждое сообщение, а криминал есть только в одном из них. И оно попадает в бездну.

> зачем оно

см предыдущий ответ

> для кого

по идее для админов, но как показала практика никто из админов не резидентов не задумывается над предназначением этого раздела. Соотв отсюда и проблема. Я в свое время писал readme для него, но что-то его не видно на сайте.

> степень актуальности/необходимости

однозначно необходимо (см предисторию создания раздела и ответ на первый вопрос).
Актуальность?... вот тут все сложно. В 99% случаев зловредов отлавливаем по жалобам, которые идут по нормальному процессу.

**Comment by Fenslau** [comment]
Мда, как-то негласно сложилось, что оттуда достаем только явный "криминал". Собственно я - за это.

**Comment by inquisitor6789** [comment]
а смысл доставать оттуда другое? Бездна собственно для этого и задумывалась

**Comment by tebaly** [comment]
>  Я в свое время писал readme для него, но что-то его не видно на сайте.

Текст сохранен и залит на сервер уже давно. На него просто нет ссылки. Планировалось добавить как "Подробнее", но ввиду сырости самого инструмента решили доделать всё сразу "по случаю".

**Comment by tebaly** [comment]
чуть поправил, раскатил
