### ISSUE TITLE
заблокирована анкета

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#263]
http://sexoo.ru/userinfo/profile/6377413
А может добавить пояснения, за что блокировано, чтобы каждый раз разрабов не дергать? Один раз было ошибочно заблокировано, так у меня теперь паранойя - везде мерещатся невинные юзеры, которые попали под раздачу )

**Comment by inquisitor6789** [comment]
по этой анкете могу сказать, что у нее был конфликт с другим юзером. И может с горяча она что-то ляпнула
А так это вменяемая тетка.

**Comment by tebaly** [comment]
Здесь системная проблема:

ЗАПРЕЩЕНО ЦИТИРОВАТЬ И ПЕРЕСЫЛАТЬ СООБЩЕНИЯ СОДЕРЖАЩИЕ НЕДОПУСТИМОЕ ПРАВИЛАМИ САЙТА СОДЕРЖАНИЕ(ВКЛЮЧАЯ ПРОТИВОЗАКОННОЕ СОДЕРЖАНИЕ, СОДЕРЖАНИЕ С ПРИЗНАКАМИ ПРОТИВОЗАКОННОСТИ)

Система не различает "первоисточника" - блокируются все новые и ранее зарегистрированные анкеты Пользователей употребивших непотребства в общении.

В данном случае Пользователь цитировал 
> Ты сука конч***ая вообще ох**а. Ты ещё там что-то блокируешь. Если я тебя достану.Я тебе <...>

Я понимаю - Пользователь НЕ виноват, но система просто не может работать иначе. В случаях ДОСЛОВНОГО цитирования - анкета блокируется практически в тот же момент. 

Ваши предложения.

**Comment by tebaly** [comment]
Случай произошел в следствии "системно-архитектурных особенностей" - на данный момент система обратной связи/помощи полностью интегрирована в систему обмена сообщениями - в ней применяются все те же правила антиспама/автоблокирования. Пользователь отправил цитату уже заблокированного сообщения _помощнику_ и система за это заблокировала этого Пользователя. 

Изначально хотелось "упростить" обратную связь для пользователей - совместить ее с системой сообщений. Сейчас стало понятно, такой подход не оптимален и придется систему изменить. После редактирования системы помощи подобные случаи не повторятся.

Приношу свои извинения. На сколько я понял, Пользователь сам(а) хотел(а) заблокировать свою анкету.


## ОФФТОП - #мысливслух

У нас давно написана _памятка_ в виде статьи блога, про принцип предупреждения агрессии. 

http://freedomsex.net/блог/предупреждение-агрессии [исходники](https://github.com/freedomsex/docs/blob/master/blog/8_admin_princip.txt)

Данная статья написана в первую очередь для Администраторов - так как система администрирования развивается в сторону _децентрализации_, решать конфликты Администрирования фактически некому, а вмешиваться в отношения Пользователей??... 

Пользователям также рекомендовано _избегать_ конфликтов. Сказано о том, что нельзя отвечать оскорблениями на оскорбления. Во-первых, к хорошему это приводит никогда.. Во-вторых, как модераторы сайта, так и система сайта наказывают за оскорбления всех, без выяснения причин, оправданий и аргументов.

---

Конкретно по этому случаю - я не искал причин подобных высказываний, но вот ну не бывает на ровном месте, вот таких вот речевых оборотов.. Чтобы понять причину - нужен доступ к личной переписки, а у нас его нет. Нужно беседовать сначала с одним, потом с другим, чтобы не было клеветы. Занять место судьи? А зачем?.. Цель? Создать сервис _регулирования отношений Пользователей_ - свой собственный суд с преферансом и мадемуазелями?)

Много правильнее, имхо, запретить отвечать оскорблениями на оскорбления. Рекомендовать игнорировать любые провокации. В иных случаях решать _реальные вопросы_ в реальности. Для этого есть соответствующие органы, структуры и социальные институты. Мое мнение - модераторы/администраторы не имеют ни морального, ни какого бы то ни было законного права вмешиваться в отношения Пользователей сайта. И исходя их этого
* создание какого-то сервиса _регулирования отношений Пользователей_ не возможно в принципе.
* похожие случаи будут происходить регулярно
