### ISSUE TITLE
Новые косячки

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#265]
Разбивайте сами на отдельные обращения.

1) Я ещё ничего не вводил, просто зашёл
![fds1](https://cloud.githubusercontent.com/assets/9354685/18559236/d200823a-7b8f-11e6-81a0-a041eec5fda4.png)
![fds2](https://cloud.githubusercontent.com/assets/9354685/18559277/03c5d536-7b90-11e6-858b-8e432bdd455c.png)

2) Ещё мелочь
![fds3](https://cloud.githubusercontent.com/assets/9354685/18559291/147d81f8-7b90-11e6-947a-d11a77233787.png)

3) Кнопка "Я девушка" не работает... А вот если нажать "Я парень", сайт охотно верит )))
![fds4](https://cloud.githubusercontent.com/assets/9354685/18559316/31e97fe4-7b90-11e6-98e3-39f6cda7513b.png)

4) Походу этому косяку ещё долго жить (город в профиле указан корректно)...
![fds5](https://cloud.githubusercontent.com/assets/9354685/18559349/58e8b024-7b90-11e6-9382-e43d0c556af3.png)

5) Если случайно указать вместо города имя, а потом в настройках указать верный город, то в дальнейшем при нажатии на Поиск сначала появляется случайно указанное имя, потом оно меняется на указанный город. Так понимаю это своеобразная заплатка, так как раньше вообще город в настройках и город в поиске небыли связаны, а город для поиска берётся из кукисов. А нормально не судьба сделать?
![fds6](https://cloud.githubusercontent.com/assets/9354685/18559580/51f861a0-7b91-11e6-8cab-5cff0e7d1896.png)

**Comment by sexifixy** [comment]
Здравствуйте.

Спасибо. Будем исправлять. 

> 4) Походу этому косяку ещё долго жить (город в профиле указан корректно)...
* нет входящих сообщения вообще
* нажать "Сообщения"

Или при другом раскладе получен такой баг?

**Comment by mj4444ru** [comment]
> Или при другом раскладе получен такой баг?

Я не понял вопроса, но баг 4 к остальным багам отношения не имеет и присутствовал и ранее на полностью корректных анкетах. Получал из разных мест его...

**Comment by mj4444ru** [comment]
по поводу бага 5.
описанное выше актуально на хромиумах под линукс, а вот хромиумы под виндой город всегда из кук берут и при смене в анкете ничего не меняется, город всегда ошибочный ставится...

последнее время часто вижу разное поведение в хроме в зависимости от операционной системы...

**Comment by fenixnoir** [comment]
1. А как насчет сессий? Потянет сервер? Кукисы не шибко надежны, а некоторые экзотические системы, к примеру ArOS вообще их криво обрабатывают.
2. Баг под номером 4 вылезает ввиду некорректной/неполной обработки страницы, и к кукисам отношения не имеет. Проявляется на слабых системах и при загрузке канала, второй вариант более вероятен со стороны сервера. В таком случае сессии вполне могут помочь, т.к. обработка будет происходить без участия стороны выдачи.
3. Баг 1 опять таки, судя по всему, проистекает из-хранения данных в кукисах, зачем сделано дублирование данных из БД, я не совсем понимаю.
4. Баг 5... Люди! Почему вы так любите кукисы? Причем статичные?

**Comment by tebaly** [comment]
fix. Спасибо
