### ISSUE TITLE
Новая анкета со старыми данными

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#266]
Захожу я значит, вроде как сайт меня узнал (имя, город, возраст, желания), но всё остальное забыто и номер анкеты другой...
![fds1](https://cloud.githubusercontent.com/assets/9354685/18576471/4bedd140-7bfb-11e6-945b-ab997315b077.png)

**Comment by sexifixy** [comment]
Проблема рассинхронизации кэша. Надо дополнительно проверить, не выкидывает ли из авторизации пользователей. Но раньше такое было как минимум при выходе с сайта. Надо исправить обязательно)
* локально в браузере сохраняются данные о Имени Возрасте и Городе
* они висят, пока на сервере не сохранить новые данные (тоже и с желаниями)

**Comment by inquisitor6789** [comment]
> Надо дополнительно проверить, не выкидывает ли из авторизации пользователей

периодически жалуются

Так же у меня есть вопрос по старым анкетам - в последнее время участились случаи, когда восстают из мертвых. Например, анкете пару лет. Это старый юзер зашел или переиспользуются id?

**Comment by sexifixy** [comment]
Пока не запущено переиспользование. Я не знаю что это такое.. Может сами(старая анкета), может как-то подбирают данные авторизации, ака брутфорс или взлом.

> периодически жалуются

а у вас получалось такое наблюдать? воспроизвести конечно можно попытаться, но система авторизации до безобразия простая, и если и дает сбои, то не систематически, а в следствие наших вмешательств при обновлении или переносе БД.. :)

**Comment by inquisitor6789** [comment]
> ака брутфорс или взлом.

чисто в теории возможно, но не представляю зачем это нужно.

> а у вас получалось такое наблюдать?

если попадутся новые жалобы, то ссылку кину.

**Comment by mj4444ru** [comment]
а не подскажете где глянуть? точно не в куках оно... позже гляну в хранилище браузера что сейчас...

**Comment by tebaly** [comment]
LocalStorage

**Comment by mj4444ru** [comment]
в куках во всех полях значение Null

**Comment by inquisitor6789** [comment]
> а у вас получалось такое наблюдать?
если попадутся новые жалобы, то ссылку кину.

http://freedomsex.net/userinfo/profile/11665984
собственно вот.
как мне кажется, то ломать страницы других пользователей на сайте с моментальной регистрацией просто глупо.

**Comment by tebaly** [comment]
@inquisitor6789 `не выкидывает ли из авторизации пользователей` - я имел это)) то есть, вот вы пользуетесь сайтом, и вас вдруг выкинуло. И вам приходится нажимать кнопочку "вход/войти" чтобы заново залогиниться. 
* создалась новая анкета с новыми данными
* или пишет что нужно получить новый логин

В норме такого быть не должно вообще никогда. 
* только если почистить куки браузера
* переустановить браузер/ОС
* открыть другой браузер(например ФФ вместо Хрома, как обычно)
* возможно, путаница при использовании нескольких устройств/браузеров и нескольких анкет одновременно

**Comment by tebaly** [comment]
> как мне кажется, то ломать страницы других пользователей на сайте с моментальной регистрацией просто глупо.

Для спамеров это норма. Они не знают нашей архитектуры и могут думать, что "старые" анкеты имеют больший приоритет в СБ(как в большинстве других сайтов/сервисов), но это не так.

**Comment by tebaly** [comment]
Вроде больше не наблюдается
