### ISSUE TITLE
Сайт жрёт ресурсы (память, процессор)

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#267]
Если подержать анкету сутки, она начинает жрать много процессорного времени и памяти... Если вкладок 3-4, то соответственно в 3-4 раза печальнее всё... Через сутки 4 вкладки полностью занимают одно ядро процессора (больше вероятно им не даёт операционная система), а потом этот процесс умирает и вместо вкладок появляется ошибка в браузере. Чаще замечаю это под виндой, под убунту редко такое бывает... Какая именно страница (поиск или сообщения) жрёт ресурсы, сказать не могу, хром группирует вкладки по процессам... с другими сайтами такого не происходит...

**Comment by tebaly** [comment]
Перезагрузка вкладки должна помочь. У нас нет прям специалиста по JS. Код написан достаточно криво, это видно. Ожидалось, что при неиспользовании страницы в описанном случае, возможны такие результаты.

**Comment by mj4444ru** [comment]
Блин, я и не догадался что вкладку то перезагрузить можно...

**Comment by tebaly** [comment]
Рад помочь)

**Comment by tebaly** [comment]
@mj4444ru есть стойкое подозрение, что наш код не виноват. Уверен что это баннер рунеток.

**Comment by tebaly** [comment]
@mj4444ru подтверждено, ресурсы жрал их баннер. Временно заменили на статику
