### ISSUE TITLE
Неудобный поиск

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#268]
Я хочу искать девушек в своём городе без учёта возраста.
Что бы это делать, мне надо либо нажимать на сердечки и меня поле "кого я хочу найти", либо нажать на поиск и убирать подставленный автоматически возраст.
Очень неудобно. Хорошо бы учитывать пожелания по возрасту, а не навязывать всегда свои в зависимости от возраста в анкете...

**Comment by tebaly** [comment]
Эта проблема надумана, как мне кажется. Удалите в настройках критерии возраста и поиск будет без возраста. Ведь если настройки указаны, значит вы их установили, а не сайт.

**Comment by mj4444ru** [comment]
вы правы, но блин я зная про этот блок и то надумываю проблемы... а сколько ещё таких фантазеров как я?
сделайте эти параметры интуитивно доступными, уже не раз писал...

**Comment by tebaly** [comment]
> интуитивно доступными

Это как?
