### ISSUE TITLE
замечания к анкетам

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#269]
А может ли заблокированный пользователь писать замечания к анкетам?
Например есть замечания
http://freedomsex.net/userinfo/profile/11419255
http://freedomsex.net/userinfo/profile/12681614
написанные вот этим перцем http://freedomsex.net/userinfo/profile/16952125

как видно, то он был заблокирован приблизительно 20.09.16 в 10:00. А замечания были написаны 20.09.16 в 13:00
это нормально?

**Comment by mj4444ru** [comment]
А почему нет? Замечание может быть актуальным... Администратор решает публиковать или нет...

**Comment by inquisitor6789** [comment]
так проблема в том, что пользователь который пишет замечания заблокирован. Если мне память не изменяет, то ему должен быть доступен только просмотр. Все остальное не должно уходить дальше его компа.

**Comment by tebaly** [comment]
Архитектурой много где заложен принцип "независимости". Блокировка пользователя блокирует только доставку сообщений. @mj4444ru верно заметил, если замечание актуально, нет разницы от кого оно пришло. Можно было бы делать блокировку создания замечаний, но актуально ли это? Таким образом у "нас" заблокированный пользователь может много ещё чего, так как блокирование планировалось делать максимально незаметным для Нарушителя. В будущем мы уйдем от этого, но это другая история.

**Comment by inquisitor6789** [comment]
понятно
