### ISSUE TITLE
Онлайн и кнопка заблокировать

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#270]
Вынесите её из под ката кнопку онлайн (последнего посещения) и заблокировать/разблокировать...

Уже ранее не раз писал об этой полезной мелочи...

**Comment by DrAllcome** [comment]
Согласен. Мелочь, но удобства станет больше.

**Comment by tebaly** [comment]
Ну онлайн я вверх воткну. А "заблокировать" куда?)

**Comment by tebaly** [comment]
В принципе, хочется страницу анкеты ликвидировать.. Как раз этим и займусь :relaxed:

**Comment by mj4444ru** [comment]
не перестарайтесь...

**Comment by tebaly** [comment]
вот вам не спиться :) :wine_glass:
