### ISSUE TITLE
фото начало <> предложение знакомства?

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#271]
http://sexoo.ru/userinfo/profile/17341142/
Несколько фактов фото начал, но ни одного зафиксированного "предложенного" знакомства.

**Comment by tebaly** [comment]
Кстати. Лог о котором речь, регистрирует факт выдачи капчи, а не факт отправки сообщения/фотографии. "Утром деньги, вечером стулья (с)" - сначала выдается запрос капчи, затем, если введет, отправка сообщения. Но факт запроса капчи сохраняется. Это технические детали, об этом логе часто упоминается как "технический" - не стоит принимать информацию в нем как "особо важную".
