### ISSUE TITLE
когда  заходили в анкету

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#272]
по данным http://sexoo.ru/16907269 - "давно".
смотрим профиль: http://sexoo.ru/userinfo/profile/16907269 Анет, 22 Алматы (Девушка онлайн)

**Comment by Fenslau** [comment]
ну блин, уже изменилось в анкете... Хотя я таких уже неоднократно встречал. Ладно, пока отложим, найду еще, скину!

**Comment by tebaly** [comment]
Вполне возможен баг, я проверю

**Comment by inquisitor6789** [comment]
да, да, есть такой бажок
он исчезает при обновлении страницы

**Comment by tebaly** [comment]
Информация о визите в анкете Пользователя и профиле Нарушителя сейчас ставится (вроде как и раньше) идентично. Расхождения быть не должно.

Воспроизвести баг не получилось.
