### ISSUE TITLE
15 тыс жалоб за 2 минуты

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#273]
15 тыс жалоб за 2 минуты
Чуток поимели вашу систему безопасности?

**Comment by tebaly** [comment]
Слишком пафосно в отношении проекта находящегося в бэте, для временно нестабильного сервиса отображения жалоб :)

**Comment by mj4444ru** [comment]
ой, простите, просто у вас баг... после отправки в арбитраж так происходит...

**Comment by tebaly** [comment]
Так значит ни кто систему не имел)) #217 - сейчас исправлю. Вариант просто не всем понравится, но иначе не получается..

**Comment by tebaly** [comment]
![o](http://cs8.pikabu.ru/post_img/2016/09/28/9/1475074386180145680.jpg)

**Comment by mj4444ru** [comment]
Вы же не хотите что бы вам помогали с этими мелкими делишками...

**Comment by tebaly** [comment]
@mj4444ru - вы о каких делишках?) Могу ошибаться, но наше с вами личное общение началось с того, что вы обнаружив в текстах справки очепятки, высказали желание помочь в их исправлении. После чего я выложил для свободного редактирования тексты справки. В README проекта есть запись об оном.

---
Суть картинки была в том, что давным давно, при проектировании системы администрирования я не знал как лучше реализовать конкретную "большую" задачу(связанность жалобы и пользователей). После, её исправление стало достаточно сложным, и всё время откладывалось. "15 тыс жалоб за 2 минуты" - именно про эту проблему когда одна жалоба связанна с 15 тыс Пользователей - а решалось это костылями, убрав один из которых мы поимели проблему. Мне пришлось полностью перебрать почти всю систему администрирования и изменить структуру базы данных для решения "отложенной" ранее задачи. Масштаб очень большой, изменения весьма болезненны. Последствия ещё придется разгрести.

От помощи я никогда не отказываюсь. Я всегда иду на диалог. Просто "в интернете никто не знает, что ты кот". Не я один сказал вам, что вы очень часто сотрясаете воздух.
