### ISSUE TITLE
Сообщения удалённые собеседником

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#274]
Может не стоит удалять сообщение у отправителя при нажатии пожаловаться?
иначе получается
1) пользователь видит что на него жалуются
2) http://freedomsex.net/history/message/114297668/

да и вообще может лучше его просто серым делать у того кто нажал пожаловаться? не вижу особого смысла в удалении... не хочешь, не смотри...

**Comment by tebaly** [comment]
Смысл есть. Для пользователя не должно быть разницы между удалить/наказать. Иначе много кому, как мне кажется придется нажимать сначала "наказыть" а потом "удалить" - и им будет только удалить, без "наказать"

**Comment by mj4444ru** [comment]
я не предлагаю ничего делить и добавлять кнопки...
я о смысле кнопок вообще...
для своих сообщений должна быть кнопка удалить, которая сейчас есть и которая работает как надо...
а вот для чужих сообщений хорошо бы сделать один из следующих вариантов:
1) при нажатии наказать/удалить сообщение скрывается у получателя, остаётся как и раньше у отправителя...
2) при нажатии наказать/удалить сообщение делается серым (так пользователь понимает что он на него пожаловался), либо у получателя вместо сообщения, будет кнопка (восстановить) как сейчас после удаления.

Иногда охота пожаловаться, но сообщение не удалять. Мы то знаем если нажать на наказать, а потом восстановить, и жалоба будет и сообщение останется... но пользователь то думает что если он нажмёт восстановить, то жалоба удалиться...

**Comment by tebaly** [comment]
Можно сделать отсылку к документации и там описать сей нюанс. Как вам?

**Comment by inquisitor6789** [comment]
> Можно сделать отсылку к документации и там описать сей нюанс. Как вам?

а кто ее будет читать? Как показывает практика мало кто читает доки и инструкции пока в них носом не ткнешь

**Comment by mj4444ru** [comment]
я против ссылок... мои варианты выше...

**Comment by tebaly** [comment]
> Может не стоит удалять сообщение у отправителя при нажатии пожаловаться?

Стоит. :)

**Comment by tebaly** [comment]
![1](https://c1.staticflickr.com/3/2694/4422885389_cd279e1531.jpg)
