### ISSUE TITLE
Ограничение количества символов в сообщении 1000

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#276]
Кто за, кто против?) Другие цифры?

**Comment by inquisitor6789** [comment]
имхо достаточно. Только если больше напишут, то надо предупреждать что будет отправлено не все. Иногда в жалобах трактаты на экран встречаются :-)

**Comment by mj4444ru** [comment]
есть атрибут maxlength который не даст ввести больше 1000 символов
1000 более чем достаточно, даже можно и 500 ограничиться, нечего поэмы писать, всё равно их никто читать до конца не станет...
