### ISSUE TITLE
Ники админов в админке вместо @12345678

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#277]
Предлагаю дать админам псевдонимы, вместо @12345678
Так как анкета с данными админа и так доступна, можно для удобства добавить псевдоним.
Сразу оговорюсь, псевдоним не как в контакте, а просто отображаемое имя в админке, не влияющее ни на что и не добавляющее никаких дополнительных ссылок в структуру сайта.

**Comment by inquisitor6789** [comment]
тогда может проще разрешить ники на сайте? и выводить их? Сомневаюсь, что это кто-то будет заполнять кроме "особо задержавшихся на сайте" админов :-)

**Comment by mj4444ru** [comment]
простым посетителям они не нужны... а вот админам было бы проще видеть не чиселки, а именно ники администраторов и модераторов... Не спорю что некоторые и по чиселкам всех помнят, но не у всех такая память на чиселки...

**Comment by tebaly** [comment]
Имена? Из анкеты? + Gravatar (для списков). Вообще циферки так долго не просто так. Изначально хотелось делать систему контроля анонимной. А далее, по желанию администратора - делать ссылку на анкету. И от целей мы не отказывались. Просто пока пазл не складывается..

Ситуация: тысячи модераторов + сотни спецов + десятки админов + резиденты

Реально ориентироваться получится только в резидентах и малом количестве админов.

Ситуация: ники можно менять(а циферки постоянны) - ещё большая неразбериха

Далее начинаем костылестроение с ограничением времени смены ников, ссылки на старые ники, редиректы и так далее. А у нас же ники по желанию? Значит половина ники, половина цифры, и где-то смесь букв и цифр в нике(2641O55, 264I055, 26H1055). И мы же хотели автоматические ссылки в текстах типа @2641000 делать активной ссылкой. Много лишний головняк имхо.

---

Резиденты - вот тут уже можно извратиться как угодно, хоть ники, хоть имя-отчество. Ссылки на почту, ссылки на соцсети, адрес почты до востребования - полноценный профиль. Все что душе угодно.
