### ISSUE TITLE
Местонахождение по справочнику

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#278]
Тема уже поднималась. Но всё же хотелось бы услышать ответ.
Вы не хотите по какой причине так сделать?
1) Некогда
2) Нету базы геолокаций (адресов)
3) Хотите оставить возможность писать всякую хрень вместо города
4) Не знаете как поступить с текущими анкетами
5) Другое

**Comment by tebaly** [comment]
Ответ - 1. Пересобрать админку(вакханалия в списках жалоб), поправить JS на сайте(глюки и косяки с кэшем и null значения), ускорить отклик сайта и сервисов (работа на серверах, почта отваливается, база тупит) - работы реально дахуа...

2, База есть, она работает. Начните вводить любые символы в поиске и вам покажет список мест - всего 750,000 объектов
3, да, есть планы на перспективу
4. знаем - простой апдейт ID гео.объекта(их 750,000 сейчас, включая пгт и поселки)
5, Дело в том, что первично, точный выбор объекта несколько усложнится - 2-3 доп клика

**Comment by mj4444ru** [comment]
я предполагал что выбор не усложнится, как например ввод населённого пункта на сайте гисметео.

**Comment by tebaly** [comment]
@mj4444ru упомянутый вами "друг вокруг" - имеет точно такой же косяк. Можно писать в поле "город" всё что угодно

**Comment by mj4444ru** [comment]
о нееет, там это не косяк, а достоинство...
объясняю почему:
1) поиск идёт в пределах одной республики/края/штата... то есть как минимум структура "Страна -> Регион -> Город (в произвольной форме)"
2) Город в поиске можно не указывать
3) Поиск идёт по принцепу %ИскомаяФраза% (*ИскомаяФраза*)
4) Там нет цензуры на несуществующий города

**Comment by tebaly** [comment]
Проясните пожалуйста, в чем собственно достоинство? 
* Масква, Москава, Москов, Исква, Нерезиновая

Если вы про поиск названия по полю "Город" в формате  %НазваниеГорода% - то ни одна из перечисленных анкет найдена не будет. 

Поиск по "Москва и мос. область" - достоинство? Единственный "плюс" в том, что эти все анкеты **не будут найдены** в части базы анкет "Москва и мос. область".

> В Московской области по состоянию на 16 ноября 2015 года насчитывается 73 города. Из них 32 города областного подчинения, 40 городов районного подчинения и 1 ЗАТО (Краснознаменск). Из всех городов 28 городов являются районным центром, при этом 3 из них областного подчинения и не входят в состав района

Численность населения Подмосковья по данным Росстата составляет **7 318 647** чел. (2016) (**не учитывая** городов Москвы с подчиненным ей Зеленоградом, Сходни, вошедшей в состав Химок в 2004 году, Троицка, Щербинки и Московского, вошедших в состав Москвы 1 июля 2012 года, Юбилейного, вошедшего в состав Королёва в 2014 году)

Это всё уже оффтоп) города поправим обязательно

**Comment by mj4444ru** [comment]
Люди намеренно искажают название города что бы было понятно где они, но что бы в обычном поиске не вылезали...

Просто поиск используют исключительно для знакомства, но не все хотят знакомиться...

А на счёт регионов скажу следующее - он берётся из номера телефона указанного при регистрации (ранее не было регистрации через соцсети)... И его поменять невозможно в анкете.
Поиск без указания города полезен для поиска людей из своего и соседних городов...

**Comment by tebaly** [comment]
@mj4444ru я просто хочу прочувствовать пользу на приведенном выше примере - "Москва и мос. область". 
* если искать по "вхождению" %НазваниеГорода% - фактически тот же поиск по полю "Город"
* ... и соседних городов... - их 73 (7 318 647 чел.) плюс сама Нерезиновая, это порядка 20 миллионов человек на территории ~46.000 км² - релевантность такого поиска стремится к нулю. Людей он найдет - все 20 миллионов...

В разных регионах "общее" количество разное. Мы изначально не принимали в рассчет поиск "по региону" - так как тематика сайта не подразумевает регулярные поездки в соседний город или по региону. Наоборот, на нас постоянно давят, и продавливают поиск по районам города, станциям метро. Одновременно с поправкой в "Названиях городов" мы таки внедрим поиск по "местоположению/радиус охвата" что решит абсолютно все проблемы локации собеседников, я так думаю.

**Comment by mj4444ru** [comment]
Вы не учитываете разношорстность и специфику разных регионов... Вот у нас ближайший город в 50 км... Волгоград и Волжский находятся на расстоянии одного моста, Самара и Жигулёвск на расстоянии дамбы... Город Каспийск ближе к городу Махачкала чем 4 района города Уфы к самой Уфе... Зеленогорск находится ближе к некоторым районам Москвы чем другие районы Москвы...

Кто то готов далеко ехать, для кого то за пределами района не интересно... Кто то на машине, кто то на метро, кто то на трамвайчике (такси)...

**Comment by mj4444ru** [comment]
У нас длинна город с юга на север 60 км... не удивительно что многие хотят по районам искать... Хотя с нашего города тут всего 5 девушек, так что особо выбирать парням не приходиться...

**Comment by tebaly** [comment]
Поиск по "региону" волгоградской области выдаст помимо Волжского еще с десяток городов разбросанных по площади 112 877 км² - на территории области находятся **1506 населённых пунктов** в составе 39 муниципальных образований. Каким макаром люди определяют кто из Волжского, а кто из Урюпинска(вот же совпадение) находясь в Волгограде при таком поиске - я вообще хз..

Пик посещаемости приходился на 2015 год. Тогда, можете меня поправить, соцсеть "Друг вокруг" отождествлялась и сопровождалась фразой "Новый сайт знакомств, где можно найти красивых тёлок". Непонятки с поиском (а я это именно так называю) быстро поубавили интерес к приложению. Я думаю руководство соцсети упустило этот момент, и не уверен до конца, заметило ли вообще. Время покажет, но сейчас спад уже около половины. 

Если мне память не изменяет, после регистрации в этой сети поле город пустое - заполнение на усмотрение пользователя. Именно этот факт "убил" сервис как платформу для знакомств. Остается только платформа для общения - тогда что они противопоставят Ватсапу и ВК мне сложно предположить. Платный чат?

**Comment by mj4444ru** [comment]
У нас в регионе ДВ куда популярнее ватсапа... А в Махачкале всего 10 пользователей ДВ было когда я там был... Там у них что то другое более популярно... Этих приложений типа ДругВокруг куча...
Там есть мелкие фишки типа поиска людей рядом (через блютуз)...

**Comment by mj4444ru** [comment]
Большинство пользователей в крупных городах, так что на счёт мелких народ не парится...

**Comment by mj4444ru** [comment]
Италия, Польша, Дальний Восток, Южная Корея, Тамбовская Обл - Да, да, это города с последней страницы...

Москва Ювао, Москва Химки, Москва Капотня - Впрочем это тоже...

**Comment by inquisitor6789** [comment]
> Там есть мелкие фишки типа поиска людей рядом (через блютуз)...

бгг, это в радиусе 10 метров чтоль? Ну круто чо. Много ли ты знаешь народа, которые ходят постоянно с включенным синезубом?
Если мне память не изменяет, то лет 6-7 назад была подобная фишка (приложение или сервис какой). Но она что-то быстро заглохла.
На счет ДВ и поиска... Как мне относится к анкете в которой указано Москва и область, Нижний Новгород. Нижний, мать его, новгород в МО!!!
Если надо сделать жесткое задание места жительства, то возьмите КЛАДР. Это правда только для России. Но, думаю, что в сети есть сервисы, предоставляющие список населенных пунктов во всем мире.

**Comment by inquisitor6789** [comment]
кстати, насчет местоположения... Наткнулся тут на любопытный сервис dater.com... Если я правильно понял его алгоритм, то он определяет твое местоположение по телефону (не по номеру, а физически где трубка находится). И предлагает тебе анкеты на определенном удалении от тебя.

**Comment by mj4444ru** [comment]
> не по номеру, а физически где трубка находится

опсосы не разглашают такую информацию...
это можно по ИП вычислить, но опсосы и эту инфу не разглашают и обычно по ип можно вычислить только федеральный округ...

можно точно узнать к какому оператору привязан номер, регион номера и доступен ли в данный момент абонент (подключён к сети)...

**Comment by mj4444ru** [comment]
> Как мне относится к анкете в которой указано Москва и область, Нижний Новгород.

там переодически удаляют проституток и т.п., по этому они регистрируют симки в больших количествах... в москве симка дешевле...
а вот как относится к проституткам, интимсалонам и наркоторговцам решать тебе...

**Comment by inquisitor6789** [comment]
> там переодически удаляют проституток и т.п., по этому они регистрируют симки в больших количествах... в москве симка дешевле..

и чтобы найти одного реального человека мне надо перелопатить сотни контактов. И что такое "переодически"? Раз в месяц? Ну... не знаю...

**Comment by tebaly** [comment]
@mj4444ru интересно ваше мнение. Для удобства беру всё тот же пример, не обессудьте. 

Имеем:
* Для масштаба - Москва и мос. область (Поиск по региону)
* Для наглядности - Волгоградская область
* Желаем: поиск по региону 
* Хотим: найти людей из соседнего Волгограду города - Волжский + Волгоград

Обратная сторона:
* Для масштаба - город Мытищи (или Ступино)
* Для наглядности - город Урюпинск волгоградской области
* Желаем: познакомиться с парнем в своем городе Мытищи (или Ступино) [Урюпинск]
* Хотим: получать сообщения от парней только из своего города.

---

Как по вашему можно физически ограничить "получение" сообщений от парней из других городов для тех девушек, что живут в Урюпинске (Мытищи или Ступино). Это тождественно запрету парням, живущим в Волгограде(Москве) писать сообщения тем девушкам.

Одновременно, как позволить парням живущим в Волгограде написать девушкам, которые живут в Волжском? Если девушки, которые живут в Волжском, не хотят получать сообщения от парней, которые живут в Урюпинске, но вероятно не против пообщаться с парнями из Волгограда..

---

Опция "только мой город" сейчас работает сугубо как строгий фильтр по именованию Населенного пункта. Она прекрасно работает в отношениях Волгоград-Урюпинск, Волгоград-Москва, Москва-Ступино. В отношении смежных городов создает явные проблемы.

**Comment by tebaly** [comment]
Внимание спойлер. Такое возможно только при строгом указании местоположения. Все "придуманные города" сразу идут лесом. Но может и к лучшему. И здесь уже новые проблемы...
* я живу в Волжском и **хочу получать** сообщения из Волгограда - расстояние +10 км
* я живу в Чертаново, собеседник в Отрадном - расстояние +40 км - я **не хочу** сообщения

В первом случае, меньшая строгость по "расстоянию" решит проблему. Во втором, формально это один и тот же город, фильтр вообще сработать не должен.. 

Сортировка результатов по местоположению не совсем релевантна, но видится тем самым "выходом".

**Comment by mj4444ru** [comment]
Моё мнение: Кажется проблема придуманная... Реальная проблема в другом...

Давайте разделим всех людей на 2x2 категории и попробуем найти корни проблемы:
- Активные / пассивные
  - Активные - те кто ищут партнёра/собеседника...
  - Пассивные - те кто просто ждут пока их найдут...
- Что ищут
  - Реалы - Реальные встречи/секс...
  - Виртуалы - Виртуальное общение/секс...

Что надо этим людям?
- Активам Реалам - Удобный поиск по геолокации (расстоянию)...
- Активам Виртуалам - Удобный поиск по желаниям...
- Пассивам Реалам - Что бы им не писали те, кому интересен вирт...
- Пассивам Виртуалам - Что бы им не писали те, кому интересны только встречи...

Естественно человек может относиться к двум и более группам, но правильно реализация ограничительных мер не должна создавать проблемы для таких юзверей...

**Comment by tebaly** [comment]
Стапэ) Для виртуалов сейчас проблем нет. Если девушка указала в анкете "вирт" - ей свободно можно писать хоть с Папуа-Новой Гвинеи. Никаких ограничений. 

Если девушка забыла/не знает/не умеет как указать вирт - значит не судьба.. (хотя система указывает ей на необходимость такой настройки)

**Comment by mj4444ru** [comment]
До описания проблем я ещё не дошёл )))

**Comment by mj4444ru** [comment]
На что жалуются люди?
Мои варианты:
- Активы Реалы
  - На грубое общение, оскорбления и мат
  - На непристойное или недопустимое предложения (в том числе от гомосексуалов)
  - В ответ на жалобу собеседника
- Пассивы Реалы
  - На виртуалов
  - На тех кому сказали "пока" но они не поняли
  - На грубое общение, оскорбления и мат
  - На непристойное или недопустимое предложения (в том числе от гомосексуалов)
  - В ответ на жалобу собеседника
- Виртуалы
  - На грубое общение, оскорбления и мат
  - Собеседник надоел
  - На неприемлимые темы (типа педофилии)

**Comment by mj4444ru** [comment]
Если пассив хочет секса, ему без разницы откуда будет ехать актив...
Ну активы и виртуалы точно не будут жаловаться на расстояние...

**Comment by mj4444ru** [comment]
Я думал тут всё решили... Справочник скромный, но есть...

**Comment by mj4444ru** [comment]
И вы как бы дали развернутый ответ...

**Comment by mj4444ru** [comment]
И ещё это по факту дубликат #4

**Comment by tebaly** [comment]
Нет. Работаю ещё над этим..

**Comment by tebaly** [comment]
#4
