### ISSUE TITLE
вирт по вебке на рунетки,и прочие фотки пюсюна пидарасы оставьте себе

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#279]
И где тут намёк на "мошенничество, предложения оплаты, индивидуалку или спам ссылку" ?

Парень присылает свой член, предлагает вирта...
Девушка вполне логично отсылает на сайт "который все на самом деле и так знают" и немного оскорбляет.

Максимум это оскорбление, но не как не больше...

**Comment by mj4444ru** [comment]
Пожалуйста, обратитесь к администратору с рейтингом 5010 или выше для изменения решения по данной жалобе.

И как обычный человек ниже администратора должен найти такого человека?

**Comment by tebaly** [comment]
Ну вы же ни анкет ни ссылок не дали. К чему сей пост?

> И как обычный человек ниже администратора должен найти такого человека?

Вы всех их уже поименно знаете, например. Другие могут знать одного-двух. Планируем списки админов - пока только планы. "обратитесь к администратору" запилили в спешке, особо не продумывали.

Замечание годное, спасибо.

**Comment by inquisitor6789** [comment]
тем не менее, я склонен считать это рекламой.
Тем более что использовались прямые ссылки на конкретные страницы. Действия были согласно регламента. В чем проблема?

**Comment by mj4444ru** [comment]
проблема в том что вы Сергей считаете рекламмой, то что её не является...
и впрочем самой системой тоже недоволен... чем то на наши выборы в россии смахивает... выберают вроде как изначально все, а в итоге всё решит один человек (как скажет так и будет, в не зависимости от мнения всех остальных)...

**Comment by inquisitor6789** [comment]
призыв перейти на сайт есть? есть.
конкретный адрес есть? есть.
И в чем отличие от рекламы?
Хотя по стилю общения это создание очень похоже на тупого тролля.

И мы приходим опять к Вашему альтернативному мнению которое обязательно должно быть правильным. На сайте резидентов с рейтингом повыше моего есть еще несколько человек. Если мое мнение не правильное, то чего же они его не опровергли?
Отсюда вывод - мое мнение совпадает с мнением большинства. А значит оно имеет очень большие шансы на существование. В отличие от Вашего.

**Comment by mj4444ru** [comment]
Сергей, у Вас примитивная логика. Если кто то не вмешивается, это не значит что он согласен. 
Реклама - это когда кто то призывает что то сделать в интересах кого то...

**Comment by Fenslau** [comment]
а где ссылка или вообще предмет дискуссии?
Допустим я - девка обычная. мне прислали чото там, я решаю, что это не ко мне и отсылаю чувака к платным рунеткам. Я бы при этом сказал(а) иди подрочи на рунеток. или там runetki.ru (я даже точного адреса сайта не знаю). То есть речь о том, что обычная девка, зашедшая на сайт секс-знакомств, врядли знает очень много про рунеток этих. Если ссылка была подробной и отправлялась специально - одно, если просто упоминание сайта - другое. Мое мнение

**Comment by DrAllcome** [comment]
Насколько я помню, там ссылка была именно на страницу конкретной девушки, а не на главную рунеток. Так что тоже считаю это рекламой.

**Comment by mj4444ru** [comment]
Уточняю - текст сообщения с жалобой в заголовке данной темы...
Цетирую: "вирт по вебке на рунетки,и прочие фотки пюсюна пидарасы оставьте себе"

то есть 1) там ссылок небыло... 2 ) в тексте фигурирует сайт, рекламу которого видят все пользователи... 3) но жалоба была перенесена в раздел блокировать...
![2016-10-10 16 38 12](https://cloud.githubusercontent.com/assets/9354685/19234911/f97a62dc-8f07-11e6-924f-86506e03bda4.png)

**Comment by tebaly** [comment]
@mj4444ru вам скриншот оформлять было не лень, а ссылку на анкету Пользователя запостить - лень? Цель дискуссии создать дичайший Butthurt у всех присутствующих?)

`Насколько я помню, там ссылка была именно на страницу конкретной девушки`
`1) там ссылок небыло... `
`а где ссылка или вообще предмет дискуссии?`
`Девушка вполне логично отсылает на сайт`

Как администратор решил, так и правильно.. По факту, однократную ссылку МОЖНО не блокировать, и даже МОЖНО не наказывать - МОЖНО разрешить. Блокируется 100% спам и рассылки, отличительной чертой которых являются многократные и повторяющиеся по смыслу сообщения, целью которых чаще всего является реклама. Прямая ссылка в них не обязательна, транслита или названия ресурса достаточно.

По регламенту МОЖНО наказать Пользователя, в случае сомнения, и отметить жалобу "наказано". Но не блокировать. Я в сотый раз вам @mj4444ru отвечу, что - в сложных или не очевидных случаях, любое решение будет правильным. Пользователям крайне не рекомендуется имитировать нарушение правил, нарушение законодательства - создавать провоцирующие ситуации. Так как администратор/модератор может расценить "похожее" на нарушение действие "как нарушение", и ему за это ничего не будет.

**Comment by mj4444ru** [comment]
@tebaly у меня нет ссылки. дискуссия ни вокруг пользователя, а вокруг сообщения жалобы помещённого в блокированное...

Вы сами пишете `По регламенту МОЖНО наказать Пользователя, в случае сомнения, и отметить жалобу "наказано". Но не блокировать.` и при этом утверждаете что `Как администратор решил, так и правильно` (даже если он поступил так как вы пишете он поступать не должен).

Хотя не думаю что у Сергея возникли сомнения что эта девушка злостный спамер рекламирующий сайт, баннер которого весит на всех страницах сайта freedomsex...

**Comment by mj4444ru** [comment]
@tebaly цель дискуссии защитить пользователей от (мягко выражаясь) злых админов которые не понимают разницы между юмором, оскорблением и спамом...

**Comment by inquisitor6789** [comment]
блин, ну ты неугомонный
http://freedomsex.net/history/message/114727780/
http://freedomsex.net/history/message/114860246/
http://freedomsex.net/history/message/115159865/
http://freedomsex.net/history/message/114767303/

может не все ссылки указал.... но во всех из них присутствует призыв заплатить и дан адрес сайта. И какая фиг разница, что баннер от него висит на главной странице. Наш Сайт не терпит конкурентов :-)

**Comment by mj4444ru** [comment]
это не твой сайт... у тя слишком бурная фантазия... рунетки не конкуренты, иначе их баннер не висел бы на этом сайте... ты можешь хоть миллион левых ссылок дать, это тебя не оправдывает...

**Comment by inquisitor6789** [comment]
А я и не говорю что мой. Но доходы от рекламы получает именно этот сайт. Вас опять куда-то уводит от простой и понятной логики. Что курите?

**Comment by tebaly** [comment]
Вот и правда, неугомонный)) По факту приведенных ссылок
1 - Пользователь тролль, вероятность 99.99%
2 - Скрытый спам, неявная рассылка, вероятность 89%
3 - Анкета фейк, вероятность 80%

@inquisitor6789 поступил на все 100% правильно - заблокировал тролля, удалил фейка и предупредил спам рассылку и грязный пиар рунеток посредством рассылки провокационных сообщений. А вы  @mj4444ru , в свою очередь, находите и поднимаете трололо-темы, чтобы, видимо, поржать над происходящим. Фу, как не красиво :persevere:

**Comment by mj4444ru** [comment]
Вы очень похожи... Даже наталкивает на мысль что вы один человек...

И вы крайне упёрты... Я не обсуждаю человека, я здесь пишу о конкретной жалобе... У меня нет возможности смотреть ваши ссылки и профили нарушителей, да и не вижу в этом никакой необходимости...

**Comment by tebaly** [comment]
@mj4444ru скоро можно будет делиться рейтингом :star2:

**Comment by tebaly** [comment]
![1](http://nochdobra.com/wp-content/uploads/2016/07/2.jpg)

**Comment by mj4444ru** [comment]
Вы хотите что бы я отдал вам кусочек своего скромного рейтинга?

**Comment by tebaly** [comment]
> У меня нет возможности смотреть ваши ссылки и профили нарушителей

чтобы давали, когда нужно

**Comment by mj4444ru** [comment]
дайте мне 1234 рейтинга взаймы, хочу 4 ссылки посмотреть... 

вам заняться больше нечем???

**Comment by Fenslau** [comment]
Короче я понял суть "проблемы" .... Серега запихал чото там в блок, другой админ не согласен, мол фраза не дотягивает до блока, нет оплаты там за секс, то се. Ну чо сказать... Ох, даже комментить не хочется - Если все было так, как изложено - я пожалуй серегу здесь не поддержу. В том плане, что не было мол рекламы во фразе "идите дрочить на рунеток". Но в конце концов - чо за такой рьяный спор? Тама куча есть сообщений в блоке еще, особенно в раннем, которые вообще блоку не подлежат, ужс нах. минимум 10. У меня их достать в свое время не получилось, а щас уже нет времени... к сожалению... В связи с этим предлагаю кому нибудь это таки сделать и создать тут ищью и все запилить как надо.

**Comment by Fenslau** [comment]
Почему не получилось: - так совпало, что как раз в тот момент, когда я это все просматривал и пихал на арбитраж, у меня был занижен рейтинг. А возможно некоторые их этих фраз тупо зависли где-то в арбитражах, или же были приняы другими модерами (не так давно это было возможно, зотя мне писали, что мол отправляем одмину с рейтингом 5000+) ну да ладно. Короче. история такая. Когда то давно , пока еще все не устоялось, в блок попадали совершенно не регламентные фразы. Либо обычные оскорбления, либо просто грубости. Их не так много. Но вот меня угораздило недавно попасть на одну из них ))) Результат - анкета блокирована ) 
Короче. По идее нужно все это достать и распихать. Блин, ну парни, мне реал некогда, чот в последнее время вообще караул и жуть. даже стал редко заходить.

**Comment by tebaly** [comment]
> на сайт "который все на самом деле и так знают" и немного оскорбляет

Одна ссылка - не спам и не реклама. Одна жалоба - это не значит, что сообщение было единичным. То есть, при двух однотипных жалобах вполне может иметь место рассылка. С партнером проекта ещё не обсуждалась реклама в рассылке, и не уверен что это возможно.

На сколько помню, анкеты были заблокированы за троллинг.
