### ISSUE TITLE
Просьба фоток нынче вирт... нет слов...

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#280]
http://freedomsex.net/history/message/113705145/
"Скинь фоточку ню"

Кто ещё согласен с этим?

**Comment by mj4444ru** [comment]
и чем вот это отличается от предыдущего
http://freedomsex.net/history/message/115760199/

**Comment by mj4444ru** [comment]
А вот это тем более не вирт
http://freedomsex.net/history/message/115143673/
"Привет. Покажи сисечки свои"

**Comment by inquisitor6789** [comment]
просьба интим фото всегда считалась виртом. Что не так?

**Comment by Fenslau** [comment]
Любое взаимодействие, касающееся просмотра интим фоток = вирт, я так всегда считал. Бывает, что по контексту понятно, что вирт в плане "давай фотообмен" или "фоточками обменяемся" - я такое маркировал как разрешить, если нет четкого указания, что фото интим.

**Comment by mj4444ru** [comment]
у меня "ню" однозначно не ассоциируется с эро... это может быть например как "Скинь фоточку, ну" - типа уговаривает девушку...

**Comment by tebaly** [comment]
Не имея представления о "факте" первого сообщения и его содержания, возникает поднятая вами проблема. Проблемой, истинно, это назвать сложно, так как отметка "вирт" на сегодня сугубо информативная - нужна для администрирования. В будущем возможно, но пока так. А далее - если сходу(без привет и знакомства) просят фото, то вирт 100%. А вот отличить, где просто просьба, а где влоб спрашивают, нет возможности в принципе. Костыли строить не планируется.

**Comment by Fenslau** [comment]
Ааа... да все вроде бы было понятно интуитивно:
давай фото обменяемся
вышли фотку
покажи себя
 - ну возможно обычное фото, не интимное - маркируем как разрешить.
покажи пизду/хуй/сиськи, голенькую себя
дай посмотреть на это же все, видеочат - ну явный вирт чо уж. 
Мало кто ради риалсекса проси чото показать в первом сообщении, Даже скорее наоборот - редко когда вообще реалы просят чото показать, сюрпрайзз )

**Comment by mj4444ru** [comment]
видимо только у меня НЮ не ассоциируется с обнажёнкой...

**Comment by Fenslau** [comment]
гг. только щас понял что тс хотел сказать.
ню=ну<>nu
В таком случае конечно можно по-разному рассуждать.
Если сделать в слове хлеб 4 ошибки, вообще пиво получится....
Актуальность не очень высока. 
Слава богу за ню никто никого не карает. 
пусть пишут себе хоть ню хоть мну
