### ISSUE TITLE
не удаляются сообщения

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#283]
http://freedomsex.net/admin/sethelp/?id=153913&ln=0
может это как-то связано с https://github.com/freedomsex/freedomsex/issues/282

**Comment by tebaly** [comment]
Только что проверил. Сообщения удаляются как обычно. 

У вас получилось воспроизвести проблему?

**Comment by inquisitor6789** [comment]
нет, у меня не получилось.
но пользователи по прежнему не удаляются из списка контактов https://github.com/freedomsex/freedomsex/issues/282
