### ISSUE TITLE
Давайте немного освежим гитхаб и поговорим вот о чем: не дает фото - что делать?

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#285]
Якобы. Силами интуиции и  прочей комплексной фигни было негласно договорено так:
Замечания такие не публикуем, если нет оснований. Девка не дает фотки. Не обязана по идее. 
Тем не менее, есть любители публиковать такие замечания. То есть все админы разделились негласно на два лагеря - одним лишь бы повод дай и они такое хотят публиковать, другие - не хотят. Нужно подвести общий знаменатель. чтобы небыло ватных проволок и неразберих. Давайте критерии в студию. Я размышляю так:
Пользователь оставяет ос на юзершу. мы не знаем чтотам оно как было в большинстве случаев. Предлагаю тогда не принимать все эти "она не выслала, не дала, не показала".
По моим наблюдениям, %50 юзерш фотки кидают, особенно если было так заложено в анкете. Если в одном городе - то кидают 98% обычные фотки, если конечно у нее не вирт стоит. Ни разу не было такого, чтобы в ответ на мою скинутую фотку меня послали на хер. В связи с этим: 
*рекомендую админам воздерживаться от принятия подобных решений, памятуя что личное фото - есть личное, и будь там хоть лицо, хоть пизда, хот сиськи, это все не обязательно. Не выложила = значит не хочет.

**Comment by tebaly** [comment]
Только вот тема задана странно вами) "не выслала, не дала, не показала" - более подходит как мне кажется, вместо "Давайте немного освежим гитхаб..." :trollface:

Такого понятия как "Замечания к анкетам" я в принципе в интернете не встречал. Законодателем мод быть сложно, так как всё нужно продумывать самостоятельно. Некого копировать :sweat_smile:

> Не обязана по идее. Тем не менее, есть любители публиковать такие замечания. То есть все админы разделились негласно на два лагеря

Идея в том, чтобы регулировать все "отношения" админ/админ, пользователь/пользователь, админ/пользователь, а также все взаимодействия/воздействия в системе администрирования посредством _Соглашений_

Для полноты охвата мы выбрали формат объемного _Соглашения_, в котором по возможности описываются все детали проблемы/ситуации. Далее _можно_ переварить полный текст Соглашения в _статью справки_, изложенную простым языком, без деталей - только суть. Далее, при необходимости, все детали, в сухом остатке постулировать в пунктах _Правил_. Итого:
* Соглашение
* статья блога/Справки
* пункты Правил

Если фиксировать достигнутые соглашения подобным образом, никаких "разделений по лагерям" не предвидится. Конечно, я могу сказать "делайте так", а вы скажете "мне так сказали" ... и так далее)

Есть ли у вас желание набросать черновик _Соглашения_ по Замечаниям? Документация выделена в отдельный репозиторий **docs**
https://github.com/freedomsex/docs/tree/dev/deal - список всех Соглашений. Нажмите "Create New file". Дайте название, и пролейте свет на разногласия, для достижения Согласия :smile:

**Comment by Fenslau** [comment]
куяссе.... чо происходит.  я для начала хотел бы мнений одминов других....

**Comment by tebaly** [comment]
Я тоже )) тэг - обсуждение)

**Comment by tebaly** [comment]
По теме: часто вижу "коллекционер фоток". Так вот, вполне ожидаемо, если анкета "девушки" заведена парнем(натурал), то ему просто нечего отправить, да и лень ему. Один из признаков поведения фейка - "сбор фоток" и дальнейший игнор оппонентов. Далее, много парнев гей/транс - которые ведут себя подобным образом, но общение продолжают, так как это их цель. 

Своим предложением вы их всех канонизируете в святые :)

**Comment by tebaly** [comment]
Для пушей красоты, можно собирать инфу, типа 
* загружено фотографий - 0
* получено фото - 35
* отправлено фото - 0
* жалоб на фото - 0

**Comment by Fenslau** [comment]
вот это кстати мысль, кто за? кто против?
Просто я тут на днях прошелся по анкетам. 
и совершенно случайно обнаружил:
* девочки не стесняются кидать фотки
* фэйки конечно есть, но выявляются еще на первом этапе.

**Comment by inquisitor6789** [comment]
на счет статистики по фото +1
Что же касается старт-топика, то мое поведение в рассматриваемом случае простое - первое замечание не публикую, второе 50/50, третье публикую (т.к. это уже диагноз). Все это, естественно, если в жалобах есть подтверждение просьбы фото. И видно, что пользователь не высылает фото вообще.

**Comment by Fenslau** [comment]
Порой видим такую картину. У девки фото:начало несколько штук + замечание от обиженного юзера, мол не высылает. Парадокс. Плохо просил значит )

**Comment by tebaly** [comment]
@Fenslau - не обязана :stuck_out_tongue:

**Comment by fenixnoir** [comment]
А вариант того, что фото на сайт не грузится, не рассматривается? Я с вами уже 17 дней, из них дней пять модером/админом, но когда мне было нужно, фото загрузить так и не смог, отсылал на емейл.
Вообще движок ещё весьма сыроват, требует много доработок, а уже идет обсуждение функционала с позиции юзерфрендли... Давайте для начала проработаем код и основной функционал? ТЗ на проект вообще в природе существует? Где нибудь есть подробное описание функционала, разделов и пр.?

**Comment by tebaly** [comment]
> проработаем

:neutral_face:

**Comment by DrAllcome** [comment]
Я бы принимал, только в одном случае, если идет договоренность обмена фотками, ты отсылаешь, а в ответ игнор. Не спортивно как-то. Но как это мониторить - хз. 
Если бы был в интерфейсе счетчик, как предложил tebaly, легче бы стало.

**Comment by tebaly** [comment]
@fenixnoir - проблем хватает. Сильно копать и не нужно. Давайте начнем с вами с того, что на поверхности. Есть очень много моментов, где "давать исходники чтобы покопаться" совсем не обязательно. Спасибо.

> Не спортивно как-то. Но как это мониторить - хз. 

Пока только субъективно. Если такая жалоба не однократна - значит что-то тут не так..

**Comment by NeverovI** [comment]
Я за свободу выбора. Ни кто не может быть принужден. И если публикация подобных действий, есть личная обида, то одобрение модером таких мессаг,  есть нездоровая канитель.

**Comment by tebaly** [comment]
@NeverovI - частенько бывают ситуации "сначала ты мне, потому что ты парень. потом я." - а далее "ой, всё." (ничего я тебе отправлять не обязана). Это уже ~нае~ неспортивное поведение.

**Comment by NeverovI** [comment]
Ну порой реально видишь такое, что "ну все" и пошел за пакетиком аэрофлота. Ну какой там еще обмен, лишь забанить хочется.
