### ISSUE TITLE
В ИЕ нет обглвления страницы - кто тебе пишет, хз

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#286]
В ИЕ все работает не так, или у меня глюк? Когда написывают девушки, видно сообщения, проходит оповещение, но нету обновления списка контактов. Пока не выйдешь и заново ие не запустишь. то есть попапы работают, но нет обновлений в списке сообщений. косяк?

**Comment by tebaly** [comment]
Список какой, я запутался)
* список контактов
* список сообщений - история переписки
* список уведомлений(новых входящих сообщений)

**Comment by Fenslau** [comment]
список контакто-сообщений

**Comment by Fenslau** [comment]
ебучий багрепорт.... короче. В ИЕ: если приходит сообщение, то посмотреть его можно только выбрав пункт "сообщения". И так всегда. Проблема в том, что когда приходит несколько соощений, то они в списке контактов не отображаются. пока не выйдешь/зайдешь. И соответственно нельзя переключаться между последними написавшими пользователями, потому что их нет. В списке. не обновляется.

**Comment by tebaly** [comment]
Да, спасибо. Обнаружили, что JS там безбожно бажит.. :grimacing:

Проверил в эдж - подтверждено. В хроме норм.. Попробую разобраться, спешить не буду..

**Comment by fenixnoir** [comment]
@tebaly, я мог бы просмотреть код и внести правки, только у меня с оперативностью проблемы, доступ к нормальному компу с сетью редкий. Сфера компетенции php, html, css, mysql. Если устроит, то мне необходим сайт и структурный дамп БД. С меня помимо правок комменты в коде.

**Comment by tebaly** [comment]
JS - по этой проблеме нужен JS :relaxed:

**Comment by fenixnoir** [comment]
На эту тему есть множество готовых js, и как правило изобретать велосипед нет смысла, достаточно просто найти и максимум внести небольшие правки. А прикрутив сделать в коде разграничение по браузеру, дабы не засорять ресурсы лишним кодом. Мне всегда такой подход помогал. Тем более на список контактов все равно сейчас ничего нет, т.к. уведомление о новом сообщении у меня в хроме отображается только в заголовке и на кнопке сообщений, а чтобы прочитать или узнать от кого, необходимо обновить страницу с перепиской.

Я не говорю, что я профи в кодинге. Я скорее любитель. Мой опыт ограничивался каталогами, магазинами, почтовиками, соц.сетями, процессингом, и системами вебадминистрирования удаленных серверов...

**Comment by tebaly** [comment]
Можно со списка контактов и начать. Как писать предлагаете? Что позаимствуем из готового?

**Comment by tebaly** [comment]
Я как раз готовлю реп с исходниками JS

**Comment by fenixnoir** [comment]
Для начала нужно посмотреть, что есть. В целом необходимо либо сделать динамическим список контактов и диалог, либо наладить рефреш страницы, если открыт диалог, но это уже костыль, их хочется избежать. Фактически динамичность уже есть (о чем говорит уведомление в заголовке и рефреш кнопки "Сообщения").
Но параллельно хотелось бы попробовать переделать выдачу поиска (нужен сам поиск, скрипт и страница, структура таблицы юзеров) и покопаться в системе сообщений (разграничить возможность отправки/приема фото). Фактически я был бы не прочь вообще весь сайт копнуть, если вы будете не против довериться мне. Но для начала можно попробовать и помодульно, отдельно js не стоит, я в нем разбираюсь слабо, и мне необходим сам модуль, к которому он прикручивается, дабы иметь возможность редактирования "по месту".
Более предметно объяснить сложно, т.к. сижу пока с планшета и у компа буду не скоро.

**Comment by tebaly** [comment]
Там, в глубине, на Symfony нужно переписывать. Знакомы с этим фреймворком?

**Comment by fenixnoir** [comment]
Не знаком, но ради проекта могу если и не выучить, то освоить точно. За 6 лет в сфере айти и не такое приходилось делать.

**Comment by tebaly** [comment]
Ради проекта сейчас бы юриста в Чите найти, чтобы копию дела взял хоть посмотреть на него :smile:

**Comment by fenixnoir** [comment]
Увы, юристы знакомые только в Москве, но я не думаю, что проект вообще потянет стороннего юриста. Это нужно искать среди своих. Можно кинуть клич Юленьке, когда админка заработает, авось кто найдется, все же нас не мало (мне так кажется).

Насчет сабжа. Прочитал о Symfony, вроде будет не очень сложно, даже не сильно должно затянуть процесс.

**Comment by fenixnoir** [comment]
Кстати, @tebaly, админка нужна. У нас проститутки копеечные активируются. Мне несколько часов назад с этой анкеты http://sexoo.ru/18835795 пришло, что мол отчим ее в аренду сдает за 1000 рублей в сутки. Прибить бы как нибудь, либо напрямую в базе...

**Comment by tebaly** [comment]
Ошибки в ИЕ, исключительно кроссбраузерное и сугубо в публичном JS

**Comment by tebaly** [comment]
Сайт официально __не работает__ в IE8 и более старых динозаврах
* доля IE8 по сайту - 0,057 %
* доля IE9 по сайту - 0,037 %

#353

**Comment by tebaly** [comment]
> но нету обновления списка контактов. 

эта с..ка кэшировала список по жести :grin:
