### ISSUE TITLE
нас заблокировал роскомнадзор

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#289]
![image](https://cloud.githubusercontent.com/assets/19651618/19467898/781a351c-951c-11e6-9070-13a4ac90d544.png)

**Comment by Premaswarupa** [comment]
Что-то изменится или это окончательно?(

**Comment by inquisitor6789** [comment]
это касается только freedomsex.net
sexoo.ru. qbsex.ru, oesex.ru пока работают

**Comment by Premaswarupa** [comment]
Уже заметила))

**Comment by drvalera** [comment]
РКН совсем охренел, везде пустит свои сети....

**Comment by mj4444ru** [comment]
конкуренты пожаловались в какой нить деревенский суд и тот решил прикрыть, а до администрации этого сайта не достучаться... вроде у нас сейчас так с конкурентами борятся )))

**Comment by mj4444ru** [comment]
есть расширение friGate для хромиумов... через него норм... надо попросить что бы fds добавили в их список...

**Comment by tebaly** [comment]
Я то думаю, че за ху..ня

**Comment by mj4444ru** [comment]
теперь картинки не открываються... так как через прокси получается сижу, а картинки без прокси... 
давай те придумайте что нить, что бы ИП не проверялся при запросе картинки...

**Comment by tebaly** [comment]
Центральный районный суд г. Читы - Забайкальский край
2-3525/16
16.05.2016

**Comment by mj4444ru** [comment]
деревушка в сибири... бред конечно что какой то мелкий районный судья может запретить всей стране посещать сайт который не понравился лично ему...

**Comment by mj4444ru** [comment]
давайте напишем петицию на имя президента от всех посетителей данного сайта )))))))

**Comment by tebaly** [comment]
счас IP поменяю..

**Comment by mj4444ru** [comment]
я то думаю что всё сломалось... дайте новый ип?

**Comment by Premaswarupa** [comment]
Пипец. Как много оленей((

**Comment by tebaly** [comment]
@mj4444ru тебе не дам, я думаю ты из РКН :sweat_smile:

Смена DNS занимает от 1 до нескольких часов. После восстановления работы начнем разбираться с причиной бана)) Кто-нибудь желает от моего лица в суд сходить? Я сейчас не в РФ  :bowtie:

**Comment by tebaly** [comment]
https://centr--cht.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=31090605&delo_id=1540005&new=

похоже оно..

**Comment by tebaly** [comment]
Если кто может, свяжитесь поинтересуйтесь как решить вопрос, я попробую справки навести пока.
`````
Центральный районный суд
672000, Забайкальский край, г. Чита
ул.Бутина, д. 41  карта проезда
тел: (3022) 35-12-49, факс: (3022) 23-83-80 
e-mail:Centr.cht@sudrf.ru 
Ответственный за сайт: начальник отдела правовой информатизации Румов С.А.

**Comment by tebaly** [comment]
Ах да.. домен тоже придется поменять :relaxed:

**Comment by tebaly** [comment]
За ночь всё нормализую.. Новый IP и новый домен заработают в течении часа-двух

**Comment by inquisitor6789** [comment]
Вроде заработало

**Comment by tebaly** [comment]
Это пока IP завтра новый домен и редирект полностью решат проблему. Причину бы устранить...

**Comment by fenixnoir** [comment]
А причина вполне ясна. У нас не фильтруется контент по возрасту, вот какую нибудь Мизулину это и возмутило. Совращение, блин, малолетних. Пропаганда гомосексуализма. Эти Мизулину в последние годы вообще на почве своей неудовлетворенности с катушек съезжают. Тут только и остается, что айпи с доменом регулярно менять

**Comment by tebaly** [comment]
@fenixnoir в законе всё четко прописано. Есть решение суда, там фигурируют "интим услуги". Для начала нужно разобраться..

**Comment by tebaly** [comment]
redirect на новый домен, куки новые, поэтому войти нужно будет заново

**Comment by inquisitor6789** [comment]
что-то интерфейс модера и админа отвалились.... Говорит что "Раздел проектируется или на техническом обслуживании". С рейтингом все нормально

**Comment by DrAllcome** [comment]
Такая же картина с админкой.

**Comment by tebaly** [comment]
Закрыто на временно на 12-48 часов

**Comment by inquisitor6789** [comment]
ну все, анархия

**Comment by fenixnoir** [comment]
@inquisitor6789, возможность вынесения первичного решения при нажатии ссылки "Я модератор". Так что фиг им, а не анархия.
Хотя отсутствие возможности отвечать на обращения юзеров, это существенный минус. @tebaly, включите, по возможности Юленьку.

**Comment by inquisitor6789** [comment]
а первичное решение без вердикта все равно бессмыслено

**Comment by fenixnoir** [comment]
Логично, но хоть какая деятельность, а то иначе на сайте вообще делать нечего (после знакомства с моим Солнышком смысла знакомиться дальше не вижу), а отблагодарить посильной проект за добрые дела очень хочется...

**Comment by fenixnoir** [comment]
sexoo.ru заблокирован.

Надо разбираться, очень похоже на целенаправленную блокировку.

**Comment by fenixnoir** [comment]
В общем я наконец изучил решение суда.
Срок обжалования истек 30 июня, посему подавать апелляцию поздно.
Организация занятия проституцией вменена неправомерно, т.к. на сайте отсутствует сама суть определения товара (отсутствуют расценки, отсутствуют изображения товара и образцы). Тем более, что ресурс выступает против интим-услуг и усиленно борется с проституцией как реальной, так и виртуальной.
Единственное, что вменено объективно, это защита детей, т.к. ресурс предназначенный для секса позволяет регистрацию лиц не достигших совершеннолетия. В то же время, УК РФ имеет исключение, что запрещены действия сексуального характера с лицом достигшим 16 летия но не достигшим совершеннолетия без его на то согласия. В таком разрезе, добровольная регистрация данных лиц может расцениваться как данное де-факто согласие.
На основании этого возможна подача ходатайства о снятии меры пресечения в связи с фактическим отсутствием состава преступления.
Но я бы рекомендовал ограничить минимальный возраст регистрации 18 годами, ввести соглашение оферту с кнопочкой "мне есть 18", и все же убрать из шапки акцент на знакомства именно для секса. В таком случае у ходатайства будет больше шансов.

В то же время, вменено может быть больше, чем отражено в решении, поэтому действительно нужен человек в Чите, с нотариально заверенной судебной доверенностью от владельца ресурса, который сделает копию материалов дела.

Кстати, неустановленной группой лиц вполне могут оказаться параноидальный родители шерстящие историю браузера своих чад. Не вспомню с ходу, но вроде есть возможность очищать историю выборочно через веб. Если наладить эту функцию по закрытию сайта... Я посмотрю, как до компа доберусь. Хотя бы с этой стороны прикроемся.

**Comment by tebaly** [comment]
> в интересах неопределенного круга лиц

Это граждане РФ. Вы всех путаете..

**Comment by fenixnoir** [comment]
@tebaly, прошу прощения. Видимо уже сплю, путаются различные определения из разных дел. Все таки бодрствовать нужно не более двух суток. :-)

**Comment by Fenslau** [comment]
А это ходатайство снова должно через суд пройти? Это ж долго ппц. Юзеры не вытерпят. А кто ж истец?

**Comment by fenixnoir** [comment]
@Fenslau,  пунктам предлагают видеочат, секс они не предлагают, и в названии сайта не используется слово sex.

Да, ходатайство проходит фактически те же процедуры, приемку, рассмотрение, слушание, решение/определение. Заявитель (не истец) законный владелец ресурса, либо его законный представитель на основании нотариальной доверенности. Учитывая разброс судов, можно попробовать включить в ходатайство просьбу запросить материалы дел и подавать его в суд по месту нахождения ресурса (серверов, я надеюсь они не за бугром), но более точно советую уточнить этот момент у юристов.

Могу посоветовать бесплатно проконсультироваться на форуме сайта gdezakon.ru, я в свое время там получал помощь по этим вопросам...

**Comment by tebaly** [comment]
> суд по месту нахождения ресурса 

Париж, франция + Нидерланды :sweat_smile: - так проблем чуть-чуть меньше, поверьте)

**Comment by tebaly** [comment]
@Fenslau они там сговорились что ли..

**Comment by inquisitor6789** [comment]
> sexoo.ru заблокирован.
Надо разбираться, очень похоже на целенаправленную блокировку.

да, похоже... или кто-то прочитал таки пользовательское соглашение (как бы глубоко оно не было зарыто). А там все наши доменные имена указаны. Только в этом случае не понятно по какой причине решения принимают разные суды.

**Comment by fenixnoir** [comment]
> Париж, Франция + Нидерланды 

Тогда по месту регистрации владельца (вашей прописки)? Вроде тоже возможно...

**Comment by inquisitor6789** [comment]
> Закрыто временно на 12-48 часов

вроде как 2 дня прошло, а воз и ныне там.... в чем проблема то?

**Comment by tebaly** [comment]
вроде как и проблем больше стало :relaxed:

**Comment by fenixnoir** [comment]
> вроде как и проблем больше стало ☺️

И не только технических за короткое время отключенной админки, фейки, проститутки, геи без чувства меры, стали попадаться на каждом шагу. Я уже боюсь написать/ответить девушке, т.к. там наверняка будет парень предлагающий минет...

**Comment by mj4444ru** [comment]
Может конечно это совпадение, но тут недавно очень любопытный тип с Юлей общался на тему что то вроде использования сайта с целью поиска девушек для ... (не помню подробностей)... Я ему кинул ссылку на страничку блога на тему покупки рекламы...

**Comment by mj4444ru** [comment]
sexoo.ru давно блокируется расширением WOT...

**Comment by fenixnoir** [comment]
@mj4444ru, это точно совпадение. Суды состоялись давно, и вполне вероятно, что копать начали в самом начале года.

**Comment by mj4444ru** [comment]
админку тоже роскомнадзор заблокировал? ))))))

**Comment by tebaly** [comment]
@mj4444ru я сам

**Comment by inquisitor6789** [comment]
А смысл?

**Comment by tebaly** [comment]
не успеваю

**Comment by tebaly** [comment]
Поступило предложение пообщаться с журналистами. Есть желающие? :relaxed:

**Comment by inquisitor6789** [comment]
если только в оффлайн режиме...

**Comment by tebaly** [comment]
А че так?))

**Comment by inquisitor6789** [comment]
а то так :-) хз когда время будет. А в оффлайне можно не привязываться ко времени. Да и такой стиль общения мне комфортней.
ЗЫ. и почта предполагает оффлайн. Онлайн это либо тет-а-тет, либо в мессенджере

**Comment by Premaswarupa** [comment]
Намечаются перемены?

**Comment by tebaly** [comment]
в чём? в судебной системе РФ ? я хз..

**Comment by tebaly** [comment]
Финансово - за разблокировку одного домена попросили 250.000 + 150.000 -- **без гарантии** на успех.

**Comment by tebaly** [comment]
давайте проголосуем, как поступить?

**Comment by inquisitor6789** [comment]
а есть много вариантов?

**Comment by tebaly** [comment]
1. Начать юридический процесс(3-9 мес)
2. Забить, и подождать склейки новых доменов(1-3 мес)
... ваш вариант

**Comment by mj4444ru** [comment]
Можно и то и другое одновременно (если есть 500к)... А вообще слышали последние новости? как бы так же не вышло (хотя тут сразу есть железная отмазка - без гарантий)...

**Comment by tebaly** [comment]
### FREEDOMSEX.RU

17.08.2016 | 2-1088/2016 | Шилкинский районный суд - Забайкальский край
-- | -- | --


Р Е Ш Е Н И Е
ИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ
г. Шилка                                17 августа 2016 года
Шилкинский районный суд Забайкальского края в составе:
председательствующего судьи Н.В. Страмиловой,
при секретаре В.В. Шустовой,
с участием прокурора М.А. Мункуевой,
рассмотрев в открытом судебном заседании гражданское дело по иску Шилкинского межрайонного прокурора в интересах Российской Федерации, неопределенного круга лиц, в том числе несовершеннолетних, о признании информации запрещенной,
У С Т А Н О В И Л:
Шилкинский межрайонный прокурор обратился в суд с вышеуказанным иском, ссылаясь на следующие обстоятельства. По результатам осмотра сайтов в информационно-телекоммуникационной сети «Интернет» выявлены факты размещения для свободного доступа неограниченного круга лиц запрещенной к распространению на территории Российской Федерации информации на страницах сайтов: <данные изъяты>
В судебном заседании процессуальный истец – участвующий в деле прокурор М.А. Мункуева исковые требования поддержала по основаниям, приведенным в исковом заявлении.
Представитель Управления Федеральной службы по надзору в сфере связи, информационных технологий и массовых коммуникаций по Забайкальскому краю в судебное заседания не явился, просил рассмотреть дело в их отсутствие.
Руководствуясь ст. 167 ГПК Российской Федерации суд приступил к рассмотрению дела в отсутствие неявившихся лиц.
Выслушав прокурора, исследовав письменные материалы дела, суд приходит к выводу об удовлетворении требований истца по следующим основаниям.
В соответствии со ст. 2 Федерального закона «Об информации, информационных технологиях и о защите информации» информационно-телекоммуникационная сеть - технологическая система, предназначенная для передачи по линиям связи информации, доступ к которой осуществляется с использованием средств вычислительной техники.
В силу ч.ч. 1, 6 ст. 10 Федерального закона «Об информации, информационных технологиях и о защите информации» в Российской Федерации распространение информации осуществляется свободно при соблюдении требований, установленных законодательством Российской Федерации. Запрещается распространение информации, которая направлена на пропаганду войны, разжигание национальной, расовой или религиозной ненависти и вражды, а также иной информации, за распространение которой предусмотрена уголовная или административная ответственность.
Статьями 6.11, 6.12 КоАП Российской Федерации предусмотрена административная ответственность за занятие проституцией и получение дохода от занятия проституцией, если этот доход связан с занятием другого лица проституцией.
За вовлечение в занятие проституцией и организацию занятия проституцией установлена уголовная ответственность ст.ст. 240, 241 УК Российской Федерации.
В соответствии с ч. 5 ст. 15 Федерального закона «Об информации, информационных технологиях и о защите информации» передача информации посредством использования информационно-телекоммуникационных сетей осуществляется без ограничений при условии соблюдения установленных федеральными законами требований к распространению информации и охране объектов интеллектуальной собственности. Передача информации может быть ограничена только в порядке и на условиях, которые установлены федеральными законами.
Согласно ч. 1 ст. 9 Федерального закона «Об информации, информационных технологиях и о защите информации» ограничение доступа к информации устанавливается федеральными законами в целях защиты основ конституционного строя, нравственности, здоровья, прав и законных интересов других лиц, обеспечения обороны страны и безопасности государства.
Одним из способов защиты гражданских прав в силу ст. 12 Гражданского кодекса Российской Федерации является восстановление положения, существовавшего до нарушения права, и пресечение действий, нарушающих право или создающих угрозу его нарушения.
Данная мера не связана с имущественным воздействием на правонарушителя, в связи с чем целесообразно её применение к данному спору.
Судом установлено, что согласно акта проверки от 24.06.2016 на сайтах с доменными именами: <данные изъяты> и на страницах сайтов с URL адресами <данные изъяты>, осуществляется реклама платных услуг интимного характера, что может способствовать формированию у пользователей мнения об обыденности и успешности лиц, оказывающих либо использующих данные услуги.
В связи с распространением на страницах указанных сайтов информации в нарушение положений Федерального закона «Об информации, информационных технологиях и о защите информации» требования прокурора являются законными и обоснованными, в связи с чем подлежат удовлетворению.
Руководствуясь ст. ст. 194-199 ГПК Российской Федерации, суд
Р Е Ш И Л:
Исковые требования Шилкинского межрайонного прокурора удовлетворить.
Признать информацию, размещенную на страницах сайта с доменными именами: <данные изъяты> и на страницах сайтов с URL адресами <данные изъяты> информацией, распространение которой на территории Российской Федерации запрещено.
Копию решения суда направить в Управление Федеральной службы по надзору в сфере связи, информационных технологий и массовых коммуникаций по Забайкальскому краю для последующего включения доменных имен сайтов <данные изъяты> в Единый реестр доменных имен, указателей страниц сайтов в сети «Интернет» и сетевых адресов, позволяющих идентифицировать сайты в сети «Интернет», содержащие информацию, распространение которой на территории Российской Федерации запрещено.
Решение может быть обжаловано в апелляционном порядке в Забайкальский краевой суд в течение месяца со дня его принятия в окончательной форме путем подачи апелляционной жалобы через Шилкинский районный суд Забайкальского края.
Судья Н.В. Страмилова

[shilka--cht.sudrf.ru](https://shilka--cht.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=64995704&delo_id=1540005&new=0&text_number=1&case_id=54039337)

**Comment by tebaly** [comment]
### SEXOO.RU

17.08.2016 | 2-1088/2016 | Шилкинский районный суд - Забайкальский край
-- | -- | --

Дело 2-3525-16

Р Е Ш Е Н И Е

ИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ

16 мая 2016 года г. Чита

Центральный районный суд города Читы в составе:

председательствующего судьи             Копеистовой О.Н.,

при секретаре             Голобокове А.М.,

рассмотрев в открытом судебном заседании в городе Чите гражданское дело по заявлению прокурора Читинского района в интересах Российской Федерации и неопределенного круга лиц о признании информационных материалов запрещенными,

У С Т А Н О В И Л:

Прокурор Читинского района обратился в суд заявлением в интересах Российской Федерации и неопределенного круга лиц о признании информационных материалов запрещенными. Прокуратурой района проведена проверка исполнения законодательства об информации, информационных технологиях, о защите детей от информации, причиняющей вред их здоровью и развитию. В ходе проверки осуществлён мониторинг сети «Интернет» на предмет наличия сайтов, посредством которых предоставляются интимные услуги. Установлено, что для пользователей сети «Интернет» доступны следующие сайты, предоставляющие интимные услуги: <данные изъяты> На основании выше изложенного, прокурор просит признать информацию, размещённую на страницах сайтов с доменными именами <данные изъяты> информацией, распространение которой в Российской Федерации запрещено.

В судебном заседании помощник прокурора ФИО3 уточнила заявленные требования, просила признать информацию, размещённую на сайтах с доменными именами <данные изъяты> информацией, распространение которой в Российской Федерации запрещено. Копию вступившего в законную силу решения суда по делу направить в Федеральную службу по надзору в сфере связи, информационных технологий и массовых коммуникаций по Забайкальскому краю для последующего включения доменных имен <данные изъяты> в Единый реестр доменных имен, указателей страниц сайтов в сети «Интернет», содержащие информацию, распространение которой в Российской Федерации запрещено.

Заинтересованное лицо Управление Федеральной службы по надзору в сфере связи, информационный технологий и массовых коммуникацией по Забайкальскому краю извещенное о времени и месте рассмотрения дела, в судебное заседание своего представителя не направило, представили отзыв.

Суд, руководствуясь ст. 167 ГПК РФ, считает возможным рассмотреть гражданское дело в отсутствие заинтересованного лица

Выслушав помощника прокурора, изучив материалы дела, суд приходит к следующему.

Согласно ч.ч. 1 и 6 ст. 10 Федерального Закона от 27.07.2006 № 149-ФЗ «Об информации, информационных технологиях и защите информации» (Далее- Закон № 149-ФЗ) в Российской Федерации распространение информации осуществляется свободно при соблюдении требований, установленных законодательством Российской Федерации. Запрещается распространение информации, которая направлена на пропаганду войны, разжигание национальной, расовой или религиозной ненависти и вражды, а так же иной информации, за распространение которой предусмотрена уголовная или административная ответственность.

Статьей 4 Закона Российской Федерации от 27.12.1991 № 2124-1 «О средствах массовой информации» установлен запрет на использование средств массовой информации в целях совершения уголовно наказуемых деяний.

Частью 6 ст. 10 Федерального закона № 149-ФЗ запрещено распространение информации, за распространение которой предусмотрена уголовная или административная ответственность.

Уголовным кодексом Российской Федерации (далее – УК РФ) запрещены организация занятия проституции и вовлечение в занятие проституцией (ст. 241, ст. 240 УК РФ).

В соответствии с требованиями ст. 15.1 Федерального закона № 149-ФЗ в целях ограничения доступа к сайтам в сети «Интернет», содержащим информацию, распространение которой в Российской Федерации запрещено, создается единая автоматизированная информационная система «Единый реестр доменных имен, указателей страниц сайтов в сети «Интернет» и сетевых адресов, позволяющих идентифицировать сайты в сети «Интернет», содержащие информацию, распространение которой в Российской Федерации запрещено (далее - реестр).

В реестр включаются: доменные имена и (или) указатели страниц сайтов в сети «Интернет», содержащих информацию, распространение которой в Российской Федерации запрещено; сетевые адреса, позволяющие идентифицировать сайты в сети «Интернет», содержащие информацию, распространение которой в Российской Федерации запрещено.

Создание, формирование и ведение реестра осуществляются Федеральной службой по надзору в сфере связи, информационных технологий и массовых коммуникаций, в порядке, установленном Правительством Российской Федерации.

Законом установлено (п. «г» ч. 5 чт. 15.1), что основанием для включения в реестр соответствующих сведений является вступившее в законную силу решение суда о признании информации, распространяемой посредством сети «Интернет», информацией, распространение которой в Российской Федерации запрещено.

В соответствии с п. 3 ч. 3 ст. 5 Федерального закона от 29.12.2010 N 436-ФЗ «О защите детей от информации, причиняющей вред их здоровью и развитию» к информации, распространение которой среди детей определенных возрастных категорий ограничено, относится информация, представляемая в виде изображения или описания половых отношений между мужчиной и женщиной.

Таким образом, во исполнение действующего законодательства информацию, для применения указанных выше юридических последствий распространяемую посредством сети «Интернет» на сайте с доменными именами <данные изъяты> информацией, распространение которой в Российской Федерации запрещено.

При вышеуказанных обстоятельствах, в целях восстановления нарушенных прав граждан и во исполнение действующего законодательства, суд считает необходимым заявленные требования удовлетворить.

На основании изложенного и руководствуясь ст. 194-198 ГПК РФ, суд

Р Е Ш И Л:

Требования прокурора Читинского района в интересах Российской Федерации и неопределенного круга лиц о признании информационных материалов запрещенными, удовлетворить.

Признать информацию, размещённую на сайтах с доменными именами <данные изъяты> информацией, распространение которой в Российской Федерации запрещено.

Копию вступившего в законную силу решения суда по делу направить в Федеральную службу по надзору в сфере связи, информационных технологий и массовых коммуникаций по Забайкальскому краю для последующего включения доменных имен <данные изъяты> в Единый реестр доменных имен, указателей страниц сайтов в сети «Интернет», содержащие информацию, распространение которой в Российской Федерации запрещено.

Решение может быть обжаловано или опротестовано в Забайкальский краевой суд в течение одного месяца путем подачи апелляционной жалобы или апелляционного представления через Центральный районный суд г. Читы.

Судья: Копеистова О.Н.

Решение изготовлено в мотивированной форме 20 мая 2016 года.
