### ISSUE TITLE
нет доступа к картинкам, если сайт работает через прокси

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#290]
Если работать через прокси (например friGate), картинки не отображаются, выдаётся 403 ошибка... Возможно с разных ИП идут запросы, а может что то ещё у вас хитрое...

**Comment by inquisitor6789** [comment]
А может в настройках прокси дело...

**Comment by tebaly** [comment]
Да. Смотря что использовать. Кое какие настройки режут картинки и скрипты.

**Comment by tebaly** [comment]
Я проверю, но завтра и прокси не нужен будет. Потерпите пару часов :)
