### ISSUE TITLE
Разблокирование сайта, нужна помощь

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#291]
Как минимум от лица Пользователя сайта можно способствовать разблокированию сайта.
http://digitalrights.center/makedoc/user

Особо безбашенные имеют возможность делать запросы от лица администрации сайта)

Сайт был заблокирован по решению суда(деталей пока нет) #289 - действия конкурентов, вероятность 89%

**Comment by inquisitor6789** [comment]
рад бы помочь, но со временем вообще никак
