### ISSUE TITLE
Тормозит база, диалог обновляется до 10 минут

### ISSUE THREAD

**Issue by fenixnoir** [freedomsex/freedomsex#293]
При обновлении диалога (уже упоминал причину) страница с анкетой грузится моментально, а сам диалог хромает к ней даже без костылей. Время загрузки диалога от одной минуты и до десяти минут. Можно вообразить, будто код блока диалогов хранится в БД.

Сервер БД медленный/перегруженный? Вообще какой суточный отклик базы?

Вопрос считаю хоть и не приоритетным, но достаточно важным, аудитория падает.

**Comment by tebaly** [comment]
Это не база) База нонче просто летат :smile:

Исправлено, спасибо

**Comment by fenixnoir** [comment]
Увы. Закрывать рано. До сих пор проблема есть.
Кстати уже не первый раз такое...

**Comment by tebaly** [comment]
Да, сейчас. А чего вам не спится то?)

**Comment by tebaly** [comment]
5 минут до обновляются остальные хосты

**Comment by fenixnoir** [comment]
Ну, отвечая на вопрос, немножко пооффтопю...
У нас в гаражах, где у меня мастерская, резко урезали электричество, мне включают только на ночь, в итоге почти всю ночь прогревающемся мастерскую, один-два часа работаю, 3-6 часов сплю утром, когда электричество выключают, а потом весь день в машине отсиживаюсь, дабы не упустить вероятность раннего включения, или нормализации ситуации. Клиенты ждут.
В итоге получается, что мне банально скучно, но спать еще рано...

**Comment by fenixnoir** [comment]
Ок. Работает. Спасибо. А в чем проблема-то была?
