### ISSUE TITLE
Сервер прилег отдохнуть?

### ISSUE THREAD

**Issue by fenixnoir** [freedomsex/freedomsex#294]
Собственно взывает к Хьюстону...
Это он самовольно отдыхает, или у него секс с админом?

**Comment by inquisitor6789** [comment]
Скорее у админа с ним :-)

**Comment by fenixnoir** [comment]
Ежкин кот. Саша, объясните, что за проблемы с сайтом? Может помощь какая нужна? Не реально же так, мы всех пользователей растеряем...

**Comment by drvalera** [comment]
сейчас походу из-за блока и так дофига потеряли

**Comment by fenixnoir** [comment]
@drvalera, да вроде не должны (можно попробовать у Саши запросить статистику). Редирект вроде проходит до отсечки и нормально уводит на .me...

**Comment by drvalera** [comment]
Печально что модерка не работает((( опять надо будет набивать очки, а то до адмиина так и не дорос

**Comment by tebaly** [comment]
@drvalera  накину всем желающим)

**Comment by tebaly** [comment]
Большая, жирная черная полоса :disappointed_relieved:
