### ISSUE TITLE
Замечаний нет - для заблокированных

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#296]
Вероятно они тогда уже не нужны, но содержания типа "это проститутка" возможно кому-то мешают.

**Comment by drvalera** [comment]
Меня эти сообщения не напрягают. Я думаю можно и убирать их с блокировкой акка) И кстати что там нужно чтобы админку ты выписал? Помню ты тогда говорил обратиться.

**Comment by fenixnoir** [comment]
Замечания нужны у наказанных, у блокированных они реально бесполезны. А насчет мешают... Лично мне по барабану.
Кстати как там с репозитарием для покопаться/улучшить?

**Comment by tebaly** [comment]
Так не вам )) #289 :satisfied:
