### ISSUE TITLE
Обновление админки, принятие/сброс/списки решений

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#298]
Нужна ваша помощь. Предстоит обновить структуру БД, но перед этим необходимо обработать все скопившиеся в очереди заявки на подтверждение. Восстановлен доступ к интерфейсу модератора, затем, в течении суток начнем выкатывать новый/измененный интерфейс администратора. 

Изменения в основном структурные/архитектурные. Коротко

### 1. изменен подход к сущности "жалоба" 
Как и планировалось изначально, но не было реализовано раньше - сущность жалобы теперь _обезличена_. Изначально было сложно понять "как вообще это реализовать", и как это может/будет работать. Накопление информации в области администрирования позволило найти некоторые технические особенности/трудности и направить усилия на их реализацию и преодоление. Данное изменение фундаментально в разработанной ранее системе администрирования и потребовало переписать всё, что взаимодействовало с жалобами. Начиная от подачи жалобы Пользователем, заканчивая историей принятых решений и историей по жалобе.

Теперь не будет прямой связи _жалоба-пользователь_. Между ними вклинивается отдельная связь "заявки/обращения" - она ближе к сущности _жалоба_, а сущность _жалоба_, становится де факто сущностью _маркер_. Итого маркер > "заявки/обращения" > Пользователи

### 2. Новый алгоритм арбитража
Если очень коротко - сбросить теперь сможет любой. Так было изначально и планировалось как основа системы. Затем мы внедрили неоднозначную систему _подпись_, когда ограничивалась возможность сброса. Мы выпиливаем теперь данное ограничение, и возвращаемся к изначальной задумке - мониторинг/сброс любым модератором с необходимым для этого уровнем. Сущность _подпись_ - остается.

Изменение коснется стадии _принятия_ решения в арбитраже и вердикта. Его сможет сделать только администратор, чей рейтинг выше "подписи" сброшенной жалобы. Вы много раз указывали на необходимость ограничения возможности участия администраторов в принятии решений по сброшенным жалобам - теперь такое ограничение будет. Количество необоснованных сбросов решаем отдельно. 

### 3. Автоматический арбитраж
Новое. Направленно на необоснованные сбросы. До конца не реализовано. Но, если распространить идею - _сбросивший решение не может принять решение_ - в итоге получаем ситуацию со сброшенными решениями, которые никто не может обработать. Это один из выходов. Описание/обсуждение будет отдельно.

Спасибо.

**Comment by inquisitor6789** [comment]
модерилку вообще отключили?

**Comment by tebaly** [comment]
Пару часов на отладку нужно. Сегодня всё откроется. Ну почти всё..

**Comment by tebaly** [comment]
"модерилка" - открыта

**Comment by tebaly** [comment]
### Право быть забытым

Изначально при разработке интерфейса был заложен такой принцип. Работал на основе сигналов из интерфейсов администратора и модератора. Поскольку интерфейсы длительное время были недоступны, сигналы отсутствовали и многие "Нарушители" были "забыты" системой безопасности - это не баг, это фитча (c)

"Теперь не будет прямой связи жалоба-пользователь." - в связи с этим, при наличии самой истории по жалобе, теперь _может отсутствовать_ прямая связь с профилем Нарушителя. Такая связь по прежнему остается из списков "Замечаний", и на данный момент должна быть стабильной.

**Comment by tebaly** [comment]
Все интерфейсы открыты. Ожидаются баги, местами "ошибка 500".. :grimacing:
Пожалуйста, сообщите о обнаруженных неисправностях.
