### ISSUE TITLE
Дополнительная информация для администраторов

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#3]
Иногда для принятия решений не хватает информации.
Предлагается реализовать историю изменения анкетных данных.
В историю включать следующие пункты:
- изменение возраста
- изменение пола
- изменение имени
- изменение города
- изменение блока кого ищу

**Comment by tebaly** [comment]
Да, эти логи уже пишутся. Будет добавлено 100%

**Comment by tebaly** [comment]
https://github.com/tebaly/freedomsex/blob/dev/doc/news/20160619-Комментарии-к-профилю.md

**Comment by tebaly** [comment]
> изменение возраста
изменение пола
изменение имени
изменение города

> пусть многоуважаемая и всем надоедающая Юля пишет сообщение типа "Пользователь сменил имя с Александр, на Александра"
или типа "Пользователю было 30 лет, а тут внезапно он помолодел до 16"
ну или вообще "Пользователь сменил пол на Женский"

Имя меняется с полом _синхронно_. Невозможно быть парнем Машей например. Информация в имени оценивается модераторами - всё неподобающее удаляется с обновлением имени. Отсюда вопрос
* на сколько востребована будет информация по имени, если исключить возможность определение пола по имени?

**Comment by tebaly** [comment]
Для блокировки крайне важен факт "смены пола"

**Comment by mj4444ru** [comment]
**Из жизни:**
Поступает замечание "Каждые 5 минут меняет имя"
Что делать модератору? Одобрять или нет?

**Comment by mj4444ru** [comment]
Тоже касается города...

Человек вправе путешествовать, но не 10 городов в сутки...

**Comment by mj4444ru** [comment]
http://freedomsex.net/userinfo/profile/12530677/
я уже неоднократно обращал на это внимание
люди руками пишут имя...
и не в комментах, а в статусе...

**Comment by mj4444ru** [comment]
кстати хочу допонить что этот лог хорошо бы выводить прям в анкете, а не за кнопочкой как с историей статусов, иначе будет ровно то же самое что и сейчас...

**Comment by mj4444ru** [comment]
вот опять незнай что ответить
http://freedomsex.net/admin/sethelp/?id=141847&ln=141866

**Comment by tebaly** [comment]
Прошло ещё не совсем три года... Добавлено, отслеживается:
- изменение возраста
- изменение пола
- изменение имени
- изменение города

Наверное нет особого смысла в этом, не отслеживается:
- изменение блока кого ищу

---
Данные пишутся, завтра зарелизю компонент в админку.

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/32302491-0b5a68ba-bf74-11e7-8fc1-5e5bf267fafa.png)

Задержка ещё 1-2 дня

**Comment by tebaly** [comment]
Полез на оверхед задачи. 
* Выпилил сорсы админки из общего кодобазы
* Переписал на модули/компоненты, собрал вебпаком
* Пытался применить сторонние материал-компоненты, откатился

Теперь пробую выпилить саму админку на бэкенде и отдавать _дополнительные данные_ из отдельного микросервиса. Слишком оверхед, но что поделать. По каждой задаче из списка это +1-2 недели сверху... И всё ради компонента _истории данных_ анкеты :relaxed:

**Comment by tebaly** [comment]
Запустил админку на отдельном домене. Пока как сервис данных.

**Comment by tebaly** [comment]
@inquisitor6789 поспешил выкатить в тест на dev. Получилось сильно грязно и глючно в целом. Но по крайней мере эта функция уже работает. Остальное как обычно поотваливалось :stuck_out_tongue:

Буду править, про ошибки пока не сообщайте, я их знаю и исправляю.

**Comment by inquisitor6789** [comment]
дождемся препрода :-)

**Comment by tebaly** [comment]
Препрод готов :stuck_out_tongue_winking_eye:

Крутил мутил с настройкой webpack, толком не вышло ничего - поменял dev-server на livereload. 
Пока вроде норм

# Итого

Начато выпиливание админки из кодобазы сайта в отдельный подпроект/сервис. Начинаю переносить функционал админки в API, а сама админка переписывается на компоненты VUE, как и сам сайт. Возможно дела пойдут быстрее. Реализовано не все из запрошенного
- изменение пола
- изменение имени
- изменение города
- время обновления

Отсутствует
- изменение блока кого ищу
- изменение возраста

---

Блока "кого ищу" как такового не будет ввиду #496 
По возрасту честно не помню почему не добавил. То ли забыл, то ли решил что излишне получается. В общем как-то так...

**Comment by tebaly** [comment]
#499
