### ISSUE TITLE
что за резидент 302070?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#300]
что это за тип и за что ему резидента дали?

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/20355473/8014683c-ac32-11e6-88a6-b2550c2e531a.png)

Юлия (c) - тестовый акк, для отладки после обновы :smile:

**Comment by tebaly** [comment]
![](http://cs4.pikabu.ru/post_img/2014/12/08/5/1418022946_2052127172.jpg)

Юбилейный тикет с номером - триста :)

:tada:

**Comment by inquisitor6789** [comment]
я старался :-)

**Comment by mj4444ru** [comment]
Добавили нового резидента без разрешения Сергея... ах ах ах...

**Comment by inquisitor6789** [comment]
Вашим мнением забыл поинтересоваться.

**Comment by mj4444ru** [comment]
А зачем вам моё мнение? Оно дорого стоит, вам не по карману )))

**Comment by inquisitor6789** [comment]
Вот именно, что оно мне нафиг не вперлось

**Comment by mj4444ru** [comment]
Ещё и обманываете людей... Вы не забыли, а не хотели...

**Comment by inquisitor6789** [comment]
Вот именно. Так что можете остаться при нем.

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/20638729/24f799fc-b3c0-11e6-9f00-34b670cdb3b9.png)
