### ISSUE TITLE
Новая закладка не закрывается

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#301]
После сброса жалобы в арбитраж не закрывается новая вкладка. Чертовски не удобно

**Comment by tebaly** [comment]
в том смысле что "плодятся"?

**Comment by tebaly** [comment]
изменено "поведение". Новые вкладки для арбитража не открываются. Если обнаружатся проблемы с "возвратом" после обработки запроса, пожалуйста сообщите.
