### ISSUE TITLE
множественный сброс в арбитраж

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#302]
Похоже система "подписи" (или как ее лучше назвать) не работает.
http://freedomsex.me/history/message/263927/
Как видно по истории сбросов в арбитраж, админ с более низким рейтингом (#13546521) смог осуществить сброс сообщения в арбитраж после того как админ с более высоким рейтингом (#5040613) вынес вердикт по жалобе

**Comment by tebaly** [comment]
Новый алгоритм следующий:
* подпись теперь не блокирует сброс
* сбросить может каждый

Что изменилось:
* принять повторно решение можно в соответствии с подписью

Изучается:
* автоматический штраф (именно для озвученного случая)
* недоступность решения в арбитраже предыдущим наблюдателям

**Comment by tebaly** [comment]
Давайте я к вечеру активирую  
* автоматический штраф
* недоступность решения в арбитраже

оценим такие нововведения

Плохо:
* администратор инициирующий сброс не будет знать "будет ли штраф"

**Comment by inquisitor6789** [comment]
> Плохо:
администратор инициирующий сброс не будет знать "будет ли штраф"

а по моему это очень даже хорошо. Только было бы не плохо добавить инфу по наложеным штрафам в профиль модератора (или как это теперь называется?)

**Comment by tebaly** [comment]
@inquisitor6789 спасибо, включил ограничение по подписи. На первое время после обновления эта функция была неактивна. Аналогично автоматический штраф.
* Сейчас администраторам с меньшим рейтингом будут доступны для сброса принятые вами решения
* Но сброшенные решения не будут доступны для них в арбитраже.
* Несколько "таких" повторных сбросов должны привести к значительному снижению их рейтинга автоматически.

Пожалуйста, оцените нововведение в бою и выскажите ваше мнение. Спасибо.

**Comment by tebaly** [comment]
Да и бажина там (( количество "автоматов" не смутило?)

**Comment by tebaly** [comment]
Прошу прощения, в коде была ошибка. Сложные решения подвисали на голосовании, оно сбрасывалось в арбитражно, но не снималось с голосования. Такие дела...

**Comment by tebaly** [comment]
Подкорректировал.

**Comment by tebaly** [comment]
множественность сбросов, как "факт" должна перестать существовать
