### ISSUE TITLE
маленький косяк со временем

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#303]
![image](https://cloud.githubusercontent.com/assets/19651618/20556111/8f47bd74-b176-11e6-9aaf-8f2c11d3fa5d.png)

По какой-то причине после любого действия у меня счетчик времени устанавливается в -17 сек (на скриншоте в поле "комментарий"). Я конечно понимаю, что это ни на что не влияет, но как-то не аккуратненько.

**Comment by tebaly** [comment]
часы разбрелись.. поправил, спасибо.
