### ISSUE TITLE
жалобы на фото

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#304]
Есть подозрение, что при жалобе на фото она не публикуется в профиле нарушителя. Соотв невозможно объективно обрабатывать замечания.
Примеры
http://freedomsex.me/userinfo/profile/22253344
http://freedomsex.me/userinfo/profile/22033219
http://freedomsex.me/userinfo/profile/22231750

**Comment by tebaly** [comment]
Сейчас поправлю.

**Comment by tebaly** [comment]
жесткий баг - 583 жалобы на фото прошли мимо :unamused:

поправил

**Comment by tebaly** [comment]
спасибо
