### ISSUE TITLE
сброс в арбитраж

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#305]
в продолжении https://github.com/freedomsex/freedomsex/issues/301
До последних изменений после сброса в арбитраж система устанавливала фокус окна на том сообщении, которое сбросили в арбитраж (оно оказывалось в самом верху окна). В настоящий момент показывается начало раздела (разрешено, вирт, наказано). При этом не важно в какой части окна было сброшенное сообщение.

**Comment by tebaly** [comment]
таки да. Страниц/разделов где отображаются жалобы становится всё больше и больше. и у каждой жалобы есть ссылка на арбитраж. и как это всё корректно возвращать, я хрен его знает :confused:

Но я попробую, может что и получится..

**Comment by inquisitor6789** [comment]
а раньше это как работало?

**Comment by tebaly** [comment]
Костыли костыли костыли :grin: ой, да я просто ленивая жопа, и меня нужно постоянно пинать 

Поправил, спасибо :)

![image](https://cloud.githubusercontent.com/assets/9466814/20618688/9af3c636-b301-11e6-9c23-aa9bb541858a.png)
