### ISSUE TITLE
Взят курс на вирт

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#307]
Сервисы будут адаптированы под использование с этой целью. 

Ранее была заложена неопределенность
* Сервисы не разрабатывались с целью использования для вирта
* Вирт в системе был разрешен из-за фактической невозможности запрета

Теперь во все новые сервисы будет заложена возможность общения виртуально*. Уже функционирующие сервисы будут адаптированы под новые условия.

> Это нарушает принцип единой "ответственности", но видимо иначе не выйдет

\* общение не подразумевающее реальных встреч

Обсуждается

**Comment by tebaly** [comment]
Просьба ко всем администраторам смягчить отношение к Пользователям, использующим сайт лишь с целью вирта.

**Comment by inquisitor6789** [comment]
спам членов можно подвести под эту категорию?

**Comment by tebaly** [comment]
Нет, это по прежнему спам и рассылка. @inquisitor6789 я уже если честно и сам не знаю как к этому относить. Хотелось сделать сервис для реальных знакомств, но бороться судя по всему бессмысленно.

**Comment by inquisitor6789** [comment]
главное за виртом не забыть про реал :-)

**Comment by tebaly** [comment]
В этом и вся проблема. Сервис должен реализовывать достижение только одной цели, поэтому возможны только два варианта исхода.
* запретить вирт, сделать акцент на "реальности"
* разрешить вирт, и тогда через некоторое время сервис станет почти полностью "виртуальным"

**Comment by inquisitor6789** [comment]
не совсем понятно. Вирт, вроде, сейчас не запрещен. И вроде как народ особо не жалуется на нехватку каких-то сервисов для этого. Или планируется создать большое количество каких-то новых сервисов, которые будут способствовать виртуальным знакомствам?

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/20662190/78d3a8e6-b563-11e6-881e-11d33fdc8877.png)

**Comment by tebaly** [comment]
Право руля! ... Забудьте :sweat_smile:

**Comment by inquisitor6789** [comment]
ага, что-то типа этого
