### ISSUE TITLE
Новые модераторы и рейтинг

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#308]
Голосовалка не повышает рейтинг новых администраторов... Так задумано или баг?

**Comment by tebaly** [comment]
Вероятно баг. Уточните пожалуйста ID администраторов которые наблюдают проблемы со своим рейтингом.

**Comment by mj4444ru** [comment]
например этот 22432018

**Comment by tebaly** [comment]
Да. Баг, приношу свои извинения всем новым модераторам. Им рейтинг не засчитался

**Comment by tebaly** [comment]
Исправлено. Проверьте пожалуйста.
