### ISSUE TITLE
Криво работает поиск

### ISSUE THREAD

**Issue by alex-kag** [freedomsex/freedomsex#309]
Функция поиска планируется к доработке? а то сейчас идет поиск по полу собеседника.
Фильтр не учитывает пол того, кто ищет.

**Comment by inquisitor6789** [comment]
он всегда так работал

**Comment by alex-kag** [comment]
но это же не повод не исправить? 
просто для примера: профиль М, ищу Ж
логично, что выдача должна быть Ж, которые ищут М, а не Ж/Ж....
В базе вся инфа есть, так что не думаю, что это сильно много исправлять.

**Comment by inquisitor6789** [comment]
лучше в поиск еще параметр добавить, а не делать это автоматом. Чтобы получилось что-то типа "Я парень ищу Х". Где Х - парня, девушку, друзей. По умолчанию Х ставить из предпочтений того, кто ищет. Если делать жесткую зашивку, то пострадают би. Сегодня они хотят с одним, завтра с другим.
Это более гибкое решение.
Но последнее слово за владельцами

**Comment by inquisitor6789** [comment]
не все так просто.... А как же быть с не определившимися?

**Comment by alex-kag** [comment]
дать возможность не устанавливать это поле, или дать возможность множественного выбора....

**Comment by mj4444ru** [comment]
Ж/Ж в поиске выделяется серым... вам этого мало?

**Comment by tebaly** [comment]
@alex-kag - логика была в том, что знакомства для гетеро. Если кто-то любит в гомо или в группы - то для этого нужны отдельные сайты, типа знакомств для геев, знакомств для лесбиянок и свингер сайты знакомств. 

Так как регистрация автоматическая, и сделаны попытки устроить заполнение анкетных данных автоматически - автоматически мы можем записать не то, что есть на самом деле. Тогда анкета выпадает из поиска по вашей схеме. Мы же подсвечиваем гомо анкеты серым цветом.

**Comment by alex-kag** [comment]
так вся проблема что именно при поиске . я М, ищу Ж, мне выдает кучу анкет Ж ищет Ж. все они идут в разнобой. 
Так же хотелось бы "мертвых душ" - людей, которые не заходили давно, видеть в низу списка. и вот их-бы хотелось бы как-нибудь помечать /фильтровать.

**Comment by mj4444ru** [comment]
так всё так и есть... активные вверху... (ну по крайней мере так было пока некоторые всё не испортили своими обновлениями)...
а ЖЖ помечены серым, не обращайте на них внимания и всё...

**Comment by alex-kag** [comment]
ну, те что онлайн - они раскиданы в разнобой. это раз.  ЖЖ раскиданы среди правильных.

**Comment by alex-kag** [comment]
в плане фильтра - очень удачное решение на п.о.р.е.в.о.и.н.ф.о.

**Comment by mj4444ru** [comment]
> ну, те что онлайн - они раскиданы в разнобой

Вот тут лично я точно не понял что вы имели ввиду

> ЖЖ раскиданы среди правильных

Да, они среди всех остальных и ничего тут не сделаешь... Радуйтесь что хоть серым подсвечивают...

Просил сделать функционал для галочки "отображать только онлайн пользователей, и то не хотят"... Уж если это не сделали, остальное тем более не дождёмся...

**Comment by alex-kag** [comment]
так и я вот не сильно понял, можно ли дождаться исходников для ускорения процесса, или это не реально?

**Comment by mj4444ru** [comment]
> можно ли дождаться исходников

в теории - можно
по факту - нельзя

**Comment by alex-kag** [comment]
ясно, догда пользуемся тем, что доступно.  Больше открывать тикетов не буду.

**Comment by mj4444ru** [comment]
Ну не, вы открывайте... Просто на тему поиска у разработчиков своё мнение и они в танке...

**Comment by alex-kag** [comment]
так остальное все вроде бы устраивает. Плохо что не видно мертвых душ...

**Comment by mj4444ru** [comment]
> Плохо что не видно мертвых душ

Это как?
Пишите более развёрнуто, слишком много сокращаете, не понятно что конкретно имеется ввиду...

**Comment by inquisitor6789** [comment]
если мне память не изменяет, то сейчас анкеты сортируются по последнему отправленному сообщению. Обновление списка происходит раз в 15 минут.
Хотя, у меня иногда складывается впечатление, что где-то там косяк... Например на первых 3-4 страницах поиска может быть анкета с давностью посещения 6 дней назад. Для Москвы это несколько странно. На такое происходит не постоянно.

**Comment by alex-kag** [comment]
Плохо что не видно мертвых душ
Это как?
Пишите более развёрнуто, слишком много сокращаете, не понятно что конкретно имеется ввиду...
Мертвая душа - это человек, который есть в системе, но заходил в систему очень давно. Фактически - он только зарегистрировался. возможно когда-то был активен, но на данный момент не посещал сайт  уже "надцать" дней....

**Comment by inquisitor6789** [comment]
дык их на 10-15 странице поиска полно.
Только зачем они вам?

**Comment by mj4444ru** [comment]
что значит не видно? они в самом низу поиска...
то есть сначала идут активные, а потом "мертвые"...
поиск сортирует по последней активности... мертвые неактивны, по этому будут в самом низу... другое дело что сортировка может глючить...

**Comment by alex-kag** [comment]
с мобильного телефона пользоваться не удобно.

**Comment by tebaly** [comment]
> Хотя, у меня иногда складывается впечатление, что где-то там косяк...
Вернул как было. 
* Сортировка поиска каждые 10-15 минут
* Онлайн вверх при отправке сообщения
* Онлайн вверх при входе на сайт
* Онлайн вверх каждые 10 минут

**Comment by tebaly** [comment]
Над опцией "кого ищу" по теме вопроса, думаем.
