### ISSUE TITLE
наказано/блокировоано

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#310]
http://freedomsex.me/history/message/265851/
заметил, что при маркировке жалобы как "наказать" она сразу помещается в раздел наказано. Однако, для определенного количества жалоб надо выносить вердикт - блокировать. И поэтому приходится скидывать их в арбитраж.
Это так автоматизировали процесс принятия решений?

**Comment by tebaly** [comment]
Пофиксил. Была проблема в коде. Проблема должна уйти

**Comment by tebaly** [comment]
Спасибо :wink:
