### ISSUE TITLE
блокировка фейков

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#311]
http://freedomsex.me/userinfo/profile/22532654/
а разве некоторое время назад мы не пришли к соглашению (и даже его закрепили в тексте), что если по фото из инета нельзя идентифицировать человека, то мы не блокируем такие анкеты?

**Comment by tebaly** [comment]
Каюсь, грешен

**Comment by mj4444ru** [comment]
что за соглашение? кинь ссылку если не сложно...

**Comment by tebaly** [comment]
> (3) Интимные фото девушки скачены из интернета - блокировать?

> Интимные фото девушки скачены из интернета. Не стоит полагать, что все девушки готовы делать интим фото и отправлять их всем желающим. Вполне разумна ситуация, когда девушка отправляет обычную фотографию свою, настоящую, а в качестве интимной выбирает подходящее фото в интернете, которое имеет все сходства с "реальностью". Она просто не готова к таким действиям. Если блокировать только за это, можно перебанить массу реальных девушек на сайте. Ну накажите, ну опубликуйте замечание. Блокировка тут неуместна.

У настоящего фейка все фотографии будут фейкофые. Ведь нет резона отправлять обычное фото, принадлежащее другому человеку, скачивать и отправлять обычные фотки из вконтактика. Вот если девушка отправляет обычные фотки, не интимные, и они фейковые, тогда да, с большой вероятностью анкета фейк. Фейки часто скачивают сразу интернет подборку фоток и выдают их за свои.

https://github.com/freedomsex/docs/blob/master/deal/800-Неоднозначные-и-спорные-ситуации.md

**Comment by tebaly** [comment]
9 Несоответствие действительности

9.1. Использование ненастоящих фото или чужих фотографий крайне не желательно. Собеседник может подать жалобу обнаружив обман.
9.2. При обнаружении жалоб на ненастоящие фотографии Администратор может принять решение о блокировании анкеты.
9.3. Количество жалоб, приводящих к блокированию анкеты, субъективно, и может равняться 1 жалобе в строгом отношении к Пользователю или превышать 3 жалобы, при лояльном отношении к подобному нарушению.

https://github.com/freedomsex/docs/blob/master/rules.md

**Comment by mj4444ru** [comment]
а ну это старое, я помню ) думал что то новое есть...

**Comment by tebaly** [comment]
> Вполне разумна ситуация, когда девушка отправляет обычную фотографию свою, настоящую, а в качестве интимной выбирает подходящее фото в интернете, которое имеет все сходства с "реальностью". 

И тут можно поспорить. Ведь фотка не интимная.. Другое дело, что конкретно это фото **не** интернетное. Гугл не нашел ее [surprize]

**Comment by tebaly** [comment]
> пришли к соглашению (и даже его закрепили в тексте), что если по фото из инета нельзя идентифицировать человека, то мы не блокируем такие анкеты?

@inquisitor6789 вот кстати да. Где мы это закрепили? :grinning:
