### ISSUE TITLE
жалуются на 403 ошибку при просмотре фото

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#312]
http://freedomsex.me/admin/sethelp/?id=155356&ln=0

**Comment by tebaly** [comment]
C телефона сидят - включили сжатие трафика. Страница открывается с сервера гугла(прокси), а фотки грузятся со своего IP. На сегодняшний день мной не придуман костыль к этой ситуации.

**Comment by mj4444ru** [comment]
вместо 403 ошибки выводите картинку с текстом типа отключите сжатие трафика...
и вообще не вижу смысла запрещать с других IP... а что если сделать ссылку с ограниченным сроком действия, например 1 минута... внутрь ссылки помещаем юникстайм и бинарный мд5 завёрнутые в бэйс64... итого получаем 20 байт бинарного кода и 30 байт бэйс64... срок действия 1 минута...

**Comment by mj4444ru** [comment]
мд5 берём от времени, юзера, айди фото и соли...

**Comment by tebaly** [comment]
Времени чего? Man in the middle?

**Comment by tebaly** [comment]
@mj4444ru - да, в виду озвученной проблемы, ограничение по IP будет снято. Ограничивать будем по времени. Но решение ещё не принято.

**Comment by mj4444ru** [comment]
под временем я имел ввиду результат функции time()
фиксируем в ссылке время генерации ссылки, при загрузке фото извлекаем время из адреса, проверяем его повторным вычислением мд5 и если всё верно, проверяем не прошло ли более минуты с времени генерации ссылки...
