### ISSUE TITLE
работает ли бездна?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#313]
сабж

**Comment by tebaly** [comment]
Нет :pensive: баги. 
Спасибо. Исправлено. Проверьте пожалуйста.

**Comment by tebaly** [comment]
Начнут появляться жалобы в бездне.

**Comment by inquisitor6789** [comment]
пока не начали.... слабо верится, что за 3 дня не было ни одной записи для бездны

**Comment by tebaly** [comment]
Теперь должно заработать.
