### ISSUE TITLE
Популярность сайтов знакомств стремительно падает

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#314]
# Делюсь наблюдениями

![image](https://cloud.githubusercontent.com/assets/9466814/20798540/396479f8-b7f0-11e6-8cac-cdd322c37657.png)

![image](https://cloud.githubusercontent.com/assets/9466814/20798767/1e273896-b7f1-11e6-9c3e-d3cac1293f1e.png)

![image](https://cloud.githubusercontent.com/assets/9466814/20798782/2dd19408-b7f1-11e6-8f2e-2e9f51b98255.png)

![image](https://cloud.githubusercontent.com/assets/9466814/20798850/6c141b46-b7f1-11e6-8e0d-c2eee0547e4d.png)

**Comment by tebaly** [comment]
Либо народ просто перестает пользоваться "интернетом" в качестве платформы для знакомств и переходит в приложения. Либо изменилась сама "парадигма" отношения людей к знакомству, сексу и совместной жизни. Очень интересно.

**Comment by inquisitor6789** [comment]
Скорее первое чем второе.
Так же не стоит забывать, что определенная часть народу ушла в соц сети. Особенно это касается молодежи. Они кроме вк (и иже с ним) ничего не знают.

**Comment by tebaly** [comment]
> часть народу ушла в соц сети. 

Они тоже уже не популярны. Пик давно пройден. Люди покидают и соцсети. Мы просто отстаем по трендам от "цивилизованных стран". То что динамика ВК не такая явная - вопрос времени. Дуров не дурак, он не просто так свинтил оттуда и взялся за мессенджер..

![image](https://cloud.githubusercontent.com/assets/9466814/20829429/138c3890-b88d-11e6-9059-aa5cabdcef51.png)

![image](https://cloud.githubusercontent.com/assets/9466814/20829444/23c7e880-b88d-11e6-866f-11801c527dde.png)

**Comment by inquisitor6789** [comment]
И какой нынче тренд? Апликухи? Дык народ давно просил приложение :-) правда в последнее время таких просьба нет, но все же...

**Comment by tebaly** [comment]
На первых слайдах можно увидеть провал **Badoo** - это гибрид соцсети и сервиса для знакомств. Очень яркие данные - людям не нужен ни сервис знакомств, ни соцсеть - поэтому мы наблюдаем такое катастрофическое падение Badoo. Куда все пошли мать их?

**Comment by tebaly** [comment]
> И какой нынче тренд? Апликухи? 

Ой, вопрос не из легких. Я пока так и не понимаю куда все двинули.

Тренд общий - показывает "заинтересованность" в сервисе в целом. То есть, популярность приложения от Фэйсбук вероятно проседает симметричным образом. Я хотел бы проверить статистику скачиваний приложений, но пока не нашел как и где.

**Comment by inquisitor6789** [comment]
А много ли даст такая статистика? Ведь она не покажет как часто им пользуются?

**Comment by tebaly** [comment]
У меня пока только одно предположение - людям стал _не интересен_ сервис соцсетей для общения(основная задача) и просмотра фото(вторая по популярности).
* кому нужно общение, ушли в ватсапп и тому подобные мессенджеры (только рост)
* кому нужны фотки, пошли в инстаграмм (только рост)
* видео, контент - ютуб и онлайн сервисы (без динамики)

Это объясняет провал соцсетей в целом. Но у соцсетей осталась важная функция - база данных о людях, друзьях друзей. Проведите соц опрос, лучшим способом знакомства люди считают знакомство _с другом друга_. Вот тут лучшего, чем соцсети нет.
* соц.сети всё чаще используют для знакомств
* выборка потребности в _знакомствах_ значительно меньше выборки потребности _коммуникации_

Моё предположение можно характеризовать как
Потребность коммуникации: соцсети > мессенджеры 
Потребность в знакомствах: сервисы знакомств > соцсети

Общий тренд _по теме_: сервисы знакомств > соцсети > мессенджеры 

---
Но есть парадокс - мессенджеры никак не удовлетворяют потребность в знакомствах. Соц сети не адаптированы для поиска знакомств, но пока справляются. Сервисы знакомств имеют функционал для знакомств, но их базы стремительно пустеют. Пустые базы никак не поспособствуют росту популярности.

**Comment by inquisitor6789** [comment]
Кстати насчет мессенджеров, а не возникало ли идеи приспособить чатбот для наших целей? Или как-то по другому использовать возможность мобильной платформы?

**Comment by tebaly** [comment]
>  идеи приспособить чатбот

Раскройте тему пожалуйста :)

**Comment by inquisitor6789** [comment]
А фиг его знает как это можно сделать. Еще и сохраняя анонимность.

**Comment by mj4444ru** [comment]
набирают активность ватсап, вибер, друг вокруг... мне кажется в нашем регионе друг вокруг станет скоро на ровне с контактом...

**Comment by mj4444ru** [comment]
мамба, баду, ловпланет, там в основном сидят те кто когда то давно туда пришли, новых там нет, а если и заходят, долго не задерживаются...

**Comment by mj4444ru** [comment]
не знаю как в ловпланет, далее буду писать про баду и мамбу...

парням там не нравиться по тому что:
- баду всегда вела агрессивную ценовую политику... популярным (красивым) девушкам можно писать только заплатив за суперсилу... причём часть анкет фейки (вижу анкету знакомой девушки, спрашиваю лично, сидишь в баду? нет, первый раз слышу)... постоянно предлагают писать некрасивым девушкам, что тоже раздражает...
- мамба в виду малой популярности пошла на обман, подключая смс сервисы без спросу, и делая новых девушек круглосуточно онлайн... что видимо оттолкнуло людей и они одумались... далее они решили пойти по пути баду, разрешив писать не более 10 сообщений одной девушке, свех лимита могут писать только випы... в итоге красивым девушкам могут писать только випы... большинство девушек ищут богатеньких... раньше часть аудитории привлекали проститутки, но мамба активно боролась с ними с помощью таких как я и в итоге они все ушли в друг вокруг, где проститутция формально разрешена... девушек всё меньше, соответсвенно отток больше чем приток...

**Comment by mj4444ru** [comment]
Новые девушки не задерживаются по тому что при регистрации им могут писать только випы... набегает толпа випов со своими секс предложениями, в итоге девушки не хотят дочитывать все сообщения и забивают... а если есть 8 (ранее 10) непрочитанных сообщений, обычные люди писать не могут... вот и получается что красивым девушкам могут в начале писать только випы озаботы, а потом вообще никто не пишет, вот и уходят...

**Comment by mj4444ru** [comment]
у мамбы есть сервис анонимных знакомств... там в основном либо мошенники, либо проститутки... так как всё анонимно, даже пожаловаться нельзя...

**Comment by mj4444ru** [comment]
как появился друг вокруг:
он появился неожиданно, вместо аськи... не надо было регистрироваться, только номер телефона и всё... при общении собеседник видит полноценную фотку в профиле и микрофотку в списке сообщений и контактов), автоматический поиск друзей по номеру из записной книжки... это как раз то, до чего не додумались сделать в аське... хотя они конечно сделали это всё, но было уже поздно...

для чего используют друг вокруг:
- для общения вместо смс
- для знакомства (уникальный удобный поиск)
- для общения в общем чате (в эфире)
- если в эфире пишут сотни людей, то читают его тысячи...

друг вокруг не просит денег за всё подрят... дарит деньги просто за общение...
иногда борятся с мошенниками...
отправлять хуи как тут не получиться... 

сейчас добавили модерацию эфира самими пользователями...

**Comment by inquisitor6789** [comment]
поставил ради интереса себе этого друга.... такого количества блядей на мегабайт я видел только на мамбе.
С фотками - вопрос открытый как лучше.

**Comment by tebaly** [comment]
@mj4444ru благодарю вас за качественный обзор. На мамбу давно не заходил. Поражен масштабом безумия которое они там творят. Как понимаю, выжимают максимум, так как реально пузырь лопнул, и роста у них уже не будет.
