### ISSUE TITLE
Неверный падеж при указании города

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#315]
Вероятно что то у вас не так в интерфейсе, если много людей пишет город в стиле:
В Азербайджане Баку
В Бровары
В Уфе
В Казахстане
В Орша
В Днепродзержинске
Риге
Турции

А ещё часто встречаю очень имеющие некоторое сходство и идущие подряд города
Волгоград Обл Фролово  ?  
Липецкая Обл Город Грязи  ?  
Днипропетровька Обл  ?  
Калининградская Обл  ?  
Россия Саратов
Россия Обнинск

Что то мне кажется это фейки... как их таких найти? можно конечно через поиск, но они наверняка уже сменили город...

**Comment by tebaly** [comment]
Нет. Не фейки. "Пользователи". Скоро поправим, как наладим фильтр городов нормальный
