### ISSUE TITLE
Глюк?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#317]
На странице принятия решения по жалобе если сбросить в арбитраж, то система принимает решение "разрешено".
http://freedomsex.me/history/message/267658/

**Comment by tebaly** [comment]
если не ошибаюсь, ставит то, к чему пришло голосование

**Comment by inquisitor6789** [comment]
т.е. кнопка арбитража из "решения" не работает?

**Comment by tebaly** [comment]
Нет. Оно должно отправить в арбитраж. Если это не так - то глюг точно.

**Comment by inquisitor6789** [comment]
вот еще свежий пример
http://freedomsex.me/history/message/267841/
100% что я нажал на "арбитраж".

**Comment by tebaly** [comment]
Исправлено. Спасибо.
