### ISSUE TITLE
Предопределенный список замечаний

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#318]
Переделать систему замечаний. Составить список стандартных замечаний. 
1. **Предложение оплаты услуг**, вирт за деньги, проституция, мошенничество, спам, шантаж, вымогательство, иные противозаконные действия.
2. **Обман, чужие фотографии**, вымышленные данные, несоответствие действительности, фото из интернета, парень под видом девушки, фейк, провокация 
3. **Оскорбления, хамство**, отвратные фото, картинки из интернета, троллинг, преднамеренные оскорбления, грубые сообщения, мат

### Только одно замечание к анкете.

Оставить возможность постить "авторские" замечания, или не оставлять.

PS: будет заблокирована возможность отправки фотографий без "первого" ответа собеседника. Таким образом, спам фото становится невозможным.

**Comment by inquisitor6789** [comment]
Имеется ввиду замечания от пользователей?

**Comment by tebaly** [comment]
Да.

Витает мысль в голове, что это можно объединить со статусом профиля Нарушителя. 
* тогда публикация замечания одновременно равно "смена статуса на выбранный"
* "смена статуса на выбранный" равно публикация замечания админом - даже тогда, когда замечаний от Пользователей на Нарушителя нет.

**Comment by mj4444ru** [comment]
Крайне мутная идея... В таком варианте лучше точно не делать...

**Comment by tebaly** [comment]
Слишком бурное обсуждение :smile:
На данный момент пять предопределенных

* Предложение оплаты услуг, вирт за деньги, проституция 
* Мошенничество, развод на деньги, шантаж, вымогательство 
* Обман, фото из интернета, вымышленные данные, фейк 
* Оскорбления, хамство, троллинг, грубые сообщения 
* Рассылка интим фото, спамит, провоцирует

**Comment by mj4444ru** [comment]
вымышленные данные? о дааа... мне сразу авансом впилите это замечание... 

а вообще бред... по всем пунктам не  согласен...  нерационально и неправильно...

**Comment by mj4444ru** [comment]
рассылку интим фото убрать, это должна делать кнопка под присланной фоткой если уж так хочется.

**Comment by tebaly** [comment]
Поскольку возражений нет..
