### ISSUE TITLE
вот такая вот фигня

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#319]
http://freedomsex.me/security/delcity/E%3CIframe+Src961515Com%3E%3CIframe%3E/0/

**Comment by mj4444ru** [comment]
![2016-12-12 12 43 01](https://cloud.githubusercontent.com/assets/9354685/21091525/921bbe28-c068-11e6-86d6-b6c3c1ffca19.png)

**Comment by inquisitor6789** [comment]
и не удаляется

**Comment by mj4444ru** [comment]
это пример успешной инъекции... ну или не очень... но всё равно страшно...

**Comment by mj4444ru** [comment]
![2016-12-12 14 49 29](https://cloud.githubusercontent.com/assets/9354685/21094735/1ee73740-c07a-11e6-999c-13a9f0b5446e.png)

**Comment by mj4444ru** [comment]
хорошо хоть =, / и " вырезаете

**Comment by inquisitor6789** [comment]
![image](https://cloud.githubusercontent.com/assets/19651618/21094873/0584a8ba-c06a-11e6-9a6e-3d16d4c54af5.png)
они видимо добьются своего

**Comment by mj4444ru** [comment]
да не, это я уже сделал... проверял как это на фронте выглядит... вроде безопасно...

**Comment by tebaly** [comment]
@inquisitor6789 кто они?) пытаются взломать. Все возможности используют. Только вот найдут ведь в итоге...

**Comment by tebaly** [comment]
Это пока XSS ищут

**Comment by inquisitor6789** [comment]
> хорошо хоть =, / и " вырезаете

надо бы еще и <> вырезать... ну и вообще все не буквы (кроме тире)

**Comment by tebaly** [comment]
94.41.80.224 - уфа
http://ru.infobyip.com/ip-94.41.80.224.html

**Comment by inquisitor6789** [comment]
странно, что через города ломать начали. Было бы логичней через желания

**Comment by tebaly** [comment]
@inquisitor6789 с месяц назад через куки просунули запросы к базе. Ну она и их сохранила как текст :)

**Comment by tebaly** [comment]
В именах с прошлой недели пробелы запрещены. Там чуть сложнее стало.

**Comment by tebaly** [comment]
Полей пользовательского ввода относительно мало. По всем в базе предустановленн лимит по длине. Для имен ~15 символов. Для городов 20-30. Стараюсь фильтровать ввод. Нашли лазейку, скорее всего используя кодировку/кодирование.

**Comment by mj4444ru** [comment]
какую лазейку? просто вставляется в поле города и все...

**Comment by mj4444ru** [comment]
тебалай, вы зачем меня палите? последние запросы мои...  раньше смотрите...

**Comment by mj4444ru** [comment]
@tebaly по вашему я в гаражах сижу? )))

**Comment by tebaly** [comment]
@mj4444ru ссорян ) 

https://ipgetinfo.com/?mode=ip&lang=en&ip=31.181.63.229

Темрюк - СОШ №2 - школьники ломятся :satisfied:

**Comment by tebaly** [comment]
Пропатчил. Непотребства почистил. Тэги не пройдут. НО, зная мой стиль программирования... могут вылезти баги...

**Comment by tebaly** [comment]
Спасибо за обнаруженный баг.
