### ISSUE TITLE
Скайп и другое

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#321]
> приветик давай в скаип общаться (в разделе "наказано")

у нас теперь нельзя предлагать общаться в скайпе, вибере, ватсапе?

я понимаю что проститутки и т.п. могут такое писать, но в самом сообщении нарушения нет...

**Comment by tebaly** [comment]
Это был бы не @mj4444ru если бы не возразил по этому случаю :sweat_smile:

приветик [означает приветствие, оно же здравствуйте, он же в подавляющем числе случаев "начало знакомства"] давай в скаип общаться [есть предложение отказаться от общения на сайте в угоду использования стороннего сервиса, а именно - скайп]. - Исходя из того, что данное сообщение в преобладающем числе случаем может трактоваться как приветственное в начале знакомства, а в данном случае, как ответ на приветственное сообщение собеседника, данное сообщение я бы отнес к _скрытой схеме мошенничества_ изначально. Далее, такое решение легко подтверждается другой жалобой на этого же Нарушителя - "не общаюсь здесь только в скапе".

Как вы уже хорошо знаете, у нас **категорически запрещено** отказываться от общения в угоду иных сервисов общения, а именно, делать это _в начале знакомства_. Так как в подавляющем большинстве это необходимо мошенникам. Кстати, последнюю упомянутую жалобу я бы заблокировал вообще, так как в дословном исполнении используется только мошенниками.

**Comment by tebaly** [comment]
Здесь же. Контактные данные по типу _логина скайпа_ в случае явной принадлежности мошенникам необходимо блокировать. Одиночный логин либо в любом ином контексте, пусть даже вообще безобидном необходимо блокировать. Так как его наличие формирует уникальность содержания сообщения имеющего запрещенные признаки.

В качестве стёба, @mj4444ru поясню отдельно:
* никто из модераторов не сможет оценить такого рода жалобы в "наказано" - все они придут в итоге в разрешено
* в этом нет ни ошибки модератора, ни ошибки системы даже близко
* такого рода жалобы невозможно правильно промаркировать ни автоматически, ни по регламенту
* только вручную, только индивидуально, только в контексте

И "разрешать" естественно нельзя. При наличии признаков **уникальности** такого рода жалобы необходимо маркировать в соответствии с контекстом их употребления.

---

Сказанное выше может спровоцировать у _некоторых_ модераторов/администраторов приступ потери смысла. Но это лишь кажущееся ощущение.

> Содержание жалобы нужно оценивать в отрыве от контекста, что необходимо из-за технической особенности работы системы. 

Никак не противоречит сказанному выше, поскольку  **содержание жалобы** - а жалоба как раз и содержит контактные данные мошенников.

Скользкость случая в том, что сразу выяснить принадлежность контактных данных мошенникам получается не всегда. После получения "подтверждения", администратор вправе самостоятельно перенести* данную жалобу в заблокированные. Рекомендуется помечать все подозрительные жалобы с контактными данными как "наказано".

@mj4444ru оба случая я характеризую как _сложные_ - действия модераторов в таких случаях мы с вами обсуждали.

**Comment by tebaly** [comment]
Вообще, любые жалобы имеющие _признаки уникальности_ необходимо, а иногда крайне важно маркировать в соответствии с контекстом употребления. Например, случается, что кто-то со злости распространяет _чужие контактные данные_ третьих лиц, будь-то номер телефона, адрес в соцсети и так далее. 
* в случае подозрения или наличия "не проверяемых" обращений третьих лиц, такие жалобы рекомендуется маркировать как "наказано"
* при имеющихся признаках незаконности или запрещенности - блокировать. Равно как и при обращении субъекта персональных данных к администраторам (владелец телефона, страницы соцсети).

**Comment by tebaly** [comment]
@inquisitor6789 есть ли у вас возможность/желание проинспектировать Правила/Справку/Соглашения на наличие несогласованности и/или отсутствие пунктов правил охватывающих вышесказанное?  https://github.com/freedomsex/docs/blob/master/rules.md

**Comment by mj4444ru** [comment]
@tebaly согласен со всем вышесказанным,  но жалобу "приветик давай в скаип общаться" и другие не содержащие "контактные данные", "намёков" и какой либо вообще привязки к мошенникам считаю наказывать несправедливо... если мошенник будет писать "привет, давай обменяемся фотками" (с целью незаконного распространения потом и т.п.), это не повод это сообщение заносить в заблокированные...

**Comment by inquisitor6789** [comment]
не совсем понял на счет блокирования логинов. Учитывая, что сообщения оцениваются без контекста, то тут обнаруживается определенная проблема по определению мошеник это или нет. Например, http://freedomsex.me/history/message/269412/ логин irinasova1991 мошеник это или нет можно определить только после того, как в анкету посмотрел.
Теперь предлагается блокировать все контакты? Логины, адреса почты, ссылки на вк? А не боитесь, что пострадают невинные?
Что же касается отказа общаться на сайте (старт пост), то стараюсь не зверствовать. Там по сообщению с вероятностью 95% писалось от имени женщины. Это даже без контекста понятно. Но памятуя, что у нас "очень крутая" система безопасности посчитал нужным это наказать, что бы не пострадали невиновные (ну или пострадали, но не сильно; от капчи еще никто не умирал)

Кстати, http://freedomsex.me/history/message/269415/ было бы не плохо как-то ее отмаркировать. А то она очень долго в арбитраже висеть будет :-)

Правила и соглашения могу проревьивить, но это будет не скоро, т.к. на работе определенный завал наблюдается.

**Comment by tebaly** [comment]
Опять вас несет в степи троллига...

"привет, давай обменяемся фотками" - в соответствие с законодательством не имеет запрещенного содержания. По данному содержанию не усматривается ни злого умысла, ни побуждения к противозаконным действиям. 

http://freedomsex.me/блог/строго-запрещено/ 
> **Запрещены все явные и не явные мошеннические схемы**. Запрещено просить перейти на другой сайт, включая сайты знакомств или интим знакомств, просить позвонить по указанному телефону, или созвониться в скайпе и т.п. с целью продолжения _всего разговора там_, категорически **отказываясь общаться здесь под любыми предлогами**. Таким образом мошенники пытаются обойти систему безопасности.

Данный пункт Соглашения считаю в полной мере конкретным и он не будет меняться. Оспариваемая жалоба соответствует описываемому намерению и побуждению к действиям.

> "приветик давай в скаип общаться"
> "давай в скаип общаться"

Второе абсолютно разрешено! Хотя вашими глазами не видно разницы, подчеркну - приветствие, в совокупности с предложением отказаться от использования нашим сервисом - является запрещенным действием. Наказано, так как только лишь признаков не достаточно для "блокирования", но признаки имеются, поэтому "наказано". 

Сложное решение - оно от того и сложное, что принимаемое решение неоднозначно.

"не общаюсь здесь только в скапе" - по моему мнению необходимо блокировать. Жалоба имеет явно запрещенного содержания.

---

К вам лично была просьба, а затем строгая рекомендация - не притягивать в обсуждения тем с тегами #противозаконныедействия #незаконно #нарушениезаконодательства :цитата:

> будет писать "привет, давай обменяемся фотками" (с целью незаконного распространения потом и т.п.)

Прошу вас, не использовать данный контекст в обсуждениях. Мне кажется, у меня аллергия..

**Comment by tebaly** [comment]
Правилами и соглашениями должен заниматься я, но по аналогичным причинам не могу сделать этого сейчас, от того и просьба.

|Вопрос|Ответ|
|-----|-----|
Теперь предлагается блокировать все контакты? |  нет
Логины, адреса почты, ссылки на вк? |  нет
А не боитесь, что пострадают невинные? |  нет

* никто из модераторов **не сможет оценить** такого рода жалобы в "наказано" - все они **придут в итоге в разрешено**
* в этом нет ни ошибки модератора, ни ошибки системы даже близко
* такого рода жалобы **невозможно правильно промаркировать** ни автоматически, ни по регламенту
* **только вручную**, только индивидуально, только в контексте

Общие принципы системы безопасности в глубине
* от децентарализации к иерархии
* от автоматического управления к _ручному_

Система в 90% случаев работает в автоматическом режиме, и, если все модераторы следуют описанному регламенту, делает это хорошо. В 5% - система безопасности совершает ошибки. И еще в 5% случаев система не может работать в автоматическом режиме, и требует ручного управления.

И на этот случай давно есть решение - _shadow-table_(скрытая таблица в БД). Если я буду задействовать этот механизм всё чаще, вопросов будет ещё больше. _shadow-table_ - полностью отделен от интерфейса модерирования и создан как раз для случаев аналогичных употреблению контактных данных. Когда уж мы дойдем до интерфейса "супер-админ", этим разделом смогут управлять резиденты с уровнем доступа "системный-администратор" - на сегодняшний день это как минимум @inquisitor6789

**Comment by tebaly** [comment]
Пару слов о двухконтурной системе. Упомянутый _shadow-table_ механизм принадлежит ко второму контуру и управляется строго в ручную. Доступ к его управлению сейчас только у разработчиков. Разработчики на данный момент очень редко вмешиваются в процесс администрирования. А в виду подготовки "новогодних подарков", им просто нет на это времени.
* в таком случае ожидается вакханалия в администрировании по части уникального, но не явного контента в системе принятых решений.

http://freedomsex.me/блог/мониторинг-решений/
> **Как именно работает ваша система безопасности и блокировок?**
... Второй контур создан для защиты от ручного спама и высокоорганизованных автоматических систем. Детект фэйков и троллей возможен **исключительно вручную** модераторами и администраторами. Ошибки в применение с этой целью контурной защиты могут навредить реальным пользователям.

Как бы я упомянул об этом всём в самом начале, но ясности не дал. 
> ... "Блокировать" за оскорбления стоит только в крайнем случае, если оскорбление **имеет признаки уникальности**, а отправитель является троллем, цель которого на сайте лишь провокации и оскорбления.

Контуры:
I. Система принятия решений по жалобам
II. Скрытый раздел ручного управления

В первом контуре нельзя маркировать жалобы "по контексту" - только по содержанию. Но(!) **наличие контактных данных в тексте жалобы как раз и формирует ее содержание**.

**Comment by tebaly** [comment]
Администраторам разрешено использовать первый контур "не по назначению" и в нарушение некоторых принципов регламента в таких случаях. А именно, _в случаях требующих ручного управления_ для противодействия противоправным действиям.

По факту, ничего вы не нарушаете! Ни принципов администрирования, ни регламента, ни морали(если кого-то это задевает):
* жалоба промаркирована в соответствии с содержанием
* жалоба содержит контактные данные
* **имеется подтверждение принадлежности контактных данных мошенникам**

То есть, вся сложность в том, что момент подтверждения "принадлежности контактных данных мошенникам" отстает по времени с принятием _правильного_ решения. Но это ничего не меняет и не отменяет.

Для исключения конфликтов
* при сбросе такого решение можно указать комментарий "контакт принадлежит мошенникам"
* при вынесении решения/вердикта и наличии такого комментария лучше прислушаться к комментарию

**Comment by tebaly** [comment]
Наличие
* номера телефона
* логина скайпа
* ссылки на соцсеть, ВК и тд
* ссылки на сайт (спам)

Делает любое сообщение **уникальным**. Поэтому тут стоит действовать как и со спамом. И никому вы не навредите. Но, **не все сообщения с контактными данными** одинаково полезны.
* только если имеются доказательства принадлежности контактных данных мошенникам, индивидуалкам, иным элементам противозаконных групп.

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/21217227/2ed4ef0a-c2bc-11e6-83d0-086f86c53416.png)

**Comment by inquisitor6789** [comment]
если уж пошла такая пьянка, то вопрос по сообщениям типа "я парень, хочу чтоб меня отодрали" http://freedomsex.me/history/message/269570/
в настоящий момент, такие сообщения разрешаются. Но, как показывает практика, на 99.9999% это сообщения с фейковой анкеты.
Такие сообщения уникальны только в части "я парень". Дальше может следовать что угодно.

**Comment by tebaly** [comment]
@inquisitor6789 - прошу прощения. Уникальность связи "текст жалобы"="конкретный человек"

Например, текст "Привет, отвечаю в твиттере @inquisitor6789 " - сто процентов будет связан с вами лично. И не важно, кто будет отправлять сообщения с таким содержанием
* вы, с целью спама/рассылки/мошенничества
* ваш сообщник @mj4444ru чтобы увеличить охват Пользователей
* я, с целью дискредитировать Вас среди Пользователей сайта и администраторов 

Во всех этих случаях, блокировка не навредит никому кроме вас в 1 и 2 случае. И навредит мне, но выйдет благом для вас в 3-ем случае.

**Comment by tebaly** [comment]
@inquisitor6789 - логика здравая. Когда в анкете указано "Парень", зовут Ваня - сообщение с таким началом выглядит глупо.

Именем Российской Федерации
Властью, данной мне Конституцией РФ (Статья 3 п. 2) повелеваю!
Наказывать всех за сообщения "я парень ...". 

![image](https://cloud.githubusercontent.com/assets/9466814/21220744/60643bc0-c2cb-11e6-9704-fa0d3d76f75a.png)

**Comment by tebaly** [comment]
Поправки
* за дословно "я парень" не наказывать
* наказывать, если ему что-то нужно \*бздыщ\*

**Comment by mj4444ru** [comment]
Что вы зациклились на мошенниках... Под данной фразой можно подразумевать "приветик давай в скаип общаться" => "приветик, давай в скаипе по видеочату повиртим"... Так что не убедили...

на счёт "я парень, хочу чтоб меня отодрали" давно придлагал наказание не по факту написания, а по факту жалобы... то есть условно наказано - когда при написании пропускаем, а  если поступает жалоба, наказываем...

по поводу "К вам лично была просьба, а затем строгая рекомендация" - я прислушиваюсь к вашим рекомендациям, правилам и пожеланиям... но всё в пределах разумного...

**Comment by tebaly** [comment]
@mj4444ru - без "приветика", милости просим. А так, у нас сайт знакомств - извольте сначала познакомиться, а уже потом скайп. Это одно из жестких требований на нашем проекте. И это требование предупреждает и спам и мошенничество. 

Цель спамеров "в идеале" - отправить всего одно сообщение получателю с тем чтобы смотивировать его к действию. Удлинение цепочки сообщений на **+одно**, снижает "спам" на _две трети и более_. Удлинение **на два** сообщения - остается _не более 10%_ спамеров. Свыше трех сообщений - _единичные спамеры_, ручной/индивидуальный спам.

**Моя цель - жестко требовать отправки не менее 3-5 сообщений собеседнику, прежде чем позволить обменяться ссылками или предложить общение в другом сервисе.**

**Comment by mj4444ru** [comment]
давно ждал когда вы это напишете...  (без "приветика" и Моя цель)
только мне кажется сам факт борьбы как на уровне модераторов так и на уровне посетителей самый эффективный способ и значительно эффективнее всяких автоматических фильтров, под которые можно легко подстроится...

**Comment by tebaly** [comment]
Мне всегда интересен диалог и я это очень ценю, спасибо. "Придуманная" СБ была эффективной не с самого начала. строгие фильтры "ослабляются" по мере необходимости. Но, сама СБ основана на  нескольких принципах, одним из первых тот о котором сказано выше:
* вы на сайте знакомств - знакомьтесь. 
* все ваши скайпы и соцсети в первом сообщении - спам

**Comment by tebaly** [comment]
@mj4444ru @inquisitor6789 - мы же с вами задолго до этого всё в правилах зафиксировали

> 5 Мошенничество недопустимо
5.1. Запрещены все явные и не явные мошеннические схемы.
5.2. Попытки обхода системы безопасности, с целью заманить Пользователя на свою территорию для безнаказанного осуществления мошеннической деятельности запрещены.
5.3. Запрещено просить перейти на другой сайт, включая сайты знакомств или интим знакомств, с целью продолжения всего разговора там, категорически отказываясь общаться здесь под любыми предлогами.
5.4. Запрещено просить позвонить по указанному телефону, или **созвониться в скайпе и т.п.** с целью продолжения всего разговора там, категорически отказываясь общаться здесь под любыми предлогами.
5.5. Просьбы о смене места общения **не должны быть похожи на действия мошенников**. Такие действия стоит отличать от нормальных предложений пообщаться в другой соцсети, по телефону или скайпу.
5.6. Просьба о смене места общения **не должна быть в начале общения или ближайшее время после его начала**, так как это делается мошенниками для экономии своего времени и большего охвата потенциальных жертв.
5.7. Категорический отказ от общения на нашем сайте в пользу иного сервиса для общения должен свидетельствовать о возможных злонамеренных действиях такого Пользователя. В совокупности с иными признаками может указывать на принадлежность данного действия к скрытой мошеннической схеме.

По теме запроса там даже править нечего.. Пункт 5.6 полностью описывает причину.

**Comment by tebaly** [comment]
По поводу контактных данных давайте сейчас поправим. Я пока внесу свои правки (14 раздел), присоединяетесь.

**Comment by tebaly** [comment]
Готово

**Comment by tebaly** [comment]
> 9.8. Крайне не рекомендуется сообщать собеседнику о своей половой принадлежности, месте проживания, возрасте в личных сообщениях. Жалобы на подобное содержание могут расцениваться как попытка введения в заблуждение посредством указания в анкете данных, не соответствующих действительности.  
> 9.9. Оправдания своих действий Пользователями в части не указанных данных, неверно указанных данных и/или невозможности исправить указанные данные может свидетельствовать о эксплуатации таких действий в мошеннической схеме.  

Пункты 9.8. и 9.9. по части жалоб "Я парень" и "На самом деле я из Москвы"

**Comment by mj4444ru** [comment]
сумма сошли? я против...

**Comment by mj4444ru** [comment]
если "я парень"  написал парень, о нарушения нет, а если девушка, то не наказывать, а блокировать надо...  так что в корне не верный подход...

**Comment by mj4444ru** [comment]
если я живу в волжском, я могу написать Волгоград и это тоже нормальная ситуация... они рядом...

**Comment by mj4444ru** [comment]
указывать не свой возраст и имя это вообще нормальная ситуация для этого сайта...

**Comment by mj4444ru** [comment]
С учётом всего выше написанного затрудняюсь решить разрешено что то типа такого "Привет давай устроим виртик по скайпу?" или нет? вроде как всё как обычно, простой вирт, но склоняюсь к варианту НЕТ... а вы что скажете?

**Comment by tebaly** [comment]
Без паники :sweat_smile:

Во первых, **если в анкете указано то, что не соответствует действительности - это обман**. И нечего спорить вообще.

> указывать не свой возраст и имя это вообще нормальная ситуация для этого сайта...

Во вторых, про имя не сказано ни слова. Возраст не точный, но реальный.

* указано 30 - на самом деле 33 - норма
* указано 20 на самом деле 18 - норма
* указано 20 - на самом деле 30 - наказать
* указано 80 - на самом деле 20 (троллинг) - наказать / блокировать
* указано 18 - на самом деле 40 (троллинг) - наказать / блокировать
* указано 16 - на самом деле 12 - блокировать

>  и это тоже нормальная ситуация... они рядом...

* и кто же это будет определять?
* а если я из Владивостока, но в сообщении пишу, что из Москвы - это не норма

> так что в корне не верный подход...

В третьих, **если вы парень, на кой хрен вам писать собеседнику, что вы парень?** - такие сообщения однозначно плохо пахнут.

---

Данный пункт 9.8 введен для случаев жалоб по типу "я парень..." о чем говорил @inquisitor6789 выше. Про город и возраст - от меня лично. Его применение напрямую зависит от адекватности администратора - **"могут расцениваться как"** - а могут и не расцениваться...

Никто не запрещает - _не рекомендуется_. Так как такое поведение может боком выйти.

**Comment by tebaly** [comment]
@mj4444ru - хватит абстрагировать на правила. Вы можете писать всё что хотите - ваша задача, чтобы на вас _не жаловались_ по поводу того, что вы там написали.

**Comment by tebaly** [comment]
> "Привет давай устроим виртик по скайпу?" - простой вирт, но склоняюсь к варианту НЕТ... а вы что скажете?

Нет ничего плохого в том, что кто-то введет капчу для подтверждения отправки сообщения, в том случае, **если такая мера будет снижать или ограничивать действия мошенников**. 

Мной было обнаружено, что предложение _общаться_ в скайпе или созвониться по телефону - зачастую исходят от мошенников. Если вы обнаружите, что сообщение "Привет давай устроим виртик по скайпу?" используется мошенниками - отметьте "наказано". Если нет, то здесь предложение вирта в первом сообщении - "только вирт".

**Comment by mj4444ru** [comment]
про скайп я с самого начала был согласен с вами... 

а вот скажите мне как система распознает разницу между:
- указано 20 на самом деле 18 - норма
- указано 20 - на самом деле 30 - наказать

это не спасёт вас от фейков и тролей (которые уже научились юзать голосовалку для борьбы с капчей), но нагадит нормальным людям...

**Comment by tebaly** [comment]
Система - никак. Ей вообще на всё насрать - это машина, железо. Системой управляют администраторы - как скажут, так и сделает. Вы в корень запутались. У администраторов сейчас есть масса инструментов. Пункт 9.8 предупреждает Пользователей, что так делать можно, но администратор в некоторых из таких действий способен "узреть" мошенничество - и тогда пи..дец.

Одновременно, пункт 9.8 дает право администраторам толковать сие действия как попытку введения в заблуждение, и использовать любые инструменты, какие посчитают применимыми в данной ситуации.

Не придирайтесь. Нигде не сказано, что за неверный возраст нужно банить. 

---

@mj4444ru  если вы считаете нужным сообщить о противоправных действиях в части нарушения Правил сайте или фактах обхода системы безопасности, пожалуйста, выделите для этого отдельную тему и добавьте туда необходимые для этого скриншоты, ссылки, наблюдения. Спасибо.

**Comment by mj4444ru** [comment]
Вы сегодня не в духе? Устали?

**Comment by tebaly** [comment]
Наоборот) дух есть, но я действительно подустал :smile: 
это просто неформальное общение, меня просили раньше
