### ISSUE TITLE
Заморозка решений

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#322]
Не удивляйтесь, обнаружив зависшие в арбитраже решения, которые при этом недоступны в самом арбитраже. Так выглядит заморозка по _принципам последнего принятого решения_. Вмешаться могут только разработчики и резиденты с уровнем доступа "системный администратор"(скоро). 
* Ни на что не влияет. Система учитывает последнее принятое решение
* Когда придут "разрабы", разберутся и разморозят, или разберутся и не разморозят...

Пример
http://freedomsex.me/history/message/269415
http://freedomsex.me/history/message/269272
http://freedomsex.me/history/message/266584

Такое состояние есть плохо для тех, кто допустил очевидные или преднамеренные ошибки в этих решениях. Фитча ещё изучается

**Comment by tebaly** [comment]
@inquisitor6789 @mj4444ru - вы поднимали вопрос по _неадекватным_ заморозкам. Скиньте пожалуйста примеры, где решение зависло не в том разделе, и его нужно перенести. 
* если решение _висит_ там где надо - это нормально, ведь оно на своём месте.

**Comment by inquisitor6789** [comment]
как попадется такое, то отпишу
больше раздражает, что они зависли
ведь висеть ничего не должно :-)

**Comment by inquisitor6789** [comment]
http://freedomsex.me/history/message/330712/
имхо должно быть в вирте

**Comment by tebaly** [comment]
> ведь висеть ничего не должно

Немного иначе - гонять туда-обратно без надобности не нужно. Поэтому и зависает. Чаще всего зависает там где нужно или когда от смены раздела мало что меняется. 

Так как фитча в процессе изучения, косяки можно исправить по требованию. Остальное после внедрения "структур/организаций".
