### ISSUE TITLE
Недочёт

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#323]
![2016-12-20 21 18 48](https://cloud.githubusercontent.com/assets/9354685/21358212/cdbaf812-c6f9-11e6-8c6a-38c87e3e255f.png)

**Comment by tebaly** [comment]
Спасибо. Но в чём именно?

**Comment by mj4444ru** [comment]
в заблокированном домене :)

**Comment by tebaly** [comment]
Почта же ходит? Технически нет причины менять почту.

**Comment by mj4444ru** [comment]
я не знаком с тонкостями блокировок, но если провайдер на внешнем маршрутизаторе залочит сайт для клиентов, это же может и заблокировать отправку почты с почтового сервера провайдера...

**Comment by tebaly** [comment]
я тоже не знаком :) проверял, почта ходит с майлру и гугла. поменяю после НГ для достоверности

**Comment by mj4444ru** [comment]
Гугл не в России, а майл и яндекс делают всё что бы пользователи не замечали хотения наших властей...

**Comment by tebaly** [comment]
Я исправлю скоро
