### ISSUE TITLE
Предупреждение: На сообщения от этого пользователя поступают жалобы

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#325]
Вобщем пока не прочтёшь это х*** сообщение, остальные не открываются, можно кликать до посинения на пункт "Сообщения" вверху анкеты... Лично для меня непонятно как быть дальше... Думаю остальным тем более...
![2016-12-21 23 28 36](https://cloud.githubusercontent.com/assets/9354685/21401232/45238db6-c7d5-11e6-94b5-28b0373a119d.png)

**Comment by tebaly** [comment]
А если кликнуть "Посмотреть сообщения" - откроются?

**Comment by mj4444ru** [comment]
Если кликнуть, то далее всё как обычно...

**Comment by mj4444ru** [comment]
Так понимаю сообщение становится прочитанным только после клика на "Посмотреть" и в этом проблема...

**Comment by tebaly** [comment]
Йоп тип топ) Я проблемы не вижу... На вашем скриншоте даже замечание есть (!) - не нужно эти сообщения показывать сразу - **плюс один клик**. Если память не ошибает - вы всё правильно поняли - _сообщение становится прочитанным только после клика на "Посмотреть"_ 

PS: Вы там ещё собственный freedomsex с блэкджеком и шлюхами не сделали?)

**Comment by mj4444ru** [comment]
В том что сообщение не становиться непрочитанным, я тоже проблемы не вижу...
А вот то что система не даёт читать при этом сообщения других пользователей, тут однозначно проблемка есть...

PS: вы как бы сообщаете что что-то не так, но при этом фактически обязываете пользователя прочитать это нехорошее сообщение, а это ни есть гуд, особенно когда у девушки 50 непрочитанных сообщений...

**Comment by mj4444ru** [comment]
PPS: с блэкджеком сложности однако, так что пока только шлюхи есть...

**Comment by tebaly** [comment]
>  читать при этом сообщения других пользователей, тут однозначно проблемка есть...

А такого быть не должно

**Comment by tebaly** [comment]
Спасибо. Пофиксил.

Сказывается только на тех, кто заработал капчи сверх "нормы".  Раньше в таком случае должен был отображаться другой текст, типа "вы что-то нарушаете, как не хорошо, атата" при попытке написать сообщение.

Отключил пока. Проверьте пожалуйста, ушла ли проблема в вашем случае.
