### ISSUE TITLE
я парень, просто пишу с аккаунта своей сестрички

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#326]
> Знаешь на самом деле я парень, просто пишу с аккаунта своей сестрички(у нас с ней час назад был секс))) Я тут нашел ее фоточки:3

объясните мне тупому, почему это не блокировано, а только наказано?

в тексте содержится информация при которой абсолютно не важно кто написал, но автор однозначно достоин блокировки (по причине фейк/тролль/парень по видом девушки)...

**Comment by tebaly** [comment]
Ну.. Смотрите. Вы всё верно сказали - **автор однозначно достоин блокировки**. Моими словами - анкету нарушителя блокировать нужно однозначно. Но вот само сообщение. 

Я только вчера писал о том, что системе безразлично на то, кто и что пишет. Все ее действия исходят от действий администраторов напрямую. Много модераторов и администраторов мыслят в том ключе, что если противозаконно, то блокировать, если нет - наказать. В этом сообщении нет ничего противозаконного, это раз (и мы не будем с вами это развивать). 

Далее, я открываю раздел решений по "блокировано", и вижу - "Мошенники, предложения оплаты, индивидуалки, спам ссылки." - то есть, нет там "братья, которые сестры"...

**Comment by mj4444ru** [comment]
Да мне вообще пофиг на законы, сайт международный, а законы всех стран я знать не обязан... Есть правила сайта, формальные и неформальные правила администраторов... Если сообщение однозначно говорит что автор достоин блокировки (без контекста), значит надо помещать в блокировано... Разве не логично? В чём минус этого подхода? Я вижу лишь плюсы... В первую очередь для администраторов...

**Comment by tebaly** [comment]
@mj4444ru давайте ставить маркеры там, где это нужно. Если пользователь начнет вести себя по типу "Саши минского" - тогда маркер нужен будет. Если единичное "употребление" - то не стоит захламлять этим раздел "блокировано". Вот прям острой необходимости не вижу, честно.

**Comment by mj4444ru** [comment]
Не понять мне ваши фактически приравнивания раздела блокировано к проституткам и вымогателям денег... 
Для меня сообщение либо идентифицирует нарушителя, либо нет... И не важно что там за нарушитель...

**Comment by tebaly** [comment]
> либо идентифицирует нарушителя, либо нет...

* _только вирт_ - по факту, спамить вирт нельзя, это **нарушение**. Да и в принципе позиция по вирту у нас хоть и неоднозначная, но не хотелось бы. Ожидалось такое нарушение _фильтровать_, но такой фильтр не включен до сих пор. Но нет гарантий, что в один прекрасный солнечный день он не заработает.
* _наказать_ - **нарушения**, всё что нежелательно, но НЕ смертельно. Точнее, то за что банить мало.
* _блокировать_ - **нарушения**, за которое явно нужно банить.

Действующая система гибше чем "либо идентифицирует нарушителя, либо нет"

И вы снова абстрагируете на правила. Натрете мозоли :smile:

**Comment by mj4444ru** [comment]
а тут простите банить как то не явно надо? в том что за это нужно банить вы согласились...
> автор однозначно достоин блокировки

**Comment by mj4444ru** [comment]
> наказать - нарушения, всё что нежелательно, но НЕ смертельно. Точнее, то за что банить мало.
> блокировать - нарушения, за которое явно нужно банить.

я опять с вами согласен, но почему то это не работает :worried:

**Comment by tebaly** [comment]
@mj4444ru - есть возможность банить в профиле нарушителя.

**Comment by mj4444ru** [comment]
о, зачем тогда вообще нужен раздел блокировано?

**Comment by tebaly** [comment]
Не скажу :stuck_out_tongue_winking_eye:
