### ISSUE TITLE
готовятся сюрпризы?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#327]
https://chrome.google.com/webstore/detail/fds-helper/opekekncnpkljanbmddpdlhmeiinebpo

**Comment by tebaly** [comment]
Я не в курсе. Я другой сюрприз готовлю :relaxed:

![image](https://cloud.githubusercontent.com/assets/9466814/21419026/4a5e0b42-c836-11e6-97ec-c72ef48e1f00.png)

@mj4444ru - вы что там темните?)

**Comment by tebaly** [comment]
@inquisitor6789 - а вы как это отыскали??

**Comment by inquisitor6789** [comment]
да как-то так http://freedomsex.me/history/message/271421/

**Comment by inquisitor6789** [comment]
а, это наш @mj4444 развлекается :-) не обратил внимания на автора

**Comment by tebaly** [comment]
@inquisitor6789 есть подозрения, что @mj4444 строит свой собственный freedomsex с блэкджеком и шлюхами :smile:

**Comment by mj4444ru** [comment]
ага, китайская копия freedomsex :smiley:

**Comment by mj4444ru** [comment]
> Я другой сюрприз готовлю 

Это вы о чём?

**Comment by tebaly** [comment]
Новогодний подарок. Рано ещё :santa:

**Comment by inquisitor6789** [comment]
блэкджек?
шлюх и так много :-)

**Comment by tebaly** [comment]
@inquisitor6789 - с год-два назад нас пытались скопировать, добавив всего того "чего у нас нет". Не пошло... Хотелось бы также проследить развитие "китайского" варианта.

**Comment by inquisitor6789** [comment]
> развитие "китайского" варианта

эммм.... проследить развитие плагина для нашей модерилки?

**Comment by tebaly** [comment]
@inquisitor6789 не уверен что только только плагином дело ограничится))) слишком много тонкостей

**Comment by inquisitor6789** [comment]
пока только плагин, причем недоделаный

**Comment by mj4444ru** [comment]
> слишком много тонкостей

это вы о чём? ну просто очень любопытно что вы там ещё себе понапредставляли...

**Comment by inquisitor6789** [comment]
![image](https://cloud.githubusercontent.com/assets/19651618/21428687/62a29494-c86c-11e6-81a2-e554ee79c28a.png)

**Comment by tebaly** [comment]
Я тоже умею в плагины для хрома, но меня "никто" об этом не спрашивал. Какова по вашему причина? @inquisitor6789 вы вспомните как от нас "уходили", соберите воедино отношение ко мне лично, к "системе безопасности", к администраторам - я думаю вы получите ту картину, на которую я смотрю уже как год. Если мне память не подменяет, началось все в ноябре/декабре прошлого года.

Так вот. Стал ли бы человек, у которого "пропало всякое желание в администрировании" писать плагин для ненависного сервиса, сугубо для себя... Ведь нас с вами на вечеринку так и не пригласили :cold_sweat:

**Comment by inquisitor6789** [comment]
> Ведь нас с вами на вечеринку так и не пригласили 

![image](https://cloud.githubusercontent.com/assets/19651618/21429054/24e1826c-c86e-11e6-9909-42d894e54fb1.png)

такими темпами он фридому совсем не конкурент если только спустя год плагин состряпал. Хотя, надо отдать ему должное, есть там одна удобная фишка - нотификация о новых жалобах.

**Comment by inquisitor6789** [comment]
а если серьезно, то, я подозреваю, что он просто смотрит по открытым ссылкам и делает доп обработку инфы. Внутрь не лезет

**Comment by tebaly** [comment]
Далее. Моя память опять может обмануть, но расширения для хрома пишутся на JS. Даже судя по скриншотам, плагин сделан достаточно грамотно. То есть, сделавший его человек может не только в JS но и в CSS фреймворки, разбирается в сетях и тд. 

@inquisitor6789 смотрите, JS - публичная штука. Я намеренно не обфусцировал и не сжимал код, чтобы любой желающий смог его посмотреть. Поверьте мне на слово, любой, кто взглянет, не сможет удержаться от матов. Но в ответ, тишина :simple_smile:

Отсих и сомнения... Зачем так поступать?

**Comment by inquisitor6789** [comment]
@mj4444ru, вам есть что сказать?

**Comment by tebaly** [comment]
```
mode.paranoia.state = "on"

text = "В статистике скачивания вполне можно следить за модераторами/администраторами установившими расширение. Думаю вполне будет доступна информация об: "

spy_info = {
    "IP": "ваш IP адрес и время доступа",
    "user_agent": "идентификатор браузера, операционной системы и параметры дисплея"
}

info = "Дальше зависит от фантазии разработчика"

**Comment by tebaly** [comment]
С точки зрения безопасности - это очень нехорошо. Для **личного** использования публиковать расширения не обязательно(!) они прекрасно работают локально, в режиме разработчика)

**Comment by mj4444ru** [comment]
@tebaly я ожидал от вас большего...

**Comment by tebaly** [comment]
Например?

**Comment by mj4444ru** [comment]
Вот зачем мне айпи и браузер? куда более ценная информация есть на ......

**Comment by tebaly** [comment]
Где?

**Comment by mj4444ru** [comment]
я вам даю время подумать...

**Comment by tebaly** [comment]
Ой, хрен с ним, палите

**Comment by mj4444ru** [comment]
http://freedomsex.me/profile.php

**Comment by tebaly** [comment]
Ну из статы инфа чуть более достоверная.

**Comment by mj4444ru** [comment]
Плагин "может" получить не только куки, но и логин администратора с паролем... Ну и поменять например их...

**Comment by tebaly** [comment]
Вы же в курсе, что расширение можно сделать так, что оно будет отправлять инфу на сервер разработчика. Иногда, можно сделать так, чтобы получить инфу с других открытых вкладок :confused:

**Comment by tebaly** [comment]
Вот мы сейчас не о том. Вы нам "подарок к новому году готовили", хотели приятно сделать, или как?

**Comment by mj4444ru** [comment]
А вы нам?

**Comment by mj4444ru** [comment]
У плагинов всё ж есть хорошая сторона... Они опенсурс...

**Comment by mj4444ru** [comment]
А вы так и не пошли мне на встречу и не дали апи... Пришлось извращаться...

**Comment by tebaly** [comment]
Опенсурс - иногда делают в команде. :cry:

API просто нету. То что есть, это не апи... Там нет ни REST ни JSON - лишь изредка. Давать то нечего, а то что есть (обычные контроллеры, иногда даже страницы php) - легко посмотреть.

**Comment by mj4444ru** [comment]
я думал хотя бы модели у вас есть... выдать их в json не так много кода... другое дело с командами... но там не думаю что на много сложнее с учётом того что MVC (и т.п.) должно структурировать и упрощать код...

**Comment by tebaly** [comment]
Нет там ничего - беда там, я об этом говорил в самом начале.

**Comment by mj4444ru** [comment]
сочувствую...

**Comment by mj4444ru** [comment]
![2016-12-22 20 25 36](https://cloud.githubusercontent.com/assets/9354685/21430385/d7ca9574-c884-11e6-89b1-11547e53421c.png)
![2016-12-22 20 26 03](https://cloud.githubusercontent.com/assets/9354685/21430386/d7cae718-c884-11e6-8ab5-b9681b964e2d.png)

**Comment by mj4444ru** [comment]
![Uploading Снимок экрана от 2016-12-22 20:25:10.png…]()
![2016-12-22 20 26 03](https://cloud.githubusercontent.com/assets/9354685/21430408/ec2c4b8e-c884-11e6-9701-8d62c8789db9.png)

**Comment by mj4444ru** [comment]
![2016-12-22 20 25 10](https://cloud.githubusercontent.com/assets/9354685/21430417/f6a02e32-c884-11e6-8b3c-fbbdf8addb12.png)
![2016-12-22 20 26 03](https://cloud.githubusercontent.com/assets/9354685/21430418/f6a0fff6-c884-11e6-8656-dd48548ea03d.png)

**Comment by mj4444ru** [comment]
давайте модераторскую переделаем в таком стиле? будет одна страничка... с вас аякс данные, с меня сама страника...

**Comment by tebaly** [comment]
Давайте после НГ. Причины я говорил
Стиль хорош)

**Comment by mj4444ru** [comment]
да я понял что подарок готовите...

**Comment by tebaly** [comment]
дело закрыто)

**Comment by mj4444ru** [comment]
добавил всплывающее уведомление при новых событиях... для наглядности...
