### ISSUE TITLE
черный список желаний

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#328]
Планируется или нет такой функционал? Задолбали педофилы

**Comment by tebaly** [comment]
да. сейчас просмотрю

**Comment by tebaly** [comment]
он есть

**Comment by tebaly** [comment]
Спасибо. Мало времени, за всем не успеваю. Массу подчистил, сейчас остальное посмотрю. Инструмент станет доступен резидентам в будущем. Скоро, относительно..

**Comment by inquisitor6789** [comment]
что-то как-то криво стало работать.... покликайте по желаниям (все равно каким). Раньше желания сортировались в порядке их добавления (я надеюсь). Сейчас же вообще не понятен принцип сортировки.

**Comment by tebaly** [comment]
Мой косяк. Сейчас попробую исправить. Всё работает как надо. Отображение заглючило..

**Comment by inquisitor6789** [comment]
не, не исправилось
или кэш надо почистить?

**Comment by tebaly** [comment]
Так я и не сказал что исправил уже :grimacing:

А вот сейчас исправил. Но не на 100% - в течении суток (2-3 часа) это пропадет. 

Спасибо

**Comment by inquisitor6789** [comment]
> Всё работает как надо.

сорян, вот это смутило

**Comment by tebaly** [comment]
Технически)) Визуально отображение проглючило, но это временно.

**Comment by inquisitor6789** [comment]
вроде заработало, но после удаления пары страниц желаний
