### ISSUE TITLE
несовершеннолетние и сортировка жалоб

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#329]
@tebaly не надо напоминать что это запрещённая для меня тема, я помню... 

"Хорошо,ну если честно мне 13 лет но очень хочется пососать" - ранее в таких сообщениях ничего страшного администраторы не видели и переносили в раздел "Разрешено", теперь вот такая тема в разделе "Блокированно"...

Просто хочу знать что поменялось...

**Comment by tebaly** [comment]
Я не участвую в администрировании. тем более, что я разработчик по

**2.3. Администрация сайта не влияет на процесс принятия решений Сообществом, и не участвует в нем;
2.4. Администрация сайта не одобряет и не отклоняет принятых Сообществом решений, ни самостоятельно, ни по просьбам третьих лиц;**

> Администрации сайта как таковой, в общем понимании или толковании такового понятия, не существует. Проект создан и развивается в рамках саморегулируемого Сообщества. Администрация сайта большей частью выполняет функции по обслуживанию работы систем сайта, их разработку и совершенствование, включая обслуживание и масштабирование серверного оборудования и так далее.

**Comment by tebaly** [comment]
За комментариями вы вправе обратиться к Администратору, принявшему решение. Или к любому администратору/модератору Сообщества с более высоким рейтингом.

**Comment by mj4444ru** [comment]
1. @tebaly вы лукавите. 
2. это обращение было к хозяину этого решения, а он читает гитар. 
3. @tebaly если у вас нет мнения на эту тему, не обязательно было закрывать обращение.  тут вы не одни.

**Comment by mj4444ru** [comment]
1. @tebaly вы лукавите.
2. это обращение было к хозяину этого решения, а он читает гитхаб.
3. @tebaly если у вас нет мнения на эту тему, не обязательно было закрывать обращение. тут вы не одни.

**Comment by tebaly** [comment]
Начиналось с обращения ко мне лично. Напишите ему лично :kissing_heart:

**Comment by mj4444ru** [comment]
к вам только первая строчка...

**Comment by inquisitor6789** [comment]
в чем проблема? я никогда не разрешал такие сообщения.
Если есть доказательства, то в студию
иначе дружите с регламентом

> это обращение было к хозяину этого решения, а он читает гитхаб.

и откуда такая таинственность? Пальцем тыкнуть можете?

**Comment by mj4444ru** [comment]
> и откуда такая таинственность?

да нет никакой таинственности... я думаю и так понятно к кому вопрос...

**Comment by tebaly** [comment]
Ребят. Пользуясь своей магией, я запрещаю вам продолжать обсуждение темы здесь.
![image](https://cloud.githubusercontent.com/assets/9466814/21485689/c3a5fb8e-cbb7-11e6-8133-4070b9ef3f4f.png)

@mj4444ru напоминаю вам что это запрещённая для вас тема :kissing_closed_eyes:

Кстати, Администрация сайта (в частности все Администраторы сообщества) _вправе игнорировать обращения с просьбой дать комментарии своим действиям_. **Действия так или иначе касающиеся "законности" крайне рекомендуется игнорировать.** @inquisitor6789 - рекомендую вам воздержаться от комментариев по этой теме, и остановить обсуждение.

Я ответил не потому, что вы снова подорвали мой пукан, а потому, что вы своими "благими намерениями" начинаете провоцировать Администраторов сообщества. Если подобное положение дел начнет доставлять дискомфорт Администраторам сообщества, мы вручим вам, @mj4444ru титул **Почетного тролля сообщества** :boom:
* это позволит официально обращаться к вам как _мистер тролль_, _господин тролль_ и тд
* а также отвечать на ваши вопросы - _Гражданин, хатит троллить_

**Comment by mj4444ru** [comment]
А на гитхабе троллить правилами запрещено?
да да, я смеюсь и над вами @tebaly над @inquisitor6789 
я буду до последнего защищеть интересы нормальных пользователей, хоть 100 титулов мне дайте )))

**Comment by tebaly** [comment]
За заслуги перед Сообществом, за самоотверженную защиту интересов Пользователей, награждается @mj4444ru [овации и восторженные крики]

![image](https://cloud.githubusercontent.com/assets/9466814/21487839/718e0b32-cbe6-11e6-8ad5-f3be1dc85a68.png)

**Comment by inquisitor6789** [comment]
эххх... а так хотелось ответить... Но если босс сказан нет, то придется послушаться :-)

**Comment by mj4444ru** [comment]
@inquisitor6789 спрятались за мамину юбку? никто не говорил "нет"...
