### ISSUE TITLE
Юмор над проститутками

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#330]
> Встречное предложение. За тысячу отправлю сперму в баночке. ПыСы - выгляжу хорошо, ничего не болит!

Я конечно понимаю что у некоторых тяжело с юмором (очень тяжело)... Но давайте как то с этим что то сделаем?

Ну реально парень постебался над проституткой...

**Comment by tebaly** [comment]
я вас умоляю... http://absurdopedia.net/wiki/Абсурдопедия:Про_список_Минюста - ему пригрозили реальным сроком за шутку :disappointed_relieved:

а вообще, я тут не при чем.

**Comment by mj4444ru** [comment]
это намёк у кого вы учитесь? так вот не тех вы выбрали за пример для подражания...

**Comment by tebaly** [comment]
А вы их ни за кого не считаете?

**Comment by inquisitor6789** [comment]
при принятии решений у меня отсутствует чувство юмора и включается режим максимальной паранойи

**Comment by mj4444ru** [comment]
@inquisitor6789 человек отличается от животного тем что он умеет логически мыслить...  недавно в контакте в публичной группе видео было, где собака умнее человека... 

ну или  даже  пример из абсурдопедии будет ближе...  
давайте не будем как они? вы же не модератор первого уровня и за подобные решения вполне достойны сброса рейтинга...

**Comment by inquisitor6789** [comment]
назовите мне хоть 1 пункт правил, который был нарушен при принятии решения.

**Comment by tebaly** [comment]
Ну крайний случай же..

**4.5. Запрещено отправлять прайс, стоимость услуг, описание услуг, ценники, иное - так или иначе подразумевающее предстоящие и/или фактические финансовые взаимодействия между Пользователями.
4.9. Запрещены любые предложения купли-продажи, что не ограничено предложениями покупки видео и фотографий.**

Ранее, в предыдущей версии правил/соглашений была фраза приблизительно такого содержания "запрещено предложение оплаты(оскорблять) услуг даже в шутку". Затем было изменено, дабы не вызывало похожих ситуаций. 

@mj4444ru, @inquisitor6789 - если принципиально, можно "вернуть" похожую формулировку в правила. И более, описать алгоритмы касающиеся юмора. Это к тому, что это две различные ситуации. НО! И там и там юмор:
(а) Отдамся тебе за тыщу. ой, нет - шучу конечно
(б) Встречное предложение. За тысячу отправлю сперму в баночке

Администраторы вправе не иметь юридического образования - это для случаев "незаконного содержания", когда заблокировали, но фактического нарушения законодательства не было, а было просто похоже. Оттолкнитесь от этого, и получите то, что администраторы _не обязаны иметь чувства юмора_. Это уже когда в шутке есть намеки на нарушения. Дабы не повторяться, это всё описывает 13-й раздел.

Моё личное мнение - правила сайта и вся система созданы для борьбы с мошенниками (1), индивидуалками(интим услуги) (2), спамом/рекламой (3). Если озвученный контекст "продажа спермы" был использован **конкретно этим пользователем** однократно - говорить о коммерции излишне, равно как и о рекламе услуг. Далее смотрим **в целом по системе** - если случай "продажи спермы" единичен, вероятно он не достоин внимания. И дальше, здравый смысл - продавать сперму в баночке относительно сложно. В теории, я допускаю появление таких коммерческих предложений. Но про реальность данного случая говорить не возьмусь. Но я с чистой совестью поставил бы маркер "наказано" для профилактики.

@mj4444ru - свой спрос имеет продажа мочи в баночках, нижнего белья со следами калла и так далее. @inquisitor6789 - если факт единичный локально и в целом по системе, да и угрозы не несет, можно "брать его под наблюдение" не применяя никаких мер.

- _Отдамся тебе за тыщу. ой, нет - шучу конечно_ - необходимо блокировать не обращая внимания ни на контекст шутки, ни на фактический отказ от озвученного
- _Встречное предложение. За тысячу отправлю сперму в баночке_ - стоит наказать/блокировать, если случай повторяющийся/массовый соответственно.

Правила нарушены - да - 4.8 и 4.9
Можно было не наказывать - думаю да.

Сам случай не анализировал, опирался на имеющуюся в топике информацию - а её здесь минимум.

**Comment by mj4444ru** [comment]
админисирирование ресурса, это определенная ответственность и администратор должен немного разбираться в аудитории, которую администрирует... 

1) прежде всего администратор должен понимать, что пользователь не в курсе о существовании правил, правила нужны тут только Администраторам (как регламент)... 

2) пользователи могут шутить (иногда даже там где шутить запрещено законом и знаканчивается это большим штрафами)... но так как у нас шутить не запрещено, пользователи рассчитывают на адекватное восприятие шуток администраторами  (видимо зря)... 

3) администратор должен иметь хоть чуточку мозгов что бы понимать что есть что...  что бы отличать фейковые замечания от обычных и т.д....

**Comment by tebaly** [comment]
Иии. Не совсем. Вот вам новые правила.

>  **15 Содержание вне контеста употребления**
 15.1. Незаконное и/или неправомерное содержание может быть признано таковым вне контеста их оригинального употребления.  
 15.2. Цитирование неправомерного содержания крайне не желательно. Равно как и употребление его в любом ином контексте.   Автоматические системы не в состоянии давать оценку контексту употребления содержания, и ожидаемо могут расценить его как неправомерное.  
 15.2. Употребление неправомерного содержания в качестве шутки, даже прямо отрицая серьезность намерений, также нежелательно. Администраторам и модераторам рекомендуется игнорировать юмористический контекст употребления противоправного содержания.  

https://github.com/freedomsex/docs/blob/master/deal/809-Неправомерность-юмора-и-цитат.md

**Comment by mj4444ru** [comment]
я против это х**ни... запрет шутить это просто 3.14здец...

**Comment by tebaly** [comment]
@mj4444ru - а что поделать.. "в отрыве от контекста". 

Конкретно в этом случае перегиб. @11877811 там дал соответствующий комментарий _Не уверен, что это было предложение оплаты, скорее простебал проститутку._ и я с этим согласен.

Для исключения подобных случаев поправил Правила и дописал Соглашение.

**Comment by mj4444ru** [comment]
спс, только я вот ваше дополнение не понял... в такой формулировке его можно воспронимать так как хочется, а не так как задумывали вы...

и опять же, цель борьба с проститутками, мошенниками и т.п., а не теми кто троллит проституток...
(хотя я бы и некоторых других поубирал бы с этого сайта)
так и надо закрепить что блокируем тех, кто имеет реальные признаки мошенничества, либо предложения услуг/денег/вознаграждений, так как по логике @inquisitor6789 сообщение типа "чисик будет стоить миллион рублей" будет блокировано, а это не есть хорошо...

**Comment by tebaly** [comment]
> будет блокировано

:copyright: ибо нех#й

Ценники всё время меняются, курс не стабилен. Того и гляди, что вы разрешите с такой логикой сегодня, завтра нужно будет блокировать. Россией мир не ограничен. Не так давно в Белоруссии миллион - не такая уж большая сумма была..

Вас прошу говорить конкретно.

**Comment by tebaly** [comment]
> Ранее, в предыдущей версии правил/соглашений была фраза приблизительно такого содержания "запрещено предложение оплаты(оскорблять) услуг даже в шутку". 

Нашел))

> <b>Предложение интим услуг</b> на сайте запрещено, как и на уровне закона 
   почти всех развитых и цивилизованных стран мира. Даже в шутку. Если модератор получит 
   жалобу на сообщение с &laquo;расценками&raquo; анкета будет заблокирована без разбирательств.

https://github.com/freedomsex/docs/blob/master/blog/8_follow_law.txt
