### ISSUE TITLE
Возрастные ограничения 16+

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#333]
> **10 Блокировка несовершеннолетних**
10.1. Пользователем сайта может быть лицо достигшее 16 лет.
10.2. Точный возраст в анкете указывать не обязательно. Реальным возрастом Пользователя считается возраст, указанный в анкете.
10.3. Подтверждением реальности возраста может служить сообщение своего возраста собеседнику.
10.4. В случае, если Пользователь сообщает собеседнику о возрасте менее 16 лет, такая информация может рассматриваться как реальный возраст Пользователя, независимо от информации указанной в анкете.
10.5. Администратор может заблокировать анкету, если реальный возраст Пользователя меньше 16 лет.
~10.6. Общение несовершеннолетних Пользователей с совершеннолетними на тему секса на сайте запрещено.~
~10.7. В случае общения на тему секса несовершеннолетнего Пользователя с совершеннолетним, Администратор может заблокировать анкету несовершеннолетнего Пользователя.~
~10.8. Возраст совершеннолетия зависит от страны проживания Пользователя.~

Предложение. 
* Если по тексту жалобы можно **однозначно** утверждать, что Пользователю, отправившему сообщение 15 лет или менее - маркировать жалобу "блокировано" (0-15 лет)
* ~Если также можно утверждать о факте общения несовершеннолетнего с совершеннолетним на тему секса - маркировать жалобу "блокировано"  (16-17 лет)~

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/21518667/27217908-ccf9-11e6-9056-1ec3a3ff7a69.png)

**Comment by inquisitor6789** [comment]
> Если также можно утверждать о факте общения несовершеннолетнего с совершеннолетним на тему секса - маркировать жалобу "блокировано" (16-18 лет)

это вроде всегда блокируется, т.к. налицо нарушение УК РФ.
На счет остального как хочешь. Но позволь мне напомнить, что мы не ограничиваем общение. В том числе и несовершеннолетних. Общаться можно, но не о сексе. Или у нас меняется парадигма?

**Comment by tebaly** [comment]
@inquisitor6789 - всё меняется :smiling_imp:

Всему виной "желания и фантазии". Либо форматировать их в соответствии с маркировкой 16+, либо форматировать доступ к проекту в соответствии с 16+

Мат в желаниях ещё можно фильтровать, но вот "тематические" перегибы вряд ли получится.

**Comment by inquisitor6789** [comment]
> всё меняется 😈

да я не против. Просто хотелось бы определить глубину перемен....

**Comment by tebaly** [comment]
Глубина озвучена)

**Comment by tebaly** [comment]
### Не слышу возражений!)

> Понятия «совращение малолетнего», равно как и статьи «совращение несовершеннолетнего», нет ни в одном российском нормативно-правовом акте. Это, скорее, обывательское обозначение действий сексуального характера, совершенных по отношению к ребенку.

> Действующее законодательство, в том числе и уголовное, называет гражданина малолетним до достижения им 14-летнего возраста, но сексуальная неприкосновенность, в соответствии с УК РФ, сохраняется до 16 лет – именно до этого времени ребенок в силу своих физиологических особенностей не способен в полной мере выполнять половые функции.

То есть, моё утверждение в отношении Пользователей группы 16 и 17 лет излишне.

**Comment by tebaly** [comment]
Понятие "несовершеннолетие" будет убрано из всех Соглашений. Прошу не применять этого термина к пользователям 16 лет и старше.

**Comment by inquisitor6789** [comment]
> Прошу не применять этого термина к пользователям 16 лет и старше.

так вроде и не применяли... Есть прецеденты?

**Comment by tebaly** [comment]
не знаю :)

**Comment by tebaly** [comment]
Обновил правила, справку. Пожалуйста сообщите другим администраторам в случае "конфликтов" об изменениях. Спасибо.

Если обнаружите противоречия в справке/соглашениях/правилах - пожалуйста сообщите, предложите правки или исправьте.

**Comment by mj4444ru** [comment]
давно пора... никогда не понимал комментариев в арбитраже на эту тему типа "в самом сообщении нет нарушения"...
