### ISSUE TITLE
Дедовщина и диссидентство в Сообществе

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#334]
@Premaswarupa @Fenslau @fenixnoir - вы живы? За ваше здоровье тут интересуются)

Узнаю от третьих лиц о насилии и принуждении в отношении вас со стороны старослужащих. Какого ляда мне об этом ничего не известно?
* это вымысел и бред не соответствующий действительности
* вас заперли в подвале, пытают, шантажируют или угрожают

**Comment by inquisitor6789** [comment]
откуда такие вести?
судя по статистике @Premaswarupa давно не заходит (12 дней)
@Fenslau вроде как сидит на сайте, но не модерит ничего
за @fenixnoir ничего не могу сказать...

**Comment by fenixnoir** [comment]
Я жив. Спасибо за интерес. Просто у меня семейные перестановки глобальные, бывшая выселила в гараж с вещами без повода, зато благодаря сайту не на мороз ушел, а к самой лучшей, летом-осенью свадьба.
Пока возможности нет администрировать, да и вообще на сайт заходить. Надеюсь, в течении года все уляжется...

Так что, никакой дедовщины я не наблюдаю (по крайней мере 2 месяца назад все было хорошо).

**Comment by tebaly** [comment]
@inquisitor6789 - если есть связь с остальными, попросите отметиться в этой ветке. У нашего общего знакомого заканчиваются темы для троллинга, идет вабанк :smile:

**Comment by inquisitor6789** [comment]
только через сайт могу. личных контактов нет

**Comment by Fenslau** [comment]
Да вообще кризис...
личностного масштаба.
стою на развилине, налево пойдешь коня потеряешь и т.п.)

**Comment by tebaly** [comment]
Просто мне сказали, что вы все пропали по **принуждению** :cold_sweat:
Посчитал своим долгом проверить)))

Всех с Наступающими праздниками!

**Comment by Fenslau** [comment]
Хм, я думал это такая креативная шутка в заголовке )

**Comment by Premaswarupa** [comment]
Всех с Наступившим!🎄🎆🍾
Познакомьте с благодетелем?!)))))
Давно так не смеялась))))С тем кто "принудил" тоже не прочь познакомиться))))))
Tebaly) реверанс и дробь ресницами))) за заботу и чуткость)

**Comment by tebaly** [comment]
Товарищу отчет видимо годовой сдавать нужно было. Статистику по админам подбивал :laughing:

**Comment by mj4444ru** [comment]
@tebaly с вами не соскучишься, над вами можно смеяться бесконечно (пытаюсь оправдать титул)... Снимите розовые очки...

PS: не там копаете...

**Comment by mj4444ru** [comment]
> Узнаю от третьих лиц о насилии и принуждении в отношении вас со стороны старослужащих. Какого ляда мне об этом ничего не известно?

А можно мне по секрету сообщить откуда эти бредовые сведения? Если вы это из другого топика, так подозреваю вы это сначала перевернули, потом изменили, приукрасили и вынесли в своём видении... Лично я понял о чём там речь. А тут простите, полный бред у вас )))
