### ISSUE TITLE
кого ищу

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#338]
http://freedomsex.me/admin/sethelp/?id=156553&ln=0
сколько ещё раз люди должны спросить, прежде чем вы что то сделаете?

**Comment by tebaly** [comment]
> Жаль, что ты далеко, у нас есть общие интересы, хорошо бы встретится.

вполне адекватно :)

**Comment by mj4444ru** [comment]
> Ещё вопрос, будь так добра. Парень ищет девушку в возрасти и т.д. Как изменить этот возраст?

не думал что этот болбес с саппортом надумает знакомиться

**Comment by tebaly** [comment]
делайте выводы

**Comment by mj4444ru** [comment]
я в своё время тоже не мог найти, вы подсказали... делайте выводы...

**Comment by tebaly** [comment]
значит исправим.
