### ISSUE TITLE
Плагин для хрома (исходник)

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#339]
В продолжение #324, #327
https://chrome.google.com/webstore/detail/fds-helper/opekekncnpkljanbmddpdlhmeiinebpo
https://github.com/mj4444ru/fds-chrome-notification

Добрались руки до плагина. Исправил некоторые недочёты и выложил на гитхаб.
Если кто то хотел бы поставить плагин, но боится по соображениям безопасности, можете взять исходный код с гитхаба, изучить и поставить к себе в браузер напрямую. Такой код автоматически обновляться не будет, переживать не за что.

Для установки:
- Скачайте исходники https://github.com/mj4444ru/fds-chrome-notification/archive/master.zip
- Распакуйте в любую папку.
- Зайдите по адресу browser://extensions/
- Вверху включите режим разработчика.
- Далее нажмите что то типа "Загрузить распакованное расширение" и укажите папку "fds-chrome-notification-master/browser_extension/source".
- Пользуйтесь.

Для обновления:
- Скачайте исходники https://github.com/mj4444ru/fds-chrome-notification/archive/master.zip
- Распакуйте в ту же папку куда распаковывали ранее.
- Зайдите по адресу browser://extensions/
- Под строчкой "FDS Helper description of extension" нажмите "Обновить (CTRL + R)".

**Comment by tebaly** [comment]
Не могу брать в работу плагин в данный момент. Я имею в виду ревью кода, упаковку, публикацию, обновление/поддержку. Просто до потенциальных пользователей нужно донести информацию о том, что это сторонняя разработка, на данный момент неофициальное ПО. Что код не проверялся на безопасность и конфиденциальность использования. Причем второе важнее. Об этом я вскользь упоминал ранее.
* сбор статистических данных использования
* сбор даннных о пользователях плагина - Hardware, GEO, IP и временные метки

Считаю, будет правильным указать в описании к плагину что-то типа:
* Является сторонней(личной, для личного использования) разработкой. На безопасность кода и конфиденциальность использования администрацией сайта не проверяется. 

Давайте согласуем этот текст и вы его добавите к описанию.

**Comment by mj4444ru** [comment]
# fds-chrome-notification

## Описание ##
Плагин создан для упрощения режима модерирования на сайте проекта [http://freedomsex.me/]().

## Об авторах ##
Автор плагина некоим образом не связан с сайтом [http://freedomsex.me/]() и его зеркалами.

## Установка ##
Установка плагина возможна двумя способами
- Установка непосредственно из магазина [https://chrome.google.com/webstore/][webstore]
- Установка из репозитория [https://github.com/mj4444ru/fds-chrome-notification/][github] (подробнее ниже)

## Возможности ##
- Плагин предоставляет альтернативный интерфейс доступа к разделу "Интерфейс модератора", страницам: Новые, Решение, Арбитраж, Вердикт, Помощь.
- Выводит всплывающие уведомления в браузере при появлении новых событий (опционально, отключается в настройках плагина).
- Выводит в правом верхнем углу браузера количество новых событий (опционально, отключается в настройках браузера индивидуально для плагина).

## Планируемые возможности ##
- Уведомление о входящих сообщениях от других пользователей.
- Уведомление о входе на сайт других участников согласно установленного фильтра.

## Хотелось бы, но скорее всего никогда не  будет ##
- Альтернативный интерфейс для общения в основной версии сайта.
- Альтернативный интерфейс для администраторов.

## Гарантии и безопасность ##
- Плагин не содержит вредоносного кода и кода слежения за кем либо.
- Плагин выполняет запросы только к сайту [http://freedomsex.me/]() и сайтам которые предоставлены сайтом [http://freedomsex.me/]().
- Плагин выполняет запросы по ссылкам полученным с сайта [http://freedomsex.me/](), таким образом позволяя сайту [http://freedomsex.me/]() выполнять любые запросы от имени плагина и от вашего имени.
- Для безопасности **политикой безопасности браузера** плагину разрешёны доступ только к данным сайта [http://freedomsex.me/]().
- Плагин содержит ошибки и недоделки некритического содержания.

## Предупреждения от разработчика сайта [http://freedomsex.me/]() ##
Эти предупреждения написаны автором плагина по просьбе разработчика сайта.
- Возможности плагина практически такие же как и у любого сайта в интернете:
  - Возможность слежки.
  - Возможность выполнять анонимные запросы к другим сайтам (без доступа к пользовательским данным).
- Дополнительные возможности плагинов предоставляемые браузером:
  - Возможность выполнять запросы, а так же получать полный доступ к данным пользователя для сайтов из запрошенного списка привилегий. Ознакомиться со списком запрашиваемых плагином привилегий вы можете [тут][permissions].
  - Возможность выводить диалоговые уведомления с 2 кнопками.
  - Возможность получать список открытых окон и открытых вкладок.
  - Возможность хранить данные (в частности настройки) в браузере пользователя.
  - Другие возможности, неиспользуемые плагином.
- Плагин автоматически обновляется и в него в любой момент может быть дописан вредоносный код (**я как автор плагина обещаю что этого не будет**).
- Особое внимание хотелось бы уделить тому что логин и пароль к сайту [http://freedomsex.me/](), электронная почта в настройках [http://freedomsex.me/]() так же уязвимы и доступны плагину (**плагин эти данные не загружает с сайта**).

## Установка из репозитория ##
- Скачайте исходники из [репозитория][sources].
- Распакуйте в любую папку.
- Зайдите по адресу [browser://extensions/]().
- Вверху включите режим разработчика.
- Далее нажмите что то типа "Загрузить распакованное расширение" и укажите папку "fds-chrome-notification-master/browser_extension/source".
- Пользуйтесь.

## Обновление из репозитория ##
- Скачайте исходники из [репозитория][sources].
- Распакуйте в ту же папку куда распаковывали ранее.
- Зайдите по адресу [browser://extensions/]().
- Под строчкой "FDS Helper description of extension" нажмите "Обновить (CTRL + R)".

[webstore]: https://chrome.google.com/webstore/detail/fds-helper/opekekncnpkljanbmddpdlhmeiinebpo
[github]: https://github.com/mj4444ru/fds-chrome-notification/
[sources]: https://github.com/mj4444ru/fds-chrome-notification/archive/master.zip
[permissions]: https://github.com/mj4444ru/fds-chrome-notification/blob/master/browser_extension/source/manifest.json#L25

**Comment by tebaly** [comment]
Меня беспокоит только описание(оно идет в самом верху на странице в сторе) - там где сейчас _description of extension_

> Плагин создан для упрощения режима модерирования на сайте проекта http://freedomsex.me/. Является моей личной разработкой. Плагин ещё не проверялся администрацией сайта на безопасность и конфиденциальность использования.

**Comment by mj4444ru** [comment]
Добавил

**Comment by tebaly** [comment]
Слишком много добавили..

**Comment by mj4444ru** [comment]
коротко - непонятно... там весь текст говорит что я к вам не имею отношения...

**Comment by tebaly** [comment]
Я четко обозначил, что меня возбуждает - "безопасность и конфиденциальность использования". Поэтому обратился к вам с просьбой, упомянуть об этом как можно выше. До всего остального мне ровно.

Пожалуйста, скопируйте этот текст в самое начало описания:
> Плагин создан для упрощения режима модерирования на сайте проекта http://freedomsex.me/. Является моей личной разработкой. Плагин ещё не проверялся администрацией сайта на безопасность и конфиденциальность использования.

К вашему первоначальному описанию это добавляет всего два предложения.

---

За многократную вставку ссылок на сайт и текст не по теме в описании вас могут забанить(вас забанят) в сторе, причем пожизненно. Рекомендую вам ограничиться только этими тремя предложениями и ссылкой на гит в поле "сайт".

**Comment by mj4444ru** [comment]
> Плагин создан для упрощения модерирования на сайте http://freedomsex.me/.
>
> Это неофициальное расширение и администрация вышеупомянутого сайта к его действиям и содержимому отношения не имеет, а так же не отвечает за его безопасность и конфиденциальность использования.
>
> Автор и разработчик плагина к вышеупомянутому сайту и его администрации так же отношения не имеет.
>
> Любой желающий может использовать, модифицировать, распространять (в том числе модифицированный) плагин без каких либо ограничений.

Текущая редакция описания.
Это максимум что я могу предложить. 

Банить там не за что, тем более пожизненно. Ссылки у них разрешены в описании.

**Comment by tebaly** [comment]
например https://habrahabr.ru/post/231009/
Причина блокировки: Поисковый спам
Причина блокировки: keyword stuffing

Это хром стор - тотже гугл плэй только в профиль.

> Автор и разработчик плагина к вышеупомянутому сайту и его администрации так же отношения не имеет.

Слишком категорично для лучшего тролля Сообщества за 2016 год и самого активного борца за права сферических Пользователей в вакууме. Де факто - вы тоже Администрация.

**Comment by mj4444ru** [comment]
Мне далеко до этих гореразработчиков.
А зная как они отстаивают свои права, я думаю на месте гугла поступил бы так же.

> вы тоже Администрация.
Ну это знаете только вы и то по секрету 👤


>Четверг, 12 января 2017, 3:49 +05:00 от FreedomSex <notifications@github.com>:
>
>например  https://habrahabr.ru/post/231009/
>Причина блокировки: Поисковый спам
>Причина блокировки: keyword stuffing
>Это хром стор - тотже гугл плэй только в профиль.
>>Автор и разработчик плагина к вышеупомянутому сайту и его администрации так же отношения не имеет.
>Слишком категорично для лучшего тролля Сообщества за 2016 год и самого активного борца за права сферических Пользователей в вакууме. Де факто - вы тоже Администрация.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Евгений Махаев
