### ISSUE TITLE
меня ломанули или сайт глючит?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#340]
что-то я не могу зайти на сайт. :-(
С утра все работало замечательно, а вот сейчас проблемс.
мой ид 5040613
восстановление пароля на емайл тоже не работает
![image](https://cloud.githubusercontent.com/assets/19651618/21805450/4cab670a-d745-11e6-9854-bd8d4205c3ae.png)

**Comment by mj4444ru** [comment]
Справедливости ради можно заметить что вы не первый жалуетесь на невозможность восстановления пароля.

**Comment by inquisitor6789** [comment]
так раньше то все работало. даже если и были проблемы с сервисом рассылки, то там ошибка вроде другая была
а сейчас я даже залогиниться не могу, хотя точно уверен в корректности логин/пароль/капча

**Comment by mj4444ru** [comment]
напишите на почту, может быстрее помогут

**Comment by tebaly** [comment]
исправил. проблема была не в восстановлении, а чуть выше... само восстановление работало как положено, поэтому факт проверки работы восстановления был положителен. 

проблема должна была иметь место только для очень "давних" анкет, как минимум старше года. во всех похожих случаях возможно восстановление индивидуально. сами данные анкет на месте - затерли данные авторизации для некоторого количества анкет. за масштаб сказать пока не могу. ошибка в скрипте сборки "мусора", в данном случае - по заброшенным анкетам.

пожалуйста, накидайте сюда ID тех кто обращался с аналогичной проблемой, нужно проверить.

**Comment by tebaly** [comment]
сложности в том, что Пользователи часто жалуются на "вход" или траблы с емаил, так как ошибаются при вводе пароля или неправильно указывают емайл. далее забывают подтвердить емайл. сообщений о таких "ошибках" - более 90% - проверять все нет никакой возможности.

**Comment by mj4444ru** [comment]
а вот значит почему я не мог зайти в свою старую анкету...

думаю ситуация актуальна только для админов... у остальных вы всё трёте... так что можно давать совет завести новую анкету и пользоваться ей...

**Comment by mj4444ru** [comment]
PS: Хьюстон, у нас проблема..

**Comment by tebaly** [comment]
если анкета **заброшена** - вы лично или кто-то из админов ратовали за удаление анкет.

**Comment by mj4444ru** [comment]
@tebaly вы уточняйте кому отвечаете
я лично говорил что друзей можно через сколько то времени удалять (с побочным эффектов ввиду разыгноривания) и за удаление фоток через пол года...

**Comment by inquisitor6789** [comment]
4511540
Судя по всему у этого пользователя аналогичная проблема
http://freedomsex.me/admin/sethelp/?id=157446&ln=0

**Comment by tebaly** [comment]
Судя по всему косяк серьезный был.. Суть в том, что "потерлись" записи логин/пароль для давно зарегистрированных пользователей. Сейчас нумерация идет с 26 миллионов, а его ID 4.511.540 - так можно легко определять "проблемных пользователей" в будущем. Да, у него такая же проблема, но к тому же в базе нет его емайл для восстановления..
* я реализовал костыль на этот случай - доступ можно восстановить, если есть емаил
* если его нет, или он не подтвержден - только новая анкета

Сожалею.

Пожалуйста, предлагайте Пользователям попробовать восстановить пароль по емаил. Если окажется, что он не был указан или подтвержден - предложите завести новую анкету. 

![image](https://cloud.githubusercontent.com/assets/9466814/22369582/cffcf5be-e49d-11e6-9f3f-523b37063c0b.png)
