### ISSUE TITLE
Понятие вирта (предложение)

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#341]
Вирт давно является проблемной стороной для модераторов и администраторов.

Предлагаю определиться с тем что такое вирт и подробнее описать в каких случаях он помещается в раздел вирт.

Для начала некоторая информация.

### Цели сайта
Сайт изначально создавался с целью поиска партнёров, то есть с конечной целью свести людей в реале.

### Википедия
Виртуа́льный секс (также вирт) — процесс, во время которого два или более человека соединяются вместе в виртуальном пространстве ... с целью сексуального удовлетворения друг друга ...

### Что есть Вирт
Удовлетворение может быть разное, каждый удовлетворяется по своему, но однозначно можно разделить удовлетворение с встречей партнёров или без. В связи с этим предлагаю в первую очередь убрать понятие виртуальный секс.

### Вирт (определение)
Вирт - Любые сообщения, однозначно не направленные на процесс договора о встрече в реале, а так же некоторые специфичные фразы, которые пользователями ассоциируются с виртом, хотя могут использоваться в любом контексте.

С одной стороны данное определение вносит кучу неопределённости и неясности и позволяет многие вещи трактовать исходя из опыта каждого конкретного модератора, но с другой стороны сейчас всё на самом деле ещё более размыто, либо противоречиво.

### Предложение Вирта
Так уж получилось, что в большинстве сообщений начала вирта присутствует слово "привет", но на самом деле оно никак не идентифицирует предложение вирта. Предложение вирта, это призыв к виртуальному общению, иногда не в прямой форме. К предложению вирта можно отнести вопросы не касающиеся встреч в реале, если понятно что это начало беседы.

### Пошалим, пообщаемся, помоги кончить и т.д.
Фразы которые нельзя однозначно отнести к вирту, но при отсутствии признаков реального знакомства, должны восприниматься как вирт.

### Интим фото и интим переписка
Интим фото и интим общение, призывы к их обмену необходимо относить к вирту, так как они не являются необходимым элементом для встречи людей.

**Comment by mj4444ru** [comment]
За ошибки модераторов при распределении вирт/не вирт наказывает только система.
При массовом переносе (менее 30 уникальных жалоб) необходимо побеседовать с нарушителем.
Если нарушитель не реагирует на призывы прекратить перенос, либо перенесено разом более 30 уникальных жалоб без комментариев, нарушить может быть лишён рейтинга.

Понижение рейтинга используется только в случае безусловного, либо однозначно хулиганского переноса. Если сообщения являются неоднозначными, допустимо только предупреждение.

**Comment by inquisitor6789** [comment]
> Вирт - Любые сообщения, однозначно не направленные на процесс договора о встрече в реале,

тогда получается, что и "Привет! Давай знакомится" будет отнесено к вирту, т.к. тут нет ни слова о встрече в реале. А на сайте априори все происходит в виртуальном пространстве. И отсюда опять же будет вытекать множество проблем.
Однако, если не убирать понятие виртуального секса, то предложенное описание вполне подходит...

**Comment by mj4444ru** [comment]
знакомиться - неотъемлемая часть перед встречей в отличии от "давай поболтаем"...

**Comment by inquisitor6789** [comment]
"давай поболтаем" может быть тоже частью начала знакомства
как сейчас мОлодежь пишет - одно сообщение должно уместиться в одну строку на экране мобилки. Таким образом можно предположить следующую ситуацию (все сообщения от одного пользователя)
- Привет!
- Давай поболтаем
- А потом встретимся

Я конечно понимаю, что эта ситуация синтетическая, но тем не менее нельзя совсем исключать ее вероятность.

**Comment by mj4444ru** [comment]
пошалим
у меня хата сегодня свободна 

аналогичная ситуация... тема двусмысленности уже поднималась...

**Comment by tebaly** [comment]
@mj4444ru - https://github.com/freedomsex/docs/blob/master/deal/803-Виртуальный-секс-не-запрещен.md

Вы читали? Если нет, прочитайте и внесите правки в ваше предложение. Если читали - отредактируйте ваше предложение в том формате, когда вы указываете на:
* явный конфликт с тем что там написано, двусмысленность
* то чего там нет, но считаете нужным вписать

Там есть и определение вирту и многие особенности.

**Comment by mj4444ru** [comment]
Читал я... Вот эти определения и предлагаю поменять, в частности убрать понятие виртуального секса.
Тут соответственно вынес на обсуждение.
Изменение в какой то мере можно назвать глобальным, то есть равноценно полному переписыванию этого раздела.
На практике же оно мало чего поменяет, но даст более чёткую границу что такое вирт.

Исходя из этого можно поступить двумя способами
- Поменять этот раздел полностью, убрав при этом само понятие виртуального секса.
- Поменять раздел частично, оставив только нюансы касательно виртуального секса, а описание самого вирта и порядка действий вынести в новый раздел.

**Comment by tebaly** [comment]
>  с встречей партнёров или без.

без встречи - вирт. какие в этом проблемы то?

> сейчас всё на самом деле ещё более размыто, либо противоречиво.

Вот это я от вас и хочу:
* явный конфликт с тем что там написано, двусмысленность
* то чего там нет, но считаете нужным вписать

---

Прямо _цитату_ оттуда выхватывайте и напишите, в чём видите там конфликт.

**Comment by mj4444ru** [comment]
1) Заголовок - "Виртуальный секс не запрещен" - подразумевает что вирт это вирт секс.
2) Технически была необходимость в кратком именовании маркеров. Именование маркера как "Предложение к занятию виртуальным сексом" технически было неприемлемо.
3) Ссылка на статью википедии "Виртуальный секс"

Других описаний что такое вирт, я не нашёл.
Так что надо уже как минимум заголовок менять.

Если вы согласны что вирт это не только Вирт секс, я при появлении свободного времени постараюсь отредактировать эту статью в соответствии со своими мыслями. Просто не охото тратить 2-3 часа времени на то что бы делать то что никому не надо... Хотя я смотрю вам это и так не надо...

**Comment by tebaly** [comment]
@mj4444ru - все Соглашение касается того, что такое Виртуальный секс, и как с этим бороться. А я вас попросил:
* явный конфликт с тем что там написано, двусмысленность
* то чего там нет, но считаете нужным вписать

Я не вижу никаких противоречий.

**Comment by mj4444ru** [comment]
> Оценивайте всю имеющуюся информацию, и решайте, стоит ли блокировать за вирт.

> Администратором может быть принято решение о наказании Нарушителя и/или блокировании его анкеты, ограничивая или прекращая возможность его дальнейшего общения на сайте.

вроде за вирт не блокируют, я бы убрал это предложение.
а то в соответствии с "приводящих к блокированию анкеты ... может равняться 10" можно пол сайта переблокировать...

**противоречия**
- "Поболтать не желаешь на неприличные темы?)" - фраза отмечена для отметки как вирт, но каким боком она относиться к теме соглашения? напомню тема "Виртуальный-секс-не-запрещен".
- "привет!) обменяешь свои фото/видео на фото/видео моих подруг?)" - вам не кажеться что распростронять чужие фотки/видео это нарушение?

Для того кто хочет реального секса, нет разницы между фразами
- Поболтать не желаешь на неприличные темы?)
- Поболтать не желаешь?)

> "Привет, не против приятного общения?" - помещено в раздел "Разрешено", т.к. под "приятным общением" понимается простое, не напрягающее общение. Но и перемещение в раздел "Вирт" допускается. Однако, в этом случае будьте готовы отстаивать свою точку зрения.

Да прям в соглашении написано "люди, создавайте конфликты"...

- "Привет! Интересный собеседник с фантазией. Пообщаемся?" - предлагается просто общение. Даже не смотря на то, что упоминается "фантазия".

Прямое предложение вирта. Вот похожие примеры решений других администраторов
`Приветик ) любишь фантазии с сюжетом ?)` @5040613 - вирт
`Давай постоянно общаться по телефону?` @22863802 - вирт
`привет сладенькая давай пообщаемся` @17621938 - вирт

И даже так
`Фотками обменяться не хочешь????` @24027668 - вирт

я просто хочу немного формализовать эту грань, что бы людям было понятнее даже без конфликтов модераторов.
`Пришли еще себя милая` @5499473 - вирт
`Привет, обменяемся фото?` @15952121 - вирт
`Привет)..покажешь себя пышечка?)` @5040613 - вирт
`Просто общение?) или встречи фото?` @15551555 - вирт
`Ещё фото хочешь?` @15551555 - вирт

**Comment by tebaly** [comment]
> Да прям в соглашении написано "люди, создавайте конфликты"...

там написано - в целом пофигу как вы в этом случае сделаете - главное, чтобы вы друг друга не поубивали из-за этого :sweat_smile: 

Я до сих пор не вижу противоречий с Соглашением. Плохо стараетесь.

> привет сладенькая давай пообщаемся

а вот здесь про вирт ни слова... но это банальная ошибка. про фантазии, телефон и тем более фотографии написано в Соглашении. 

Ещё одна попытка сеньор

**Comment by NeverovI** [comment]
> Вирт стоит толковать из подхода - реальное знакомство и общение против виртуального. Если глубже - вирт у нас не равно **виртуальный секс**, а равно **виртуальное общение**.

Исходя из вышесказанного @tebaly просто отказаться от формулировки "**виртуальный секс**" и везде прописать "**виртуальное общение**", в последствии отказавшись от сокращения "вирт" и перейдя к сокращению "общение", так как данное сокращение будет точнее передавать суть знакомства. Ведь на сколько понимаю цель была разделить виртуалов от реалов, а уж чем там занимаются виртуалы, это их личное дело. Сейчас же эта кнопка "вирт" какая-то призрачная охота на ведьм.

**Comment by tebaly** [comment]
По указанной ссылке это всё описано. Перечитайте, там нет противоречия с приведенной вами цитатой. Любое общение в сети есть виртуальное(!) Так что не вносите смуты. 

ВИРТУАЛЬНОЕ ОБЩЕНИЕ.
Разновидность коммуникации, которая носит опосредствованный компьютером характер, осуществляется с помощью телекоммуникационных систем. Имеет ряд особенностей в сравнении с непосредственным, т. е. «живым» общением. К ним можно отнести следующие:
1) расширение границ и возможностей общения, так как партнеров по общению можно найти практически во всех странах мира;
2) оба партнера в процессе общения находятся в своем привычном жизненном пространстве, пользуются удобными различными источниками информации;
3) общение осуществляется преимущественно в письменной форме (e-mail, чат), что позволяет совершенствовать навыки и умения письменной речи;
4) помимо совершенствования языковых знаний участники общения могут получить информацию о личности партнера, его взглядах на окружающий мир, о стране изучаемого языка и т. д.;
5) общение осуществляется в форме электронных писем и устных сообщений;
6) в ходе обмена сообщениями совершенствуется умение понимать письменный текст, сопровождаемый при необходимости пояснениями носителя изучаемого языка. Виртуальное общение в Интернете путем регулярного обмена электронными письмами позволяет значительно усовершенствовать навыки и умения письменной речи, способствует обогащению словарного запаса, расширяет кругозор и социокультурную компетенцию, совершенствует навыки работы с компьютером и Интернетом. См. также компьютерные учебные программы, тандем-метод.

**Comment by tebaly** [comment]
> Вирт у нас не равно виртуальный секс, а равно виртуальное общение.

Вероятно не корректно сформировано. "а равно" стоит заменить на "больше похоже на". Это утверждение касается только "непонятных" ситуаций. Вы выдавили с меня это в случае касающемся "обмена интим фото", вспоминайте. Но ситуация с обменом фото уже была описана в соглашении задолго, и этот комментарий явно лишний.
