### ISSUE TITLE
привет. я парень

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#342]
Сообщение "привет. я парень, секса хочется, давай отсосу тебе"
http://freedomsex.me/history/message/284168/

Помню была тема, но не нашёл.
Некоторые люди пишут "Я дима, мне 25 лет, ухоженный, спортивный, ищу девушку для секса". Всё написанное есть либо может быть в анкете, но люди всё равно это пишут для количества. 
Ввиду этого не вижу причин подобные сообщения помещать в "наказать"...

**Comment by mj4444ru** [comment]
А это почему тогда не наказали?

Сообщение "Хочешь вирт со мной-я парень 17"
http://freedomsex.me/history/message/275540/
![derzkij-kote_45595497_orig_](https://cloud.githubusercontent.com/assets/9354685/21820134/57841956-d790-11e6-8f30-ddcae01d1236.jpg)

**Comment by tebaly** [comment]
читайте вниматочно, это раз.
комментарии запрашиваете у меня зачем вы? для этого личные сообщения есть у джедая.

**Comment by mj4444ru** [comment]
забейте уже ))) картинка была намёком...

**Comment by tebaly** [comment]
не вижу причин -> читайте вниматочно
почему тогда не наказали -> комментарии запрашиваете у меня зачем вы?
