### ISSUE TITLE
Опрос: допустимо ли распространять чужие фотки?

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#343]
привет, хочешь фото, которые мне скинули?)
http://freedomsex.me/history/message/274065/

Как вы думаете, допустимо ли распространять чужие фотки?
(не те которые интим с интернета публичные)

**Comment by tebaly** [comment]
нет.

**Comment by mj4444ru** [comment]
спс, будем блокировать...

**Comment by mj4444ru** [comment]
@tebaly а как на счёт сообщений типа "Обменяю своё фото на фото твоих бывшех" ? тоже были такие. Я считаю это незаконно и делают это только парни под видом девушки.

**Comment by tebaly** [comment]
только не маркируйте их как "блокировано", без крайней необходимости.

**Comment by mj4444ru** [comment]
хорошо. но "привет, хочешь фото, которые мне скинули?)" считаю крайней необходимостью с целью защиты пользователей сайта.

**Comment by tebaly** [comment]
> с целью защиты пользователей сайта

нет нигде такой формулировки

> **Коля:** Могу ли я заблокировать пользователя по собственным соображениям, которые вы не упомянули в правилах?
O: В правилах мы постарались перечислить все возможные случаи требующие блокирования анкет. По личным мотивам или на основе собственных религиозных взглядов блокировать анкеты категорически запрещено. Теоретически, возникновение не описанной в правилах ситуации вполне возможно, как и вероятно возможно будет и блокирование анкеты.

**Comment by mj4444ru** [comment]
То есть нарушение правил сайта (пункт 4.10) не является крайней необходимостью? Можно тогда я буду все правила нарушать, а меня за это не будут блокировать?

**Comment by tebaly** [comment]
только не маркируйте их как "блокировано", без крайней необходимости.

**Comment by tebaly** [comment]
маркер "блокировано" и блокировка анкеты связаны **НЕ** линейно!
