### ISSUE TITLE
баг в разделе решения в интерфейсе модератора: \r\n вместо переноса строк

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#344]
<div id="" class="" style="color: #777; font-size: 14px; margin-bottom: 5px;
              border: 1px solid #CCC; background: #f5f5f5; padding: 10px 15px;">
                4. Сайт запрещается использовать для\r\n4.10. сбора и хранения персональных данных третьих лиц;
             </div>

**Comment by tebaly** [comment]
формально, это перенос :smile:

**Comment by tebaly** [comment]
там сама реализация этих "комментариев" ещё не завершена. 
можно вырезать все табы и переносы чтобы в одну строку, но пока закрою...

**Comment by mj4444ru** [comment]
не надо резать )))
