### ISSUE TITLE
Хьюстон, у Вас опять проблема..

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#345]
Сегодня постоянно вылазят "Хьюстон, у нас проблема.."
Вы это что то обновляете или это просто проблема?

**Comment by tebaly** [comment]
должно было быть в 19:30 и час назад - это же не постоянно.

**Comment by mj4444ru** [comment]
сегодня вечером постоянно... то норм, то хьюстон... много раз... если будут ещё, напишу...
