### ISSUE TITLE
Функция "Модератор"

### ISSUE THREAD

**Issue by warkann** [freedomsex/freedomsex#346]
После двух дней модерирования упали все достижения, и даже базовый пункт "Помощь" стал "исследовано на -500%" при "Действий: 752".

**Comment by tebaly** [comment]
мало деталей. ID ваш укажите хотя бы :relaxed:

**Comment by warkann** [comment]
@tebaly всё для вас)) ID 19679734

**Comment by mj4444ru** [comment]
Кто мальчика обидел? Вроде не хулиганил, а поставили в угол )))

![default](https://cloud.githubusercontent.com/assets/9354685/21899151/0f5bacca-d911-11e6-9b4e-5f52d789f817.png)

**Comment by tebaly** [comment]
надо время разобраться

**Comment by tebaly** [comment]
баг на голосовании. автоматикой списывался рейтинг почти рандомно. спасибо за информацию
исправил. раскачу, понаблюдаем

**Comment by tebaly** [comment]
поправил вам достижения. всем кто потенциально "пострадал" от бага восстановил до некоторого значения. извините, в нашем коде ошибок есть :blush:

**Comment by warkann** [comment]
@tebaly за cегодня рейтинг опять припал, с "Специалист высшего уровня" до "Специалист 1 класса", прогресс исследований так же упал с 41% до 40%.

**Comment by tebaly** [comment]
колебание в пределах 10-20% это норма :)

До этого было -500% - вот это уже аномалия...
