### ISSUE TITLE
Ошибки в разделе модерации городов.

### ISSUE THREAD

**Issue by warkann** [freedomsex/freedomsex#347]
@tebaly 
![issue 1](https://cloud.githubusercontent.com/assets/6175902/21930832/26ba3434-d9a9-11e6-9713-16e89accfd02.jpeg)
При попытке удалить эти три элемента открывается пустое окно 'about:blank'

![issue 2](https://cloud.githubusercontent.com/assets/6175902/21930905/91f57416-d9a9-11e6-9a4b-37ac1f18505a.jpeg)
Удаляя невалидные элементы, они просто уезжают в начало списка не удалясь.

**Comment by tebaly** [comment]
@warkann - начало списка для вас где?)) Я пришел "починить" проблему - но не вижу её :grin:

Удаления как такового в этом списке нет - названия улетают в конец списка, удаляясь при этом в таблице городов пользователей. А в этой идет инкремент счетчика удалений, с тем, чтобы решить - что заблокировать совсем, а что редактировать.
