### ISSUE TITLE
Спор о блокировке

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#348]
У меня возник спор с другим админом по поводу блокировки следующих анкет
http://freedomsex.me/userinfo/profile/19602946/
http://freedomsex.me/userinfo/profile/25018989/
http://freedomsex.me/userinfo/profile/22168312/
http://freedomsex.me/userinfo/profile/24275674/
http://freedomsex.me/userinfo/profile/25100177/
http://freedomsex.me/userinfo/profile/25118806/
http://freedomsex.me/userinfo/profile/22484058/
В связи с этим прошу сообщество высказаться по этому вопросу. За какое решение будет большинство так и поступлю

**Comment by tebaly** [comment]
Во-первых, @mj4444ru удостоен сразу нескольких премий в 2016 году

# 1. Тролль сообщества - 1-е место
# 2. Лучший борец за права сферических Пользователей в вакууме 

Зря вы не следите за номинированием в этих категориях :stuck_out_tongue:

**Comment by mj4444ru** [comment]
а я тут причём? )))))))

**Comment by tebaly** [comment]
ссорян, у вас накой ID - я запутался уже :satisfied:

**Comment by mj4444ru** [comment]
Надо сделать вторую копию сайта, точнее окружение, и всех блокированных туда переносить. Пусть друг с другом там развлекаются ))) Здорово я придумал?
Хочу премию Тролль года 2017 :laughing:

**Comment by tebaly** [comment]
@22290748 - это же ваш ID ? если да, то не вносите смуту

**Comment by mj4444ru** [comment]
А вдруг Сергей не знает? остальные то давно догадались.


>Понедельник, 16 января 2017, 0:07 +05:00 от FreedomSex <notifications@github.com>:
>
>@ 2229074 - это же ваш ID ? если да, то не вносите смуту
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Евгений Махаев

**Comment by mj4444ru** [comment]
Блин, спалился...

**Comment by tebaly** [comment]
>  Как вариант сложного случая в ошибках при сложных решениях - эксплуатация коллизий и неточностей в правилах, двусмысленности правил, пограничности принимаемого решения для провоцирования конфликтных ситуаций, накрутки рейтинга, системного флуда, троллинга Администраторов. Здесь же - разницы в индивидуальных качествах администраторов, таких как чувство меры, нормы, морали, нравственности, юмора и так далее. Равно как и создание таких ситуаций - вправе расцениваться как саботаж.

https://github.com/freedomsex/docs/blob/master/deal/820-Саботаж-и-преднамеренные-ошибки.md 

На самом деле - не смешно. Я бы блокировал подобную деятельность уже давно, но я, как разработчик, преследую иные цели. Как поступать в конфликтных ситуациях я уже давным давно описал и озвучивал много раз.

**Comment by mj4444ru** [comment]
Тут нет преднамеренных ошибок. Другие админы со мной солидарны (кроме анкет с морковками).
На тему морковок я провожу эксперимент. Вполне разумный и пока я бы сказал даже успешный.
И вам советую присмотреться, так как это куда эффективнее ваших особых.

**Comment by tebaly** [comment]
Далее - https://github.com/freedomsex/docs/blob/master/blog/8_admin_princip.txt

Где-то я давал ссылку на эту справку. Если крайне нужно, вставлю туда, куда попросите :relaxed:

> В любой похожей ситуации стоит выбрать меньшее из зол. Например, если
  можно и наказать, и не наказывать - не наказывайте, разрешите. 
  Если можно и блокировать и не блокировать - не блокируйте, накажите. 
  Иначе возникновение конфликтов администрирования неизбежно, 
  решать которые просто некому.

> Администраторы не обязаны выяснять, как именно вы понимаете правила администрирования, в чем и как ошибаетесь. Администратор вправе снизить или обнулить рейтинг за допускаемые ошибки,  и даже в отсутствии споров, по своему усмотрению.

**Comment by tebaly** [comment]
### 13.1. Незаконным может быть принято содержание по факту _являющееся законным_, если оно имеет те или иные признаки незаконности.

То есть - даже намеков хватит. Добавьте кавычки по вкусу, например - "незаконное".

**Comment by tebaly** [comment]
Рассылка интим фото, предложений вирта и подобного б#ядства - разработчиками не приветствуется, но напрямую и не запрещается.

https://github.com/freedomsex/docs/blob/master/rules.md

> 7.5. Рассылать интимные фотографии всем подряд, **запрещено**.

> 9.7 Допускается использование эротических фото **из интернета без лица** в ограниченном количестве. При строгом отношении к Пользователю допускается блокировка при наличии 3-х жалоб. 


Обычные фото 

> 9.1. Использование ненастоящих фото или чужих фотографий крайне не желательно. Собеседник может подать жалобу обнаружив обман.

> 9.2. При обнаружении жалоб на ненастоящие фотографии Администратор может принять решение о **блокировании анкеты**.

**Comment by tebaly** [comment]
И не нужно голосовать. Читайте правила и Соглашения - находите противоречия и предлагайте правки в правила и Соглашения. Вы можете взять и написать новые Соглашения самостоятельно, всегда, когда посчитаете нужным.

**Comment by mj4444ru** [comment]
@inquisitor6789 что вы имели ввиду? я тут вижу текст в поддержку моего предложения о взаимном праве на вето. 

> Если можно и блокировать и не блокировать - не блокируйте, накажите.

**Comment by inquisitor6789** [comment]
это все что вы увидели? я же вижу намного больше пунктов, указывающих на правоту принимаемых мной решений

**Comment by mj4444ru** [comment]
объясните свое видение.

**Comment by tebaly** [comment]
https://gitter.im/freedomsex/freedomsex

Для общения можно пользовать этот чат 

Отдельно чат по вопросам правил/документации - **docs**
