### ISSUE TITLE
идея на тему жалоб "я удаляю, а он всё пишет и пишет"

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#349]
я тут представил себе сценарий:
- парень заходит, пробегается по списку онлайн анкет и пишет свою коронную фразу всем кому ранее не писал
- заходит через час и делает тоже самое

проблема заключается в том как он определяет писал он раньше или нет.
естественно если он видит пустую историю, ему не приходит в голову что на него всего лишь пожаловались и он пишет снова.

то есть причина проблемы в самом сайте.
как пользователь, могу подтвердить наличие проблемы, я даже переименовывал в своё время пользователей, добавляя плюсик что бы знать кому писал, а кому нет.

**Comment by tebaly** [comment]
в форме отправки сообщения как минимум (работает и при чистой переписке)

> Начало общения 20.01.2017

**Comment by mj4444ru** [comment]
ну вы это им объясните.

**Comment by tebaly** [comment]
зачем?
