### ISSUE TITLE
Фото и блокировка

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#351]
Ни где и никогда не встречал что бы блокировали анкету за чужое фото, если оно не нарушает законы.

Обращаюсь к разработчикам (@tebaly). Давайте двигаться в направлении отказа от подобной практике как здесь и сейчас.

Если человек размещает чужое фото, вполне достаточно повесть ему медаль в анкете (замечание) что данный пользователь рассылает чужие фото, а далее на выбор пользователя общаться с ним или нет. Возможно кому то интересно текстовое общение и ему без разницы какие фотки и кому он отправляет. Интим/не интим значения в данном случае не имеет.

Далее можно сделать настройку, хочет ли пользователь получать фото от тех кто не в списке.
Сейчас при написании пользователю, он автоматически попадает в список друзей (справа).
Таким образом пользователь сам решит хочет ли он получать или нет. Опция достаточно простая, похожа на то что сейчас с виртом сделано.

Ещё одно предложение. Сделать рядом с фото кнопку (я не хочу общаться с этим человеком). Кнопка добавляет в чёрный список. Думаю пользователи оценят.

За "детскую порнографию" блокировка анкеты безоговорочно.
Содержание на фотографии (в виде текста или в любом другом виде) приравнивается к текстовому содержимому и наказывается по общим правилам применимым к текстовым сообщениям.

Другие участники могут предложить поправки к данному предложению.

**Comment by tebaly** [comment]
Нет. У нас чужие фото нельзя.
