### ISSUE TITLE
Чёрный список

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#352]
Разработка интуитивно понятного интерфейса и юзабилити это одна из важнейших частей создания сайта, крупные компании на это тратят миллионы.
Я сам работал в компании где 500 000 отдали за разработку интерфейса (не путать с дизайном).

вот примеры где очень не хватает наглядного способа поместить человека в ЧС.

![2017-01-16 11 19 44](https://cloud.githubusercontent.com/assets/9354685/21972885/85783c50-dbde-11e6-9564-7d7616ad892b.png)
Справа можно сделать красную кнопку "В ЧС".
Важно: Что бы исключить случайного попадания в ЧС, после нажатия вместо оскрывания сообщения, оно заменяется на окно с сообщением типа "Вы поместили человека в чёрный список" и кнопка "Я передумал, убрать из ЧС".

![2017-01-16 11 22 51](https://cloud.githubusercontent.com/assets/9354685/21972892/8c9c292e-dbde-11e6-9545-fd74539cc582.png)
Тут под надписью блокнот её разместить.
Важно: Что бы исключить случайного попадания в ЧС, после нажатия в этом же месте вылазит сообщение типа "Вы поместили человека в чёрный список" и кнопка "Я передумал, убрать из ЧС".

**Comment by tebaly** [comment]
Спасибо, подумаем

**Comment by mj4444ru** [comment]
Кстати на сайтах знакомств девушки настолько сильно любят черные списки, что помещают туда даже тех кто им никогда не писал.

**Comment by tebaly** [comment]
у меня есть другая идея, заимствованная из тиндера. но я вам о ней не расскажу :stuck_out_tongue:

черных списков не будет. спасибо.
