### ISSUE TITLE
Не отображается список контактов и сообщения

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#353]
http://freedomsex.me/admin/sethelp/?id=157277&ln=0
http://freedomsex.me/admin/sethelp/?id=157250&ln=157277

**Comment by tebaly** [comment]
у вас тоже?

**Comment by tebaly** [comment]
Если можно, интересуйтесь пожалуйста про то, через что открывают - это очень важно.
* Каким браузером пользуетесь? 
* Каким устройством, телефон/компьютер/кофеварка? 
* ОС какая(Win/Android/iOS/*nix)?

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/22220856/7be60198-e1c1-11e6-98fe-9d7f352ee2cd.png)

**Comment by tebaly** [comment]
http://freedomsex.me/admin/sethelp/?id=157294&ln=157283

**Comment by tebaly** [comment]
Спрашивать их бесполезно.. не видят..

**Comment by tebaly** [comment]
Сайт может не работать на старых IE и мобильных браузерах до андроидной эры. Сайт тестируется на корректность в _Google Chrome_ последних версий. Для Опера мини основные функции тестируются. Изредка но просматривается в старших версиях IE. 

Баг локализовать не получилось. Сайт корректно работает
* _Google Chrome_ последних версий
* Опера мини устройство/эмулятор
* Мобильный браузер Андроид

Пожалуйста, сообщите если у вас получится воспроизвести сию особенность.

**Comment by tebaly** [comment]
Сайт официально не работает в IE8 и более старых динозаврах
* доля IE8 по сайту - **0,0**57 %
* доля IE9 по сайту - **0,0**37 %
