### ISSUE TITLE
Прыгающий дизайн

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#358]
Сильно раздражает прыгающий из за рунеток дизайн (((

**Comment by tebaly** [comment]
Куда он прыгает?) 

PS: вы таки не ушли? :grinning:

**Comment by mj4444ru** [comment]
как пользователь я иногда захожу... и вот это прыганье оооочень достало...

попробую описать:
1) появляется страница поиска или с беседой, в начале на ней нет банера рунеток...
2) потом появляется белая полосочка высотой пикселов 10...
3) потом появляется пустой белый блок для банера рунеток со скролом...
4) появляется надпись "Видеочат с девчонками из твоего родного города"
5) потом появляются квадратики с рунетками...
6) потом опять всё пропадает (включая скрол), остаётся полоска высотой около 10 пикселов...
7) потом обратно становится полная высота, а внутри уже кроме квадратиков с рунетками и текстом "Видеочат с девчонками..." появляется всё тот же скрол и двухцветная надпись "РУНЕТКИ"...
8) скрол исчезает...

и всё это на протяжении 2-3 секунд...

**Comment by tebaly** [comment]
Блок во фрейме с жестко заданными пропорциями. Прыгать может внутри блока, но никак не страница.

![image](https://cloud.githubusercontent.com/assets/9466814/23126579/5f3f24ca-f788-11e6-8133-1b4fedf97b04.png)

**Comment by mj4444ru** [comment]
вроде норм

**Comment by mj4444ru** [comment]
Оно опять прыгает... Опять добавляю в фильтр Adguard...
