### ISSUE TITLE
Аватары исчезают в полдень

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#359]
В целом аватарки в анкетах/контактах была дурацкая идея. Это мегакостыль к системе "временных", сомоудаляющихся фотографий. То есть, какбы, как хранить аватарку в контакте
* если аватаров нет по определению - нет публичных/статических загружаемых фото
* присланное фото должно быть удалено через...

Как итог - либо фотки не удалялись, либо аватары самоликвидировались. Настало время реформ
* аватаров в анкетах больше не будет, появится новый блок/элемент в анкете
* аватаров в контактах не будет
    * до тех пор, пока не слелаем новый, супермегакостыль к этой системе обмена фоток

**Comment by tebaly** [comment]
Важное уточнение - мелкие фото будут доступны по приватной ссылке. Пока вы не получите эту ссылку, вы фотку не увидите. Технически - фотки по прежнему недоступны. Эти мелкие доступны не авторизованным с любого IP - но, по приватной ссылке, которую еще нужно получить...

**Comment by mj4444ru** [comment]
Хуйня какая то...

**Comment by tebaly** [comment]
:stuck_out_tongue_winking_eye:

**Comment by tebaly** [comment]
Сайт обновлен. Аватары в контактах пока остались, в анкетах замена.

**Comment by tebaly** [comment]
Размытые микро фотки публичны. Издержки разработки, по другому нельзя.. Приватные фото доступны с любого IP в ограниченном промежутке времени по `ключу`. Ключи персональные, публиковать запрещено(так было и раньше).
