### ISSUE TITLE
Новый интерфейс и баг загрузки фото

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#362]
Новый интерфейс в чём то хорош, в чём то наоборот... 50 на 50...
При загрузке фото, ничего не происходит после загрузки фото... Сами фото появляются только после нажатия F5... Хром...

**Comment by mj4444ru** [comment]
как теперь понять прочитано сообщение или нет? и ещё крестики не в тему иногда, которые не при наведении или клике появляются, а просто всегда есть...
вобщем муть ваш новый интерфейс... больше похож на сильно черновой вариант...

**Comment by tebaly** [comment]
странное поведение.. попробуйте ещё раз, но в этот раз просто ждите.
PS: dtcm cfqn d nfrjv cjcnjzybb e;t ytcrjkmrj ktn

**Comment by tebaly** [comment]
Проверьте, исправилось

**Comment by tebaly** [comment]
Сейчас точно исправилось))
