### ISSUE TITLE
VIP статус

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#365]
Давным давно было сказано "Никаких Vip статусов!"

Ну это было очень давно :stuck_out_tongue: [шутка] всё остается как и прежде. У всех анкет появится некоего рода "статус доверия". Сейчас он определяется "кредитами доверия". Теперь за бабки можно будет купить у системы немножко доверия)) Появляется вопрос. Как вычислить "тру" пользователей, от "проплаченных" -> Vip "статус".

Де факто, это тот же статус, который получают все модераторы имея кредиты доверия. И в то время, когда _Вип_ от _неВип_ не отличается абсолютно ничем, их нужно как-то различать. 

![image](https://cloud.githubusercontent.com/assets/9466814/23161006/887fc1da-f839-11e6-963a-ba7f96aa5414.png)

**Comment by tebaly** [comment]
Cкорее всего значение будет производным от количества кредитов, и все у кого их выше "N" - VIP

**Comment by inquisitor6789** [comment]
Что-то я не совсем понял.... Т.е. кредиты можно будет купить? И как тогда со спамерами бороться? Ведь если особое не будет действовать за счет купленных кредов, то это же потенциальная дырка. Не, я конечно в курсе, что спамеры предпочитают халяву (как и все), но если цена кредита будет мизерной, то что им помешает закинуть 1уе и рассылать свой спам всем?

**Comment by tebaly** [comment]
Помешает. Выгода от спама возможна только при условии отсутствия затрат или их минимуме. А заодно и проверим..

**Comment by mj4444ru** [comment]
Поддержу Сергея... Ни*уя не понял...
Выглядит примерно так: Если ты обычный лох, ездей по правилам, иначе будешь платить штрафы или вообще прав лишат... Ну или заплати и делай что хочешь...

**Comment by tebaly** [comment]
Не. Заплати и очкуй, чтоб бабло не списали в счет штрафов :sweat_smile:
Это сильно разно.

**Comment by mj4444ru** [comment]
Очкастые не будут платить
![l_40446311](https://cloud.githubusercontent.com/assets/9354685/23220578/4622469e-f944-11e6-95de-7fea104667c3.jpg)

**Comment by NeverovI** [comment]
А не получится ли так, что заплатил, наполучал особых за свое поведение, а потом начал вонять, что мол заплатил, а все украли?

**Comment by tebaly** [comment]
Пусть воняет) Для этого есть кнопка "Всё понятно, закрыть справку" :smile:

**Comment by mj4444ru** [comment]
Введите статус меценат/спонсор... По факту ничего давать не будет кроме ярлыка с пояснением что он помогает проекту... Этот же статус давать модераторам с рангом 444 и выше )))
Статус может ранжироваться по уровням... Да да, пусть меряются стручками...

Далее сделайте верификацию фотографий... Если сервис будет популярен, сделайте месяц бесплатно, далее 10 руб за фотографию... Хороший путь борьбы с фейками, который реальные пользователи вполне поддержат...

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/23340074/02faabae-fc41-11e6-9f39-a8265118db64.png)

**Comment by mj4444ru** [comment]
ну тогда у меня ещё одно предложение... давайте переименуем сервис в "знакомство с фейками"... так как именно это вы называете "анонимностью"...

хотя пойду как я создам анкетку с фейковыми фоточками и поугараю над дрочерами )))

**Comment by tebaly** [comment]
attach #406
