### ISSUE TITLE
Фаворитов больше не будет

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#367]
Фитча будет выпилена. Рекомендую переписать фаворитов на листочек. Будут перетурбации в списках контактов на пример "Ваши пары" из Тиндера. Как это разрулить ещё подумаю, накосячу и забью. А всех кто юзал фитчу непременно подaрвет пуканы. Каюсь, но иначе никак.
* вангую дичайшие косяки со списками контактов

![image](https://cloud.githubusercontent.com/assets/9466814/23207698/3da92078-f903-11e6-8eec-51158d9563dd.png)

**Comment by drvalera** [comment]
Косяки с контактами уже заметны. Во-первых не отправляются сообщения как раньше по "ctrl+enter" происходит просто перезагрузка страницы. Во-вторых контакт, с которым общаюсь при отправке сообщений может просто пропасть из списка справа и его не видно ни в одном из трех. Сижу с Оперы на данный момент.

**Comment by tebaly** [comment]
Поправлю списки. Вполне возможно, но я их ещё не трогал. "ctrl+enter" верну, это не сложно.

**Comment by tebaly** [comment]
"ctrl+enter" - вернулся

**Comment by tebaly** [comment]
Ой, сейчас со списками такой пи%дец будет... мать моя женщина

## Лицо любого пользователя после обновы
![image](https://cloud.githubusercontent.com/assets/9466814/23340470/f2c127de-fc47-11e6-8059-97779b4a72cb.png)

**Comment by drvalera** [comment]
Я морально готов)

**Comment by tebaly** [comment]
Поэтапно сделать не получается. Будет даунтайм в несколько часов и много-много боли :persevere:

**Comment by tebaly** [comment]
attach #406
