### ISSUE TITLE
Бесконечный запрос капчи

### ISSUE THREAD

**Issue by wWolfovich** [freedomsex/freedomsex#368]
Бесконечно запрашивает капчу при попытке отправки любого сообщения.

**Comment by tebaly** [comment]
быть может вы нарушаете?)

**Comment by wWolfovich** [comment]
С любого устройства и учетки. И ничего особо не нарушал, общался как обычно.

**Comment by wWolfovich** [comment]
И если вдруг чего нарушил, насколько такой бан? Или с концами?(

**Comment by wWolfovich** [comment]
И почему собственно тогда в дебаге бесконца сыпятся ошибки при любом вводе?

**Comment by tebaly** [comment]
Ничего не понятно. 
* какой дебаг
* какие ошибки
* кто вы

**Comment by mj4444ru** [comment]
@tebaly Я давно писал что есть такой грешок за вашей капчей...

**Comment by tebaly** [comment]
Баг прежде чем исправить, нужно локализовать. Моё предыдущее сообщение в силе
