### ISSUE TITLE
Кратное увеличение объема сообщений

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#369]
Отправить новое сообщение можно будет в два клика(менее чем за секунду) :relaxed:

![image](https://cloud.githubusercontent.com/assets/9466814/23356424/c7f89bec-fcea-11e6-859d-5137667b290d.png)

**Comment by inquisitor6789** [comment]
а откуда второй клик взялся?

**Comment by tebaly** [comment]
так собеседника надо выбрать)) речь о новых знакомствах
* выбрать собеседника
* отправить сообщение

Скоро безрегистрации, перезагрузок страниц и СМС :heart_eyes:

**Comment by tebaly** [comment]
attach #406

**Comment by tebaly** [comment]
#448 - реализовано. Блокнот станет вишенкой, как только воскреснет.
