### ISSUE TITLE
написать нормальную систему, в которой конфликты были бы исключены

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#37]
Я с вами в корне не согласен. Вы либо сейчас не правы, либо в прошлый раз. Ситуация аналогичная. (моё мнение что именно в прошлый раз).

А ваши попытки что то там сделать, закончились неудачно, уж не буду разбираться почему...

**Comment by tebaly** [comment]
Приступаем :cry:

**Comment by tebaly** [comment]
Ваше возражение: - "У вас всё "В праве". То есть это и есть двойные стандарты. У вас все правила "можно так, а можно так". Ваше отношение предвзято, вы по разному реагируете на аналогичные в зависимости от сторон конфликта."

Мы пытаемся писать систему в которой отсутствует _право блокирования голоса_ с целью оставить место для _диалога_ именно поэтому так много фраз начинающихся с _имеет право_. С другой стороны, начиная с Пользовательского соглашения, мы, как администрация сайта, **не имеем права** использовать фразы, начинающиеся со слов _обязан_. Данное соглашение было принято нами в самом начале разработки. 

Поэтому нам остаются _из возможных_ фразы: 
- [x] может
- [x] возможно
- [x] вправе
- [x] имеет право
- [x] нежелательно
- [x] крайне нежелательно
- [x] запрещено
- [x] категорически запрещено

Мы не имеем права обязывать, кроме соблюдения и принятия Пользовательского соглашения.

**Comment by tebaly** [comment]
Идея "голосования" порочна созданием **сговора** и блокированием решений на его основании.

**Comment by tebaly** [comment]
По теме открытия диспута появились новые данные. Оправлю вам личным письмом.

**Comment by mj4444ru** [comment]
- Мы не имеем права обязывать

Единственное что вы можете обязать, это соблюдать правила (вами установленные запреты). Обязан - это значит нарушение запрета может нести определенные последствия.

Но не об этом речь на самом деле...

- Сговор

Сам по себе сговор не имеет смысла по одной простой причине: если у людей на какую то ситуацию одинаковое мнение, то не важно сговор это или нет, они высказывают своё мнение...
Если в ряды администраторов попали фейки, это не проблема, так как при наличии 5 настоящих администраторов, необходимо будет 3 или даже 4 фейка... ну а если среди 9 администраторов 4 фейка и 5 настоящих, это уже печалька... но можно добавить новый ранг, Резидент...

**Comment by NeverovI** [comment]
Отличный план! И что дает резидент? Неприкасаемость? Т.е. срежи равных есть более равные?

**Comment by tebaly** [comment]
@NeverovI не совсем. У нас здесь где-то была дискуссия на тему "централизовано/децентрализовано". Там засветилась идея реализовать нелинейный переход от децентрализованной схемы на централизованную по мере роста ранга администратора. Подчеркну, что это была идея, которой мы пока ещё придерживаемся.
* от автоматического назначения, к ручному
* от автоматической балансировки, к ручной

> Неприкасаемость? Т.е. среди равных есть более равные?

1. Уровень автоматического регулирования: модераторы до администратора
2. Резидент - назначение ручное, резидент-резидент (план: резидент-администратор)
3. Разработчик - назначение ручное, разработчик-резидент, разработчик-разработчик

Отличие в том, что резидент имеет право настучать по голове администратору, а наоборот не получится. Это фактически основное отличие. Вероятно для резидентов будет свой уровень админки с мадмуазелями и преферансом. Тоже самое относится и к разработчикам. Они в свою очередь получают доступ/звание сугубо при личной встрече. Выше нет ничего. Администрации, как таковой у проекта нет и не будет. Лишь формально.

Я думаю такое "разделение" будет окончательным. Новых уровней больше не предвидится. Отмечу, что уровень разработчик существовал с самого начала.. Теперь это значение становится несколько "шире", так как разработчик, это не только тот, кто пишет код.

**Comment by tebaly** [comment]
> Отличный план! И что дает резидент?

В отличие от администратора, которого дает система автоматически, резидент сможет отвечать на официальные обращения/запросы, выступать от "лица" администрации сайта где угодно и так далее. Де факто, с уровня резидент начинается "Администрация сайта". В формулировке указано "Представитель администрации сайта" - так потому, что у нас нет Администрации как таковой.

**Comment by tebaly** [comment]
На будущее, возможно создание "инструментов" _отнятия_ рейтинга и званий посредством _голосования_. Об этом частично упоминал @mj4444ru в своих предложениях. Мы же нацелены на реализацию _голосований_ направленных на "личность/человека/пользователя", а не на конкретные его действия. Но это сугубо перспектива.

**Comment by tebaly** [comment]
конфликты будут всегда. иначе не существует ни одна открытая система
