### ISSUE TITLE
Готовится серьезная провокация

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#371]
В отношении проекта и всех его Пользователей готовится крупнейшая провокация! Мне цели, причины и заказчики известны. К сожалению, противодействовать или предотвратить их намерения возможностей нет. 

Предвидя задолго такое развитие событий, мною были предприняты попытки обратиться ко всем Пользователям проекта с просьбой не пересылать посредством его сервисов критически значимой информации. Использовать сайт для знакомства, а не для потенциально компрометирующего общения. Сайт и его сервисы создавались для знакомства с возможностью анонимного общения и обмена фотографиями. 
* Настойчиво рекомендовалось использовать для обмена анонимные фотографии
* Либо обычные фотографии без потенциально компрометирующей ценности

**Рекомендовалось использовать для обмена в сообщениях информацию, несанкционированный доступ к которой не способен привести к хоть сколь-нибудь значимым последствиям.**

---

В подготовке атак на проект участвуют серьезные силы с большим бюджетом. Источники финансирования очень "интересны". Я использую все имеющиеся возможности для противодействия, но силы очевидно не равны.

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/23585778/209c4468-0198-11e7-9e19-9e26dce8fcdc.png)

**Comment by inquisitor6789** [comment]
сказал а говори и б
кто, когда? :-)

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/23617664/d75e90e6-029e-11e7-9129-8d4cc745dfd9.png)

**Comment by tebaly** [comment]
#459
