### ISSUE TITLE
Похоже, что переписка попадает к Юле...

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#373]
http://freedomsex.me/admin/sethelp/?id=159502&ln=0

**Comment by tebaly** [comment]
Юлия пока не сильно отличается от обычного пользователя. Для быстрых тестов используется ее анкета, например, чтобы проверить отправку/получение сообщений/фотографий.

**Comment by tebaly** [comment]
в общем не должна она туда попадать..
