### ISSUE TITLE
Ничего у вас не меняется

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#374]
![2017-03-28 19 13 03](https://cloud.githubusercontent.com/assets/9354685/24409784/a7a68dce-13ea-11e7-9f78-2fb8112e2458.png)

**Comment by mj4444ru** [comment]
![2017-03-28 19 15 40](https://cloud.githubusercontent.com/assets/9354685/24409903/085b0d34-13eb-11e7-9be4-4b8c27415422.png)

**Comment by tebaly** [comment]
счас вроде норм
