### ISSUE TITLE
Как там со знакомствами?)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#375]
Какова обстановка с "целями" пользователей по вашему мнению?
* много ли тех кто "просто общается" / "я тут не знакомлюсь" (не блокируемых)

Вопрос в сторону "закручивания гайки"- зачистки этой части и необходимости в этого в принципе..

**Comment by inquisitor6789** [comment]
50/50 наверно
девушки больше как-то по вирту... по крайней мере если по жалобам судить

**Comment by tebaly** [comment]
Давно ожидалось, замечено, а теперь уже подтверждено - на сайте "арудуют" боты. Применяются технологии машинного обучения уже, ожидаю [от "них", их разработчиков] подключения ИИ и/или внешних сервисов с достаточной "мощностью". Единственный критерий для _вычисления_ бота - отказ встречаться в реальности, просто общение, болтовня. Других способов де факто нет.

**Comment by mj4444ru** [comment]
http://freedomsex.me/32134743

Писал с разных анкет.
Всегда стандартные ответы.
![2017-04-16 23 19 15](https://cloud.githubusercontent.com/assets/9354685/25073214/2044904a-22fb-11e7-866e-a753bcb56a7e.png)

Сидит в вечернее время постоянно, ночью нету, в остальное время не знаю. Но это точно не бот. Цель - выманивание фоток. Зачем - не понятно. Создаётся впечатление что это так администрация сайта с помощью фейков создаёт видимость того что тут есть активность, а на самом деле её нет. Не удивительно что никакого интереса к этому сайту не возникает.

**Comment by tebaly** [comment]
С недавних пор "Администрация сайта" == Администраторы

**Comment by mj4444ru** [comment]
Посетителям пох кто с каких пор Администрация сайта... Я выражаюсь терминами обычных людей...

**Comment by tebaly** [comment]
Помечайте где ваш текст и мысли, а где копипаста.

**Comment by tebaly** [comment]
https://github.com/freedomsex/docs/blob/master/deal/111-Общение-для-знакомства.md - чтиво

Так было всегда, просто не особо акцентировалось. Кандидат на главное правило №2 - знамение грядущей "Охоты на.. ботов"

![image](https://cloud.githubusercontent.com/assets/9466814/25230005/404504f0-25db-11e7-95aa-44320cedb038.png)

**Comment by mj4444ru** [comment]
у вас паранойя батюшка )))

**Comment by tebaly** [comment]
а у вас амнезия. сами пару дней назад писали про несметные полчища ботов
:) 

Я здесь тролл-сообщения затирать буду, чтоб почище было. Если вам просто "поболтать", пишите в чате, пожалуйста. А то еще начнете мне тут притеснения меньшинств инкриминировать.

**Comment by mj4444ru** [comment]
в очередной раз предлагаю, всех кто просто общается отнести к вирту
ввести статусы в анкетах типа только общаюсь (только вирт), только реал, возможно и вирт и реал
любые предложения общения относить к вирту.

**Comment by mj4444ru** [comment]
если человек признаётся что только общается (и администратор видит это в виде жалобы), администратор вправе сам выставить пользователю статус только вирт...

**Comment by Fenslau** [comment]
Эмпирическим путем выяснено следующее:
На сайте есть:
1. Те у кого не стоит "реал", но не стоит и зеленый вирт. иногда они (по их же словам) не против повиртить/неповиртить, но скажем так пообщаться. Фотки шлют тоже (для тех, кому мол это важно). Нельзя это ограничивать, это не простое бесцельное общение. Девочкам скучно + аналог либидо (не знаю, как там у них это называется).
2. Есть те, у кого реал стоит. Ой, да тоже шлют порой. от настроения. Как подкатишь. 
некоторые просто тупо ничо не ставят - как там по умолчанию в акнкете и все.
Да и дело не в этом
и тех и других и третьих довольно много. Иначе как бы я о них узнал? )

**Comment by tebaly** [comment]
Будем пробовать в сторону _знакомства важнее общения_
#430
