### ISSUE TITLE
на сайте не работает "вход" и невозможно отправить сообщение

### ISSUE THREAD

**Issue by mara112** [freedomsex/freedomsex#376]
попробуйте сами

**Comment by tebaly** [comment]
не могу воспроизвести. входит/выходит. сообщения идут, трафик в норме

**Comment by mara112** [comment]
это продолжалось около двух часов и прошло. потом у вас капчи не
принимались в течение какого-то времени (это было недавно). а вот сейчас
плохо подгружаются диалоги.

2017-04-14 15:22 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by tebaly** [comment]
Периодическое отсутствие работоспособности сайта допустимо. Сайт может отвалиться вообще и не работать несколько суток, так как сильно мешает конкурентам и подвергается хакерским атакам.

**Comment by tebaly** [comment]
Если есть какая-то явная "постоянная" техническая проблема - опишите пожалуйста.

**Comment by mara112** [comment]
явная проблема - пытаешься цифры ввести, и они не подходят

2017-05-09 5:53 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by tebaly** [comment]
Исправлено. Обновится в течении минуты

**Comment by tebaly** [comment]
Спасибо :wink:

**Comment by mara112** [comment]
все равно никак! стал спрашивать цифры после попытки отправить ссылку!
ввожу - но он не принимает их!

2017-07-06 13:44 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by tebaly** [comment]
Там при многократных попытках не принимает несколько часов
#430

**Comment by mara112** [comment]
блин! глупая же защита! допустим я хочу фотки ссылками отправлять - и что
мне теперь делать? мне не нравится, что ваш сайт фотки сжимает

2017-07-06 19:48 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by tebaly** [comment]
Фотки, вход или компрессия - вы уже определитесь на что жаловаться :)

**Comment by mara112** [comment]
на все и сразу определенно

2017-07-06 20:14 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by mara112** [comment]
а вы знаете, что у вас невозможно делиться ссылками? после отправки нн-ой
ссылки выскакивает капча, которая сайтом больше не принимается

6 июля 2017 г., 20:19 пользователь vika alekseeva <112alekseeva.vi@gmail.com

**Comment by tebaly** [comment]
Да вы что? :flushed:

**Comment by mara112** [comment]
прямо сейчас у вас не работает логин

2017-07-17 19:45 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by tebaly** [comment]
Спасибо. Исправлено. Заработает в течении 5 минут. 
* После входа просто обновите страницу

**Comment by mara112** [comment]
у вас раньше уведомления были звуковые, когда сообщение приходило. а теперь
что? а теперь приходится страничку то и дело обновлять.

2017-07-19 14:00 GMT+03:00 FreedomSex <notifications@github.com>:

**Comment by mara112** [comment]
сайт не работает сейчас?

20 июля 2017 г., 14:53 пользователь vika alekseeva <
112alekseeva.vi@gmail.com> написал:

**Comment by tebaly** [comment]
работает же
