### ISSUE TITLE
Удаление фото

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#377]
Откройте секрет глупому программисту, как удалить загруженное фото

**Comment by tebaly** [comment]
это мелкая, преднамеренная недоработка. пока никак. выкачу обнову и поправлю.

**Comment by denverman123** [comment]
когда планируется обновление?

**Comment by tebaly** [comment]
планы были за две недели сделать и поправить, но уже третий месяц на исходе... почти всё готово в принципе. много вопросов к новой архитектуре...

**Comment by tebaly** [comment]
#372

**Comment by tebaly** [comment]
Исправлено после пинка))
