### ISSUE TITLE
Город знакомтсва

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#378]
Некоторое время назад познакомился с такой замечательной штукой, как geo лакция в гугле
https://github.com/ubilabs/geocomplete/
https://github.com/jstayton/GoogleMapsGeocoder/

давайте уже замутите её, там есть всё что нужно, в результате выдаются даже координаты, которые можно использовать в поиске не по городу, а по расстоянию, то есть пользователь сам выбирает как точно себя позицианировать и как далеко искать и не надо бла бла бла про конфидициальность, пользователь сам в праве решать что конфидициально, а что нет и на сколько он готов раскрыть свои данные. естественно без номеров домов и квартир.

**Comment by mj4444ru** [comment]
формула для расчёта расстояний по этим координатам у меня есть...

**Comment by mj4444ru** [comment]
Если лень изучать, могу кинуть примеры кода как это юзается...

**Comment by tebaly** [comment]
Да, конечно. Спасибо.

**Comment by mj4444ru** [comment]
> Да, конечно

Это к чему?

**Comment by tebaly** [comment]
#278
