### ISSUE TITLE
Оскорбления родственников

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#379]
> Тут мама твоя звонила недавно ,говорит парню моему отсос сделать хочет , передай пусть приехжат

Предлагаю внести в правила строжайший запрет на оскорбления родственников.
А таких персон блокировать как троллей.

Так же необходимо наказывать (особым или вплоть до блокировки) за разжигание межнациональной розни [https://ru.wikipedia.org/wiki/Разжигание_межнациональной_розни](https://ru.wikipedia.org/wiki/Разжигание_межнациональной_розни)

**Comment by Fenslau** [comment]
анриал. чо как будто щас нельзя за это "строжайше наказать"... 
нафиг какие то рамки? к тому же, кто так вообще говорит? парочка тинэйджеров, которые мамку свою защищают от таких же? ) 
Чот я ни разу серьезного оскорбления родственников не слышал с тех пор как в линейку перестал играть ))
А за розню - вон они давно все в блоке сидят эти все межнациональные "зарЭжу"

**Comment by tebaly** [comment]
Оскорбление родственников к УК не относится никак - "по признакам пола, расы, национальности, языка, происхождения, отношения к религии". Блокирование анкет только лишь за оскорбления запрещено, вне зависимости от того, кого оскорбили - пользователя, модератора, администратора, царя, идола. 
* Случаи блокирования анкет в ответ на оскорбление модератора/администратора могут быть расценены как саботаж.
* Для троллей, @mj4444ru есть четкий алгоритм действий, включающий описание термина тролль. Вам сей слой должен быть хорошо известен.

**Comment by mj4444ru** [comment]
Тебалай, про сабатаж вы ба молчали, у вас один принцип, у кого круче рейтинг, тот и прав... и по*** прав он или нет на самом деле...
Это предложение было для других админов, а не для вас, так что непонятно какого вы *** закрыли это обсуждение... Все действия админов должны быть в рамках правил и за разовые оскорбление, особое, а за многократное блокировка, ибо это уже тролль... Всё чётко...

**Comment by mj4444ru** [comment]
хотя да, забыл, предложения от троллей года у вас наверно не принимаются... лол...

**Comment by tebaly** [comment]
@mj4444ru уточните ваш статус. Не так давно вы утверждали что вам наш сервис не интересен, равно как и его администрирование. Что изменилось и чем ваши решения мотивированы?

**Comment by mj4444ru** [comment]
У меня есть пара собеседниц интересных и мне ваш сервис интересен в роли пользователя. Когда скучно в модерирование захожу. Статус тролля меня вполне устраивает. Да, такого интереса как раньше нет, но всё равно тянет на борьбу со злом.

**Comment by tebaly** [comment]
В пользовательском соглашении приблизительно три года назад (может и раньше может позже не суть, так как достаточно давно) был добавлен раздел о "Саморегулируемом сообществе", суть которого
* 2.3. ~~Администрация сайта~~ не влияет на процесс принятия решений Сообществом, и не участвует в нем;
* 5.8. ~~Администрация сайта~~ вправе следить за соблюдение Правил участниками Сообщества, вправе принимать любые меры, направленные на соблюдение правил Пользователями сайта;
* 5.9. ~~Администрация сайта~~ вправе контролировать действия Модераторов, на соответствие принятых ими решений Правилам, вправе принимать любые меры, направленные на соблюдение справедливости в принятии решений Модераторами и правомерности их действий; 
* 5.10. ~~Администрация сайта~~ стремится не применять свои права в прямом контроле действий в Сообществе, и разрабатывает системы автоматического воздействия, корректируя работу автоматических систем, с целью соблюдения Правил всеми участниками Сообщества, включая Модераторов и Администраторов сайта;

При следующем апдейте "Администрация сайта" будет заменено на "Разработчики", тем самым станет более прозрачно наше отношение к администрированию Сообщества. Такой шаг уже сделан при составлении Правил сообщества, где принадлежность Разработчиков к администрации сайта отсутствует, а Администраторы сообщества максимально приближены к Администрации сайта. 

---

**5.7. ~~Администрация сайта~~ Разработчики устанавливают Правила поведения в Сообществе. Участники Сообщества вправе содействовать разработчикам в этом процессе.**

Ваше предложение можно отнести к содействию, однако оно противоречит действующим правилам. Цитату я привел и подчеркнул то, в чем заключается противоречие. Это и было основанием закрыть тикет - в виду противоречия дальнейшее обсуждение предложения не имеет смысла, но _обсуждение открыто_, как вы можете видеть. 

Дальнейший диалог по поводу _вселенской справедливости_ настоятельно рекомендую вести в чате, чтобы не засорять ветку. Оффтоп так или иначе приходится удалять, так как специально  для околотематического оффтопа и были созданы чаты на https://gitter.im/freedomsex

**Comment by tebaly** [comment]
Напомню, @mj4444ru у вас как минимум два достижения в администрировании официально закрепленных
* Тролль года (2016), титул главного тролля сообщества - вы первый :1st_place_medal: 
* Лучший борец за права сферического Пользователя в вакууме

В процесс ранжирования ранее был заложен процесс линейного/уровневого перехода от автоматического к декларативному. Обсуждение и анонс состоялись около года назад. Таким образом, на высших уровнях администрирования _цифры_ уже не значат ничего. Остаются достижения в администрировании и авторитет.

Ввиду конкретно ваших достижений @mj4444ru - с них писалось это:
* эксплуатация коллизий и неточностей в правилах, двусмысленности правил, пограничности принимаемого решения для провоцирования конфликтных ситуаций, накрутки рейтинга, системного флуда, троллинга Администраторов. Здесь же - разницы в индивидуальных качествах администраторов, таких как чувство меры, нормы, морали, нравственности, юмора и так далее. Равно как и создание таких ситуаций - вправе расцениваться как саботаж. 

Дельных и полезных ваших предложений достаточно. Нет никакого секрета - их больше всего. Все они открыты и по всем им идет работа. У вас есть знания и навыки в разработке. Также, судя по всему вы хороший специалист в социальной инженерии. Горжусь вами, честно. И благодарен вам за вашу помощь. Спасибо.

Исключая профессиональные моменты, никакой предвзятости к вам нет.
