### ISSUE TITLE
Вакансии на участие в разработке

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#380]
Чуть позже на главную будет добавлено объявление о _вакансиях_ в разработке проекта. Оплата по договоренности. Бюджет в целом у проекта скромный, поэтому нанять высокооплачиваемых специалистов, равно как и установить/опубликовать "базовую оплату труда" нет возможности.
* JavaScript - VueJS
* PHP - Symfony 3

**Comment by mj4444ru** [comment]
ну хоть 100к деревянных будете платить?

**Comment by mj4444ru** [comment]
только 10?

у вас php часть вроде должна быть простая как 2 копейки... только некоторые функции не тривиальные... или вы всё же хотите всё с нуля переписать?

**Comment by mj4444ru** [comment]
Я бесплатно вам хотел помочь, но у нас разные взгляды на некоторые вещи... Кое что у вас всё же через жопу...

**Comment by mj4444ru** [comment]
Поделитесь исходниками и структурой базы, что бы хотя бы понимать в каком состоянии оно... Ну и подробнее какой план...

**Comment by Fenslau** [comment]
Если бы я знал php этот ваш.... 
Охх. Такое желание есть опыта поднабраться. Но вот даже начального уровня нет.
Хотя это бы реально вдохнуло бы в меня интерес к проекту. 
Но... Нету. И, как я понимаю, в кратчайшие сроки эту кухню не освоить.
У меня опыт только по политеху - ООП, асм_х86 (о, боже, да, не могу вспоминать без ностальгии, какие проги я на нем писал...!), общая теория алгоритмов... 
Блин, ну и вот получается, что до сих пор! ДО СИХ ПОР! нужно знать синтаксис какого то языка чтобы писать программы. И это в то время, когда просторы бороздят.... Когда сайты уже можно делать порядочные в виксе, конкурируя со студиями, которые их же и изготавливают... 
Да что ж такое! 
Этот ПХП и яваскрипт мне сыпят соль на рану - ну чош я их не изучил ранее, а...

**Comment by mj4444ru** [comment]
@Fenslau - изучить PHP в основе хватит несколько вечеров, далее пишется по примерам ранее написанного кода...

Для правильной организации проекта и т.п., нужны глубокие знания, причём знание языка это капля в море по сравнению с тем что надо знать о фреймворке на котором пишешь, ибо его функционал кратно больше и сложнее всего php...

Для расширения несложного функционала достаточно ранее написанных примеров...

Яваскрипт при своей максимальной простоте и тривиальности воспринимается куда сложнее чем php...

**Comment by Fenslau** [comment]
Да, да. То же самое можно и для асма_х86 написать. Как и для любого другого языка. Я уже понял, что я лузер в этих ваших пхп. Но вот есть мнение, что по общей алгоритмизации, я еще что-то могу. 
Го тест-соревнование. С заданием. Кто справится быстрее и оптимальнее - тот и победил. Ты же программист так или иначе?
Принимай вызов. А парни придумают нам задание. Найти алгоритм в таком то условии.

**Comment by inquisitor6789** [comment]
гыыы, лол
а че тут думать? вот вам задание - придумать и задокументировать в BPMN новую систему администрирования-модерирования. Документация должна включать в себя следующие артефакты:
- общее описание решаемой проблемы
- описание иерархии административного ресурса (если будет такая иерархия)
- описание процессов принятия решений
- описание процессов решения конфликтов
- описание решения по проблеме бездействия админов (опционально)
Результат в свою репу на гите выкладывайте, а мы посмотрим

**Comment by Fenslau** [comment]
если штаб-квартира фридомсекса находится в питере, напишу эту документацию за 1 день.

**Comment by inquisitor6789** [comment]
а при чем тут шк? не вижу связи

**Comment by Fenslau** [comment]
Я хочу туда переехать.

**Comment by mj4444ru** [comment]
я все равно не понял причем тут шк...

**Comment by Fenslau** [comment]
Более тесное сотрудничество, пьянки, гулянки, блэкджэк

**Comment by inquisitor6789** [comment]
не удивлюсь если шк в нижней пердяевке :smile:

**Comment by Fenslau** [comment]
Давайте ачивки добавим. Оно и бесплатно и лояльность повышает.
Заибали, предлагайте чони ть

**Comment by inquisitor6789** [comment]
> Давайте ачивки добавим.

и что на них должно быть?
"Я послал член 100 раз?"
"Меня послали нахуй"?
![image](https://cloud.githubusercontent.com/assets/19651618/26243748/9f283db8-3c95-11e7-8954-14750f5ce974.png)

**Comment by Fenslau** [comment]
Г.
Максимальная конверсия (для парней).
И полезно и для девочек информативно.
у тебя 15,6
у меня: 32,8

**Comment by Fenslau** [comment]
в % перевести можно
у тебя 6 % сообщений достигают ответа.
У меня - 3 ))
Сука, надо нагонять )

**Comment by inquisitor6789** [comment]
ууууу..... боюсь эти цифры будут стремиться к нулю....
кстати, это уже есть, только видно это в профиле 
`Предложено 3815, принято 224 знакомств `

**Comment by Fenslau** [comment]
простым смертным не видно.

**Comment by judgeofdestiny** [comment]
Привет разработчику))у тебя крутой чат)спасибо за труды) я вот юзаю несколько дней его)))весело там. у меня есть идеи)могу делиться бесплатно просто от души)хотел бы чтоб таких чатов было больше)и функций было больше)потому что это реально круто)

**Comment by tebaly** [comment]
Ух.. Привет :relaxed:
Идей тут 78 - добавляй сколько хош. Ток мо проблема в коде. 
Его писать и править не успевают))

**Comment by tebaly** [comment]
> Где у вас узкое место? Кто сколько ресурсов жрёт? ... Может даже проблемные запросы...
Тогда я подумаю над оптимизацией всего этого добра... @mj4444ru 

Ни с запросами ни с нагрузкой проблем нет. Разделение на независимые микросервисы это не про нагрузку и даже не про оптимизацию. Микросервисы это архитектурное решение. Просто как требование - треба чтоб микросервисы и независимые БД, и всё))
* Проблемы с OS(гипервизором) + неоптимальная конфигурациея софта. Диски медленные у машинок. Но это совсем другая история.

---
Писать кода много нужно сейчас. Фронтенд сейчас много пишется, например. А для него АПИшки нужны, которых не было и так далее. Всё связано.

**Comment by mj4444ru** [comment]
Ок, зачем вам нужно такое архитектурное решение?
Какова причина выбора такого решения?
Какие плючы и минусы?
Какова реальная необходимость каждого из плюсов данного решения?

**Comment by mj4444ru** [comment]
Раскройте текущее состояние вашего решения... Какие сервисы... Что они делают... Как связаны между собой... Как изолированы... Что из себя представляет каждый сервис...

По мне так расходы на взаимодействие сервисов могут быть оправданны только технической невозможностью решить задачи в рамках единого сервиса...

**Comment by tebaly** [comment]
Вы не правы :stuck_out_tongue_winking_eye:

**Comment by mj4444ru** [comment]
Ок, жду ответы на вопросы )))

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26742940/84fa27b8-47e8-11e7-92f7-01c8eea2c338.png)

**Comment by tebaly** [comment]
Опубликовано
