### ISSUE TITLE
Вертикаль власти

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#381]
> Ввиду того что спорить с ним бесполезно, получается что у вас не сообщество равных администраторов, а вертикаль администрации со всеми вытекающими последствиями. То есть Сергей по факту как президент этого сайта. 

А что ответить? Он этой должности достоин) 

Демократия без ограничений/ответственности - это анархия. Точно цитату не вспомню, но смысл вроде торт. @mj4444ru с кем то из вас лично обсуждали централизованное/децентрализованное администрирование. Сошлись на том, что будем развиваться в сторону линейного/уровневого перехода от распределенного администрирования к вертикали. Когда в массовом сегменте модераторов преобладает обезличенность и равноправие, у администраторов согласованность, а на высшем уровне администрирования авторитарность.

Своего рода сущность "Суперадмин" подразумевает, что он может делать всё что захочет из того, что правилами явно не запрещено или им не противоречит. Чем выше Администратор сообщества тем больше он "Администрация сайта". 
* **5.9. Администрация сайта вправе контролировать действия Модераторов, на соответствие принятых ими решений Правилам, вправе принимать любые меры, направленные на соблюдение справедливости в принятии решений Модераторами и правомерности их действий;**

**Comment by mj4444ru** [comment]
Да да, это мы с вами спорили. Вы за вертикаль, я за равноправие каждого человека в рамках своего статуса. нельзя ставить = между активностью и адекватностью человека. Ввиду отсутствия системы разруливания споров, адекватной оценки опытности администратора и нежеланием вас (разработчика) разруливать споры, вертикаль как мне кажется несколько не подходит.

**Comment by mj4444ru** [comment]
Хорошо что он (Сергей) чуть добрее чем Ким Чен Ын... шутка...

Но проблема то не в Сергее, а общая... И Сергей раньше чаще всего был не самым высоким резидентом, так что это лишь актуальный на текущий момент пример...

Почему вы не хотите принцип 3 участников реализовать на уровне автоматики?

PS: Я вполне допускаю что Сергей как высшая инстанция может разруливать любые споры других лиц, но только не споры других участников с ним...

**Comment by inquisitor6789** [comment]
> Почему вы не хотите принцип 3 участников реализовать на уровне автоматики?
потому что тогда время решения увеличится пропорционально. Сейчас жалобы по 40 минут висеть могут. А что же тогда будет если реализовать тройки?

> И Сергей раньше чаще всего был не самым высоким резидентом
однако самый "долгоиграющий" с недавнего времени. Да и у меня такое впечатление, что система начисления рейтинга сейчас работает не пойми как.

**Comment by Fenslau** [comment]
Давайте уже развенчаем Сергея как высшую инстанцию!
Мне лично вообще не нравится, что какой то там, понимаешь, парень, чо то там вершит.
Как так а? 
Кто он такой? Надо просто взять его и как следует спросить, я щитаю ))
А то вдруг мало ли что.
)

**Comment by tebaly** [comment]
> Да и у меня такое впечатление, что система начисления рейтинга сейчас работает не пойми как.

Так и есть. Давайте голосовать. Принимаем заявки на пост Президента сайта. Выберем три заявки, и будем голосовать))

**Comment by mj4444ru** [comment]
> Сейчас жалобы по 40 минут висеть могут. 

Заявка на блокировку 12 часов висит, хотя вот тут действительно иногда актуальна моментальная блокировка. А жалобы подождут.

@tebaly Тогда надо предвыборную программу каждому кандидату готовить )))

**Comment by Fenslau** [comment]
Да это шутка блин ))))

**Comment by mj4444ru** [comment]
> Выберем три заявки, и будем голосовать))

голосую за @Fenslau (других не знаю)...

**Comment by Fenslau** [comment]
не не. Щас а то меня выберут единогласно.
Чо короче хочу сказать. Как бы это и так понятно:
Кого мы вообще выбираем? Сергей ничо не хочет. А у меня нет предложений по монетизации.

**Comment by Fenslau** [comment]
дайте стату по метрике.. Можно чото придумать.

**Comment by Fenslau** [comment]
444, напиши мне. не обещаю, что будет хорошо. но тем не менее

**Comment by mj4444ru** [comment]
@Fenslau если бы я ещё знал кто ты там )))

**Comment by inquisitor6789** [comment]
>Сергей ничо не хочет.

кто вам это сказал?

**Comment by Fenslau** [comment]
давайте плясать от статы по метрике.
Надеюсь она прикручена?
Нам надо думать про монетизацию, чтобы бабло у разрабов было, согласны?
Серег, ну придумай чонить. Я хз. Концепцию можно и изменить - го мозговой штурм.

**Comment by tebaly** [comment]
В треде наблюдается недостаточное владение основой под дискутируемой сущностью. Президент - сие исполнительная власть, это - интеграционный правовой институт, цель которого состоит в согласовании деятельности институтов инкапсулированной/ограниченной власти.

**Comment by tebaly** [comment]
> А чо еще надо?

Надо чтобы тролли успокоились. Для этого президентом должен быть непосредственно король троллей. Иначе тролли не в состоянии рассмотреть в вертикали ничего кроме диктатуры и авторитарного режима.

Сергей не подходит, он не из Единой России. :disappointed_relieved:

**Comment by Fenslau** [comment]
А я думал, что президент не исполнительная. Что он исполняет? Это номинальная фигура. Но важная. 
Я бы Юльку в президенты двинул, но она чот забила на сайт, походу бабло рубит в Сибе )))

**Comment by mj4444ru** [comment]
> Я бы Юльку в президенты двинул

Это которая сначала нахамила, а потом мне рейтинг обнулила из за своей невнимательности и безответственности? id 2641055

**Comment by Fenslau** [comment]
нет, эту я не знаю.

**Comment by mj4444ru** [comment]
Или та Юля, которая техподдержка?

**Comment by inquisitor6789** [comment]
Насколько я понял, то речь идет о Юле ака Premasvarupa (надеюсь что правильно ник написал) ака 7669797

**Comment by mj4444ru** [comment]
Давненько её не видно и не слышно...

**Comment by tebaly** [comment]
Проблему власти обсудили. Возражений нет. Тема закрыта.
