### ISSUE TITLE
Визуальная идентификация пола

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#384]
![2017-05-15 19 36 57](https://cloud.githubusercontent.com/assets/9354685/26062915/c9d52dde-39a5-11e7-9951-813c95a68216.png)

Вот так вот иногда пишут. Как мне кажется это из за отсутствия явного визуального указания на пол в самой анкете. Сделайте в публичной части как вы это сделали в админке (красиво и доходчиво).

**Comment by tebaly** [comment]
#55
