### ISSUE TITLE
Я разговаривал на тех же тонах

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#385]
> Я разговаривал на тех же тонах что и собеседник, но значительно более корректно... Я не хамил... Я адекватно представлял аргументы...
Я пытался объяснить админу что она не права... Получил обнуление...
Обратился к вам со всеми доказательствами... Получил обнуление...
И смешно читать что вы не предвзято относитесь ко мне...

@mj4444ru получил необоснованное обнуление от Администратора с которым участвовал в споре. При разбирательстве, так как необоснованность была очевидна, рейтинг был возвращен. Но в последующем это решение было пересмотрено:
* Администратору, за необоснованное обнуление был сброшен рейтинг, до выяснения обстоятельств
* Для @mj4444ru рейтинг был приведен в состояние на момент принятого сброса
    * _на тех же тонах_ - в резкой достаточно манере, что не способствовало решению конфликта

Не пытайтесь вводить в заблуждение. В отношении вас по тому "эксцессу" **в итоге** не было предпринято ровным счетом ничего. Планировалось дойти до этого уровня:

![image](https://cloud.githubusercontent.com/assets/9466814/26074124/5705f25c-39b9-11e7-902b-7842faeadb0e.png)

---

# Но чуда не произошло - стороны конфликта отказались от диалога.

**Comment by mj4444ru** [comment]
Почему я должен быть вежлив и мягок в отношении тех кто мне прямо угрожает и хамит в ситуации когда он не прав? Я не оскорблял, я был краток и конструктивен, хоть и в грубой форме...

Вот Сергей в такой момент не церемонится, а просто пишет "Ещё раз так сделаешь, сброшу рейтинг"... Так вот по вашему очень конструктивно, а то что я пытался несколько раз донести до администратора что она не права, указывая на ошибки, это по вашему не способствует решению проблемы...

> У вас есть дедовщина? Не, не слышал...

**Comment by tebaly** [comment]
Когда вы не можете чего-то сделать - выясните позицию Администратора. Если его позиция и действия противоречат правилам - сообщите разработчикам и/или другим Администраторам.
* если вы повторяете "запрещенные" действия - это троллинг и саботаж
* если вы хамите/дерзите в ответ или провоцируете - это троллинг и саботаж

Разработчики не станут "восстанавливать справедливость", если сторонами конфликт не предпринято мер к разрешению конфликта. Разработчики могут, но не обязаны выяснить позиции участников конфликта. Используйте комментарии, чтобы обосновать свои действия и ведите диалог, чтобы разрешить конфликт или выяснить позицию и цели конфликтующего.
* Разработчики вправе отменить ошибочное воздействие на Администратора, однако такая возможность есть не всегда.
* Разработчики вправе игнорировать ошибочное воздействие на Администратора, если его действия не сопровождались необходимыми комментариями или не имели должной аргументации в сложных или неоднозначных ситуациях.
* Разработчики вправе игнорировать конфликты среди Администраторов, если ими не предпринимались попытки к совместному решению конфликта или спора, поиску решения в сложной ситуации.
* Намеренное игнорирование Администратором возможности указать комментарий к действию в сложной ситуации, или при отмене сложных решений, ожидаемо приводящих к конфликту/спору, может восприниматься как попытка саботажа системы безопасности.
