### ISSUE TITLE
Глюк с идентификацией последнего входа

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#388]
![2017-05-17 18 02 16](https://cloud.githubusercontent.com/assets/9354685/26154967/0b06078e-3b2b-11e7-87e3-ffed064b9192.png)

**Comment by tebaly** [comment]
#272

**Comment by mj4444ru** [comment]
Вы закрыли тему, логично предположить баг найден...

Дам подсказку, через 5 минут статус нормализовался... Может кеш?

**Comment by tebaly** [comment]
> Может кеш?

Может. Скорее всего критерий не из того места берется :relaxed:

Тот тикет закрыли после фикса. Дабы его заново не открывать, оставил ваш до починки

**Comment by tebaly** [comment]
#357
