### ISSUE TITLE
Проблемка с желаниями

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#389]
Поступила проблема через саппорт
http://freedomsex.me/admin/sethelp/?id=162224&ln=162225

![2017-05-17 18 09 37](https://cloud.githubusercontent.com/assets/9354685/26155257/0488e7f4-3b2c-11e7-9c5d-c68ebe56a87d.png)

**Comment by inquisitor6789** [comment]
на телефонах не все кнопки нормально нажимаются.
Например нельзя установить статус нарушителя или быстрые ответы юли не работают. Может корень проблемы один?

**Comment by mj4444ru** [comment]
> Может корень проблемы один?

ну да... руки тебалая...

**Comment by tebaly** [comment]
Сейчас всё на сайте работает через раз. В случаях, когда нет массовой проблемы, значит это не проблема. Это проблема разработки, бес с порно.

**Comment by inquisitor6789** [comment]
проблема с телефонами массовая

**Comment by tebaly** [comment]
У кого получилось воспроизвести(1), На каком устройстве и ПО(2) - просто, _у меня всё работает_))
* ввиду применения современных средств разработки на клиенте, а именно - VUE.js - много у кого может что-то перестать работать - это норма для старых устройств или старых версий броузеров
* в дополнение, процесс разработки вовсе не как у ВК или фейсбук - кроссбраузерность или кроссплатформенность обеспечиваются на минимальном уровне. 
* отладка и тестирование проводятся в минимально необходимом объеме и на ограниченном числе платформ и браузерах - мы не такие богатые как может показаться.

**Comment by inquisitor6789** [comment]
труба - SM-A700FD
ос - андроид 6.0.1 со всеми установленными апдейтами
браузер - стандартный для андроида (хром??) версии 4.0.30-15

не нажимается следующие кнопки - статус в профиле, быстрые ответы юли (на компе тоже не всегда; такое впечатление, что размер кнопки составляет несколько пикселов и попасть в нужное место сложно). Может что-то еще, но я не заметил.

В разработке вы пошли путем первопроходцев (даешь внедреж и свистоперделки).... Может надо пойти по пути стратегии 80/80 (80 процентов функционала работает у 80 процентов пользователей)? Пользователь в данном контексте это связка человек-устройство.

**Comment by tebaly** [comment]
Тако суть была в желаниях - у каго-то оно не нажимается...
