### ISSUE TITLE
Спорная ситуация

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#390]
Имеем жалобу "Привет некрасивая. Интимные темы с фото?"
http://freedomsex.me/history/message/379594/

Я вижу в этой жалобе прямое оскорбление. Сергей считает это виртом.
Кто прав?

Вот переписка:
![2017-05-17 18 38 46](https://cloud.githubusercontent.com/assets/9354685/26156552/1ca7ac54-3b30-11e7-868e-40113960c962.png)

**Comment by tebaly** [comment]
> Я вижу в этой жалобе прямое оскорбление

Мы все за вас рады. Вам дали четкие и ёмкие комментарии. Перечитывайте.
