### ISSUE TITLE
Баг в статусе и быстрых ответах

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#391]
>  не нажимается следующие кнопки - статус в профиле, быстрые ответы юли (на компе тоже не всегда; такое впечатление, что размер кнопки составляет несколько пикселов и попасть в нужное место сложно). Может что-то еще, но я не заметил. @inquisitor6789 

Давайте попробуем локализовать проблему. С десктопа начать будет проще:
* на компе тоже ... такое впечатление, что размер кнопки ... попасть в нужное место сложно
    * сможете записать home-видео для меня?
        * с воспроизведенным багом
        * с открытым "инспектором"/консолью инструментов разработчика

**Comment by inquisitor6789** [comment]
вот стоило только заговорить о проблеме и на компе все стало нормально работать :-[

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26208038/c41d5db4-3bf1-11e7-8263-d02bfe0696b9.png)

**Comment by tebaly** [comment]
Может и с мобилками так же??
