### ISSUE TITLE
ТП: После обновления сайта , пропали присланные фотографии

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#392]
http://freedomsex.me/admin/sethelp/?id=162408&ln=0

> После обновления сайта , пропали присланные фотографии ! Как их восстановить?`

**Comment by tebaly** [comment]
неа. обновления не было. фото не трогали

**Comment by mj4444ru** [comment]
Ну тогда ответте сами от юли, человек говорит у всех пропали. Я проверить не могу, так как нет фото, ну или тоже пропали ))))

**Comment by tebaly** [comment]
не могу подтвердить баг. если у вас тоже пропали, сообщите. ему то откуда знать что у всех?)

**Comment by mj4444ru** [comment]
В смысле у всех его контактов пропали...

**Comment by mj4444ru** [comment]
Человек пишут...

> Из чата да , удаляются !) Но они еще находились где написано "будут храниться " ... Ан нету ))) но справа в списке , Аватарии видны )

У меня по факту так же... Может разъясните принцип работы?

**Comment by tebaly** [comment]
>  Может разъясните принцип работы?

NO.

Из-за низкого качества кода и архитектуры приложения. Проще говоря - это норма!

**Comment by tebaly** [comment]
Что касаемо блока присланных и аватаров - они могут пропасть в любой момент. Фотки нужны только чтобы на них посмотреть "один-два" раза, в переписке. Больше от них ожидать нечего.
