### ISSUE TITLE
Юля

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#393]
Я тут заметил если открыть вопрос в ТП и выйти без ответа, он исчезает из списка... Это реально так или меня глючит?

Хотел проверить, но вопросы отправленные Юле до Юли не дошли (((

**Comment by mj4444ru** [comment]
а не, проверил, вроде всё ок сейчас...

**Comment by tebaly** [comment]
Этот киборг сейчас так нестабилен.. можно ожидать чего угодно

![image](https://cloud.githubusercontent.com/assets/9466814/26286841/1a87034e-3e77-11e7-9317-6f4511839e0b.png)
