### ISSUE TITLE
Чужие интим фото в первом сообщении

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#395]
Чужие интим фото без лица в первом сообщении - с одной стороны это как бы вирт, ничего такого, но с другой стороны это не совсем хорошо... Как это толковать с точки зрения правил сайта и что с ними делать?

**Comment by tebaly** [comment]
рассылка фото всем подряд запрешена

**Comment by mj4444ru** [comment]
так они не всем подрят, через одного... это уже не всем подрят, а значит можно )))

второй вопрос, что с ними делать? вроде не видел что бы этих перцев блокировали... мнение администраторов?

**Comment by tebaly** [comment]
Делайте что хотите опираясь на правила. Рассылка фото запрещена. В правилах и соглашениях достаточно информации. Тема не достойна обсуждения.
