### ISSUE TITLE
Грубость девушек

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#396]
http://freedomsex.me/userinfo/profile/32916185/

Давайте с пониманием относится к нормальным пользователям...
@inquisitor6789 вы отличаетесь от программы тем что можете анализировать адекватность жалоб, а не только их количество...

Что имеем
-------------------

Девушка грубо реагирует на виртуалов и отправителей хуев...
За свою грубость она вводит капчу...

8 замечаний, 7 из которых не имеют оснований, хотя такого рода обвинения должны иметь доказательства... а 8-я от виртуала (которых она явно не любит)...

Сама никого не провоцирует, грубо отвечает только мудакам...

**Зачем блокировать?**

**Comment by tebaly** [comment]
> Сама никого не провоцирует, грубо отвечает только мудакам...

Читайте Правила **"Мы не устанавливаем контекста употребления оскорблений."** И не тащите сюда весь этот хлам. Решили вспомнить былую молодость?) Я уверен, что @inquisitor6789 и другие Администраторы помнят, что за создание _обоснованных и необоснованных_ конфликтов можно ограничивать доступ к админке сбросом рейтинга инициатору конфликта.

**Comment by tebaly** [comment]
Если вам лень читать правила или Соглашения, это ваша проблема. Ни один из Администраторов не обязан вам их разъяснять или пересказывать. Администратор вправе предоставить цитату или ссылку на правила, и мы рекомендуем делать это для
* предупреждения конфликтных ситуаций
* косвенного "обучения" зеленых админов

Но вы то лично уже давно переросток)) И даже разработчики уже склонны игнорировать генерируемый вами бред, что к величайшему сожалению, получается делать не всегда.

**Comment by mj4444ru** [comment]
Я не создавал конфликты...
Я лишь попросил безосновательно не блокировать нормальных пользователей и написал почему, а так же мне было интересно мнение других администраторов...

Вам похоже нравится что ваш сайт превратился в сообщество ебанутых дрочеров, виртуалов и любителей отправлять чужие письки... А реальных пользователей которые тут ради секса вы блокируете...
Сергей вечно защищает дрочеров, видимо сам только этим и занимается...
Вы тебалай походу тоже... Два сапога пара...

**Comment by inquisitor6789** [comment]
хм.... интересно, а на гите можно капчей наказать? :-)

**Comment by mj4444ru** [comment]
на гите можно удалять и блокировать на время...
бесите вы меня когда нормальных пользователей обижаете...

PS: спасибо что рейтинг сбросили... хоть весь заберите, мне не жалко...

**Comment by tebaly** [comment]
## Настало время открыть вселенскую тайну.
Сайт создан для знакомств! Только никому не говорите!!!
* Использовать сайт _для занятия сексом_ технически невозможно. Отсутствуют сервисы для физической стимуляции половых органов Пользователей или осуществления полового акта

**Comment by mj4444ru** [comment]
Открою вам не вселенскую, но наверно тоже тайну...

Сайт используют не только для знакомств...

> FreedomSex.net - это свободный проект. ... Подразумевает целью знакомства именно секс.

А у некоторых цель знакомств - поунижать и пооскорблять... И вы к ним относитесь лояльней, чем к тем кто для секса сюда пришёл...

**Comment by tebaly** [comment]
Ну, в ваших словах нет ни единого противоречия!)
* сайт для знакомства, а встреча или свидание происходит уже в реальности.
* я вас снова разочарую, но парни с девушками не знакомятся для чего-то иного.
    * это не я придумал, а природа. и это не на сайте написано, а в генах всех людей
* мы собственно и ограничиваем возможности тем, кто ставит целью поунижать и пооскорблять

**Comment by mj4444ru** [comment]
тебалай. зарегистрируйтесь как девушка, поссидите от имени девушки якобы в поисках реального секса и вы поймёте сколько дибилов на вашем сайте мешают это нормально делать...
если парень начинает домагаться до девушки, не понимает что его действия ей не интересны, то за посыл таких парней блокировать не нельзя, ибо они достойны этого...
а вот за клевету со стороны таких парней как раз таки надо наказывать, чего вы не делаете... а страдает девушка, которую заебали ваши дрочилы, виртуалы, люди с больной фантазией...

я вот специально провёл эксперемент, пообщался от имени девушек и теперь совсем иначе смотрю на многие вещи. и только в основном девушки админы я смотрю тут у вас как то адекватно могут судить...

**Comment by inquisitor6789** [comment]
блин, ну сколько вам говорить, что оскорбления и чрезмерная грубость должны быть наказаны без учета контекста. 
Касаемо описания ситуации проигнорировать их было слабо? Или гордость и религия не позволяли? Если такие нежные, то сидите дома и дрочите под одеялом

**Comment by mj4444ru** [comment]
> Если такие нежные, то сидите дома и дрочите под одеялом

То есть вы считаете что если человека оскорбляют присланные хуи без спроса, то ему нечего делать на этом сайте и таких надо блокировать? Вы ебанулись? Вы за 100 отосланных хуёв не блокируете, а за 10 несерьёзных оскорблений за всю историю общениях, готовы блокировать...

и чё за термин, фиолетовая анкета? может вы не в курсе что фиолетовым окрашены отклонённые замечания? по вашей логике за то что на неё клевещат, это уже повод её блокировать?

**Comment by tebaly** [comment]
@mj4444ru - для того, чтобы открыть фото, необходим **безусловный акцепт** от Пользователя на просмотр фотографии. Без согласия на то, что фотографии могут содержать взрослый контент, и без подтверждения того, что Пользователь имеет право просматривать контент с возрастными ограничениями - открыть и увидеть содержание фотографии _невозможно_.

Решение о том, просматривать содержимое фотографии или нет, Пользователь принимает самостоятельно в каждом случае получения графического файла.
* Если пользователь не запрашивал фотографию от собеседника и не знает заранее содержания, ему рекомендуется игнорировать её. Если он принял решение посмотреть...

**Comment by mj4444ru** [comment]
@tebaly это сайт секс знакомств, а не какой нибудь юридический портал... Вы с Сергеем живёте в какой то своей реальности и не понимаете что людям на самом деле нужно...

**Comment by mj4444ru** [comment]
Вы поднимали тему отсутствия диалога между админами и вами... Ваши действия не адекватны, может по этому контакта с вами избегают...

Пример? Да вот именно сейчас ко мне обращаются люди с вопросами за что заблокировали, а не к вам...

Я устал бороться с вашей неадеватностью... Теперь мне на всё похуй...

**Comment by mj4444ru** [comment]
Думаете я один такого мнения? 

![2017-05-25 18 03 14](https://cloud.githubusercontent.com/assets/9354685/26451214/80ae92fe-4174-11e7-9b0f-da20cbc3b699.png)

**Comment by tebaly** [comment]
У вас какой-то секретный канал связи?) 

![image](https://cloud.githubusercontent.com/assets/9466814/26455760/cc8a0830-4173-11e7-8a42-72ff52449193.png)

* Если вы наблюдаете несоответствие правилам (нарушение) - вы должны действовать
* Если вы игнорируете Нарушение, вы нарушаете принципы администрирования
* Замалчивая нарушения в администрирования, вы с происходящим соглашаетесь.

С точки зрения СБ, те кто видят и молчат, те кто видят и ничего не делают - неадекватны. Ну а те кто видят, ничего не делают и возмущаются отсутствием действий - ... Не переживайте, впереди ещё зачистки :kissing_heart:

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26456439/baa1a16c-4175-11e7-9e3e-45ea6e342b8b.png)

**Comment by mj4444ru** [comment]
> У вас какой-то секретный канал связи?)

Да, есть такой один канальчик анальчик... Только вам и только по секрету em.xesmodeerf...
Там высший уровень секретности, сообщения удаляются через 7 дней, но главное фотки не постить...

**Comment by mj4444ru** [comment]
> Если вы игнорируете Нарушение, вы нарушаете принципы администрирования

А если не игнорируете, вам режут рейтинг, что бы в след раз соглашались со всеми неадекватными решениями дедов...
