### ISSUE TITLE
Глюк с отображением изменённого имени в анкете

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#397]
Если поменять собеседнику имя и не общаться с ним неделю, то при открытии анкеты отображается исходное имя, но если человеку написать, то человек становится снова переименованным... когда он снова становится переименованным непонятно, то ли после отправки сообщения мной, то ли после получения ответа, но в любом случае не удобно...

**Comment by tebaly** [comment]
> и не общаться с ним неделю

И не благодарите. Скоро вы вообще не сможете ему написать :sweat_smile:

**Comment by mj4444ru** [comment]
Чё то я не понимаю вашего юмора (((

**Comment by tebaly** [comment]
Контакты будут одноразовые. Ели вы перестали общаться или вас удалили/заблокировали
* всё (как в тиндере)

![image](https://cloud.githubusercontent.com/assets/9466814/26531851/0c158e64-43fb-11e7-81c4-9bffd12bd194.png)
