### ISSUE TITLE
Возможно не работает блокировка и/или замечания

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#398]
> Я получаю член в подарок и, не вступая в переписку блокирую автора на своей странице, но он тут же шлёт мне тот же член только в профиль. Вынуждена быть грубой)). Из этого я делаю вывод, что блокировка не работает.
Фото отправляю модераторам и пишу замечание. Тут же иду смотреть. Фото есть. Замечания нет((.

Вот такое мне прислали, сам не проверял

**Comment by mj4444ru** [comment]
Блокировку проверил, вроде работает

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26530852/b3c7d998-43e5-11e7-9728-b1b418f39610.png)

**Comment by mj4444ru** [comment]
сказали работает через раз...

ещё если нажать отправить в арбитраж на 2 сообщения, реально отправится только последнее... возможно есть что то общее, а может нет...

**Comment by Neaskil** [comment]
Если нажать ссылку заблокировать при переписке с пользователем.
Выдается что вроде как заблокирован "Контакт заблокирован и удалён из списка." но не убирается из списков общение или знакомства.
При этом если в анкету зайти видим опять же активную ссылку "заблокировать".
Также при нажатии ссылки заблокировать не работает ссылка опубликовать замечание.

**Comment by tebaly** [comment]
Уберем эту кнопку со следующим обновлением. Да, кнопка не работает - отключена.

**Comment by tebaly** [comment]
убрано. осталось только на одном основном сайте и пропадет после обновления
