### ISSUE TITLE
Боты

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#399]
![2017-05-28 21 17 09](https://cloud.githubusercontent.com/assets/9354685/26530261/0c88a544-43eb-11e7-8cc0-52b1a74f9c92.png)

И как с такими бороться? Мне кажется пора забацать кнопочку "Отправить жалобу с отправкой всей истории", ибо иначе тут никак...

**Comment by mj4444ru** [comment]
PS: у анкеты собеседника нет города

**Comment by tebaly** [comment]
@то норма - не так давно общался с разработчиком из областей ботостроения и машинного обучения. Об этом говорил в одной из тем в тот же день здесь. Он работает самостоятельно. 

Как и спам отаку, решим как станет необходимо. Об этом было предупреждение уже

**Comment by tebaly** [comment]
Моя тактика в этом отношении проста - подождать максимальных затрат со стороны атакующего. Решить вопрос так, чтобы это причинило максимальный ущерб атакующей стороне. Написать бота или эффективного спамбота для отдельного сайта, это всегда затратно.

**Comment by mj4444ru** [comment]
И опять оказалось что не бот..
Откуда только такие идиоты берутся...

![2017-05-28 23 10 15](https://cloud.githubusercontent.com/assets/9354685/26531076/df48f1f0-43fa-11e7-8481-2bca60685650.png)

**Comment by mj4444ru** [comment]
я тут подумал, может эти мудаки используют форму массовых ответов? отсюда и бессмысленные сообщения...
