### ISSUE TITLE
Геолокация

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#4]
Предлагается гео-локацию сделать не в виде строки, а в виде 3 полей (которые функционально можно хранить в виде одной стандартизированной, либо сериализованной строки).
Гео-локация должна содержать 3 поля:
- Страна (фиксированный справочник локализованный под каждый язык сайта)
- Тип населённого пункта (фиксированный справочник локализованный под каждый язык сайта) [город, посёлок, село, посёлок городского типа]
- Населённый пункт в виде строки (с возможным указанием региона для городов типа Благовещенск).

Возможно использование справочников карт OSM например.

**Comment by tebaly** [comment]
Ок. Давайте думать. Отложим до выкатки обновления интерфейса.

**Comment by mj4444ru** [comment]
Списки стран, городов, населенных пунктов на разных языках с контакта
Достаточно подробное деление по населённым пунктам, городам, но нет типа населённого пункта
https://habrahabr.ru/post/204840/

База OSM (48Gb в архиве, хз как с этим работать, но есть всё)
http://planet.openstreetmap.org

**Comment by tebaly** [comment]
аттач #412
