### ISSUE TITLE
Контакты станут одноразовыми и коротко живущими

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#401]
Формально, контакт станет нужен до обмена реальными контактами. Хоть это и не в наших интересах, но мы станем форсить переход к общению на другой сервис (соцсеть, мессенджер). Вероятно мы даже установим время жизни контакта ~15 дней. И, если вы не успели перевести общение на качественно новый уровень - селявиасталависта.
* автоудаление без возможности вернуться к беседе
* удаление по таймеру через 15 дней, без возможности "продлить"
* если "Вас" удалили - всё, считай заблокировали и вычеркнули из жизни.

Поэтому функция "заблокировать" канет в лету. Параллельное общение админов и дальнейшее использование сайта под большим вопросом. До тех пор, как мы окончательно не вырежем интерфейс безопасности из сайта. Тогда админка будет полностью независима от сайта.
* но сейчас, после обновы, настоящее положение дел станет сильно неудобным.
* крайне рекомендуем завести отдельную анкету для знакомства и общения.

![image](https://cloud.githubusercontent.com/assets/9466814/26552003/f5aef708-448d-11e7-9c22-e48110751d0a.png)

**Comment by mj4444ru** [comment]
Я совсем ничего не понял...

**Comment by tebaly** [comment]
attach #406

**Comment by tebaly** [comment]
- Новые знакомства удаляются через _15 дней_ после добавления
- Контакты, через _45 дней_ отсутствия активности - **имеются большие планы**
- Память о контактах Пользователя снижена до _90 дней_

## Большие планы

Форсить уход Пользователей с сайта. По второму пункту, фиксировать время жизни контакта. На данный момент, если вы общаетесь, вы можете делать это бесконечно долго. Но, в будущем, вероятно, это время станет конечным, и зафиксируется либо на 45/30 дней, либо как и знакомства на 15 дней. А знакомства в свою очередь снизятся до _7 дней_. Таким образом будет достигнута цель в снижении части Аудитории "просто поболтать"/"знакомства ради общения". 

Что-то похожее возможно и с самими Пользователями, но "элегантного" решения ещё не найдено...

### Про память

#212 про "право на забвение" для Знакомств. Суть в том, что если хранить информацию о статусе знакомства бесконечно, в случае "совершения ошибки" Пользователи не смогут "повторить попытку" - второго шанса просто нет. Это не всегда правильно, хотя и реализовано в таком виде почти на всех сайтах. Так как время жизни контактов стремится быть фиксированным, данные о статусе общения принимают вид бесконечного роста. С технической стороны это бессмысленная трата ресурсов. С другой, автоочистка старых статусов дает "второй шанс" тем, кому это нужно. Рано или поздно, надеюсь, всё это вольётся в общий тренд по проекту "всё временно".

**Comment by tebaly** [comment]
>  @tebaly абсолютно не понимает что людям нужно...
А тут как я вижу ещё и не особо хочет слушать этих людей ))) https://github.com/freedomsex/freedomsex/issues/406#issuecomment-305807034 от @mj4444ru 

> Ваша аудитория воспринимает сайт не как площадку для знакомства, а как площадку для общения. Тут никто не даёт никому реальных контактов. https://github.com/freedomsex/freedomsex/issues/406#issuecomment-305807767 от @monkklan 

> Вы не понимаете пожалуй самого главного, что люди не хотят выходить за рамки этого сайта, то есть переходить на общение в другом месте... https://github.com/freedomsex/freedomsex/issues/406#issuecomment-305838147 от @mj4444ru

## Unix-way

В общих словах, если кто-то с данной терминологией не знаком - программа должна выполнять одну задачу. Вторая часть этого выражения "и делать это хорошо" проистекает из первой. Философски, если вы сконцентрированы на одной задаче, вы выполните её лучше и качественнее, чем если вы пытаетесь выполнить несколько задач в рамках одного проекта.

## Не для людей

Следующее высказывание относится к приложениям: "Пишите приложения не для людей, а для конкретной ситуации." Ссылку и цитату уже найти не смогу, но смысл в том, что приложение должно преследовать цель помочь человеку в конкретной ситуации, в решении конкретной задачи. А в типологии _Unix-way_ - единственной. Приложение как сервис.

# Cервис быстрых знакомств

Приложение для ОДИНОКИХ парней и девушек, которые хотят ПОЗНАКОМИТЬСЯ максимально БЫСТРО. Любые иные кейсы отсекаются на уровне постановки задачи. Если нужно будет написать приложение для вирта - проект будет склонирован для достижения этих целей. Но, приложения для знакомств, и для вирта, и для простого общения, и для поиска принца на коне - в озвученной выше идеологии не будет. Это легко понять, если основываться на принципах мирового сообщества. Именно поэтому приложение "Погода" устанавливают чаще чем "Погода с чатом для друзей".

**Comment by inquisitor6789** [comment]
> Приложение для ОДИНОКИХ парней и девушек

чо за дискриминация?

**Comment by tebaly** [comment]
@inquisitor6789 вы про это?

Приложение для ОДИНОКИХ парней и **ОДИНОКИХ** девушек

**Comment by inquisitor6789** [comment]
я про все. Где справедливость в этом мире? А если женатому тройничок захотелось?

**Comment by tebaly** [comment]
Я пытаюсь что-то придумать для "групп", но пока ничего не получается.

> Это анкета моей жены, мы ищем пару для...

Стандартная ситуация для "такой части аудитории" в сегодняшних условиях расценивается (должна расцениваться) как грубое нарушение правил сайта - [Фейк, вымышленные данные, парень под видом девушки]

**Comment by tebaly** [comment]
## Иное: девушка ищет девушку. 
Что на самом деле - парень ищет девушку под анкетой девушки, которая ищет девушку - [Фейк, вымышленные данные, парень под видом девушки]. Но может и девушка... Как проверить?... Определить ресурс как **поиск девушек парнями** и никак иначе. Определенный выход из ситуации...

**Comment by inquisitor6789** [comment]
> Я пытаюсь что-то придумать для "групп", но пока ничего не получается.

а слабО их сделать третьим полом? кстати, это выход и для трансов....

**Comment by tebaly** [comment]
В сухом остатке
* Сервис _исключительно_ для гетеросексуальных пар
* Классический поиск парень -> девушку
    * Как _исключение_: девушка -> парень
* Не предназначен, но имеет возможность
    * Попробовать вирт - временно, условия ограниченно
    * Поиск пары, группы - условия ограничены

**Comment by tebaly** [comment]
@inquisitor6789 да, слабо. Так как в моем понимании
* Сервис для гетеросексуалов
* Сервис для геев, лесбиянок
* Сервис для трансгендеров, фетишистов
* Сервис для пар, свингеров, групп

Как минимум разные как по характеру, так и по структуре. Равноценно
* Сервис для общения
* Сервис для виртуального секса
* Сервис для поиска любви и семейного благополучия
* Сервис для быстрого поиска партнера

**Comment by inquisitor6789** [comment]
> Сервис для гетеросексуалов
Сервис для геев, лесбиянок
Сервис для трансгендеров, фетишистов
Сервис для пар, свингеров, групп

не вижу принципиальной разницы

**Comment by tebaly** [comment]
Геи и лесбиянки требуют **защиты** от гетеросексуалов/гомофобов. У нас нет такой защиты и реализовывать её сильно излишне. У нас есть защить гетеросексуалов от геев, и это нормально. Когда гей пишет гомофобу - это ненормально, так как оба испытают дискомфорт и могут быть оскорблены сложившимся общением.

Для пар и трансгендеров нормально заводить анкеты другого пола. Потенциальному собеседнику важно знать с кем он общается, с парнем или девушкой. Поэтому запрещающего правила на ведение одной анкеты парнем и девушкой [парнем, девушкой и парнкем], [тремя девушками] и так далее, быть не должно в принципе. А оно у нас не только есть, а взято в абсолют.

**Comment by tebaly** [comment]
@inquisitor6789 ... _не вижу принципиальной разницы_
У них у всех абсолютно разное отношение к сексу. А также есть различия в характере ведения диалога и общения. Что требует разного рода "защиты" Пользователей каждого сервиса.

Я над этой проблемой ломаю голову уже несколько лет, и ничего не получается. Единственный выход - разделить/клонировать сервис на полностью независимые клоны (вместе с админкой). Открыть код всех сервисов, и пустить в открытое плавание :relaxed:

**Comment by inquisitor6789** [comment]
имхо со всеми этими нововведениями у нас нормальных людей не останется. Будут тролли-проститутки-малолетки. Посмотрите сейчас на список блокировок - он не бывает пустым и там регулярно больше 20 кандидатов. Я даже свежих заявок не вижу.
Мое имхо, что надо с одной стороны ужесточать правила поведения (даже допустим время жизни анкет/знакомств/сообщений и т.п.), но с другой стороны и смягчать что-то. Ведь если ограничиться только знакомствами гетероорриентированных особей, со сроком жизни анкеты 3 дня ( :-D больше для знакомства и не надо), то есть очень хороший шанс растерять всю аудиторию.
И если уж идти этим путем, то в итоге окажемся подобием доски объявлений где все будут спамить всем.

**Comment by inquisitor6789** [comment]
> У них у всех абсолютно разное отношение к сексу. А также есть различия в характере ведения диалога и общения. Что требует разного рода "защиты" Пользователей каждого сервиса.

наблюдая тут за всякими забавными экземплярами я понял одно - если человек адекватный и его цель совпадает с целью ресурса, то он и общается адекватно. Если же персонаж неадекват, то это никаким сервисом не исправишь

**Comment by tebaly** [comment]
> где все будут спамить всем.
Спамить не получается. Спама ссылками нет уже **более пяти лет**. Проблема со спамом номера телефона **решена** месяц назад, и не пока ещё не повторилась. Над спамом _логинов соцсетей_ уже есть решение, но атаки как таковой ещё нету.

## Что будут спамить? "Приветы"?.. 
Зайдите с филосовского входа. На сегодняшний день, массовая рассылка "Приветов" это устоявшийся способ знакомства на сайтах и соответствующих сервисах. Бороться с этим, всё равно что направлять струю против ветра. 

В таком случае, весьма информативна бала бы ваша полная версия "идеального" знакомства в интернете. Возможно алгоритм поиска партнера с технической стороны.

**Comment by inquisitor6789** [comment]
> Возможно алгоритм поиска партнера с технической стороны.

для этого есть одно условие  - то, что написано в анкете (кого ищут, желания... эти параметры не должны быть пустыми) должно соответствовать реалиям. На основе этих данных можно уже делать кое-какие выводы. Например, если что-то не совпадает, то эти сообщения можно "поместить вниз списка" (сделать менее заметными). Это как пример.
Если же заполнение анкет оставить как сейчас, то только бигдата с нейросетью помогут отсеить всякий шлак

**Comment by tebaly** [comment]
И, если вы не любите БДСМ, это вовсе не значит, что его не люблю я. Но, как же тогда при таких моих взглядах, у нас на проекте "преследуется" и "имеет последствия" употребление оскорблений и насилия? Оставим геев и вирт, но выпилим БДСМ?.. несправедливо же.. 
* Будем колдовать со статусами анкет в зависимости от опций вирт/бдсм
* Можно, сложно, но зачем...

**Comment by tebaly** [comment]
`только бигдата с нейросетью помогут отсеить всякий шлак`
* Люди как пользователи сайта - меньшее из того, чего я боюсь как разработчик проекта
* Боты, +ИИ - с их приходим станет ещё веселее :dizzy_face:

**Comment by inquisitor6789** [comment]
некорректный пример. Если у меня в желаниях не указано БДСМ, то мне он как минимум не интересен. Но никто не мешает мне предложить поучаствовать в соответствующих развлечениях. Но делать это надо корректно. Как минимум уважая мнение собеседника. Все эти "привет сучка", "давай я тебя выебу/выпорю как шлюху" к БДСМ не имеют никакого отношения. Это просто оскорбление. Да и Вы про него мало что знаете, если приводите такие примеры.
С моей т.з. проблема в том, что многие "чоткие пацанчеги"воспринимают этот ресурс как сборище бесплатных шлюх, готовых прыгнуть в койку по первому зову.

**Comment by inquisitor6789** [comment]
> Люди как пользователи сайта - меньшее из того

ну да, чего их бояться. Зайдут на пару часов, наструт в камментах и свалят в даль. Чо их бояться. Только из-за таких портится репутация (если это важно для ресурса; в чем я уже сомневаюсь)

**Comment by tebaly** [comment]
> @inquisitor6789 Будут тролли-проститутки-малолетки. Посмотрите сейчас на список блокировок - он не бывает пустым и там регулярно больше 20 кандидатов. Я даже свежих заявок не вижу.

Правила просто будут конкретизироваться. Сервис будет развиваться по намеченным планам. А вот по части ускорения блокировок и изменения их механизма мы с вами уже договорились, что я приложу все усилия, чтобы максимально это дело ускорить и упростить. И задействовать блокировку по ключам и скрытым идентификаторам - обычных троллей-фейков и тому подобный шлак эти нововведения выкосят накорню за неделю-две. Поверьте мне

**Comment by tebaly** [comment]
@inquisitor6789 диалог, это всегда хорошо. Но вы сильно перетягиваете в сторону абстракции
* Чувствительность СБ сейчас свыше [ 1:1.000.000 ] - это кратно больше чем нужно
    * Я не уверен что подобные результаты есть в реализациях СБ иных крупных(-еших) проектов
* За сутки фиксируется ~30 заблокированных жалоб
    * Отправляется по проекту в сутки до 30.000 раз больше сообщений (количество жалоб умножить на 30 тысяч)

Ускорим блокировки, применим автоматический бан по ключам - и список активных заявок на блокирование анкеты просто будет пустым...

**Comment by tebaly** [comment]
>  то, что написано в анкете (кого ищут, желания... эти параметры не должны быть пустыми) должно соответствовать реалиям. На основе этих данных можно уже делать кое-какие выводы. Например, если что-то не совпадает, то эти сообщения можно "поместить вниз списка" (сделать менее заметными). Это как пример.

Просто лет семь назад у меня сложилось впечатление, что _"Анкеты никто не читает"_. Из этого мнения родились требования в реализации проекта: 
- Отсутствует необходимость заполнять анкету (никто же не смотрит)
- Жэсточайше убран шаг просмотра анкеты. 
    - Пиши сообщения сразу
    - Просмотр анкеты как опция

В данном ключе `эти параметры не должны быть пустыми` конфликтует с архитектурой всего проекта. А на основе неполных данных делать кое-какие выводы невозможно. Это равносильно сложившейся ситуации вокруг "Вирт секс". Опция есть, но её далеко не все указывают. И указывают кому не интересен, и не указывают кому интересен. И даже города свои "возвели"...

---

> Если же заполнение анкет оставить как сейчас...

Оно останется таким, это "фишка" всего проекта в целом. Сейчас в планах просто вышести за скобки (по умолчанию) реальность, гетеросексуальность и единообразие поиска (парень -> девушку).

### Часть два

> Но никто не мешает мне предложить поучаствовать в соответствующих развлечениях. Но делать это надо корректно. Как минимум уважая мнение собеседника. 

Так вот в случае "необязательности" заполнения анкеты, единственное что остается - писать всем подряд. Как вы выразились, спамить. Это и происходит прямо сейчас с виртом, и "бдсм" 

> Все эти "привет сучка", "давай я тебя выебу/выпорю как шлюху" к БДСМ не имеют никакого отношения. Это просто оскорбление. 

Раскройте пожалуйста смысл вашего видения б**Д**см, в части **Д**оминирования (унижения) партнера. На сколько я просвещён, БДСМ - это как минимум четыре ипостаси, далеко не всегда взаимосвязанных. И часто конкретному человеку нравится что-то одно. Только вот проблема
* Связать или иначе ограничить движения через сервис не получится
* Причинить боль собеседнику, применить физическую грубость - тоже невозможно
    * Равно как и испытать боль, полученную от партнера

Остается только **Д** - а как бы вы унижали собеседника, будь вы поклонником данной веры? Как бы вы "корректно предлагали" потенциальной подчиненной? И если у меня в этом пробел - нуачите меня, я буду вашим самым послушным и покорным учеником сегодня :books:

---

> С моей т.з. проблема в том, что многие "чоткие пацанчеги"воспринимают этот ресурс как сборище бесплатных шлюх, готовых прыгнуть в койку по первому зову.

А шо поделать. В такое время живем...

**Comment by inquisitor6789** [comment]
охх..... как многа букофф...
## часть раз

> анкеты никто не читает

так если сервис будет развиваться из этого посыла, то может стоит отменить пункты правил, касаемых спама, рассылки фото, посылов нахуй и т.п? Ведь большинство конфликтных ситуаций возникает как раз по этой причине.
Ну и до кучи разрешить девушкам с пониженной моральной составляющей рекламировать свои услуги. Кстати, за это можно с них бабосики рубить :-)
Короче, хозяин барин. Но мне кажется, что будет только хуже.

## часть два

Для непросвещенных - в бдсм основополагающим принципом этого движения является БРД - безопасность, разумность, добровольность. Другими словами - без согласия второй стороны никакие действия не должны совершаться. Таким образом все равно в какой ипостаси будет реализовано желание пользователя осуществить свои бдсм-ные наклонности (вирт или реал). Главное, что это должно быть добровольно с обеих сторон, А всякие "Привет. отсоси мне сучка" к бдсм не имеют никакого отношения. Это просто быдло, скот.

> Как бы вы "корректно предлагали" потенциальной подчиненной?

в процессе НОРМАЛЬНОГО общения выясняются пристрастия. А дальше - только после получения согласия на такое обращение.

**Comment by tebaly** [comment]
> так если сервис будет развиваться из этого посыла -> то может стоит отменить пункты правил

Неасилил. Хде связь? Чтение анкеты в воем мозге не увязывается с правилами отправки сообщений. Проект постепенно ~~разваливается~~ развивается на три глобальных сервиса ПОИСК/КОНТАКТЫ/СООБЩЕНИЯ. И они как бы изолированны друг от друга, и правила для них не пересекаются в идеале. Я имел данные анкеты, вы подтасовываете сюда содержание сообщений. А оно не связано.

> в процессе НОРМАЛЬНОГО общения выясняются пристрастия.

Назовите уровень ощущаемой вами абстракции от 0 до 10 после прочтения этой фразы. 
По моим ощущениям 9+ 

Среднестатистический пользователь сервиса знакомств ведет себя как классический спамер
* Одно/первое/единственное сообщение
* Отправил и забыл

А так как невозможно совместить три названных вами составляющих в одно целое, то отправляется сразу всё, пакетом...
* Приветствие
* При возможности запрос взаимодействия/интересов
* Действие

В итоге `привет сучка. давай я тебя выпорю как шлюху` - и ничего странного в этом нет. 
Я так думаю

**Comment by inquisitor6789** [comment]
> Чтение анкеты в воем мозге не увязывается с правилами отправки сообщений. 

если в желаниях у человека написано, что он любит унижение, то с натяжкой можно допустить, что к нему будут обращаться в уничижительной форме.

Блин, вы понимаете, что 

> Приветствие
При возможности запрос взаимодействия/интересов
Действие
В итоге привет сучка. давай я тебя выпорю как шлюху - и ничего странного в этом нет.

является несколько неприемлемым с точки зрения адекватного среднестатистического человека?
Собственно из-за этого столько негатива со стороны женского пола. Я полагаю, что тех, кому приемлемо такое обращение исчезающе мало.

> Назовите уровень ощущаемой вами абстракции от 0 до 10 после прочтения этой фразы.

1

**Comment by tebaly** [comment]
> является несколько неприемлемым с точки зрения адекватного среднестатистического человека?

Да кто же спорит то. Но есть такие процессы, как ветер. И как вы не тужтесь, сса против него, сухим не будете :stuck_out_tongue: **Дичайшее соотношение полов в сервисе просто вынуждает к этому**. И даже недавних адекватов сильно ломает.

**Comment by tebaly** [comment]
> Собственно из-за этого столько негатива со стороны женского пола.

А может на волне трансформаций _выиплить_ "поддержку" БДСМ общения и всех быдло-альфа-самцов. Просто
* Запретив любые оскорбления/унижения/хамство в начале знакомства?)

**Comment by inquisitor6789** [comment]
> Запретив любые оскорбления/унижения/хамство в начале знакомства?)

а разве это не предполагается по умолчанию? Да и почему только в начале? Без согласия собеседника такое поведение должно наказываться.

**Comment by tebaly** [comment]
@inquisitor6789 - всё просто. Вы должны хорошо помнить, на сколько сильно я отстаивал отсутствие цензуры на проекте. Это было до того. Так как раньше была идея и стремления собрать всех и вся на одном ресурсе.

Идея казалась сложной, но возможной. А вот теперь стало ясно, что этого делать просто не нужно. И сегодня мы с вами обсуждаем уже "срез" лишних слоев аудитории с технической точки зрения.
1. Только для гетеро знакомств
2. Не для БДСМ (оскорблений)

То есть, сейчас попробуем отсечь вовсе не мат и богохульство, а тех кто пишет
* Гадости вместо приветов или вместе с приветом
* Целенаправленно оскорбляет

**Comment by inquisitor6789** [comment]
ох что будет....
Я, в принципе, тоже за жестокое наказание таких персонажей. 
Если все таки введете это, то давайте хотя бы большими красными буквами всем напишем, что за оскорбления (особенно в начале диалога) будут применяться жестокие кары

**Comment by tebaly** [comment]
Да. Уже думаю как...

**Comment by inquisitor6789** [comment]
Юля не может?

**Comment by tebaly** [comment]
Юля R.I.P.

**Comment by inquisitor6789** [comment]
может реинкарнировать ее не на долго?

**Comment by tebaly** [comment]
Будем колдовать с "ботами" и "уведомлениями" вместо Юлии, а вопрос решим несколько иначе.

**Comment by tebaly** [comment]
В новом релизе **запрет БДСМ общения**. 
Информация будет доведена до всех старых пользователей огромным баннером на главной.

**Comment by tebaly** [comment]
Часть темы про БДСМ реализована. Часть про удаление контактов реализована, про "форсить уход" - заморожена. #510
