### ISSUE TITLE
6 % сообщений достигают ответа.

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#402]
[moved] @Fenslau

> в % перевести можно
> у тебя 6 % сообщений достигают ответа.
> У меня - 3 ))
> Сука, надо нагонять )
> 
> ууууу..... боюсь эти цифры будут стремиться к нулю....
> кстати, это уже есть, только видно это в профиле 
> `Предложено 3815, принято 224 знакомств `

> Г.
> Максимальная конверсия (для парней).
> И полезно и для девочек информативно.
> у тебя 15,6
> у меня: 32,8
> А для девочек так: отношение тех, с кем поддержала диалог к количеству написавших.

Точно не считали, но есть данные по многим другим сервисам знакомств - там процент успеха не превышает 10%.

**Comment by mj4444ru** [comment]
@Fenslau, ты зарегистрируйся девушкой, подожди сутки и подумай на сколько бы сообщений ты смог ответить... 1% ???

По `Предложено 3815, принято 224` можно смотреть парень это или девушка под этой анкетой сидит, но больше ничего из этого не высчитаешь )))

**Comment by tebaly** [comment]
я хочу дать возможность парням без напряга отправлять по 300 сообщений в день)

**Comment by mj4444ru** [comment]
@tebaly, чёт мне кажется ни девушки, ни парни этому не будут рады...

**Comment by Fenslau** [comment]
да не, ну э
то же мы пьяные были и неправильно все посчитали, не на то поделили.
Короче былло бы интересно узнать, какова у кого конверсия - предложения знакомства/ответы на них.
Но сейчас это невозможно.
Потому что показывается только то, сколько ты предложил. А сколько ответов было - нини. 
Есть принятые знакомства, но это не то, это если мне мол кто то писал сам. Вот я и подшутил над Серегой, мол, ему то больше пишут всякие там юзерши)) Но это не значит, что ему пишут именно в ответ.

**Comment by tebaly** [comment]
Ой. Эти цифры очень специфичны)) мы их не считали ещё
сервис такой же как и везде, отличия в статистике мало заметны  - а то что заметно мало зависит от отличия сервиса от других. больше влияют технические моменты типа вчерашней обновы...

**Comment by tebaly** [comment]
Раз посчитано неверно, уберем под ковер
