### ISSUE TITLE
Придумать и задокументировать в BPMN новую систему администрирования-модерирования

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#403]
[moved] @inquisitor6789 

вот вам задание - придумать и задокументировать в BPMN новую систему администрирования-модерирования. Документация должна включать в себя следующие артефакты:
- общее описание решаемой проблемы
- описание иерархии административного ресурса (если будет такая иерархия)
- описание процессов принятия решений
- описание процессов решения конфликтов
- описание решения по проблеме бездействия админов (опционально)
Результат в свою репу на гите выкладывайте, а мы посмотрим

**Comment by mj4444ru** [comment]
Это неправильный подход мне кажется...

Для начала надо вместе определится со списком реальных проблем, а уже потом думать как их решать...

Текущая система не решает реальные проблемы девушек...

**Comment by mj4444ru** [comment]
PS: я думаю нужно мнение девушек и желательно с городов разных калибров...

**Comment by tebaly** [comment]
Вам для этого нужно открыть доступ к сайту?))

**Comment by mj4444ru** [comment]
![default](https://cloud.githubusercontent.com/assets/9354685/26724837/f07ea678-47b4-11e7-8b19-c90e33b4546e.jpg)

А если честно, то нет желания заниматься опросами... 
Своё мнение за что надо наказывать я уже высказывал (если коротко - за любое неуважение чужих предпочтений), а как это реализовать описывал подробно в других темах #2 и наверно другие...

Что касается интерфейса, предлагаю сделать ленту событий для админов, что бы всё было в одном месте, а не как сейчас бегать по более чем десятку страниц...
Если лента заинтересует, могу подумать подробности её реализации... Мне лень просто так думать если это никому не нужно...

**Comment by mj4444ru** [comment]
**Что касается интерфейса**, предлагаю сделать ленту событий для админов, что бы всё было в одном месте, а не как сейчас бегать по более чем десятку страниц...
Если лента заинтересует, могу подумать подробности её реализации... Мне лень просто так думать если это никому не нужно...

**Comment by tebaly** [comment]
#380

**Comment by tebaly** [comment]
@mj4444ru - добрый вечер :copyright: Вы куда-то пропали насовсем...

> Что касается интерфейса, предлагаю сделать ленту событий для админов, что бы всё было в одном месте, а не как сейчас бегать по более чем десятку страниц...
Если лента заинтересует, могу подумать подробности её реализации... Мне лень просто так думать если это никому не нужно...

Нужно. Расскажите как бы вы это делали :blush:
