### ISSUE TITLE
После обновления перестали открываться фото с любых устройств

### ISSUE THREAD

**Issue by monkklan** [freedomsex/freedomsex#404]
Собственно сабж

**Comment by monkklan** [comment]
Так же не приходят оповещения о новых сообщениях, тоже на всех устройствах, с пк тоже проверял

**Comment by tebaly** [comment]
исправляем

**Comment by tebaly** [comment]
Исправлено. 1 минута на обновление

**Comment by monkklan** [comment]
а сообщения? нет оповещений совсем, невозможно общаться

**Comment by tebaly** [comment]
оповещения будут. там с самими списками косяки сейчас вроде как..
