### ISSUE TITLE
верните всё обратно

### ISSUE THREAD

**Issue by AndreyRAY** [freedomsex/freedomsex#405]
Чё за ЧУШЬ сделали ??? я теперь найти не могу контакт с которым ООООЧЕНЬ давно общаюсь. просто среди шквала сообщений этот контакт затерялся. я не вижу теперь, в сообщениях. ПРОЧИТАЛИ ЛИ МОЁ СООБЩЕНИЕ, в ОНЛАЙНЕ ЛИ этот человек! не могу выделить в отдельную папку группу контактов, как раньше. ВЕРНИТЕ ВСЁ ОБРАТНО! ЭТО ОБНОВЛЕНИЕ ГОВНО!!!!!!!!!!!!!!!!!!

**Comment by AndreyRAY** [comment]
Чё за ЧУШЬ сделали ??? я теперь найти не могу контакт с которым ООООЧЕНЬ давно общаюсь. просто среди шквала сообщений этот контакт затерялся. я не вижу теперь, в сообщениях. ПРОЧИТАЛИ ЛИ МОЁ СООБЩЕНИЕ, в ОНЛАЙНЕ ЛИ этот человек! не могу выделить в отдельную папку группу контактов, как раньше. ВЕРНИТЕ ВСЁ ОБРАТНО! ЭТО ОБНОВЛЕНИЕ ГОВНО!!!!!!!!!!!!!!!!!!

**Comment by tebaly** [comment]
Да ладно вам. Поправим и улучшим. Возвращаться не к чему.

![image](https://cloud.githubusercontent.com/assets/9466814/26670683/493b4e60-46bb-11e7-883d-a075c44dcdd8.png)

**Comment by Fenslau** [comment]
нотификации и сортировка контактов по последнему сообщению в списке треба! )

**Comment by tebaly** [comment]
@Fenslau - контактов теперь офисално 2 списка. Вы о каком?)

**Comment by tebaly** [comment]
Отзыв конечно важный.. прикрепим к основной теме #406
