### ISSUE TITLE
Снова обнова (контакты)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#406]
Пугали уже несколько месяцев осознанно, потому что знали что будет пи*дец.. И он настал
* Отвалился гиперчат - его не будет в старом исполнении, его нужно полностью переписать
* Отвалились уведомления вместе с гиперчатом, это норма, оно же взаимосвязаны
* Там же фитча "ответить всем", "сейчас на сайте" и так далее

Это всё нужно по новой писать и это много времени, но всё вернется. 100%

Уведомления в "шапке" о новом сообщении заработает как надо до вечера. Фотки/аватарки в контактах вероятно появятся.. Остальное смутно)) Из-за постоянных атак на сервис не осталось возможности спокойно дописывать до конца, пришлось выкатывать то что есть.

---
Сейчас имеем два списка контактов
1. "Заявки в друзья", они же "новые пары", они же у нас _Знакомства_ (пассивные контакты)
2. "Активные контакты" - "Друзья", они же у нас _Общение_

Сортировка - в первом случае без автоматического поднятия в списке, во втором с автоматическим поднятием в топ по последнему сообщению. Высока вероятность того, что отметки "Отправлено/Новое/Прочитано" у нас не станет(вроде как в Тиндере этого нет)

На сегодня хотелось бы прежде всего отладить "потоки" сообщений/контактов, чтобы сам процесс общения/знакомства не был нарушен, остальное поправим достаточно быстро.

**Comment by mj4444ru** [comment]
Сама по себе идея интересная разделить новые и старые, но реализация какая то извращённая...

**Comment by monkklan** [comment]
ага, реально очень неудобно стало

**Comment by tebaly** [comment]
Ничего нового)) Всё как у всех. @mj4444ru расскажите нам про ваши любимые извращения, чтобы иметь представления о реализации контактов)

**Comment by mj4444ru** [comment]
я бы извратился так...
![2017-06-01 20 17 28](https://cloud.githubusercontent.com/assets/9354685/26686957/f700ca88-4707-11e7-87a6-4c520088d19b.png)

**Comment by mj4444ru** [comment]
```sql
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`dialog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dialog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `second_user_id` INT NOT NULL,
  `type` ENUM('req','unread','read','ban') NOT NULL,
  `favorite` TINYINT NOT NULL,
  `unread_count` TINYINT NOT NULL,
  `text` VARCHAR(32) NOT NULL,
  `private_comment` VARCHAR(200) NULL,
  `created_at` INT NOT NULL,
  `updated_at` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`user_id` ASC, `type` ASC, `favorite` ASC, `updated_at` ASC),
  INDEX `index3` (`second_user_id` ASC),
  CONSTRAINT `fk_dialog_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dialog_2`
    FOREIGN KEY (`second_user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `second_user_id` INT NOT NULL,
  `related_message_id` INT NULL,
  `type` ENUM('in','out','system','alert','photo') NOT NULL,
  `read` ENUM('Y','N') NOT NULL,
  `text` TEXT NOT NULL,
  `created_at` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`user_id` ASC, `id` ASC),
  INDEX `index3` (`second_user_id` ASC),
  INDEX `index4` (`related_message_id` ASC),
  INDEX `index5` (`created_at` ASC),
  CONSTRAINT `fk_message_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_2`
    FOREIGN KEY (`second_user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_3`
    FOREIGN KEY (`related_message_id`)
    REFERENCES `mydb`.`message` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
```

**Comment by tebaly** [comment]
![risovach ru 3](https://cloud.githubusercontent.com/assets/9466814/26687549/ab93616e-46f8-11e7-9869-81cdfe94d976.jpg)

Красиво конечно, но как быть, если это нужно впихуярить в три _независимых_ микросервиса?

**Comment by mj4444ru** [comment]
> нужно впихуярить в три независимых микросервиса?

это как?

можно убрать связи, будет 3 отдельных микросервиса...

можно подеоить dialog на dialog('unread','read','ban') и request ('req'), вот вам 4 сервиса

если нету диалога, создаём реквест... если в бане, диалог не отображается, но есть и по этому реквест второй раз не создастся... но не вижу особого смысла делить...

если организовать правильное кеширование (мемкеш), мне кажется не так уж и много ресурсов это всё займёт...

а поделитесь секретом какой у вас размер базы в гб (сама база и отдельно индексы)... можно на почту...

**Comment by tebaly** [comment]
Оффтопите)) Да, именно. Убрать связи и разнести на три сервера и при возможности на три независимых БД. Для каждого свой АПИ и ... это не просто :sweat:

Ваша схема не тянет на 100К ))

**Comment by mj4444ru** [comment]
ещё как тянет... я вам на почту написал...

**Comment by Fenslau** [comment]
пользователь негодует. (как и всегда) - говорят мол шибко непривычно.
Нет обновлений в этих ваших списках "общение", или как там их - не сортируется ни пса!
Потестить не с кем, Юльки то нет. У меня там последние контакты, которые когда то были с ними диалоги - и они заморожены. Новым я пишу - вроде появляются там, но только если отвечают (кстати, может быть так оно и правильно). Пока ничо не понятно. Если отвечает пользователь из старых контактов, то он там не появляется (в этом вашем списке "общение"" - хорошо если он там вверху есть, а если нет, то все? Хер?

**Comment by tebaly** [comment]
Сортировка (всплытие) исправлено. 
Статус "непрочитано/новое" работает.

![image](https://cloud.githubusercontent.com/assets/9466814/26723073/68460030-479b-11e7-9771-768bdd40a903.png)

**Comment by SVIT-Lanka** [comment]
Доброго дня! Пользователь желает видеть, кто из его контактов он-лайн, а кто нет. Добавьте рыжий кружочек рядом с именем во вкладках Общение и Знакомства) Благодарю)

**Comment by tebaly** [comment]
Благодарствую за отзыв. Эта опция под большим вопросом сейчас. Опция всё реже встречается в мегапопулярных мессенджерах. Отсутствует например в:
* WatsApp
* Viber
* Tinder

Этому есть объяснение - относительная сложность в реализации и постоянной поддержки актуальности данных против важности и необходимости:
* Если вам есть что написать - пишите. Это не жизнь. Вам, чтобы написать, вовсе не нужно находиться перед собеседником и смотреть ему в глаза.
* У нас не "общалка/болталка" - мы далеко от ICQ-шных фишечек. Знакомьтесь, обменивайтесь _реальными_ контактами и вперед, на свидание :relaxed:

**Comment by mj4444ru** [comment]
Как мне уже говорили некоторые девушки, @tebaly абсолютно не понимает что людям нужно...
А тут как я вижу ещё и не особо хочет слушать этих людей )))

**Comment by monkklan** [comment]
Воот, насколько я понял, вы видите функцию сайта именно в этом, и это в общем-то понятно. Тут другая фишка. Ваша аудитория воспринимает сайт не как площадку для знакомства, а как площадку для общения. Тут никто не даёт никому реальных контактов. Там всё поломано не в плане технической реализации, а в плане социальной инженерии. А заводить левые вконтактики и скайпы постоянно всем в лом. Особенно девочкам. А ведь ресурс на них держется.

**Comment by mj4444ru** [comment]
> относительная сложность в реализации...
За эту фишку может отвечать например nodejs...
Или функционал на php без фреймворка (неоправданно грузить весь функционал фреймворка ради 1 ajax запроса к базе или мемкеш серверу)...

**Comment by mj4444ru** [comment]
> относительная сложность в реализации...

За эту фишку может отвечать например nodejs...
Или функционал на php без фреймворка (неоправданно грузить весь функционал фреймворка ради 1 ajax запроса к базе или мемкеш серверу)...

И вообще отдавать статусы контактов аяксом не гуд... Это гарантированный дополнительный вопрос, который нет особого смысла делать отдельно... Лучше сразу на сервере его сделать и сразу отдать с другими аякс или не аякс данными...

**Comment by tebaly** [comment]
@mj4444ru - я когда про 100К говорил, это про запрошенный гонорар было.

> Пользователь желает видеть, кто из его контактов он-лайн, а кто нет.

К базе не получится. Если присмотреться, то видно, что речь идет о списке контактов. Составим запрос к БД и посмотрим на его уникальность - запрашиваем 10 контактов. Берем выборку в 1000 пользователей. Сколько уникальных запросов имеем? 
* Правильно. Все 1000 запросов уникальны. А через 5 минут?
     * Правильно. Снова 1000 уникальных запросов...
* А если хотим точное время визита - 100% уникальных запросов каждую секунду

Только мемкеш и спасет... Но - вебсервер сам по себе всё это уникальное ... не закэширует ну никакушечки :) 

---

Нет смысла продолжать. В реализации нет проблемы(это уже было реализовано). Почему этого нет у тех, у кого технических ограничений нет в принципе - WatsApp?

**Comment by mj4444ru** [comment]
> Почему этого нет у тех, у кого технических ограничений нет в принципе - WatsApp?

Ок, тогда ждём когда вы уберёте и поиск новых контактов... Его же нет в ватсапе ))) Будем знакомиться через объявления по личному номеру (айдишнику)...

**Comment by tebaly** [comment]
> Ваша аудитория воспринимает сайт не как площадку для знакомства, а как площадку для общения. Тут никто не даёт никому реальных контактов. 

Во первых. Каждому своё. Вы вероятно забываете, но в интернете сотни сайтов, где можно
* Публично загрузить левых фоток тонну. И х*и и сиськи, и даже фотохронику своих побед
* Писать что угодно - вот прямо всё что хочешь. Вот реально можно всё!
* Давать левые контакты, просить оплату и многое многое

Зачем? Зачем делать точно такое же? Вы говорите "поболтать"... Ну и пусть наши с вами взгляды расходятся)) Просто у нас будет сервис знакомств. А всех кто знакомиться не хочет, и не захочит уйти - мы выкинем сами рано или поздно :sweat_smile:

**Comment by mj4444ru** [comment]
Вы не понимаете пожалуй самого главного, что люди не хотят выходить за рамки этого сайта, то есть переходить на общение в другом месте...
PS: Это не я сказал...

**Comment by tebaly** [comment]
Тррр... За последние 10 лет в обществе определился четкий тренд. И это точно не "посиделки в чате" [точка]. И обсуждение в данном направлении я продолжать не буду. :innocent:

**Comment by monkklan** [comment]
Кстати, вы будете смеяться, но аналогов вашему сайту нет)

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26735678/8df7d986-47cb-11e7-9e87-4088a0ab775d.png)

**Comment by Fenslau** [comment]
обратная связь с народом очень важна! )
В вк сотни и тысячи групп, которые задумывались как нечто оригинальное.! Но потом они реорганизовались в то, что больше нравится народу. 
Кстати, сир tebaly в чем-то прав. Многие именно так и используют сайт, приходят сюда время от времени чтобы найти любовника, потом пропадают, пока эта связь актуальна и возвращаются за новым. Я сужу по реальному общению, буквально вчера об этом говорили. Но многие также любят просто посидеть, подурачиться. Некоторые кстати и так и так любят, что уж тут говорить.
Блин, моя мысль вот в чем: Надо все категории пользователей учитывать, особенно, если они реальны и уже есть на сайте.
Кстати, а что за репрессии, за что мне скинули рейтинг до непривычных значений?))) 
Это всё потому что я чёрный, да?)))

**Comment by tebaly** [comment]
@Fenslau а вы черный? так надо вас вообще забанить :sweat_smile:

**Comment by Fenslau** [comment]
откуда только вы черпаете вдохновения для изменений? ))

**Comment by Fenslau** [comment]
Капеец, я вам завидую. Можете выбирать чо там кого и тп.
Мы то так не можем.У нас на сайте ток ветер дует холодный....

**Comment by tebaly** [comment]
@Fenslau - вы лично предлагали разделение на активный список и не очень активный

> Максимум бы я делал бы уведомление (и то ненавязчиво, раз в день, там), мол вам написало хх парней за сегодня, хотите посмотреть? Ну это на случай если ей скучно станет. 

https://github.com/freedomsex/freedomsex/issues/241#issuecomment-240924316

Собственно немного развил вашу идею и упростил для пользования. "Она" сейчас общается с теми кто в "Общении" а когда скучно, открывает "Знакомства". Всё как вы и хотели. Циферку "хх парней" добавим.

**Comment by Fenslau** [comment]
Слушайте, я даже хз. Тут такая тема короче:
Надо Серегу подтянуть сюда.
Пусть выскажет вое мнение

**Comment by SVIT-Lanka** [comment]
Доброго дня всем! Что хочу сказать... идея разделения на знакомства и общение очень даже отличная, особенно для девушек, которых просто заваливают сообщениями. Да, по-началу не удобно, не привычно, постоянно тянет вправо) но, как показывает практика, со всеми обновочками так сначала) А Пользователь так негодует, потому как багов много сразу вылезло. Доработаете и угомонятся, еще и благодарить будут)

**Comment by Fenslau** [comment]
Все пропало, господа. Новая девочка на гитхабе.

**Comment by Fenslau** [comment]
нифига не отличная (я оппонирую)! Раньше было лучше. заходишь в сообщения и сразу все понятно. Теперь же все непривычно. Главно непонятно на кой пес изменения, и так же все работало!

**Comment by SVIT-Lanka** [comment]
Джентельмены, ну если вы не возражаете, буду вставлять свои пять копеек иногда)

**Comment by SVIT-Lanka** [comment]
Да, раньше было привычно! Заходишь в сообщения, а там их 50... следующие... следующие... еще раз прокрутил... ах ну вот же тот человек,  которому хотела написать))) спасал, правда, список избранных)

**Comment by Fenslau** [comment]
да кто тут возражать будет, тут только сир tebaly и я. Ну лорд Сергей еще иногда заходит.

**Comment by Fenslau** [comment]
50? ох, ниху... Пардон.
Много. Теперь видимо они все в "знакомствах". Дык и чо принципиально поменялось?

**Comment by drvalera** [comment]
Так теперь с кем общаешься он висит в списке Общения, а не по всему списку ищешь, а то новые сообщения всегда забивали верх и с кем общаешься всегда было сложно найти, если не успел в Избранные закинуть

**Comment by inquisitor6789** [comment]
Блин, нельзя уже в отпуск уехать так начинают поминать в суе :-)
В понедельник ознакомилась со всем что вы тут наделали

**Comment by tebaly** [comment]
Серёга в отпуске пол сменил :flushed:

**Comment by inquisitor6789** [comment]
> Серёга в отпуске пол сменил 😳

да? я чего я тогда не в курсе?

**Comment by inquisitor6789** [comment]
короче, по факту использования нового интерфейса. Испытания проходили на хроме Версия 58.0.3029.110 (64-bit)
1. Мои первые сообщения зачастую не попадают ни в "общение", ни в "знакомства"
2. В "общение" мои первые сообщения попадают выборочно по совершенно не понятной мне логике.
3. не работает редактирование имени собеседника

Пока как-то так.....

**Comment by tebaly** [comment]
Оповещение наладим. Остальное вроде работает.

**Comment by tebaly** [comment]
прикрепляю #442
