### ISSUE TITLE
Фича "ответить всем" будет выпилена

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#407]
Таки пришло осознание, что даже если её кто-то и использовал, в самой фитче было много базовых противоречий. Например самые серьёзные
* девушек заваливают сообщениями и они не могут всем ответить физически
* если они ответили всем, то эти все "всплыли в списке контактов" отодвинув интересных собеседников
* подразумевалось использовать, чтобы "сократить" поток сообщений, но инструмент не сильно помогал. На ответ шли новые сообщения

В итоге его просто дискредитировали Нарушители, используя его для быстрой рассылки спам сообщений. Смысла в возобновлении фичи не видно. У девушек всегда есть собеседники, и когда нужно, они изучат список новых знакомств и ответят тому, кому повезёт. 
Далеко не всем.. очень очень далеко...

**Comment by tebaly** [comment]
аттач #406

**Comment by mj4444ru** [comment]
о боже, наконец то свершилось, вы это осознали )))

**Comment by mj4444ru** [comment]
я даже картинку нашёл 
![y9admzu3bts](https://cloud.githubusercontent.com/assets/9354685/26687740/f5eb37e4-4709-11e7-9ac6-3442878edaa2.jpg)

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26687934/e6dfcd1a-46f9-11e7-9a9d-958fde2497f3.png)
