### ISSUE TITLE
А я твой друг и не ипёт...

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#408]
Вобщем если отправить одно сообщение, попадаешь в Знакомства... Если отправить ещё одно сообщение, ты уже друган )))

#406

**Comment by mj4444ru** [comment]
#406

**Comment by tebaly** [comment]
Бывает)) исправим конечно

**Comment by tebaly** [comment]
Проверьте пожалуйста. Вроде сейчас норм работает
