### ISSUE TITLE
откуда берутся анкеты (много дней, мало статы):

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#409]
http://freedomsex.me/userinfo/profile/34535601
Это баг, фича или случайность?
анкете 24 дня  Предложено 0, принято 21 знакомств

**Comment by tebaly** [comment]
Что вы хотите видеть?))

**Comment by Fenslau** [comment]
вопрос не по существу.

**Comment by tebaly** [comment]
Тогда опишите существо более подробно. Ничеж не понятно, что вам нужно)

**Comment by mj4444ru** [comment]
Ну то что она сама ни кому не пишет это нормально (девушка же)...
То что принято 24 ноже норм, ибо в поиске по городу она не светится, а значит дебилов достающих меньше...
Ну как то так мне это видится, ничего необычного...
