### ISSUE TITLE
Кнопка "я модератор"

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#410]
В связи с изменениями в интерфейсе полагаю, что кнопку "я модератор" надо перенести в более доступное место. Сейчас чтобы зайти в модерилку мне надо совершить несколько лишних действий.
Предлагаю ее перенести куда-то рядом с анкетой.

**Comment by KILLER1974** [comment]
рядом с ваш логин

**Comment by tebaly** [comment]
туда то зачем :flushed:

**Comment by tebaly** [comment]
В диалоги вероятнее всего, и в просмотр анкеты.

**Comment by inquisitor6789** [comment]
не, в диалоги и в чужую анкету нафиг не надо
может лучше в свою?

**Comment by tebaly** [comment]
Вообще - в самое проходное место. И, там где будет больше мужчин. Почему? Потому как девушкам и на сообщения отвечать времени не хватает. А парни, когда пишут, а им не отвечают, например, испытывают желание "чем-то отвлечься" - тем паче, что кредиты способствуют более "простому" общению. А общение у нас именно в диалогах и просмотрах профилей... В настройки заходят редко.

**Comment by KILLER1974** [comment]
рядом с входом при входе - помоему самое удобное место

**Comment by tebaly** [comment]
Обновлено #451

**Comment by tebaly** [comment]
Быстрый патч
