### ISSUE TITLE
Badoo сменили логотип. Совпадение?)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#411]
Было
![image](https://cloud.githubusercontent.com/assets/9466814/26820647/2f72c748-4aac-11e7-8f7a-e60aa481f0d6.png)

Стало
![image](https://cloud.githubusercontent.com/assets/9466814/26820710/730a189e-4aac-11e7-8d3c-898020d20294.png)

Наш для закладок
![apple-touch-icon](https://cloud.githubusercontent.com/assets/9466814/26820739/958a8e76-4aac-11e7-8a93-475fea021409.png)

Сердечки повсюду))

**Comment by mj4444ru** [comment]
Не льстите себе, сейчас многие освежают иконки... Просто до баду тренд долго шёл... Ну или долго думали на что сменить... Иконка в стиле Windows mobile или в стиле новых иконок Samsung...
Хороший ход...

**Comment by tebaly** [comment]
Подождем, когда они разделят сообщения на два списка как у нас))
