### ISSUE TITLE
Поиск на главной странице

### ISSUE THREAD

**Issue by Neaskil** [freedomsex/freedomsex#412]
День добрый 
Скажите будет ли доработан поиск ?
В настоящий момент выводится выборка в зависимости от 4х параметров указанных в форме.
Без учета того кого ищут пользователи попавшие в выборку.

Иными словами 
В базе у пользователя установлено что пользователь мужчина возраст 30 
ищет он например девушку от 25-30 

В выборке сейчас будет выдача всех девушек кто попадет в 25-30 независимо от того кого они ищут сами. 
Т.е. будут и те кто ищет девушку и те кто ищет другой возраст...

**Comment by mj4444ru** [comment]
нет, не будет... большенство не в курсе кого они там вообще ищут...

**Comment by Neaskil** [comment]
Ну вроде как те кто не в курсе наверное все таки не ставят ограничение по возрасту, полу и городу.

Непонятно зачем выдавать в общую выборку для пользователя тех кто явно поставил себе такое ограничение. Чтобы их задалбывали приглашениями и вопросами? 
Глубинный смысл показать как много народа в онлайне ?

**Comment by tebaly** [comment]
> Глубинный смысл показать как много народа в онлайне ?

Таки раскусили вселенский замысел. Изначально на проекте было мало народу, и все хотели онлайн общения. При этом больше всего возмущались как раз те, что ставили фильтр "только девушку и только 21 год" - разумеется не в каждом городе результат был в принципе. 

Мы работаем над этим...

**Comment by Neaskil** [comment]
Тогда это проще сделать отдельной галкой аля "только онлайн" на странице поиска
И назвать ее типа "Ищут вас" отключенной по умолчанию. Те кому нужно поставят себе.
А в запросе это по моему обычный подзапрос.

**Comment by Neaskil** [comment]
или в настройках формы "Кого вы ищете?" что в принципе даже логичней

**Comment by mj4444ru** [comment]
Тут так всё запутано что люди сами не понимают что у них в анкете и кого они тут по версии сайта ищут... Игнорировать пожелания единственный выход из ситуации...

**Comment by Neaskil** [comment]
Ну хоть фильтр по полу сделайте. Хрен с ним с возрастом как грится. 
Зачем в выдаче куча девушек которые ищут девушек ?

**Comment by tebaly** [comment]
mj4444ru - это тролль, он ничего сделать в принципе не может. Он может только вводить в заблуждение. И не имеет никакого отношения к разработчикам :stuck_out_tongue:

**Comment by mj4444ru** [comment]
tebaly - это разработчик, он многое может сделать. Однако он почему то только вводит в заблуждение пользователей. И не имеет никакого отношения к пользователям :stuck_out_tongue:

**Comment by tebaly** [comment]
# Ваша лодка готова, капитан*
![image](https://user-images.githubusercontent.com/9466814/26968114-7e039aea-4d09-11e7-9cc5-f3ce5b677273.png)
в точном звании могу ошибаться))

**Comment by mj4444ru** [comment]
С такой девушкой и такая яхта сойдёт...

**Comment by tebaly** [comment]
> Скажите будет ли доработан поиск ?

Поиск доработан **не будет** как минимум год-два на перспективу
* Сайт ищет всех, кто входит в рамки желаемого
* Проект рассчитан на "естественный" критерий _парень-девушка_
* Поиск дает предпочтение интересам Пользователя перед Собеседником

Геолокация максимум изменится увеличением информативности списка "подсказок"
Да, теперь поиска "только онлайн" нет в принципе

#436
