### ISSUE TITLE
форма быстрого ответа

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#413]
в форме быстрого ответа было бы неплохо сделать отправку сообщения по ctrl+enter

**Comment by mj4444ru** [comment]
зачем? она же форма **быстрого** ответа...

**Comment by inquisitor6789** [comment]
так нажать 2 кнопки быстрее чем мышкой тыкнуть

**Comment by tebaly** [comment]
Это был сарказм в исполнении _великого_ тролля всея Сообщества

**Comment by mj4444ru** [comment]
в том то и дело, одну кнопку (enter) быстрее нажать чем две (ctrl+enter) ))) глупые блондинки не умеют 2 клавиши одновременно жать...

**Comment by inquisitor6789** [comment]
а не находите что поведение одинаковых по назначению элементов должно быть тоже одинаковым?

**Comment by mj4444ru** [comment]
А вы пользуетесь контактом?
Так вот там отправка сообщения из чата ctrl+enter, а из быстрого чата (справа снизу) уже по enter...

Я не ориентируюсь на контакт, просто их мнение совпадает с моим...

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/26968286-28b53a8e-4d0a-11e7-86d2-2581ef3f00d9.png)

**Comment by inquisitor6789** [comment]
так вся проблема в том, что если жмакнуть на ентер, то  не произойдет отправки быстрого ответа...

**Comment by mj4444ru** [comment]
ну тогда это форма **мышечного** ответа, если её нельзя отправить с клавиатуры...

**Comment by tebaly** [comment]
Пока нельзя)

**Comment by tebaly** [comment]
Добавлено. В деве, раскатится потом с обновой.
