### ISSUE TITLE
оповещение о новых сообщениях

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#414]
В настоящий момент оповещение о новых сообщениях пропадает как только открыли раздел "общение". Даже не смотря на то, что там есть не просмотренные сообщение.
Как мне кажется, было бы логичней оставлять оповещение пока не просмотрены все сообщения

**Comment by tebaly** [comment]
Нет))

**Comment by tebaly** [comment]
Считайте что это как с девственностью
