### ISSUE TITLE
одинаковый логин

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#417]
завел фейковую анкету и установил у нее логин, совпадающий с моим.
При попытке захода в анкету меня перекинуло на мою настоящую анкету.
Необходимо реализовать проверку на уникальность логина.
Понимаю, что большинство пользователей не меняют логин, но все таки....

**Comment by mj4444ru** [comment]
Если я это не писал, то значит просто было лень написать...

Там собственно есть проверка на уникальность, только она регистрозависимая (и та не всегда срабатывает)...

Я когда создал юзера с логином 'login' и паролем 'password', штук 8 анкет перебрал прежде чем до своей добрался...

**Comment by inquisitor6789** [comment]
> и та не всегда срабатывает)...

скорее вообще не срабатывает
логин и пароль были одинаковые вплоть до регистра

интересно, как ты их перебирал? менял логины чтоли?

**Comment by mj4444ru** [comment]
> менял логины чтоли?
именно так )))

**Comment by mj4444ru** [comment]
> менял логины чтоли?

именно так )))

**Comment by tebaly** [comment]
## Сие есть уязвимость?..

Кажется, если вы "угадали" связку логин+пароль - это ничем не отличается от обычного брутфорса. Последний будет успешным в обоих случаях.

Далее, если атак по смене логина приводит к "совпадению" связки для чужой анкеты, ничего не мешает вам без изменения своего логина применить данные авторизации на входе в чужую анкету. То есть, вам заранее должен быть известен ПАРОЛЬ от анкеты.
* если на _чужой_ анкете пароль **password** - таки чиья это уязвимость?..
* а если пароль **DARqoDgaN9VS7MUx9Za0wzQ** - таки когда вы закончите менять логины?..

**Comment by tebaly** [comment]
Поправьте пожалуйста, если я ошибаюсь. Ошибки по проекту допускаются в удручающем количестве. Но конкретно в этом случае _уязвимости_ я не наблюдаю. Есть:
* "мягкая" архитектура в системе авторизации, которая не проверяет ни "уникальности" связки логин+пароль, ни уникальности логина, ни уникальности пароля
* авторизация "мягкая" даже в том моменте, что изначально дает пароль в **5 символов**. Хотя по стандартам должно быть в два(!) раза больше.
* системе авторизаци пифиг что вы там сохраняете, лишь бы длинее трех символов. 

**Спорить не буду, это неправильно, но на сегодняшний день, если вы захотите сохранить пароль '_1234_' или '_pass_', или '_password_' - система даже не заикнется!** Система дает свободу мысли и действиям всем того желающим. Система считает, что если вы ставите логин **login** и пароль **password** - значит вам в этот момент это нужно и вы отдаете себе отчет в ваших действиях.

**Comment by tebaly** [comment]
> интересно, как ты их перебирал? менял логины чтоли?

Безусловно, наличие такого "мусора" в авторизации не есть хорошо, и я постараюсь повлиять на это. Но ведь здравомыслящие будут писать свои "нормальные" логин и пароль :)

**Comment by inquisitor6789** [comment]
ну как бы и да и нет... проблема немного в другом - не целенаправленное "угадывание". Например какой-то вася всегда использует логин Vasya. Другой Вася, что логично, будет использовать тот же самый логин. От простого совпадения логинов нас страхует пароль. Но учитывая специфику контингента сайта, очень маловероятно, что будут использовать пароли стойкие ко взлому. Скорей всего будут пароли из top10 популярных.

**Comment by tebaly** [comment]
> Но учитывая специфику контингента

В данный момент "исправляю"... Будет добавлено информирование по типу "сам дурак если чё". Запрета вводить покамест не будем, ибо только неудобства создаст... Я так думаю.

**Comment by tebaly** [comment]
На тесте. Частично закрываю, так как "видимый" эффект будет после обновы фронта, а я его не трогал сейчас. Бэкенд будет ругаться с сегодняшнего дня.
