### ISSUE TITLE
замечания

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#418]
http://freedomsex.me/35727425
http://freedomsex.me/userinfo/profile/35727425
Написано замечаний нет (хотя в профиле есть одно подтвержденное). 

И хоть я с ним и не согласен (по крайней мере 9 дней назад нечего было там подтверждать [этот 7313219 достал кстати! подтверждает всё подряд!], но все равно ведь где то косяк?

**Comment by mj4444ru** [comment]
Так уже не раз писали... Тебалай косяк, не знает что делать... Замечания только для админов видны, А на тему что он обманывает пользователей что типа замечаний нет, он сказал типа не доделано ещё (и доделано врятли будет)...

**Comment by tebaly** [comment]
Всё по очереди. Пока не работает..

**Comment by tebaly** [comment]
аттач #354
