### ISSUE TITLE
Не открывается список контактов

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#419]
У некоторых пользователей не отображается список контактов. При нажатии на "знакомства" или "общение" ничего не происходит.

**Comment by tebaly** [comment]
Если перезагрузка страницы не помогает, то некоторые пользователи ожидают там что-то увидеть в тот момент, когда там ничего и не должно быть. Признак верного бага - зависший лоадер(колечко такое крутящееся). Причина в ошибке авторизации, чему и поможет перезагрузка страницы..

Но если лоадера нет - то список просто пустой.

**Comment by Neaskil** [comment]
Так может кнопку добавить обновить которая будет релоадить окно ?

**Comment by SVIT-Lanka** [comment]
Бесконечный лоадер есть, перезагрузка не помогает. Со слов пользователя)

**Comment by tebaly** [comment]
Если воспроизвести ситуацию ни у кого кроме как у Пользователя не получилось, значит это миф, провокация и "фальшыука зробленная у Польшчы".

**Comment by mj4444ru** [comment]
Я сегодня авторизовался с телефона и где то после 3 минут нажимания обновить страницу, о чудо, контакты появились ))) так что подтверждаю что что то не так...

**Comment by mj4444ru** [comment]
PS: есть предположение что оно у вас сначала появляется, а потом обновляется и если сайт тормозит, то при определённой последовательности действий мы получаем пустые контакты...

**Comment by tebaly** [comment]
Добавлена информация на случай ~важных переговоров~ отсутствия списка. На время загрузки его действительно нет - окудава ему взяться то... Посмотреть в Деве, потом обнова. 
#430
