### ISSUE TITLE
A/B тестирование сайта.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#420]
Почему не применяется при нововведениях.
Ведь это отличный, давно рарекомендовавший себя способ.

**Comment by tebaly** [comment]
В проектах с каким бюджетов и с какой командой это обычно применяется?

**Comment by Fenslau** [comment]
Дык а есть же бесплатные методы вроде как?.... ? Или мы говорим о разный принципах?

**Comment by tebaly** [comment]
И яваскрипт и пэхапэ изначально бесплатны, но вы же их не применяете?..

**Comment by Fenslau** [comment]
Яваскрипт чтоб применять нужны команды знать. Блять, я это объяснял нашим лекторам по ООП, которые учили нас с++.
Я им говорил: Хули толку с этих всех классов, с этих блять объeктов, если мы не знаем главного - как на с++ сделать простейший вывод на экран хотя бы что нибудь кроме hello world.
но нас не учили этому. Да, какой то там стдаут я запомнил, да что с него толку? Он какую то вонючую строку только мог вывести. Чо мне эта строка, когда на асм х86 я мог уже написать полноценную змейку.
Это потом я понял, что там что то есть, какие то библиотеки, какие то дллы, еще какая то хрень....
Нет команд - нет программы. Нельзя изучить язык без ебучих команд, как сделать окно, как туда что-то кроме хелло ворлд поместить. Хоть заебись ты с этими объектами.
Ладно, это была лирика. Которая никому не интересна. 
Как я понимаю - есть инстументы А/Б тестирования, которые не одразумевают владения какими то там языками. не так ли?

**Comment by tebaly** [comment]
Стоит заметить, что крупные Веб проекты пишут свои веб-сервисы именно на С++ 
Данные не первой свежести, но суть отражают. Думаю, когда нибудь в будущем, некоторые наши сервисы будут написаны на С++ (если и язык и проект до того времени доживут).

![image](https://user-images.githubusercontent.com/9466814/27002008-8a1b560c-4ddf-11e7-8640-79d2eb538ea9.png)

A/B тестирование дает нагрузку на команду разработчиков и увеличивает бюджет разработки минимум на 20%. Если говорить о случаях, когда меняется структура базы данных - затраты на AB тест превысят 50% от самой разработки. 

В небольших командах и малом бюджете намного рентабельнее выкатить сразу и править на горячую. Да, пользователям не приятно, но они у нас за это пока и не платят... Расходы на AB тест равны или превысят потери при его отсутствии. Но. Мы всегда проводим такие тесты когда есть возможность для этого. У нас есть 4 тестовых сервера. На каждом своя часть аудитории, так что  фактически, каждый из них и есть относительная выборка в 5/10/15/50%

аттач #406

**Comment by Fenslau** [comment]
Я чот недопонял. А/Б тестирование типа сложно? То есть выбрать сервис и настроить в нем все так, чтобы было две версии (полуверсии) сайта - это так сложно? Если да, то чувствую нас ждет новая волна парадигмы А/Б тестирования. Я всегда считал, что нужно просто выбрать проект, указать две версии сайтов и выбрать логику. и все. Ну мож заплатить рублей 300. Извиняйте, если я не прав.

**Comment by Fenslau** [comment]
Я сам немного сопровождал проект на с++, который так же был сайтом. На тот момент я считал что такой язык (с++) был выбран исключительно потому что разработчики его знали хорошо и он обладал некоторой производительностью что ли (прошу строго не судить, но тема была такая - на с++ движок сайта тогда мог работать, на другом - задохнулся бы). А что сейчас - не знал - что до сих пор.
.
Лирика

**Comment by Fenslau** [comment]
читать чужой код - говорят эти типа некомильфо.
Да неееттт! После такого обучения, когда ты не знаешь ни одной блять команды - это просто поразительно! 
Понятно практически всё. 
По крайней мере за исключением этих ебучих ооп классов и объектов, которые я так и не освоил. Потому что нечего было осваивать.
В том коде я разобрался, пару моментов поправил и на этом мой опыт с с++ закончился.
Не знаю , зачем рассказываю это вам все, но думаю, что не направсно.

**Comment by Fenslau** [comment]
читать чужой код, когда ты не знаешь ни однлй команды в нем - просто. Становитс понятно, какие они хотя бы есть.

**Comment by tebaly** [comment]
@Fenslau ты пьян, иди домой :grimacing:

Перестаньте материться!
Здесь блядь официальный канал общения разработчиков. 
А вы какуюто хуету устроили.

**Comment by Fenslau** [comment]
Если бы мы отправляли всех, кто пьян домой - все сидели бы дома. И на вашем сайте были бы одни домоседы.

**Comment by Fenslau** [comment]
https://career.ru/vacancy/18486101
Я нашел 27+ ошибок. Кто больше?

**Comment by tebaly** [comment]
@mj4444ru - будьте бдительны. На один из ваших титулов есть конкурент))

**Comment by Fenslau** [comment]
нет нужды вызывать сира 44444 в закрытую тему. Я готов к этому вашему развенчанию.

**Comment by tebaly** [comment]
Зачем ссылку на ошибки запостили в тред про AB тесты?

**Comment by mj4444ru** [comment]
я тут... тесты это хорошо... но блять эти ебучие тесты забирают больше 50% рабочего времени... что то сделаешь, везде всё падает нахуй... защищаю титулы...

тесты хорошо когда делает куча людей и страшно что то где то трогать, по тому что обязательно где то что то сломается... и вот там как раз без тестов вообще не реально, вот и тратят столько времени на тесты... я лишь модульные тесты делаю, а ещё функциональные и приёмочные, там ваще ад...
