### ISSUE TITLE
Развенчание резидента.

### ISSUE THREAD

**Issue by Fenslau** [freedomsex/freedomsex#421]
Пришел тот самый момент.
Немного расскажу о себе: Я сюда пришел по тому что однажды Юлька (717 которая) почему то меня заметила и возжелала помочь мне в этом. Кстати - хер знает почему. У меня был опыт администрирования какого-то подобного проекта, но там все завершилось по другим обстоятельствам. 
В свою очередь, я, как и обещал Юльке, Привнес в проект новую админшу. Я думаю, что те, кто админит - знают ее, как Таню. Из Одессы. На этом считаю мой долг выполненным. И больше не могу занимать "должность" резидента. Так как не собираюсь (да и давно уже не) не выполняю его обязанностей.
Желаю всем, кто остается хорошего настроения. 
Надеюсь, что все будет хорошо!

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/27002990-158c3cc6-4df7-11e7-94d5-e9411d1130d7.png)

В прошлый раз публичный уход "резидента" сопровождался блокировками со стороны Роскомпозора. Что будет в этот раз? Страшно представить... Спасибо вам за всю помощь, которую вы оказали ресурсу и его пользователям.

**Comment by Fenslau** [comment]
В этот раз, надеюсь, обойдемся без подобных репрессий ))

**Comment by Fenslau** [comment]
До свидания, мои хорошие. Было классно. Мож с кем-то еще увидимся )

**Comment by tebaly** [comment]
> обойдемся без подобных репрессий ))

Очень хочется в это верить :grin: 

mj4444ru - уже то ли два, то ли три раза уходил, а всё никак.. Что-то держит. Ресурс проклят, отсюда ещё никто по своей воле не уходил.

![image](https://user-images.githubusercontent.com/9466814/27003171-60a42e3c-4dfa-11e7-9191-5cec64bc788a.png)

**Comment by Fenslau** [comment]
Да ну я знаю что это ))) Так же из "Тусовки" уходили одмины ) хлопали дверьми ) Ох.. знаю ) В отличие от них, я понимаю, что нет ничего тут незаменимого. А стало быть нет причин мне возвращаться. Так что все ок.

**Comment by tebaly** [comment]
аттач #420

**Comment by Fenslau** [comment]
Да ни чо он не проклят. Серега с вами. а это какая никакая но сила. Так что не надо тут не надо фотографий козла (или барана)? ничо не проиошло все норм. закрывайте темку.

**Comment by mj4444ru** [comment]
я не уходил на совсем, только с админов... и заметьте, я не админ )))

**Comment by mj4444ru** [comment]
надо роскомнадзору сказать что очередной админ уходит, пусть опять что нить заблокируют )))
