### ISSUE TITLE
Список "отравленных" знакомств - его может не быть.

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#422]
На самом деле он есть. И большая часть фукционала разработана изначально. Но этот список сейчас из интерфейса не доступен. Были смутные планы по его "внедрению/задействованию". Скорее всего он так и не будет "опубликован". И, вероятно, будет выпилен насовсем.
* На данный момент нет возможности "получить" список всех отправленных знакомств
* Вновь зарегистрированные парни не понимают, куда уходят их сообщения и уходят ли
* Это причина _большого непонимания_ в интерфейсе, баттхерта и критики

Кажется, его придется придержать на время + ∞

**Comment by mj4444ru** [comment]
по сути это как в контакте, добавь меня в друзья или не сможешь мне писать, при этом к запросу прилагается сообщение... я не понимаю что тут непонятного?

**Comment by tebaly** [comment]
#442 - ref

**Comment by tebaly** [comment]
прикрепляю #442

**Comment by tebaly** [comment]
Попробую всё-таки добавить чуть позже
