### ISSUE TITLE
Редактирование имени

### ISSUE THREAD

**Issue by astronom84** [freedomsex/freedomsex#425]
Товарищи, похоже не сохраняется редактирование имени собеседника. 
Отредактированное имя сбивается при обновлении страницы или при повторной загрузке анкеты собеседника через меню. 
Фича иногда достаточно полезная.

**Comment by tebaly** [comment]
Этой фичи в ближайшее время не будет. В новой обнове она пропадет вовсе. Попробуем ее вернуть конечно.
