### ISSUE TITLE
Правила сайта

### ISSUE THREAD

**Issue by KILLER1974** [freedomsex/freedomsex#426]
Когда исправите граматические ошибки и описки или дайте мне возможность это сделать.

заранее спасибо за реакцию.

**Comment by SVIT-Lanka** [comment]
граММатические :)
Вы уверены, что хотите этим заниматься? :)

**Comment by tebaly** [comment]
Вся документация включая правила размещена в отдельном репозитории 
* https://github.com/freedomsex/docs

Сами правила - rules.md в корне раздела. Для редактирования доступно всё уже больше года. Стоит отметить, что сам многоуважаемый @mj4444ru порывался всё исправить. И таки сделал целый один коммит в мастер ветку https://github.com/freedomsex/docs/pull/1/commits/48eab0a0bf269d44ed56d5f2114b3f0f80738897 Но что-то не задалось.

**Comment by mj4444ru** [comment]
Лень из за каждой очепятки делать пулреквест... я случайно много находил, но это было всё по одной штуке за раз... Да и читать правила нынче не модно )))

**Comment by KILLER1974** [comment]
puntoswitcher так грамматически исправил)))
я могу не только ошибки исправлять, но и базу пользователей почистить - "мёртвые души", которые больше года не заходят и более. Думаю, таких на сайте немало(синоним-много)

**Comment by tebaly** [comment]
Как ни лето, так всем базу подавай :sweat_smile:
Кому чистить, кому развивать...

![image](https://user-images.githubusercontent.com/9466814/27394900-99ff15a6-56b6-11e7-8a56-0596a3bc084e.png)

**Comment by KILLER1974** [comment]
кто-то же должен работать-пока другие отдыхают...

**Comment by KILLER1974** [comment]
грусть нам не присуща! мы - должны быть единим организмом сайта

**Comment by mj4444ru** [comment]
я правозащитный орган )))

**Comment by mj4444ru** [comment]
чур я правозащитный орган )))

**Comment by KILLER1974** [comment]
юридическая сторона - это компетенция юристов!
вы - юрист? тогда вперёд и с песенкой!

**Comment by tebaly** [comment]
он не меньше чем прокурор)) хотя скорее всего чуть выше и несколько в другой структуре  

![image](https://user-images.githubusercontent.com/9466814/27431199-50b5f808-5754-11e7-977a-942312bd81ac.png)

**Comment by tebaly** [comment]
патч применен на бете. судя по всему вся мутка ради одной буквы была. где-то мы это уже встречали :grin:
