### ISSUE TITLE
Обновление интерфейса (бета-тест)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#427]
На http://qrsex.ru - пробный выкат(еще хватает косяков)
* Просмотр аккаунта в процессе
* Замечания в процессе
* Модерилка в процессе

**Comment by inquisitor6789** [comment]
поиск не работает

**Comment by inquisitor6789** [comment]
а какой профит от этого обновления? на мобиле будет нормально показывать?

**Comment by tebaly** [comment]
Пробуйте :)

**Comment by tebaly** [comment]
Поиск исправил

**Comment by tebaly** [comment]
60% юзеров ходят с мобилок. Да и поисковики не любят сайты, не любящие мобилки. Мы не можем делать разные версии отображения. Попробуем сделать адаптивную версию. Дополнительно загоним её в app для желающих установить приложение.

**Comment by inquisitor6789** [comment]
1. невозможно зайти под существующим логином. Кидает форму заполнения анкеты.
2. кривовата верстка
![image](https://user-images.githubusercontent.com/19651618/27538244-b6a4caf8-5a7f-11e7-9c17-71223cf5ee3b.png)

**Comment by tebaly** [comment]
что за браузер?

**Comment by inquisitor6789** [comment]
samsung internet
версия 5,4,00-75

**Comment by mj4444ru** [comment]
пользователи мобилок дождались... а где кнопка вход? )))

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/27539906-f64d3b2a-5a86-11e7-9b80-daf100b94f7d.png)

**Comment by Reydan46** [comment]
Зачем в поле возраст отсчёт идёт аж от 1-цы? О_о

**Comment by tebaly** [comment]
Ой. Косяк))

**Comment by mj4444ru** [comment]
я даже попытался указать возраст 5, но блин сайт не захотел он мне верить (((

**Comment by Reydan46** [comment]
На странице аккаунта "Другие настройки", все кнопки, кроме перехода на главную страницу не работаю. Не знаю, может это и есть "Просмотр аккаунта в процессе" )

**Comment by Reydan46** [comment]
![image](https://user-images.githubusercontent.com/4998320/27540457-ec554b88-5a88-11e7-9751-57248e695619.png)
Ни списка контактов, что бы переключиться быстро. 
Ни отображения того, с кем говорю, вообще ничего.
Да и область для сообщений крайне мала)

**Comment by Reydan46** [comment]
![image](https://user-images.githubusercontent.com/4998320/27540514-19ce45e2-5a89-11e7-9f8e-7e5e41df3bab.png)
Я уже не говорю про великолепный дизайн загруженных фотографий)
И ни одно фото так и не смог отправить...

**Comment by Reydan46** [comment]
В пункте "Знакомства" при нажатии на "Читать полностью..." открывается анкета. Фича или баг?

**Comment by tebaly** [comment]
> кривовата верстка

@inquisitor6789 - проверьте, должно было стать получше..

**Comment by tebaly** [comment]
> Я уже не говорю про великолепный дизайн загруженных фотографий)

Нет. Это при разработке фон был, просто остался. Уберу.

**Comment by tebaly** [comment]
> Ни списка контактов, что бы переключиться быстро.
> Ни отображения того, с кем говорю, вообще ничего.

Собственно некуда.. Имя можно в заголовок пихнуть вместо "Сообщения"

**Comment by inquisitor6789** [comment]
> @inquisitor6789 - проверьте, должно было стать получше..

не, не стало
хочу еще раз обратить внимание - нет возможности войти под существующим аккаунтом. А если и и есть, то очень хорошо спрятана

**Comment by tebaly** [comment]
Спрятана - Настройки анкеты, выйти, войти. Попробую исправить. 
* Вот куда эту кнопку вставить?)

**Comment by Reydan46** [comment]
Позвольте пофантазировать
![image](https://user-images.githubusercontent.com/4998320/27541544-f3ab5dec-5a8c-11e7-85f4-583800934ead.png)

**Comment by Reydan46** [comment]
А по поводу входа. Если выйти из аккаунта, то не имея уже существующий, нельзя создать новый.

**Comment by tebaly** [comment]
Это как?..

**Comment by Reydan46** [comment]
Ну вышел из акка. Доступна кнопка вход (но, допустим у меня нет акка и я по глупости нажал выйти)
И вторая кнопка "Получить логин и пароль прямо сейчас", которая не работает.

**Comment by tebaly** [comment]
> не, не стало

Тогда я хз. На древнем ведроиде 4.2.2 в дефолтном браузере верстка этого блока в норме. Всё что выше, просто обязано работать ещё лучше.

**Comment by tebaly** [comment]
> И вторая кнопка "Получить логин и пароль прямо сейчас", которая не работает.

Да) она сейчас не работает..

**Comment by inquisitor6789** [comment]
> Вот куда эту кнопку вставить?)

а что мешает ссылкой вот сюда?
![image](https://user-images.githubusercontent.com/19651618/27541908-5b503e1c-5a8e-11e7-8306-a4990dbbfe9e.png)

**Comment by tebaly** [comment]
В самый низ? Под "другие настройки" - _Другая анкета_ ?..

**Comment by inquisitor6789** [comment]
> Позвольте пофантазировать

кажется это не лучшее решение с точки зрения мобил

**Comment by inquisitor6789** [comment]
> В самый низ? Под "другие настройки" - Другая анкета ?..

да. как-то так

**Comment by Reydan46** [comment]
Либо подпунктом ... что то вроде
![image](https://user-images.githubusercontent.com/4998320/27542168-1d3d9560-5a8f-11e7-9da2-5ff55574cb76.png)

**Comment by tebaly** [comment]
Давайте без подпунктов :blush:
* Точно, _сменить аккаунт_ 

Голосуем :)

**Comment by inquisitor6789** [comment]
> Точно, сменить аккаунт

+1

но это будет работать только если уже залогинен. А если первый раз?

**Comment by KILLER1974** [comment]
действительно с 4,4,2 - норма

**Comment by mj4444ru** [comment]
а как люди (обычные, которых 99%) должны догадаться?

**Comment by mj4444ru** [comment]
вы где такие старые телефоны берете? @tebaly , у вас нет денег на новый телефон? в хроме есть эмуляция телефона )))

**Comment by KILLER1974** [comment]
на 6,0,1 тоже работает

**Comment by KILLER1974** [comment]
почта не регистрируется

**Comment by SVIT-Lanka** [comment]
Зачем кнопка "Поиск" в шапке и область "Вы ищите бла-бла-бла.. настроить поиск"? Можно убрать область и функционал весь повесить на кнопку Поиск в шапке? И в бланке поиска может не "Мой город", а "Город поиска" сделать?

**Comment by SVIT-Lanka** [comment]
Еще вопрос, можно ли сделать автоматическое обновление приходящих сообщений в окне чата. И в списке контактов тоже можно было бы) А то не очень удобно, каждый раз возвращаться назад или обновлять, а потом снова заходить в Общение.

**Comment by tebaly** [comment]
> "Вы ищите бла-бла-бла.. настроить поиск"?

В этой области сконцентрирован глубокий тантрический смысл. Сам юзер знает кого ищет, но вот кого ищет для него сайт, узнаёт не сразу...

**Comment by tebaly** [comment]
* Пункт "Сменить анкету" добавлен
* Фон галереи фоток исправлен
* В шапке диалога - данные контакта

**Comment by tebaly** [comment]
@SVIT-Lanka - можно. Но сложно... PHP не может в сокеты.. и пушить тоже не в силах. А бэкенд на пхп написан пока ещё.

**Comment by tebaly** [comment]
> вы где такие старые телефоны берете?

Мой собственный динозаврик, храню как эталон.. Хром не эмулирует поведение ОС/приложений, он разрешения экрана может изменять и только.

**Comment by SVIT-Lanka** [comment]
Вот еще момент только заметила, в окне чата, когда жмешь на "Следующие", чтоб посмотреть всю переписку, сообщения перемешиваются по непонятному алгоритму)) нарушается хронологический порядок.

**Comment by inquisitor6789** [comment]
отправка сообщений по ctrl+enter не работает

**Comment by tebaly** [comment]
Да, есть такое..

**Comment by inquisitor6789** [comment]
не снимается маркер нового сообщения
шаг1. читаем и отвечаем на сообщение
![image](https://user-images.githubusercontent.com/19651618/27575524-d550cbac-5b22-11e7-8524-8bcabeb72077.png)
шаг2. нажимаем стрелочку назад
![image](https://user-images.githubusercontent.com/19651618/27575581-f630f41e-5b22-11e7-8992-c6c9abb29941.png)

**Comment by inquisitor6789** [comment]
> отправка сообщений по ctrl+enter не работает
Да, есть такое..

вы, батенька, шаман? сейчас заработало

**Comment by inquisitor6789** [comment]
нет значка "онлайн" в анкете

**Comment by Grian59** [comment]
Поиск настроили. Ищем. В определенном городе, например Вирт Секс.
Однако, если хотим посмотреть весь список, без выбора города - не дает. При попытке оставить в поиске чистое поле - не дает, возвращает Вирт Секс

**Comment by inquisitor6789** [comment]
еще такой косячок нашел...
1. получаем предложение о знакомстве
2. нажимаем на него
3. открывается фрейм быстрого ответа
4. жмем "читать полностью"
**5. открывается анкета, а не окно сообщений**
6. жмем "Написать сообщение"
**7. открывается фрейм быстрого ответа**

**Comment by inquisitor6789** [comment]
как просмотреть анкету из окна сообщений?

**Comment by SVIT-Lanka** [comment]
В нижнем левом углу кнопочка есть) Но вот анкета открывается в этом же окошке.... и номера не видно...

**Comment by inquisitor6789** [comment]
> В нижнем левом углу кнопочка есть)

мда... не очень очевидное решение.... хотя может дело привычки

**Comment by tebaly** [comment]
Всё верно. Ещё не решили как правильнее "разделить" общение/знакомства. 
* получаем предложение о знакомстве
* нажимаем на него
* открывается фрейм быстрого ответа
* жмем "читать полностью"

Скорее всего либо сделаем открытие диалога, либо "Не будет у вас больше переписки до первого ответа собеседника"

![image](https://user-images.githubusercontent.com/9466814/27584884-9ae6e382-5b42-11e7-8545-49c6136cc043.png)

**Comment by tebaly** [comment]
Например. Фото уже "нельзя" отправить, если вам ещё не ответили..

**Comment by Grian59** [comment]
Пишу первое сообщение.
Населенный пункт совпадает, как и возраст в диапазоне поиска.
Отрывается капча. Заполняю, нажимаю "Отправить". Опять капча с другими цифрами. И так до бесконечности.

**Comment by SVIT-Lanka** [comment]
Вы этот вопрос задавали на сайте? Напишите виртуальному помощнику. Админы посмотрят, что с Вашей анкетой.

**Comment by mj4444ru** [comment]
> PHP не может в сокеты.. и пушить тоже не в силах.

Ну если коротко, то он всё может совместно с каким нибудь модулем... Битрикс забубенили пуш сообщения на одном лишь php... а вы не может, не может...
а если коротко, ставится модуль для эндженикса, который эту пуш и реализует, а php присылает ему сами события... мы такое на ноде делали, но у нас там широковещательные были, надо было не тока юзера, но и события других независимых обектов слушать с учётом прав (которые могут и поменятся)... а тут всё проще, модулей под этих целей вроде как много говорили...

**Comment by Grian59** [comment]
> Пишу первое сообщение.
Населенный пункт совпадает, как и возраст в диапазоне поиска.
Отрывается капча. Заполняю, нажимаю "Отправить". Опять капча с другими цифрами. И так до бесконечности.
>
Это тестирование нового дизайна. Если более подробно, то... 
Сначала диапазон возраста не совпадал, и капча не пускала ни на первый ни на второй, ни на третий раз.  Ок.
Поменяем возраст на входящий в диапазон. Пишем сообщение. Опять капча (?) и опять по кругу.
ПК, Хром.

**Comment by SVIT-Lanka** [comment]
> Опять капча (?) и опять по кругу. ПК, Хром.
Да, есть такое в Хроме. И верстка в шапке кривая.

**Comment by SVIT-Lanka** [comment]
Да, есть такое в Хроме. Предложить знакомство невозможно получается. И верстка в шапке кривая.

**Comment by tebaly** [comment]
Обновлен интерфейс настроек анкеты (Другие настройки)

**Comment by KILLER1974** [comment]
Когда примерно это переедет на основной сайт или наоборот новый будет?

**Comment by tebaly** [comment]
Обновлен просмотр анкеты(не завершено)
"Читать полностью" - выпилено -> стало -> _Смотреть анкету_ 
Статус онлайн появится 

До обновления на второстепенных зеркалах 1-2 дня. 
Главные, через 2-3 дня.

**Comment by SVIT-Lanka** [comment]
1. как можно попасть а страницу собеседника или посмотреть его id? Получается, что из вкладок Знакомства и Общение на страницу перейти нельзя.
2.  вытекающее из 1 пункта - где будет ссылка на видеочат?

**Comment by tebaly** [comment]
Двигаемся в сторону одностраничного приложения. Нет понятия "страница собеседника" - теперь это ближе к "Анкета" собеседника. Просмотр сейчас как минимум из трех мест - знакомства/общение/быстрые сообщения.

**Comment by SVIT-Lanka** [comment]
Не очень удобна форма быстрого ответа с мобилы. Если много желаний и большой текст входящего сообщения, то окно занимает почти весь экран. Вследствие: 1. ответ набираешь вслепую (область ввода оказывается под клавиатурой); 2. окно нельзя закрыть. 
Есть предложения: 1. убрать желания из формы быстрого ответа (они же есть в анкете), 2. добавить 'крестик' для закрытия окна.

**Comment by mj4444ru** [comment]
как так у вас набирается под клавиатурой? браузер должен следить что бы тем набирается выше клавиатуры и все известные мне браузеры за этим следят....

**Comment by tebaly** [comment]
Попробуйте. Сам в ах..е :flushed:

**Comment by tebaly** [comment]
"Отложим" на после выката. Иначе из теста ещё месяц не выйдем ...

**Comment by Grian59** [comment]
1. Я - модератор - пропал? 
2. Невозможно искать без города, если город введен в поиск.

**Comment by tebaly** [comment]
1. Из шапки - _Модерилка в процессе_ :snowflake:
2. Ибо не нужно это, мне кажется. 
* Понятие "Город поиска" _выпилено_ -> стало -> "Мой город"

**Comment by tebaly** [comment]
Тестируем "возвращение" видеочата + список присланных фото.

**Comment by SVIT-Lanka** [comment]
Не могу найти Выход с сайта. Можно добавить в анкету под Уже есть анкета...

**Comment by SVIT-Lanka** [comment]
Список присланных фото есть (миниатюрки). Открыть/просмотреть их их этого раздела нельзя. Так и задумано?

**Comment by tebaly** [comment]
нет)

**Comment by tebaly** [comment]
Исправлено. Фото открываются. 
Выход через ~жепу~ _Другие настройки_

**Comment by SVIT-Lanka** [comment]
1. Разделы блога хромают: ссылки в шапке на рабочие, верстка кривая.
2. Желания... Свои желания добавить нельзя, только выбор из списка (а список, надо сказать, так себе)).  Желания на главной и у собеседника не кликабельные, не добавляются в мои, как раньше.

**Comment by tebaly** [comment]
Блог поправим. Желания допилим..

**Comment by tebaly** [comment]
Блог "адаптирован" под изменения
Доделывается после выката на основные зеркала будет:
* Модерилка (ссылка на интерфейс) - сам интерфейс никуда не делся
* _Кликабельность_ желаний
* Замечания, пока ещё в холде  :snowflake:

С большего вроде всё из темы исправлено. Основной функционал сайта/приложения исправен и доступен. Тестирование на зверопарке мобильных браузеров не проводилось. В нормальных браузерах работает. На динозаврах что-то может не работать, равно как и не заработать никогда.

ЗЫ: если у вас есть возможность исправить ошибки в коде или верстке, буду благодарен

:beetle:

**Comment by tebaly** [comment]
Исправлен баг "чтения" в сообщениях. Выкатил на предпоследнее зеркало. Полетят гневные письма от Юзеров в большом количестве. Спасибо за помощь. Чтобы не путаться, открываю новую тему.

430 - Invalid username or password
