### ISSUE TITLE
Собственный домен для каждого :kiss:

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#429]
Если есть желающие "вести" _своё зеркало сайта_, пришлите название своего домена*.
* Можете сами купить домен в любой доменной зоне(от 80 рублей)
* Можете выбрать дефолтный город для отображения на главной

От вас ожидается (можем и сами)
* Выбрать картинку для шапки главной страницы ~ 750х250 
* Придумать текст/заголовок для шапки главной страницы 150-300 символов
* Придумать текст для трех слайдов в футере на главной

Вы получаете - зеркало сайта на вашем _собственном_ домене. 
Бесплатно и без СМС

\* Вы можете придумать название и проверить, свободно ли оно. И, **если у вас нет денег** или вы **не хотите тратиться**, пришлите название нам - мы купим его для вас**.
\** Покупка в таком осуществляется через наш аккаунт и домен будет ваш теоретически...
\*** В любом случае, "заниматься" сайтом вы будете самостоятельно :) 

# Предложите красивое название 
Название домена из свободных  - и мы его обязательно зарегаем! Чтобы его не зарегал кто-нибудь до нас, пришлите название нам на почту :sweat_smile:

**Comment by mj4444ru** [comment]
база то общая будет?

**Comment by mj4444ru** [comment]
и что значит заниматься сайтом?

**Comment by tebaly** [comment]
Оу.. Что-то вам в забойкалье не спится)))

**Comment by tebaly** [comment]
> и что значит заниматься сайтом?

Всё что изволите исходя из того, что вам принадлежит домен))

**Comment by KILLER1974** [comment]
Считаю лучшим заниматься одним сайтом - довести до полного совершенства и получить блаженство от толково выполненной работы!

**Comment by tebaly** [comment]
Сайт то один, как ни крути

**Comment by Reydan46** [comment]
Как по мне, так рано ещё создавать тьму алиасов. Сначала допилить базовый функционал нужно. ИМХО.

**Comment by tebaly** [comment]
Нужно. Но вообще, вопрос был в том, есть ли у кого желание :grimacing:

**Comment by tebaly** [comment]
Количество в данном случае никак не влияет на качество.

**Comment by KILLER1974** [comment]
наплодить клонов и всё?!

**Comment by mj4444ru** [comment]
Кто тут в забойкалье? ))) 

> *** В любом случае, "заниматься" сайтом вы будете самостоятельно :)
> Всё что изволите исходя из того, что вам принадлежит домен.

Это в смысле менять DNS сервера?
Или при покупке услуги DNS сервера менять A и MX записи?

**Comment by tebaly** [comment]
@mj4444ru смотреть, следить за доступностью и исправностью. Быть суперадмином в некотором смысле.

**Comment by mj4444ru** [comment]
то есть у вас:
- тестировщик == суперадмин

**Comment by tebaly** [comment]
А, то есть вы заранее знаете дальнейшее развитие событий :wink:
Это начальная часть большого ~заговора~ замысла

![image](https://user-images.githubusercontent.com/9466814/27878909-87b613dc-61c8-11e7-846f-c79f4df6fb45.png)

**Comment by mj4444ru** [comment]
вы наняли программистов и они вам всё ломают? или сами уже запутались в кода?

у меня тут последнее время действует правило - в одном месте наладил, в другом полюбасу что то сломалось... вот она совместная разработка...

**Comment by tebaly** [comment]
Если вы не хотите помогать вносить исправления в код - просто сообщите где и что работает не так как надо. Мы стараемся исправить. 

![image](https://user-images.githubusercontent.com/9466814/27887918-de13754e-61eb-11e7-9bd7-ab824ad2550e.png)

**Comment by avkHV** [comment]
Добрый день. Есть домен. Куда и кому писать?

**Comment by tebaly** [comment]
support@freedomsex.net | admin@freedomsex.net

**Comment by tebaly** [comment]
#380
