### ISSUE TITLE
Обновление интерфейса

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#430]
Вид сайта меняется в сторону веб-приложения. Появляются характерные черты приложения хотя по сути это всё ещё сайт. Процесс перехода не самый простой. Исправлено много ошибок, но они всё же остались в некотором количестве. Работу по наладке и исправлениям продолжаем.

1. Cсылка на интерфейс модератора заработает - сам интерфейс никуда не делся
2. Кликабельность желаний будет исправлена
3. Замечания, пока ещё в заморозке

* Понятие "Город поиска" _выпилено_ -> стало -> "Мой город"
* Сайт никогда не был расположен к поиску вне одного города
    * Никогда не было поиска по стране или области - этого не видно и в будущем
    * Нельзя было искать по двум и более городам

Яснопонятно, что те кто искал "кого-нибудь" онлайн чтобы непременно написать _романтическое стихотворение_ или поделиться _яркостью своего темперамента_ в фото это огорчит...
 
Основной функционал сайта/приложения исправен и доступен. Тестирование на зверопарке мобильных браузеров не проводилось. В нормальных браузерах работает. На динозаврах что-то может не работать, равно как и не заработать никогда.

---

### Пожалуйста, сообщите если всё же что-то не работает или работает не так. Перепостите сюда жалобы Пользователей, которые считаете важными. Спасибо.

**Comment by monkklan** [comment]
капча зверствует, невозможно никому написать вообще, а так как модерки нет то и кредитов нет

**Comment by monkklan** [comment]
капча зверствует у всех, причем уже в переписке, в процессе начинает зверствовать так что невозможно дальнейшее общение, народ уже Юльке строчит гневные сообщения. оставьте хотябы на сексуууу старый интерфейс

**Comment by mj4444ru** [comment]
жестоко... я вообще не смог никому написать, капча не дала... а вообще все печально...

**Comment by Reydan46** [comment]
Исходя из "Понятие "Город поиска" выпилено -> стало -> "Мой город"" и "Яснопонятно, что того кто искал "кого-нибудь" ..... это огорчит"
Получается, что поиск идёт только в моём городе и пункт "Только в моём городе" бессмыслен?

**Comment by SVIT-Lanka** [comment]
Да, пункты "Виртуальный секс" и "Только в моем городе" в поиске ни на что не влияют.

**Comment by SVIT-Lanka** [comment]
Несколько мелочей (придираюсь наверное уже)): 
1. на фридоме на главной рудиментик остался в зеленой области "нажмите слово Анкета в самом верху"
2. в блоге ссылка Онлайн помощник не ведет на Юльку
3. в футере Способ знакомства открывается в новом окне, в отличии от других разделов справки

Капча зверствует за несоответствие города и возраста, в остальном норм.
Юзер гневается, в основном, с непривычки и на сложности писать всем и всяк)

**Comment by monkklan** [comment]
специально тестил сейчас, капча зверствует рандомно, возраст и город совпадают, вообще идеальный мач, но капча написать не даёт вооще

**Comment by tebaly** [comment]
> теперь другие города не выберишь -> сайт в говно превратили

Капчу по факту не трогали то. Да и работает она вроде нормально. И в другой город вы написать можете как и раньше - в этом плане ничего не поменялось. 
* Единственное, что не нравится тем, кто виртуалит - сложнее стало писать с Мурманска в Москву. Потому что город поиска стал равен городу в анкете, и для смены города поиска нужно менять город анкеты. А сам поиск поиск "без города" стал не очевидным..

**Comment by tebaly** [comment]
> но капча написать не даёт вооще

Вводите правильно и не пускает? Сама капча обновляется?

**Comment by tebaly** [comment]
> Да, пункты "Виртуальный секс" и "Только в моем городе" в поиске ни на что не влияют.

Это настройки поиска для тех, кто вас ищет. Образно - вы ищите общение "только в своем городе" - кому-то сложнее будет написать вам из другого города.

**Comment by monkklan** [comment]
капча не работает, она просто каждый раз обновляется, хоть 10 или 20 раз вводи, и так даже если города и возраст поиска совпадают

**Comment by SVIT-Lanka** [comment]
В старой версии Хрома было такое, после обновления все норм. Проверяла несколько раз, с разными параметрами - по две капчи на несоответствие максимум. (хром и лисичка на ПК, хром на дроиде)

**Comment by tebaly** [comment]
@SVIT-Lanka - самые адекватные замечания за всю историю. Аж слезки наворачиваются :relaxed:

**Comment by SVIT-Lanka** [comment]
Спасибо... так приятно это слышать :)

**Comment by Grian59** [comment]
Да, при тестировании капча не давала писать. Сейчас - просто идеально Хром не обновлялся, сам как то "привык".
Поиск "везде" - можно вести, если хочется с главной страницы, правда, без раздления по полу, так что не страшно )

**Comment by monkklan** [comment]
браузер мобильный сафари

**Comment by Grian59** [comment]
Капча, все таки некорректно работает. Вообще, такое впечатление, что цифры не те... Крутит по многу раз. Она же должна когда нибудь сработать...

**Comment by mj4444ru** [comment]
если капча привязана к ип, то это все объясняет... 

ps: капча привязанная  к айпи вредит только честным пользователям, а роботу и механизму обхода капчи это сложностей не доставляет...

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/27922680-89e21216-6284-11e7-8f23-04fd04459b6f.png)

**Comment by tebaly** [comment]
Исправлен баг с подтверждением/удалением емайл

**Comment by Grian59** [comment]
Проблема удалить желание.
Удаляю, красное окно с "удалить" Подтверждаю, Желание исчезает. Вхожу снова, как было, так и остается.

**Comment by tebaly** [comment]
Исправлен баг капчи - кэшировался компонент капчи на клиенте вместе с картинкой

**Comment by brat-neo1** [comment]
Ничего не исправлено, по прежнему капча бесит.

**Comment by tebaly** [comment]
Исправлен баг "удаления" желаний.

**Comment by tebaly** [comment]
@brat-neo1 - теперь бесит не всех..

**Comment by brat-neo1** [comment]
??? а когда у меня пропадет?

**Comment by tebaly** [comment]
ID ваш напишите

**Comment by brat-neo1** [comment]
сюда?
Вы про логин?

**Comment by tebaly** [comment]
Пробуйте. Должно полегчать. Страницу обновите

**Comment by tebaly** [comment]
ID анкеты (адрес)

**Comment by brat-neo1** [comment]
Урааа. Заработало. Огромное спасибо Вам. Дай Бог Вам здоровья и кучу детей))))

**Comment by tebaly** [comment]
Свечку в церкви поставьте :joy:

**Comment by brat-neo1** [comment]
Все равно бывает подглючивает(((
ID: 39670228

**Comment by brat-neo1** [comment]
Да. Опять начала капча слетать(( с 15-20 раза сообщения отправляются. А фото тем более нет((

**Comment by tebaly** [comment]
Проверил, с капчей проблем не заметил. У _кого-нибудь ещё_ с ней есть проблемы?

**Comment by Reydan46** [comment]
С капчей проблем нет, однако есть проблема с отправкой фото. Что на freedomsex, что на qrsex

**Comment by drvalera** [comment]
Не дает фото отправлять вообще ни в какую.... капча мучает страница типа обновляется и пустота

**Comment by drvalera** [comment]
А почему нельзя было оставить старую систему диалогов? Зачем все убирать во всплывающие окна?

**Comment by Reydan46** [comment]
Android 6 стандартный браузер от Miui
Фото не отправляются

**Comment by tebaly** [comment]
не по всем раскатил

**Comment by tebaly** [comment]
> Стало не удобно ! Месяц назат было все просто и удобно ,**и фото отправить** и **в любой город написать** .А сейчас вообще не удобно( зачем вы все усложняете????????)

Топ жалоб от девушек
* Пишут с других городов
* Присылают фото когда не просят
* За#бали виртуалы

![image](https://user-images.githubusercontent.com/9466814/27993295-83dba804-64b0-11e7-9016-884a7737ae32.png)

**Comment by tebaly** [comment]
@inquisitor6789 поправил верстку немного. Заголовки должны стать на место.

**Comment by drvalera** [comment]
так самих виртуалок куча, пусть не брешут)

**Comment by tebaly** [comment]
> оставить как и было

![image](http://i0.kym-cdn.com/photos/images/newsfeed/000/727/911/515.gif)

**Comment by drvalera** [comment]
Понял Сир) ПРивыкаем к новому)

**Comment by inquisitor6789** [comment]
> @inquisitor6789 поправил верстку немного. Заголовки должны стать на место.

подтверждаю, исправлено

**Comment by Reydan46** [comment]
Маленькая проблема, если фото в правом верхнем углу белое, то и крестика, закрывающего фото, так же не видно.

**Comment by Reydan46** [comment]
И ещё, не знаю как остальным, но лично мне крайне не хватает видимого статуса онлайн человека. Что при поиске, что при общении. Приходится каждый раз заходить и смотреть анкету собеседника.

**Comment by Reydan46** [comment]
Кхм...
![image](https://user-images.githubusercontent.com/4998320/28026528-a9592034-6596-11e7-8286-12c339e86845.png)
![image](https://user-images.githubusercontent.com/4998320/28026541-b2a59668-6596-11e7-9644-d9c7112f4150.png)

**Comment by tebaly** [comment]
Индикация онлайн в поиске добавлена.

**Comment by Grian59** [comment]
И, в результате всех переделок

Топ жалоб от девушек

Пишут с других городов
Присылают фото когда не просят
За#бали виртуалы

Получился чистый лесби сайт. 90% девушек ищут девушек. Подсчет за 3 последних дня в группе Вирт Секс 
Топ жалоб от девушек, от tebali можно выразить одним
- Сделаем лесби сайт, Мужики затрахали.

**Comment by drvalera** [comment]
Хоть убейте. В глаза долблюсь и не вижу куда уехала кнопка "Я модератор" Оо

**Comment by tebaly** [comment]
Её там ещё нет

**Comment by tebaly** [comment]
@Grian59 - я то тут причем.. все администраторы имеют доступ к жалобам/отзывам/вопросам. у кого-то из администраторов другие данные?)

**Comment by tebaly** [comment]
@Reydan46 - добавил тень к крестику, онлайн в поиске. Онлайн в общение добавлю, главное не забыть.. Кракозябры уберу. Прикрепляю к #442

**Comment by tebaly** [comment]
@Reydan46 - Кракозябры поправил, на тесте.
