### ISSUE TITLE
Бесконечная капча

### ISSUE THREAD

**Issue by Pere4niza** [freedomsex/freedomsex#431]
При попытке кому угодна написать сообщение, требуется выбивать капчу которая не заканчивается

**Comment by SVIT-Lanka** [comment]
Я так поняла, эта проблема в основном на мобилах и в определенных браузерах...

**Comment by Pere4niza** [comment]
Пробовал в трёх браузерах и на другой мобиле со своего акка16:51, 6 июля 2017 г., "SVIT-Lanka" <notifications@github.com>:Я так поняла, эта проблема в основном на мобилах и в определенных браузерах...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by SVIT-Lanka** [comment]
В каких?

**Comment by Pere4niza** [comment]
uc browser, dolphin и стандартный андроидовский. С телефонов Iman viktor и лейка17:09, 6 июля 2017 г., "SVIT-Lanka" <notifications@github.com>:В каких?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Grian59** [comment]
Дело даже не в этом. Один и тот же браузер ведет себя по разному. То пропускает сообщения без проблем, то начинает "крутить капчу". Даже, если я написал с нарушением условий поиска, ввод капчи, пусть 2-3 раза должен пробивать нестыковку условий. Этого не происходит.

**Comment by tebaly** [comment]
Причина найдена. Исправляю.

**Comment by tebaly** [comment]
Исправлено
