### ISSUE TITLE
пометка пользователя которому уже писал

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#433]
http://sexoo.me/admin/sethelp/?id=165518&ln=165521
http://sexoo.me/admin/sethelp/?id=165521&ln=0
Если в кратце, то пользователи хотят видеть кому уже написал, а кому нет. В настоящий момент из анкеты этого не видно.

**Comment by tebaly** [comment]
да. уже работаем над этим

**Comment by tebaly** [comment]
#434 аттач

**Comment by tebaly** [comment]
#436 добавлено
