### ISSUE TITLE
Интерфейс поиска, разработка

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#434]
На dev сервере выкладывается рабочая версия нового интерфейса поиска. http://qrsex.ru

**Comment by KILLER1974** [comment]
Андрей - #39221125
Не удобно очень
Пожалуйста
Сделайте так чтобы было видно кому писал уже!!! И чтобы город можно было убрать

**Comment by KILLER1974** [comment]
Здравствуйте,хотел уточнить,до обновления было удобно в том плане,что в поиске слева от имени показывало зеленый кругляшок тем кому ещё не писал,сейчас этого нет,и из поиска сложно определить с кем уже переписывался а с кем нет,прошу обратить на это внимание

**Comment by tebaly** [comment]
Поиск обновлен
* Загрузка следующих
* Быстрое сообщение

Отметка "Кому писал" в пути... Напилася и спит где-то под забором :stuck_out_tongue:

**Comment by Grian59** [comment]
Искать девушек - дает парней
Искать парней - дает девушек.

Не видно кто онлайн
Нет всплывающих подсказок на желаниях

**Comment by Grian59** [comment]
Что значит в поиске одновременные пометки у некоторых девушек и вирт зеленым и реал красным?

**Comment by Grian59** [comment]
Много без имени только возраст. Это все, видимо, кто оставил себе "Девушка", без имени?

**Comment by avkHV** [comment]
После последнего обновления все стало совсем неудобно. Открыть страницу пользователя, которому хочешь написать стало неудобно. При использовании поиска непонятно, кто онлайн, а кто нет.
Было бы неплохо расширить возможности поиска. Как минимум добавить статус пользователя "онлайн" в поиске.

**Comment by Grian59** [comment]
Разница была в цвете для девушек, которые ищут девушек. Сейчас этого нет. ) Неудобно

**Comment by tebaly** [comment]
поправим

**Comment by Grian59** [comment]
Желания (количество есть), а в окна всплывающего нет. Виден перечень только при написании сообщения. Не очень удобно.
Нет пометки онлайн

**Comment by tebaly** [comment]
@Grian59 - так и задумано. Для быстрого просмотра нужно кликнуть.. Для детального, кликнуть дальше на просмотр анкеты. Из главной страницы _возможно_ тоже пропадут "всплывающие" списки желаний. Как было замечено ранее - они довольно глючно сделаны* и наладить вряд ли получится.

---

* результаты поиска с просмотром анкеты не связаны. В теории это два разных сервера со своими собственными правилами кэширования. Так результаты поиска _иногда_ можно легко кэшировать на 5-15 **дней**. Анкета же может меняться хоть каждую минуту и наоборот. "Пересобирать" результаты поиска на каждый чих в _желаниях_ - бред... То, что раньше можно было посмотреть "всплывающий" список, это как "попробовать".. Попробовали - не получилось. Теперь убираем...

**Comment by tebaly** [comment]
#436
