### ISSUE TITLE
Как общаться?

### ISSUE THREAD

**Issue by z-igor** [freedomsex/freedomsex#435]
Есть уведомление, щелкаю по нему и пусто. Как общаться?

**Comment by avkHV** [comment]
Если в "Знакомства", то такое бывает в том случае, если сообщение которое вам отправил собеседник нарушило правила сайта и было удалено модераторами. Поэтому и пусто)

**Comment by z-igor** [comment]
Не только в "Знакомства", так же и в "Общении". Короче ерунда.

**Comment by tebaly** [comment]
это не столько уведомление, сколько просто "посмотри меня"
