### ISSUE TITLE
Логика "Уже знакомы" изменена

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#436]
Раньше это было не очевидно, и понять можно было только по наличию истории сообщений. Сейчас всё осталось по прежнему не очевидно... История переписки удаляется. Мы просто ..барабанная дробь.. соединили сущности **анкета просмотрена**, _"уже написано"_ и _"уже знакомы"_
* В поиске все просмотренные анкеты - _серополупрозрачные_, но это не точно.

**Comment by SVIT-Lanka** [comment]
Вопрос:  девушки в оттенках серого в поиске - это что?)
Полупрозрачные просмотренные вроде работают.

**Comment by tebaly** [comment]
Девушка хочет девушку, а вы парень. Вы когда начимаете, вам об этом сообщается :pray:

**Comment by SVIT-Lanka** [comment]
Ага.. А если я девушка, значит серенькие - это девушки, которые ищут только парня... Понял, спасибо)

**Comment by tebaly** [comment]
> А если **я девушка**, значит серенькие - это девушки, которые ищут только парня... **Понял**, спасибо)

Тут зависит от того, кого ищите(пол/пиписька). Когда не совпадает - серенько.

**Comment by tebaly** [comment]
#430
