### ISSUE TITLE
Новый дизайн - Быстрое общение

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#437]
Объедините окно анкеты и быстрого написания сообщения при клике из поиска. Всё таки важно видеть анкету прежде чем написать.

**Comment by KILLER1974** [comment]
согласен - было бы удобненько

**Comment by SVIT-Lanka** [comment]
Только не в окно быстрого ответа это все! Оно и так на экране не помещается.
Я все-таки предлагаю убрать из него желания.

**Comment by mj4444ru** [comment]
у вас такой маленький экран? зачем вам что бы посещалось на экране? пальцем не сложно скролить, одно движение пальцем и всё...

**Comment by SVIT-Lanka** [comment]
Я уже писала в другой теме, экран не маленький, но если желаний много и/или текст сообщения большой, то это окно выходит за пределы экрана. Ни закрыть, ни отправить. Такие сообщения бывают не так уж и часто, но все же... 
И оно не скроллится. 
Куда там еще анкетные данные впихнуть?

**Comment by tebaly** [comment]
> Всё таки важно видеть анкету прежде чем написать.

Кому важно? Откуда получены данные, и какие реальные цифры?

![image](https://user-images.githubusercontent.com/9466814/28087161-2d5fe0b8-668a-11e7-92fc-7a825f1cf705.png)

**Comment by tebaly** [comment]
#430
