### ISSUE TITLE
Сообщение при поиске

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#438]
В настоящий момент, при каждом открытии поиска появляется сообщение "Поднятие в топ бесплатно... бла-бла-бла". Можно ли его как-то отключить? Или не показывать, к примеру, после 3-х подтверждений. Меня потихоньку это сообщение начинает бесить :-)

**Comment by Reydan46** [comment]
И сообщение "Контроль содержания отсутствует" при просмотре фото, так же начинает напрягать.
Спрашивает снова, при обновлении страницы.

**Comment by tebaly** [comment]
Исправлено, тестирую
