### ISSUE TITLE
баг с именем и полом

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#439]
![image](https://user-images.githubusercontent.com/19651618/28017350-900c3252-6581-11e7-8255-83ff88214b41.png)
![image](https://user-images.githubusercontent.com/19651618/28017416-cc7ff80e-6581-11e7-9316-84b967b99907.png)

**Comment by tebaly** [comment]
Кэш, я думаю...

![image](https://user-images.githubusercontent.com/9466814/28067861-afbdb95c-664b-11e7-867b-e61b594a1de7.png)

**Comment by inquisitor6789** [comment]
для разных аккаунтов и для разных сайтов один кэш? или речь идет про кэш на сервере?

**Comment by tebaly** [comment]
Общий. Так точно. На сервере

**Comment by tebaly** [comment]
> для разных аккаунтов 

Это как? Там же как я понимаю для разных акков разный баг и бажит не все анкеты?..

**Comment by inquisitor6789** [comment]
> Это как? 

первый скриншот из админского акка
второй с фейковой анкеты

**Comment by tebaly** [comment]
аккаунт пользователя то один. страница из кэша, в админке без кэша

**Comment by tebaly** [comment]
@inquisitor6789 - что мы решили?) Кэш или баг?..

**Comment by inquisitor6789** [comment]
тебе виднее что это...
для меня это выглядит как баг

**Comment by tebaly** [comment]
Но сейчас там Максим 30 - значит кэш. Кэш анкеты живет всего 5 минут. Можно сделать инвалидацию, но ~~лень~~ сейчас нет времени.

**Comment by tebaly** [comment]
Появилась идея использовать расхождение в кэше в админке, но это фитча поверх нестандартного поведения..
