### ISSUE TITLE
Глюк с фото

### ISSUE THREAD

**Issue by monkklan** [freedomsex/freedomsex#440]
Так по порядку, глюк следующий, если отправить фото, и после того как оно успешно отправится тут же написать сообщение, то вместо этого сообщения при нажатии на кнопку отправить, отправляется всё то же только что отправленое фото, и так до бесконечности пока в данный чат не перезайти. Сайт qrsex, браузер мобильный Сафари на ипаде.

**Comment by monkklan** [comment]
На фридомсексе тоже самое

**Comment by tebaly** [comment]
Исправлено, тестирую/обновляю
