### ISSUE TITLE
Если критических багов нет - я готов всё поломать снова!)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#442]
Уважаемые Администраторы и пользователи. Если за время "тестирования" нового интерфейса не осталось критических багов, я добавлю роуты, исправлю пару косяков с версткой и выкачу по всем серверам :see_no_evil: #430

**Comment by KILLER1974** [comment]
можно добавлять - потом по факту будем вносить коррективы.

**Comment by tebaly** [comment]
Ой, я то багов добавлю :honeybee:

**Comment by SVIT-Lanka** [comment]
Ждемс :-)

**Comment by drvalera** [comment]
Все чаще замечаю, что народ хочет видеть свои отправленные сообщения. Что с этим будет в дальнейшем, вернутся ли отправленные сообщения в разряд видимых?

**Comment by tebaly** [comment]
Добавлены роуты/пути к переходам между "окнами". Теперь адекватно работает навигация браузера/устройства.

**Comment by SVIT-Lanka** [comment]
Ссылка "Уже есть анкета" во всплывающем окне перестала работать.

**Comment by tebaly** [comment]
у меня работает...

**Comment by SVIT-Lanka** [comment]
Таак... а куда пропал текст сообщения из окна быстрого ответа?)

**Comment by SVIT-Lanka** [comment]
И обновления нет во вкладке Знакомства, какие просмотрел, на какие ответил... Те, на которые ответил пропадают только после обновления стр., просмотренные так и остаются с кружочками.

**Comment by tebaly** [comment]
Исправлено, раскатываю..

**Comment by tebaly** [comment]
Увеличил присланные фото в галерее, добавил заголовки

**Comment by SVIT-Lanka** [comment]
Предложение по желаниям: сделать поле свободно редактируемым, не выбор из списка.

**Comment by tebaly** [comment]
желаниями займусь дня через два. не до них пока :)

**Comment by SVIT-Lanka** [comment]
Ок)
Еще есть такой глюк, когда удаляешь сообщение или фото в диалоге, "удаляется" первое сообщение в окне, а не то, по которому кликнул. И так по порядку сверху вниз, даже если удаляешь рандомно. Так отображается. При обновлении стр. показывает нормально, те, что реально удалил.

**Comment by tebaly** [comment]
ок. исправлю

**Comment by drvalera** [comment]
Народ интересуется, можно ли лесбиянок в отдельных список запихнуть)

**Comment by tebaly** [comment]
Примите за официальный ответ: "Если исключить эту группу из основного поиска, там мало кто останется. Учитывая, что бывает так, что под анкетой девушка-девушку сидит парень(виртуал/фетишист/...) - зачем им облегчать жизнь?)"

Цель проекта: знакомства мальчик-девочка. Для геев и лесби мы в лучшем случае запустим отдельный проект. Для пар и свингеров отдельный...

**Comment by tebaly** [comment]
>  удаляешь сообщение или фото в диалоге, "удаляется" первое сообщение в окне, а не то, по которому кликнул.

Исправлено. Тестирую

**Comment by SVIT-Lanka** [comment]
У меня таки эта ссылка не работает...  Сир, проверьте еще раз, будьте так добры:)


![default](https://user-images.githubusercontent.com/29144506/28435733-ebf6b2e0-6d9c-11e7-8ff5-63e29c6f555c.jpg)

**Comment by tebaly** [comment]
А сразу так можно было? Таких ссылок две, равно как и "окон" :smile:
Спасибо, исправил ;)

**Comment by tebaly** [comment]
Уведомления... со звуком :grin:
Добавлены

**Comment by wWolfovich** [comment]
А можно еще вернуть уведомление о входящих на заголовке вкладки?
Как раньше меняющимся текстом или еще лучше динамической заменой favicon на анимированный gif.

**Comment by tebaly** [comment]
@wWolfovich - есть варианты гиф анимации на примете?

**Comment by SVIT-Lanka** [comment]
В Сафари разделы в шапке не отображаются.

**Comment by wWolfovich** [comment]
@tabaly, я что-то пропустил, есть мобильный клиент к сайту? Или ты имеешь ввиду мобильные браузеры? Если второе, то не знаю как на iphone-ах, а в андройде куча браузеров и в том числе с табами и/или заголовками. Да и не все же с мобилок пользуются. Хотя новый дизайн стал дружелюбней к мобилкам.
Гифки готовой нет, но могу попробовать наваять вечером.

**Comment by wWolfovich** [comment]
![favicon](https://user-images.githubusercontent.com/3851790/28516218-7c523068-7071-11e7-9345-4758152fabac.gif)
Вот банально добавил анимацию к тем слоям что уже оказывается есть в нынешнем favicon'е

**Comment by tebaly** [comment]
@wWolfovich - надеюсь запихнуть всё это в приложение

![image](https://user-images.githubusercontent.com/9466814/28519778-91b9d9ac-7075-11e7-801a-32baa2a9fdd0.png)

**Comment by wWolfovich** [comment]
@tebaly отличная идея, сам давно подумывал об этом. Есть не большой опыт под андроид. А у сайта есть какое-то API? REST?

**Comment by tebaly** [comment]
@wWolfovich - пишется. Медленно, бажно, но пишется...

**Comment by tebaly** [comment]
#448 - новая обнова

**Comment by tebaly** [comment]
@SVIT-Lanka - в 9/10 сафари всё норм :confused:
Более ранние не рассматриваются, их меньше 1%
