### ISSUE TITLE
достижения

### ISSUE THREAD

**Issue by KILLER1974** [freedomsex/freedomsex#443]
Специально сутки просидел на модерации. В итоге потерял 2 уровня и не стал администратором.
Вопрос: это такое поощрение???

**Comment by tebaly** [comment]
Да. Нельзя сутки сидеть на модерации (!)
* отекают ноги
* устают глаза
* начинает неметь правая рука

А ещё, просто нельзя всё в одно лицо модерить - это не красиво...

**Comment by KILLER1974** [comment]
Спасибо за ответ! больше вопросов нет!
