### ISSUE TITLE
Недостатки

### ISSUE THREAD

**Issue by Grian59** [freedomsex/freedomsex#444]
1. Желания. Ввести больше чем 8 символов новых желаний невозможно. И яндекс и хром
2. Написать для знакомства в Яндекс браузере невозможно. Просто не отсылает. В хроме работает
3. В мобильной версии Хрома нет поиска. Просто пустой экран. В яндексе - работает.
4. Так и нет оповещения о новых сообщениях.

**Comment by tebaly** [comment]
Спасибо. Проверю

**Comment by tebaly** [comment]
> В мобильной версии Хрома нет поиска. Просто пустой экран.

Там важно Версия ОС и версия Хрома. Как вариант, значения в настройках "необычные"..
**Попробуйте** там где пустой экран, изменить все наcтройки поиска. Так как я проверил "мобильный Хром **58.0**":
* :white_check_mark: андроид 4.3 Samsung Galaxy Note 3
* :white_check_mark: андроид 4.4 Nexus 5 
* :white_check_mark: андроид 7 Nexus 6P

**Comment by tebaly** [comment]
>  нет поиска. Просто пустой экран. 

Спасибо, баг нашел. Проблема в "старых" браузерах, точнее... В коде шаблонов использован новый синтаксис ES6.. В коде он адаптируется под ES5 автоматически, а вот в шаблонах нет... Поправлю

**Comment by tebaly** [comment]
аттач #424

**Comment by tebaly** [comment]
Поиск поправлен, доступен в тесте. #442 - С желаниями пока так. Написать сообщение проверю.

**Comment by tebaly** [comment]
> @Grian59 - Написать для знакомства в Яндекс браузере невозможно.

И сейчас также? Уточните версию браузера пожалуйста, и ОС.
