### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Grian59** [freedomsex/freedomsex#445]
1. Желания. Ввести больше чем 8 символов новых желаний невозможно. И яндекс и хром
2. Написать для знакомства в Яндекс браузере невозможно. Просто не отсылает. В хроме работает
3. В мобильной версии Хрома нет поиска. Просто пустой экран. В яндексе - работает.
4. Так и нет оповещения о новых сообщениях.

**Comment by tebaly** [comment]
#444
