### ISSUE TITLE
Замечания и жалобы

### ISSUE THREAD

**Issue by Grian59** [freedomsex/freedomsex#446]
Как правильно жаловаться в новом интерфейсе?
Рядом с сообщением находятся рука с пальцем вниз (синяя) и крестик. Хочу пожаловаться. Что нажимать? Если руку - попадет ли жалоба к админам?
Раньше была ссылка "замечание" и выпадающее меню. Это будет или нет?

**Comment by mj4444ru** [comment]
мне кажеться и так понятно, палец это типа отстой, а крестик просто удалить... а о том куда это попадёт в как пользователь не должны думать...

**Comment by Grian59** [comment]
Попробовал, протестировал. Уже как час прошел, не попало пока в админку. Поэтому и спрашиваю.
Дело в том, что и после нажатия на крестик и на руку возникает одно и тоже окошко об удалении данного сообщения.

**Comment by tebaly** [comment]
Загляните в исходники - там весело :)

**Comment by tebaly** [comment]
#354 аттач
