### ISSUE TITLE
Звук на входящие сообщения

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#447]
Если у кого есть предложение "заменить" звук на другой (like Tinder, etc) прикрепите здесь ссылку пожалуйста на ваш вариант.

**Comment by KILLER1974** [comment]
зачем? какая разница каой сигнал приходит...

**Comment by drvalera** [comment]
Самое главное что он приходит. Вполне нормально!

**Comment by tebaly** [comment]
#448 - ветка закрыта, но варианты по желанию кидайте сюда :relaxed:
