### ISSUE TITLE
Фильтр желаний - разработка/тест

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#448]
На дев сервере тестирую "Фильтр желаний" бета 
* True SPA, come :sunglasses:
* Ещё ближе к мобильному приложению
* Исправлены баги поиска

**Comment by tebaly** [comment]
Раскатил почти везде. Сообщите пожалуйста о багах.. они есть...

**Comment by drvalera** [comment]
При повторном нажатии "Поиск", страница не обновляется..

**Comment by tebaly** [comment]
Добавлю авто обновление. Спасибо.

**Comment by drvalera** [comment]
При открытии переписки из "Общения", окно открывается у первых, а не последних пришедших, приходится крутить вниз постоянно

**Comment by tebaly** [comment]
@drvalera - исправил, выкатываю.

**Comment by drvalera** [comment]
Вопрос до кучи. Тех кого смотрел или писал человек выделяется серым. А вот желтым тоном что за пользователи выделяются в списке поиска?

**Comment by tebaly** [comment]
Так ведь _"Фильтр желаний"_ :relaxed:

**Comment by drvalera** [comment]
Почему то не работает кнопка "Уже есть анкета?", если в профиле в правом углу сверху нажать

**Comment by tebaly** [comment]
Роутер - я в нём косячу, и то и дело что-то перестает открываться :sweat:

**Comment by tebaly** [comment]
- [ ] Время от времени около Общения и Знакомств появляются кружочки, хотя никто ничего не писал.
- [ ] Один из скриптов на сайте жрёт дико память, если не трогать сайт минут 15.
- [ ] Фотки если загружаешь, с новым дизайном нельзя удалить.
- [x] И верните звуковое оповещание или хотя бы мигающее название, а то приходится за этим мелким кружочком следить :/ Если как раньше окошко должно появлятся и пикать, то оно нифига не появляется.
- [ ] Сайт классный, но народа не так и много, порекламировать его было бы хорошо. :)

**Comment by SVIT-Lanka** [comment]
На главной отображаются контакты по критериям поиска.

**Comment by SVIT-Lanka** [comment]
Насчет пожирания памяти - поддерживаю! Каждые 15 минут надо обновляться...

**Comment by mj4444ru** [comment]
это рунетки...

**Comment by tebaly** [comment]
Поддерживаю :thumbsup:
Я им стописят раз писал...

**Comment by drvalera** [comment]
Какая то ерунда, за последние полчаса сайт сам по себе издал звуковое уведомление 3 раза, причем ни в знакомства, ни в сообщения ничего не прилетало,.. загадка

**Comment by tebaly** [comment]
>На главной отображаются контакты по критериям поиска.

 @SVIT-Lanka - главной как таковой нет. Это одна и та же страница с одними и теми же настройками поиска.

**Comment by tebaly** [comment]
@drvalera - больше не появлялось подобного? Оно могло быть так, что вы с телефона или другого устройства одновременно читали.

**Comment by drvalera** [comment]
На данный момент нет. Сидел только с компа, с оперы. Может быть такое, что пользователя заблокировал, а он когда писал был только звук, без сообщения?

**Comment by tebaly** [comment]
Система уведомлений сейчас самая ненадежная, работает без каких либо гарантий.
* Но есть плюс - она уведомит когда письма нет с гораздо большей вероятностью, чем наоборот.

**Comment by drvalera** [comment]
Радует тот факт, что хотя бы уведомляет) А то сидишь как дурак просматриваешь верхушку на наличие кружка)

**Comment by drvalera** [comment]
Ппц сколько левака летит в Юлькино окно помощника. Устал темы закрывать....

**Comment by tebaly** [comment]
Я виноват)) Я когда захожу под ее анкетой, она в поиск вылазит как Пользователь... Система помощи будет относительно скоро переработана. Прошу прощения за неудобства.

**Comment by drvalera** [comment]
А через помощника реально добраться до Администратора? А то я свой статус отслеживаю через вкладку пользователи, там процент достижения выше 82% не поднимается...

**Comment by tebaly** [comment]
Попробуйте делать меньше модерского и больше админского. Вырастет

**Comment by tebaly** [comment]
Пофиксил баг с поиском/настройки. Некоторые мелкие фиксы. На тестах.

**Comment by drvalera** [comment]
лорд tebaly зашел, Юля здравствуй куча сообщений)

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/28755457-1d88bd0c-7564-11e7-9291-0cb270991e5c.png)

**Comment by inquisitor6789** [comment]
>  она уведомит когда письма нет с гораздо большей вероятностью, чем наоборот.

а поменять плюс и минус местами не пробовали? :-)

**Comment by tebaly** [comment]
@inquisitor6789 вот ведь эта привычка к краткому изречению... Какой плюс, да на какой минус? В каком компоненте и в какой строке кода?)
* так ведь получится, что не уведомит, когда письмо есть, до тех пор, пока не откроешь. А учитывая, что не откроешь, пока не уведомит, так и не уведомит никогда...

**Comment by inquisitor6789** [comment]
@tebaly 
так если сейчас ложных уведомлений больше чем нужных, то надо не слать уведомление когда его согласно текущему алгоритму надо слать и наоборот. Поменять полярность так сказать...
а в какой строчке это тебе должно быть виднее :-)

**Comment by tebaly** [comment]
Добавлено функций "идентификации"

**Comment by tebaly** [comment]
> Верн те старую версию
во уроды--вы что с сайтом делаете?

Обновление теперь везде :smiling_imp:

_PS: с каждым обновлением все хуже, прекратите... новый интерфейс абсодютно неудобен_

**Comment by drvalera** [comment]
Не знаю, уже нормально вроде обвыклись все) но крики насчет кнопки модерирования теперь начались

**Comment by tebaly** [comment]
Сегодня добавлю..

**Comment by inquisitor6789** [comment]
гыгыгы, а зачем оно если не работает механизм жалоб?

**Comment by evgad** [comment]
Хоть здесь дайте ссылку на интерфейс модератора!... я вчера думал браузер глюканул и всю историю грохнул(((

**Comment by evgad** [comment]
И еще... в "общении" сделать отметки кто онлайн а кто нет! А то пока в анкету залезешь, пока разглядишь(( очень не удобно((((

**Comment by inquisitor6789** [comment]
> ссылку на интерфейс модератора!.

<имя сайта>/security/action
только там сейчас делать нечего. система жалоб не работает

**Comment by evgad** [comment]
Спасибо!!! Пусть будет) а то когда еще самый главный админ новую выпилит и приклеит))) а так хоть кого-нить от ника очередной раз от ника избавлю)))

**Comment by evgad** [comment]
И еще...  если сделать возможным подключение к диалогу новых участников из списка контактов? Что об этом думаете?.... скажем так- комната на 3-5 человек?

**Comment by tebaly** [comment]
> скажем так- комната на 3-5 человек?

NO :)

**Comment by evgad** [comment]
NO :)   .... эх жаль, столько девушек, мечтающих о вирте с групповым изнасилованием, страдает)))... Ну да ладно, о деле: цветом надо выделять весь ник а не только возраст. Если возраст не указан, то не понятно кого ищут

**Comment by tebaly** [comment]
@evgad - просто сайт не для "общения", а для знакомства. Так как вирт и групповой чат это больше про общение, а не про знакомство, то и не нужен он. Про цвета годное замечание, спасибо :wink:

**Comment by tebaly** [comment]
Исправлена верстка в форме сообщений и меню - на "не хром" браузерах плыло..
* сайт по прежнему дичайше выглядит на динозаврах младше 4.4 андроида 
    * в родном браузере, но в установленных - всё норм

**Comment by tebaly** [comment]
#452

**Comment by drvalera** [comment]
Подниму опять тему. Скачал сейчас последние возможные браузеры из appstore на свой ipad mini во всех не скролятся сообщения верхние вижу, нижние никак, скролится хадний фон и все. Уже не знаю что пробовать. Обычно сижу с Яндекса. Пробовал Хром, Safari, Лису, какой то mx5. Везде скроллится фон. Need help.
