### ISSUE TITLE
Нейронная сеть на желания

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#449]
Были желающие поработать с нейронной сетью. Вы ещё остались?
* стильно, модно молодежно
* много хайпа вокруг этой темы

Можно скормить базу данных по желаниям в "такую" нейросеть, чтобы она помогла разобрать списки более конкретно. Нужна помощь.

**Comment by inquisitor6789** [comment]
а какой результат нужен?

**Comment by tebaly** [comment]
новая гламурная зависимость в проекте :heart_eyes:

**Comment by tebaly** [comment]
нет. очевидно же..

**Comment by inquisitor6789** [comment]
совсем нет

**Comment by tebaly** [comment]
вам что, нейронные сети не интересны?) интересно же :stuck_out_tongue:
я поковыряюсь точно. ищу единомышленников для группового с..

**Comment by tebaly** [comment]
> Верн те старую версию
во уроды--вы что с сайтом делаете?

Обновление теперь везде :smiling_imp:

**Comment by tebaly** [comment]
#380
