### ISSUE TITLE
отображение новых сообщений

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#450]
заметил такой маленький косячок, что когда открываешь переписку с мобильного, то показывается самое верхнее (наиболее старое) сообщение. Для просмотра нового надо прокрутить вниз. Это несколько не удобно.
Либо измените сортировку сообщений, либо сделайте чтобы показывалось новое сообщение без прокрутки

**Comment by tebaly** [comment]
вы уверены? Как давно заметили?
* это было исправлено день-два назад

**Comment by tebaly** [comment]
https://github.com/freedomsex/freedomsex/issues/448#issuecomment-317510768

**Comment by drvalera** [comment]
Подниму опять тему. Скачал сейчас последние возможные браузеры из appstore на свой ipad mini во всех не скролятся сообщения. верхние вижу, нижние никак, скролится задний фон и все. Уже не знаю что пробовать. Обычно сижу с Яндекса. Пробовал Хром, Safari, Лису, какой то mx5. Везде скроллится фон. Need help.

**Comment by tebaly** [comment]
все не надо - хром какой версии?

**Comment by drvalera** [comment]
61.0.3163.73

**Comment by tebaly** [comment]
Статистика по устройствам iPad в рамках средних значений по ресурсу. Понятия не имею что у вас с ним не так, и сколько таких же счастливчиков. У нас физически нет возможности отлаживать работу сайта под все устройства, даже под большинство... 
* Если вы докопаетесь до причины, и сможете найти решение - сообщите, мы исправим.
