### ISSUE TITLE
не работает механизм жалоб

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#451]
При клике на дислайк в переписке появляется предупреждение "Удалить навсегда бла-бла-бла" если подтвердить, то сообщение просто удаляется.
Не появляется ни в списке свежих жалоб, ни в профиле нарушителя....
браузер хром Версия 60.0.3112.78 (Официальная сборка), (64 бит)
на других браузерах тоже самое

**Comment by inquisitor6789** [comment]
мама - анархия, папа - стакан портвейна
второй день полета без модеров и админов... судя по количеству всякого левака в именах и городах там сейчас творится ад
@tebaly  чинить будешь? или как в прошлый раз?

**Comment by tebaly** [comment]
Да. Сегодня. Прост не получилось пока...

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/28925062-68f96312-786c-11e7-8020-05954b138c8a.png)

**Comment by tebaly** [comment]
> второй день полета без модеров и админов...

в разработке, dev

**Comment by inquisitor6789** [comment]
пляя.... и зачем это если нет ни одной жалобы?

**Comment by tebaly** [comment]
Так много желающих помочь мне с микросервисами)) так приятно :relaxed:
Не могу я так быстро кончить

**Comment by inquisitor6789** [comment]
> Так много желающих помочь мне с микросервисами))

а мужики-то не знали...

**Comment by tebaly** [comment]
Исправлено. dev
