### ISSUE TITLE
UI/UX - нипанятнаничево...

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#452]
> Как открывать анкету собеседника??? КОГДА ВАШ САЙТ НАЧНЕТ НОРМАЛЬНО РАБОТАТЬ????? С КАЖДЫМ РАЗОМ ВСЕ ПАРШИВЕЙ И ПАРШИВЕЙ!!!!!

> Как же Вы учитываете?, если большее число пользователей не довольны необоснованными переменами формата сайта... Еще весной было нормально потом сделали не понятно что.. А сейчас вообще все паршиво!!! И к стати загляните на страницу пользователя, слева от окна общения нет не какой возможности открыть анкету собеседника!!!

> У Вас я так понял все меньше грамотного персонала??, поэтому Вы и упрощаете до неприятного... В прошлую замену формата я почти у всех спрашивал с кем общался и не кто не был доволен переменами.. Думаю Вы понимаете что не довольные в наше время просто уходят.. нежели пытаются что то объяснить или выяснить... Но все та ки я так понял есть те кто как и я написал Вам??? и выразил недовольство, только я так понимаю от этого не чего не изменится?! Просто интересно для чего Вы уродуете сайт?? наверное вам лишние пользователи, или как уже сказал нет грамотного персонала?? Да и к стати я поэтому тут и задержался с зимы потому как сайт был приятен для общения и удобен!!!

> Скажите,куда исчезла кнопка отправка фотографии... Почему изменился дизайн

> Красивый и удобный дизайн, постарались на славу ! Спасибо ! (may be sarcasm)

> каждое изменение только ухудшает интерфейс. особенно для пользования на телефонах, планшетах. (так для них и затевалось..)

> Куда вся переписка делась? Отправляешь человеку сообщение и не видишь прочитано оно или нет.Сайт всё дебильней и хуже становиться.Во всех сайтах переписка всегда видна ,у вас же мало того что она быстро исчезает если с человеком не переписываешься так теперь она вообще исчезла.Как понять вообще что письмо отправлено если переписка вообще не видна.

> Ребят , мне нравится ваш сайт , но после того как вы его обновили на телефоне сидеть на нем стало - настоящем извращением. Прошу вас вернуть прежний дизайн сайт ибо это говно.

:disappointed_relieved: как вернутся в мобильную версию :disappointed_relieved:

:heart_eyes: во уроды--вы что с сайтом делаете? :heart_eyes:

---

Большинство "проблем" у пользователей с нормальными устройствами - они (35-55 лет) не понимают пиктограмм / минимализма дизайна. Как итог, человек видит значек "аккаунт/анкета" и не знает / не понимает, что кликнув по ней, откроется анкета собеседника. Дело привычки судя по всему. Попробуем повысить UX в  этом месте..

Пользователи не понимают "зачем" и хотят вернуть. Но вернуть невозможно, а аргументация слишком сложна для обывателя. Изменения в UI не окончательны, то что пропало может вернуться или точно вернется в течении недели или нескольких дней. Это норма.

Про рассылку фото, когда не просят обсуждали сотню раз. Не исключено, что опция вернется. Но само то, что фото нельзя отправить "до" знакомства - об этом просили...

Ну и самое крутое - старые браузеры, старые устройства, стандартные браузеры древних телефонов - это беда... Достаточно просто установить/обновить браузер, и всё _заработает_. В разработке сейчас, мы немного обогнали действительность. Технология "Flex" которая применяется при верстке шаблонов _не нова_, и поддерживается _всеми_ адекватными браузерами. Только вот НЕ новые браузеры не полностью понимают эту технологию, так как в развитии остались в 2012 году - это было пять лет назад!.. У всех, кто купил телефон до 2012 года (+- год) и _не хочет_ ставить нормальный браузер (зачем мне, у меня есть заводской) - у них проблемы, не у нас... Таких людей не много, и каждый день их становиться всё меньше... Так или иначе они обновляют устройства или браузеры.

_* Баги есть, и их хватает. И когда "баг" не связан с "уникальностью" браузера - он может быть исправлен в течении суток._

**Comment by tebaly** [comment]
Почему мы немного обогнали действительность. Новые технологии очень удобные, и позволяют легко делать веб-приложение. Со старыми технологиями это просто невозможно, и "многие" пытались пилить нативные мобильные Приложения в дополнение к веб сайтам, чтобы предоставить сервис всем потенциальным Пользователям. В настоящее время, необходимость нативного Приложения(Андроид, iOS) как дополнения к сайту теряет свою актуальность. Отчасти благодаря новым технологиям. Просто ещё все Пользователи успевают за прогрессом, и немного отстают. Маленькая жертва в угоду всем тем, кто более расторопный.

Например, Перископ - популярное мобильное приложение - оно в принципе недоступно всем отстающим... И им уже не достаточно браузер обновить... 
Им нужен новый, дорогой телефон :grimacing:

**Comment by 4FortyTwo2** [comment]
Хех, не думаю, что те кто не может обновить браузер прочитают это.

**Comment by tebaly** [comment]
Так это не для них )) Вайтпапер по поводу "обновления" недовольства.

**Comment by tebaly** [comment]
Косяк со списком сообщений поможет кто-нибудь исправить?)

**Comment by 4FortyTwo2** [comment]
Не могу воспроизвести проблему.

**Comment by tebaly** [comment]
Попробуйте Эдж предпоследний и любой Файрфокс

**Comment by tebaly** [comment]
Добавлено "иконок" на быстрый диалог. тест

**Comment by tebaly** [comment]
Желания на главной активны. тест

**Comment by SVIT-Lanka** [comment]
Что там с поиском? Куча жалоб на то, что критерии не работают. У меня на хром/дроид все норм, с другого проверить нет возможности.

**Comment by tebaly** [comment]
Скролл пофикшен - @4FortyTwo2 - благодарности ;)

**Comment by tebaly** [comment]
@SVIT-Lanka - чтобы баг исправить, его нужно сначала воспроизвести.. или скриншотов нормальных заиметь. Пока ничего нет..

**Comment by tebaly** [comment]
@SVIT-Lanka - есть возможность проверить почти на любом устройстве, любой ОС, с любым браузером. Для этого нужно знать устройство/ОС/браузер и их версии того человека, у которого бажит.

**Comment by tebaly** [comment]
@SVIT-Lanka - сейчас исправлю :)

**Comment by tebaly** [comment]
Поиск исправлен. Баг в ночном обновлении был.

**Comment by SVIT-Lanka** [comment]
Благодарю) 
Все ж в жалобах только и пишут, что 'ничегонеработает!', а конкретики от них не добьешься)

**Comment by tebaly** [comment]
Просто "переспрашивайте" о деталях)) Чаще всего пишут всё что спросить.

**Comment by SVIT-Lanka** [comment]
Вы баги исправляете быстрее, чем они отвечают))

**Comment by tebaly** [comment]
Я баги пишу быстрее чем вы их находите :sweat_smile:

**Comment by SVIT-Lanka** [comment]
)))) Пишите, пишите... То ж без них скучно)

**Comment by SVIT-Lanka** [comment]
Кнопка "Удалить контакт" отрабатывает так же как и "Продолжить просмотр". 

![default](https://user-images.githubusercontent.com/29144506/29004786-60b8b844-7ad6-11e7-9e92-8a99724e62d4.jpg)

**Comment by drvalera** [comment]
Короче говоря ***/security/action/ если делать выбор наказывать или нет по этой ссылке, то кнопки не работают!! Кнопки эти работают только в основном диалоговом окне сайта.

**Comment by SVIT-Lanka** [comment]
В окне чата сообщения отображаются... не знаю, как это обозвать, не так, короч)) До нового/последнего скроллить вниз нужно.

**Comment by SVIT-Lanka** [comment]
> Короче говоря ***/security/action/ если делать выбор наказывать или нет по этой ссылке, то кнопки не работают!! Кнопки эти работают только в основном диалоговом окне сайта.

На ПК не работают, с Андроида - все работает и в отдельном окне.

**Comment by drvalera** [comment]
На iOSе тоже не работают, проверено на ipad mini

**Comment by evgad** [comment]
Не прокручиваются сообщения в переписке

**Comment by drvalera** [comment]
Да, перстал скролиться список сообщений

**Comment by 4FortyTwo2** [comment]
Вообще ?

**Comment by drvalera** [comment]
Когла прокручиваешь сверзу вниз то листается задний фон, а не область сообщений в перписке

**Comment by evgad** [comment]
На андроиде 5.0 все работает, на 4.0 не прокручивает.... понимаю что древний, но до недавнего времени все работало

**Comment by evgad** [comment]
И там и там браузер хром

**Comment by SVIT-Lanka** [comment]
На 4.1 все нормально.

Вопрос к знатокам: а нельзя ли отделить скролл в окнах от скролла заднего фона?) Точнее, убрать скролл заднего фона при открытом окне. Неудобненько так как-то)

**Comment by tebaly** [comment]
@4FortyTwo2 @drvalera @evgad - если нет скролла на нормальных браузерах, то кажется мы нашли баг в браузере, и нужно уже им репортить :stuck_out_tongue_winking_eye:

А ежели что-то не работает на динозаврах - так это с недавнего времени норма..

**Comment by tebaly** [comment]
@evgad смотрите https://caniuse.com/#feat=flexbox (Showing all) - если там красненькое, то и не заработает

![image](https://user-images.githubusercontent.com/9466814/29019482-511bbdd2-7b67-11e7-9ea9-0673f711936f.png)

**Comment by 4FortyTwo2** [comment]
@tebaly Android 6.0.1, Chrome 59.0.3071. 125 - скрол работает. Edge - работает, Firefox - работает(но это у меня). На ff/edge раньше встречал этот баг. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 4FortyTwo2** [comment]
Надо  будет проверить в ff nightly.  Ах да, задних скроллится везде.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tebaly** [comment]
рефакторинг. местами возможно появление багов :relaxed:
dev

**Comment by 4FortyTwo2** [comment]
☺️

**Comment by SVIT-Lanka** [comment]
От пользователя:

"Было бы не плохо зафиксировать верхнюю строку с закладками "Поиск", "Общение" и т.п. Или хотя бы сделать кнопки быстрого перехода вверх и вниз страницы. А то когда несколько раз открываешь "Следующие" - мотать на самый верх не очень удобно..."

Дельное предложение, вроде...

**Comment by tebaly** [comment]
Рефакторинг страницы "пользователей" (site.ru/id-user)
Возможно появление багов. Добавляю политоту. dev

**Comment by tebaly** [comment]
фиксированное меню. dev

**Comment by tebaly** [comment]
Полазил по верстке "активити/окна" - баги с прокруткой могут вернуться...
dev

**Comment by SVIT-Lanka** [comment]
1. В анкетах глюки, либо открывает пустую, либо левую какую-то.. (если открывать из Общения, из Знакомств норм).
2. Страница пользователя тоже через раз пустая открывается.

**Comment by tebaly** [comment]
**1. Исправлено**
2. Не смог повторить...

**Comment by SVIT-Lanka** [comment]
Перестали приходить оповещения о новых сообщениях и знакомтсвах.

**Comment by tebaly** [comment]
Оповещение исправил. Пропатчил желания - теперь они активны и в анкетах.
dev

**Comment by tebaly** [comment]
UI - Patch :relaxed:
* Вместо "Смотреть анкету" -> "Анкета"
* Клик по списку желаний в "Быстром диалоге" открывает анкету

**Comment by tebaly** [comment]
@SVIT-Lanka 

Кнопка "Удалить контакт". Изменен UI
* Решение _удалять или нет_ теперь принимает Пользователь после закрытия предупреждения
* Изменены кнопки/поведение. Предупреждение можно "Закрыть" или "Продолжить"

**Comment by tebaly** [comment]
Прикрепляю #458
