### ISSUE TITLE
Общий сбор

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#453]
## Товарищи Администраторы! 

Ломание всего и вся было бы неполным, если бы не поломать основательно админку! Ранее, у основ администрирования был положен камень - _"назначение" Администратором в автоматическом режиме._ Не так давно было ананировано введение системы Кураторов. Сия система обдумывалась и рассматривалась всесторонне. 

### Всеобщая иммобилизация
Для самых прожженых Администраторов будет открыт доступ к закрытому супер-пупер интерфейсу администрирования, который в будущем будет открыт, но до того, только для них. Там избранные Администраторы смогут избрать Администраторов, сделав их таким образом _избранными_. Опроча всего, СуперАдмин наделяется правом блокировать неугодных ему Администраторов на веки вечные, пока иной Администратор не помилует провинившегося.

Таким образом, резюмируя - назначение Администраторов будет полностью ручным. 
* Точные сроки запуска неточные. 
* Все администраторы будут сброшены в пропасть.
* И набраны в ручном режиме заново, до уровня насыщения.

**Уважаемые Администраторы, присмотритесь пожалуйста друг к другу. В какой-то момент, Вам придется выбирать, кому остаться рядом с вами. Настоятельно рекомендую подготовиться, и составить списки "избранных" каждому. Право выбирать будет предоставляться сверху-вниз постепенно.**

**Comment by evgad** [comment]
Хочешь переделать администрирование из квеста в работу на которой все хотят сожрать друг друга?.... на мой (не профессиональный, я только начал проходить этот квест и добрался до кандидата) взгляд сегодняшняя система очень интересна... некоторые моменты надо доработать, например к жалобе прикладывать список желаний жалобщика, а то часто получается он (она) сам провоцирует на нарушение своими желаниями! (грубое и пошлое отношение)

**Comment by evgad** [comment]
Конечно же админы должны контролировать всех ниже стоящих и иметь какие то рычаги воздействия.... например бальная система- баллы начисляются автоматически за активность, но админ может их снять за не правильно принятое решение

**Comment by tebaly** [comment]
> если ваш собеседник просит вас об оскорблениях, или заявляет, что ему это доставляет удовольствие - при поступлении жалоб, ответственность за ведение такого диалога всё равно лежит на вас. Мы не устанавливаем контеста употребления оскорблений. Собеседник может умышленно отправлять жалобы, при этом сообщая о том, что для него любые оскорбления допустимы. Пожалуйста, не используйте наш сервис для БДСМ общения в части доминирования, унижения собеседника, если не до конца уверены в своем собеседнике.

Любой админ снимет вам баллов сколько захочет. Инструмент не доказал своей "крутизны".

**Comment by evgad** [comment]
По поводу бдсм.... было бы замечательно, было бы просто здорово если бы девушки отвечали на "привет, как дела?"... но из-за их малого количества и огромного спроса (делал фейковую анкету, чтобы узнать сколько сообщений приходит- до 1000 в день!!!!!!!) Сообщения многие мужчины стараются сделать максимально интересными исходя из желаний! И получают наказание!!!

**Comment by evgad** [comment]
По поводу админов... ни чего советовать не буду, потому что просто не знаю как они работают сейчас, но напомню историю с варгейминг... они очень круто поднялись на вершину, но так же быстро и рухнули потому что не прислушивались к мнению игроков, спохватились только когда многие от них разбежались....

**Comment by evgad** [comment]
... и все таки про комнаты!- создай прямо на сайте комнату для админов! Где они могли бы разговаривать между собой. Наверняка болшей части здесь в гитхабе нет, потому что регится надо, а оно в лом....

**Comment by KILLER1974** [comment]
Иерархия должна быть! 
"Избранные" - это реально знакомые создателю люди!  
"Избранные"- это адмиистрация, остальные-модерация и функционал должен быть, соответственно разный!

**Comment by KILLER1974** [comment]
более того, нужна система наказаний от малого до большего прегрешения.

**Comment by Grian59** [comment]
Если есть некто "верховный(е)", значит, нужно \ должно быть прописано четко за что наказывать, за что блокировать, Что в вирт относить... До сих пор - кто в лес, кто по дрова. 
Если не будет четких правил, будет "хотели как лучше - получилось как всегда". 

Ну, и реализация.
Вдруг сегодня заработала админка, но не полностью. Но, нажатие на руку пальцем вниз так и не работает как замечание.

**Comment by tebaly** [comment]
Правила есть. Ссылка на главной. Хотите править - милости прошу :clap:

**Comment by Grian59** [comment]
Не, tebaly, это не те правила. Я имею ввиду правила для админов. Что к какому виду запретов относится. 
А правила должны быть прописаны полностью и по сайту. Например по именам, городам. А не прочитал - твои проблемы - блокировка.

**Comment by tebaly** [comment]
@Grian59 - опишите ваше предложение более подробно. Чем больше деталей, тем лучше.

**Comment by inquisitor6789** [comment]
> А не прочитал - твои проблемы

так в том и проблема, что большинство не утруждает себя чтением. Это наиболее видно в разделе вирт. Мало того, что теорию не знают, так еще и на практике лажают

**Comment by KILLER1974** [comment]
Попробую детально описать наказания с юридической точки зрения:
Каждый пользователь сайта вправе писать в сообщениях то, что считает нужным. 
Запрещены оскорбления собеседника в любой форме. 
Запрещено незаконное содержание.(именно: реклама, ссылки на другие ресурсы, деткая порнография, Интим услуги, мошенники и спам наказываются всегда!)

Бывают ситуации, когда сделать выбор крайне сложно. 
(здесь должен принять решение АДМИНИСТРАТОР(А), который подтвердит или опровергнет решение МОДЕРАТОРА(М) и это решение- БЕЗОГОВОРОЧНО!!!)

М, просматривая жалобы и другую информацию, принимает решение, которое другой (М) не имеет права изменять.

**Comment by KILLER1974** [comment]
А имеет прво назначить и снять М!!!(при этом не нужно никаких автоматических уровней роста М)

**Comment by KILLER1974** [comment]
А и М - одна команда, которая контролирует сайт!

**Comment by tebaly** [comment]
@mj4444ru - в законодательном полку прибыло. При возможности, продолжите дискусс тама
https://github.com/freedomsex/docs/issues/6

**Comment by tebaly** [comment]
О, гитхаб тоже обновляется))) 
Теперь эпизоды ~цензуры~ перемещение флуда по веткам остаются в истории

**Comment by evgad** [comment]
Итак, соглашусь! Админов должны выбирать и суперадмины нужны... Но еще- надо немного расширить полномочия кандидатов в админы. И ещё право админам блокировать хотя бы проституток прямо с сайта! Иначе система блокировки слишком долгая, а анкету создать 2 сек! Затопят!!!!!

**Comment by SVIT-Lanka** [comment]
Да админов то активных раз, два и обчёлся, че там присматриваться)))

Evgad, так дискриминация по половому признаку у нас получится)) Блокировать проституток с сайта только мальчики то смогут))

**Comment by mj4444ru** [comment]
опа, меня вспомнили... почитаю...

**Comment by inquisitor6789** [comment]
> Evgad, так дискриминация по половому признаку у нас получится)) Блокировать проституток с сайта только мальчики то смогут))

прям с сайта не уверен, но вот для админа было бы неплохо выдавать блокировки из любого места пока идет голосование. Или хотя бы иметь ссылку на профиль рядом с жалобой

**Comment by tebaly** [comment]
@evgad @inquisitor6789 @SVIT-Lanka - #46

**Comment by inquisitor6789** [comment]
идее больше года, а воз и нынче там

**Comment by tebaly** [comment]
А у меня только две руки и один член. И хоть очень похоже, но членом я кодить ещё не научился)) 
* В приоритете до сентября-октября Интерфейс пользователей
* Вероятно будет запущено приложение, но это не точно
* Админка, отошла. На второй(третий) план :sweat:

Интерфейс пользователей переписан полностью. Это само собой очень много работы. Кроме того, мы так и не ответили на блокировки. И готовим свой несимметричный ответ.

**Comment by tebaly** [comment]
@inquisitor6789 - перед тем, как давать админам право перманентного блокирования, состав админов нужно привести к соответствие. В данный момент кроме вас, адекватных, там хватает и ботов и засланцев, готовых по команде сделать бо-бо.

**Comment by Grian59** [comment]
> В данный момент кроме вас, адекватных, там хватает и ботов и засланцев, готовых по команде сделать бо-бо.

Даже так? А какой в этом смысл?

**Comment by inquisitor6789** [comment]
> А какой в этом смысл?

сделать бо-бо))

**Comment by Grian59** [comment]
Чтобы делать БО-бо нужно делать конкретному человеку. ))) Ну ладно, есть и есть, не буду спорить. 
Дети гор, дикие люди, однако!

**Comment by tebaly** [comment]
> сами же признавались

На этом только весь проект и держится :joy:

`<шутка></шутка>`

**Comment by KILLER1974** [comment]
повторюсь - админы не должны изменять решение другого админа!

**Comment by inquisitor6789** [comment]
обоснуйте
например по какой причине надо было этого человека блокировать?
http://freedomsex.me/userinfo/profile/33885891/

**Comment by tebaly** [comment]
@inquisitor6789 большая просьба, не тяните пожалуйста сюда "внутренние" дела для обсуждения причин и мотивации принятых решений. Благодарю.
