### ISSUE TITLE
старые идентификаторы

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#456]
есть анкета http://freedomsex.me/userinfo/profile/4114510
по ее ИД видно что она древняя (старше 2-х лет)
однако в профиле значится, что ее возраст 28 дней.
это как? начали свободные идентификаторы повторно использовать?

**Comment by mj4444ru** [comment]
короткие номера уже можно купить?))) 

а если серьёзно, наверно глюк... типа анкета удалилась, а данные авторизации нет, потом восстановилось когда юзер зашел...

PS: ни чем необоснованные догадки...

**Comment by tebaly** [comment]
А не повтор? #416 :cat:
