### ISSUE TITLE
Политота в проекте...

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#457]
> На самом деле _это_ не связано с политикой. И больше похоже на демократию. Часто встречаются слова _власть_, _выборы_, _голосование_, _конституция_, но никаких отсылок к какой-либо стране, Лидеру или представителям власти там быть не должно. Если найдете, я исправлю ошибки.

Как бы, это _наш_ несимметричный ответ на _санкции_. Выражен в отдельном, _свободном_ проекте так или иначе реализующем идеологию Revolter(чего уж там скрывать, тоже наш проект). Если кто-то читал Манифест проекта от ~2009 года, там есть отсылка к реализации всего _этого_. Поэтому причинную связь между блокировками усмотреть можно, но её де-факто нет, так как работа уже над этим проектом была начата в феврале 2014 года.

С одной стороны, участники Сообщества включая Администраторов вправе отказаться от участия в данной социальной активности. Но, по мнению разработчиков, всё то _счастие народа_ которое можно наблюдать почти на всём постсоветском пространстве, и есть результат права каждого отказаться от социальной активности. То есть, обладая добровольным правом, участия или не участия,  _большинство_ решило заняться чем-то своим - что уже было _большой_ ошибкой.

[rev.freedomsex.net](http://rev.freedomsex.net/) - у вас ещё не заблокировано? :grin:

_PS: не могу сказать за всех провайдеров, но блокироваться не должно._

**Comment by tebaly** [comment]
## Что делать

Если вы разделяете точку зрения разработчиков заключающуюся только в том, что "что-то нужно делать, и начинать нужно прямо сейчас". В соответствии с аналагичным разделом текста по ссылке, вы можете:
* **Прочитать** текст. Далее вы должны сделать вывод, с чем вы согласны, а с чем не согласны. И, если для вы с чем-то не согласны, либо **внесите правки** в текст, либо **выскажите критику** в отношении текста, либо **напишите свой** собственный.
* Если вы согласны - **обсудите** текст с теми, кто его ещё не читал. **Распечатайте** текст, дайте почитать друзьям/знакомым, кто _возможно в этом заинтересован_

**Comment by SVIT-Lanka** [comment]
Прям прослезилась, читая историю проекта...

И... у нас уже заблокировано! erblock.crimea.com приносит свои извинения))

**Comment by tebaly** [comment]
@SVIT-Lanka тогда закину на новый домен, просто интересен масштаб :stuck_out_tongue:

**Comment by tebaly** [comment]
https://habrahabr.ru/company/darudar/blog/137825/

**Comment by inquisitor6789** [comment]
не слабо так пропиарился :-)

**Comment by tebaly** [comment]
Это вы о чем?)

**Comment by tebaly** [comment]
Прикрепляю #458

**Comment by tebaly** [comment]
Опубликовано

**Comment by tebaly** [comment]
https://www.youtube.com/watch?v=BFE3oJq4Ods
