### ISSUE TITLE
Патчим#патчи

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#458]
Начинаю раскатывать новое обновление. 
* Рефакторинг старого кода
* Изменение "страницы" Пользователей (SEO)
* Активные желания
* Фиксированное меню
* Патчи и фиксы найденных багов
* Политота

**Comment by tebaly** [comment]
Пачиму никто не жалуется? :cry:

**Comment by SVIT-Lanka** [comment]
@tebaly сложно поверить, что все работает?)))

**Comment by SVIT-Lanka** [comment]
У меня вот сообщение остается в поле после отправки... только на oesex

**Comment by tebaly** [comment]
@SVIT-Lanka - да пипец просто. необычно как-то :stuck_out_tongue_closed_eyes:
Проверил на "ое" - сообщение уходит нормально. Сможете повторить?

**Comment by tebaly** [comment]
@SVIT-Lanka - исправлено. Мой косяк.

**Comment by SVIT-Lanka** [comment]
Что-то антиспам у вас получился жесткий)) жалобы посыпались...

http://qrsex.ru/userinfo/profile/?id=8284344
За что этому типу столько капчи и что значат логи [ошибки]?

**Comment by SVIT-Lanka** [comment]
Анкета пустая - 
http://qrsex.ru/44825018/#/
Профиль полный - 
http://qrsex.ru/userinfo/profile/44825018/

**Comment by SVIT-Lanka** [comment]
Предупреждение о мошенниках в чате это, конечно, хорошо, но... или дайте возможность его закрыть или же пусть будет однократным при первом сообщении. А то раздражает как-то потом...

**Comment by tebaly** [comment]
А шо поделать... Там сейчас **требование** не менее 2 ответов от вас к собеседнику. Вполне адекватное требование. Хотелось 5, но вероятно станет 3... 
* Можно долго писать аргументации и мысли, но у нас не чат и не соцсеть - среднестатистическому Пользователю, для которого пишется сайт, это не мешает :sweat_smile:
* Таки это уже было. Раньше тоже было это сообщение. И висело всегда до 5 ответов
    * Но, его _видели только Парни_... Вот уже эту правку вполне можно внести. Я просто забыл :)

![image](https://user-images.githubusercontent.com/9466814/29940763-efba287c-8e98-11e7-9128-dbb9ce5b3e36.png)

**Comment by SVIT-Lanka** [comment]
Погорячилась, простите :)  Все норм, уведомление уходит.

**Comment by drvalera** [comment]
Тут от пользователя поступило предложение сделать так, чтобы новые сообщения отображались сверху, а не снизу как сейчас есть.

**Comment by tebaly** [comment]
А в 90% интернета снизу вверх...
