### ISSUE TITLE
Конфиденциальность общения не гарантирована

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#459]
> Проект и все его сервисы созданы для знакомства с возможностью анонимонго общения и обмена фотографиями. Администрация проекта и разработчики принимают все возможные усилия направленные на защиту данных и информации Пользователей от несанкционированного доступа. Несмотря на все применяемые меры по защите, разработчики не могут полностью исключить возможность взлома систем и сервисов хакерами и/или спецслужбами государств, и несанкционированного доступа к данным хранящимся на серверах. Силы очевидно не равны.

Чтиво: https://github.com/freedomsex/docs/blob/master/deal/003-Конфиденциальность.md

Если коротко
* Мы, разработчики проекта, _не имеем никакой возможности_ противостоять
    * Государственным спец службам(ФСБ, КГБ, СБУ, FBI, NSA и т.д.)
    * Международным группам хакеров. 
    * Высококвалифицированным и сильно мотивированным хакерам, даже в одном лице

Мы принимаем всё возможное, включая галюциногенные психотропы, но мы так много косячим в коде, что это пиздец... Поэтому: _знакомьтесь, общайтесь, обменивайтесь контактами_, а дальше, продолжайте общение где угодно! **Watsapp** - шифрует переписку и НЕ храниет её на сервере вообще. **Telegram** - шифрует всё что может, и обещает не давать ваших переписок никому(его ещё не заблокировали в РФ, как бы намекает). Любой другой сервис, который вы считаете, что его ещё не взломали или не взломают. 

Разработчики напоминают - ломают всех! 
* Windows
* PayPal
* NASDAQ
* Ядерная программа Ирана
* Пентагон
* Сайты 
    * ФБР
    * Белого дома
    * Министерства юстиции США
    * Холдинга звукозаписи Universal Music Group

Это всё было взломано не один раз. 
Не нами конечно, но ломали.

**Comment by inquisitor6789** [comment]
https не рулит? давно об этом говорили. Это конечно не 100% гарантия защиты, но намного усложняет процесс взлома

**Comment by tebaly** [comment]
На взлом серверов вроде не влияет. А уязвимости в коде вполне могут быть - от них это не спасет, их нужно только править. https попробуем прикрутить в сентябре.

**Comment by tebaly** [comment]
Опубликовано

**Comment by tebaly** [comment]
#459
