### ISSUE TITLE
Сделать отправку отпечатков пальцев обязательной, а не только по запросу ФСБ

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#460]
> Добрый день! Предлагаю тему фото в личном общении чтоб не было такого что прошу фото то нету то еще что, я имею виду что вот комне зашел парень на анкету я решила сним познакомится начала переписку но он по каким либо причинам свое фото не показывает то чтоб быть уверенной что эт тот кто есть чтоб в углу сверху было фото как бы обезательно,его акаунта. Почему счас обьясню фото 97% не тех кто есть с гуглино скопиравано тут с других, и получается что при реальной встрече он не он, она не она. [цензура] Может тот кто регестрируется делать так чтоб потверждение телеф было и один акаунт, то 1 чел и по 10 акаунтов лично сама просекла такое. И другое вот я например ищу по городу минску а заходят чуть не с канады, но эт же не реально, значит выдумывают города,. И последнее гео даные сделать обезательным включением. Спасибо вам что есть такой сайт!!! И если можно чтоб добавили смайлики!!!!

Рецензия от довольного Пользователя :relaxed:

**Comment by evgad** [comment]
Прально! Верно подмечено!! А ешо образец спермы, отпечаток языка и члена... И по клочку волос для каждого админа- бум делать куклу вуду и по ней наказывать!

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/29325001-d091c362-81ee-11e7-8da3-f6f4746d7efb.png)

Тогда уже и отпечаток языка на члене для девушек, а то им предъявить то нечего будет

**Comment by tebaly** [comment]
@inquisitor6789 - возьмите аватарку, я там тут принес. А то не гоже такому статуснуму лицу и без аватара :grin:

![image](https://user-images.githubusercontent.com/9466814/29326555-aa9cb0f8-81f4-11e7-8e59-61dfd9ebc45e.png)

**Comment by Grian59** [comment]
А давайте вообще сделаем на сайте не только опечатки пальцев, но и голосовое представление о себе.  Господи, что за бред пишут то...

**Comment by inquisitor6789** [comment]
> @inquisitor6789 - возьмите аватарку

jawohl mein Fuhrer

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/29354876-86e8849c-8277-11e7-962f-ac96bf4dfa30.png)

**Comment by tebaly** [comment]
@drvalera - вот вам аватарка. можете сами, что-нибудь по эротичнее :)

![image](https://user-images.githubusercontent.com/9466814/29405374-5fd629fc-8346-11e7-8c76-696863293fc7.png)

**Comment by tebaly** [comment]
@SVIT-Lanka - это вам. Украсьте профиль на гитхабе :)

![image](https://user-images.githubusercontent.com/9466814/29409310-498ba916-8354-11e7-9e0a-fa8e2a88137a.png)
![image](https://user-images.githubusercontent.com/9466814/29409324-553ccd62-8354-11e7-880b-ae9edd651131.png)

https://www.pinterest.co.uk/saul2627/the-letter-s/
https://www.pinterest.com/pin/494410865315814413/

![image](https://user-images.githubusercontent.com/9466814/29409454-ef1724a0-8354-11e7-8497-cb7eca9fa9c3.png)
![image](https://user-images.githubusercontent.com/9466814/29409457-f544e02e-8354-11e7-9f54-db4e974a720e.png)

**Comment by inquisitor6789** [comment]
не, ей больше эта лучше
[http://chronikigothama.ru/gallery/pic.php?mode=large&pic_id=2204](url)

**Comment by tebaly** [comment]
@inquisitor6789 знает толк :relaxed:

**Comment by tebaly** [comment]
Нужно сохранять анонимность. Я немного обрезал.
![image](https://user-images.githubusercontent.com/9466814/29410631-1273c278-835a-11e7-93c3-e8fc188b464a.png)

**Comment by SVIT-Lanka** [comment]
)))))
@tebaly @inquisitor6789 пасиба, ребята! Принимается!

**Comment by 4FortyTwo2** [comment]
Ааа, что происходит.

**Comment by tebaly** [comment]
Мы тут аватарки друг другу в профиль вставляем :stuck_out_tongue:
Хотите и вам что-нибудь вставим?)

**Comment by inquisitor6789** [comment]
а может и не вставим, а может и не в профиль :smiling_imp:

**Comment by tebaly** [comment]
Или не аватарку 

![image](https://user-images.githubusercontent.com/9466814/29415215-f91d2920-836a-11e7-9873-33f93e3cc9f6.png)

**Comment by 4FortyTwo2** [comment]
Давайте аватарку, только вставлять ничего не надо.

**Comment by tebaly** [comment]
У вас же есть. Или вы хотите две сразу?)

**Comment by 4FortyTwo2** [comment]
Новую хочу.

**Comment by tebaly** [comment]
@4FortyTwo2 

https://s8.hostingkartinok.com/uploads/images/2017/08/cbcdb3dd5ffa3594012c963e129fa360.png

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/29560205-edd3ede2-8739-11e7-8553-f1a4169932f6.png)

![image](https://user-images.githubusercontent.com/9466814/29560214-f4164f24-8739-11e7-82f3-04f3bc74a336.png)

Подрежьте для крупноты)

**Comment by inquisitor6789** [comment]
мсье, вы бы лучше атаку отбивали :-)

**Comment by tebaly** [comment]
Каку таку атаку??. Пропатчил старющие фильтра по спаму. Теперь или спама будет меньше, или с сообщениями у всех будут проблемы :laughing:

**Comment by inquisitor6789** [comment]
[https://github.com/freedomsex/freedomsex/issues/461#issuecomment-323745437](url)

**Comment by tebaly** [comment]
@inquisitor6789 - а вообще, это добрый тестировщик дает просраться проекту, чтобы подлатать дыры. На сколько он добрый, он нам скоро расскажет)))

**Comment by 4FortyTwo2** [comment]
@tebaly Благодарю.

**Comment by tebaly** [comment]
@4FortyTwo2 - жали пайнтом?)

Вот вам наилучшего какчества:
https://s8.hostingkartinok.com/uploads/images/2017/08/636c4578579b6c9f75bcdc4147ed2668.png

**Comment by 4FortyTwo2** [comment]
@tebaly Так гитхаб же жмет, не?

**Comment by tebaly** [comment]
но вы же редактировали. ТМ убрали и сохранили не в PNG судя по всему. И получили двойное сжатие на выходе :open_mouth:

**Comment by 4FortyTwo2** [comment]
В PNG сохранял.
