### ISSUE TITLE
Интерфейс модера

### ISSUE THREAD

**Issue by drvalera** [freedomsex/freedomsex#461]
Заметил баг или не баг, не понял еще.  Короче говоря в "Новых" и "Решениях" пусто уже который день. А дофига вылетает в "Арбитраже". Что может быть?

**Comment by SVIT-Lanka** [comment]
Не знаю, где там у Вас пусто... завал, как всегда)
А в арбитраже дофига, когда кто-то косячит дофига)

**Comment by tebaly** [comment]
там от уровня зависит. чем выше, тем больше - но не всегда прямая зависимость

**Comment by evgad** [comment]
В "новых" первое сообщение зависает и в "решение" не переходит... Приходится выходить на сайт в "защитить" и от туда распределять жалобы

**Comment by tebaly** [comment]
Это да. я это в курсе. исправлю. спасибо

**Comment by inquisitor6789** [comment]
не знаю у кого там и где пусто, но я уже затрахался разгребать это
только несколько минут назад список ожидающих решения стал пуст :-)
но еще вагон и меленькая телега не дошедших до решения,

Кстати, а нельзя ли уменьшить количество необходимых голосов для перевода жалобы из простого голосования дальше по цепочке? Сейчас насколько я могу видеть, требуется около 10 голосов. На мой взгляд достаточно 5

**Comment by drvalera** [comment]
У меня Помощник Админа, но в новом болт совсем)

**Comment by tebaly** [comment]
Там разброс вроде. Если спорно, то до победы, если явно "плохое", то быстрее. А от Резидентов может хватить одного контрольного. Безусловно я буду пересматривать и этот механизм, как только возьмусь за него. Пока у меня руки на другом.

**Comment by inquisitor6789** [comment]
какой-то очень сильный разброс...
http://freedomsex.me/history/message/437393/
и в конце непонятный автосброс в арбитраж уже после вердикта

**Comment by tebaly** [comment]
Мне нужно будет глубже изучить проблему. Так быстро не могу ответить. Напомню, раз уж мы начали так ненавязчиво _копать детали технической реализации_ самого сверх секретного Üeber Алгоритма голосования - та он не блокирует нерадивых модераторов, он _принимает голоса_, но не видит их - наощупь. Поэтому, когда  Üeber Алгоритм пытаются ~наебать~ взломать, мы наблюдаем именно такую картину
* Видимо проект сейчас успешно атакуют, а я наблюдаю за атакой, чтобы выработать механизмы противодействия таким типам атак. Вы только об этом никому не говорите :grin:

**Comment by SVIT-Lanka** [comment]
> Заметил баг или не баг, не понял еще. Короче говоря в "Новых" и "Решениях" пусто...

У меня сегодня с обеда та же беда. Или то благо такое, вроде отпуска в порядке очереди?))))

**Comment by inquisitor6789** [comment]
> У меня сегодня с обеда та же беда.

как так? чего я только один тут работаю? :dizzy_face:

**Comment by SVIT-Lanka** [comment]
> У меня сегодня с обеда та же беда.

@tebaly, брат, братан, братишка, когда меня отпустит?

@drvalera как у вас дела обстоят?

**Comment by inquisitor6789** [comment]
@SVIT-Lanka, у меня тоже что-то сегодня пусто... Видать карма кончилась.
Хотя с другой анкеты видно, что жалоб вагон

**Comment by SVIT-Lanka** [comment]
А рейтинг потихоньку ползет вниз... и никакие другие действия на него не влияют...
Так не только от работы, а и из админов отстранить могут)

Саботаж какой-то или сир tebaly таки перекапывает алгоритм модерки?)

**Comment by tebaly** [comment]
Всё также?..

**Comment by SVIT-Lanka** [comment]
С рейтингом уже все норм. А вот в новых и решениях по-прежнему пусто.

**Comment by tebaly** [comment]
Там "отаке" на интерфейс идёт во всю :shipit:
* Если вы лично (Администраторы/Пользователи) никаких особых "проблем" в этом не видите, то хорошо.
* Я просто использую момент, чтобы оценить степень уязвимости и степень реального ущерба от атаки. Такое бывает всего раз в год.
* Могу "пропадать" делая вид, как-будто меня нет, чтобы товарищи показали всё, что могут.

**Comment by drvalera** [comment]
Завтра днем посмотрю. Сейчас просто только вернулся домой с отдыха. Но на данный момент пусто в Новых.

**Comment by drvalera** [comment]
Итог. На долю секунды замечаю, что в новом что-то есть и следом сразу пишут "Спасибо. Сообщения скоро будут". Как и было на момент создания обращения.

**Comment by Grian59** [comment]
> не знаю у кого там и где пусто, но я уже затрахался разгребать это
> только несколько минут назад список ожидающих решения стал пуст :-)
> но еще вагон и меленькая телега не дошедших до решения,
Я тоже. Проблема не в том, что разгребать, а в том, что пользователь не понимает, что такое жалоба, а что такое удаление.

Предлагаю поменять руку с пальцем вниз и крестик местами. Народ просто тупо жмет на руку, удаляя сообщения. 
И нужно описать для пользователя механизм жалоб.  А то так полдня будем тратить на жалобы типа "Привет, Поговорим?"

**Comment by evgad** [comment]
Поддерживаю! И дополню: завал с жалобами типа: привет начался после изменения сайта... То есть те люди у которых проблема с прокруткой (скролом, если вам так больше нравится) сообщений, вынужденны удалять старые сообщения, чтобы прочитать новые...

**Comment by evgad** [comment]
По поводу взлома! Только что пришло сообщение с несуществующей анкеты! http://sexoo.me/#/intimate/44864551/detail

**Comment by evgad** [comment]
То есть.... Мне написали сообщение, я ввел цифры в командной строке " профиль нарушителя" выдало- анкеты нет!

**Comment by SVIT-Lanka** [comment]
В админке часто мелькают жалобы без привязанной анкеты последнее время...

По поводу 'поменять руку с пальцем вниз и крестик местами' я руками и ногами ЗА :) Сама иногда мимо крестика попадаю. 
Еще такой вопрос, если дизлайк на весь чат (на собеседника), то вся переписка попадает в жалобы?

**Comment by inquisitor6789** [comment]
> И нужно описать для пользователя механизм жалоб. А то так полдня будем тратить на жалобы типа "Привет, Поговорим?"

так оно де вроде описано при подтверждении действия? не?
да и не будут читать! совсем давно (до начала переработки дизайна) была такая же ситуация. Только там текстовые ссылки были - "удалить" и "наказать". Поток жалоб был почти такой же

**Comment by inquisitor6789** [comment]
УРААА!!! ЗАРАБОТАЛО!!! :-)

**Comment by evgad** [comment]
Не знаю... У меня интерфейс модератора висит... Первое сообщение повисает и ни туда и ни сюда.... Ни новые ни решения ни арбитраж, уже второй день

**Comment by inquisitor6789** [comment]
перезайти не пробовал?
на крайняк перезагрузи браузер

**Comment by SVIT-Lanka** [comment]
У меня всё по-прежнему печально....:'(  Арбиртаж работает.

**Comment by evgad** [comment]
Перезашел, переустановил браузер.. все так же, зависает первое сообщение в новых решениях и арбитраже.... Бораузер- хром

**Comment by evgad** [comment]
Упс... Про арбитраж не видел, потому что там сообщений не было... Ща, скину что нибудь, пооверю

**Comment by evgad** [comment]
Нет, у меня арбитраж тоже не работает, сообщение туда отправилось, а решение по нему принять не могу.... Андроид 5.0 браузер хром... Хотя вроде уже говорил

**Comment by tebaly** [comment]
@evgad установите аватарку на гитхабе, это важно)) Вообще, и арбитраж и жалобы работают **не линейно** - если вы чего-то скинули, не факт что вы там это сразу увидите.

**Comment by evgad** [comment]
Сообщение в арбитраже появилось, они и сейчас есть.... Я нажимаю принять какое нибудь решение (наказать не наказать) но следующим выходит это же сообщение и так до бесконечности... Ни куда дальше это сообщение не проходит

**Comment by evgad** [comment]
.... Сейчас с другого браузера попробую...

**Comment by evgad** [comment]
Нет... Та же история!... Интерфейс админа работает без проблем

**Comment by evgad** [comment]
Ещё один интересный момент http://sexoo.me/history/message/407258/
Решение принято моего имени 2 часа назад! Но 2 часа назад я спал!! И никаких решений ( писал выше) принять не могу!

**Comment by tebaly** [comment]
Это давний баг "отображения" - показывает не время добавления, а время обновления, хотя и пишет что "принято"

**Comment by tebaly** [comment]
По теме топика

> Заметил баг или не баг, не понял еще. Короче говоря в "Новых" и "Решениях" пусто уже который день. А дофига вылетает в "Арбитраже". Что может быть?

Проблема ещё есть?? Суть вероятно состояла в "не линейности" списков. 
* по остальным заявленным "багам" подтверждения как я понял не нашлось

**Comment by tebaly** [comment]
Починил

**Comment by SVIT-Lanka** [comment]
КТО, ГДЕ починил?? У меня ничего не поменялось и проблема где была, там и осталась: разделы Новые и Решения пусты... всегда.. Как на сайте, так и в админпанели.
Кого-то кроме Инквизитора попустило? Отзовитесь!)

**Comment by tebaly** [comment]
@SVIT-Lanka дайте ID нужно посмотреть :)

**Comment by drvalera** [comment]
эт мой 2352120

**Comment by tebaly** [comment]
тоже пусто?..

**Comment by drvalera** [comment]
Да, ничего не изменилось. Пустые Новые и Решения, просто моргает какое-то сообщение на долю секунды и все, пустота.

**Comment by tebaly** [comment]
Но вы же не @SVIT-Lanka :stuck_out_tongue_winking_eye:

В принципе, я воздержусь от комментариев, так как работает механизм о котором давным давно просили @mj4444ru и @inquisitor6789 - бага нет, от так работает, как и просили...

**Comment by SVIT-Lanka** [comment]
Дело ясное, что дело тёмное.... Ну, ок.

А есть топик, где сий механизм просится/обсуждается?)

**Comment by tebaly** [comment]
Есть, но я не могу пока в конкретику. Ещё дня два-три не могу, извините пожалуйста.

**Comment by inquisitor6789** [comment]
> В принципе, я воздержусь от комментариев, так как работает механизм о котором давным давно просили @mj4444ru и @inquisitor6789 - бага нет, от так работает, как и просили...

что-то я не помню про такое... про арбитраж - да, было. А вот про голосование не отложилось в памяти
