### ISSUE TITLE
Свободы нет

### ISSUE THREAD

**Issue by KILLER1974** [freedomsex/freedomsex#462]
http://rev.freedomsex.info/under-threat/info#FreedomSex
прочитал от корки до корки и пришла мысль:"Болит судьба сайта, болит!"

Что же делать и как быть??.
Мысли, идеи развития, модернизация и реконструкция сайта приводят всё к новым и новым проблемам. Возникает вопрос:
- Стоило ли ломать, чтобы по-новому всё собирать, как Экклезиаст камни??.
Сам же и отвечу:
- Стоило! Новые технологии, новые требования, новые взгляды на современные тенденции заставляют идти и даже опережать время!

p.s. Большое спасибо разработчикам, что они находят время на всё это дело!!! СПАСИБО!!!

**Comment by tebaly** [comment]
Благодарю за отзыв
