### ISSUE TITLE
Ошибки в работе административной панели

### ISSUE THREAD

**Issue by infman86** [freedomsex/freedomsex#465]
Всем привет.
При нажатии на эти https://prnt.sc/gefden кнопки ничего не происходит, а если использовать эти http://prntscr.com/gefgb2 кнопки, то всё отлично работает
Возможно это только у меня так, пробовал на хроме и голой мозиле.
Каперский выключен на браузерах нет блокировщиков

**Comment by tebaly** [comment]
Да. Это баг, о нем уже сообщали. Попробую сейчас починить. Спасибо.

**Comment by tebaly** [comment]
#461

**Comment by tebaly** [comment]
Исправлено
