### ISSUE TITLE
Доработка фильтра

### ISSUE THREAD

**Issue by infman86** [freedomsex/freedomsex#466]
Предложение такое
Реализовать поиск партнёра по "желаниям и фантазиям"
Эту функцию можно добавить тут http://prntscr.com/gefry9 
Пользователь будет вводить "фантазии и желания" точно так же как и в этом разделе http://prntscr.com/gefw9t
Пользователь вводит желания своего потенциального партнёра и получает только те анкеты в которых есть эти желания, уверен что этот фильтр будет пользоваться спросом.

**Comment by tebaly** [comment]
> уверен что этот фильтр будет пользоваться спросом.

Одной только "уверенности" мало. Проясните пожалуйста вашу точку зрения. Например, какие желания вы стали бы искать. Приведите топ 10 пожалуйста.

**Comment by tebaly** [comment]
@infman86 - поставьте аватарку пожалуйста. Меня это возбуждает к работе)) Вот например(понятия не имею что там написано), но можете любую другую.
![image](https://user-images.githubusercontent.com/9466814/29820433-1b759032-8ccd-11e7-90a9-07b7e5b581f1.png)

**Comment by tebaly** [comment]
@infman86 (Приведите топ 10 пожалуйста.) - если _важно/приватно_, можете на почту скинуть, я никому не расскажу :relaxed:

**Comment by infman86** [comment]
Дополнительный фильтр это всегда плюс, если он не является слишком громоздким для пользователя, это так просто мысль.

Допустим мне нравятся нимфоманки, давать задания, анальный секс, слушать рассказы о сексе, раком и любой другой список запросов который можно продолжать до бесконечности.

Я хочу получить список девушек именно с такими желаниями, а не вращать колесом мышки до высматривая выделенные анкеты. Кстати есть ещё такая штука как пробела с цветопередачей у мониторов, то есть выделения анкет которые есть сейчас могут не эффективно работать, так как их плохо заметно, плюс есть люди со слабым зрением и они тоже могут пропустить эти анкеты.

Помимо этого интернет если можно было бы выбрать к нему одно слово описывающее его сущность это свобода и скорость. Люди не хотят чего либо долго искать, они хотят получить искомую информацию сразу с наименьшим количеством действий. 

Что проще? выискивать помеченные анкеты среди длинного списка или получить список отсортированных анкет без каких либо временных затрат.

То что такой фильтр будет полезет 100%, хорошо подстрахуюсь 99%

Над чем реально стоит задуматься так это над тем где его разместить и в каком виде

Кстати, если на сайте не установлена метрики Яндекса или Гугла советую поставить, чтобы собирать информацию о действиях пользователей, на основе которой можно будет дорабатывать сайт

**Comment by infman86** [comment]
Да я могу скинуть и тут) я тот ещё извращенец) просто наврятли как то помогут в этой задаче)

**Comment by tebaly** [comment]
Попробуйте перейти ~на сторону зла~ на мою сторону. 
* сайт пишется только под **реальные знакомства** - в _одном городе_, с _реальной_ встречей
* если "Вы" (здесь любой Пользователь) хотите что-то _кроме_ - прошу прощения

> любой другой список запросов который можно продолжать до бесконечности

Хотя бы 10, но вы указали только 5.. Нужно больше (20 сейчас на сайте лимитировано), чтобы понять направление, актуальность и техническую необходимость.

---

Например, я, как Темный Лорд, придерживаюсь следующей стратегии
* вы пишите всем онлайн/актив девушкам, к которым ОТСУТСТВУЮТ претензии
    * чаще поступают наоборот, и пишут тем, к кому испытывают интерес, тем самым ограничивая и выборку и свои шансы одновременно
* вы на сайте, и вы пишите здесь - потому как ни один другой сайт вам не подошел
    * равно и традиционные места и способы знакомств вам чужды
        * я предлагаю кроме сайта иную стратегию - **сначала пишите, потом читайте**
* например девушек будет 100 - вы написали всем, ответов пришло 10
    * смотрите анкету, есть ли там _пересечение_ желаний
        * если нет, таки решайте что вам нужно - шашечки или ехать

Из всего сказанного, я не вижу смысла _ограничивать выборку_ по сайту чем-то больше, чем сейчас. То есть, по части желаний - я могу выделить анкеты в списке, желания в анкете - но лимитировать результаты поиска не намерен.

И ежели вы в рядах повстанцев, а так как вы указали _давать задания_, _слушать рассказы о сексе_ - вероятно вы настроены на свидание с монитором больше чем на реальную встречу с девушкой, то сайт и не рассчитан на удовлетворение таких потребностей изначально.

## Ваша задача сейчас, если не переубедить меня, то привести максимально возможное количество аргументов.

**Comment by infman86** [comment]
Суть этого фильтра расширить возможности для пользователей, а не ограничивать это к слову "я не вижу смысла ограничивать выборку по сайту чем-то больше, чем сейчас"

Не важно реальная это встреча или виртуальная, так этот фильтр будет работать для обеих категорий пользователей.

Ведь проще и интереснее общаться с людьми у которых похожие желания и интересы, причём это касается не только сексуальной сферы.

Если этот фильтр будет добавлен, то он просто расширит возможности пользователей и никак им не повредит, ведь чтобы его задействовать с ним придётся взаимодействовать, кому фильтр будет интересен, тот им и воспользуется, а тех кого устраивает текущий функционал просто не обратят на него внимания.

Допустим я ищу девушку в реале которая любит: мужское доминирование, безопасный секс, встреча в реале, сначала общение, свободный партнёр, анальный секс, оральный секс, регулярный секс, секс на всю ночь, секс на природе.

Вбивая эти данные или часть этих данных, я получу выборку именно тех девушек которые мне интересны изначально, а потом уже как пойдёт.

Если честно не совсем понимаю зачем указывать именно 10 пунктов, пользователю может хватить и 2-3. 

P.s это просто предложение убеждать кого либо это дело такое, я предложил эту идею  по доработке не чтобы заставить/убедить кого либо, а с целью подсказать как можно улучшить сайт.

В общем как-то так, а вообще, чтобы не мучатся такими вопросами, нужно это пользователям или нет, то проще спросить у них самих, но не так как это реализовано сейчас. Имеется ввиду запилить опрос или что-то подобное на отдельной странице и самое главное чтобы пользователи увидели эту страницу. 

На вскидку вариантов два  

1) в подвале сайта, выглядит аккуратно, но заметность этого пункта будет небольшая, но как минимум она хотя бы будет. Ещё как вариант выделить этот пункт в подвале ярким цветом, чтобы глаз цеплялся.

2) Колхозить где-то в верхней части, самый большой плюс это заметность и соответственно хорошая обратная связь, из минусов не понятно где и как лепить, чтобы этот пункт нормально вписался в дизайн и идею сайта, с другой стороны он будет временным, только для того чтобы собрать обратную связь

Аминь

**Comment by tebaly** [comment]
Моя точка зрения проистекает из двух констант
* Вам сложно найти девушку в реальной жизни
* Вам сложно(а это сложно) найти девушку на сайте


Итого - зачем ещё и "фильтровать"? :stuck_out_tongue:
* Просто потому - так это уже проблемы с технической стороны
* Что-то похожее _запланировано_, и уже в этом году

Спасибо

**Comment by KILLER1974** [comment]
Не проще сделать блок сравнения желаний и города, и от этого уже и танцевать??
Изменяя желания, города - находим похожие анкеты

**Comment by tebaly** [comment]
Проще делать по порядку. Привести список тех желаний, которые вам критичны "для поиска", и оценить _реальность_ таких запросов - если они для вирта, то не стоит пока напрягаться. Так как в реальной жизни, такой фильтр вероятно имеет низкую актуальность.

**Comment by inquisitor6789** [comment]
блин, ну вы даете...
нафига это делать при достаточно низком онлайне со стороны девушек? Данный поиск, с моей точки зрения, имеет смысл делать когда соотношение парней/девушек в онлайне будет хотя бы 60/40. Про другие пропорции я и мечтать не могу.
В настоящий момент из москвы в возрасте 18-50 онлайн только 30 девушек (парней раза в 4 больше; если только сэр @tebaly опять что-то не намутил с поиском). Приблизительно 40% из них ищут только девушек (остается 60% ищущих парней). Ограничивая этот список еще и желаниями мы получим ситуацию что в онлайне не будет никого.
Кроме того, не стоит забывать, что народ на сайте "шибко грамотный" и фантазия, к примеру, "нимфоманка" может быть написана множеством способов. Например, нифаманка, нимфоманка, немфаманка, нмефоманка и т.п. Отсюда следует, что это будут разные желания и простой текстовый поиск не найдет их.
Нет, конечно явный неадекват модераторы вычистят (если руки дойдут), но все равно остается обширное поле деятельности :-)
К сожалению, а может и к счастью, сайт не обладает эвристическим анализом и даром телепатии чтобы переварить все то, что творится в голове у пользователей :-)

**Comment by tebaly** [comment]
Таки консенсус? Закрепим для потомков
* нафига это делать при достаточно низком онлайне со стороны девушек
