### ISSUE TITLE
ложные уведомления о новом сообщении/знакомстве

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#467]
заметил, что если ты удалил контакт, но он тебе продолжает писать, то появляется новое уведомление о сообщении. 
То же самое относится и у заблокированным пользователям.
Возможно, что стоит немного поменять порядок проверок статуса пользователя (если такой есть) при обработке оповещений о новых сообщениях.

**Comment by tebaly** [comment]
Баг исправлен. Появилось в следствие изменения списков контактов. 
А возможно было и раньше :shit:

Спасибо.
