### ISSUE TITLE
уведомление на почту

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#468]
с недавних пор все таки заработало уведомление на почту о новых сообщениях.
но текст надо подредактировать

> У вас есть одно или несколько новых сообщений.
Чтобы прочитать сообщения посетите свою анкету http://**где адрес анкеты??**
Для автоматического входа на сайт используйте ссылку «авто-вход»:
http:///**где имя сайта**login.php?u=**удалено**&p=**удалено**
Вы получили это письмо, так как являетесь зарегистрированным пользователем сайта.
Отключить уведомления можно в настройках анкеты на сайте.

**Comment by tebaly** [comment]
Хотфикс на тесте.

**Comment by tebaly** [comment]
Баг исправлен. Существовал с момента блокировки доменов, с ноября прошлого года :sweat:

**Comment by tebaly** [comment]
#467 - связано
