### ISSUE TITLE
Утопленники

### ISSUE THREAD

**Issue by evgad** [freedomsex/freedomsex#470]
Зашёл сегодня в раздел "утопленники" и ... Там половина, а может и более, всех не просматривал, вполне себе законопослушные граждане просто замордованы капчой! http://sexoo.me/userinfo/profile/61727018/.    http://sexoo.me/userinfo/profile/61721810/.  http://sexoo.me/userinfo/profile/39361974/.... И это... Умными словами не пинайте меня пжалста, как нить попроще, на пальцах объясните..

**Comment by tebaly** [comment]
Не отрицаю серьезного бага. Но воспроизвести его не могу вообще никак.
* На пальцах: у меня всё работает.....

**Comment by evgad** [comment]
Да работать то работает, но за что их? Людям прилетело от этой работы по сотне капчи... Как бы любому из нас не попасть под раздачу

**Comment by tebaly** [comment]
Я не знаю. @evgad - пожалуйста, вы нам сильно очень поможете, а возможно без вашей помощи ничего и не получится. Создайте фейковую анкету, и попробуйте добиться попадания в "утопленники" совершая обычные действия не взаимодействуя с интерфейсом безопасности. Через админ интерфейс другой анкеты вы сможете проконтролировать весь процесс.

**Comment by evgad** [comment]
Задачу понял) будем искать!)))

**Comment by mj4444ru** [comment]
да я много раз так топил себя с фейковых анкет )))
здрасти...
сейчас весь в делах, некогда воспроизводить...

**Comment by tebaly** [comment]
Исправлено. 
Проблема появилась с изменением интерфейса. Раньше если что-то и было, то не это..
