### ISSUE TITLE
Прямо сейчас. Кнопка пропустить ответ на http://sexoo.me/security/action/ doesnt work

### ISSUE THREAD

**Issue by ivankrut856** [freedomsex/freedomsex#471]
Прямо сейчас. Кнопка пропустить ответ на http://sexoo.me/security/action/ doesnt work
Через раз нажимаются две другие кнопки

**Comment by tebaly** [comment]
В это время сайт был на обслуживании. 

![image](https://user-images.githubusercontent.com/9466814/30581766-f247b2cc-9d29-11e7-856f-0ce801680414.png)

**Comment by ivankrut856** [comment]
Всё ещё. Кнопка пропустить не пропускает

**Comment by tebaly** [comment]
Спасибо. Исправлено
