### ISSUE TITLE
Новым сообщением показывает то, что послал я; сообщения иногда не обновляются и др. ошибки

### ISSUE THREAD

**Issue by GetNight** [freedomsex/freedomsex#473]
1. Если я посылаю сообщение, мне показывает, что есть новое сообщение, где вижу своё собственное.

2. Когда мне отвечают, сообщение в чате не видно;
приходится выходить на уровень, где видно меню Поиск  Общение  Знакомства
и снова входить...

3. Очень тяжело контролировать ситуацию, когда при общении с человеком не видно основное меню, где видно, что есть новые сообщения от других пользователей. Может лучше его не прятать? А текущий пункт просто выделять цветом?

4. Очень часто показывает, что есть сообщения в меню Знакомства. Захожу уже в 5й раз там пусто.

5. Плохо видны контакты, которым не писал. Можно ли их еще выделять жирным?

6. Не понятно, что означают значки вирт, реал и цифры. Предположения есть, но хотелось бы знать точно.

**Comment by tebaly** [comment]
Благодарю за замечания. Попробуем как-нибудь улучшить.

**Comment by C1923** [comment]
Ребят. Проблема одна появилась. После того, как найду анкету интересующего пользователя и напишу ему сообщение, то при открытии вкладки "Общение" не появляется список отправленных сообщений. На его месте лишь дефолтное "Здесь будет список ваших контактов, сообщений, диалогов. Чтобы начать общение, нужно Познакомиться. " Спасибо за понимание и внимание.

**Comment by tebaly** [comment]
#486 - аттач
