### ISSUE TITLE
Невозможно понять, последнее сообщение от кого и нужно ли его читать

### ISSUE THREAD

**Issue by GetNight** [freedomsex/freedomsex#477]
Захожу в общение вижу часть последнего сообщения.

Не всегда понятно, от меня это сообщение или мне. Читал я его или еще нет?

Предлагаю выделять цветом серым - мои сообщения, чёрным - мне. Если оно не прочитано, выделять кружком как в меню.

**Comment by tebaly** [comment]
Там стрелочка есть. Указывает направление. Точка - статус прочитано/нет
