### ISSUE TITLE
На форуме - почему когда я хочу создать новую тему, в закладке Write при входе текст предыдущего?

### ISSUE THREAD

**Issue by GetNight** [freedomsex/freedomsex#478]
При этом когда сотрёшь и напишешь новый текст,  нажмешь Submit new issue...

то тема исчезает! и в списке тем не появляется!!!

помогает только одно - переждать 5+ минут, пока при нажатии на кнопку New Issue не будет текста предыдущей темы (написанной менее 5 минут назад).

**Comment by tebaly** [comment]
Уточните пожалуйста, о чем идет речь.
