### ISSUE TITLE
что это?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#479]
в тех логе http://freedomsex.me/userinfo/profile/61758365

03.10 ` 17:33 (3) - [модератор] - перевод с уровня 3
03.10 ` 17:22 (3) - [модератор] - перевод с уровня 2
03.10 ` 17:17 (3) - [модератор] - перевод с уровня 1
03.10 ` 17:06 (3) - [модератор] - перевод с уровня 0

**Comment by tebaly** [comment]
Давно забытое старое 
:poop:

**Comment by tebaly** [comment]
"отвалилось" с полгода назад а то и раньше.. Пофиксил :relaxed:
- Уровни в системе голосования это
