### ISSUE TITLE
Система жалоб/голосования была атакована, но это не точно...

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#480]
Так совпало, что мнимая атака началась в период обновления интерфейса сайта. Суть сей отаке в том, что очередь голосования по жалобам завалена по самые .. уши. Реальная ли это атака нежели фейл интерфейса, попивая пиво выясняется. Но в то же самое время начался ДуДос сервера. Долбили, и продолжают долбить по сей день по странице логина. [Совпадение?...] Что должно всех насторожить. Мы же не кинопоиск, нас то за шо?

Критического ни в том ни в другом нет ничего. Плюсы есть.
* Апнули алгоритмы голосовалки. Она стала чуть чуть умнее... Голосовалке устроили стресс тест... Либо мы, по скудоумию, либо наши недруги, которым мы расклад всё время портим...
* Найдено несколько серьезных багов, о которых сообщалось 100500 лет назад и столько же раз, но которые так и не были вычислены. 

Пиво есть, ДуДос продолжается.. главное не спиться :yum:

**Comment by inquisitor6789** [comment]
ну вы это.... держитесь там... много не пейте, а главное держитесь подальше от компов. А то на утро рискуем сайт не узнать :wink:

**Comment by tebaly** [comment]
То есть, по ощущениям на вашей стороне всё норм?)

**Comment by inquisitor6789** [comment]
по ощущениям - да. Тормозов не заметно.

**Comment by SVIT-Lanka** [comment]
У меня вот голосовалка заработала пару дней назад! Наконец-то) Так что сами плюсы))

**Comment by tebaly** [comment]
Для атаки создаются сотни анкет девушек, чтобы "быть онлайн", принять сообщение и пожаловаться на него. Хм... Онлайн по проекту вырос... Совпадение?.. Так норм же, чо)))

**Comment by SVIT-Lanka** [comment]
Вчера/сегодня глючит интерфейс модератора: решения зависает на какой-то жалобе и на след не переходит.

Теряется периодически связь действий с рейтингом. Действия соответствующего уровня выполняются, а звание и кредиты падают. (Подобная жалоба была еще в отзывах на сайте)

**Comment by tebaly** [comment]
> Действия соответствующего уровня выполняются, а звание и кредиты падают.

Давно уж существуют лимиты (час/сутки). Чтобы невозможно было накрутить администратора за сутки. Возможно речь про это. Тогда при превышении лимита, рейтинг только падает.

**Comment by tebaly** [comment]
@SVIT-Lanka - с этой/следующей недели вводится новый алгоритм для предупреждения "флуда" голосовалки. К слову, она флудится уже третий месяц к ряду. Так что заодно протестируем новый механизм. И... Замечания скоро вернутся.

**Comment by tebaly** [comment]
#488 - как основа для предупреждения спама телефонов

Теперь зафлудить голосовалку стало сложнее, а именно над решением этой проблемы пришлось долго думать. Теперь без блокировок по IP, бесплатно и без СМС. Как и во всём проекте, основой есть стремление обходить проблемы без применения блокировок учитывающих _идентификацию_ Пользователей, а брать за основу _поведение_. Применено два серьезных изменения, при которых в голосовании теперь учитывается и рейтинг модератора, и рейтинг того, кто отправил жалобу. Теперь учитывается также _повторность_ жалобы, а также принято в основе то, что подать _уникальную_ жалобу может кто угодно. Раньше "автором" жалобы был первый подавший, сейчас последний с "большим рейтингом".

Так как жалобы прежде всего направлены на предупреждение нежелательного поведения, сам процесс подачи жалобы по умолчанию подразумевает маркер "наказать", таким образом, при повторной жалобе на тот же текст, либо всплывает _адекватная_ жалоба, либо тонет _флудер_ со всеми своими жалобами.

Как можно было заметить, надежды на систему жалоб, как панацею от спама не оправдались. Противодействовать автоматическому спаму мы можем только в полуавтоматическом режиме, всё чаще переходя непосредственно к ручному контролю в реальном времени. А это не выход. На очереди атаки ботов неотличимые по поведению от обычных людей... Основной функцией системы голосования всё больше становится процесс "рождения" модераторов. Из этих оснований _флудить_ систему просто бессмысленно. С другой стороны, чем больше в системе промаркированных сообщений, тем лучше в целом. Обо всё этом говорилось ранее, и в целом звучит как "Чем больше жалоб, тем лучше".

![image](https://user-images.githubusercontent.com/9466814/31873726-bae89ac6-b7cd-11e7-9871-9f72f195a657.png)

Теперь очередь за "замечаниями" и статусами для анкет.

**Comment by inquisitor6789** [comment]
не ну чо, круто... Только я нифига не понял :-)

**Comment by tebaly** [comment]
Так и задумано :joy:

**Comment by tebaly** [comment]
>  решения зависает на какой-то жалобе и на след не переходит.

@SVIT-Lanka  - исправлено. Спасибо.
