### ISSUE TITLE
Пожалуйста, уберите эрофотку с шапки сайта

### ISSUE THREAD

**Issue by GetNight** [freedomsex/freedomsex#481]
Если сидишь на работе, тупо не откроешь сайт. Потому что бросается в глаза всему этажу.

Предлагаю оставить её только для невошедших пользователей.
А если авторизировался - то пусть она не показывается.

Спасибо за понимание.

**Comment by tebaly** [comment]
Смотря какое зеркало. Выберите более менее подходящее.
* После открытия страницы скролл в низ
* Нажать кнопку "Поиск"

И картинка исчезнет, даже не появившись :)

---

Без вопросов, можно запустить зеркало с котиками в шапке. **Серьезно(!)**
Просто подскажите имя домена красивое. Я пока сам подумаю...

**Comment by tebaly** [comment]
http://cats-x.com - по остальным сайтам будет добавлена кнопка замены на котиков.

**Comment by SVIT-Lanka** [comment]
Отличная идея! Беспалева так))) А то, то не нажал "Поиск", то забыл поскроллить...

**Comment by tebaly** [comment]
> @SVIT-Lanka ... то не нажа**л** "Поиск", то забы**л** поскроллить...

Тема сисек не раскрыта :)

**Comment by SVIT-Lanka** [comment]
Та то ж я от общего лица (всех потенциальных страдальщиков), в унифицированном мужском роде)))

**Comment by tebaly** [comment]
А, ну раз унифицированном :relaxed:

**Comment by GetNight** [comment]
Уже намного лучше) Но я бы вообще убрал бы и котиков) Только текст и ничего кроме)

Котики, знаете, тоже ставят под сомнение начальству серьёзность ваших намерений на... работе)

**Comment by tebaly** [comment]
Ну б..я)) отключите картинки :)

**Comment by tebaly** [comment]
Новой вункциональности по сокрытию сисек из шапки добавляться не будет. Подразумевается, что вы используете сервис с личного устройства в уютной домашней обстановке, либо уединившись. В таком случае подобный функционал просто не нужен...

На работе нужно работать :relaxed: 
Ссылка на _версию с котиками_ внизу страницы всех зеркал, включая самих котиков.

Спасибо за идею.

**Comment by GetNight** [comment]
Извиняюсь за повторное вторжение.
Но реализация с котиками понижает градус быть попаленным лишь процентов на 30.

1. рядом с закладкой висят КРАСНЫЕ СЕРДЕЧКИ. их видно. они бросаются в глаза любому, кто просто подошел за советом на работе.
2. когда браузер свернут, простое проведение мышкой над значком браузера высвечивает заголовок страницы, который просто режет по глазам:
БЫСТРЫЕ ЗНАКОМСТВА. СЕКС ЗНАКОМСТВА БЕЗ СМС БЕСПЛАТНО
3. Котики на полстраницы, поверьте, тоже очень заметны.
4. Строка с рекламой рунеток... сиси писи и их вариации...

Что ПРОШУ: минималистический сайт без всего этого... Поверьте, я в любом случае не зайду в рекламу рунеток, потому что я знаю этот ресурс уже 150 лет. А котики после внезапного палева всплывут в памяти руководства ("ага... так ты уже месяцами сидишь тут!")

_Вариант 1_ (наиболее желательный)
Зеркало страницы: foundx.com
Значёк страницы: серый кружок с белой звездочкой или белой лупой
Заголовок страницы: Поиск контактов
Картинка в шапке: отсутствует
Реклама рунеток: отсутствует (или на крайний случай внизу страницы)

_Вариант 2_ (альтирнатива минимум)
Опционально возможность смены адреса картинки в шапке, значка сайта и текста заголовка страницы...

"Подразумевается, что вы используете сервис с личного устройства в уютной домашней обстановке, либо уединившись." - представьте, что иногда ждать возможности полностью уединиться можно целый день... и не дождаться. За это время твой контакт отправит тебя в игнор.
Если я большую часть жизни нахожусь на работе, мне нужна возможность пользоваться сервисом на работе.

п.с. Вы помните старую игру "Президент"?.. идеальная игра вообще без графики))

**Comment by tebaly** [comment]
**3. Котики на полстраницы, поверьте, тоже очень заметны.**

По этому пункту. Это только на "стартовой странице". Как только вы нажимаете "поиск"...
![image](https://user-images.githubusercontent.com/9466814/33162538-15b161ba-d03b-11e7-9a60-a7ea492a63aa.png)

... и нет котиков.

Если появятся сиськи на доли секунды, я ещё понимаю. Но если "моргнут" котики - вполне норм. Ваша задача - нажать поиск после загрузки сайта. Обновлять страницу полностью не нужно.

**Comment by tebaly** [comment]
**А котики после внезапного палева всплывут в памяти руководства ("ага... так ты уже месяцами сидишь тут!")**

И котики тут имеют значение, но сам дизайн. Он ведь тоже запоминается. Или у вас в начальстве дебилы. А если спалят по дизайну, то смысл дергаться с котиками, которые сами собой исчезают, как сказано выше.

**Comment by GetNight** [comment]
Не понимаю вашего упорства...
Я думал, что вы хотите сделать сервис удобным не для себя лично...

Почему так сложно НЕ показывать котиков, если я авторизирован?
Одна грёбаная проверка и все довольны)

И насчёт дизайна вы ошибаетесь.
Он запоминается лишь тогда, когда в него вникаешь. Создаются ассоциативные связи в мозгу и только тогда ты его начинаешь узнавать. А если видишь мельком, то нет. 
Котики же - это уже готовая ассоциативная связь. Они запоминаются в одно мгновение.

То есть, пока ты нажимаешь ПОИСК, они УЖЕ остаются в памяти.

И еще. Вы говорите, что обновлять страницу не нужно. Но если я не обновляю страницу поиска, то в ней не отображаются новые контакты. А когда я обновляю страницу через F5 котики ОПЯТЬ появляются. Таким образом я вижу котиков десятки раз за день. И не только я, т.к. мой компьютер просматривается со всего этажа...

Вы сами пробовали пользоваться своим сервисом, или вы изучаете его лишь в теории?

**Comment by GetNight** [comment]
Странно, что когда тратишь время на то, чтобы сделать более привлекательным чей-то проект, 
на тебя еще и обижаются...

**Comment by tebaly** [comment]
@GetNight - нажатие кнопки "Поиск" загружает новые данные по результатам поиска. Это равноценно обновлению страницы сайта, кроме того что
* Обновление происходит до 10 раз быстрее
* Котики **не появляются** снова (обсуждаемое)

Либо вы не разобрались с назначение и работой кнопки "Поиск", либо это дикий троллинг :sweat_smile:

### Мы с вами покамест обсуждаем третий пункт по вашему списку. 
Не спешите пожалуйста.

![image](https://user-images.githubusercontent.com/9466814/33170661-2fe5ae28-d05a-11e7-80a4-2b3c64b364ff.png)

**Comment by GetNight** [comment]
Надеюсь, вы всё еще раз обдумаете и примете верное решение помочь пользователям своего сервиса чувствовать себя еще более комфортно) //заголовок, котики, иконка сайта

п.с. в любом случае спасибо за хорошую попытку сделать наш серый быт менее серым)

**Comment by tebaly** [comment]
> @GetNight  - Странно, что когда тратишь время [...] на тебя еще и обижаются...

Цитату моих слов пожалуйста, где я на вас обижаюсь. Если нету, то вы официально тролль Сообщества. Просто чтобы я на кого-то обиделся, нужно очень очень постараться. За всю историю проекта, я ещё ни на одного участника не обиделся. :stuck_out_tongue:

Спасибо за замечания. Любые отзывы о работе сайта всегда приносят пользу. Я благодарен вам за ваше участие в развитии проекта. Ещё раз, благодарю.

**Comment by tebaly** [comment]
@SVIT-Lanka предложение адекватное. На тематических сайтах часто присутствует данный функционал. У нас возникло явное недопонимание. Если смотреть в смысл того, что я писал выше, легко прочитать то, что я вовсе не против предлагаемого. Я против дублирования функционала. Я специально акцентировал внимание @GetNight на том, что пытаюсь обсудить с ним пока только Третий пункт из его списка. Потому как
* Картинка с доп текстом исчезает сразу, после нажатия кнопки "Поиск". Обновлять страницу нет необходимости. Но он этого не делает, обновляет, и предъявляет за появившихся котят, предлагает новую кнопку "убрать котят" или сделать версию без шапки. 
* Дублировать функционал "сокрытия картинки из шапки" по присутствующей до сего момента аргументации нет необходимости. Над остальным я пока думаю

**Comment by SVIT-Lanka** [comment]
@tebaly, полагаю, @GetNight предлагает не дублировать или добавлять функционал, а, скорее, обезличить графику сайта. Ну и Рунеток в подвал скинуть (поддерживаю, кстать)). Хотя, это уже зависит от ваших интимно-деловых отношений с ними)

**Comment by tebaly** [comment]
> обезличить графику сайта

Я до этого ещё не дошел)) А котики убираются одним кликом в действующем интерфейсе :stuck_out_tongue_closed_eyes:

**Comment by tebaly** [comment]
> Предложение по сайту oesex.ru. Прошу убрать огромную интимную картинку на главной странице т.к. что-бы открыть ваш сайт надо прятать телефон или монитор что бы ее не было видно!

**Comment by tebaly** [comment]
Дополнительного функционала по скрытию картинки из шапки не будет. 
#510
