### ISSUE TITLE
Онлайн статус. Предложение.

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#482]
В каких случаях у контакта появляется значок онлайн? Насколько я поняла: 
• при входе
• при отправке сообщения
Если же пользователь на сайте, но 10 минут никому ничего не писал, то статус  меняется.
В масштабе эт, конечно, хорошо. Меньше народу - больше кислороду, как говорится)) Но в небольших городах и так не людно, так еще и теряются те, стесняшки, что сидят, смотрят и не пишут)
Может добавить еще какие-то действия  в активность, например, Поиск, просмотр сообщений... (Тут же еще глюк возникает: сообщение прочитано 5 минут назад, а собеседник был на сайте  3 дня назад)))

**Comment by tebaly** [comment]
Добавил синхронизацию _по максимуму_. До нескольку раз в минуту будет синхронить. Это опять же "откатывает" внесенные ранее _по предложению_ изменения ограничивающие поднятие анкет. Поэтому стоит будет снова откатиться по лимитам. Потестируем новшества чтобы очутить необходимость.

**Comment by tebaly** [comment]
Если ничего не путаю, вот старая ветка
- https://github.com/freedomsex/freedomsex/issues/229 

Возможно где-то ещё обсуждали, если помните, прикрепите ссылку пожалуйста.

**Comment by SVIT-Lanka** [comment]
Про поднятие в поиске я и не говорила. Лишь о том, что на статус онлайн влияет только отправка сообщения, а другие действия пользователя на сайте оставляют его невидимкой.

Поиск и раньше заплывал. При большом скоплении онлайн контактов дальше второй страницы листать бесполезно - идут повторы.

**Comment by tebaly** [comment]
@SVIT-Lanka - там просто жестко связан статус онлайн и сортировка. Раньше был костыль на этот случай. Но после обновы его не стало. Попробую подшаманить. Суть понял, спасибо.

**Comment by SVIT-Lanka** [comment]
Да Вы шаман, батенька! Статус теперь более адекватен и старается отражать действительность)

**Comment by tebaly** [comment]
Ой. Лишь бы не во вред :relaxed:

![image](https://user-images.githubusercontent.com/9466814/31442649-bf068230-ae9f-11e7-94cb-841a15d57cd2.png)

**Comment by tebaly** [comment]
Оставим пока так. Вроде ничего плохого в этом нет
