### ISSUE TITLE
Предлагаю на модерацию давать сообщения, направленные к такому же полу

### ISSUE THREAD

**Issue by GetNight** [freedomsex/freedomsex#483]
Предлагаю каждому полу на модерацию давать сообщения, направленные к такому же полу

Так все будет более осознанно, т.к. мужчине непривычно адекватно оценивать сообщения а-ля "пососи мой член и полижи зад, шлюшка" или "люблю когда сперма наполняет мой рот и зад".

Профит?

**Comment by SVIT-Lanka** [comment]
На мой "женский" взгляд, модерация на сайте такова, что ее осилят особи обоих полов в равной степени. Вас же не просят оценивать благосклонность к каждой фразе, насколько нежно она сказана и нравится ли Вам это действо. Отличить оскорбление, шантаж и другие сообщения противоправного содержания способен любой адекватный человек.

**Comment by inquisitor6789** [comment]
учитывая, что активных модераторов/админов женского пола можно по пальцам одной руки пересчитать, то все остальные останутся без работы

**Comment by tebaly** [comment]
Администрация высказалась против :relaxed:
Спасибо. Свежие идеи очень важны для проекта. 
На сим закрываю
