### ISSUE TITLE
Рейтинг для пользователей

### ISSUE THREAD

**Issue by ablomov12345** [freedomsex/freedomsex#484]
Предлагаю ввести подобие рейтинга модераторов для пользователей
Например, если пользователь читает сообщения, но не отвечает
Жалуется на сообщения, которые не имеют для этого основания
Часто отвечает односложно ("ок, да, нет...")
Несоответствие выбранных желаний и поведения при общении (понятно, что у каждого они могут измениться, но об этом можно сказать собеседнику совершенно спокойно)
За рассылку чужих фото (за исключением, если это не было оговорено предварительно)
Если пользователь совершает часто вышеперечисленные действия и его рейтинг падает значительно, вводить ограничения
- снижение места в топе
- ограничение на количество новых собеседников (не имеет права писать новым людям)
- уменьшение общего количества сообщений за определенное время  

Мне кажется, подобное нововведение будет мотивировать пользователей на более активное и адекватное общение
Кто не особо желает общаться, тот быстро заработает низкий рейтинг
Не хочешь общаться - не засоряй сайт

**Comment by tebaly** [comment]
Моё стандартное: сайт вообще не для общения, это вам не мессенджер.

![image](https://user-images.githubusercontent.com/9466814/31236679-858aa03c-a9fd-11e7-8fb5-03ff3dff5eda.png)

**Comment by ablomov12345** [comment]
Другой вариант
Если исключить рейтинг, чтобы избавиться от лишних заморочек
Может, тогда вводить ограничения в автоматическом режиме? 
Не ответил на 10 предложений знакомств - 10 минут не можешь сам писать новым людям
Или, к примеру, не можешь писать другим, пока не ответишь на эти 10

Несколько сообщений длиной меньше 10 символов - подобное ограничение

**Comment by tebaly** [comment]
Спешу разбить всю вашу наивность, пока этого не сделал кто-то другой :stuck_out_tongue:
* Вам девушки сами по себе часто пишут?)
* Вам хочется чтобы вам меньше писали парни?

Парадокс в том, что можно перманентно забанить возможность "писать самим" для всех девушек на проекте, и от этого ничего не поменяется. И это на любом сайте знакомств :)
* Аналогия: надеть майку с надписью "девушки, не подходите ко мне знакомиться"

**Comment by tebaly** [comment]
> Или, к примеру, не можешь писать другим, пока не ответишь на эти 10

Для девушки из Москвы в возрасте ~23 года приходит по 30-50 знакомств в минуту...

**Comment by SVIT-Lanka** [comment]
@ablomov12345 Вы, ради эксперимента, зайдите под анкетой девушки и попробуйте отвечать на ВСЕ сообщения! Да что там отвечать, Вы их прочтите сначала все! А потом еще и развернутый ответ дайте на его "привет зацени мой инструмент" или "отстрапонь меня, шлюха". Тут не абы какой талант нужен... и выдержка)) 

Даже, если вы 80-летняя старуха из Мухосранска - это будет проблематично и топового рейтинга Вам не видать по этой системе))

**Comment by tebaly** [comment]
Спасибо. Пишите любые ваши идеи. Это важно для проекта.
