### ISSUE TITLE
Блокнот возвращается

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#487]
На тестовом сервере новая обнова. Вернулись функции блокнота. Но он уже не тот что прежде. Сходства только внешнее.
* На данный момент нет синхронизации с сервером. Фактически она не планировалась изначально. Теперь же планируется, но ещё не понятно как будет выполняться. 
* Пишется всё в вашем браузере в единственный "файл". Многопользовательский режим вероятно будет добавлен.

У блокнота тестовая версия, поэтому багов может быть. Буду крайне благодарен за ваши баг-репорты и отзывы о реализации.

---

- В новом обновлении изменен дизайн быстрых сообщений. Чтобы втиснуть и блокнот и шаблоны.
- Исправлены серьезные баги в системе жалоб/голосовании
- Добавлены "контент" функции для "информации"
- Начинаем интернационализацию

---

# Алерт

В блокнот пишется всё что отправляете. Делается для удобства, чтобы не набирать текст повторно. Внешне похоже на "собирание данных" о том что вы пишите и отправляете - потому что это и есть линейная запись того, что вы отправляете в сообщениях. Содержание не шифруется. Пишется всё на вашем устройстве, поэтому фактически, при доступе к вашему компьютеру или телефону другого человека, а далее доступе к Блокноту - этот человек сможет прочитать то, что вы чаще всего отправляете. Это очевидное следствие из функциональности блокнота.

**Comment by SVIT-Lanka** [comment]
Отчет: 

Блокнот и быстрые сообщения работают из окна 'Написать сообщение'.  Сообщения из 'Быстрого ответа' в блокнот НЕ ПИШУТСЯ, а это куда более актуально для девушек)

Не совсем понятен алгоритм сортировки сообщений в блокноте.  Сначала предположила, что будет по частоте отправки или времени отправки... но нет, как-то не так)

**Comment by tebaly** [comment]
Спасибо. Исправил

**Comment by tebaly** [comment]
> Привет разработчикам этого сайта! Проект очень даже интересный и народ к Вам стремится. Недавно можно было "видеть" собеседника в сети и общаться с ним и от кого пришло сообщение - тоже было видно. Потом это устранили, с трудом, но можно было узнать в сети ли собеседник. Но уже не узнаешь отправлял ли ты ему сообщение. **С сегодняшнего дня и этого нет, есть "блокнот". Неужели люди такие тупые, что сами не придумают, что написать абоненту??? Но зато теперь не ясно в сети ли твой собеседник.** Всё с Вашей стороны делается для того, чтобы отвадить контингент , а не создать комфортные условия для общения. Не надо таких экспериментов, верните настройки обратно.

Благодарствую конечно за отзыв. Человек явно не за минуту это написал... Но пля... Ссылку на анкету перенесли на три сантиметра выше, её ж никуда не убирали :sob: :disappointed_relieved: :astonished:

**Comment by tebaly** [comment]
@inquisitor6789 - не могу найти ваше обращение по поводу "фантомных" сбросов в арбитраж автоматикой. Когда по уже принятому решению вылетает сброс
```
блокировать » автомат » ? » сброс авто, сложно - 3 дня назад
сброс » #5040613 » #5040613 » наказать - 3 дня назад
```

И я хрен его знает как это происходит... Шучу конечно. Это из-за путаницы голосовалки/бездны/арбитража. Раньше, да и сейчас, было возможно такое
* что-то улетело в _бездну_ - соответственно решения не имеет
* это-самое влетает следом в _голосовалку_, так как _решения то нет_
* вы, как всея админ, выцепляете это-самое из бездны и кидаете в арбитраж
* благополучно устанавливаете нужное решение
* но оно-клон всё еще голосуется, _плохо голосуется_ и сбрасывается автоматом

С этим надо что-то делать. Да-да, надо :persevere:
