### ISSUE TITLE
Цензура первого сообщения

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#488]
Раньше было, что в начале знакомства, например, нельзя отправить _ссылку_ любого вида типа [google.com](https://google.com) (нужна капча). Отправку фото в начале знакомства тоже нужно подтверждать. За последние несколько месяцев на "почту" насели спамеры номеров телефонов... Как говориться, лохи будут всегда, и _информационное предупреждение_ судя по всему на них, лохов, просто "не работает". Поэтому и спамеры не сдаются :relaxed:

Так как затраты спамеров минимальны, а цензуры на сайте нет по определению, спам будет продолжаться. Поэтому, принято волевое решение "запретить" отправку номеров телефонов и всего что на них может быть похоже _в начале знакомства_.

### Совершенно секретно

![screenshot 5](https://user-images.githubusercontent.com/9466814/31860991-8fdd0958-b72c-11e7-9cf3-c521ae45efb5.png)

ДуДос сервера за вчерашний день. На графике вы можете наблюдать ~~позиции повстанцев в районе села Снежное~~ настойчивость наших с вами Товарищей.

---

Нововведение с новым обновлением. Ждем сообщений типа "позвони мне на плюс семЬтире∞тире ЗS chетыре"... Не исключено, что придется лимитировать и логины скайпа/соцсетей.

**Comment by tebaly** [comment]
_Информационное предупреждение_ теперь скрывается по клику.

**Comment by tebaly** [comment]
> 32.180.69.22см, люблю куни

Эмм.. Хьюстон.. у нас проблема.. Парень, 32 года 180 см рост 69 кг вес и 22см - теперь это номер телефона :sweat:

**Comment by inquisitor6789** [comment]
> Эмм.. Хьюстон.. у нас проблема.. Парень, 32 года 180 см рост 69 кг вес и 22см - теперь это номер телефона

:grinning::grinning::grinning:

**Comment by tebaly** [comment]
Пишу ВайтПапер по этому поводу. Так как фильтр крайне жесток. Сейчас это пять цифр в сообщении. Как угодно. 
`"~[0-9].*[0-9].*[0-9].*[0-9].*[0-9]~"`

Это конечно лютый п#здец... Но, а шо поделать...

**Comment by inquisitor6789** [comment]
жесть! невольно напрашивается нейросеть :-))

**Comment by tebaly** [comment]
Наши друзья вероятно остались недовольны нововведением. 
Проблески новых атак на графиках. Это весь вчерашний день. 

![screenshot 6](https://user-images.githubusercontent.com/9466814/31938476-5128b118-b8c0-11e7-89c1-f0f5fcab57c9.png)

**Comment by inquisitor6789** [comment]
так, я что-то не понял. Если в первом сообщении есть какой-либо контакт вне сайта, то что делаем с сообщением? блокируем или наказываем?
Намедни вы, сэр, соизволили в арбитраж накидать кучу телефонов... и что с этим теперь делать?

**Comment by tebaly** [comment]
> Если в первом сообщении есть какой-либо контакт вне сайта, то что делаем с сообщением?

Хотелось бы ответить как-то по особенному, с искоркой в глазах, но не получается))

> Запрещены все явные и не явные мошеннические схемы. Запрещено просить перейти на другой сайт, включая сайты знакомств или интим знакомств, **просить позвонить по указанному телефону**, или созвониться в скайпе и т.п. с целью продолжения **всего разговора там**, категорически отказываясь общаться здесь под любыми предлогами. Таким образом _мошенники пытаются обойти систему безопасности_.

Пикантность ситуации в следующем
* Сие действо возможно со стороны парней и крайне скверно со стороны девушек
* По содержанию жалобы часто не ясно, парень или девушка к этому причастна

Судя по всему, пришло время внести ясность... Суть мысли в следующем
* Если голые ценники отправлять в блокировано нельзя, мы же этого не одобряем, и на всякий случай кидаем в наказано
* Этой же логики наверное стоит придерживаться и при рассылки номера телефона,
 любых персональных данных, логинов, уникального содержания:
    * если пишет явно парень, то скорее разрешить
    * если не понятно, то скорее наказать

---

Далее логику стоит позаимствовать из "вирта"
* Если по содержание походит на приветствие - отягощающее обстоятельство
    * Например начинается со слова "Привет"

## Просить позвонить по указанному телефону

Наверное наличие только лишь телефона не относится к просьбе, но наличие слов "Давай вацап", "Давай созвонимся" и тому подобное есть очевидная просьба.

**Номер телефона относится к уникальным/персональным данным, про это есть целый 14 пункт правил. В общем и целом данная ситуация является сложной. Полагаю, стоит начать кидать любые непонятные логины и номера в наказано. А далее по обстоятельствам в блокировано. Что скажете?**

_PS: поленился комментари указать, мне выговор_ :persevere:

**Comment by tebaly** [comment]
#491 аттач

**Comment by tebaly** [comment]
Самое обидное, что спамерская атака обеспечила квартальный рост аудитории и онлайн до +30%
* То есть, получение спам сообщения  для парней, это вовсе не повод печалиться :sweat_smile:
* Большая часть новоприбывшей аудитории расценило это как показатель "реальности"
* И задержались здесь до получения реальных ответов девушек

Плюс ко всему, было больше и онлайн "девушек" (в этом была _суть атаки_).
После добавления спам фильтров сейчас, картина меняется в обратную сторону...

**Comment by tebaly** [comment]
Попытка номер раз :)
> добавляйся в Cк"@п логин pi*****4 Жду

---

> Намедни вы, сэр, соизволили

У меня на столько высок ЧСВ, да?) Уже прям заметно стало? :sweat_smile:
