### ISSUE TITLE
Работа системы жалоб

### ISSUE THREAD

**Issue by monkklan** [freedomsex/freedomsex#490]
И так я вернулся и после нескольких дней тестирования системы жалоб и вновь вернувшейся системы стандартных сообщений готов задать наконец вопрос.

Суть:
На сайте действует система жалоб, насколько я понял она работает таким образом что при накоплении какой-то критической массы жалоб, при попытке ответить или написать контакту на который эти жалобы поступают выдаётся окно с предупреждением собственно о том, что контакт плохой, негодный и вообще не надо ему писать. Всё это происходит автоматически и не зависит от реакции на эти жалобы модеров. Поправьте меня если я не прав.

Если я прав, то хочу заметить что всё очень сильно поломано. В результате тестирования под женским аккаунтом получается так что половина мужских контактов которые пытаются познакомиться пестрят предупреждениями. При этом предложения знакомства у большинства вполне приличные. Идём дальше, специально создан мужской аккаунт, и девушкам у которых имеется пометка вирт, это важно только им, разсылается каждой единожды, стандартное приглашение к вирту в скайпе(одно из предложенных в списке стандартных предложений знакомства). И вуаля, через полчаса аккаунт с которого это делается становится плохим и негодным. Что сделает нормальный человек заметив это? Создаст новый аккаунт и продолжит знакомится. Но теперь он не знает кому он уже писал. И сообщения начинают отправляться по второму кругу, тем самым раздражая девушек. Но по сути человек всего лишь зашёл на сайт и делает то для чего сайт предназначен. Использует стандартные средстваи не злоупотребляет вниманием девушек с пометкой реал, ищущих других девушек и прочее.

За сим, хотелось бы уточнить, можно убрать автомат с жалоб и отдать на откум модерам. Потому как если модеры будут наказывать за фразы из списка стандартных, их можно будет призвать хоть к ответу если что.

**Comment by tebaly** [comment]
@monkklan - давайте более предметно и по пункта. Дайте мне ID пострадавшего. В данном случае вай "фейк" который отправлял _стандартные сообщения_, и который за это влетел...

**Comment by monkklan** [comment]
ID: 66192799 вот айди, этот свежий вчера вечером процесс проходил, вчера слал, сегодня зашёл уже выводится предупреждение

**Comment by tebaly** [comment]
@monkklan - по логу в основном `факт: preset: virt`. Это значит по анкете вы не подходили. Остальное `preset: age` - различие в возрасте. Поэтому вам ожидаемо накинули 5 жалоб.

**Comment by tebaly** [comment]
#491 аттач

**Comment by tebaly** [comment]
Затрэшили хороший отзыв

> Кнопку наказать обузят. Насколько я понимаю, почти все парни тут наказаны. Зайдите в раздел модерации и посмотрите за что там наказывают - всякие "привет как дела". Ваше "Может стоит наказать?" на кнопке удаления явно не помогает ситуации.
Лучше просто сделайте "удалить и заблокировать", а наказание сделайте как отдельную кнопку в анкете, например. Чтобы её использоали по назначению, а не из-за всякой фигни

**Comment by tebaly** [comment]
> Если вы тупые свиньи админы думаете, что надо вводить по сто раз коды доступа потому что **какой-то клушке показалось, что её домогаются**, то ваш проект летит в полную п..бездну, потому-что _парней достает набирать кажды раз коды из-за какой-то клушки_.. Пусть сидят и меж собой квохчут. Без мужиков. Посмотрим насколько их хватит. Как в Однокласниках и Фейсбуке. Там эти дуры почему не ищут "лубофф" Муж подписан?
