### ISSUE TITLE
Фильтр/настройка во вкладке знакомств

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#491]
> Как оказалось, это абсолютно не удивительно, "девушке" приходят сотни предложений в закладку "Знакомства" и это реально бесит, как содержание предложений так и функционал приёма заявок. Я считаю, что это очень сильно бы облегчило жизнь многим, если бы галочка "Только в моём городе" отсекала саму возможность написать мне какому-то Васе Писечкину из другой страны, звучит интуитивно понятно и логично.

Таки реализовано, уже на тесте. Так как у нас _принцип ничего не отсекать_ - ничего и не отсекается, а красится. Сейчас пока в серый цвет. Печально, на для слабовидящих и дальтоников сайт становится всё хуже и хуже, так как мы решили применять цветовую маркировку против прямой "фильтрации" списков. Ноухау, йопта.

![image](https://user-images.githubusercontent.com/9466814/32051417-2facfba4-ba5d-11e7-8eb1-b98e034446a0.png)

**Comment by tebaly** [comment]
> Зачем вы сделали серый фон? Извините, но большинство девушек ставят возраст любой и город. Им нету значения какого возраста парень. Они и так игнорили, а щас вообще никому отвечать не будут... Сделайте, как было!

![image](https://user-images.githubusercontent.com/9466814/32081385-c5d41508-babd-11e7-9707-6988db5af233.png)

**Comment by SVIT-Lanka** [comment]
Не могу сказать, что прям красота получилась... По началу вообще подумала, может Знакомства "поломались" и не активны сейчас))) Но, идея хорошая! По крайней мере заставляет обдуманно выставлять критерии поиска) Ну и скрывает мозолившие глаза предложения спам-дрочеров)

Предложение: добавить инфу, мол "серым выделены те, кто не подходит Вам по критериям поиска. Для изменения критериев нажмите Настроить" (согласна, как для идиотов) Куда-нибудь в Знакомства или сюда вот: 

![11](https://user-images.githubusercontent.com/29144506/32093729-26a97d12-bb06-11e7-93bc-1818138ecf73.jpg)

**Comment by tebaly** [comment]
Спасибо. Добавлено модальное окно при клике по "серости". 
* Требуется обязательное подтверждение - нажатие "Ок"

**Comment by SVIT-Lanka** [comment]
Заметила такую мелочь...

Фильтр в Знакомствах отсекает (скрывает серым) пограничные значения по возрасту.

Т.е. если я ищу от 18, то 18-летние уже скрываются. Это же приводит к выводу капчи при попытке написать мне  пользователям с этим возрастом.

**Comment by tebaly** [comment]
> Фильтр в Знакомствах отсекает (скрывает серым) пограничные значения по возрасту.

Спасибо. Исправлено

---

> Это же приводит к выводу капчи при попытке написать мне пользователям с этим возрастом.

Вы в этом уверены? :dizzy_face:

**Comment by SVIT-Lanka** [comment]
Мои логические догадки, так скажем. Других противоречий для вывода капчи не обнаружила, вышла только на вот эти ограничения с возрастом.

**Comment by tebaly** [comment]
@SVIT-Lanka - вы обнаружили критически значимый баг, которому уже столет в обед :fearful:
* Вам полагается премия в криптовалюте.
* А мне жесткая порка))

**Comment by tebaly** [comment]
Фикс применен

**Comment by SVIT-Lanka** [comment]
@tebaly - премию закиньте на мой кармический счет)

... и снимайте штанишки, я пошла за ремнем!)))

**Comment by tebaly** [comment]
... тогда уж веревки, плётку, кожаную маску и страпон. 
Наказывать так наказывать. К чему вам эта детская атрибутика :relaxed:

**Comment by inquisitor6789** [comment]
> К чему вам эта детская атрибутика 

у каждого свои фетиши :smiling_imp:
@SVIT-Lanka видать больше любит простые вещи, чем все эти лишние прибамбасы

**Comment by SVIT-Lanka** [comment]
@inquisitor6789 , Ваша правда! Вот насмотришься/начитаешься всех этих БДСМщиков и страпонесс, и хочется чего-то простого, естественного чтоль :)
