### ISSUE TITLE
Новые элементы в описании жалобы

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#492]
➚ 19 часов ⚑ 19 часов
в заголовке жалобы появились новые элементы. Как их следует понимать?

**Comment by tebaly** [comment]
Это попытка разделить время добавления/обновления жалобы. Черновой/временный вариант

**Comment by SVIT-Lanka** [comment]
Присоединяюсь к вопросу)

**Comment by tebaly** [comment]
➚ - стрелка вверх вправо. Время обновления жалобы. Например жалобу прокинули через арбиртаж или посупила новая жалоба идентичного содержания и так далее (19 часов)
⚑ - флаг на флагштоке. Символизирует время основания жалобы. Время первичного поступления/подачи (19 часов). Чаще всего отличается от первого.

* Сама по себе _жалоба_ сферична в вакууме. Не фиксирует ни время её появления ни того, кто её подал. Фиксируется только текст/содержание жалобы и некоторая информация о статусе. В ней фиксируется только время обновления. 
* Иная важная информация, такая как идентификатор подавшего и время получения хранится в другом списке. Эта информация подключается при необходимости, например при просмотре профиля нарушителя. Там некоторые из жалоб могут многократно повторяться, и это нормально.

**Comment by tebaly** [comment]
Секунда/Минута/Час/День/Месяц - скорее всего заменим на с./м./ч./д./м.

**Comment by SVIT-Lanka** [comment]
Сейчас ссылка "от кого жалоба" ведет на **админский профиль**. Предлагаю заменить на **пользовательский профиль**. Больше пользы будет)

**Comment by tebaly** [comment]
@SVIT-Lanka - только если не добавить список отправленных жалоб в профиль модератора :)
А так, много ли пользы знать кто пожаловался?

**Comment by inquisitor6789** [comment]
> А так, много ли пользы знать кто пожаловался?

иногда бывает польза. Например для жалобы "ах ты пидор (дальше придумайте сами)" есть смысл посмотреть профиль жалобщика

**Comment by SVIT-Lanka** [comment]
Польза есть, кстати. Несколько раз выходила так на педофилов и проституток. У нормальный пользователей на них 'нормальная' гневная реакция тоже бывает. Так что, там еще смотреть надо, кого и за что наказывать)

**Comment by tebaly** [comment]
Спасибо. Поменяю при следующем патче (1-2 дня)

**Comment by tebaly** [comment]
Есть проблема...
* #088888 - это анкета
* @088888 - это админ профиль

А какую козявку поставить перед цифрами, если ссылка на профиль, когда она именно цифрами..

**Comment by tebaly** [comment]
#499
