### ISSUE TITLE
Призы, подарки, конкурсы, тамада

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#494]
@inquisitor6789 @SVIT-Lanka

> Проблема в том, что все отказались от этого уже на стадии обсуждения идеи...

Давайте снова вернемся к теме. Не смог отыскать, но здесь точно это мы где-то обсуждали. Личную переписку я сюда тянуть не буду, но пообсуждать заново вполне себе можно.

## (1) Базовые выплаты

В идеале, после того, как будут введены платные ништяки на сайте, направлять весь доход с них на выплаты модераторам. Это относительно сложно реализовать технически, так как существует вероятность продажи/перепродажи учеток и тому подобное лядство типа накруток, так как появляется "материальная цель" у потенциальных мошенников в этой сфере. Но это всё равно придется делать так или иначе. 

Тем более, возможны платные услуги от администраторов типа проверить фото/имя/анкету/желания или _установить статус_ для анкеты, удалить замечания/жалобы и так далее, придумать можно. Деньги от этого источника можно напрямую возвращать модераторам. Проблемы тут ещё и в организации юрлица/счетов/потоков/налогов/отчетности... Острова нам в помощь. Эту идею мы затрагивали в личном общении с администраторами. Базовые выплаты создают оверхед в процессе разработки, да, но планировать и писать можно было бы начинать потихоньку.

## (2) Достижения

Более простой схемой можно считать разовые призовые выплаты по аналогии с достижением. Например "Лучший насователь" для зоркого админа, "Лучший репортер" для того, кто сообщает об ошибках в работе сайта и так далее. Учредить так называемые призовые места и осуществлять выплаты в некотором промежутке времени. Будь то достижение "Года" или "Месяца" или "Разовое" с присуждением уникального достижения.

Тут просто нужно составить графики и нафантазировать список достижений. Денег в бюджете не много и кидать по 100К деревянных всем каждый месяц не самая оптимистичная цель. Но на АйФон можно, SE :stuck_out_tongue_winking_eye: или шестерка - пока вполне хватает))

**Comment by inquisitor6789** [comment]
от базовой выплаты я бы отказался от слова совсем. Вы правильно обозначили риски. Кроме того, можно тупо сидеть, совершать пару действий в день (показать, что я активен) и тупо рубить бабло. Мне это напоминает историю с безусловным доходом в Швейцарии. Если бы это там приняли, то даже активность работы не надо было бы показывать. Просто сидеть на попе ровно.

**Платные услуги**
Да, наверно можно сделать что-то типа этого. Но в этом случае встает вопрос о распределении доходов - кому сколько отщипывать. То ли модеру/админу большую часть отдавать. То ли сервису. Но это вопрос для обсуждения.

**Призовые места за достижения**
На мой взгляд, наиболее разумный способ премирования. Чем больше приносишь пользу проекту, тем больше тебе бонус. 

**Штрафы**
Нельзя про них забывать. Если кто-то сильно накосячил (неправомерные решения, троллинг админов как это любил делать @mj4444ru и т.п.), то его надо карать материально. Для этого можно делать некую задержку по выплатам. Например, после начисления ништяков на виртуальный (на стороне сервиса) счет админа делать задержку перед перечислением на персональный счет. Это необходимо для того, чтобы можно было проверить деятельность выгодоприобретателя...

**Comment by SVIT-Lanka** [comment]
Из отзывов  

> Ребята спасибо вам за такой крутой проект вы хорошо постарались я очень удивлён что такие сайты есть , где все без коммерции, и ещё раз спасибо

оставлю пока здесь, по теме отпишусь позже.

**Comment by tebaly** [comment]
Давайте начнем с разового/ежегодного "вручния" премий. Нужно нафантазировать собственно номинации и выбрать даты для их вручения. Возможные даты
* День рождения проекта **20 апреля** (2010.04.20)
* За пять дней до Нового года - **26 декабря**
* **10 июля** - день бездаты

Любые даты предлагайте :heart_eyes:

**Comment by tebaly** [comment]
Как то было вручали 
* Тролль года - достижение
* Титул главного тролля сообщества :1st_place_medal:
* Лучший борец за права сферического Пользователя в вакууме - достижение

Ход истории восстановить не получается, дату вручения вспомнить не могу. 
То ли **10 января** https://github.com/freedomsex/freedomsex/issues/379#issuecomment-300562409, то ли раньше... На начало года премии ставить наверное не стоит, так как все заняты праздниками, хотя вполне можно и так.

**Comment by tebaly** [comment]
Нужно думать какого-то рода голосование, так как моё мнение сильно субъективно
* Лучший администратор и всея Инквизитор - @inquisitor6789 
* Защитник кода, супер Багхантер  - @SVIT-Lanka

**Comment by inquisitor6789** [comment]
4.04 хорошая дата по-моему :-)
а по номинациям ничего не могу сказать - не слежу за другими т.к. некогда. Да и некая сводная статистика не помешала бы

**Comment by tebaly** [comment]
5.02 тоже норм и 5.03 можно. 
А 3.01 - сделать всероссийским днем защиты от информации

**Comment by tebaly** [comment]
@SVIT-Lanka отзывы бывают разными

> Фуфло лохотрон регистрируется, деньги берут а на сайт зайти невозможно.

**Comment by tebaly** [comment]
# 26 декабря

По дате возражения имеются?)

Номинации две по прежнему две. Третью так и не придумали.
* Лучший администратор и всея Инквизитор - @inquisitor6789 
* Защитник кода, супер Багхантер - @SVIT-Lanka

Призы подарки
1000$ и 750$ соответственно. 

Вероятно будет не всё гладко с переводом, так как есть возможность воспользоваться только новомодными криптовалютами.

**Comment by inquisitor6789** [comment]
адреса кошельков можно уже сейчас?

**Comment by tebaly** [comment]
Возможно в какой-то другой крипте. Может Эфир... Биток глючный вроде. Я ещё не определился))

**Comment by inquisitor6789** [comment]
> Биток глючный вроде.

с чего он глючный? просто у него комиссия за перевод зашкаливает. Может выйти больше суммы самого перевода. Особенно если не с персонального кошелька (того, который на своем компе стоит) переводить. Да и долго подтверждения ждать можно... А так... Особых глюков не заметил...

**Comment by SVIT-Lanka** [comment]
HNY18S31TJfXtBYM4P9

**Comment by tebaly** [comment]
Все подарки розданы! За новыми занимайте очередь :stuck_out_tongue:
