### ISSUE TITLE
Ресурс станет гетеросексуальным, уже точно

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#496]
Откроем печальные цифры... Они такие большей частью на всех сайтах знакомств, а у нас ещё и небывалый сервис... так что нового в этом мало. Здесь же прямой ответ на вопрос, почему так много "развода" и мошенников в виде _тематических сайтов_ в интернете. И так мало ответов от девушек. 
* По статистике ресурс используют парни которые ищут девушку (+75%) 
* Анкеты в которых пол совпадает с полом собеседника 5%
    * Геи по проекту наблюдаются в количестве 2%
    * Лесбиянки, 3% от числа всех анкет...
* Остальные не определились (18%)
    * Из них девушек 3%

---

Итого. 95% целевой аудитории против 5% гомосексуальных анкет. Сожалею, но на ресурсе будут повышены возможности общения и знакомства до _"только гетеро"_

https://github.com/freedomsex/freedomsex/issues/401#event-1348680430

**Comment by GetNight** [comment]
Это не может не радовать. Тотальная толерастия уже достигла апогея. Когда 5% в прямом и переносном смысле имеют 95%.

**Comment by tebaly** [comment]
На всякий случай стоит подчеркнуть. Сами предпочтения конкретных Пользователей к изменениям не имеют никакого отношения. Толерастия/Гомофобность и иное к теме не относятся никоим образом. Как было описано выше, и обсуждалось ранее, нет технической возможности и объективной необходимости поддерживать принципиально разные агломерации Пользователей в рамках одного проекта.

**Comment by tebaly** [comment]
Изменения на dev сервере

**Comment by tebaly** [comment]
#499

**Comment by tebaly** [comment]
> Верните как было. Сайт Ваш обречен. [анон]

> Люди уходят с Вашего сайта. [анон]

:scream: :fearful: :cold_sweat:

**Comment by tebaly** [comment]
> Прошу вернуть возможность девушкам знакомиться с девушкой.Так же,прошу добавить возможность блокировать возможность писать мне людям,попадающим под определённые критерии.К примеру,мне уже на нервы действует,что мне пишет куча озабоченных кретинов,которые не умеют читать и не понимают что я ищу ДЕВУШКУ а не парня.Я лесби,мне нафиг не сдался противоположный пол.

> Был отличный ресурс , до изминения, спасибо и удачи

> Подскажите как изменить в настройках,кого хочу найти, ищю девушку а вижу только парней

> Ребята,верните БИ-знакомства!!! Пожалуйста!

> Верните как было. Зачем сделали что я не могу выбирать кого ищу

> ну и что это за дискриминацию вы устроили на сайте???
