### ISSUE TITLE
Отображение наличия исходящих сообщений в строке пользователя.

### ISSUE THREAD

**Issue by toshamanski** [freedomsex/freedomsex#498]
Или отображение в анкете информации, что данному пользователю уже было отправлено сообщение.
Или отображение в списке "общение" исходящих неотвеченных сообщений.
Без таких маркеров очень сложно понять, кому писал, а кому нет. Так же пропадают переписки с пользователями, получившими наказание. Личный кабинет живёт на данный момент своей жизнью, в общем. И нынешняя система отображения в поиске требует доработки. Разница между типами пользователей в результатах поиска чудовищна. Если я ищу девушку, зачем в результате присутствуют анкеты, где девушки ищут исключительно девушек? Поправьте, пожалуйста.

**Comment by tebaly** [comment]
Есть разметка в поиске. Просмотренные анкеты подсвечены серым

**Comment by meganafig** [comment]
Согласен на все сто.если просматривалась анкета,либо писали-серый цвет.к чему дополнительные фишки?

**Comment by tebaly** [comment]
#486 - аттач
