### ISSUE TITLE
ЧТО НОВОГО

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#499]
Сейчас проект рассчитан только на девушек, которые хотят найти парня и парней которые ищут девушку в данный момент. Сервис быстрых знакомств с возможностью анонимного общения и приватного обмена фотографиями.
* Теперь только гетеро знакомства, парень-девушка #496
* Теперь без оскорблений, БДСМ общение нарушает правила https://github.com/freedomsex/freedomsex/issues/401#event-1348680430

Большие изменения. 
Чую много багов всплывет... 

![image](https://user-images.githubusercontent.com/9466814/34071823-d9612988-e28d-11e7-9115-a48f6b23af18.png)

**Comment by SVIT-Lanka** [comment]
Можно пояснения, для самых одаренных?)) Что мы теперь относим в Наказано, а что в Блокировано? А то прям растерялась... Насколько я поняла, просто оскорбления, как ответные или рожденные в споре за истину - это наказано. А оскорбления в первом сообщении, предложения аля БДСМ со шлюхами и блядями - в блокировано?

_Знаешь что?пиздуй Ка ты на хуй,умник ебаны_  - наказано
_Хочу ... Зделать тебя конченой блядью и шлюхой_ - блокировано
_Привет шалава. Давай пошалим?_ - блокировано

Каков предел ошибок? Ведь "наказать" сообщения можно случайно. За одно-два таких сообщения блокировать же не будем? Или будем?)

**Comment by tebaly** [comment]
Всё так :blush:

Как это всё разрулить я вообще хз))) Точно сразу не получится. Так ещё кроме идеологических проблем много по архитектуре ещё поправить нужно. В целом трактовка правильная. Именно против _"Привет шалава."_ нововведение в части оскорблений и вводилось.
* Слишком часто стали появляться жалобы подобного содержания. Более того, это всё указывает на проведение своего рода атаки на ресурс. Боты или полуботы рассылают такие сообщения девушкам с целью дискредитировать ресурс. Одним выстрелом двух зайцев, главное не выстрелить себе в ногу.
* В тексте релиза я попытался сделать акцент именно на оскорблении в начале знакомства и "преднамеренность" оскорбления, "личное" оскорбление. Добавляется новый фронт неопределенности, так как "оскорбить может что угодно" и каждый администратор станет трактовать оскорбления по своему. 

На некоторое время право действовать отдается всецело в волю Администратора. Если считаете нужным - блокируйте. Имейте ввиду автоматические блокировки по маркеру жалобы, чтобы не цепляло невиновных Пользователей. Постепенно внесем правки в Правила, Соглашения и Справку, чтобы снять давление неопределенности.

Нет необходимости действовать срочно. Информирование пользователей произведено в рамках "Мы предупредили, если что..."

**Comment by tebaly** [comment]
> вот у вас сайт секс знакомств, хочет человек поизвращаться, позапредельничать вы его блокируете, вопрос зачем тогда ваш сайт если вы не разрешаете материться и извращаться? типа вот я снимаю с тебя трусики и вхожу в тебя а ты у меня сосешь писю, ну это же детский сад, разрешите грубые слова и не ограничивайте людей в извращениях. так нравится ваш сайт но с каждым разом хуже и хуже, даже не возбудиться

Если я всё правильно понимаю, то никто маты не запрещал. О чем сказано в полном тексте релиза. А именно: _"Вы по-прежнему вправе использовать в общении нецензурную лексику. Делать этого вам никто не запрещает, но только в тех случаях, когда это не оскорбляет вашего собеседника. Никакой другой цензуры на сайте нет и не было."_

## Хочет человек поизвращаться

Сайт ассоциируется с извращениями только у праведных нравоведов, для которых само слово секс судя по всему извращение и нецензурное ругательство. Для извращений, пожалуйста, найдите другой ресурс. Здесь вы вправе общаться так, чтобы это было приятно вашему собеседнику. Так как здесь не общение и не мессенджер, а знакомства. Познакомились, обменялись контактами, и Го общаться в ВатсАпп... Вот такая политика... 

А извращайтесь сколько хотите, пока на вас нет жалоб. Доступа к переписке нет ни у кого. Её никто кроме вас не читал и не читает. Но вот если пошли жалобы, приносим извинения за неудобства....

## вопрос зачем тогда ваш сайт

Для знакомств. У нас секс это норма, но оскорбления собеседника запрещены. Всё просто. Предложить секс это нормально, а предложить вы*ебать как ш*юху - оскорбление.

**Comment by SVIT-Lanka** [comment]
> вот у вас сайт секс знакомств, хочет человек поизвращаться, позапредельничать вы его блокируете, вопрос зачем тогда ваш сайт если вы не разрешаете материться и извращаться? типа вот я снимаю с тебя трусики и вхожу в тебя а ты у меня сосешь писю, ну это же детский сад, разрешите грубые слова и не ограничивайте людей в извращениях. так нравится ваш сайт но с каждым разом хуже и хуже, даже не возбудиться

А можно этого пользователя в перманент по IP, устройству или еще чему-нибудь...? Достал уже своими историями про маму и малышек! И не понимает же (или не хочет принимать), что тема педофилии запрещена!

**Comment by tebaly** [comment]
Можно. На нем и протестируем. Только чуть позже :relaxed:

**Comment by tebaly** [comment]
> [Девушка] Сайт реально тупит ((( профель не поменять что это такое ? Хочу поставить поиск девочек он выдает мне мальчиков ужас ((((

> [Девушка] Почему мне не могут писать девушки, но могут мужики не нужных мне возрастов? Кому мешала эта возможность? 

> [Девушка] Третий раз вам пишу куда делся поися девушек ? Хочу познакрмится с девушкой а вылазят одни парни ????

То ли баннер не заметен, то ли я хз...

**Comment by SVIT-Lanka** [comment]
Это их мужское эго бунтует) Как же теперь без переодеваний то баб разводить на фоточки)

**Comment by tebaly** [comment]
Параметр "кого ищу" (пол собеседника) постепенно удаляется из БД - осталось менее 1% анкет, для которых этот параметр остается указанным. Для остальных данные "кого ищу" генерируются исходя из пола Пользователя указанного в анкете.

**Comment by SVIT-Lanka** [comment]
Обновите эту строку на девушку/парня


![default](https://user-images.githubusercontent.com/29144506/33591338-22246bf4-d996-11e7-9658-c7b5de1f79f9.jpg)

**Comment by tebaly** [comment]
@SVIT-Lanka - спасибо, исправлено

**Comment by Grian59** [comment]
Ну, в общем, не совсем понятно. почему и по каким желаниям,  сайт изменяется.
Пользователи уже нашли лазейку по поводу однополого секса. Или... или кто то им помогает
В любом случае, либо нужна персонификация анкет (что администрация сайта не хочет), либо нужно создать отдельные ареалы обитания однополовых связей, гетерополовых связей. Пусть будут 2-3-4 базы пользователей, разнесенных по секс. предпочтениям. В одну калитку всех не загонишь.  А сайт все таки, постепенно превращается в лесби, хоть и парней больше в 10 раз )) Imho.

**Comment by SVIT-Lanka** [comment]
@Grian59  да не превращается он в лесби, их реально не так уж и много. Большинство лесби, вовсе не девочки. По личным наблюдениям, 1/10 девушек, желающих познакомиться - девушка (и то не факт), остальные парни в облике).

**Comment by tebaly** [comment]
@Grian59 - вы слишком драматизируете. Это решается в 2-3 патча. Проблема озвучена, я ее решу в ближайшее время.

> Или... или кто то им помогает

Автоматизировано, это очевидно.

---

Слишком много внимания к очевидным вещам. Многоцелевой проект сложен в разработке. Поддержание маловостребованных функций, _кратно усложняющих разработку_, затратно и бессмысленно само по себе. Вся эта ситуация чисто техническая. Мне в принципе всегда было всё равно, кто куда чего суёт. А сам я человек весьма раскрепощенный во всех этих делах.

**Comment by tebaly** [comment]
> Ну, в общем, не совсем понятно. почему и по каким желаниям, сайт изменяется.

### Задавайте понятные вопросы получайте конкретные ответы

![image](https://user-images.githubusercontent.com/9466814/34176825-66fae6b8-e512-11e7-8bb5-48411087b73e.png)

**Comment by tebaly** [comment]
#508 - дополнение

**Comment by tebaly** [comment]
#499 аттач
