### ISSUE TITLE
Опции "Только мой город" и "Искать в любом" будут объединены 

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#500]
Настройки пожеланий для поиска всегда были "рюшечками" без какой-либо большой функциональной нагрузки
* Только мой город - указывало на поиск партнера только в своем городе [реал]
* Виртуальный секс - указывала на возможность такого диалога [вирт]

После обновления в августе, появилась "неожиданность" - Пользователи хотели _искать в любом городе_, независимо от того, что указано в графе Город собственной анкеты. При разработке такая возможность была упущена и горячий костыль был успешно добавлен в виде одноименной опции.

"Только мой город" и "Искать в любом" - схожи по характеру, одновременно противоположны во всех отношениях. С той лишь разницей, что первая из них добавляла рюшку "реал" в поиск. 

### Ожидаемые изменения

1. "Только мой город" - перестает существовать как опция. В графе "пожелания" либо останется одна настройка "Виртуальный секс", либо раздел будет убран, и опция будет болтаться по "Возрастом" сама по себе.  
2. "Искать в любом городе" без отметки по умолчанию. Одновременно, отсутствие отметки указывает на _поиск партнера только в своем городе_. Итого, **все по умолчанию получают рюшку "реал"** до тех пор, пока не поставят птичку в опции "Искать в любом городе". После чего рюшка "реал" будет убрана автоматически.

**Comment by inquisitor6789** [comment]
так может наоборот надо? те кто ищет реал, то пусть ищет в своем городе
если же вирт, то в любом.
Даже я, не первый год работающий в ИТ, чуть мозг не сломал от такой логики. Что уж говорить про простых пользаков

**Comment by tebaly** [comment]
@inquisitor6789 итоговый вариант может быть таким

![screenshot 10](https://user-images.githubusercontent.com/9466814/33766375-31861f6c-dc2e-11e7-95b1-6dcaa0947fc7.png)

---

То есть. Если у вас стоит "В любом" - то это не реал точно, но и не вирт. Так как вирт соотносится, но вовсе не обязательно, как мне кажется. 
* Опцию "Виртуальный секс" нельзя убирать. Вас завалят вопросами, как включить маркер [вирт] для анкеты. И вам придется бесконечно горорить, что за это отвечает опция про город...

## Вариант 2

![screenshot 11](https://user-images.githubusercontent.com/9466814/33766516-dbbdd06a-dc2e-11e7-8522-8c25d5acf369.png)

**Comment by inquisitor6789** [comment]
> Опцию "Виртуальный секс" нельзя убирать. 

дык и я про то же. Имхо вирт подразумевает экстерриториальность.

а про связь другого города и вирта ваще не очевидно.

**Comment by SVIT-Lanka** [comment]
Вирт можно искать и в с своем городе, как и реал в чужом. 

Виртуальный секс скорее предпочтение (желание), а не критерий поиска... Будет ли теперь он критерием? Будет ли влиять на выборку?

**Comment by tebaly** [comment]
> Будет ли теперь он критерием? Будет ли влиять на выборку?

Не планировалось. Ни ранее, ни сейчас :stuck_out_tongue:

**Comment by tebaly** [comment]
> Дебильный сайт. Соответственно и разработчики такие же. Люди от вас уходят и правильно делают.

Всё! Я пошел ~~за ним~~ в запой :sob: 

[пью по праздникам и сравнительно мало]

**Comment by SVIT-Lanka** [comment]
Тогда, может, закинуть эту опцию в желания. Зачем она в Поиске, когда не влияет на его результаты)

**Comment by tebaly** [comment]
@SVIT-Lanka - это рюшка, для привлечения внимания. 
Талисман, оберег. У него статус особенный, пока ещё.

**Comment by SVIT-Lanka** [comment]
Ну, если оберег, еще и с особым статусом неприкосновенности... то вопросов больше нет:) 
Хоть все-равно не логично :)

**Comment by tebaly** [comment]
Ну почему же. Желания все в поиске не вместить при всём желании... А обереги (реал/вирт) вполне помещаются. Они более важны как информация. А функционально не нагружены, потому как не все итмечают их. 
* Планировалось делать так, что если нет [вирт] то вы физически не сможете написать. 
    * Но при плохом настроении, можно всё же попробовать "обязать"
* Выяснилось, что многие просто забивают на эту настройку.

Оно влияет уже на "процесс" общения - нужно вводить капчу, если есть "реал" или нет "вирт". Когда города или возраст не соответствуют.

**Comment by SVIT-Lanka** [comment]
Потому, что все другие параметры поиска - возраст, город - влияют на показанный результат. Если я ищу парня из Москвы, то мне выводятся только парни и  только из Москвы, а не из Уфы в придачу. Но, если я укажу, что я ищу виртуальный секс, то получу в результатах поиска людей, которые ориентированы и на реал. Зачем они мне?) 
Получается, что данная опция не работает в контексте поиска. Но отлично работает как параметр анкетных данных, пожелания.

**Comment by tebaly** [comment]
> Зачем они мне?) Получается, что данная опция не работает в контексте поиска. Но отлично работает как параметр анкетных данных, пожелания.

У проекта не было целей "виртуальный секс". Поэтому решено по данной позиции поддерживать любой функционал, не усложняющий поиск партнера. На сегодняшний день я стремлюсь развивать поиск по принципу _минимального фильтра_
* Город
* Возраст от/до
* Пол (теперь авто)

Добавлять функционал по поиску "только виртуальный" собеседник в сложившейся идеологии абсурдно. Одновременно "отсекать" поиском анкеты _виртуалов_ пока ещё противоречит принципу _минимального фильтра_. Виртуалы есть везде. У нас они просто имеют возможность себя обозначить. Остальные, возможность отградиться от них. Но жесткого барьера нет.

То есть, они как бы есть. И оберег для/от них есть. Но проект для них не разрабатывается. Проект для реальных знакомств. А так как виртуалов всё равно никуда ни деть, а их ещё и большинство... То пока опции касающиеся виртуального секса больше для того, чтобы "защитить" реалов от них.

**Comment by tebaly** [comment]
Бета версия по второму варианту на дев сервере

**Comment by tebaly** [comment]
Обновление на всех серверах - #509

**Comment by tebaly** [comment]
#500 - реализовано
