### ISSUE TITLE
Надо с этим что-то делать... 

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#501]
Надо с этим что-то делать:

> Мне что-то пишут открываю сообщения... Там нечего нет..почему? 

> Приходят сообщения, а при открытии пропадают и нет возможности прочитать их 

Если пользователь удален или заблочен, сообщения от него не поступают, то и уведомления не должны приходить. А они по прежнему приходят. 

и с этим:

> Говносайт! Сообщения не приходят адресатам!

> Здравствуйте! Очень неудобно ориентироваться в диалогах! Нельзя ли, например, выводить в поиск только тех, с кем ты еще не общался? Далее, девушки завалены вопросами. Парни ждут, идут задавать вопросы по второму кругу (ибо альтернатива - уйти с сайта, чего вам и им не хочется). Но не видно что писал в первый раз той или иной девушке! Не с блокнотом же сидеть на вашем сайте!

Тут даже предложить не знаю что... Не удобно, конечно, что большинство парней остаются в полном неведении, дошло их сообщение или нет, прочитали его или нет, писал ей или просто посмотрел анкету... сидят в гордом одиночестве и пишут, как в бездну) И начинаются предположения  типа "Сайт не работает", "Тут никого живого"...

Знаю, что уже много раз обсуждалось, но может у кого будут еще какие мысли на этот счёт? :)

**Comment by tebaly** [comment]
Да. Относительно ваших слов _"Не удобно, конечно, что большинство парней остаются в полном неведении"_ я пишу трактат:
https://github.com/freedomsex/docs/blob/master/blog/404-Просто-пишите.md
https://github.com/freedomsex/docs/blob/master/blog/401-Используйте-простые-фразы.md

По иному у меня ничего не получается. Мне очень нужна помощь. То, до чего я додумался в рамках сегодняшней реали - если кому-то из парней что-то не нравится, они как минимум должны понимать, что на одну девушку по статистике приходится ещё почти десять его "коллег" по общению. Чем меньше парней, тем свободнее дышать. Я поставил в приоритет задачу
* Поддержать высокий онлайн девушек на сайте
    * Любые ваши предложения по решению этого вопроса
* До тех пор, пока не решена первая задача, но вопрос о том, как "удержать" на сайте парней, я даже не смотрю. 
    * Сожалею, первая задача очень сложная, и кажется уже, что решения нет

**Comment by tebaly** [comment]
> Если пользователь удален или заблочен, сообщения от него не поступают, то и уведомления не должны приходить. А они по прежнему приходят.

Постараюсь исправить в течении недели.

**Comment by SVIT-Lanka** [comment]
> на одну девушку по статистике приходится ещё почти десять его "коллег"

это реальная статистика сайта? Какое у нас соотношение м/ж в онлайне?

**Comment by tebaly** [comment]
Перегнул сильно :relaxed: 
Извиняйте. Соотношение 4 : 1

**Comment by tebaly** [comment]
![-einsteinsmama-randomcomics- -4181677](https://user-images.githubusercontent.com/9466814/33761222-452a6880-dc19-11e7-9754-906ea18b14f0.png)

**Comment by SVIT-Lanka** [comment]
> Соотношение 4 : 1

 Где все эти барышни???

> До тех пор, пока не решена первая задача, но вопрос о том, как "удержать" на сайте парней, я даже не смотрю

А вот и зря, всё взаимосвязано)

Девушки приходят на сайт, в большинстве своём, как мы ранее выяснили, за парнями. За нормальными адекватными парнями, готовыми к встрече. Тролли/проститутки не в счет. Таким образом, чтоб удержать девушек на сайте, надо задержать тут хороших парней. Попустить дрочеров-спамеров-хамов (реализуется потихоньку) и стимулировать как-то стесняшек, которые напишут свои 20-30 приветов и ждут с моря погоды. А приветы те в море спамошлюховирта просто теряются...

**Comment by tebaly** [comment]
* Попустить дрочеров-спамеров-хамов
* в море спамошлюховирта просто теряются...

До тех пор, пока на сайте не введут обязательную дактилоскопию с забором образцов спермы, это море как было, так и останется. Ну мы можем корректировать размеры этого моря, но оно морем от этого быть не перестанет :sweat_smile:

---

### Попустить дрочеров-спамеров-хамов

Я уж так повелось, совсем не могу делать чего-то в количестве двух одновременно и давно отказался от этой практики. Поэтому либо удерживать адекватов, либо линчевать неадекватов. Под давлением общественности, решено было начать с вырезания частей аудитории, дабы преподнесть иную часть в лучшем свете.

**Comment by tebaly** [comment]
И кстати! 

# А не заявочка ли это на риволюцию?..

Госпожа @SVIT-Lanka - потрудитесь пояснить высказывание "дрочеров-спамеров". 
Вы что, против витра на проекте?

![image](https://user-images.githubusercontent.com/9466814/33765295-2439947e-dc29-11e7-8308-30f2601206c5.png)
* На картинке злой админ, тобишь я 
* Всё сарказм

**Comment by inquisitor6789** [comment]
> На картинке злой админ, тобишь я

а чо такой маленький? :-)

а если по теме, то пока не запретим мультиводство, то дрочеров-хамов-неадекватов останется в том же количестве :-( Завести новую анкету дело 2-х секунд

**Comment by tebaly** [comment]
> пока не запретим мультиводство

Вплотную подошли к этому вопросу, уже чувствуется запах гари

> дрочеров

И вы туда же, как не стыдно :angry:

---

Кажется это бунт :joy:

**Comment by SVIT-Lanka** [comment]
> потрудитесь пояснить высказывание "дрочеров-спамеров"

Я ни в коем разе не против вирта на проекте! Занятие сие увлекательное и полезное от части, так что быть, быть и еще раз быть. Я против клоунов с макаронной фабрики и настойчивых смотрителей. Частенько поступают предложения "давай встретимся, я в твоем городе/я только за реал...", а потом начинается сказочный поток сообщений типа "я прям ща не могу, ты только пришли фото ножек/сисек/попы и т.п, а вот завтра обязательно ..." до тех пор пока не удалишь. Извращаются как только могут)  Ото я про них)


> непринужденно оскорбили большую часть мужской аудитории сайта

Что ж они оскорбиночки то такие))

**Comment by SVIT-Lanka** [comment]
Теперь по теме.

Трактаты прочла. Букашек приодели хорошо)) 

Но по сути, не хватает очень интерактивности. При проектировании нового интерфейса, как мне кажется,  не до  конца продумали логику взаимосвязей между пользователями.

Что если дать всё-таки мальчикам желанный фидбэк, пусть даже отрицательный. 
Если девушка прочла сообщение и оно её не заинтересовало, дать об этом знать. Можно добавить кнопку в окно быстрого ответа типа "**Мне не интересно**". 
- это не сильно отяготит девушку, т.к. клик по кнопке будет равносилен просто закрытию окна
- в Общение этот контакт не перелетит (не будет хламить лист приятных собеседников), как в случае с таким же отрицательным ответом в форме сообщения
- парню придет сообщение от этого адресата, сгенерированное автоматически, вроде "_Этому контакту не интересно Ваше предложение_". Хоть какой-то, но ответ)) Ну и знак того, что сообщение прочитано.

**Comment by SVIT-Lanka** [comment]
### Есть еще одна мысля... 

только не кидайтесь камнями сразу:) 

Что, если откатить немного назад и вернуться к идее с избранными, только подать под новым ~соусом~ интерфейсом. Ведь было достаточно просто и работало не плохо.

- Все сообщения, как входящие, так и исходящие, помещаем в Знакомства
- Даем пользователю свободу самостоятельного выбора и кнопку "Добавить в Общение"
- При нажатии диалог перемещается (отображается) в Общение
- При нажатии на "Удалить" - диалог перемещается обратно в Знакомства
- При удалении из Знакомств контакт попадает в бан пользователя
- "Удалить и наказать" - я и щас не совсем понимаю зачем нужно, при условии наличия наказаний по сообщениям и замечаний - убрать
- Блокнот в чат можно добавить

Что получим:

- Упрощение системы интерфейса общения. Отпадет окно быстрого ответа и окно предупреждения о жалобах на пользователя (не знаю, кто читает эти жалобы, тем более, что они не всегда адекватные) Слишком много окон…
- Отображение отправленных сообщений и реальный статус их прочтения.
- У девочек по-прежнему фильтруются знакомства.
- Можно самостоятельно выбирать, кто будет находится во вкладке Общение, а не все, кому ответил. Ведь ответить можно из вежливости и при этом не продолжать общение. 
- Нет случайно и безвозвратно удаленных приятных собеседников.

**Comment by tebaly** [comment]
> Дуже гарна задумка сайту, все чітко, зрозуміло і доступно. Є лише один нюанс в спілкуванні, але це швидше за все залежить від кожної людини. Люди спілкуються і через деякий час не з'являються, або відповідають одією фразою, і більше немає відповіді, хоча людина онлайн.

**Comment by tebaly** [comment]
> Хотелось бы добавить корректив в работу сайта: чтобы 1 человек мог написать только 3 людям, и пока хотя бы 1-2 не ответит ему, другим он писать не мог. Так будет хоть общение, я выходит написал 30 девушкам, никто не отвечает, так как их диалоги со скоростю света летят из-за парней

**Comment by SVIT-Lanka** [comment]
> Уважаемые разработчики,благодарю вас за создание этого сайта,но есть недоделки например что бы прочесть письмо надо бесконца перезагружать страничку-это очень не удобно,контакты с которыми уже переписываешься гад ними ге горит иконка онлайн или нет-это тоже не камильфо и к стати сделайте плиз звуковое оповещание о пришедшем смс,лично в нашем городе девушек мало и можно не успеть когда тебе ответили и её перехватят другие)) плиз доделайте эти существенные минусы,заранее благодарю вас за понимание!!!

**Comment by tebaly** [comment]
#486 - аттач

**Comment by tebaly** [comment]
> Что если дать всё-таки мальчикам желанный фидбэк, пусть даже отрицательный.

Перечитал всё заново. Писал на форуме про асимметричность сервиса, когда на мнения парней во многом забивают, а мнение девушек возводят в абсолют. Я ориентируюсь во многом на существующие и мейнстрим сервисы в нашей тематике. Для меня вдохновителем реформ является Тиндер. Мне кажется, лучше этого приложения для знакомств наверное уже и не придумают, если уж его самого не сговнячат. 

Как можно узнать из истории Тиндера, он и задумывался как инструмент быстрого поиска новых знакомств в новом месте. Например фестиваль, отпуск-тур, путешествие. Когда нет времени для _классической_ схемы знакомств, и очень мало времени на всё в принципе. Но в реальной жизни очень часто просто нет времени для _классического_ паттерна, и все уже давно ждали появления нового или _убыстрения_ старого. 

### Скорость в тренде

В тиндере у парней нет вообще никакой обратной связи. Лайки профилей летят сотнями в никуда. Там даже нельзя передумать или в принципе подумать над выбором. Даже ошибочный свайп нельзя отменить, а если это была ваша судьба, ваш конь или принц?.. Это никого не волнует, скорость в тренде. Поэтому я подумал, и сделал тоже самое. 

Обратная связь нужна только парням. Но здесь никто даже не заметит, если кто-то из парней уйдет с сервиса из-за отсутствия обратной связи. Остальные парни скажут ему спасибо, а другие будут посыпать эту дорогу лепестками роз, чтобы _мотивировать других_ последовать его примеру. На проекте слишком большая конкуренция среди парней.

## На самом деле это проблема

Конкуренция патологически большая. И с этим надо что-то делать. А вы, если присмотреться, заботитесь о комфорте парней, и ратуете за их комфорт, чтобы они задерживались на проекте и в целом их становилось больше. Я считаю, что должны быть ограничивающие факторы. Их можно вводить, как например платную регистрацию для парней, а можно просто оставить эволюционно формирующиеся фильтры  
* Отсутствие обратной связи, определенного уровня комфорта
* Наличие парней в анкетах девушек, фейковые анкеты
* Скрытые блокировки из-за явного нарушения правил

Озвученные проблемы из списка выше можно решить, но действительно ли это нужно? Если на проекте будут реальные девушки, недостатка в мужской аудитории не будет никогда. У нас определенно _нишевой сервис_, он не массовый как может показаться изначально. Если он кому-то не подходит, это вовсе не значит, что кто-то другой не будет от него в восторге.

@SVIT-Lanka  Да, то что вы предлагаете, это круто, спасибо за идеи. Но если копнуть чуть дальше UI-UX, это будет работать уже против ресурса в целом.

**Comment by tebaly** [comment]
> Есть еще одна мысля...

@SVIT-Lanka 

* Блокнот добавил в чат.
* > "Удалить и наказать" - я и щас не совсем понимаю зачем нужно, при условии наличия наказаний по сообщениям и замечаний - убрать
    * **нельзя убрать**. Должна быть возможность "Наказать" прямо из списка Знакомств, так как там уже доступно содержание сообщения. Иначе пользователь будет просто Удалять негативные сообщения, и мы с вами о нарушениях никогда не узнаем
* > Даем пользователю свободу самостоятельного выбора и кнопку "Добавить в Общение"
    * Пользователь ленив по определению - он, пользователь, будет вести **все диалоги в знакомствах**, и будет думать - _"А на кой тут кнопка Добавить в общение"..._. В это самое время, это наше разделение нужно для того, чтобы разгрузить сервер по части _Активных диалогов_. 

Вкладка "Знакомства" - это **неактивные** диалоги и их, если очень грубо - 90%. В то время как "Общение", это крайне активные диалоги, их хоть и мало, но они дают самую большую нагрузку. В идеале, это будет даже два разных сервера, каждый обслуживающий свою задачу. 

Процесс перемещения _из Общения в Знакомства_ вообще малопонятен. Кто и зачем это будет делать?) Как в принципе описать эту логику? _"Мы пообщались, и я решила, что мы ещё малознакомы, поэтому тебя перемещаю обратно в Знакомства"_ :blush:

Не исключаю, что это кому-то будет полезно, но мне кажется, это очень специфическая задача. Мы больше сосредоточены на том, что наш сервис не используют больше недели-двух. То есть, спустя очень короткое время, Пользователю уже глубоко всё равно, с кем он знакомился, а с кем нет - он уже сервисом не пользуется. А на то время, что пользуется, вполне реально запомнить, с кем общаешься. Сам процесс структурирования контактов теперь не подразумевается. Опять же, в идеале, процесс использования сервисом должен быть таким
* Создать анкету > Написать сообщение > Познакомиться > **Обменяться реальными контактами** 

Мы изначально предполагаем, что наш сервис **не используют для общения**. Вконтакте, Одноклассники, ВатсАпп - что угодно, звоните по телефону, по скайпу - но наш сервис не для общения, как такового, а для знакомства. 

### Нет случайно и безвозвратно удаленных приятных собеседников.

По умолчанию в тиндере свайп нельзя отменить и познакомиться дважды тоже. _Интересный собеседник - обменяйтесь контактами_ - это одно из наших правил. Теперь это написано в диалоге удаления контактов.

Интерфейс удаления контактов и сообщений переписан и немного обновлен.

**Comment by SVIT-Lanka** [comment]
Ваши выкладки понятны и логичны, согласна. Я, наверное, на многое смотрю со своей колокольни довольно длительного общения на сайте и упускаю частенько основную идею:)
