### ISSUE TITLE
Система поддержки пользователей

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#502]
- Отзывы из Анкеты работают, **вопросы - нет** (не доходят).
- Вопросы из формы обратной связи так же не доходят до админов.
- Сообщения-ответы от админов (Юльки) не отображаются в Общении вопрошающих, да и вообще нигде не отображаются. Не все же через адрес строку могут добраться...

Фактически обратная связь ~работает через ж...~ не работает.

**Comment by tebaly** [comment]
Не работает - исправим :)

**Comment by tebaly** [comment]
Нашел проблему. Вопросы принимает только от админов/модераторов... 
Исправление с новым обновлением. Скоро.

**Comment by inquisitor6789** [comment]
>  Вопросы принимает только от админов/модераторов...

это было выполнение просьбы некоторых о чатике? :-)

**Comment by SVIT-Lanka** [comment]
> Вопросы принимает только от админов/модераторов...

Не знаю, кто их там принимает... или перехватывает)) до админпанели они не доходят) И админы/модераторы тут на общих основаниях)

**Comment by tebaly** [comment]
Не, это баг на костыль... У нас была форма для вопросов в админке, я решил повесить на ее обработчик "обратную связь". Вышло криво...

![screenshot 9](https://user-images.githubusercontent.com/9466814/33766105-0f597354-dc2d-11e7-944c-56dea3e5d733.png)

**Comment by tebaly** [comment]
Исправлено. 
На dev сервере

**Comment by SVIT-Lanka** [comment]
Не работает

**Comment by tebaly** [comment]
@SVIT-Lanka - http://qrsex.ru (dev сервер)
Я смотрел, работало))

**Comment by SVIT-Lanka** [comment]
Хм.. на деве и смотрела... не работало..

**Comment by tebaly** [comment]
> зато отзыв от админа сразу получил мега оценку (127)

Админы чета редко отзывы отправляют. Поэтому забыл уже, это баг или фича :grimacing:
В отзывах прямая зависимость от рейтинга модератора с максимумом в 127

> но никак не дают об этом знать, ни уведомления, ни сообщения.

Это баг... Поправлю.

----

> вопросы от админа доходят, но в админ панели не отображаются.

Странно. Мои и дошли и отобразились.

**Comment by SVIT-Lanka** [comment]
Что я делаю не так?

в диалогах мои вопросы даже прочитаны, а в админке я их не вижу...
Или негоже свои же вопросы читать?))

![default](https://user-images.githubusercontent.com/29144506/33801953-bcc02fba-dd7c-11e7-83d0-8847d83afbc5.jpg)

С левого акка все проходит.

**Comment by tebaly** [comment]
> Что я делаю не так?

Уж расскажите, как вы это делаете)
А чёй-то вы не спите? :sweat_smile:

**Comment by SVIT-Lanka** [comment]
> А чёй-то вы не спите

Это заложено в планах на следующую жизнь)

> Уж расскажите, как вы это делаете)

Я так поняла, проблема только у меня...

**Comment by tebaly** [comment]
@SVIT-Lanka нет, с вами всё Ok.

`mb_strlen($mess->getText()) < 25`

Оно значит - не пишите вопросов по 25 букв включая пробелы :stuck_out_tongue_winking_eye:

**Comment by SVIT-Lanka** [comment]
> не пишите вопросов по 25 букв

Это типа, мыслите шире и излагайте свои мысли максимально развернуто?)))

**Comment by tebaly** [comment]
Ага :smile: :sweat_smile: :laughing:
 
> Будет ещё приятнее, если вы выскажитесь максимально подробно. 

Поставлю алерт в интерфейсе "Нужно больше букав, милорд")

**Comment by tebaly** [comment]
В основном интерфейсе добавлено уведомление

> Пожалуйста, сообщите больше информации. Хотя бы одну-две фразы, иначе сложно понять суть.

Для админки будет тоже самое, как дело до нее дойдет))
