### ISSUE TITLE
Не показывает отправленные сообщения

### ISSUE THREAD

**Issue by bdd001** [freedomsex/freedomsex#504]
Добрый день. я новенький и такой вопрос возник,  я отправляю сообщения, но у меня не показывает кому что отправлял и не показывает писал ли мне кто то, что то.  так и должно быть или нет?

**Comment by SVIT-Lanka** [comment]
@bdd001 доброго времени суток. Отправленные сообщения не отображаются у Вас, они видны только тому, кому Вы написали (во вкладке Знакомства). Если Вам ответят, то сообщения будут видны у Вас во вкладке Общение.

**Comment by tebaly** [comment]
> Добрый вечер уважаемая администрация сайта!!!! Хочу Вам уведомить как пользователь сайта вашего, что самый первый интерфейс был лучше, чем сейчас, там хоть видно кому пишешь кто отвечает

**Comment by tebaly** [comment]
#498 - прикреплено
