### ISSUE TITLE
реклама? хакнули?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#505]
Заметил, что в некоторых случаях с главной страницы перебрасывает на
http://theshops.pro/aff/?to=http%3A%2F%2Fengev.one-night-stand.club%2Fc%2Fda57dc555e50572d%3Fs1%3D6927%26s2%3D27417%26j1%3D1%26j3%3D1%26s399158
а потом на
http://engev.one-night-stand.club/c/da57dc555e50572d?s1=6927&s2=27417&j1=1&j3=1&s399158

Мы начали рекламировать платных конкурентов?
поправка. не только с главной, но и из админки

**Comment by tebaly** [comment]
> Мы начали рекламировать платных конкурентов?

Мы уникальные. У нас нет конкурентов. Только партнеры))) [шутка]
Это не наша реклама. Причину будем выяснять.  "Взлом" должен подтвердить ещё хоть кто-нибудь. У меня сие поведение не воспроизводится.

> поправка. не только с главной, но и из админки

Отсюда посложнее будет. так как я грешил на скрипт "соцсетей". А его в админке нету...
Может вам комп хакнули?) Вряд ли, но проверить тоже нужно.

**Comment by inquisitor6789** [comment]
проверял уже
может конечно какой-то хитрожопый скрипт шалит....

**Comment by tebaly** [comment]
C недавних пор JS админки и сайта разделен. То есть в самих скриптах каки нет, судя по всему. А в админке сторонние скрипты не подключаются. 

Массовости проблемы вроде нет. Подтвердить взлом пока не получается. 

---

## в некоторых случаях с главной страницы перебрасывает на

Пожалуйста. Попробуйте локализовать проблему. Первое что необходимо подтвердить - _редирект с админки_. И чаще ли он происходит нежели с главной сайта. Благодарю.

---

В консоли страницы можно поискать источник перехода и заблокированные скрипты.

**Comment by tebaly** [comment]
Вероятно форсмажер ... Скрипт партнеров временно снят. Попробуйте воспроизвести проблему через вкладку "Инкогнито" и/или после смены IP адреса и очистки Cookies + LocalStorage и локальной базы данных браузера. 
* При возможности - с чистой инсталяции браузера
* Или из окружения виртуальной машины, иного устройства с чистой ОС

**Comment by SVIT-Lanka** [comment]
У меня ничего подобного ни разу не было.

**Comment by tebaly** [comment]
Код динамического информационного блока (баннер) заменен. Осталось пинять только на блок AdThis.com - в любом случае необходимо локализовать и в лучшем случае, воспроизвести проблему.

**Comment by SVIT-Lanka** [comment]
Я все собиралась спросить, а был ли баннер с реальными ссылками на комнаты моделей или что-то с памятью моей) А тут вот он))

**Comment by tebaly** [comment]
@inquisitor6789 есть ли новости с фронта?

![image](https://user-images.githubusercontent.com/9466814/34274099-32e063fc-e6a8-11e7-94ec-ed31d684c1d0.png)

**Comment by inquisitor6789** [comment]
пока все так же. 
судя по всему я какую-то бяку подцепил.

**Comment by tebaly** [comment]
Возможность есть, **подтверждений взлома не найдено**. Данное поведение ожидаемо от скрипта социальных закладок. Попробуем это проконтролировать.
