### ISSUE TITLE
Вопрос по дамам.

### ISSUE THREAD

**Issue by Grian59** [freedomsex/freedomsex#506]
Я все чаще вижу дам, ищущих дам, вопреки новой политике сайта.
Некая дама, в желаниях ищет лесби и т.д... Короче полный набор. По идее, она должна в поиске видеть только парней, и не общаться с дамами. И толку от такой анкеты нет.
Ан нет! Открываешь анкету и видишь, **не указан пол.**
Т.е. в нормальных анкетах - Я девушка (рост, вес и т.д. по желанию)
А в таких анкетах просто - никто. Ищу парня, да... а пола нет, и ничего нет
 И, им доступно общение как с парнями, так и девицами. Я специально спрашивал, подтвердили.
Есть дыра в регистрации? У меня не получилось завести такую анкету. или дыра в эксплуатации?
И, таких анкет становится все больше и больше.

**Comment by inquisitor6789** [comment]
а я давно говорил, что сползание в сторону "строго гетеро" до добра не доведет.
Как говорится на каждую хитрую жопу найдется болт с правой резьбой 😈

**Comment by Grian59** [comment]
Как пример приведу 
Леся 28 лет (Онлайн)
Вирт Секс
Я ищу
Парня
Мои желания и фантазии
только с девушкойпышные формыбольшая грудьвиртуальный секссмотреть фотообмен фотокуни очень нежно до оргазмаудовольствие для двоихоральный сексоткровенная перепискадоставлять оргазмы девушкамязыком по клитору до оргазма

Т.е. человек обошел (каким образом?) пол (при регистрации? при юзании?)

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/34107812-a7aa28ae-e40e-11e7-865f-9ce82c05c814.png)

* При нормальном использовании сайта он всегда выкидывает на диалог "Кто вы?".
* Нужно просто добавить редирект на "Кто вы?" из контактов. 
* Можно добавить проверку пола на "ответ", и не принимать сообщения
    * Много ещё чего можно
        * Пол должен быть указан в анкете (В. Высоцкий)

Это просто баг, его просто нужно пофиксить. 
Желания с противоречиями удалить и будет счастие.

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/34413035-e84fe732-ebf1-11e7-9207-62f1fd9fd9d2.png)

**Comment by tebaly** [comment]
Я проверил. До сего момента отправить сообщение из анкеты в которой не указан пол - **невозможно**. Получить сообщение не указав пол было можно, но ответить - всё также _невозможно_.

> И, им доступно общение как с парнями, так и девицами. Я специально спрашивал, подтвердили.
Есть дыра в регистрации? У меня не получилось завести такую анкету. или дыра в эксплуатации?
И, таких анкет становится все больше и больше.

Поэтому повторю: "IT`S IMPOSSIBLE!" :sob:

`if ($this->user->getSex() && ...` - было есть и будет

**Comment by tebaly** [comment]
В теории, поведение _"Получить можно, отправить - нет"_ сохранится. Оно так и задумывалось, чтобы в момент ответа обязать вас указать пол, если это ещё не было сделано в условиях _автоматической регистрации_.

**Comment by tebaly** [comment]
#499 - объединено, добавлено
