### ISSUE TITLE
Списывание рейтинг модератора

### ISSUE THREAD

**Issue by superneo98** [freedomsex/freedomsex#507]
Здравствуйте, у меня рейтинг списывается судя по всему без причины, ведь я даже сообщений не писал толком. Мой ID: 67975042 Был на мастере 3 уровня и за секунду списали до знатока, притом что возвратов и т.д не было и обратно рейтинг, что-то не растёт...

**Comment by superneo98** [comment]
Да и сейчас попробовал. Обработал 300 запросов, кредиты чуть подросли, а новое достижение как было 0 процентов, так и осталось.Притом, что до этого в самом начале очень быстро выросло до Мастера 3. И при этом правил не нарушал,сообщений толком не писал, а скинуло по нулям и не растёт. Сайт очень нравится, но хотелось бы позащищать от тех, кто оскорбляет и т.д...)

**Comment by tebaly** [comment]
За один проход и не объяснить. Смотрите ссылку Подробнее, там описано

![image](https://user-images.githubusercontent.com/9466814/34438648-64d37392-ecb9-11e7-9811-b0e48bba8d82.png)

**Comment by tebaly** [comment]
@superneo98 там есть как минимум дневной лимит. 300 - многократно превышает лимит, и пользу не приносит. Пробуйте 5-10-20 в сутки
