### ISSUE TITLE
Преднамеренные личные. Оскорбления, БДСМ - не всё

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#508]
Кажется есть некоторое недопонимание в администрировании. Сейчас блокируются почти все оскорбительные сообщения. Но об этом не говорилось в релизе изменений, и это несколько противоречит "направлению" развития.

http://sexoo.me/#/releases/2017-12-01

> Вы по-прежнему вправе использовать в общении нецензурную лексику. Делать этого _вам никто не запрещает_, но только в тех случаях, когда это **не оскорбляет** вашего собеседника. _Никакой другой цензуры на сайте нет и не было_.

Блокировка всего, что может потенциально кого-либо оскорбить - тупиковый путь. Границы "нормы" в восприятии у всех разные, включая администраторов и модераторов. Что в любом случае приведет к постоянным спорам. Есть стремление этого избегать. Поэтому выше было обозначено как минимум два эпизода, из-за которых собственно и меняемся

###  С новыми изменениями список запрещенного на сайте дополняется запретом на
* Любые оскорбления, унижения и хамство **в начале знакомства (1)**
* **Преднамеренные личные (2)** оскорбления собеседников

---

> Иди сюда, дрянь!
> У меня Т9 сучка тупая
> Ух какая грязная сучка!

Раздел "блокировано" задумывался как способ борьбы с крайне нежелательными проявлениями. Закидывание в его "всего и вся" значительно затрудняет администрирование и неминуемо приводит к блокировке Пользователей в тех случаях, когда в этом нет необходимости. 

# Преднамеренные личные

С приветствием и "началом знакомства" давно и успешно разобрались. _Преднамеренные_ - значит совершаемый или совершенный с заранее обдуманным намерением, умышленный. Есть очевидный умысел и явное намерение его достичь. В качестве умысла можно предположить
* **Дискредитация проекта**<sup>1</sup>, через женские или мужские анкеты Пользователей  
* **Троллинг**, который мы с вами обсосали со всех строн

Намерение/умысел "оскорбить" при употреблении оскорблений - абсурдно, согласитесь. Более того, нецензурная лексика часто употребляется без очевидного умысла и чаще всего не планируется заранее. Преднамеренное оскорбление
* Планируется заранее
* Имеет определенный умысел 
* Явное намерение его достичь

@inquisitor6789 - мы с вами ожидали "непоняток". Для внесения правок в Соглашение необходимы ваше мнение и комментарии. Любые другие комментарии приветствуются.

---

<sup>1</sup>_Подрывать (подорвать) доверие к проекту и/или заявляемому способу знакомства, умалять (умалить) авторитет, достоинство администраторов ресурса, разработчиков._

_Например: "Привет шлюха!" - намеренно провоцирует негативный опыт общения на сайте у девушек, дискредитируя проект в лице женской аудитории через подставные анкеты парней под видом БДСМ общения._

**Comment by inquisitor6789** [comment]
а что тут непонятного? По личному опыту могу сказать, что в заблокированные стоит сбрасывать оскорбительные сообщения, носящие регулярный характер. Например, "ух какая грязная сучка" на моей памяти появлялось не один десяток раз с разных анкет. С моей тз это намеренное оскорбление.
Кроме того, давайте вспомним про изначальную задумку механизма жалоб - если собеседника все устраивает в общении, то он и не жалуется. Да, тут многие жалуются на простой привет. Но, наверно, это происходит от непонимания простыми пользователями самого механизма жалоб - тупо тыкают на дислайк.

**Про БДСМ**
Считаю, что знакомства с целью найти себе нижнего/верхнего вполне допустимы. Сообщения типа "вам раб/рабыня не нужен/а" или "будешь моей рабыней?" вполне себе корректны. А вот сообщения "Привет. Будешь моей сучкой?" или "на колени блядь" (заметьте, "блядь" в данном случае не междометие) должны быть однозначно блокированы.

**мысли в слух**
Я бы для сообщений, которые в блоке сделал автоматическую блокировку анкеты. Но помечать сообщения как блокированные должны только админы с наивысшим доверием (не обязательно резиденты).

вот как-то так....

**Comment by tebaly** [comment]
> Я бы для сообщений, которые в блоке сделал автоматическую блокировку анкеты
* Оно же и так блокирует, вы разве не замечали))
* Есть отдельный "список" с такими приоритетными жалобами
    * и он тоже блокирует автоматически

Мы уже касались этой темы. Закидывайте в блокировано при крайней необходимости что-то из того, что не особо нарушает правила, но выглядит подозрительно. В идеале это что-то потом оттуда убирать. Так как для подобного "действия" работает другой функционал, хоть и на данный момент в закрытом виде, но он есть и работает. 

Мы с вами договаривались о том, что на время до публикации сего интерфейса, вы будете дергать меня, чтобы я туда чего-нибудь добавил. 

---

> Кроме того, давайте вспомним про изначальную задумку механизма жалоб - если собеседника все устраивает в общении, то он и не жалуется.

Не верно, вы подменяете. Жалобы оцениваются в отрыве от контекста, а профиль нарушителя - в любом удобном виде. Как и говорилось ранее, когда жалобу нужно отметить разрешенной, анкету можно блокировать и нужно при сопутствующих обстоятельствах. Если жалоба поступила, это сигнал администратору, но никак не причина/повод при выборе маркера для жалобы.

---

> Да, тут многие жалуются на простой привет.

#480 - хоть ветка и закрыта, проблема всё ещё актуальна

При ближайшем рассмотрении, всё осталось как и прежде, кроме тех двух пунктов, которые обозначены в начале. Свободы по теме "цензуры в общении" стало больше, но и не до того, чтобы превращаться в тотальный контроль за содержанием высказываний. 

С началом 2018 года начнем зачистки по Пользователям и всякого рода троллям. А в этом ещё нужно успеть закрыть проблемы в интерфейсе Пользователей...

**Comment by SVIT-Lanka** [comment]
@inquisitor6789 теперь это в блокировано?

> Я парень ищу парня я женат
Привет, я парень, если не передумал, то я только за)
хочу, но я мальчик 

Вроде же обсуждали где-то, что, хоть теперь гомо поиск ограничен, но наказывать за сии наклонности и желания пользователей не будем. Или я ошибаюсь?

**Comment by tebaly** [comment]
@SVIT-Lanka - напишите мне пожалуйста на почту. Я вас никак найти не могу :relaxed:

---

**9. Несоответствие действительности**

> 7. Крайне не рекомендуется **сообщать собеседнику о своей половой принадлежности**, месте проживания, возрасте в личных сообщениях. Жалобы на подобное содержание могут расцениваться как попытка введения в заблуждение посредством указания в анкете данных, не соответствующих действительности.
> 8. Оправдания своих действий Пользователями в части не указанных данных, неверно указанных данных и/или невозможности исправить указанные данные может свидетельствовать о эксплуатации таких действий в мошеннической схеме.

Наклонности никто не запрещает. Запрещено сидеть под анкетой девушки, и представляться парнем. Если правильно понимаю, здесь именно эта ситуация. Представить другую, в которой парень будет сообщать о том, что он парень - сложно.

**Comment by tebaly** [comment]
#510 - аттач
