### ISSUE TITLE
Сообщения не отправляются

### ISSUE THREAD

**Issue by Eva31** [freedomsex/freedomsex#509]
Не отправляются сообщения на сайте((( что это может быть?

**Comment by Eva31** [comment]
Не могу даже просматривать существующий диалог

**Comment by PreyOfLust** [comment]
Проблема с сервером.
```
Request URL: http://freedomsex.me/ajax/messages_load.php?id=nnnnnnnn&next=0
Request Method:GET
Status Code:500 Internal Server Error
```

**Comment by Eva31** [comment]
То есть это не у меня проблема? А ваши неполадки?

**Comment by PreyOfLust** [comment]
Я не знаю, кто занимается серверной частью. @tebaly Нужно твое внимание.

**Comment by Eva31** [comment]
То есть проблема не только у меня?

**Comment by PreyOfLust** [comment]
@Eva31 да, не только у вас

**Comment by tebaly** [comment]
Откатил. Обнова кривая... Ссорян :relaxed:
Всех с Новым Годом!

**Comment by Eva31** [comment]
Пасиб))) и вас с наступающим!

**Comment by tebaly** [comment]
Пофиксил. Выкатил по новой.

**Comment by SVIT-Lanka** [comment]
@tebaly  выкат новый - баги те же))

**Comment by tebaly** [comment]
Работает же

**Comment by SVIT-Lanka** [comment]
Вот теперь работает)

**Comment by tebaly** [comment]
Хотфикс :relaxed:

PS: @SVIT-Lanka найдите меня через почту пожалуйста supp***@fre*domsex.*et

**Comment by SVIT-Lanka** [comment]
Уже отписалась)

**Comment by SVIT-Lanka** [comment]
На главной у девочек - только девочки, у мальчиков - мальчики. А вот микс перед этим был очень не плох.

**Comment by tebaly** [comment]
Поправил. Спасибо

**Comment by SVIT-Lanka** [comment]
> Здрасьвуйте! С новым годом! Я столкнулся с одной проблеломой, раньша такого не было( когда когда переписываешься с собеселником то через пару сообщений перекрутка и просмотр последних или новых сообщений становиться не возможно( пользуюсь айфоном захожу на сайт через сафари. как быть? заранее спасибо.

**Comment by tebaly** [comment]
C августа прошлого года в разработке(верстке) активно используется технология CSS Flexible Boxes.  
* Всеми популярными браузерами поддерживается с 2014 года
* Если у товарища древний телефон и версия ПО ...

Проблема поднималась несколько раз, и всегда выяснялось, что проблема в устройства Пользователя. Вероятно сейчас тоже самое, так как "У меня работает" :grinning:

**Comment by SVIT-Lanka** [comment]
Заметила, что такие проблемы часто на айфонах возникают. То не листается, то вообще шапка не отображается. Какие из них уж древние не знаю)
Обратную связь не наладили еще?


В админпанели
- не работает кнопка 'закрыть всё, снять с голосования'
- не доходят замечания (?)

**Comment by tebaly** [comment]
> не работает кнопка 'закрыть всё, снять с голосования'

Исправлено. Спасибо.

> не доходят замечания (?)

Это точно?) Сдедайте пожалуйста отдельный топик, этот нужно закрыть, так как основная проблема решена. Спасибо.

---

> Заметила, что такие проблемы часто на айфонах возникают. 

Сафари, браузер старой версии не понимает FLEX разметки - там всё плывёт. Нет совместимости с этими версиями сафари. Сожалею об этом.
