### ISSUE TITLE
Только реальные знакомства в этом году*

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#510]
\* По умолчанию

Теперь, все новые анкеты получают статус "реал" автоматически. То есть, все _новые_ Пользователи хотят познакомиться _только в своем городе_. Для изменения поведения, необходимо выбрать опцию настройки "Искать в любом городе". 
  
* Фактически, пользователь _обязан указать город_ знакомства (нет)
* Отсутствие города в анкете теперь чаще возбуждает капчу

  ---

Вирт по-прежнему остается как возможность, которую необходимо предварительно "настроить" с обоих сторон. Либо выбрав "любой город", либо дополнительно активировать "вирт". Названия городов _Вирт, Вирт Секс, По Переписке_ - не влияют ни на поиск ни на фильтры.

**Comment by SVIT-Lanka** [comment]
А как быть с этими↓ товарищами?


![1](https://user-images.githubusercontent.com/29144506/34584672-c1374b10-f1ad-11e7-8537-8f306e0ad7b2.jpg)

**Comment by tebaly** [comment]
Е#ическая сила :astonished:
Ну "ради них" всё и делается... Как было завещено господином **MJ** - будет разработан выбор города из списка по предопределенному каталогу, и всё это непотребство канет в лету...

**Comment by SVIT-Lanka** [comment]
Но выбор города и сейчас ограничен списком, они делают это минуя интерфейс. Можно ли их как-то "наказать"? Бо слишком умные))

**Comment by tebaly** [comment]
@SVIT-Lanka (по секрету) есть список "забаненных" названий городов, которые невозможно добавить снова. Достаточно самые назойливые добавить в этот список. Этим должен заниматься непосредственно я, но я этого не делал уже год или больше. Оттого там вакханалия сейчас. 

## Хотите ударить по больному?

Можно добавить туда города типа "Вирт Чат Секс" - но не поднимется ли вой... Давайте согласуем список, если там не очень много. Я посмотрю статистику и скину здесь.

**Comment by SVIT-Lanka** [comment]
Список составить особых проблем не будет, там каждый день одни и те же, сколько их не удаляй. "Вирт секс" и "Виртуальный секс" есть в разрешенных, как по мне, достаточно, чтоб не поднимать вой.

**Comment by tebaly** [comment]
Почистил самые популярные до популярные. Чуть больше в течении дня попробую. 
Вроде стало чище. 

Есть пока функционал, доступный только разработчикам и хакерам (но это не точно). Дергайте меня пожалуйста периодически. А то столько всего в очереди, что проект уже разваливается под своим весом. Только и успевай подпорки ставить :grimacing:

**Comment by SVIT-Lanka** [comment]
> Дергайте меня пожалуйста периодически

А я только вот извиняться собралась, что дергаю по мелочам)

**Comment by tebaly** [comment]
> Добрый день!
Верните пожалуйста знакомства парней с парнями, как и было раньше...
Сейчас эти пидарасы регистрируют анкеты как девушки.
В результате более половины - это всякие гомосек..
Познакомиться с НОРМАЛЬНОЙ девушкой стало ПРОСТО НЕРЕАЛЬНО... (((

C другой стороны анкет девушек стало больше, и отвечают они чаще :grimacing:
Только вот не парни стали регистрироваться как девушки, а лесбиянки пропали...

**Comment by tebaly** [comment]
> Здраствуйте. Давно сижу на этом сайте и замечаю что он становится все хуже и хуже. Дело не в том что дизайн плохой или еще что то. Просто много рекламы и фейков. Я за этот год уже три раза как дурак по Москве катался) хочу предложить вам сделать систему рейтинга или еще что нибудь что бы было видно сколько человек находится на ресурсе, что это анкета не одноразовая. Спасибо за внимание)

Позвонить видимо не вариант :stuck_out_tongue_winking_eye:

**Comment by tebaly** [comment]
Сайт не учитывает все запросы ищущих секзнакомств Невозможно найти партнера секс меньшинствам И поэтому когда пишешь девушке ,есть вероятность нарваться на парня,который за анкетой девушки ищет партнера гея
