### ISSUE TITLE
Запись видео(фото), шантаж(мошенники)

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#511]
# Цитата

Здравствуйте

На сайте  встречаются пользователи под женским анкетами, которые предлагают _виртуальный секс_ по скайпу. Например, пользователь под именем Лера, 24 года. В скайпе просит показать половой член. Далее сообщает, что это видео записано, предъявляя запись и требует денег во избежание опубликования данного видео и массовой его рассылки.

Прошу администрацию обратить внимание на этот факт. Предлагаю внести не полях сайта предупреждение для мужчин, чтобы выходили в видео чат только со знакомыми им лицами.

Благодарю за понимание.
Признателен разработчикам за саму идею такого сайта.

---

## Вас предупреждали

Проект позволяет сохранить анонимность перед собеседником на 100% при соблюдении простых правил конфиденциальности в общении. Скайп является сторонним приложением, и никакие предупреждения разместить в нем нет физической возможности. 

Предупреждение имеется на главной странице сайта и выделено красным фоном. На главной странице, выделено красным фоном. Имеется, выделено красным.
* не делайте денежных переводов
* не нарушайте законов, шантаж. 
* отправляйте фото сохраняя анонимность

> Наш сайт позволяет сохранить вашу анонимность перед вашим собеседником на 100% (!) Вы самостоятельно решаете, кому и что о себе рассказать. Даже _видеозвонок по Скайпу или в видеочате_ можно сделать анонимно - просто наклонив вебкамеру.

**В отсутствии доступа к личной переписке Пользователей, предупредить подобные инциденты нет физической возможности. Наш сайт не предназначен для виртуального секса изначально.**

_При имеющейся возможности вирта, на сайте отсутствуют какие либо специфические способы или средства защиты собеседников решивших начать высоко компрометирующее общение с возможностью его записи и публичного воспроизведения(опубликования). Начиная такое общение, вы делаете это на свой страх и риск._

Дополнительно, предупреждение о мошенничестве имеется в каждом окне текстового чата(общения) и является принудительным - нет возможности его перманентно скрыть.

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/34567509-a35bdd2a-f173-11e7-8ac5-b2ea622b8abe.png)

**Comment by SVIT-Lanka** [comment]
Лохи были, есть и будут. Как вы их не предостерегайте, они всё равно вляпаются.

**Comment by xxaker** [comment]
Меня такие уже неоднократно пытались развести ))) фото лица - пожалуйста, фото члена - да наздоровье, фото лица с членом - идите к буям ))) не теряйте бздительность господа!

**Comment by tebaly** [comment]
Бдительных скорее всего очень мало

**Comment by tebaly** [comment]
http://freedomsex.info/t/zapis-video-foto-shantazh-moshenniki/44
