### ISSUE TITLE
Не все замечания проходят. Нужно подтверждение

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#512]
В последние дни стало меньше замечаний (как мне показалось). Праздники и всё такое... но, накидала несколько штук с разных id - и их нет.

вопрос:
- замечания приходят в админку мгновенно или с задержкой?
- есть ли ограничения какие-нибудь по замечаниям?

**Comment by tebaly** [comment]
Замечания сейчас не только приходят мгновенно, но также и публикуются. Сохраняемый комментарий теперь доступен только после публикации замечания. Замечание можно снять с публикации, отклонив. По умолчанию теперь все замечания публикуются.
