### ISSUE TITLE
Как управлять заблокированными анкетами?

### ISSUE THREAD

**Issue by bearbarian** [freedomsex/freedomsex#513]
Кейс: я по ошибке заблокировал не ту анкету. Где мне посмотреть список всех, кого я заблокировал, и разблокировать, кого надо?

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/34605828-101638e8-f21e-11e7-9885-203fa10a66d9.png)

**Comment by bearbarian** [comment]
Это универсальное решение: нет человека, нет проблемы))

А если по делу?

**Comment by tebaly** [comment]
По делу: есть список активных блокировок. Если активный администратор обнаружит несправедливую блокировку - отменит. Вы сами можете смотреть этот список в разделе "Блокировка". Если не отменит - вам с этим жить...

**Comment by bearbarian** [comment]
Спасибо. Теперь осталось понять, где же раздел "Блокировка".
Надо получить какие-то привилегии, чтобы его видеть?

**Comment by tebaly** [comment]
@bearbarian начинайте с того, кого(1), где(2) и как(3) вы заблокировали. И что по вашему означает(4) _"я по ошибке заблокировал не ту анкету"_.

**Comment by bearbarian** [comment]
Ок, уточняю.

Я как пользователь помечал несколько спамерских переписок в своём списке общения. И то ли я промахнулся, то ли интерфейс затупил, но под раздачу попала переписка, которую я не собирался блокировать. И если я правильно понимаю, то теперь это пользователь не сможет мне написать.
Я периодически вижу всплывающие подсказки, что у меня есть новое сообщение. Но при этом в списке сообщений новых не появляется.  Я так понимаю, это происходит как раз, когда мне пишут с заблокированной анкеты

**Comment by SVIT-Lanka** [comment]
Ошибочно заблокированных анкет за последние дни обнаружено не было.

@bearbarian, возможно, Вы имеете ввиду удаленного собеседника? В таком случае даже всеяадмин не поможет и Вам с этим жить, точнее без этого (собеседника)

**Comment by bearbarian** [comment]
Печаль.
