### ISSUE TITLE
На смартфонах, мобильных и планшетах неудобно переписываться

### ISSUE THREAD

**Issue by Prsvet** [freedomsex/freedomsex#514]
Всем привет! Много обращений по поводу использования сайта в смартфонах, проверил и тоже словил проблему (ipad mini 1 в гуглохроме та же проблема, проверил):

>>Здравствуйте, не листается чат на телефоне, остальные окна нормально, очень не удобно. приходиться удалять сообщения чтобы прочитать новые ( 

>>На телефоне не проматывает сообщения что можно зделать 

>>  Не отображаються все сообщения!на  мобильной(смартфон) версии ,уже пять браузеров скачивал всё бесполезно!

**Comment by tebaly** [comment]
@Prsvet - далеко не на всех. Только там, где _всё ещё нет_ поддержки Flex CSS (~2012 год)
* Такие браузеры есть
* Равно как и старые устройства
* И пользователи, которых устраивает 
    * Старое устройство
    * Старый и не обновляемый браузер
    * Альтернативная версия браузера

Жалобы были, есть и будут. На этих устройствах сайт не работает с середины лета прошлого года и работать не будет. Работать будет только в том случае, если проблему удастся локализовать и обнаружить, что всё это из-за ошибки в верстке, а не в отсутствии адекватной поддержки Flex блоков. 

**Во всех новых браузерах последних версий всё прекрасно работает.**
* Вы же не сообщили ни версию OS ни названия браузеров ни версию браузеров

![image](https://user-images.githubusercontent.com/9466814/34688983-04f2c41e-f4c5-11e7-9577-7435d53ac2f6.png)

ipad mini 1 - дата выпуска 2012 год

**Comment by meganafig** [comment]
Опера,никаких проблем нет

**Comment by tebaly** [comment]
@meganafig ключевое слово **iPad mini 1**
