### ISSUE TITLE
Потребление памяти

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#515]
Заметил, что страницы сайта (как главная страница так и страницы админки) стали жрать немеряно памяти (over 350Mb). Вроде на странице нет ничего такого (видео, флэш и т.п.)... Куда память уходит?
Браузер хром последней версии на 10 винде.

**Comment by tebaly** [comment]
Баннер рекламный отключен?

**Comment by inquisitor6789** [comment]
нет, но его же нет в админке.

**Comment by tebaly** [comment]
Эх.. Так в админке и скриптов как таковых нету...

**Comment by tebaly** [comment]
Сам сайт может скушать много. Там и код не оптимизирован и баннеры динамические с потоковым видео в ротации... Вот там может и ОС повесить, при должном усердии :stuck_out_tongue:

**Comment by tebaly** [comment]
Проблема с кликандером/редиректом больше не наблюдается?

**Comment by inquisitor6789** [comment]
> Сам сайт может скушать много.

хрен с ним с сайтом (хотя не верю что один баннер может столько высосать; каких мне только помоек рекламных не попадалось но они столько не жрали).Меня админка больше волнует. Закрываю из списка задач 3 самых прожорливых и одна из них будет со страницей админки.

> Проблема с кликандером/редиректом больше не наблюдается?

наблюдается

**Comment by SVIT-Lanka** [comment]
На Андроид/Хром ничего такого не наблюдаю. На Винде тоже не заметила, по цифрам вечером гляну.

**Comment by SVIT-Lanka** [comment]
Вин7/Хром чуть больше 100 метров, сайт с баннером+страницы админки.

**Comment by inquisitor6789** [comment]
из жалоб Юле

> Здравствуйте! Сайт просто нереально много потребляет трафика!!! За один день нахождения на сайте расход трафика около 1,5 Гб , около 100 Мб в час! Как так? Исправьте это досадное недоразумение.

я потребления траффика не заметил

**Comment by SVIT-Lanka** [comment]
Оффтоп:

наши же партнеры нас атакуют?) или это такая программа по обмену)


![default](https://user-images.githubusercontent.com/29144506/35017690-fc274eb6-fb2e-11e7-96ca-2755de2bb04f.jpg)

За ссылки на Бонгу блокировать?

**Comment by inquisitor6789** [comment]
> наши же партнеры нас атакуют?)

конкуренты

> За ссылки на Бонгу блокировать?

а как же :-)

**Comment by SVIT-Lanka** [comment]
Хороший вопрос...

> Когда закроют лазейку для чат ботов, которые засоряют поиск и шлют ссылки с вирусом?

**Comment by inquisitor6789** [comment]
> Хороший вопрос...
Когда закроют лазейку для чат ботов, которые засоряют поиск и шлют ссылки с вирусом?

тогда, когда при регистрации будем паспорт показывать :-)
ну или сделать обязательную авторизацию через госуслуги 👿

**Comment by tebaly** [comment]
Лазейки поприкрыты. По памяти мнения разделились. Приходится закрывать, так как проблему не удалось локализовать. Бывает так реагирует блокировщик рекламы.
