### ISSUE TITLE
сервисы сокращения ссылок

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#516]
В связи с продолжающейся атакой ботов-спамеров почему бы не внести в чс адреса сайтов предоставляющих такую услугу? Тем более что в правилах четко прописан запрет на их использование.
Если в переписке промелькнет такой сайт, то анкету блокировать сразу (без жалоб и т.п.). Насколько я знаю, то сообщения мониторятся системой. Так что это не должно вызвать больших проблем.

**Comment by tebaly** [comment]
Спамер использует уязвимость. Я использовал всё это время чтобы проанализировать ситуацию и собрать данные об атаке. В новом патча будем пробовать блокировать такую активность на уровне сервера. Впервые в истории проекта :) так как раньше хотелось делать это на уровне приложения. Приложение работает, но происходит технический флуд системы администрирования большим количеством однотипных жалоб. 
* Жалобы должны были автоматически маркироваться "блокировано" 
* Или перебрасываться в арбитраж с тем же маркером

**Comment by tebaly** [comment]
@inquisitor6789 - можно ваш совет?
* В каждом диалоге висит предупреждение о том, чтобы игнорировали ссылки, мессенджеры, телефоны
* В справке по ссылке описаны наиболее частые случаи обмана/мошенничества
* При переходе по ссылке: **А вы знаете куда ведёт эта ссылка?**
    * Дополнительное описание _всех сопутствующих проблем_
    * Пользователь должен подтвердить согласие на переход по ссылке

## Если пользователь перешел по ссылке
Стоит ли мне, как разработчику за это переживать?... 

Бороться со спамом затратно и бессмысленно. Когда все Пользователи будут знать, чего делать не нужно, результативность спама станет минимально возможной - спамить становится экономически не целесообразно. 

**Чем умнее будут пользователи сайта, тем меньше будет спама. Чем больше будет спама, тем больше пользователей станет умнее. Спам - способ обучить пользователей тому, чего и как делать не стоит.**

Я вижу, что моей целью не должно быть _фильтровать_ спам. Своей целью вижу снизить уровень шума и флуда в системе от спамеров. Возможно технически подрезать максимальный канал спама, чтобы не превышал разумных границ - до 20% от всех сообщений. Я не борюсь со спамом, и не планирую этого делать. Даже когда есть простая возможность блокировать Нарушителей по IP - на нашем проекте этого нет, ведь это тупиковый путь, я думаю.

_Можно попробовать задействовать "антифлуд" для админки по спискам решений - мусора будет меньше. В моей ответственности будет чистка списков от мусора - система станет технически менее прозрачной для администраторов, но более чистой визуально._

**Comment by SVIT-Lanka** [comment]
Я не Инквизитор, но позвольте оставить своё мнение) возможно для размышления)

> Чем умнее будут пользователи сайта, тем меньше будет спама

Вы ставите перед собой слишком глобальные и утопические цели -сделать общество умнее, в то время как все средства массовой коммуникации и массмедиа направленны на обратное. Не спорю, дело благое и нужное! Но тут оно сработает Вам в ущерб.

> Я вижу, что моей целью не должно быть фильтровать спам

Ваша задача, как разработчика, сделать ресурс качественным и потребляемым, а постоянная спам атака на пользователя не располагает его к дальнейшему пользованию и создаёт впечатление низкоуровневого продукта сляпанного на коленке (ИМХО).

**Comment by inquisitor6789** [comment]
> В каждом диалоге висит предупреждение о том,

предупреждение конечно хорошо, но возбужденный самэц их не читает :-) Чем и пользуются спамеры.

>Стоит ли мне, как разработчику за это переживать?...

конечно нет. Но если пользователю было заявлено что НАШ ресурс бесплатный, а тут ему предлагают забашлять неизвестно за что, то это сказывается на репутации НАШЕГО ресурса не в лучшую сторону.

> Когда все Пользователи будут знать, чего делать не нужно, результативность спама станет минимально возможной - спамить становится экономически не целесообразно.

Вот над этим утверждением ржу в голос :-) (сорри). Если мне не изменяет моя дырявая память, то в настоящий момент эффективность спама (не у нас, а в глобальном масштабе) составляет что-то около 0.01%. И это, мать его, окупается! Для того, чтобы спам стал экономически невыгодным надо его эффективность снизить на несколько порядков. Сомневаюсь, что это получится сделать только лишь "повышением интеллектуального уровня пользователей".

>Спам - способ обучить пользователей тому, чего и как делать не стоит.

бгг, Не ожидал такого вывода :-) Я бы еще добавил - уникальный способ :-) Мое имхо - только если пользователь забашляет на стороннем ресурсе из своего кармана и ничего не получит за свои бабки, то  только это его научит чему-то. Но это опять же минус в карму НАШЕМУ ресурсу, т.к. именно тут пользователь получил ссылку.

>Своей целью вижу снизить уровень шума и флуда в системе от спамеров. Возможно технически подрезать максимальный канал спама, чтобы не превышал разумных границ - до 20% от всех сообщений.

да, наверно вполне приемлемый результат. Теперь возвращаясь к старт посту... В правилах написано, что сервисы сокращения ссылок запрещены от слова совсем. Наиболее популярные сервисы известны. Что мешает сразу их фильтровать? Думаю таким способом мы и выйдем на 20%.

**Comment by tebaly** [comment]
> только если пользователь забашляет на стороннем ресурсе из своего кармана и ничего не получит за свои бабки, то только это его научит чему-то.

За последние несколько лет наблюдаю такую тенденцию в отношении мошенничества на многих популярных общественно открытых ресурсах. 

> сделать общество умнее, в то время как все средства массовой коммуникации и массмедиа направленны на обратное.

В пьяном бреду рассматриваю проект как Сообщество. Научить общество может и утопично, но вот провернуть сей финт в рамках Сообщества возможно не так уж и непостижимо.

---

> Наиболее популярные сервисы известны. Что мешает сразу их фильтровать?

Слишком просто :grimacing:
Еще чуть чуть подумаю, может чего и придумаю. 
_"Но потом всё равно сжечь!"_

**Comment by inquisitor6789** [comment]
>В пьяном бреду рассматриваю

вы там поаккуратней. Праздники вроде закончились :-)

>Слишком просто

![image](https://user-images.githubusercontent.com/19651618/35385069-3c92309c-01d8-11e8-936e-ce4ba780df16.png)

**Comment by tebaly** [comment]
> Кроме того, считается, что работа в agile мотивирует разработчиков решать все поступившие задачи _простейшим и быстрейшим возможным способом_, при этом зачастую не обращая внимания на правильность кода с точки зрения требований нижележащей платформы (подход — «работает, и ладно», при этом не учитывается, что **может перестать работать при малейшем изменении** или же дать тяжёлые к воспроизводству дефекты после реального внедрения у клиента). Это приводит к снижению качества продукта и _накоплению дефектов_.

У нас дефектов и так через край. Не хватало ещё на каждое изменение тактики спамера патчить код и выкатывать срочные обновления с остальными недоделанными патчами :persevere:

Озвученный подход ебабелен на стадии прототипа. Именно так проект и развивался три-четыре года назад. Мы же сейчас взялись за напильники, и пилим... Внешне это выглядит не как развитие, а как деградация. Это нормально... вроде бы.

**Comment by inquisitor6789** [comment]
ну как бы да. Только с вашей стороны есть желание как-то встроить это в существующую инфраструктуру. А с моей стороны есть желание сделать простой спам-фильтр пусть и не совсем в структуре проекта, но нормально и безотказно работающий. С моей т.з. предполагалось, что он будет анализировать сообщения (в идеале все сообщения, а не только жалобы) и банить их если сообщение удовлетворяет условиям. Будут эти условия в виде регулярки или же таблицы в БД не суть важно.

**Comment by tebaly** [comment]
> Только с вашей стороны есть желание как-то встроить это в существующую инфраструктуру. А с моей стороны есть желание сделать простой спам-фильтр пусть и не совсем в структуре проекта, но нормально и безотказно работающий. 

В идеале, если это будет работать без учета характеристик устройства Нарушителя (IP адрес например, или скрытые куки/данные для слежения). Хотелось бы использовать паттерны поведения, и это сложнее чем регулярка на наличие домена в строке. Ясно понятно что готового решения не родится за неделю месяц. Но подумать стоит :stuck_out_tongue_winking_eye:

**Comment by tebaly** [comment]
Помогите с названием нового алгоритма.
* Стальное очко
* Глубокая вагина
* ... ваш вариант

**Comment by inquisitor6789** [comment]
стальное очко вполне себе рабочий вариант :-)
можно еще что-то вроде "огненное дилдо", "жопа спамера"...

**Comment by tebaly** [comment]
# Стальное очко

Алгоритм тестируется в бою. Всё что ранее "блокировалось" на уровне приложения сейчас дополнительно банится на уровне сервера, по IP так сказать. Задействовано не на всю катушку, так как при нунешней конфигурации справляется удоблетворительно. Также будет добавлен ещё один фильтр, которому также стоит придумать название, созвучное с предельно возбужденным клитором. Этот фильтр будет реагировать на _малейшие_ прикосновения.

Вопрос решен.
