### ISSUE TITLE
Новый старый спам

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#518]
http://sexoo.me/userinfo/profile/68963123
Сначала шлёт сообщение. А после ответа фото с адресом.
Аналогичное поведение было замечено у шантажистов.
Пора банить по фотке автоматом

**Comment by tebaly** [comment]
Там же коллега давал развернутый комментарий.

> Это нужно заблокировать - спамеры сменили тактику, теперь бот рассылает фото с адресом e-mail и предлагают секс-услуги в ответном письме

**Comment by inquisitor6789** [comment]
так вся проблема в том, что используется нейтральная фраза. И под раздачу могут попасть многие непричастные. Она и на наказание-то не тянет, просто так ее заметней (ну не хватает меня еще и разрешенное мониторить)

**Comment by tebaly** [comment]
Так суть в преобладании зло/добро :) Очень мало кто пишет "Привет, какие предложения?" - предложение чего?... Тут как бы вариантов мало. Уже поднимали эту тему - когда уровень угрозы "emergency" - вполне допустимо заблокировать то, что блокировать нельзя, но при этом от этого мало кто пострадает. Я думаю это как раз один из таких случаев.

**Comment by tebaly** [comment]
> Пора банить по фотке автоматом

Частично вопрос с рассылкой фото решен. Остальное попробуем перекрывать на этапе "регистрации". Гуглокапча нам в помощь...
