### ISSUE TITLE
Заблокировано от 500 до 1700 анкет, случайно

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#519]
В период с 12:30 до 13:30 могли быть и были заблокированы анкеты случайным образом. Всё что было заблокировано по возможности разблокировано. Часть истории переписок для этих контактов могла быть утеряна безвозвратно. Приношу извинения. 

Любые замечания связанные со сбоем прошу оставлять здесь.
При возможности постараюсь минимизировать последствия.

![image](https://user-images.githubusercontent.com/9466814/35622855-67d87e2a-069a-11e8-8b50-f10aeb1fce5e.png)

**Comment by SVIT-Lanka** [comment]
Ага, вот, оказывается, что это было!)
