### ISSUE TITLE
ложные блокировки

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#520]
http://freedomsex.me/userinfo/profile/?id=68992746
http://freedomsex.me/userinfo/profile/?id=68975187
http://freedomsex.me/userinfo/profile/?id=43325066
http://freedomsex.me/userinfo/profile/?id=68982294

год или 2 поднимался похожий вопрос - было бы неплохо видеть причину блокировки. Судя по жалобам блокировать не за что

**Comment by tebaly** [comment]
## Причина блокировки

Привет!  Маленькая шлюшка! = 68992746
Привет маленькая шлюшка) = 68975187
Какие расценки? = 43325066
Скайп платно? = 68982294

**Comment by inquisitor6789** [comment]
это конечно все круто, но в профиле хотелось бы видеть причину

**Comment by tebaly** [comment]
Не, в профиле это слишком. Отдельный сервис с двухфакторной авторизацией и лимитом запросов

**Comment by inquisitor6789** [comment]
нивапрос - где очередь за вторым фактором? Нет никого? тогда я первый? :-)
