### ISSUE TITLE
Спамоборьба

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#522]
К сожалению детектить текст на фото _слишком сложно_. А вводить премодерацию фотографий изначально _невозможно_. На счет верификации анкет можно было бы подумать, но сейчас попробуем переложить эту задачу на плечи великому Googl-у. Хорошо хоть данных у него на всех хватает, и вроде нормально так справляется. Заодно и проверим.

Нововведения спамоборьбы - **гуглокапча на регистрацию**. А так как регистрации у нас нет, то и капчу не видно(инвизибле). Сейчас на тесте но и на стадии черновика вроде работает нормально http://qrsex.ru/

### Из не озвученного ранее 
* Подсчитываются хэши для фотографий - нельзя всунуть одну и ту же фотку в сервер дважды, теперь. Запушено неделю-две назад в качестве теста. Легко обходится, если знать как. 
* Теперь блокируются все заблокированные по IP - как и просила партия.

В целом спама стало меньше(кажется). Гуглокапча должна будет выкосить остальных.
Но это не точно :stuck_out_tongue:

**Comment by inquisitor6789** [comment]
> Теперь блокируются все заблокированные по IP - как и просила партия.

не путай @mj4444 со всеми остальными. я всегда был против бана по ИП

**Comment by tebaly** [comment]
А тут и не совсем по IP банятся. Это как сопутствующая мера. Общий кейс сводится к спискам IP адресов - а у нас списков нет, работает алгоритм _"Стальное очко"_ который сам себе определяет какой IP и на сколько его банить. Ни один человек в этом процессе не участвует на данный момент...

**Comment by tebaly** [comment]
Пробуем нагадить спамеру в рот :hankey:
Возможны проблемы с отправкой фото.

![image](https://user-images.githubusercontent.com/9466814/36640944-149d9d46-1a39-11e8-9703-593494d8626b.png)

**Comment by tebaly** [comment]
![risovach ru 5](https://user-images.githubusercontent.com/9466814/36641018-50823780-1a3a-11e8-8300-3f9dc9e3ca2e.jpg)

**Comment by tebaly** [comment]
Добавлены фильтры на странице списка Пользователей /userinfo/users/?bun=1&sex=2&max=15
* &sex=2 - пол пользователя 1 парень 2 девушка
* &max=15 - максимальное значение по выбранной вкладке

Доведу до ума позже, пользоваться можно уже сейчас. 
http://freedomsex.me/userinfo/users/?bun=1&sex=2&max=15 или
http://freedomsex.me/userinfo/users/?sex=2&max=15

**Comment by tebaly** [comment]
"оно" обычно находится в конце списка. Чтобы найти все личинки, нужно задать фильтр по полу и устанавливать максимум для просматриваемой страницы постепенно уменьшая вплоть до единицы.

**Comment by tebaly** [comment]
Добавлен фильтр **time** - из не очевидного, фильтрует по количеству часов от момента _онлайн_, то есть, как давно был Нарушитель на сайте, по часам от 1 часа. 
* &time=15 - показать всех кто был на сайте 15 часов назад или раньше
* &time=2 - показать всех кто был на сайте раньше двух часов назад

**Comment by tebaly** [comment]
Форма фильтров, пока так

![screenshot 17](https://user-images.githubusercontent.com/9466814/36644287-e1817ca4-1a68-11e8-9092-dd663c738c2d.png)

**Comment by tebaly** [comment]
Добавлен раздел _Чтотытакое_, но добраться можно только через филтры - сути в нем мало... пока.. до проектной цели колонка "Запросов" всё ещё не доведена. Собственно по ней и сортирует... Можно дополнительно лимитировать вывод по количеству. Цифорку больше 50 можно поставить через адресную строку.
* Сейчас в этом списке только завсегдатаи сайта
* Планировалось сбрасывать счетчик вручную администратором
* Что он показывает сейчас и как использовать я хз

**Comment by tebaly** [comment]
Спамоборьба окончена. Вроде как чище стало в админке. Сегодня запускаются фильтры гуглокапчей на сообщения, чем зашлифовываются остатки спама.
