### ISSUE TITLE
Отвалилась история изменения данных

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#524]
Сабж.
Не показывает. Или надо дольше ждать? За 5 мин ожидания так и не показал

**Comment by tebaly** [comment]
Ссорян) Сейчас исправлю

**Comment by tebaly** [comment]
Исправлено 

![image](https://user-images.githubusercontent.com/9466814/36630395-c354bf86-1976-11e8-95f4-e31939ebd5b2.png)
