### ISSUE TITLE
Капча при добавлении фото в чат не очевидна и неудобна

### ISSUE THREAD

**Issue by xxaker** [freedomsex/freedomsex#526]
При добавлении фото в чат из уже загруженных многие пользователи (девушки )) не понимают как пользоваться капчей, особенно с мобильных - надо нажать на круглую стрелку, дождаться пока капча прогрузится и ее решить - это все выше понимания многих и затрудняет общение. Так же эта капча не даёт отправить текст после фотки, приходится выходить из чата и входить заново

**Comment by tebaly** [comment]
> надо нажать на круглую стрелку, дождаться пока капча прогрузится
* она сама загружается и открывается на весь экран
* никаких дополнительных действий от пользователя не требуется

> не даёт отправить текст после фотки, приходится выходить из чата и входить заново

Постараюсь исправить

**Comment by tebaly** [comment]
Исправлено
