### ISSUE TITLE
Звук оповещения о новых сообщениях

### ISSUE THREAD

**Issue by xxaker** [freedomsex/freedomsex#528]
Было бы здорово мочь его включить-выключить в настройках акка

**Comment by tebaly** [comment]
Куда ее запихнуть? 
* настройки акка(анкеты) это же не про звук

**Comment by inquisitor6789** [comment]
наверно можно в другие настройки

**Comment by tebaly** [comment]
там список категорий

**Comment by tebaly** [comment]
Реализовано в доп меню по клику на логотип. Вероятно вынесу в нижнее плавающее, когда сделаю его. Звука теперь выключаемый. Спасибо.
