### ISSUE TITLE
проблемы с админкой

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#529]
не могу открыть историю жалобы
например http://freedomsex.me/history/message/76509/
пишет 504 ошибку (gateway timeout)
да и вообще вся админско-модераторская часть жутко тормозит

**Comment by inquisitor6789** [comment]
сейчас вроде норм

**Comment by tebaly** [comment]
Там завалы 

![image](https://user-images.githubusercontent.com/9466814/37467530-8f0fac5e-2871-11e8-8d80-459ab8d2e533.png)
