### ISSUE TITLE
Имена

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#530]
как-то тут уже поднималась тема имен, но я не помню чем это закончилось
И так, я предлагаю все таки блокировать по маске имени.
То есть, если сохраненное пользователем имя подпадает под шаблон, то анкета блокируется.
Например, есть шаблон *пасс*. И пользователь сохранил имя гей_пассик или Вовапассив (реальные примеры). Такая анкета должна быть заблокирована немедленно и без предупреждений, а имя скинуто либо в null, либо в какое-то нейтральное (типа Ваня или Маня для дам).

А то я задолбался уже удалять всяких ч(м)удаков.

**Comment by tebaly** [comment]
Давайте закроем проблему следующим образом
* Попытка установить имя не находящееся в списке разрешенных **вызывает ошибку**
* Дополнение списка имен в ручном режиме как это было ранее + по запросу
* Все имена по прежнему будут попадать в модераторский раздел

Есть одно НО - количество шлака **в админке** это не уменьшит. Но - нигде на сайте этих имен уже не будет (кроме разве что лога изменения имен).

**Comment by inquisitor6789** [comment]
идея была немного в другом - банить фейков. Например, уже месяц регится какой-то гейпасся или большой_хуй. Нам такой контингент нужен?

**Comment by tebaly** [comment]
Хмм.. В будущем. Вы таким затрагиваете целый пласт аудитории из категории "Гей/пассив/актив/лесби/Би" и так далее. Тут не о "какой-то гейпасся" а сотни Пользователей. Одно дело решить проблему говноимен. Второе, говном... нетрадиционные Пользователи.
* До сего момента мы не противопоставляли ресурс к этим людям. 
* Формулируется это пока что как _"не для"_ или _"не подходит для"_

На сегодняшний день нет безусловного запрета регистрироваться и общаться от лица гея или лесбиянки. С другой стороны, по части существующего законодательства - _запрет или ограничение_ такого общения, **противозаконны**. Как бы странно это не звучало, даже в РФ.

## Нам такой контингент нужен? (в режиме обсуждения)

![image](https://user-images.githubusercontent.com/9466814/37526966-e35047a8-2941-11e8-9d76-b54749d80f7b.png)

Таки может печи начнем строить? [шутка] Вопрос очень скользкий. Мы имеем полное право запрещать искать девушку парнем от лица девушки в составе пары. Регистрировать анкету девушки от лица парня. Но, в случае, когда парень хочет зарегистрировать анкету парня и сообщить о том, что он гей... Ресурс ещё не готов к таким нововведениям.

То есть - ему будет очень сложно, так как не предполагается такого использования ресурса. Но прямо запретить, как мне кажется, мы на это просто не имеем законного права.

**Comment by inquisitor6789** [comment]
>До сего момента мы не противопоставляли ресурс к этим людям.
Формулируется это пока что как "не для" или "не подходит для"

https://github.com/freedomsex/freedomsex/issues/499
> Теперь только гетеро знакомства, парень-девушка #496

что-то вы противоречите сами себе. Или если нельзя но хочется, то можно?

**Comment by tebaly** [comment]
Ну как сказать... Там везде весьма обтекаемо должно было быть. 
* Вход геям запрещен - такого у нас пока нигде нет, вроде бы.
* Геям здесь будет не очень комфортно - да.
* Аудитория проекта не расположена к общению с геями - да.

![image](https://user-images.githubusercontent.com/9466814/37532500-400b7bd0-2950-11e8-912e-4c3b2f88e84f.png)

Если по поводу имён - то способ предложен. Весьма эффективный я думаю. Вы же попутно предлагаете(форсируете) разработку методов функционала по _блокированию Пользователей на основе гендерной предрасположенности_, или как там по научному... Не могу сказать однозначно точно по этому поводу, но _в ближайшее время_ я не могу начать разработку таких функций.

## Теперь только гетеро знакомства, парень-девушка

Возможно не совсем четко описано, но это по части _направления дальнейшей разработки проекта_. В тексте релиза вносимых изменений более точно сформулировано и раскрыто 
http://freedomsex.me/#/releases/2017-12-01

> Сейчас проект рассчитан только на парней которые хотят найти девушку [...] Парни ищут девушек, а девушки хотят познакомиться с парнями. С любыми иными целями общаться на нашем сайте будет не очень комфортно.

Именно в части регистрации анкеты парня и его общения с парнем - не всё так однозначно. Вот если такой пользователь начинает писать натуралам - на него поступают жалобы, и его есть полное право заблокировать. А если жалоб нет, то зачем обострять.

**Comment by inquisitor6789** [comment]
Наверно я не совсем точно выразился, но речь идёт как раз о фейках. Гея, регистрирующих я под женскими анкетами.
До смены ориентации сайта на строго гетеро их как-то меньше заметно было чтоль...
А сейчас одолели прям. Процентов 10 из заблокированных (если не больше) именно такие. Как раз от них я и хочу избавиться.
Так же ещё раз хотел бы обратить внимание на смену пола в анкете. Зачем это было сделано? Затрачивалось под трансов? :-)

**Comment by tebaly** [comment]
Хорошо. Давайте допилим общие вопросы с новой капчей, которые косвенно затронут и этот вопрос. Затем будем смотреть и оценивать ситуацию по преднамеренным гей-фейкам, как потенциальную уязвимость проекта.

**Comment by tebaly** [comment]
Добавлено новое поведение в имена
* Сохранение имени не из списка вызывает ошибку 400
* Пользователь видит сообщение типа "Сохраните любое другое имя"

На данный момент имена всё также будут отображаться/обновляться в админке, но чистить их не обязательно. Теперь новые недоимена нельзя будет сохранить.

.Обновление в течении суток

**Comment by tebaly** [comment]
Главное теперь запомнить где мы убер-функцию обсуждали по геям, но будущее.
