### ISSUE TITLE
жалобы на фото

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#531]
С момента последних нововведений жалобы на фото стали обрабатываться как обычные текстовые сообщения
http://freedomsex.me/userinfo/profile/69773219
вроде как-то давно это уже было

**Comment by tebaly** [comment]
Исправлено. Ошибка была в недавнем обновлении. Спасибо, выкатываю.

**Comment by tebaly** [comment]
Ложные жалобы на фото в текстах перенесены в фото - 201 жалоба
Прошедшие и отклоненные жалобы удалены - 43 жалобы
