### ISSUE TITLE
постоянные уведомления о новых сообщениях и знакомствах

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#532]
в настоящий момент уведомления о новых сообщениях и предложениях знакомства появляются постоянно (спустя 1-2 сек после открытия соотв вкладки).

**Comment by tebaly** [comment]
Было. Отказал вебсервис когда падал сервер

**Comment by tebaly** [comment]
Спасибо за информацию. тогда по вашему сообщению его и поднял :)
