### ISSUE TITLE
решили забацать знакомства для трансов?

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#533]
![image](https://user-images.githubusercontent.com/19651618/38927370-3293852e-430e-11e8-8e41-b2971cfa2d4b.png)

**Comment by tebaly** [comment]
Не совсем. Там сохранился лог без пола `sex: 0`
* с большой долей указывает на **автоматически** отправленный запрос

На сколько могу быть уверен, в интерфейсе _нет возможности_ отправить такой запрос. При обычных условиях такой записи в логе появиться не может. Но это не точно.

**Comment by tebaly** [comment]
Присмотритесь к анкетам с такими данными, если их не много, значит это признак автоматизации регистрации.
