### ISSUE TITLE
отвалились фото в профиле

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#534]
![image](https://user-images.githubusercontent.com/19651618/39039249-d632485c-448d-11e8-9a70-30071b2d0479.png)

**Comment by nhall11qqq** [comment]
Подтвержу проблему, фото отвалились несколько дней назад, ни принять, ни отправить, через прокси работает все. Возможно роскомнадзор телегу ловит, да все попасть не может. Владельцам ресурса проблему решать, само по себе не разблокируется.

**Comment by tebaly** [comment]
> роскомнадзор телегу ловит, да все попасть не может.

Именно

**Comment by tebaly** [comment]
> Владельцам ресурса проблему решать, само по себе не разблокируется.

Сильное утверждение. Так уже совсем ничего не осталось. Видимо завтра придется доказывать, что не виновен.
