### ISSUE TITLE
блокнот отображается внутри окна быстрого просмотра

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#537]
1. открыть кликом любую анкету из поиска
2. нажать блокнот
**Ожидаемый результат**
Окно блокнота откроется в отдельном фрейме поверх окна быстрого просмотра
**полученный результат**
Окно блокнота открылось внутри окна быстрого просмотра
![image](https://user-images.githubusercontent.com/19651618/42225353-08949020-7ee5-11e8-826c-06a596bb1831.png)
браузер хром Версия 67.0.3396.99 (Официальная сборка), (64 бит)

**Comment by SVIT-Lanka** [comment]
У меня открывается в отдельном окне, но там пусто. (Firefox 60.0.2)

**Comment by tebaly** [comment]
Спасибо, исправил.

**Comment by inquisitor6789** [comment]
это поправлено. Но только сейчас сохраняется последнее отправленное сообщение

**Comment by inquisitor6789** [comment]
аналогично блокноту до исправления отображается окно подтверждения если ты не подходишь по параметрам

**Comment by tebaly** [comment]
Откатил недавно обратно. По простому сделать не вышло... Тут думать нужно...

**Comment by tebaly** [comment]
> Но только сейчас сохраняется последнее отправленное сообщение

Да. Добавил как фичу. Не уверен что очень нужно, но добавил.

**Comment by tebaly** [comment]
Поправил верстку. Стало лучше, спасибо.
