### ISSUE TITLE
Сайту не хватает автоматического регулярного и быстрого обновления

### ISSUE THREAD

**Issue by SVIT-Lanka** [freedomsex/freedomsex#538]
Есть ряд багов:

- состояние вкладок Общение/Знакомства (есть сообщение или нет адекватно отображает после обновления);
- новые сообщения в окне чата можно увидеть только после обновления;
Ну и последние мелкие:
- висит последнее сообщение в окне быстрого ответа (после обновления очищается);
- статус в анкете собеседника при первом открытии старый, при повторном - обновляется на реальный.
У меня еще на мобиле появились лаги с загрузкой страницы в последнее время, грешу на инет, но раньше такого не было...

Все они решаются обновлением. 
Я не сильна в коде и не знаю какие методы сейчас для этого используются, но они явно работают не оптимально, не все изменения подтягивают и не все в режиме реал-тайм. 
Может можно в этой области чёт доработать?)
Да, кнопочка "обновить" эт здорово, но это уж совсем крайние меры, как мотыга для пашни))

**Comment by tebaly** [comment]
> не хватает автоматического **регулярного и быстрого** обновления

Для меня на данный момент это спорное утверждение. И я готов выслушать все возможные мнения. В виде выжимки я считаю что
* Если пользователь выйдет обратно к списку знакомств - это хорошо
* Нужно стимулировать пользователей выходить обратно к списку знакомств

Это равнозначно и для списка Сообщений/Общения. То есть, на данном этапе развития я лично не вижу смысла делать _динамику_. Это может казаться абсурдным в 21 то веке, но, каждый день появляются новые сервисы и стартапы, в которых нет "привычных" и ожидаемых вещей. И такие сервисы получают свою часть аудитории.

**Проблема в том, что я реализовал это не самым очевидным образом.** Вы говорите, что нужно обновить - страницу сайта или сайт полностью. Я говорю - _выйдите из чата обратно к списку Знакомств_, и зайдите в тот диалог, который вам будет интересен. И если это будет тот же диалог - выберите его снова. 

![image](https://user-images.githubusercontent.com/9466814/42631044-abc8ee14-85e1-11e8-8953-908a2c0d646f.png)

**Comment by tebaly** [comment]
> висит последнее сообщение в окне быстрого ответа (после обновления очищается)

Это новая фича. Оно больше для парней, когда они начинают писать всем по списку из поиска. Чаще всего отправляют одно и тоже сообщение. 

Не уверен, что девушкам это также полезно. Но знаю, что отвечать каждый раз новой фразой, утомительно и очень быстро _выматывает_. Тогда просто хочется от этого отдохнуть. Отвечая всем одной шаблонной фразой, вы себе сильно всё упрощаете. Практически всегда первый ответ содержит ряд вопросов и требований к парню как к претенденту, а претенденты же равны. Поэтому мне кажется сохранение шаблона будет более востребовано, чем просто пустое окошко для ввода текста.

Добавлю крестик для быстрой очистки.

**Comment by tebaly** [comment]
> У меня еще на мобиле появились лаги с загрузкой страницы в последнее время, грешу на инет, но раньше такого не было...

Это оптимизация... Теперь куски страниц и целые страницы грузятся при запросе и в коде изначально отсутствуют. Это должно было ускорить начальную(первую) загрузку страницы. А дальше всё кэшируется и работает быстро. 

После каждого обновления эти кусочки изменяются  и их необходимо грузить заново. Внешне это выглядит как лаг, и отчетливо видно при медленном интернете или мобильном устройстве. Возможно у вас кккомбо :smile:

**Comment by SVIT-Lanka** [comment]
А то, что в блокноте теперь все отправленные сообщения, а не только первые - это так и должно быть? Раньше, вроде, были только те, что отправлял из окна быстрого ответа или в начале знакомства. Редко им пользуюсь, могу и ошибаться)

**Comment by tebaly** [comment]
Это баг. Поправлю :)

**Comment by tebaly** [comment]
> А то, что в блокноте теперь все отправленные сообщения, а не только первые - это так и должно быть?

Это таки фича. Блокнот сам собирает всё что часто отправляется независимо от того, откуда. Так было изначально, но на время он писал только из быстрых сообщений. Сейчас пишет снова отовсюду. Ненужные сообщения можно удалять. Пишет только на устройстве.
