### ISSUE TITLE
не сработала блокировка

### ISSUE THREAD

**Issue by inquisitor6789** [freedomsex/freedomsex#540]
http://freedomsex.me/userinfo/profile/18530670
похоже что не работает блокировка. По крайней мере по этой анкете.
Анкета заблокирована 5 мес назад, но жалобы на этого пользователя поступают регулярно. И по логу видно, что он кому-то пишет...
мне казалось, что если анкета заблокирована, то и свежих жалоб быть не должно

**Comment by tebaly** [comment]
Там хз, обновлений по жалобам нет. На анкету заходит регулярно...
