### ISSUE TITLE
Статус (GOLD)

### ISSUE THREAD

**Issue by Hellosex** [freedomsex/freedomsex#541]
Здравствуйте. Я пользователь сайта sexoo.me , недавно приобрел статус ЗОЛОТОЙ. При покупке входило Статус и 2500 единиц кредитов ежедневно. После покупки я получил, желанный статус и всего лишь 1000 единиц кредитов, почему? И ежедневно не пополняется 2500 кредитов.
Сейчас на данный момент, с тех пор после покупки, у меня 552 кредитов осталось от 1000. Почему? Где мои кредиты? Вот логин от аккаунта - 70696933

**Comment by tebaly** [comment]
> Где мои кредиты?

Они у вас :) [Кредиты-доверия](http://docs.freedomsex.info/blog/#/%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%8F/%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%D1%8B-%D0%B4%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%8F?id=%D0%9A%D1%80%D0%B5%D0%B4%D0%B8%D1%82%D1%8B-%D0%B4%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%8F-%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE)
