### ISSUE TITLE
Проблемы с начисления балов доверия

### ISSUE THREAD

**Issue by AlexR27** [freedomsex/freedomsex#542]
Пошла проблема с начислением балов доверия,эта проблема может повлечь за собой игнорирование помощи разработчикам, так как делаешь работу модератора, а начислений нет. Я думаю вам стоит решить этот баг

**Comment by tebaly** [comment]
> Пошла проблема с начислением балов доверия

Слишком расплывчатое описание проблемы, и слишком подробное описание последствий. 
Вы спамер?

PS: в справке написано, что существуют лимиты для предупреждения накрутки. Секрета в этом нет, равно как и чего-то необычного.
