### ISSUE TITLE
Почему не сделаете возможным чтобы девушки могли искать девушек и парни - парней?

### ISSUE THREAD

**Issue by mvr25** [freedomsex/freedomsex#543]
Почему нельзя выбрать какой пол собеседника, независимо от своего пола? А то не удобно когда пишешь девушке, а тебе отвечают что "я парень, би".

**Comment by tebaly** [comment]
Пока так, извините

**Comment by BeLNea14** [comment]
есть идея лучше, добавить орентацию " БИ " и там уже указывается пол собеседника а самое поиск всех (М и Ж)

**Comment by tebaly** [comment]
Не сочтите за оскорбление. Вы оторваны от реальности. В рф это уже почти уголовно наказуемо.

**Comment by BeLNea14** [comment]
я не в РФ
