### ISSUE TITLE
Регламент.

### ISSUE THREAD

**Issue by LEGENDARYFS** [freedomsex/freedomsex#544]
Доброго времени суток. Заметил, что в новом блоге регламента нет, а в старом ничего не доступно. В репозиториях тоже не нашёл его, а любые ссылки ведут на несущетсвующую страницу. Соответственно это создаёт трудности для новых модераторов и администраторов, да и старым не помешает иногда память освежить

**Comment by tebaly** [comment]
Поправил 
http://docs.freedomsex.info/blog/#/Сообщество/Быстрый-старт?id=Регламент-сотрудника
