### ISSUE TITLE
Помогите наказать мошенника!

### ISSUE THREAD

**Issue by wecryt98** [freedomsex/freedomsex#545]
В общем одна "дама" оказалась не дамой и шантажировала тем что сольет мои не очень приличные фото моим друзьям из соц.сетей(в итоге не удалось) И требовала денег.Как наказывать таких мошенников или куда обратиться что-бы их удалили навсегда с сайта?

**Comment by wecryt98** [comment]
> В общем одна "дама" оказалась не дамой и шантажировала тем что сольет мои не очень приличные фото моим друзьям из соц.сетей(в итоге не удалось) И требовала денег.Как наказывать таких мошенников или куда обратиться что-бы их удалили навсегда с сайта?

**Comment by tebaly** [comment]
Удаляем почти сразу, но оно может снова зарегистрировать другую анкету под другими данными.
