### ISSUE TITLE
Ошибки отображения (модераторам)

### ISSUE THREAD

**Issue by kamikadzuki** [freedomsex/freedomsex#547]
Приветствую администрацию.
Собственно когда нажимаешь на звание,достижение или процент кредитов то переходит на страницу в которой минимум информации и нет конкретно этой информации.
Попрошу поправить сие ошибку.
Спасибо
![default](https://user-images.githubusercontent.com/47737148/52936808-6ecf2880-336e-11e9-9993-f63c6b408ad2.png)

**Comment by op0xide** [comment]
Когда пофиксят?

**Comment by tebaly** [comment]
Благодарю. Обнова доки на подходе. Там чуть больше работы чем казалось :)

**Comment by op0xide** [comment]
Воскресенье, 24 февраля 2019, 22:19 +03:00 от FreedomSex <notifications@github.com>:
>Благодарю. Обнова доки на подходе. Там чуть больше работы чем казалось :)
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread . 
 Ждем :)

С уважением,
Георгий хорьков
linadremier@mail.ru

**Comment by tebaly** [comment]
Поправил пару дней назад.
