### ISSUE TITLE
Для модераторов

### ISSUE THREAD

**Issue by Amimeshnik** [freedomsex/freedomsex#549]
Не давно начал модерировать на вашем сайте. В итоге подумал об одной вещи которая помогла бы выносить более точные решения при рассмотрение приходящих жалоб.
Приходят ведь всегда только одно сообщение из которого надо выносить вердикт "Да, наказать" и "Нет, отклонить", но иногда из одного сообщение не понятно то какой вердикт нужно выносить. Не проще ли дать в режиме просмотра переписку до момента нарушения чтобы можно было точно вынести вердикт наказывать или нет.
Понимаю что я скорее всего не первый кто это предложил, но решил уж попробовать внести что-то в проект который мне понравился.

**Comment by tebaly** [comment]
> Не проще ли дать в режиме просмотра переписку до момента нарушения чтобы можно было точно вынести вердикт наказывать или нет.

Не первый. Не проще. Вы, уважаемый, жестоко игнорируете конституцию РФ и Права человека ;)
