### ISSUE TITLE
Значёк онлайн и пол в публичном профиле

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#55]
Вынесите в анкете значок онлайн (время отсутствия) в всегда отображаемый блок под именем.
И добавьте информацию о половой принадлежности. В некоторых случаях пол можно понять по дополнительной информации, а если её нет, то только по заголовку браузера, который в телефоне вообще не отображается.
Достали одни и те же вопросы в саппорт на эту тему.

**Comment by tebaly** [comment]
Ок. В течении суток

**Comment by tebaly** [comment]
А нет, быстро не получится. Подумал в админке

**Comment by mj4444ru** [comment]
А сутки всё продолжаются ))) допишите короткий код jquery еоторый перенесёт кнопку куда нить выше в доме...

**Comment by tebaly** [comment]
> А нет, быстро не получится. Подумал в админке

**Comment by mj4444ru** [comment]
![3nk3f5](https://cloud.githubusercontent.com/assets/9354685/26070752/31790384-39bf-11e7-9feb-0e2933e23ce7.jpg)

**Comment by tebaly** [comment]
![image](https://cloud.githubusercontent.com/assets/9466814/26071986/a48d32e4-39b2-11e7-99c3-fddebc73bcf5.png)



В том то и дело. Что в админке было просто сделать - что и было сделано. А так как имелось в виду не только в админке, предложение было заново открыто и "ожидает" реализации.

**Comment by tebaly** [comment]
изменилась структура
