### ISSUE TITLE
Ошибка в сообщениях

### ISSUE THREAD

**Issue by Yalos119** [freedomsex/freedomsex#550]
Ребят, проблема, не могу отвечать на сообщения. Окошко ввода текста получается ниже полоски, и не отображается ни в телефонном формате, ни с компа. Когда на компьютере прокручиваешь вниз, с заднего вона опускаются все анкеты и всё. Поле для ввода текста и так и не отображается. Это уже для ответа на полученное сообщение

**Comment by tebaly** [comment]
Спасибо. Исправлено в тот же день, но с задержкой.
