### ISSUE TITLE
Веченая загрузка при разблокировании "Наказано"

### ISSUE THREAD

**Issue by IMSOLEGENDARY** [freedomsex/freedomsex#554]
В который раз при разблокировании раздела "Наказано" в Решениях перестают грузиться все разделы. В консоль прилетает ошибка: 
![image](https://user-images.githubusercontent.com/61503672/75345846-2d892700-58a6-11ea-89db-ca666410d303.png)

**Comment by tebaly** [comment]
403 - недостаточно прав для доступа.
