### ISSUE TITLE
ряд ошибок

### ISSUE THREAD

**Issue by holapie** [freedomsex/freedomsex#573]
по порядку:
- Кнопка "удалить и наказать" у самой анкеты - банально не работает, она меняет свою текстуру, но ничего не делает, и человек может продолжать тебе писать оскорбления
- Удаленные сообщения тоже магическим образом восстанавливаются
- из "желаний и фантазий" нельзя удалить эти самые желания, хоть и пишут что оно удалено, но оно по прежнему висит на месте.
- в админку ещё ни разу не пришла ни одна жалоба, и люди, которые только и делают, что явно оскорбляют, притом, в грубой форме - никак не блокируются

**Comment by nhall11qqq** [comment]
Наказания на бан не работают с лета 21 года, писал об этом здесь - нет реакции.
