### ISSUE TITLE
сломался сайт)

### ISSUE THREAD

**Issue by holapie** [freedomsex/freedomsex#575]
freedom-sex.me

в знакомства ничего не приходит, в чс кинуть никого нельзя, жалобы не работают, они просто уходят в никуда.

раньше был хороший сайт, а сейчас, остался один узбек, что оскорбления регулярно пишет, и всё.

**Comment by tebaly** [comment]
Ну жалобы пока не работают. Остальное вроде работает...
:)

**Comment by holapie** [comment]
о, знакомства пошли, но в ЧС по прежнему никого не кинуть, кнопка "удалить и наказать" просто меняет текстуру на нажатую, и даже не закрывает диалоговое окно.

P.S. ещё, если удалить собеседника, то ты вновь будешь отображаться у него как новый контакт. мне так одна семейная пара раза 4 написала, и раз 8 парень хотел ЗД, каждый раз получали отказ, но так постоянно сталкиваться - не есть'м приятно

**Comment by holapie** [comment]
да и этот надоел...
![Screenshot_2022-02-02-10-01-03](https://user-images.githubusercontent.com/98284569/152108696-250faa0f-1cbf-45a1-8770-39e3bebf5c89.jpg)

**Comment by tebaly** [comment]
Благодарю за подробный отзыв. Система жалоб пока не работает и будет исправлена в ближайшую неделю.

**Comment by holapie** [comment]
а де? :D

**Comment by holapie** [comment]
ошибки ещё есть, но надо пересоздать, бо больше не реагируют на этот тикет
