### ISSUE TITLE
freedom-sex

### ISSUE THREAD

**Issue by holapie** [freedomsex/freedomsex#577]
не начисляются кредиты доверия (ежедневные)
капча грузит очень долго, и пока картинка появляется - капча уже невалидна
и жалобы так и не работают, хотя обещали сделать давно (((

хотя бы чс почините, плиз, чтобы спамеров убирать. невозможно ведь пользоваться сайтом

**Comment by holapie** [comment]
upd: капча просто невалидна, даже если грузится секунд за 15 (это быстро, обычно она грузит от минуты), вводишь все правильно, но тебя тут же просят ввести новую

**Comment by tebaly** [comment]
Благодарю за отзыв. Капчу проверил - работает. Вероятно баг сложнее чем кажется, если вы уверены что это ошибка, давайте продолжим искать. Система сообщений может не принимать капчу, даже если ввели правильно. Такое поведение не стоит путать с ошибкой или сбоем системы.

**Comment by holapie** [comment]
эх...
походу всем просто до лампочки на репорты и кредиты (

**Comment by tebaly** [comment]
Я проверял. У меня отработало нормально. Я не знаю что у вас за проблема. Она остается? Пришлите подробнее. Пришлите текст который отправляете. Может его не пропускает система безопасности.

Кроме прочего, вы получили ответ в тот же день.

**Comment by nhall11qqq** [comment]
Это нормальная работа капчи для на кого наложено наказание живыми модераторами-админами за какое-либо нарушение. Через время все восстановится.

**Comment by holapie** [comment]
так почему я не могу наказания кидать?
