### ISSUE TITLE
Не работает админка

### ISSUE THREAD

**Issue by nhall11qqq** [freedomsex/freedomsex#578]
С сегодняшнего дня не заходит в админку - страница начинает загружаться и зависает.
Хоть и не полноценно в последнее, но помогала поддерживать порядок.

Возможность банить не работает уже года полтора, анкеты с направлением на бан активны, и продолжают разводить людей.

**Comment by tebaly** [comment]
Сбой, теперь из-за войны. Исправляю как могу.

**Comment by nhall11qqq** [comment]
> Сбой, теперь из-за войны. Исправляю как могу.

И на этом спасибо. Хорошо бы вернулся сайт в состояние как пару лет назад, реальная активность значительно больше была.

**Comment by tebaly** [comment]
Админка исправлена. Благодарю за сообщение

**Comment by holapie** [comment]
так пусто ведь
