### ISSUE TITLE
спасибо. сообщения скоро будут

### ISSUE THREAD

**Issue by holapie** [freedomsex/freedomsex#579]
Мы благодарны вам за вашу подержку. С вами сайт становится ещё сильнее. Благодаря вам анкеты мошенников, троллей, фейков и обнаглевших жриц любви блокируются практически моментально.

и на протяжении полутора года ни единого сообщения. Правила не соблюдаются, и за это никак не наказывают, даже в чс человека кинуть нельзя. может вы уже официально объявите, что эта система не будет восстанавливаться, и на сайте уже давно царит анархия?

сайт: freedom-sex.me, хотя я ни на одном подобном сайте не видела рабочей системы наказаний.

**Comment by nhall11qqq** [comment]
Оно работало, но сломалось...

**Comment by holapie** [comment]
работало, но пару лет назад
