### ISSUE TITLE
Золотой статус ошибка 

### ISSUE THREAD

**Issue by Reddarkpsy** [freedomsex/freedomsex#585]
На залотом статусе , уде несколько дней не приходят кредиты доверия совсем , всегда 0, уже много лет тут , таких проблем раньше не было …

**Comment by tebaly** [comment]
Благодарю за обращение. Ошибку обнаружил, буду исправлять

**Comment by tebaly** [comment]
> На залотом статусе , уде несколько дней не приходят кредиты доверия совсем , всегда 0, уже много лет тут , таких проблем раньше не было …

В течении часа должно заработать. Проверьте пожалуйста

**Comment by Reddarkpsy** [comment]
Так и нет кредитов, общаться невозможно нормально... Исправь пожалуйста... и сделайте так, чтобы можно было поменять аватарку Аккаунт id: 73102182
Спасибо …

**Comment by Reddarkpsy** [comment]
Спасибо , заработало :)))
