### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by RTX6626** [freedomsex/freedomsex#588]
Здравствуйте, на сайте virt3.com, после одного неправильного введённого пароля стала появляться капча, только проблема в том, что она не работает, просто не загружается. Если посмотреть через консоль в браузере, то видно ошибку. 
Что делать? В аккаунт войти не могу, проверьте, пожалуйста, может быть акк вообще в бане, номер акка 248779

**Comment by tebaly** [comment]
Вы ничего не путыете? Пришлите пожалуйста скриншот/фото. Логин пароль заблюрьте

**Comment by RTX6626** [comment]
![Безымянный1](https://github.com/freedomsex/freedomsex/assets/137399551/aab6b6d6-5fd5-4b6a-8df6-1b293be2e0a0)

![Безымянный2](https://github.com/freedomsex/freedomsex/assets/137399551/1f021f4d-d238-4f31-87d2-8e0215f94692)

**Comment by tebaly** [comment]
Благодарю вас за сообщение об ошибке. Я исправил эту блокировку. Кажется она вызвана ошибкой в коде которую еще нужно будет исправить.
