### ISSUE TITLE
Сотрудничество (платежный сервис)

### ISSUE THREAD

**Issue by PreobrazhenskiyD** [freedomsex/freedomsex#589]
Здравствуйте!

Меня зовут Дмитрий, я менеджер платежного сервиса для физ. лиц PrimePayments.io
Принимаем платежи, осуществляем мгновенные выплаты на карты и usdt, массовые выплаты.
Хочу предложить вам наш сервис! 
Рассмотрите предложение?

Для связи: Tg:https://t.me/PreobrazhenskiyD

**Comment by tebaly** [comment]
Напишите пожалуйста на емайл support[а]freedomsex.net

Ваши правила очень абстрактны 
> Сайт не должен продавать товары или услуги, а также действия или бездействия, запрещенные нормативно-правовыми актами, правилами международных платежных систем.

В то же время, я не могу обсуждать эти нюансы публично. Пишите на почту.
