### ISSUE TITLE
Жалобы на сообщения предложения вирта

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#59]
Возможно стоит в сообщении оставлять флаг, разрешён ли вирт у получателя в момент отправки сообщения и не наказывать за вирт если такой флаг был.
Хотя может оно так сейчас и есть. Просто мысль.

**Comment by Fenslau** [comment]
Да ясное дело, что так и есть уже! Иначе какой смысл в этой функции.

**Comment by mj4444ru** [comment]
есть вероятность что для простоты реализации наказываются все...

факт наказания за вирт фиксируется в админке снизу.
но нет возможности посмотреть кому человек писал при этом и оценить действительно ли тому человеку неинтересен вирт.
тут только разработчики знают как оно на самом деле.

**Comment by Fenslau** [comment]
Я полагаю, что модеры и админы фиксируют факт "только вирт" и потом система сама наказывает юзера, если выясняется, что он написал промодеренное сообщение с флагом "только вирт" тому, кому вирт неинтересен. Почти уверен, что так и есть, в этом то и смысл функции.

**Comment by mj4444ru** [comment]
Смысл все понимают, а как сделано, никто из нас не знает...

**Comment by tebaly** [comment]
Пока вас не было, мы приняли Соглашение по вирту за вас. (шутка) Мы собрали в соглашении по вирту всё что было опубликовано ранее.
* вирт не ограничивается так как не запрещен
* цензура вирта отсутствует на данном этапе развития проекта
* предполагаемое _автоматическое воздействие_ за вирт - начало цензуры, это работает только с оскорблениями и блокированными сообщениями

Что греха таить - после маркировки "Только вирт" _планировалось_ запустить на основе такой информации "фильтры". Но это осталось в планах. Давайте устроим конференцию-обсуждение 
* Стоит ли блокировать за вирт
* Стоит ли ограничивать возможность вирта в проекте

**Comment by tebaly** [comment]
вирт не ограничивается так как не запрещен :memo:
