### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Roker74** [freedomsex/freedomsex#590]
Почему не отправляются сообщения с низким уровнем доверия и правильным вводом капчи. Просто зависают сообщения и не отправляются

**Comment by tebaly** [comment]
> Почему не отправляются сообщения с низким уровнем доверия и правильным вводом капчи. Просто зависают сообщения и не отправляются

Спасибо, исправлено

**Comment by Roker74** [comment]
Врать очень плохо но похоже что вы этого не знаете. Как не работало так и не работает

**Comment by Roker74** [comment]
> > Почему не отправляются сообщения с низким уровнем доверия и правильным вводом капчи. Просто зависают сообщения и не отправляются
> 
> Спасибо, исправлено

Ни чего не исправлено. Как не работало так и не работает. Зачем врать?
