### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Roker74** [freedomsex/freedomsex#591]
Почему не отправляются сообщения с низким уровнем доверия и правильным вводом капчи. Просто зависают сообщения и не отправляются
Было написано в ответе что исправлено. Но как не работало так и не работает. Зачем обманывать?

**Comment by tebaly** [comment]
> Почему не отправляются сообщения с низким уровнем доверия и правильным вводом капчи. Просто зависают сообщения и не отправляются Было написано в ответе что исправлено. Но как не работало так и не работает. Зачем обманывать?

Был большой сбой в системе. Внутренних ошибок я не вижу, описанное поведение возможно из-за превышения попыток ввода капчи. Такая ситуация обычно разрешается сама собой, после сброса внутренних счетчиков

**Comment by Roker74** [comment]
То есть если я правильно вас понимаю надо не писать а лутьше всего выйти с сайта на неделю а может и на месяц и тогда после повторного входа через какое то время все будет опять работать.

**Comment by tebaly** [comment]
> оплата всегда происходит на разных людей и с разной суммой? Я сам лично проверял несколько раз при попытке оплаты. Разные номера карт и разные соотвественно люди. И проверка была буквально через минуту

> покупка за поднятие анкеты до статуса особенная

> не писать а лутьше всего выйти с сайта на неделю а может и на месяц и тогда после повторного входа через какое то время все будет опять работать.

Нужно разбираться - если проблема затронула всех пользователей, то здесь и на форуме будет бум тем и вопросов по этой теме. На данный момент пишите только вы, и в целом контекст обсуждения и последовательность "мутная". Внуртенняя блокировка безопасности при частом вводе капчи меньше суток, но если вы покупаете статус - вам это не к чему, для анкет со статусом эта блокировка не действует. 

Для решения проблемы с начислением статуса нужно отправить письмо в поддержку с указанными данными

**Comment by Roker74** [comment]
Я могу вас понять и у меня тоже есть сомнения что проблема только у меня. Но. Я создавал новую анкету и на новой анкету так же не срабатывает отправка сообщений после ввода капчи. Я смотрел на компьютере в консоли браузера что идет одна и та же ошибка при попытке отправки сообщения. Первая ошибка 500 а после ввода кода капчи и зависания сообщения через некоторое время выходит ошибка 502. Жаль что я сейчас не за компьютером я бы вам прислал скриншоты данных ошибок. Могу если только вечером прислать

**Comment by Roker74** [comment]
Благодарю людей из поддержки кто оказал помощь в решении моей проблемы.
