### ISSUE TITLE
Доверие

### ISSUE THREAD

**Issue by Roker74** [freedomsex/freedomsex#592]
Была оплачена покупка за поднятие анкеты до статуса особенная но сам статус анкеты не изменился . Куда ушли деньги и что делать?

**Comment by tebaly** [comment]
Здравствуйте. Обсуждение проблемы должно быть приватным, так как могут потребоваться данные платежа которые содержат непубличную информацию. Вам нужно связаться с саппортом по почте.
* Мы не занимаемся платежами непосредственно, это делает агрегатор платежей
* В мире не простая ситуация и платежи по карте или в крипте могут обрабатываться долго
* Услуга начисляется только по завершению обработки агрегатором, мы на это повлиять не можем

Если проблема не разрешилась к этому моменту, свяжитесь с поддержкой по почте.

**Comment by Roker74** [comment]
Я вас понимаю но почему тогда оплата всегда происходит на разных людей и с разной суммой? Я сам лично проверял несколько раз при попытке оплаты. Разные номера карт и разные соотвественно люди. И проверка была буквально через минуту

**Comment by tebaly** [comment]
У вас был вопрос "покупка за поднятие анкеты до статуса особенная но сам статус анкеты не изменился" - проблема решилась? Статус поднялся?

**Comment by Roker74** [comment]
Нет статус анкеты не изменился. Оплата была произведена 19.07.2023 в 8:09:10(МСК)

**Comment by tebaly** [comment]
Вы хотите продолжить обсуждение публично? Напишите на почту support@freedosex.net
* в письме укажите емайл который указывали при оплате
* ID анкеты для которой покупали статус
* Если есть чек приложите его к письму

Переписка на ГиТхабе которую вы ведете сейчас ПУБЛИЧНАЯ - все могут её прочитать.

**Comment by Roker74** [comment]
Я пробовал отправить письмо на указанный адрес электронной почты.  Пришел ответ что письмо не может быть доставлено

**Comment by tebaly** [comment]
> support@freedosex.net

Извините, опечатка - support@freedomsex.net

**Comment by Roker74** [comment]
Не доставляется по данному адресу письмо 

Это письмо создано автоматически сервером Mail.ru, отвечать на него не нужно.

К сожалению, Ваше письмо не может быть доставлено одному или нескольким получателям:

  [support@freedomsex.net](mailto:support@freedomsex.net)
    SMTP error from remote mail server after RCPT TO::
    host mail.freedomsex.net [54.37.231.206]: 554 5.7.1 Service unavailable; Helo command [f137.i.mail.ru] blocked using dbl.spamhaus.org; Error:
    open resolver; https://www.spamhaus.org/returnc/pub/51.178.111.240

Рекомендуем Вам проверить корректность указания адресов получателей.

**Comment by tebaly** [comment]
> Не доставляется по данному адресу письмо

Благодарю за сообщение об ошибке. Действительно была также проблема со входящими письмами, dbl.spamhaus.org блокировал доставку. Исправил, проверил, письма приходят.

Отправьте ваше письмо повторно. Приношу извинения за доставленные неудобства.

**Comment by Roker74** [comment]
Письмо отправлено

**Comment by Roker74** [comment]
Благодарю людей из поддержи за решение моей проблемы.
