### ISSUE TITLE
Неполадки с сайтом.

### ISSUE THREAD

**Issue by EvelynTensions** [freedomsex/freedomsex#594]
Господа вы окончательно ушатали сайт? Он стабильно лежит неделю каждый месяц?

Не могу зарегиться на форуме, чтобы про неполадки написать. Не приходит активационная ссылка на почту. Не надо советовать посмотреть в Спаме. С ГитХаба пришёл код за 5 секунд. Да потом еще после входа "здрасте. спасибо что выбрали ГитХаб". Да ещё потом оповещение об ответе от Рокера.
Адрес моей почты и там и там был указан одинаковый.
Сделал акк на ГитХабе - захожу через него на форум пишет - ошибка авторизации.

На фридомсексе в чате не отправляются сообщения с низким доверием. Т.е. почти все кроме приветкакдела - нельзя написать в другой город, на другой возраст, нельзя дать ссылку на мессенджер, нельзя послать картинку, иногда не отсылает сообщения с простыми кавычками без кода.
После ввода кода окно диалога "замораживается" (если фото отправляю) со статусом "отправляю"  на некоторое время, потом его отпускает, но в диалоге ни сообщение ни фото не появляются. Общаться невозможно! Элементарно фотку для знакомства не скинешь.

Девчонка написала мне сообщение час назад, а в анкете у неё показывает, что она была день назад. Кстати написала, что не может отправлять фото.
Теперь ещё в онлайне на всю страну 3-10 женских анкет! И те сваливают через 5 минут, потому что их моментально мужики своими членами закидывают, ибо мужиков на таких сайтах априори больше раз в 10 или 100.

Написал вчера в support@freedomsex.net - ни ответа ни привета.

Вся эта хрень продолжается с 18 июля, последнего обвала сайта.

Если с сайтом 3.14здец, сделайте хоть "плашку" на главных страницах ресурса, что "неполадки и некорректная работа. ведём работы по исправлению" чтобы пользователей не отпугивать. Потому что сайт на самом деле самый норм, а главное простой до безобразия, по сравнению со всяким чпокинг ру, мамбами и прочими притонами проституток.
Что же так рукожопить и рубить его на корню.

Вам никто не пишет про неисправности, потому что внятных контактов нигде нет. То что тут есть форум я вообще узнал месяц назад, а сижу уже год с лишним. Кое как тут нашёл ссылки на саппорт, который не отвечает. Но кто из пользователей FS пойдёт на ГитХаб искать контакты??? Формы "оставить отзыв/задать вопросы" походу такие же мёртвые. Мне никто через них ни разу не ответил.

Пользую десктоп под Вин7про инглиш. Браузер - клон хромиума.
Кэш браузера стирал вчера, кукисы тоже, браузер перзапускал. Поставил пустой ГуглХром, открыл новую анкету - **проблема не решилась.** 
До сбоя всё работало и я у себя ничего не менял. Первым отрубился сервак с загруженными картинками и вместо ярлыков стали отображаться серые квадраты. Потом перестали отсылаться сообщения с кодом, теперь ещё онлайн нулевой.

Вот тема с форума. Я не знаю как и что у Коли решилось, потому что у меня как не работало так и не работает!
![2023-7-23 10-42-23](https://github.com/freedomsex/freedomsex/assets/140303955/986b4d5a-8773-42cb-9be1-53d908c5efc7)

**Comment by Roker74** [comment]
Я тоже уже не знаю как все объяснить и кому. Пишу что все криво работает. Ответ мол это только у меня а еслиб было у остальных тогда бы завалили вопросами. И да это после последнего обвала 18 июля. Уже ни слов не мата не хватает. Либо закрывать сайт совсем либо ремонтировать чтоб все стабильно работало

**Comment by tebaly** [comment]
> это после последнего обвала 18 июля

Именно так. Не поспеваем за технологиями. Столкнулись с неизвестной проблемой. Потребовалось больше времени на ее решение чем можно было ожидать.

**Comment by tebaly** [comment]
> Либо закрывать сайт совсем либо ремонтировать чтоб все стабильно работало

С решением этой проблемы не помогли ни нейросети ни обычный гуглинг. По первоначальной проблеме во всём интернете была только одна страница, которая лишь косвенно указала на проблему, но никакого решения не было. 

В проект нужны люди, которые будут делать и ремонтировать. А таких людей очень мало в принципе. И их прайс на услуги у каждого выше чем весь бюджет проекта. Одно только обслуживание кластера сколько стоит, без учета разработки.

**Comment by tebaly** [comment]
> Я тоже уже не знаю как все объяснить и кому.

Проблема исправлена. Проверьте пожалуйста. Благодарю за сообщение об ошибках.

**Comment by EvelynTensions** [comment]
> > Я тоже уже не знаю как все объяснить и кому.
> 
> Проблема исправлена. Проверьте пожалуйста. Благодарю за сообщение об ошибках.

**upd1** 
17-30 онлайн починили. Остальное, указанное мной, не работает по-прежнему - капча не работает, ссылка с форума с верификацией не приходит.
Сложно показать в статике, надо на экране процесс видеть. Вот пытаюсь дать ник в телеграме, чтобы хоть там пообщаться. "Введите код", ввожу, капча закрывается, текст остаётся в поле ввода, в чате сообщения нет - последнее как было 17-02 так и осталось. а на часах 17-38.
Причём это разговор не одного дня. Мы тут уже практически родными стали, а у меня оказывается всё ещё низкое доверие, чтобы телегу скинуть свою.


![2023-7-23 17-38-3](https://github.com/freedomsex/freedomsex/assets/140303955/a7d2e940-1685-4aeb-90cf-bb2edf2e0366)
![2023-7-23 17-42-7](https://github.com/freedomsex/freedomsex/assets/140303955/ae5602cb-8921-4fd4-b06a-89c6aaad5c5a)
