### ISSUE TITLE
Неполадки с сайтом часть вторая

### ISSUE THREAD

**Issue by EvelynTensions** [freedomsex/freedomsex#595]
Быстро вы кейс закрыли. Хотя кроме онлайна ничего не заработало. Лень перепечатывать. Оставлю ссылку на ответ
https://github.com/freedomsex/freedomsex/issues/594#issuecomment-1646859958
ps
смотрю ошибка регистрации на форуме - тема с февраля висит нерешённая.)

**Comment by Roker74** [comment]
Полностью поддерживаю что кроме как онлайн ни чего не исправлено. После ввода капчи про низкое доверие не уходит сообщение так и остается висеть.

**Comment by EvelynTensions** [comment]
В консоли какие-то баги красным вылетают. Обведённый кусок по-моему исполнился при попытке отправить картинку после ввода капчи.
Да, опредеённо этот фрагмент выполняется после выбора картинки для отправки (ContactIntimate)
Потом после ввода капчи всё остальное.  
POST...............400
Uncaught .............. request failed with code 400
Потом в окне диалога висит несколько секунд статус "отправляю..." В норме в этот момент картинка должна опубликоваться, но этого не происходит.

И когда "отправляю" меняется на "введите текст" выскакивает последняя строка этого куска.
POST ............... 502

**На второй картинке** этот кусок отдельно.

Хотя после обновления страницы по F5 этот фрагмент тоже появляется, но с некоторой задержкой. **На третьей картинке** ошибки после обновления главной страницы. И больше никаких действий.
Сначала появляется три ошибки GET. Потом через некоторое время добавляется POST и Uncaught с кодом 400


![2023-7-23 21-29-41](https://github.com/freedomsex/freedomsex/assets/140303955/9e2e5353-99c7-445b-9ab1-2b202583120d)

![2023-7-23 21-34-12](https://github.com/freedomsex/freedomsex/assets/140303955/e6cef5c7-fefa-4424-8b86-0b1e2cfbb32d)

![2023-7-23 21-46-47](https://github.com/freedomsex/freedomsex/assets/140303955/4df82d61-099a-47ab-be43-6b20e9318688)

**Comment by Roker74** [comment]
я тоже это заметил но я не силен в программировании но есть подозрения что это и есть ошибка и возможно что даже это одна их немногих ошибок

**Comment by EvelynTensions** [comment]
Первые две ошибки GET ..... net::ERR_BLOCKED_BY_CLIENT - эта тема походу из-за АдБлокера который стоит в браузере. При его отключении этих ошибок нет. Но капчу это не исправляет.  В абсолютно девственном Хроме тоже не работает отправка сообщений. Но в нём также с задержкой появляется ошибка с кодом 400

Кроме того АдБлокер стоял у меня и до 18 июля с незопамятных времён, и сайт нормально работал. Ну насколько это можно назвать нормальным.

У Коли видимо решили вопрос с компенсацией денег и статуса. А "отправка не работает!" ))
![2023-7-23 22-20-28](https://github.com/freedomsex/freedomsex/assets/140303955/b981d444-f550-45ab-8974-fccfb7c19814)

**Comment by Roker74** [comment]
Да с компенсацией у меня они решили баг и за это дали VIP но больше ни чего не исправлено и не решено

**Comment by EvelynTensions** [comment]
> Да с компенсацией у меня они решили баг и за это дали VIP но больше ни чего не исправлено и не решено

))) Аааа так Рокер и Коля это одно лицо получается. Я думал это наш третий собрат по несчастью.)

**Comment by Roker74** [comment]
ну да ...... одно ..... не буду же я везде под одним ником.....прячусь однако )))

**Comment by Roker74** [comment]
Незнаю почему но как мне кажется вот тут проблема
![IMG_5792](https://github.com/freedomsex/freedomsex/assets/140086233/695a5ad9-8d35-4b33-bb64-8e422efebce3)

**Comment by EvelynTensions** [comment]
Ещё вот такая ошибка вылетает 502. При попытке отправить картинку.

![2023-7-24 10-49-16](https://github.com/freedomsex/freedomsex/assets/140303955/a6bd6324-03cc-4770-8a1f-ef3d780078b0)
![2023-7-24 18-5-1](https://github.com/freedomsex/freedomsex/assets/140303955/2c9e9b55-ef19-43f1-aecd-ca06f839c237)

**Comment by EvelynTensions** [comment]
Увы. Это не помогло. Сообщения с кодом по-прежнему не отправляются.

Кстати попробовал вводить неверный код. Эффект одинаковый с вводом правильного - после ввода кода, окошко закрывается, и идёт попытка отправить сообщение. Как будто код вообще не распознаётся верный он или нет. Раньше по-моему при вводе неверной комбинации окно не пропадало, а оставалось.



![2023-7-24 22-17-5](https://github.com/freedomsex/freedomsex/assets/140303955/d5f12724-ec52-4243-b310-f7dc83a0c8c7)

**Comment by Roker74** [comment]
Вот ответ с форума сайта

[jonny_don](https://freedomsex.info/u/jonny_don)
[9мин](https://freedomsex.info/t/18-07-23-19-07-23-polozhil-klaster-vse-sajty-byli-nedostupny-paru-dnej/5312/18?u=kolia)
Приношу свои искренние извинения. Благодарю за вашу помощь. Я таки наконец обнаружил проблему. Я ответил только сейчас, так как принимал попытки поскорее исправить проблему и доложить в очередной раз, что всё исправлено. Но в этот раз не получилось. Я работаю над исправлением ситуации. Я мало уделил внимание подробностям описания проблемы, так как сами по себе сообщения отправляются и капча работает. Но не отправляются сообщения вместе с капчей. Проблема глубже чем казалось, так как помимо обновления кластера я изменил некоторые настройки сети и забыл об этих изменениях, а они повлияли на внутреннюю сеть в кластере.

Работаю над восстановлением работоспособности.



посмотрим теперь как быстро решится проблема или еще будет хуже чем было

**Comment by EvelynTensions** [comment]
> Вот ответ с форума сайта
> 
> [jonny_don](https://freedomsex.info/u/jonny_don) [9мин](https://freedomsex.info/t/18-07-23-19-07-23-polozhil-klaster-vse-sajty-byli-nedostupny-paru-dnej/5312/18?u=kolia) Приношу свои искренние извинения. Благодарю за вашу помощь. Я таки наконец обнаружил проблему. Я ответил только сейчас, так как принимал попытки поскорее исправить проблему и доложить в очередной раз, что всё исправлено. Но в этот раз не получилось. Я работаю над исправлением ситуации. Я мало уделил внимание подробностям описания проблемы, так как сами по себе сообщения отправляются и капча работает. Но не отправляются сообщения вместе с капчей. Проблема глубже чем казалось, так как помимо обновления кластера я изменил некоторые настройки сети и забыл об этих изменениях, а они повлияли на внутреннюю сеть в кластере.
> 
> Работаю над восстановлением работоспособности.
> 
> посмотрим теперь как быстро решится проблема или еще будет хуже чем было

О, спасибо за инфу. Остаётся скрестить пальцы.

**Comment by Roker74** [comment]
Да я уже скрестил все что можно. Лишь бы еще хуже не сделали чем было

**Comment by EvelynTensions** [comment]
upd 27,07,2023
Капча заработала. Аплодисменты.

Но ссылка на регистрацию на форуме так и не приходит на почту.

**Comment by Roker74** [comment]
Насчет ссылок вроде было давно написано на форуме сайта что возможность отправки электронной почты отключена для пользователей, не являющихся сотрудниками. Думаю что на это можно забить это не критично.

**Comment by EvelynTensions** [comment]
> Насчет ссылок вроде было давно написано на форуме сайта что возможность отправки электронной почты отключена для пользователей, не являющихся сотрудниками. Думаю что на это можно забить это не критично.

Да есть такая тема в шапке на главной странице форума. Но мне кажется это что-то другое. Иначе как пройти процесс регистрации, который предусматривает получение ссылки по почте?) 

И да, это не критично. Меня больше волновала возможность общения на сайте. Форум мне не так интересен, просто поставить в известность админов, что функция не работает.

**Comment by tebaly** [comment]
Всем спасибо. Продолжу работу на кластере :)

**Comment by Roker74** [comment]
А может не надо больше ни чего трогать пока хоть все работает. А то чувствуется что добром эта работа не кончится
