### ISSUE TITLE
Не прошло и года

### ISSUE THREAD

**Issue by Roker74** [freedomsex/freedomsex#596]
Рано видимо вчера радовался что сайт заработал и удалось хоть немного но пообщаться с девушками. Все же снова fs сломали. Народу онлайн полтора землекопа. Да когда же все это прекратится. Почините чтоб работал сайт и больше не трогайте ни чего. Какие же вы криворукие зла аж не хватает

**Comment by tebaly** [comment]
> Все же снова fs сломали

Оно само :)

**Comment by Roker74** [comment]
Сказки можно рассказывать маленьким детям которые ходят в детский сад. Если все вчера работало и был ответ что продолжаются работы на кластере как само может сломаться??? Явно что что то как обычно пошло не так но признавать что это было конечно не кто не будет

**Comment by tebaly** [comment]
> как обычно пошло не так

Ну хз. Я меняю ноды кластера, а сломался Pod - он в ответственности Kubernetes. И этот под был Stateless - он как минимум должен был презапуститься. Он может и перезапустился, так как был в статусе Running, но перестал скейлиться сам. Тут наши полномочия, всё...

Я уже писал раньше - это обновление серверов вынужденная мера. Я бы их не трогал. Собственник серверов выкатил такие условия, при которых сервера пришлось заменить. Замена сервера в кластере Kubernetes должна быть простой и ненавязчивой, но по факту это так работает только в Amazon или Google Cloud - стоимость размещения сайтов у них переваливает за $3000 - но и аналогичный опыт был, там тоже часто что-то ломается "само". Так ещё и разработчики софта изменили настройку по умолчанию, которая и привела к сбоям. То есть, я эту настройку никогда не трогал, не использовал, и не менял.

В Kubernetes переехали насильно, также с массой сбоев и потерь. Зачем? Потому что старый подход с виртуалками перестал работать. Проект на них престал быть управляемым. Сейчас стало проще. Почему Kubernetes дает сбои - там почти весь софт с меткой "alpha/beta" - что чаще всего интерпретируется как "используйте на свой риск". И вы ещё поищите в интернете, на сколько просто или сложно иметь собственный кластер Kubernetes на голом железе. Почему не Amazon? Потому что бюджет. И всё в целом упирается в бюджет. У нас весь бюджет в два раза меньше зарплаты одного администратора кластера Kubernetes. 

Что добавить?
