### ISSUE TITLE
Техническая поддержка (заминусованные)

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#8]
Убрать отображение нулевых и плюсовых элементов, иначе из за одного плюсового в конце теряется смысл кнопки "Закрыть всё"

**Comment by tebaly** [comment]
Ок. Принято

**Comment by tebaly** [comment]
Давайте добавим фильтр "до нуля" по вкладке "Заминусованные" как вы предлагаете, это внесет ясности и баланса. Спасибо. 

Добавлено
