### ISSUE TITLE
Стоит ли наказывать за предложение знакомства из другого города

### ISSUE THREAD

**Issue by mj4444ru** [freedomsex/freedomsex#82]
"Приветы" из других городов и тому подобное при наличии галочки реал.
Наказывать хотя бы каким то количеством капч при наличии жалобы, пусть и отмеченной как ложное...

**Comment by tebaly** [comment]
> "Приветы" ... Наказывать

Это уже явная цензура и ограничение общения. Делать так не положено. 
* мы не рекомендуем Пользователям писать собеседникам из других городов
* другие Пользователи вправе "влепить" личное воздействие за такое - каптча

Несмотря на "Разрешено" - каптча начисляется. Если нет, то это баг.

**Comment by mj4444ru** [comment]
на сколько мне известно капча не начисляется...  о какой цензуре идёт речь? капча это не цензура...

**Comment by tebaly** [comment]
> на сколько мне известно капча не начисляется... 

> Наказывать хотя бы каким то количеством капч при наличии жалобы, пусть и отмеченной как ложное...

Давайте копать. 
* любое нажатие "наказать и удалить" приводит к начислению капчи собеседнику

**Comment by mj4444ru** [comment]
а потом к списании в случае признания ложной... не так?

**Comment by tebaly** [comment]
3.2. Прямое воздействие участники Сообщества осуществляют на собеседника лично, во время переписки, путем подачи жалобы и наказания собеседника за сообщение неприемлемого содержания; 
3.3. Оценку содержания сообщения собеседника, соответствия действий собеседника правилам Сайта и определение их как нарушения, участниками Сообщества производится добровольно; 
3.4. Личные воздействия участников Сообщества **не отменяются**, не осуждаются, **не обсуждаются и не контролируются**. Данный пункт не распространяется на действия Нарушителей, чьи воздействия могут быть отменены, обнулены, отвергнуты или обесценены;

**Comment by tebaly** [comment]
Нет такого понятия "ложная" 
* есть крайность как: флуд, ddos
* в таких случаях "пункт не распространяется на действия"

**Comment by tebaly** [comment]
Полагаю что стоит.
