### ISSUE TITLE
Способ монетизации проекта

### ISSUE THREAD

**Issue by tebaly** [freedomsex/freedomsex#99]
Может быть выделить способы монетизации в отдельную ветку? Может быть кто-то что-то предложит. Пара идей есть, но они сырые, но я бы попробовал их развить... Только не за 5 минут. Но возможно какой то вариант мозгового штурма 2-4 могзгов )

**Comment by tebaly** [comment]
Варианты
* Реклама
* Пожертвования, сборы
* Платные сервисы, подписка

**Comment by tebaly** [comment]
Планы
* Некоторые _сервисы_ модерирования с оплатой - половина администраторам
* Продавать кредиты доверия

Этого не будет
* Вип анкеты
* Платное общение
* Подписка за доступ

**Comment by Fenslau** [comment]
Основная моя идея была в том, чтобы ввести некую виртуальную валюту. Пусть даже как то увязать ее с кредитами доверия. Или же придумать новую. Пользователь сам должен хотеть купить её. Для этого нужно придумать, на что бы ее можно было потратить. На счет платных сервисов, даже не знаю, что это может быть...
Может быть сделать подраздельчик, в котором пользователи, которые сидят скучают, в перерывах между общением смогли бы как-то в процессе какой то общей деятельности эти кредиты тратить?
Может какая-нибудь текстовая игра? Мафия, Викторина, Рулетка? Причем можно сделать, чтобы кредиты можно было бы и зарабатывать в каждой из этих игр. Пользователи будут туда стремиться и обороты кредитов возрастут.

**Comment by Fenslau** [comment]
Просохатил свои кредиты, ушел в минус даже, новая анкета новых не даст. А у тебя тут вроде даже какие то контакты есть. Капчу вводить лень. Думаешь, а.. полтинник не жалко. И понеслась. 
Тем более здесь контингент постарше. Уж если на другом проекте удавалось на этом зарабатывать, где онлайн был 1000 максимум и состоял в основном из студентов, то тут то уж сам бог велел. 
Можно всё это дело подкрепить желанием пользователей сохранять и холить свои анкеты. чтобы они росли так сказать и это тоже как то бы было для них приятно (если это конечно не противоречит вашей политике "пришел, познакомился за пару дней и забыл".

**Comment by Fenslau** [comment]
В принципе, хотя такие игры давно известны и много где есть, сколько я видел - реализованно отвратительно! Минималистический концепт сайта позволил бы сделать всё очень красиво, понятно и главное интересно. Пользователи бы должны подсесть. Как их замотивировать идеи есть. Есть так же общее представление о мафии предлагаемой, на уровне проработки ролей и их функций и алгоритме действий. Это не та мафия, которая с этих всяких там ОК и прочих сайтиках, неее! Это гораздо более продуманная и интересная ролевушка. С интересными нестандартными ролями. Такого нигде сейчас нет (надо конечно проверить на всякий случай), а где было, там уже не будет никогда. А главное, что можно реализовать всё на простейшем текстовом интерфейсе в виде чата. Если заинтересует, готов все подробно рассказать и поучаствовать в реализации задумки. Смысл этих игр не только в трате кредитов, но и в вовлечение пользователей в общение, а так же стимуляции большего онлайна и его наращивании. Такие игры возбуждают интерес пользователей друг к другу, способствуют возникновению связей, разного рода переживаний, азарта.

**Comment by inquisitor6789** [comment]
что касается купли-продажи кредитов, то идея вполне здравая. Только для начала надо пользователю начать показывать сколько у него кредитов и на что они списываются.

Кредиты можно будет продавать и покупать на "бирже". Не обязательно в какой-то игре. Хотя игра с точки зрения привлечения и удержания клиента выглядит более симпатичной.

**Comment by Fenslau** [comment]
Из игр еще можно реализовать "Любовь с первого клика". Принцип прост - один подчатик для этой игры, там пользователи регаются. Потом выбираются три парня, три девушки. И они между собою играют во все нам известные три вопроса-три ответа и кто кому понравится. Цель - придумать творческий интересный вопрос и ответить с юмором на вопрос девушки. далее развитие игры по этой же схеме. три раунда. пользователи отвечают анонимно боту на вопросы, которые девушки задают им троим. отвечает каждый, Потом совпавшая пара получает приз) ну все это знают. Опять таки - можно все подробно расписать и добавить интересностей. 
Как это можно поставить на кредит? - да было бы желание. Главное, что это все повышает онлайн. и заставляет оставаться на сайте. Если на полупертвой ИРКЕ в это играли еще два года назад, то здесь то уж точно попрет.

**Comment by inquisitor6789** [comment]
небольшая ремарка - если будем реализовывать что-то вроде игрушек, то надо сделать их без флеша. Иначе потеряем пользователей мобильных устройств.
В идеале конечно бы и видеочат переделать на html5, но это не к спеху.

**Comment by Fenslau** [comment]
Никакого флеша!!! Флеш - зло. только текст. Весь игровой процесс только текстом и никак иначе! Это можно. Это работало и сможет работать здесь! Я уверен. Мне только нужна поддержка и одобрение. В принципе, если разработчики идею примут, но решат ее реализовывать сами, без подсказок - ничуть не обижусь. Если потребуются подсказки - с удовольствием подскажу, только не в рамках кода. В пхп я ноль. Да собственно, как и в остальном. Просто доводилось доводить что-то до ума на с++, немного знаю скрипты ирк, хотя они уже давно никому не нужны. Что готов предложить? В случае принятия положительного решения по внедрению игр - участие в алгоритмизации и нюансах. Поделюсь историей развития той или иной текстовой игры, скажу какие ошибки были и почему она умерла. Маловато, но к сожалению, пока так.

**Comment by mj4444ru** [comment]
- Реклама - Видимо того что есть не хватает, а больше не стоит, смысла не будет...
- Пожертвования, сборы - Обычно не особо прибыльный, но точно приносящий доход способ...
- Платные сервисы, подписка - Самое реальное... но надо много думать...

**Comment by mj4444ru** [comment]
- Некоторые сервисы модерирования с оплатой - никто не будет платить...
- Продавать кредиты доверия - никто не будет покупать...

на бирже капчевбивателей цены от 1$ за 1000 капч

**Comment by mj4444ru** [comment]
- Игры - люди тут не для игр
- что касается купли-продажи кредитов - у нас тут биржа?

это всё пройденные этапы, людям очень быстро это всё надоедает...

такое впечатление что дети тут собрались...
ни одной здравой идеи...

**Comment by mj4444ru** [comment]
если вы хотите обсуждать эту тему, надо немного статистики.

1. сколько у нас постоянных посетителей.

2. сколько у нас однодневных посетителей.

3. сколько посетителей задерживаються на неделю.

**Comment by mj4444ru** [comment]
Основная цель - это знакомства и сервисы прежде всего должны способствовать знакомству, а не игрушкам...

теперь о том что может быть полезно:

- верификация аккаунта
- отправка прямых сообщений на сотовый телефон
- получение уведомлений о новых сообщениях
- получения уведомления о новых пользователях
- получение уведомления о том что пользователь зашёл на сайт

уведомления можно получать посредством email, смс, телеграмм, ватсап... можно отвечать в ватсапе, телеграмме, смс...

**Comment by Fenslau** [comment]
Социальные игры _еще как_ способствуют знакомствам, это я точно знаю. А главное они увеличат онлайн. Некоторые будут заходить ради знакомства, а потом уже просто сидеть ради другого функционала.
Все перечисленные сервисы может и помогут какую-то копейку монетизировать, но никак не расширят онлайн. Нужно чтобы пользователь оставался здесь, хотя бы еще на несколько дней, если у него не получилось с первого раза познакомиться. А там, возможно, оглядевшись, он останется навсегда.
Кредиты обязательно будут покупать в том случае, если их можно будет еще куда нибудь и с удовольствием потратить. Также необходимо, чтобы их можно было и заработать в небольших количествах. Я сейчас пересказываю уже организованную схему, которая работала, поэтому некоторая уверенность у меня есть.

**Comment by tebaly** [comment]
> на бирже капчевбивателей цены от 1$ за 1000 капч

Это приблизительный ценник за 1000 кредитов. Обсуждается

> Продавать кредиты доверия - никто не будет покупать...

Если покупать будут - уже хорошо :)

**Comment by inquisitor6789** [comment]
> верификация аккаунта

предложите механизм кроме емайла. Сейчас крыжик в анкете если емайл подтвержден поставить не проблема

> отправка прямых сообщений на сотовый телефон

платный сервис

> получение уведомлений о новых сообщениях

судя по документам это когда-то было или планировалось к реализации

> получения уведомления о новых пользователях

вроде сейчас есть в виде фрейма справа

> получение уведомления о том что пользователь зашёл на сайт

если только для пользователей из списка "избранное". Иначе очень их много будет...

> уведомления можно получать посредством email, смс, телеграмм, ватсап... можно отвечать в ватсапе, телеграмме, смс...

смс платные. не забывайте об этом. Остальные сервисы наверно тоже захотят денюжку (кроме емайла)

**Comment by Fenslau** [comment]
на бирже капчевбивателей цены от 1$ за 1000 капч
Это приблизительный ценник за 1000 кредитов. Обсуждается
Как покупать и использовать капчу - знают не все. Наоборот, такую цену ставить нельзя, зачем нам спамщики? Пусть покупают свою капчу на стороне. Всеравно они будут все в топе.
Кредиты должны стоить дороже гораздо. Потому что для обычного юзера они ценнее.
В том проекте, который я упоминал, кредиты вообще были почти ненужны! Но их покупали! Более или менее с умом их можно было потратить только в текстовой рулетке. И народ покупал их. И тратил. А кто не хотел покупать - мучались, зарабатывали, но всеравно в итоге все спускали туда.
Причем это была вообще _далеко не основная_ функция того проекта - так, от нечего делать написали.

**Comment by mj4444ru** [comment]
Сергей, мыслите шире...
понятно что платные сервисы, мы то как раз и обсуждаем платный премиальный сервис...
не у всех есть желание сидеть тут всё время, а получить уведомление о новом сообщении в смс это весьма полезный сервис...

думайте не о том как денег содрать, а как сделать качественную услугу, которая будет нужна, за которую люди сами захотят платить...

Хотя вот в моём городе девушек которые тут сидят, можно по пальца пересчитать и я вообще не понимаю чем можно удержать людей тут...

Человек ищет секс знакомства, поиграться он и в контакте может...

Не надо смотреть на другие успешные проекты... Там другая ситуация, другие вложения, другой уровень...

**Comment by tebaly** [comment]
> получить уведомление о новом сообщении в смс это весьма полезный сервис...
думайте не о том как денег содрать, а как сделать качественную услугу, которая будет нужна, за которую люди сами захотят платить...

Я верю в то, что мы запустим мобильное приложение. Там уведоиления это обычное дело и СМС не нужно

**Comment by tebaly** [comment]
> Как покупать и использовать капчу - знают не все. Наоборот, такую цену ставить нельзя, зачем нам спамщики? Пусть покупают свою капчу на стороне. Всеравно они будут все в топе.
Кредиты должны стоить дороже гораздо. Потому что для обычного юзера они ценнее.

Сделаем так, что узнают все - это просто. По цене это минимум, возможно 1$ и за 500 и за 300. Спам не пройдёт - это же видно. Мы с вами на спамерах только заработаем - можно перечислять "оплаченные кредиты" в счёт модераторов(деньги в смысле), заблокировавших попытку такого спама, например.

**Comment by mj4444ru** [comment]
мобильное приложение можно сделать платным со второго месяца... 30-300 руб в месяц в зависимости от активности пользователя...
справедливо для тех кто сидит иногда, сумма 30 руб это допустимо...
для задротов которые тут живут, 300 руб тоже не деньги...

**Comment by Fenslau** [comment]
Смотрите. Я понимаю, что к моим идеям доверия нет и мои идеи кажутся неправдаподобными. Но я же это видел. Попробую сжато ответить на все замечания к моему тексту:
_Человек ищет секс знакомства, поиграться он и в контакте может..._
Да. Но там это реализовано просто отвратительно! И нигде не реализованно на данный момент так, как я предлагаю (я про мафию). Да, игра сложная в разработке. Но она экстра повышает социальность и онлайн тоже. Я бы на месте разработчиков не стал бы начинать с нее, потому что там работы просто тьма. Но игра хорошая. Оставим это на потом, когда будет реализованно что-то другое. 
_Не надо смотреть на другие успешные проекты... Там другая ситуация, другие вложения, другой уровень..._
Я как раз говорю о минимальных вложениях. Я описываю ситуацию давнишнюю. Когда то давно было это реализовано, но сам проект загнулся, и эта идея вместе с ним. И она была успешно повторена через несколько лет, уже после внедрения всех этих контактиков. Причем на ИРЦ, который был уже тогда мертв чуть менее чем полностью.
_ возможно 1$ и за 500 и за 300. _
Чуть чуть дороже. Кредиты должны быть обеспечены. и будут. А то что они их будут тратить на другое, кроме капчи  - это наша задача. Я повторюсь, обычные пользователи, у которых есть немного кредитов, должны тоже иметь возможность их приятно потратить. И чтобы можно было их как бы и не покупать так то. Вот тогда их покупать как раз и будут.
1 кредит = 1 рубль (предложение). Но это все обсудим после.

Давайте проанализируем ситуацию. Я помню, что mj4444ru просил статистику. Я присоединяюсь к просьбе. Нужна статистика по онлайну, который есть сейчас. И по новым пользователям. и по тем, которые заходят каждый день. Сколько тех и этих? Примерно хотя бы. Каков онлайн реальный в данный момент?
От этого многое зависит. 

Что еще сказать. Я готов более подробно все рассказать, что знаю о том, что предлагаю, любому, кто заинтересован в развитии проекта. Здесь одним сообщением все не опишешь - факт. По недоверию я вижу это. Если мои идеи не нравятся, то предлагайте свои, какая проблема. Я знаю только одно и предлагаю некоторый итог подвести (промежуточный):
+у меня есть несколько идей, которые могут принести дополнительный онлайн и на которые пользователи смогут тратить кредиты.
+я представляю, какие цены могут быть на эти кредиты. Сам я их ни разу не покупал (в том проекте), так как недостатка в них не было, но видел _сколько_ покупают. При онлайне до 1000/день, при том студентов в основном.
+нам нужно сосредоточить усилия одновременно на двух вещах: повышение онлайна и повышения оборотов кредитов, нельзя вводить кредиты платные до того, как их можно будет тратить и мы поймем, что пользователи этого хотят. Они сами должны хотеть! купить эти кредиты. Иначе не навяжешь, как ни старайся. Они им должны быть нужны просто ппц как. То есть пользователь должен практически задавать вопрос Юлии: как купить кредиты? Примерно так.Иначе - это всё не то.
+Должна быть возможность заработать кредиты здесь. хотя бы немного. Это тоже повышает онлайн кстати ))) _без этого покупать кредиты не будут!!!_ А вот с Этим - как раз наоборот. Ценность кредитов должна быть.
Я предлагаю игры, это да. Некоторые просты в реализации, некоторые более сложны. Но! Почему предлагаю: каждая из них повышает онлайн, заставляет пользователя остаться. Причем мы не навязываем. Будет просто ссылка наверху, типа "Скучно?" - нажимаешь - раскрывается она на три-4 ссылки, юзер выбирает игру и вовлекается в нее.Да, да, да, запуск будет непростой, хотя смотря с какой игры начать. У меня есть некоторые задумки на этот счет. Как я считаю, неплохие.
+Те, кто приходит на проект только для знакомства, даже не увидят особо этой ссылки. И основной идее сайта это не помешает.

**Comment by mj4444ru** [comment]
https://yandex.ru/search/?text=%D0%BC%D0%B0%D1%84%D0%B8%D1%8F%20%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD&clid=1955453&win=169

С мафией опоздали...

Тут бесплатно люди не сидят, а вы про деньги...

250 человек сейчас онлайн...

**Comment by inquisitor6789** [comment]
> Тут бесплатно люди не сидят, а вы про деньги...

насколько я понял, то фишка этих проектов именно в игре. Много ли вы знаете задротов, кто без мафии жить не может. В нашем же случае, игры это будет побочный продукт. Так сказать, время убить. Если выстрелит и на играх будут сидеть хотя бы 1% посетителей, то отлично. Если нет, то значит нет потребности.

Со своей стороны могу предложить следующие варианты игрушек (простые как 3 копейки):
- чет/нечет (что-то типа рулетки если ставить на красное/черное)
- камень-ножницы-бумага

**Comment by Fenslau** [comment]
Нет, нет, ничего не опоздали. И не опоздаем никогда. Та версия, что я предлагал, скорее всего не будет реализована никем. Тем более в таком простом и понятном текстовом интерфейсе. Так что к ней можно будет вернуться в любой момент позже. А пока добавить чего-то простого, что можно написать за несколько дней. Тут всё дело в фишке! Увязка кредитов доверия и игровых кредитов. Именно тот факт, что можно непринужденно их потратить в перерывах между знакомствами, должен понравиться пользователю и стимулировать его на покупку новых. Если пользователи будут играть друг с другом и кредиты будут перетекать туда-сюда, это тоже должно стимулировать. Появятся те, кто захочет отыграться, появятся те,кто захочет всем показать, что у него этих кредитов много. Рулетка - хороший способ регулярно избавлять народ от излишка кредитов. Камень-ножницы - тоже хорошо. Пусть играют друг с другом на кредиты. ЛПК - как раз знакомствам способствует, да и пусть бы парни немного фантазию развили, вместо того чтоб писать одно и то же всем подряд. 
Ну и плюс стимулирующие штучки - дополнительные кредиты топовым покупателям, возможно какие-то дополнительные статусы в анкете зелененьким писать (какие - можно придумать, для лидеров топа игр).

**Comment by inquisitor6789** [comment]
> возможно какие-то дополнительные статусы в анкете зелененьким писать (какие - можно придумать, для лидеров топа игр).

тут для начала могут подойти ачивки на подобии "я играю в...". Или "я одержал N побед в..."
Они должны отображаться где-то рядом с сетевым статусом (онлайн/оффлайн)

**Comment by inquisitor6789** [comment]
еще, как вариант,  можно раздавать кредиты за клик на баннере раз в N минут. Скажем 10 кредитов за клик. Правда я не уверен, что это может принести какую-то существенную прибыль, но в инете faucets (краны) процветают. Отсюда можно сделать вывод, что они как минимум окупаются.

**Comment by mj4444ru** [comment]
спорим что ничего из вышесказанного не приживётся?

вы ещё казино тут откройте, с покером, рулетками, тотализаторами и ставками... и вообще закроют за незаконную деятельность...

**Comment by inquisitor6789** [comment]
> спорим что ничего из вышесказанного не приживётся?

есть другие предложения? Только те, которые 100% приживуться
я смотрю вы тут платное моб приложение предлагали.... как думаете, при бесплатном сайте это взлетит?

**Comment by mj4444ru** [comment]
Есть определённые вещи за которые люди будут готовы платить. И не важно как это будет реализовано, с помощью мобильного приложения, с помощью смс и т.д...

**Comment by Fenslau** [comment]
В том проекте, с которого я беру идеи было реализовано так. Сначала было прост общение. У каждого пользователя был "уровень". Который давался через голосовку админами. Первые уровни получались автоматически - после набития статистики по сообщениям и времени. А следующие - через голосовку, причем админы смотрели, не искусственно ли набита эта стата. Эта система уровней здорово стимулировала пользователей. Они дорожили своими аккаунтами и старались их развить. Потом была введена игра викторина. Появились кредиты. За каждый правильный ответ давался 1 кредит. Но тратить их было решительно некуда. Тем не менее, народ их копил и немножко хвастался. Затем была введена мафия. Тут можно было как заработать кредиты, так и потерять их, (обычно только если тупишь безбожно). Далее за кредиты стало возможно покупать начальные уровни. Так длилось довольно долго. А потом ввели рулетку и сделали возможность покупки кредитов. Итог - 80ооо/месяц с преимущественно студенческого проекта. По ценам 2005 г. При онлайне 600 человек. При чем проект был чисто внутригородским. Из остальной России там практически никто не сидел.
Я сам тогда не верил, что эти кредиты будет кто-то покупать... Потому что они ничем почти не были обеспечены, ничего на них толком нельзя было купить. А если побольше идей реализовать, как тратить кредиты, мне кажется, пользователь будет _сам_ рад их купить. Можно сначала создать небольшой их дефицит, повременив с началом продаж, но введя фишки.

**Comment by inquisitor6789** [comment]
> Есть определённые вещи за которые люди будут готовы платить

какие же это вещи? поделитесь тайным знанием. Кроме критики в этом топике от вас ничего не слышно. Где конструктивные предложения? :-)

**Comment by mj4444ru** [comment]
я приводил примеры за что бы я платил...

**Comment by Fenslau** [comment]
Запросил бы я такую статистику: Сколько таких, кто пришел, просидел 2-3 дня и потом ушел. То есть анкете n дней. был последний раз (дата регистрации + 1,2,3 дня). Где n < 14. За последнии пару недель. Это те, кого можно было бы удержать фишками.

**Comment by mj4444ru** [comment]
может тысяч 50

**Comment by Fenslau** [comment]
Возможны какие-то конкурсы. С ачивками победителям (это пока не монетизация, но стремится к тому, скажем так, втягивает пользователей в лояльность к сайту), некоторые из этих ачивок можно автоматизировать, некоторые возможно только по результатом ненавязчивых "лайков" или чего-то такого. Например, я иногда читаю в жалобах и вижу, что-то оригинальное. Написано отлично, но почему-то попало туда. А сколько таких сообщений всего - очень много! Их можно все как то вовлечь в эту круговерть, чтоб было веселее и интереснее.
*самое оригинальное начало знакомства;
*самый оригинальный отказ девушки на предложение чего либо;
*Мисс терпеливость (отвечает корректно на кучу доставаний/предложений от одного и того же)(сыро, но тоже потом можно, если эти все приколюшки пройдут);
*Мисс отзывчивость (отвечает на почти все сообщения, даже отказом, но поясняя, почему) (то же самое);
*Добропорядочный Сэр, который пишет только по формату анкеты - ни разу не написал никому, чья анкета не соответствует его желаниям (после достаточной статистики);
*Мастер общения (тот, кому отвечают почти все с первого же сообщения и продолжают диалог после)
можно придумать и еще, если желание будет и мысль поддержат.
А ради шутки ввести и "негативные" ачивки:
*Мистер "проще дать, чем ответить" - который пишет одним и тем же, пока не добьется ответа хоть какого нибудь.
...

**Comment by fenixnoir** [comment]
А как вам вариант платного расширенного поиска? У мамбы такой был, для випов (может и сейчас есть). Покупаешь "Мастер поиска" на сутки, неделю, месяц, и ищешь по росту, весу, телосложению, совпадению желаний, по имени наконец... А для завлечения предоставлять 1 раз в сутки бесплатно.
Платные уведомления на телефон тоже мысль, чуть дороже чем сами платить будем, тогда в ноль или минус не уйдем. А бонусом на анкету можно ставить галочку "Реальный номер"...

**Comment by NeverovI** [comment]
Вроде как концепция сайта зашел - познакомился - ушел. О какой ценнлсти анкет может идти речь? 90% если слетают печеньки просто заново заполнят анкету. О каких играх, если активные анкеты с давнем сроком регистрации рассматриваются с особой осторожностью? Для монетизации нужно менять концепцию. Пора уже признать, что львиная доля тут дрочеров. На халявку вздрочнуть на порно можно, но нет контакта. Можно сходить на видеодевочку, но для кого-то дорого, а кто-то выше этого. На мамбе лица не мняются десятилетиями, вконтактике нужен реальныйконтакт. Так они сливаются сюда, где написано "знакомства для секса", свято считая, что здесь они его обретут. Что им можно предложить? Платные знаки внимания: от открыток, до каких-нибудь фичь расширяющих функционал профиля девушки. Ведь цель дрочеров, что бы им ответили, а не следить за пустым статусом своих сообщений. Так скатываемся в соц сеть. Но тут или деньги или уникальность концепта. Подписки, оповещения это все классно, но понт дороже удобств
А для игры проще сделать свой ресурс, который можно просто пиарить с фридома.

**Comment by tebaly** [comment]
будем скатываться до free-to-play с платными дополнительными опциями
